doc: update SCMP spec
scionproto/scion pull request #3861
Opened 2020-09-01 10:22 UTC by sgmonroy

Introduce error code to differentiate between unknown ingress and egress
interface, where the pointer is the offset to the hop field.

2020-09-01 10:33 UTC, Oncilla approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3861#-:-MG8DV27E_Q9_6m3l-2Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker and @shitz)



<!-- Sent from Reviewable.io -->

2020-09-01 13:01 UTC, lukedirtwalker requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3861)* status: all files reviewed, 2 unresolved discussions (waiting on @sgmonroy and @shitz)

___
*[doc/protocols/scmp.rst, line 299 at r1](https://reviewable.io/reviews/scionproto/scion/3861#-MG8kLrN1ySztR99a6hc:-MG8kLrN1ySztR99a6hd:b-ft3p47) ([raw file](https://github.com/scionproto/scion/blob/fe1abd2a28147e3967a0af8a45a3c08b9aa42b79/doc/protocols/scmp.rst#L299)):*
> ```reStructuredText
> |              |                                                               |
> |              | 48 - Invalid path                                         |br||
> |              | 49 - Unknown hop field ingress interface                  |br||
> ```

that's in construction direction right? Maybe we should add some comment to clarify this?
___
*[doc/protocols/scmp.rst, line 337 at r1](https://reviewable.io/reviews/scionproto/scion/3861#-MG8kGlp-dKAvCqVeY8_:-MG8kGlq3j2Br_H39WDR:b9fe3i8) ([raw file](https://github.com/scionproto/scion/blob/fe1abd2a28147e3967a0af8a45a3c08b9aa42b79/doc/protocols/scmp.rst#L337)):*
> ```
> 52
> ```
also 53 here?


<!-- Sent from Reviewable.io -->

2020-09-02 10:13 UTC, sgmonroy reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3861)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @shitz)

___
*[doc/protocols/scmp.rst, line 337 at r1](https://reviewable.io/reviews/scionproto/scion/3861#-MG8kGlp-dKAvCqVeY8_:-MGDIWLZCs7tyG0UBacZ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fe1abd2a28147e3967a0af8a45a3c08b9aa42b79/doc/protocols/scmp.rst#L337)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> 52
> ```
also 53 here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-02 10:14 UTC, sgmonroy reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3861)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker, @Oncilla, and @shitz)

___
*[doc/protocols/scmp.rst, line 299 at r1](https://reviewable.io/reviews/scionproto/scion/3861#-MG8kLrN1ySztR99a6hc:-MGDIk_ABRY6avICztDP:b-896fjx) ([raw file](https://github.com/scionproto/scion/blob/fe1abd2a28147e3967a0af8a45a3c08b9aa42b79/doc/protocols/scmp.rst#L299)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

that's in construction direction right? Maybe we should add some comment to clarify this?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2020-09-02 10:33 UTC, lukedirtwalker approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3861)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @shitz)



<!-- Sent from Reviewable.io -->

2020-09-02 11:01 UTC, merged