topogen: create flatter gen/ structure
scionproto/scion pull request #3877
Opened 2020-09-16 07:58 UTC by matzf

Make the `gen/` directory structure flatter to make it easier to navigate. Avoid the replication of `topology.json`, certs, keys etc. in per-service configuration subdirectories, to allow straight-forward manipulation of e.g. the topology configuration.

### Why?
The flatter hierarchy is simpler to navigate and easier to manipulate as there are no replicated configuration files to worry about.
For these reasons, I would like to adopt this flatter configuration tree for the configuration that we generate from SCIONLab (installed in `/etc/scion`). Technically, this is unrelated to whether or not this PR is merged. However, to avoid users/developers having to worry about two slightly different configuration setups, it would be great to change adapt this "upstream" setup here too.

### Before
Before the change, the (relevant parts of the) `gen/` directory hierarchy looked like this:
```
gen
├── dispatcher/
├── ISD1
│   ├── ASff00_0_110
│   │   ├── br1-ff00_0_110-1
│   │   │   ├── br.toml
│   │   │   ├── certs/
│   │   │   ├── crypto/
│   │   │   ├── keys/
│   │   │   ├── supervisord.conf
│   │   │   └── topology.json
│   │   ├── br1-ff00_0_110-2
│   │   │   ├── br.toml
│   │   │   ├── certs/
│   │   │   ├── crypto/
│   │   │   ├── keys/
│   │   │   ├── supervisord.conf
│   │   │   └── topology.json
│   │   ├── certs/
│   │   ├── crypto/
│   │   ├── cs1-ff00_0_110-1
│   │   │   ├── certs/
│   │   │   ├── crypto/
│   │   │   ├── cs.toml
│   │   │   ├── keys/
│   │   │   ├── supervisord.conf
│   │   │   └── topology.json
│   │   ├── endhost
│   │   │   ├── certs/
│   │   │   ├── crypto/
│   │   │   ├── keys/
│   │   │   ├── sd.toml
│   │   │   └── topology.json
│   │   ├── keys/
│   │   ├── prometheus/
│   │   ├── prometheus.yml
│   │   └── supervisord.conf
│   ├── ASff00_0_.../
│   ├── ASff00_0_.../
│   └── trcs
│       └── ISD1-B1-S1.trc
├── ...
```

### After
```
gen
├── dispatcher/
├── ASff00_0_110
│   ├── certs/
│   ├── crypto/
│   ├── keys/
│   ├── br1-ff00_0_110-1.toml
│   ├── br1-ff00_0_110-2.toml
│   ├── cs1-ff00_0_110-1.toml
│   ├── sd.toml
│   ├── prometheus/
│   ├── prometheus.yml
│   ├── supervisord-br1-ff00_0_110-1.conf
│   ├── supervisord-br1-ff00_0_110-2.conf
│   ├── supervisord-cs1-ff00_0_110-1.conf
│   ├── supervisord.conf
│   └── topology.json
├── ASff00_0_.../
├── ASff00_0_.../
├── ISD1
│   └── trcs
│       └── ISD1-B1-S1.trc
├── ...
```

--- 
Still TODO:
* [x] update the testcrypto generation to avoid creating the old ISD/AS structure
* [ ] maybe combine supervisord.conf files into a single file per AS.
* [ ] check how this affects the docker setup

2020-09-16 13:00 UTC, mlegner commented
For me as an infrequent user of SCIONLab and someone demonstrating this to students etc. from time to time, this makes a lot of sense. In the past I ran into the issue of replicated topology files multiple times and usually came up with some error-prone ad-hoc solution copying files or creating symlinks.

2020-09-28 12:13 UTC, Oncilla requested changes
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3877)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf)

___
*[docker/BUILD.bazel, line 44 at r1](https://reviewable.io/reviews/scionproto/scion/3877#-MIJYMxg3QH7XEdV9RF6:-MIJYMxhBIjervGLRXF_:b-swmd65) ([raw file](https://github.com/scionproto/scion/blob/59998d71151eb80d29210fdb0640f017f941a58f/docker/BUILD.bazel#L44)):*
> ```Starlark
>     entrypoint = [
>         "/app/border",
>         "--config",
> ```

This changes behavior and should be documented in the PR description.

Alternatively,  I think a cmd + entrypoint combo would be nicer to work with:

By default still run with `/app/x --config /share/conf/x.toml`, but let the user override the command if they want to:

```
diff --git a/docker/BUILD.bazel b/docker/BUILD.bazel
index 2c5e850b3..ec3366b1e 100644
--- a/docker/BUILD.bazel
+++ b/docker/BUILD.bazel
@@ -41,11 +41,11 @@ scion_app_images(
     name = "border",
     appdir = "/app",
     binary = "//go/border:border",
-    entrypoint = [
-        "/app/border",
+    cmd = [
         "--config",
         "/share/conf/br.toml",
     ],
+    entrypoint = ["/app/border"],
     workdir = "/share",
 )
 
diff --git a/docker/caps.bzl b/docker/caps.bzl
index 3f657a94d..0bac15dae 100644
--- a/docker/caps.bzl
+++ b/docker/caps.bzl
@@ -147,11 +147,12 @@ setcap = rule(
 )
 
 # same as container_image, except that it allows to set capabilities on one binary
-def container_image_setcap(name, entrypoint, caps_binary = None, caps = None, **kwargs):
+def container_image_setcap(name, entrypoint, cmd = None, caps_binary = None, caps = None, **kwargs):
     if not caps:
         # Fast path. If no caps are to be set, skip the setcap dance.
         container_image(
             name = name,
+            cmd = cmd,
             entrypoint = entrypoint,
             visibility = ["//visibility:public"],
             **kwargs
@@ -159,6 +160,7 @@ def container_image_setcap(name, entrypoint, caps_binary = None, caps = None, **
     else:
         container_image(
             name = name + "_nocap",
+            cmd = cmd,
             entrypoint = entrypoint,
             **kwargs
         )
@@ -171,6 +173,7 @@ def container_image_setcap(name, entrypoint, caps_binary = None, caps = None, **
         container_image(
             name = name,
             base = name + "_withcap.tar",
+            cmd = cmd,
             entrypoint = entrypoint,
             visibility = ["//visibility:public"],
         )
diff --git a/docker/scion_app.bzl b/docker/scion_app.bzl
index d3bec2584..1701b8546 100644
--- a/docker/scion_app.bzl
+++ b/docker/scion_app.bzl
@@ -48,7 +48,7 @@ def scion_app_base():
 #   workdir - working directory
 #   entrypoint - a list of strings that add up to the command line
 #   caps - capabilities to set on the binary
-def scion_app_images(name, binary, appdir, workdir, entrypoint, caps = None):
+def scion_app_images(name, binary, appdir, workdir, entrypoint, cmd = None, caps = None):
     pkg_tar(
         name = "%s_docker_files" % name,
         srcs = [binary],
@@ -61,6 +61,7 @@ def scion_app_images(name, binary, appdir, workdir, entrypoint, caps = None):
         base = "//docker:app_base",
         tars = [":%s_docker_files" % name],
         workdir = workdir,
+        cmd = cmd,
         entrypoint = entrypoint,
         caps_binary = "%s/%s" % (appdir, name),
         caps = caps,
@@ -71,6 +72,7 @@ def scion_app_images(name, binary, appdir, workdir, entrypoint, caps = None):
         base = "//docker:app_base_debug",
         tars = [":%s_docker_files" % name],
         workdir = workdir,
+        cmd = cmd,
         entrypoint = entrypoint,
         caps_binary = "%s/%s" % (appdir, name),
         caps = caps,
```
___
*[go/scion-pki/testcrypto/testcrypto.go, line 529 at r1](https://reviewable.io/reviews/scionproto/scion/3877#-MIJZmjmEcw79BOowKdh:-MIJZmjmEcw79BOowKdi:b-qma04r) ([raw file](https://github.com/scionproto/scion/blob/59998d71151eb80d29210fdb0640f017f941a58f/go/scion-pki/testcrypto/testcrypto.go#L529)):*
> ```Go
> 		}
> 	}
> 	pems, err := filepath.Glob(fmt.Sprintf("%s/ISD*/AS*/crypto/*/ISD*-AS*.pem", out))
> ```

For internal tooling, we need to have the `ISD*/AS*` structure of test crypto.
Please make this configurable via a flag
___
*[python/topology/topo.py, line 365 at r1](https://reviewable.io/reviews/scionproto/scion/3877#-MIJcOXcApchS0z60VGg:-MIJcOXdBak5mnn6tJPV:b-cqmeg9) ([raw file](https://github.com/scionproto/scion/blob/19818082e98a470f21c884f897e6deb06d5a8096/python/topology/topo.py#L365)):*
> ```Python
> 
>     def _write_as_topos(self):
>         # TODO use self._iterate (or replace that with as_iter)
> ```

left over?


<!-- Sent from Reviewable.io -->

2020-09-29 09:27 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3877)* status: 17 of 25 files reviewed, 3 unresolved discussions (waiting on @matzf and @Oncilla)

___
*[docker/BUILD.bazel, line 44 at r1](https://reviewable.io/reviews/scionproto/scion/3877#-MIJYMxg3QH7XEdV9RF6:-MIOATer08_HXv8wh6HU:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/59998d71151eb80d29210fdb0640f017f941a58f/docker/BUILD.bazel#L44)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

This changes behavior and should be documented in the PR description.

Alternatively,  I think a cmd + entrypoint combo would be nicer to work with:

By default still run with `/app/x --config /share/conf/x.toml`, but let the user override the command if they want to:

```
diff --git a/docker/BUILD.bazel b/docker/BUILD.bazel
index 2c5e850b3..ec3366b1e 100644
--- a/docker/BUILD.bazel
+++ b/docker/BUILD.bazel
@@ -41,11 +41,11 @@ scion_app_images(
     name = "border",
     appdir = "/app",
     binary = "//go/border:border",
-    entrypoint = [
-        "/app/border",
+    cmd = [
         "--config",
         "/share/conf/br.toml",
     ],
+    entrypoint = ["/app/border"],
     workdir = "/share",
 )
 
diff --git a/docker/caps.bzl b/docker/caps.bzl
index 3f657a94d..0bac15dae 100644
--- a/docker/caps.bzl
+++ b/docker/caps.bzl
@@ -147,11 +147,12 @@ setcap = rule(
 )
 
 # same as container_image, except that it allows to set capabilities on one binary
-def container_image_setcap(name, entrypoint, caps_binary = None, caps = None, **kwargs):
+def container_image_setcap(name, entrypoint, cmd = None, caps_binary = None, caps = None, **kwargs):
     if not caps:
         # Fast path. If no caps are to be set, skip the setcap dance.
         container_image(
             name = name,
+            cmd = cmd,
             entrypoint = entrypoint,
             visibility = ["//visibility:public"],
             **kwargs
@@ -159,6 +160,7 @@ def container_image_setcap(name, entrypoint, caps_binary = None, caps = None, **
     else:
         container_image(
             name = name + "_nocap",
+            cmd = cmd,
             entrypoint = entrypoint,
             **kwargs
         )
@@ -171,6 +173,7 @@ def container_image_setcap(name, entrypoint, caps_binary = None, caps = None, **
         container_image(
             name = name,
             base = name + "_withcap.tar",
+            cmd = cmd,
             entrypoint = entrypoint,
             visibility = ["//visibility:public"],
         )
diff --git a/docker/scion_app.bzl b/docker/scion_app.bzl
index d3bec2584..1701b8546 100644
--- a/docker/scion_app.bzl
+++ b/docker/scion_app.bzl
@@ -48,7 +48,7 @@ def scion_app_base():
 #   workdir - working directory
 #   entrypoint - a list of strings that add up to the command line
 #   caps - capabilities to set on the binary
-def scion_app_images(name, binary, appdir, workdir, entrypoint, caps = None):
+def scion_app_images(name, binary, appdir, workdir, entrypoint, cmd = None, caps = None):
     pkg_tar(
         name = "%s_docker_files" % name,
         srcs = [binary],
@@ -61,6 +61,7 @@ def scion_app_images(name, binary, appdir, workdir, entrypoint, caps = None):
         base = "//docker:app_base",
         tars = [":%s_docker_files" % name],
         workdir = workdir,
+        cmd = cmd,
         entrypoint = entrypoint,
         caps_binary = "%s/%s" % (appdir, name),
         caps = caps,
@@ -71,6 +72,7 @@ def scion_app_images(name, binary, appdir, workdir, entrypoint, caps = None):
         base = "//docker:app_base_debug",
         tars = [":%s_docker_files" % name],
         workdir = workdir,
+        cmd = cmd,
         entrypoint = entrypoint,
         caps_binary = "%s/%s" % (appdir, name),
         caps = caps,
```


</blockquote></details>

Done.
___
*[python/topology/topo.py, line 365 at r1](https://reviewable.io/reviews/scionproto/scion/3877#-MIJcOXcApchS0z60VGg:-MIOAqyQCYo4sbR_aLHO:b-f38cqk) ([raw file](https://github.com/scionproto/scion/blob/19818082e98a470f21c884f897e6deb06d5a8096/python/topology/topo.py#L365)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

left over?
</blockquote></details>

Ah, indeed. Cleaned up.


<!-- Sent from Reviewable.io -->

2020-09-29 14:30 UTC, Oncilla approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 8 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3877#-:-MIOM0iN-a2OvjPtk9KB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[go/scion-pki/testcrypto/testcrypto.go, line 529 at r1](https://reviewable.io/reviews/scionproto/scion/3877#-MIJZmjmEcw79BOowKdh:-MIPGMBn2bVB4L2hl4rf:b-jlosl5) ([raw file](https://github.com/scionproto/scion/blob/59998d71151eb80d29210fdb0640f017f941a58f/go/scion-pki/testcrypto/testcrypto.go#L529)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

For internal tooling, we need to have the `ISD*/AS*` structure of test crypto.
Please make this configurable via a flag





</blockquote></details>

As discussed offline, I will take care of this.


<!-- Sent from Reviewable.io -->

2020-09-29 14:30 UTC, Oncilla approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3877)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-29 14:31 UTC, merged