doc: epic-hp path type specification and design document
scionproto/scion pull request #3884
Opened 2020-09-21 20:23 UTC by mawyss

This PR contains the EPIC-HP path type specification and design document.
EPIC-HP (EPIC for Hidden Paths) provides the improved security properties of EPIC on the very last inter-AS link of a path. 
It is meant as a lightweight EPIC version and is specifically designed to better protect hidden paths.

2020-09-24 15:32 UTC, mlegner commented
Thanks for the PR, Marc! Could you check and fix the lint errors for the EPIC design doc?

2020-09-29 16:22 UTC, shitz requested changes
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: all files reviewed, 17 unresolved discussions (waiting on @mawyss)

___
*[doc/EPIC.md, line 43 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPesL18BjiupEYq8co:-MIPesL18BjiupEYq8cp:biiu6bo) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L43)):*
> ```
> ## EPIC-HP Overview
> ```
Here it would be good if you could add an intuition how it actually works. 
___
*[doc/EPIC.md, line 71 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPRnw938719i7-5Z35:-MIPRnw938719i7-5Z36:b-nmuook) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L71)):*
> ```
> duplicate-suppression
> ```
If EPIC itself doesn't include this can you reference something here that could be used?
___
*[doc/EPIC.md, line 71 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPVRZP6SpAiZQzevJ_:-MIPVRZP6SpAiZQzevJa:bejwhvi) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L71)):*
> ```
> two ASes
> ```
Why does the last AS also need one? Wouldn't it suffice to have it at the penultimate one?
___
*[doc/EPIC.md, line 94 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPUr06-8l6v1dAUHZl:-MIPUr06-8l6v1dAUHZm:bpq5ab1) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L94)):*
> ```
> filtering (red dots). For example, AS 5 will block (red "X" in the
> figure) SCION path type traffic from AS 3 that is destined towards
> AS 6, as it would affect the hidden path. Instead of blocking
> ```
Uh why is this necessary? Assuming AS 6 as has never publicly announced the link between AS 6 and AS 6 there is no need for such filtering/blocking, since the path information wouldn't be available. 

That also has the upside that AS 6 wouldn't need to rely on AS 5 to do that.
___
*[doc/EPIC.md, line 100 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPVfnYCbLhGIU6z_Aa:-MIPVfnYCbLhGIU6z_Ab:b-dmb4pm) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L100)):*
> ```
>  AS 6 could additionally disallow 
> ```
I think "disallow" is not really appropriate language here as it implies standard firewalling/filtering. The whole point is that this is not needed, since the path information would only be available to entities you want to admit traffic from.
___
*[doc/EPIC.md, line 147 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPYvtE73BJ4FTSqhIR:-MIPYvtFDLfTKmHzHBno:b-dhevxr) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L147)):*
> ```
> ## <a id="PathTypeFiltering"></a> Path Type Filtering
> ```
How is that communicated? Is this part of the beacon?
___
*[doc/EPIC.md, line 164 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPZ6j960_8td1aPsKk:-MIPZ6j960_8td1aPsKl:bq54dhe) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L164)):*
> ```
> AllowedTraffic(x, y) = (1, 0, 0, ...)
> ```
This seems rather implicit to me. Why not have a more verbose encoding. I'm also not sure if this is needed at all.
___
*[doc/EPIC.md, line 191 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIP_CFR820eEBEYQC8Z:-MIP_CFR820eEBEYQC8_:b-17hlzm) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L191)):*
> ```
> Note that hosts behind a hidden link can send SCION path type
> packets towards hosts in other ASes, but that those hosts can not
> ```
Ah now I see where the filtering comes in. If the hidden AS itself uses the same link for hidden and public communication. I think this is an important distinction to make, i.e., that there is no need for filtering if the hidden link is only used for communication with other ASes that are in the trusted group (of course the MAC verification is still needed, but the thing is that we don't rely on simple firewalling techniques anymore in that case)

Not sure where to best bring this in. Maybe you can make this more clear somewhere in the design doc.
___
*[doc/protocols/scion-header.rst, line 486 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPaCXU0AKPzbCZ96yc:-MIPaCXU0AKPzbCZ96yd:bhp5l6d) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L486)):*
> ```
> ·
> ```
almost every line has a trailing whitespace
___
*[doc/protocols/scion-header.rst, line 542 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPaqJK7WbQ0o45kRTN:-MIPaqJLAZcFrwSfQSWn:b-b5yor) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L542)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> whether it wants the receiver to respond with SCION path type
> response packets, or with EPIC-HP packets (assuming the receiver has
> the necessary authenticators to send on the hidden path to the
> sender).
> ```
</details>

I'm not quite convinced this is necessary. Either the receiver has the necessary information to create the {P, L}HVF or it has not. In the former case it should reply with EPIC-HP traffic, in the latter it can anyway only reply with standard SCION traffic, thus the `S` bit is in a way implicitly there already.

Or am I missing something?
___
*[doc/protocols/scion-header.rst, line 551 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPbMR27BMKHA6WsFyx:-MIPbMR27BMKHA6WsFyy:byv0pfu) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L551)):*
> ```
> scion/doc/EPIC.md
> ```
Replace with actual link?
___
*[doc/protocols/scion-header.rst, line 568 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPbjlFDFbOujIgX6KA:-MIPbjlFDFbOujIgX6KB:bhke9i) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L568)):*
> ```
> Packet Timestamp
> ```
So the packet timestamp can be used for replay suppression I assume. You should explicitly mention it's purpose.
___
*[doc/protocols/scion-header.rst, line 633 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPc3A6DH8LtT9EUW2A:-MIPc3A75KcqtLMybdLz:b-vtvvln) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L633)):*
> ```
> .. To achieve an even higher precision of the timestamp, the
> .. source is free to allocate additional bits from the PckId to TsRel
> .. for this purpose.
> ```
Didn't we say this wouldn't work?
___
*[doc/protocols/scion-header.rst, line 650 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPdnf_9_QJ1wireGhS:-MIPdnf_9_QJ1wireGhT:bunkdcz) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L650)):*
> ```
> Those 4-byte fields contain the Hop Validation Fields of the
> penultimate and the last hop of the last segment.
> ```
Mention here already _what_ they are, i.e., the last 4-byte of a MAC calculation or something similar to that. Also add a forward reference to where you describe the procedure.
___
*[doc/protocols/scion-header.rst, line 681 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPeWp6B5HWrgPu3hYU:-MIPeWp6B5HWrgPu3hYV:bb820pv) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L681)):*
> ```
> SrcHostAddr
> ```
Why is that needed?
___
*[doc/protocols/scion-header.rst, line 709 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPeh1XBXjLbX7kL9s0:-MIPeh1XBXjLbX7kL9s1:bekj845) ([ [...]

2020-09-30 08:54 UTC, mlegner reviewed
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: all files reviewed, 17 unresolved discussions (waiting on @mawyss and @shitz)

___
*[doc/EPIC.md, line 71 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPVRZP6SpAiZQzevJ_:-MIT777u1DDVemCyLVO8:b-hnmq72) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L71)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> two ASes
> ```
Why does the last AS also need one? Wouldn't it suffice to have it at the penultimate one?
</blockquote></details>

In principle, yes. The advantage of also having it at the last AS is that it can detect misbehavior by its provider.
We could make that optional though.
___
*[doc/EPIC.md, line 94 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPUr06-8l6v1dAUHZl:-MIT7gVFA_lfPLDedoVn:bhuqf1j) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L94)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> filtering (red dots). For example, AS 5 will block (red "X" in the
> figure) SCION path type traffic from AS 3 that is destined towards
> AS 6, as it would affect the hidden path. Instead of blocking
> ```
Uh why is this necessary? Assuming AS 6 as has never publicly announced the link between AS 6 and AS 6 there is no need for such filtering/blocking, since the path information wouldn't be available. 

That also has the upside that AS 6 wouldn't need to rely on AS 5 to do that.
</blockquote></details>

Valid SCION MACs are also part of the EPIC-HP header. They can thus be observed in the data plane, meaning end hosts might gain access to them somehow. Even if we didn't include the SCION MACs (which would lead to other problems), they could still potentially be brute-forced.
If SCION traffic is allowed in the data plane, end hosts or malicious ASes could simply use this information to send SCION traffic.
___
*[doc/EPIC.md, line 100 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPVfnYCbLhGIU6z_Aa:-MIT8QmUAvK1tXHb6f5k:ba1kmag) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L100)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
>  AS 6 could additionally disallow 
> ```
I think "disallow" is not really appropriate language here as it implies standard firewalling/filtering. The whole point is that this is not needed, since the path information would only be available to entities you want to admit traffic from.
</blockquote></details>

See previous comment.
The filtering here is substantially easier than standard firewalling/filtering: The border router can decide whether to forward or drop packets solely based on the path type.
___
*[doc/protocols/scion-header.rst, line 486 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPaCXU0AKPzbCZ96yc:-MITClqt8YS6tUATQMgL:b-bv0f6) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L486)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> ·
> ```
almost every line has a trailing whitespace
</blockquote></details>

Is there a plan to add a restructured-text linter to the repo? I could look into this, if you think it makes sense.
___
*[doc/protocols/scion-header.rst, line 542 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPaqJK7WbQ0o45kRTN:-MIT9X4UAm4rcpoRxicF:b-ve8bi8) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L542)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> whether it wants the receiver to respond with SCION path type
> response packets, or with EPIC-HP packets (assuming the receiver has
> the necessary authenticators to send on the hidden path to the
> sender).
> ```
I'm not quite convinced this is necessary. Either the receiver has the necessary information to create the {P, L}HVF or it has not. In the former case it should reply with EPIC-HP traffic, in the latter it can anyway only reply with standard SCION traffic, thus the `S` bit is in a way implicitly there already.

Or am I missing something?
</blockquote></details>

Yes, I think that makes sense. But what happens in the case where the end host hasn't fetched this information from the local (hidden) path server yet? In that case it would need to ask the path server, causing additional latency, etc. Does this make sense?
___
*[doc/protocols/scion-header.rst, line 681 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPeWp6B5HWrgPu3hYU:-MITANe3DMwIhqTB_2VB:b-gkl6vi) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L681)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> SrcHostAddr
> ```
Why is that needed?
</blockquote></details>

Packets can be uniquely identified by `SrcISD, SrcAS, SrcHostAddr, PacketTimestamp`; the duplicate-suppression system uses this to track packets. If the `SrcHostAddr` were not included in the MAC calculation, either the MACs could be directly used to send  additional packets with a different source address or the duplicate-suppression system would need to drop packets with equal `SrcISD, SrcAS, PacketTimestamp`, potentially causing interference between different hosts.


<!-- Sent from Reviewable.io -->

2020-09-30 19:57 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: all files reviewed, 17 unresolved discussions (waiting on @mawyss and @shitz)

___
*[doc/EPIC.md, line 43 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPesL18BjiupEYq8co:-MITnY823l8Aum1WXI3N:b-yqbjj9) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L43)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> ## EPIC-HP Overview
> ```
Here it would be good if you could add an intuition how it actually works. 
</blockquote></details>

I added a short description now.
___
*[doc/EPIC.md, line 71 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPRnw938719i7-5Z35:-MITnhXI-AljWu7GWNAh:b-m3pfi4) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L71)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> duplicate-suppression
> ```
If EPIC itself doesn't include this can you reference something here that could be used?
</blockquote></details>

Yes, it is not included in EPIC.
I added a reference to a possible replay suppression system:
https://netsec.ethz.ch/publications/papers/replay2017.pdf
___
*[doc/EPIC.md, line 147 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPYvtE73BJ4FTSqhIR:-MITpXhJ1m82nQDIYRC_:b-c3tlos) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L147)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> ## <a id="PathTypeFiltering"></a> Path Type Filtering
> ```
How is that communicated? Is this part of the beacon?
</blockquote></details>

Do you mean how the upstream AS knows what it needs to filter? See 1.)
Or do you mean whether some source needs to know which on-path AS does which kind of filtering? See 2.)

1.)
The AS protected by the hidden path requests that its upstream AS implements path type filtering.
It is not specified how this is done here, it could be via other protocols or it could even be out-of-band.

2.)
The ASes do not announce to other ASes whether they implement path type filtering or not.
- For "Highly secure hidden paths":
If the penultimate AS (AS 5) drops all non-EPIC-HP traffic that goes towards some AS protected by the hidden path (AS 6), then this will not affect any standard SCION paths, as there are no SCION paths anyway that go through any interface of AS 5 towards AS 6 (except for maliciously brute-forced ones, but it is the purpose of the filtering to block those).
- For "DOS-secure hidden paths":
If an AS only prioritizes EPIC-HP (not filtering), then SCION-traffic can still go through.

Therefore a source AS/endhost sending SCION traffic does not need to know which on-path AS implements which filtering mechanism.
___
*[doc/EPIC.md, line 191 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIP_CFR820eEBEYQC8Z:-MITxGTT8rzn9NaaJyI4:b-752daa) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L191)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> Note that hosts behind a hidden link can send SCION path type
> packets towards hosts in other ASes, but that those hosts can not
> ```
Ah now I see where the filtering comes in. If the hidden AS itself uses the same link for hidden and public communication. I think this is an important distinction to make, i.e., that there is no need for filtering if the hidden link is only used for communication with other ASes that are in the trusted group (of course the MAC verification is still needed, but the thing is that we don't rely on simple firewalling techniques anymore in that case)

Not sure where to best bring this in. Maybe you can make this more clear somewhere in the design doc.
</blockquote></details>

In the "Highly secure hidden paths" case, the filtering is essential, irrespective of whether the protected AS only communicates with ASes in the trusted group (meaning that it would only send and receive EPIC-HP traffic) or not.
Even if all the traffic towards and out of some AS behind a hidden path is EPIC-HP traffic, an adversary could still brute-force a standard SCION path, generating SCION traffic towards this AS.
___
*[doc/protocols/scion-header.rst, line 551 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPbMR27BMKHA6WsFyx:-MIV4vJ06Zcw3kvSNPLU:bg0ktrl) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L551)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> scion/doc/EPIC.md
> ```
Replace with actual link?
</blockquote></details>

I updated it, the link should work now.
___
*[doc/protocols/scion-header.rst, line 568 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPbjlFDFbOujIgX6KA:-MIVOaY-EChFoUqIzoWV:b-ns3xjd) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L568)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> Packet Timestamp
> ```
So the packet timestamp can be used for replay suppression I assume. You should explicitly mention it's purpose.
</blockquote></details>

I added a description now.
___
*[doc/protocols/scion-header.rst, line 633 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPc3A6DH8LtT9EUW2A:-MIUI3uM-LB9UYHlpIG-:b76yfim) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L633)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> .. To achieve an even higher precision of the timestamp, the
> .. source is free to allocate additional bits from the PckId to TsRel
> .. for this purpose.
> ```
Didn't we say this wouldn't work?
</blockquote></details>

Right, I kept it there as a comment.
Removed it now.
___
*[doc/protocols/scion-header.rst, line 650 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPdnf_9_QJ1wireGhS:-MIVT3BfEPKsSDQe3mDM:b-rfeuzw) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L650)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> Those 4-byte fields contain the Hop Validation Fields of the
> penultimate and the last hop of the last segment.
> ```
Mention here already _what_ they are, i.e., the last 4-byte of a MAC calculation or something similar to that. Also add a forward reference to where you describe the procedure.
</blockquote></details>

I wrote a short description and some context on how the Hop Validation Fields are used, and added a forward reference to the procedure section.
___
*[doc/protocols/scion-header.rst, line 681 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPeWp6B5HWrgPu3hYU:-MIVT_eLDmW4DOqKfZMP:bulbd4) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L681)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Packets can be uniquely identified by `SrcISD, SrcAS, SrcHostAddr, PacketTimestamp`; the duplicate-suppression system uses this to track packets. If the `SrcHostAddr` were not included in the MAC calculation, either the MACs could be directly used to send  additional packets with a different source address or the duplicate-suppression system would need to drop packets with equal `SrcISD, SrcAS, PacketTimestamp`, potentially causing interference between different hosts.
</blockquote></details>

@mlegner The Origin should further include the "Timestamp in the first Info Field", right? (Because the PacketTimestamp  [...]

2020-10-01 07:26 UTC, mlegner reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: 3 of 7 files reviewed, 17 unresolved discussions (waiting on @mawyss, @mlegner, and @shitz)

___
*[doc/protocols/scion-header.rst, line 681 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPeWp6B5HWrgPu3hYU:-MIY2QTx6enWBgwtCPKJ:bhi4t7h) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L681)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

@mlegner The Origin should further include the "Timestamp in the first Info Field", right? (Because the PacketTimestamp is calculated with respect to this other Timestamp)
</blockquote></details>

Indeed, you are right.


<!-- Sent from Reviewable.io -->

2020-10-02 12:31 UTC, shitz commented
___
*[doc/EPIC.md, line 94 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPUr06-8l6v1dAUHZl:-MIdFvod7LZBmyY0ETAj:bdmdmrl) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L94)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Valid SCION MACs are also part of the EPIC-HP header. They can thus be observed in the data plane, meaning end hosts might gain access to them somehow. Even if we didn't include the SCION MACs (which would lead to other problems), they could still potentially be brute-forced.
If SCION traffic is allowed in the data plane, end hosts or malicious ASes could simply use this information to send SCION traffic.
</blockquote></details>

Right but this is basically only a problem for on-path attackers. There is still the possiblity to register entire path segments only with a hidden path service at which point only an on-path attacker could get the necessary path information.

Bruteforcing 6 bytes I don't consider a valid attack vector.

So essentially what EPIC-HP gives you (additionally) is protection against on-path attackers, but an AS needs cooperation from its upstream provider. Maybe we could work this into the description? What do you think?


<!-- Sent from Reviewable.io -->

2020-10-02 12:52 UTC, shitz requested changes
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: all files reviewed, 9 unresolved discussions (waiting on @mawyss, @mlegner, @scrye, and @sgmonroy)

___
*[doc/EPIC.md, line 71 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPRnw938719i7-5Z35:-MIdFEhJ8GeHcu_7xDhX:b-gcsnuq) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L71)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Yes, it is not included in EPIC.
I added a reference to a possible replay suppression system:
https://netsec.ethz.ch/publications/papers/replay2017.pdf
</blockquote></details>

You should reference the reference here ;)
___
*[doc/EPIC.md, line 147 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPYvtE73BJ4FTSqhIR:-MIdHI1v1q3X0sSGLxaZ:bfb7j0d) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L147)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Do you mean how the upstream AS knows what it needs to filter? See 1.)
Or do you mean whether some source needs to know which on-path AS does which kind of filtering? See 2.)

1.)
The AS protected by the hidden path requests that its upstream AS implements path type filtering.
It is not specified how this is done here, it could be via other protocols or it could even be out-of-band.

2.)
The ASes do not announce to other ASes whether they implement path type filtering or not.
- For "Highly secure hidden paths":
If the penultimate AS (AS 5) drops all non-EPIC-HP traffic that goes towards some AS protected by the hidden path (AS 6), then this will not affect any standard SCION paths, as there are no SCION paths anyway that go through any interface of AS 5 towards AS 6 (except for maliciously brute-forced ones, but it is the purpose of the filtering to block those).
- For "DOS-secure hidden paths":
If an AS only prioritizes EPIC-HP (not filtering), then SCION-traffic can still go through.

Therefore a source AS/endhost sending SCION traffic does not need to know which on-path AS implements which filtering mechanism.
</blockquote></details>

So what's the relevance of this section then? This seems to me implementation specific how to configure a router what kind of traffic it should allow.
___
*[doc/EPIC.md, line 191 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIP_CFR820eEBEYQC8Z:-MIdHZrO4MXRIakdpM7K:b-88glap) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L191)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

In the "Highly secure hidden paths" case, the filtering is essential, irrespective of whether the protected AS only communicates with ASes in the trusted group (meaning that it would only send and receive EPIC-HP traffic) or not.
Even if all the traffic towards and out of some AS behind a hidden path is EPIC-HP traffic, an adversary could still brute-force a standard SCION path, generating SCION traffic towards this AS.
</blockquote></details>

bruteforcing a 6-byte MAC is not something you can do easily, but the hidden path information can be seen by on-path attackers. See my reply to Markus' comment above.
___
*[doc/protocols/scion-header.rst, line 486 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPaCXU0AKPzbCZ96yc:-MIdI0co9hSicE0HYPws:b-pzjtkm) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L486)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Is there a plan to add a restructured-text linter to the repo? I could look into this, if you think it makes sense.
</blockquote></details>

Unfortunately not. We have an issue internally for this, but it would be great if you could look into this.
___
*[doc/protocols/scion-header.rst, line 542 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPaqJK7WbQ0o45kRTN:-MIdKAxIA30YZ0eKTctI:bmk7p4g) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L542)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Yes, I think that makes sense. But what happens in the case where the end host hasn't fetched this information from the local (hidden) path server yet? In that case it would need to ask the path server, causing additional latency, etc. Does this make sense?
</blockquote></details>

I'm not sure we should solve that problem by including flags in the wireformat. To me, this is a problem of configuration/information availability for an application. Given that the information of how to fetch the necessary information needs to be somewhere, I think it's up to the application to figure this out or has it configured somehow.
@scrye @sgmonroy thoughts on this?
___
*[doc/protocols/scion-header.rst, line 681 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPeWp6B5HWrgPu3hYU:-MIdLj_R60sw2tdUxLC3:bqah0hv) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L681)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Indeed, you are right.
</blockquote></details>

Ok, I considered EPIC-HP to be on the AS-to-AS level, since I currently do not envision access controlling access to the necessary authenticators on a per host basis. However, it doesn't really hurt to have the SrcHostAddr in there and we could have this access controlled per host in the future thus :ok_hand: 
___
*[doc/protocols/scion-header.rst, line 669 at r3](https://reviewable.io/reviews/scionproto/scion/3884#-MIdLY74CFeREZiOpcFz:-MIdLY74CFeREZiOpcG-:bmxeoos) ([raw file](https://github.com/scionproto/scion/blob/e2a82e7ee5938fe6882b21ad633cc7a86dfe53a2/doc/protocols/scion-header.rst#L669)):*
> ```
>  Procedures_ 
> ```
Needs to be a link
___
*[doc/protocols/scion-header.rst, line 734 at r3](https://reviewable.io/reviews/scionproto/scion/3884#-MIdMd2r4ilKS74ouNFT:-MIdMd2r4ilKS74ouNFU:bov8ev1) ([raw file](https://github.com/scionproto/scion/blob/e2a82e7ee5938fe6882b21ad633cc7a86dfe53a2/doc/protocols/scion-header.rst#L734)):*
> ```
> Origin fields from the EPIC-HP packet and measure the length of the
> payload (PayloadLen), which is all the information it needs to
> ```
Why wouldn't it read that out from the common header?


<!-- Sent from Reviewable.io -->

2020-10-02 12:57 UTC, shitz requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: all files reviewed, 10 unresolved discussions (waiting on @mawyss, @mlegner, @scrye, and @sgmonroy)

___
*[doc/EPIC.md, line 184 at r3](https://reviewable.io/reviews/scionproto/scion/3884#-MIdNZQ2B6TcEOmnO6KF:-MIdNZQ2B6TcEOmnO6KG:b-h3i7wo) ([raw file](https://github.com/scionproto/scion/blob/e2a82e7ee5938fe6882b21ad633cc7a86dfe53a2/doc/EPIC.md#L184)):*
> ```
> Highly Secure Hidden Paths
> ```
You should reference the hidden paths design doc here, otherwise it's unclear for the reader how for example the information necessary to calculate the HVFs are communicated.


<!-- Sent from Reviewable.io -->

2020-10-05 10:19 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: 5 of 7 files reviewed, 10 unresolved discussions (waiting on @mawyss, @mlegner, @scrye, @sgmonroy, and @shitz)

___
*[doc/EPIC.md, line 71 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPRnw938719i7-5Z35:-MIrrGjU0_QKvVP2MeqP:b-y2elqr) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L71)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

You should reference the reference here ;)
</blockquote></details>

True, then we could use this PR as reference to the replay suppression system using three indirections :D
___
*[doc/EPIC.md, line 94 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPUr06-8l6v1dAUHZl:-MIs3-BX-NzmB6CctCTU:bsz0pov) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L94)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Right but this is basically only a problem for on-path attackers. There is still the possiblity to register entire path segments only with a hidden path service at which point only an on-path attacker could get the necessary path information.

Bruteforcing 6 bytes I don't consider a valid attack vector.

So essentially what EPIC-HP gives you (additionally) is protection against on-path attackers, but an AS needs cooperation from its upstream provider. Maybe we could work this into the description? What do you think?
</blockquote></details>

Right, the problem of on-path attackers is mitigated with EPIC. This is described in the Introduction paragraph.
I added the fact, that an AS needs cooperation from its upstream provider, to the Overview.

Regarding the 6 bytes MACs in SCION: 
- When designing EPIC-HP, I always made the (admittedly overly careful) assumption, that SCION MACs could be brute-forced. 
This led to a design, which foresees path type filtering at every interface of the last two ASes, but which leads to more security.
Even if the SCION MACs were impossible to brute-force, the path type filtering at AS 5 at other interfaces would still be necessary in a scenario where there are other hidden paths going through additional interfaces.
- For a perfect MAC function, an attacker would need at most 325 days to brute-force a 6-byte field, assuming he can send a packet every 0,1 microseconds. Considering other factors, e.g. that real implementations of MACs do not show perfectly uniform outputs (some outputs are more likely than others), we might not be *that* far away from 1 day. I wanted to be conservative about assuming the SCION MACs to be secure.
___
*[doc/EPIC.md, line 147 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPYvtE73BJ4FTSqhIR:-MIrwFfzEyeq3Bp6jMfD:b-uiv4fx) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L147)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

So what's the relevance of this section then? This seems to me implementation specific how to configure a router what kind of traffic it should allow.
</blockquote></details>

Right, it is only important that it is implemented, not how exactly.
This paragraph of the design document is meant to provide the high-level logic (abstraction).
It should clarify what is meant by path type filtering and highlight the fact, that filtering between two interfaces can be different depending on the direction of the traffic.
I changed it now so that it does not look like some kind of concrete specification.
___
*[doc/EPIC.md, line 164 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPZ6j960_8td1aPsKk:-MIrz-hK7dF54PCxA2eo:br21h2v) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L164)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> AllowedTraffic(x, y) = (1, 0, 0, ...)
> ```
This seems rather implicit to me. Why not have a more verbose encoding. I'm also not sure if this is needed at all.
</blockquote></details>

I changed it to be more verbose now.
The filtering is needed however (as you mentioned in a comment further below).
___
*[doc/EPIC.md, line 184 at r3](https://reviewable.io/reviews/scionproto/scion/3884#-MIdNZQ2B6TcEOmnO6KF:-MIs058KE0gN_QUm9g4X:b-rd4cit) ([raw file](https://github.com/scionproto/scion/blob/e2a82e7ee5938fe6882b21ad633cc7a86dfe53a2/doc/EPIC.md#L184)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> Highly Secure Hidden Paths
> ```
You should reference the hidden paths design doc here, otherwise it's unclear for the reader how for example the information necessary to calculate the HVFs are communicated.
</blockquote></details>

I added a short paragraph on how the HVFs are communicated.
___
*[doc/protocols/scion-header.rst, line 669 at r3](https://reviewable.io/reviews/scionproto/scion/3884#-MIdLY74CFeREZiOpcFz:-MIs0JsZ-Dmwc5osVi8s:bh3z5d5) ([raw file](https://github.com/scionproto/scion/blob/e2a82e7ee5938fe6882b21ad633cc7a86dfe53a2/doc/protocols/scion-header.rst#L669)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
>  Procedures_ 
> ```
Needs to be a link
</blockquote></details>

Actually, this is a valid reference to a paragraph, you can leave out the quotes if it is a single word.
However, I added quotes now to make it more clear.
___
*[doc/protocols/scion-header.rst, line 734 at r3](https://reviewable.io/reviews/scionproto/scion/3884#-MIdMd2r4ilKS74ouNFT:-MIs0rU69LAedSFbr1Tu:bdud60j) ([raw file](https://github.com/scionproto/scion/blob/e2a82e7ee5938fe6882b21ad633cc7a86dfe53a2/doc/protocols/scion-header.rst#L734)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> Origin fields from the EPIC-HP packet and measure the length of the
> payload (PayloadLen), which is all the information it needs to
> ```
Why wouldn't it read that out from the common header?
</blockquote></details>

You are right, I changed it accordingly.


<!-- Sent from Reviewable.io -->

2020-10-06 12:31 UTC, shitz requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: all files reviewed, 4 unresolved discussions (waiting on @mawyss, @scrye, @sgmonroy, and @shitz)

___
*[doc/EPIC.md, line 71 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPRnw938719i7-5Z35:-MIxj_yL3s3w546zOv3n:b-a1fjf3) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L71)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

True, then we could use this PR as reference to the replay suppression system using three indirections :D
</blockquote></details>

No what I mean is add a `[3]` with a link to the references section.
___
*[doc/EPIC.md, line 94 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPUr06-8l6v1dAUHZl:-MIxrplb2EM9Wsud8LeZ:b-p9cfwv) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L94)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Right, the problem of on-path attackers is mitigated with EPIC. This is described in the Introduction paragraph.
I added the fact, that an AS needs cooperation from its upstream provider, to the Overview.

Regarding the 6 bytes MACs in SCION: 
- When designing EPIC-HP, I always made the (admittedly overly careful) assumption, that SCION MACs could be brute-forced. 
This led to a design, which foresees path type filtering at every interface of the last two ASes, but which leads to more security.
Even if the SCION MACs were impossible to brute-force, the path type filtering at AS 5 at other interfaces would still be necessary in a scenario where there are other hidden paths going through additional interfaces.
- For a perfect MAC function, an attacker would need at most 325 days to brute-force a 6-byte field, assuming he can send a packet every 0,1 microseconds. Considering other factors, e.g. that real implementations of MACs do not show perfectly uniform outputs (some outputs are more likely than others), we might not be *that* far away from 1 day. I wanted to be conservative about assuming the SCION MACs to be secure.

</blockquote></details>

Being able to send a packet every 0.1 microseconds is definitely possible, however, as an attacker you also need feedback from the network to get a result, i.e., success or fail. There you have to deal with latencies and processing costs. I don't think it's practical to bruteforce a SCION MAC, but I'm fine with leaving the path type filtering as the default. :+1: 
___
*[doc/EPIC.md, line 175 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxslin4NVrl0iX57NC:-MIxslin4NVrl0iX57ND:b7bqgst) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/EPIC.md#L175)):*
> ```
> an AS needs to
> ```
s/an AS needs to/it should be configurable/

(the sentence is not proper English)
___
*[doc/protocols/scion-header.rst, line 669 at r3](https://reviewable.io/reviews/scionproto/scion/3884#-MIdLY74CFeREZiOpcFz:-MIxtA6-6G3L26_kPEbs:b8ht2n1) ([raw file](https://github.com/scionproto/scion/blob/e2a82e7ee5938fe6882b21ad633cc7a86dfe53a2/doc/protocols/scion-header.rst#L669)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Actually, this is a valid reference to a paragraph, you can leave out the quotes if it is a single word.
However, I added quotes now to make it more clear.
</blockquote></details>

Oh I didn't no. Anyway :ok_hand: 


<!-- Sent from Reviewable.io -->

2020-10-06 12:36 UTC, lukedirtwalker requested changes
> Reviewed 3 of 5 files at r1, 2 of 4 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: all files reviewed, 7 unresolved discussions (waiting on @mawyss, @scrye, @sgmonroy, and @shitz)

___
*[doc/EPIC.md, line 97 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxmfRO7mhB2gplxhga:-MIxmfRQ7veFv__p8cbm:bwz31m3) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/EPIC.md#L97)):*
> ```Markdown
> ### Example
> 
> ![](fig/EPIC/path-type-filtering-small.png).
> ```

For this and for all other images: It would be nice to have the "source code" for those as well. I.e. if I would want to change something in the image I shouldn't need to recreate it from scratch.

We usually use draw.io and then put the link to the file in `.lnk` file that has the same name as the png.
If we used something else it would be good to either have  the source  or a link. If it's the source it should come with an explanation of how to generate the image.
___
*[doc/EPIC.md, line 100 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxo2W88lVSIeRkwXgV:-MIxo2W88lVSIeRkwXgW:br3r1ya) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/EPIC.md#L100)):*
> ```
> local interface (black dot)
> ```
what exactly is a local interface? The thing that confuses me is that a beacon that is terminated in AS 6 would only have a ConsIngress interface which on the diagram seems to be denoted by the red dot. So it seems the local interface must be something that is not a SCION interface?
___
*[doc/EPIC.md, line 219 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxslnrD9o6XE77Cw5k:-MIxslnrD9o6XE77Cw5l:b-r762re) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/EPIC.md#L219)):*
> ```Markdown
> In this scenario, the hosts protected by the hidden path can set the
> SCION-Response flag to one, so the destination will be able to
> answer with (arbitrariliy many) SCION path type packets.
> ```

hm but if this service relies on the reply this is not really sufficient. I mean above we state that DoS attacks are not possible because of low priority (I guess we drop if we receive too many low prio) but then it could also be that we lose the reply to this?


<!-- Sent from Reviewable.io -->

2020-10-06 13:25 UTC, lukedirtwalker requested changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: all files reviewed, 13 unresolved discussions (waiting on @mawyss, @scrye, and @sgmonroy)

___
*[doc/protocols/scion-header.rst, line 516 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxz-ByEjoy86nScMqA:-MIxz-ByEjoy86nScMqB:b-xkxruf) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/protocols/scion-header.rst#L516)):*
> ```reStructuredText
>     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
> 
> The EPIC-HP header has the following structure:
> ```

Hm I think I would move this before the actual structure which is above
___
*[doc/protocols/scion-header.rst, line 601 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIy10qOE7EY4PouA4EL:-MIy10qOE7EY4PouA4EM:bd7yf5w) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/protocols/scion-header.rst#L601)):*
> ```reStructuredText
>         \text{Timestamp}_{\mu s} &= \text{Timestamp [s]}
>             \times 10^6 \\
>         \text{Ts} &= \text{current unix timestamp [\mu s]}  \\
> ```

\mu doesn't work in the text env, you'll need:
`\text{current unix timestamp [}\mu s \text{]}`
___
*[doc/protocols/scion-header.rst, line 603 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIy1DP4Ce8TDqDjexK2:-MIy1DP4Ce8TDqDjexK3:b-klhi5w) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/protocols/scion-header.rst#L603)):*
> ```
> text{\mu s}
> ```
remove the text around, so that \mu actually works
___
*[doc/protocols/scion-header.rst, line 604 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIy1HTt6Fiq5kbIQUU3:-MIy1HTt6Fiq5kbIQUU4:b-lk9wxs) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/protocols/scion-header.rst#L604)):*
> ```reStructuredText
>         \text{q} &= \left\lceil\left(\frac{24 \times 60 \times 60
>             \times 10^6}{2^{32}}\right)\right\rceil\text{\mu s}
>             = \text{21 \mu s}\\
> ```

ditto, remove text around so that \mu works.
___
*[doc/protocols/scion-header.rst, line 614 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIy1Pa-9IDGh4I_arrR:-MIy1Pa05-0yUqNAkLs1:b-l6mcp7) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/protocols/scion-header.rst#L614)):*
> ```
> \text{
> ```
remove
___
*[doc/protocols/scion-header.rst, line 617 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIy1SO84jQVJ91Fobf8:-MIy1SO84jQVJ91Fobf9:b-l6mcp7) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/protocols/scion-header.rst#L617)):*
> ```
> \text{
> ```
remove
___
*[doc/protocols/scion-header.rst, line 634 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIy2NYPAq7n-ptfDbyU:-MIy2NYQDWYi2HgsCYsN:bz9xri9) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/protocols/scion-header.rst#L634)):*
> ```reStructuredText
> 
> CoreID
>   Unique identifier representing one of the cores of the source host.
> ```

I think defining this via the hardware of the sending host is not optimal. what if multiple hosts in the same AS send packets using epic-hp? IMO we could just say that this needs to be a 4 byte unique ID for the timestamp above. It's a detail that each AS can decide on its own how it wants to deal with it.


<!-- Sent from Reviewable.io -->

2020-10-06 16:10 UTC, scrye commented
___
*[doc/protocols/scion-header.rst, line 542 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPaqJK7WbQ0o45kRTN:-MIyd9KG5cUm0OE0Eee9:b-n14uke) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L542)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

I'm not sure we should solve that problem by including flags in the wireformat. To me, this is a problem of configuration/information availability for an application. Given that the information of how to fetch the necessary information needs to be somewhere, I think it's up to the application to figure this out or has it configured somehow.
@scrye @sgmonroy thoughts on this?
</blockquote></details>

This does sound to me like application security policy.

On a stream connection the `S` bit semantics get weird. The concept of "the reply packet to a packet" doesn't make sense for streams in general, so I'm wondering what would the server even be expected to do if they receive packets with alternating `S` bits on the same stream.

So yeah, I agree with @shitz, I would let the applications decide these aspects based on apriori policy, or negotiate it at application level on the fly.


<!-- Sent from Reviewable.io -->

2020-10-06 16:10 UTC, scrye requested changes
> Reviewed 3 of 5 files at r1, 2 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: all files reviewed, 14 unresolved discussions (waiting on @mawyss and @sgmonroy)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/3884#-MIybF3X5-EsRlQQcbo0:-MIybF3X5-EsRlQQcbo1:b2wcwtv) (no related file):*
Really cool stuff, thanks for adding this to the repo!

I'm curious about a specific component, the Replay Suppression system. I skimmed the Usenix paper, but didn't find an in-depth discussion of how an architecture with replay suppression would look like. Where can I read more about it?

---


<!-- Sent from Reviewable.io -->

2020-10-07 15:14 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: all files reviewed, 14 unresolved discussions (waiting on @lukedirtwalker, @mawyss, @sgmonroy, and @shitz)

___
*[doc/EPIC.md, line 71 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPRnw938719i7-5Z35:-MJ0z_Qr8S9Fok8KNYk-:book2id) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L71)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

No what I mean is add a `[3]` with a link to the references section.
</blockquote></details>

Got it now :)
___
*[doc/EPIC.md, line 97 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxmfRO7mhB2gplxhga:-MJ1-XEn9i47m4JxzwSb:b-2qjmg8) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/EPIC.md#L97)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

For this and for all other images: It would be nice to have the "source code" for those as well. I.e. if I would want to change something in the image I shouldn't need to recreate it from scratch.

We usually use draw.io and then put the link to the file in `.lnk` file that has the same name as the png.
If we used something else it would be good to either have  the source  or a link. If it's the source it should come with an explanation of how to generate the image.
</blockquote></details>

The images are also created using draw.io.
Draw.io by default includes the whole diagram in the .png file, so you can simply drag-and-drop the .png to draw.io and modify it there.
The only .lnk file I could find was for doc/protocols/fig/seg-id-calculation.png.
However, also this image has the complete diagram embedded and can simply be modified in draw.io.
___
*[doc/EPIC.md, line 100 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxo2W88lVSIeRkwXgV:-MJ10xSz7yBJNIrltvqD:b-kofivg) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/EPIC.md#L100)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> local interface (black dot)
> ```
what exactly is a local interface? The thing that confuses me is that a beacon that is terminated in AS 6 would only have a ConsIngress interface which on the diagram seems to be denoted by the red dot. So it seems the local interface must be something that is not a SCION interface?
</blockquote></details>

The local interface represents all the services and end hosts in the AS.
The red dots are the border routers that implement path type filtering.
A beacon would therefore have both, a ConsIngress and a ConsEgress (local interface ID).
___
*[doc/EPIC.md, line 175 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxslin4NVrl0iX57NC:-MJ15ELc1r7LkCZ5qTws:b-mhvvg3) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/EPIC.md#L175)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> an AS needs to
> ```
s/an AS needs to/it should be configurable/

(the sentence is not proper English)
</blockquote></details>

Changed it accordingly now.
___
*[doc/EPIC.md, line 219 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxslnrD9o6XE77Cw5k:-MJ15eVA5aIm_VYmBV9B:b-sdzd9l) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/EPIC.md#L219)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

hm but if this service relies on the reply this is not really sufficient. I mean above we state that DoS attacks are not possible because of low priority (I guess we drop if we receive too many low prio) but then it could also be that we lose the reply to this?
</blockquote></details>

Yes, low priority packets are dropped in case there are not enough resources to handle them.
And you are right, the reply would be low priority and may not arrive.

The idea of the DDoS Secure Hidden Paths scenario is that in the normal (non-DDoS) case, a host protected by the hidden path can also communicate with destinations that do not know the authenticators necessary to send traffic on the hidden path. 
However, destinations that are in the possession of the authenticators and which see that the S-flag is set, can still send back high priority EPIC-HP traffic.
___
*[doc/protocols/scion-header.rst, line 516 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxz-ByEjoy86nScMqA:-MJ1C38k9lB2ljPNZbIi:b-pso3lp) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/protocols/scion-header.rst#L516)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Hm I think I would move this before the actual structure which is above
</blockquote></details>

I moved it above the structure now.
___
*[doc/protocols/scion-header.rst, line 601 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIy10qOE7EY4PouA4EL:-MJ1GyaEClecS8PP4cAq:b-8dhu24) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/protocols/scion-header.rst#L601)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

\mu doesn't work in the text env, you'll need:
`\text{current unix timestamp [}\mu s \text{]}`
</blockquote></details>

Thank you for pointing that out!
I adapted the text accordingly.
___
*[doc/protocols/scion-header.rst, line 603 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIy1DP4Ce8TDqDjexK2:-MJ1HMLc-8ZOjbFiYsrh:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/protocols/scion-header.rst#L603)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> text{\mu s}
> ```
remove the text around, so that \mu actually works
</blockquote></details>

Done.
___
*[doc/protocols/scion-header.rst, line 604 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIy1HTt6Fiq5kbIQUU3:-MJ1HNaBEjBQ6glJScEb:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/protocols/scion-header.rst#L604)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

ditto, remove text around so that \mu works.
</blockquote></details>

Done.
___
*[doc/protocols/scion-header.rst, line 614 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIy1Pa-9IDGh4I_arrR:-MJ1HOh-ApJ-edtLLZUX:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/protocols/scion-header.rst#L614)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> \text{
> ```
remove
</blockquote></details>

Done.
___
*[doc/protocols/scion-header.rst, line 617 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIy1SO84jQVJ91Fobf8:-MJ1HPRn9UONUsrBtXVQ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/protocols/scion-header.rst#L617)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> \text{
> ```
remove
</blockquote></details>

Done.
___
*[doc/protocols/scion-header.rst, line 634 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIy2NYPAq7n-ptfDbyU:-MJ1Ie2tCf_hhR2c1kUW:bsieiq9) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/protocols/scion-header.rst#L634)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I think defining this via the hardware of the sending host is not optimal. what if multiple hosts in the same AS send packets using epic-hp? IMO we could just say that this needs t [...]

2020-10-08 07:20 UTC, lukedirtwalker requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @lukedirtwalker, @mawyss, @scrye, @sgmonroy, and @shitz)

___
*[doc/EPIC.md, line 97 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxmfRO7mhB2gplxhga:-MJ5zdVR-IrUXN34G3F8:b-kp95ok) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/EPIC.md#L97)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

The images are also created using draw.io.
Draw.io by default includes the whole diagram in the .png file, so you can simply drag-and-drop the .png to draw.io and modify it there.
The only .lnk file I could find was for doc/protocols/fig/seg-id-calculation.png.
However, also this image has the complete diagram embedded and can simply be modified in draw.io.
</blockquote></details>

Nice, I didn't know about that. :+1: 
___
*[doc/EPIC.md, line 100 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxo2W88lVSIeRkwXgV:-MJ62U-z1dv9W9LKeCD7:b-ep4p37) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/EPIC.md#L100)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

The local interface represents all the services and end hosts in the AS.
The red dots are the border routers that implement path type filtering.
A beacon would therefore have both, a ConsIngress and a ConsEgress (local interface ID).
</blockquote></details>

I don't understand. The current beaconing implementation upon terminatation doesn't add a ConsEgress field, so where does that come from?
___
*[doc/EPIC.md, line 219 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxslnrD9o6XE77Cw5k:-MJ6-F4u5UijCGoyJJLw:b-87tsrt) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/EPIC.md#L219)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Yes, low priority packets are dropped in case there are not enough resources to handle them.
And you are right, the reply would be low priority and may not arrive.

The idea of the DDoS Secure Hidden Paths scenario is that in the normal (non-DDoS) case, a host protected by the hidden path can also communicate with destinations that do not know the authenticators necessary to send traffic on the hidden path. 
However, destinations that are in the possession of the authenticators and which see that the S-flag is set, can still send back high priority EPIC-HP traffic.
</blockquote></details>

I see
___
*[doc/protocols/scion-header.rst, line 634 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIy2NYPAq7n-ptfDbyU:-MJ6255lAZLHsjKRCu93:b-ayuna8) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/protocols/scion-header.rst#L634)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

The packets and timestamps are generated by the hosts  themselves, and not by the AS.
- Every source (host, service, ...) is free to choose the PckId, it does not need to be defined via cores and counters. The only restriction is that all the packets with the same TsRel need to have different PckIds. This is already mentioned in the description of the PckId field.
- The recommendation to use cores and counters is there because it was tested and proved useful in a standalone implementation of EPIC. It allows the generation of packets using multiple cores without any coordination among them. Using for example more precise (e.g. nanosecond precision) timestamps can still lead to collisions when sending packets from multiple cores. The same issue arises when using random PckIds, which could even cause performance degradation.
- If multiple hosts in the same AS send packets using EPIC-HP it will be very likely that the PacketTimestamp is used multiple times. This is not a problem, because the PacketTimestamp only needs to be unique per host. 
The combination of ISD, AS, host , the Timestamp in the first Info Field, as well as the Packet Timestamp of EPIC-HP uniquely identifies a packet.

</blockquote></details>

I see I must have misread the section about what uniquely identifies a packet and what is used for replay detection, I misinterpreted and thought it would only be the timestamp that is used for replay detection.


<!-- Sent from Reviewable.io -->

2020-10-09 13:54 UTC, sgmonroy reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @lukedirtwalker, @mawyss, @scrye, @sgmonroy, and @shitz)

___
*[doc/EPIC.md, line 100 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxo2W88lVSIeRkwXgV:-MJCMmys5GwLy26yoOwY:bxc4lh6) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/EPIC.md#L100)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I don't understand. The current beaconing implementation upon terminatation doesn't add a ConsEgress field, so where does that come from?
</blockquote></details>

Maybe it is a terminology issue but I also find `local interface` rather ambiguous when referring to end hosts/services in an AS.
Also, like Luke, not understand the how you would have any value in `ConsEgress` in such scenario.


<!-- Sent from Reviewable.io -->

2020-10-12 14:16 UTC, mlegner reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @lukedirtwalker, @scrye, @sgmonroy, and @shitz)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/3884#-MIybF3X5-EsRlQQcbo0:-MJS5fw_DWVKCD1qc3gA:boyxo3z) (no related file):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Really cool stuff, thanks for adding this to the repo!

I'm curious about a specific component, the Replay Suppression system. I skimmed the Usenix paper, but didn't find an in-depth discussion of how an architecture with replay suppression would look like. Where can I read more about it?
</blockquote></details>

What exactly do you mean with "how an architecture with replay suppression would look like"? The basic idea is that packets would be handed over to and tracked by a duplicate-suppression system after being authenticated by the border router. This system could be collocated with the border router or deployed somewhere else in an AS' network. The inspiration comes from the referenced 2017 paper (https://netsec.ethz.ch/publications/papers/replay2017.pdf) but there is no full design/implementation for SCION yet. I haven't looked at the details yet, but there are some challenges, e.g., large latency variations due to the use of different paths, compounding false-positive rates, etc.
As far as I know, there is a duplicate-suppression system implemented in LightningFilter which could be modified to be applicable as an in-network system as well.

---
___
*[doc/EPIC.md, line 94 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPUr06-8l6v1dAUHZl:-MJS7sJc6kg0NDVsCJW1:b-6leiea) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/EPIC.md#L94)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Being able to send a packet every 0.1 microseconds is definitely possible, however, as an attacker you also need feedback from the network to get a result, i.e., success or fail. There you have to deal with latencies and processing costs. I don't think it's practical to bruteforce a SCION MAC, but I'm fine with leaving the path type filtering as the default. :+1: 
</blockquote></details>

In my opinion the on-path attackers are much more relevant than the brute-forcing issue: the latter was a real threat when we still had 3-byte MACs but is no longer practical now (in particular as sending 10M invalid packets per second for a day might be detectable... :grin: ).
___
*[doc/EPIC.md, line 100 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxo2W88lVSIeRkwXgV:-MJS8xmaA33PWlyfzgud:b-ptnzo9) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/EPIC.md#L100)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

Maybe it is a terminology issue but I also find `local interface` rather ambiguous when referring to end hosts/services in an AS.
Also, like Luke, not understand the how you would have any value in `ConsEgress` in such scenario.
</blockquote></details>

We often talk about "internal interface" to mean a virtual interface for all local hosts and services (i.e., `ConsIngress = 0` or `ConsEgress = 0`). I guess that's not standard terminology but we got so used to this that we don't notice any more.
I guess we can rewrite this to make it more clear and avoid this term.
___
*[doc/protocols/scion-header.rst, line 486 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPaCXU0AKPzbCZ96yc:-MJS9SFr30lP9BBpEAW5:bxkppei) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L486)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Unfortunately not. We have an issue internally for this, but it would be great if you could look into this.
</blockquote></details>

OK, will add an issue on github and add it to my TODO list. :+1: 


<!-- Sent from Reviewable.io -->

2020-10-12 15:55 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @lukedirtwalker, @scrye, @sgmonroy, and @shitz)

___
*[doc/EPIC.md, line 100 at r4](https://reviewable.io/reviews/scionproto/scion/3884#-MIxo2W88lVSIeRkwXgV:-MJSUfFX1P_ELgAppP1g:btvdpqj) ([raw file](https://github.com/scionproto/scion/blob/af94dfd8ee6490017ade83b1917251d64d20b0e1/doc/EPIC.md#L100)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

We often talk about "internal interface" to mean a virtual interface for all local hosts and services (i.e., `ConsIngress = 0` or `ConsEgress = 0`). I guess that's not standard terminology but we got so used to this that we don't notice any more.
I guess we can rewrite this to make it more clear and avoid this term.
</blockquote></details>

I changed the design document so that it does not use the term "local interface" anymore.
___
*[doc/protocols/scion-header.rst, line 542 at r2](https://reviewable.io/reviews/scionproto/scion/3884#-MIPaqJK7WbQ0o45kRTN:-MJSTSvF5KFFR5oq_cqQ:b-lwhswu) ([raw file](https://github.com/scionproto/scion/blob/c76e4fa0ab1631e4e2d6acf6d69b112e9c40716b/doc/protocols/scion-header.rst#L542)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

This does sound to me like application security policy.

On a stream connection the `S` bit semantics get weird. The concept of "the reply packet to a packet" doesn't make sense for streams in general, so I'm wondering what would the server even be expected to do if they receive packets with alternating `S` bits on the same stream.

So yeah, I agree with @shitz, I would let the applications decide these aspects based on apriori policy, or negotiate it at application level on the fly.
</blockquote></details>

Right, the packet header is probably not the ideal place to communicate this information.
I removed the S-flag now. It is the responsibility of the destination to have this configured / fetch this information.


<!-- Sent from Reviewable.io -->

2020-10-14 06:04 UTC, lukedirtwalker approved these changes
> Reviewed 5 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: all files reviewed, 4 unresolved discussions (waiting on @scrye, @sgmonroy, and @shitz)



<!-- Sent from Reviewable.io -->

2020-10-14 12:41 UTC, shitz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884#-:-MJb7LZ37kOgFXvJ67zt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @scrye)



<!-- Sent from Reviewable.io -->

2020-10-14 12:42 UTC, shitz approved these changes
> Reviewed 5 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: all files reviewed, 1 unresolved discussion (waiting on @scrye)



<!-- Sent from Reviewable.io -->

2020-10-14 14:03 UTC, scrye commented
*[a discussion](https://reviewable.io/reviews/scionproto/scion/3884#-MIybF3X5-EsRlQQcbo0:-MJbP0CT38mSaXWBxe0k:b-rzy57m) (no related file):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

What exactly do you mean with "how an architecture with replay suppression would look like"? The basic idea is that packets would be handed over to and tracked by a duplicate-suppression system after being authenticated by the border router. This system could be collocated with the border router or deployed somewhere else in an AS' network. The inspiration comes from the referenced 2017 paper (https://netsec.ethz.ch/publications/papers/replay2017.pdf) but there is no full design/implementation for SCION yet. I haven't looked at the details yet, but there are some challenges, e.g., large latency variations due to the use of different paths, compounding false-positive rates, etc.
As far as I know, there is a duplicate-suppression system implemented in LightningFilter which could be modified to be applicable as an in-network system as well.
</blockquote></details>

By architecture I meant the hosts/applications that make up the replay suppression system, and how they communicate with the other components in the network. I'm thinking packet latency, bandwidth, reliability in the eventuality of crashes, processing bottlenecks, etc. are all challenges that the architecture would have to deal with.

If it's out of scope for this, then ok, but if deployed it sounds like the replay suppression system will have a big impact on the security and performance of the overall system.

---


<!-- Sent from Reviewable.io -->

2020-10-14 14:04 UTC, scrye approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3884)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-14 14:59 UTC, shitz commented
/rebase

2020-10-14 15:00 UTC, merged