StaticInfoExtension to grpc (WIP)
scionproto/scion pull request #3899
Opened 2020-10-14 12:44 UTC by matzf

Add latency, geo coordinates and notes (rest will follow).
Simplify the representation of the data by using maps instead of lists,
in both the protocol and the related higher-level go structs.

Notes:
- not updating sciond/pathmeta.go for now, as that will be deleted.
- only minimal changes to the related (inactive) combinator code, as this will be revisited separately.

2020-10-22 12:54 UTC, lukedirtwalker requested changes
> Reviewed 4 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3899)* status: 4 of 19 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker and @matzf)

___
*[proto/control_plane/v1/seg_extensions.proto, line 60 at r1](https://reviewable.io/reviews/scionproto/scion/3899#-MKFL0Sz4FWBIjVhJDxg:-MKFL0T0Bb2dy20hhNR2:b-7tnjv0) ([raw file](https://github.com/scionproto/scion/blob/2c16c2252d7248d31858b3359f6f25989cef364f/proto/control_plane/v1/seg_extensions.proto#L60)):*
> ```
> ·
> ```
trailing space
___
*[proto/control_plane/v1/seg_extensions.proto, line 85 at r1](https://reviewable.io/reviews/scionproto/scion/3899#-MKFLVCM3Ut31PXhZLG6:-MKFLVCM3Ut31PXhZLG7:b48adts) ([raw file](https://github.com/scionproto/scion/blob/2c16c2252d7248d31858b3359f6f25989cef364f/proto/control_plane/v1/seg_extensions.proto#L85)):*
> ```
> interface the relevant
> ```
`and` missing?


<!-- Sent from Reviewable.io -->

2020-10-22 13:58 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3899)* status: 4 of 19 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[proto/control_plane/v1/seg_extensions.proto, line 60 at r1](https://reviewable.io/reviews/scionproto/scion/3899#-MKFL0Sz4FWBIjVhJDxg:-MKFaZ49DPOEan29Y3Jt:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/2c16c2252d7248d31858b3359f6f25989cef364f/proto/control_plane/v1/seg_extensions.proto#L60)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> ·
> ```
trailing space
</blockquote></details>

Done.
___
*[proto/control_plane/v1/seg_extensions.proto, line 85 at r1](https://reviewable.io/reviews/scionproto/scion/3899#-MKFLVCM3Ut31PXhZLG6:-MKFaZo6Ayf6343MnSS_:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/2c16c2252d7248d31858b3359f6f25989cef364f/proto/control_plane/v1/seg_extensions.proto#L85)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> interface the relevant
> ```
`and` missing?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-26 09:12 UTC, lukedirtwalker requested changes
> Reviewed 5 of 19 files at r1, 7 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3899)* status: 16 of 18 files reviewed, 27 unresolved discussions (waiting on @lukedirtwalker and @matzf)

___
*[go/cs/beaconing/staticinfo_config.go, line 116 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYb3Es9YCOxZq4UzOh:-MKYb3Es9YCOxZq4UzOi:b-yyxuyv) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/cs/beaconing/staticinfo_config.go#L116)):*
> ```Go
> }
> 
> func (cfg StaticInfoCfg) gather(ifType map[common.IFIDType]topology.LinkType,
> ```

this could be directly inlined in the `Generate` method, or is there a specific reason for this to be separate?
___
*[go/cs/beaconing/staticinfo_config.go, line 130 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYaY1h0moBUYkRiI3y:-MKYaY1h0moBUYkRiI3z:btcdv7h) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/cs/beaconing/staticinfo_config.go#L130)):*
> ```
> inserts 
> ```
the comments on those methods are not 100% correct. It doesn't insert it just creates. I wonder if we should rename the methods to `create*` or `generate*`
___
*[go/cs/beaconing/staticinfo_config.go, line 138 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYdqp7E3KQdiFL6lf-:-MKYdqp7E3KQdiFL6lf0:b-ptoqcn) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/cs/beaconing/staticinfo_config.go#L138)):*
> ```Go
> 		Inter: make(map[common.IFIDType]time.Duration),
> 	}
> 	if egress != 0 {
> ```

isn't the `Intra` map just empty for the `0` ? 
___
*[go/cs/beaconing/staticinfo_config.go, line 163 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYco4gEOgFoaRBZaH3:-MKYco4gEOgFoaRBZaH4:b-7x6348) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/cs/beaconing/staticinfo_config.go#L163)):*
> ```Go
> 		Inter: make(map[common.IFIDType]uint32),
> 	}
> 	if _, ok := cfg.Bandwidth[egress]; egress != 0 && ok {
> ```

hm why doesn't that use the exact same pattern as the method above?
___
*[go/cs/beaconing/staticinfo_config.go, line 164 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYd5VLAQwoqmJSzXn8:-MKYd5VLAQwoqmJSzXn9:b-nt2dwd) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/cs/beaconing/staticinfo_config.go#L164)):*
> ```Go
> 	}
> 	if _, ok := cfg.Bandwidth[egress]; egress != 0 && ok {
> 		bw.Inter[egress] = cfg.Bandwidth[egress].Inter
> ```

isn't that already handled by the loop below?
___
*[go/cs/beaconing/staticinfo_config.go, line 201 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYdWEtAgB7gAsK8CAK:-MKYdWEtAgB7gAsK8CAL:bspq7rp) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/cs/beaconing/staticinfo_config.go#L201)):*
> ```Go
> 
> 	ihi := make(seg.InternalHopsInfo)
> 	for ifid, v := range cfg.Hops[egress].Intra {
> ```

why do we not need the `egress != 0` check here but we need it above in the other methods?
___
*[go/cs/beaconing/staticinfo_config.go, line 255 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYbUM6-xQORN95TWP0:-MKYbUM6-xQORN95TWP1:b-3rb4m4) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/cs/beaconing/staticinfo_config.go#L255)):*
> ```Go
> 
> func interfaceTypeTable(intfs *ifstate.Interfaces) map[common.IFIDType]topology.LinkType {
> 	ifTypes := make(map[common.IFIDType]topology.LinkType)
> ```

we should use the correct size for allocation:
```go
	ifMap := intfs.All()
	ifTypes := make(map[common.IFIDType]topology.LinkType, len(ifMap))
	for ifID, ifInfo := range ifMap {
```
___
*[go/lib/ctrl/seg/staticinfo_extn.go, line 15 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKZ6ssH9pmT50IDtx1a:-MKZ6ssH9pmT50IDtx1b:b-b4pj4h) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/ctrl/seg/staticinfo_extn.go#L15)):*
> ```Go
> // limitations under the License.
> 
> package seg
> ```

hm I think we should move this to a separate package. For example having `LinkType` in the `seg` package might be confusing in the future since it might not be clear that it belongs to the StaticInfo extension only.

Either we create a `seg/extensions` package and rename the type so using it becomes `extensions.StaticInfo`
or we create a `seg/extensions/staticinfo` package and rename the type so using it becomes `staticinfo.Extension`

from reading I like the first one better, but I think it's cleaner to have separate packages per extension.

or maybe you have a better proposal?
  
___
*[go/lib/ctrl/seg/staticinfo_extn.go, line 25 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYi7J95sbEfJ_osW6I:-MKYi7J95sbEfJ_osW6J:bdos2d5) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/ctrl/seg/staticinfo_extn.go#L25)):*
> ```Go
> )
> 
> type StaticInfoExtension struct {
> ```

I think this and all other structs could have some documentation.
___
*[go/lib/ctrl/seg/staticinfo_extn.go, line 26 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYfelB2kXcQy-BivdW:-MKYfelB2kXcQy-BivdX:bwpsbi) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/ctrl/seg/staticinfo_extn.go#L26)):*
> ```
> *LatencyInfo
> ```
I don't think, this and the entry below need to be pointer entries, since the structs are that simple.
___
*[go/lib/ctrl/seg/staticinfo_extn.go, line 102 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYiQt19STTwsZ19XtQ:-MKYiQt28h_u7i65U-81:b-ojvy71) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/ctrl/seg/staticinfo_extn.go#L102)):*
> ```Go
> }
> 
> func latencyInfoFromPB(pb *cppb.LatencyInfo) (*LatencyInfo, error) {
> ```

never returns an error, remove it from the signature.
___
*[go/lib/ctrl/seg/staticinfo_extn.go, line 106 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYjhin5fsVyIs8O3QI:-MKYjhioCHO4lrpNzJNV:b-gghx2h) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/ctrl/seg/staticinfo_extn.go#L106)):*
> ```Go
> 		return nil, nil
> 	}
> 	intra := make(map[common.IFIDType]time.Duration)
> ```

here and everywhere else us the `len` of the existing map for allocation.
___
*[go/lib/ctrl/seg/staticinfo_extn.go, line 120 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYiV7D9gzK3V750epd:-MKYiV7D9gzK3V750epe:b-ojvy71) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/ctrl/seg/staticinfo_extn.go#L120)):*
> ```Go
> }
> 
> func bandwidthInfoFromPB(pb *cppb.BandwidthInfo) (*BandwidthInfo, error) {
> ```

never returns an error, remove it from the signature.
___
*[go/lib/ctrl/seg/staticinfo_extn.go, line 138 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYiW7j-rfXElseep5T:-MKYiW7j-rfXElseep5U:b-ojvy71) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/ctrl/seg/staticinfo_extn.go#L138)):*
> ```Go
> }
> 
> func geoInfoFromPB(pb map[uint64]*cppb.GeoCoordinates) (GeoInfo, error) {
> ```

never returns an error, remove it from the signature.
___
*[go/lib/ctrl/seg/staticinfo_extn.go, line 164 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYk2Hz4fQYuY4Woh9v:-MKYk2Hz4fQYuY4Woh9w:b-ta3u2r) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/ctrl/seg/staticinfo_extn.go#L164)):*
> ```
> option
> ```
I think this word is not needed.
___
*[go/lib/ctrl/seg/staticinfo_extn.go, line 164 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYloKvC5P8FGGa961x:-MKYloKvC5P8FGGa961y:bz90t6n) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f [...]

2020-10-27 08:25 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3899)* status: 7 of 20 files reviewed, 27 unresolved discussions (waiting on @lukedirtwalker and @matzf)

___
*[go/lib/ctrl/seg/staticinfo_extn.go, line 15 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKZ6ssH9pmT50IDtx1a:-MKd6mmG4q0lUceKu3e9:b-gxhr08) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/ctrl/seg/staticinfo_extn.go#L15)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

hm I think we should move this to a separate package. For example having `LinkType` in the `seg` package might be confusing in the future since it might not be clear that it belongs to the StaticInfo extension only.

Either we create a `seg/extensions` package and rename the type so using it becomes `extensions.StaticInfo`
or we create a `seg/extensions/staticinfo` package and rename the type so using it becomes `staticinfo.Extension`

from reading I like the first one better, but I think it's cleaner to have separate packages per extension.

or maybe you have a better proposal?
  
</blockquote></details>

Done, moved to `seg/extensions/staticinfo`.
___
*[go/lib/ctrl/seg/staticinfo_extn.go, line 25 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYi7J95sbEfJ_osW6I:-MKd8_7J6wNOqjyCf-C4:bdcor9s) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/ctrl/seg/staticinfo_extn.go#L25)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I think this and all other structs could have some documentation.
</blockquote></details>

Done. I've only added some dummy comments that refer to the more detailed documentation in the protobuf definitions. Otherwise, it would be identical comments, which seems nasty for maintenance.


<!-- Sent from Reviewable.io -->

2020-10-27 10:16 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3899)* status: 5 of 20 files reviewed, 26 unresolved discussions (waiting on @lukedirtwalker)

___
*[go/cs/beaconing/staticinfo_config.go, line 116 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYb3Es9YCOxZq4UzOh:-MKdSnjzDiTbVr9efy7I:bc48h9q) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/cs/beaconing/staticinfo_config.go#L116)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

this could be directly inlined in the `Generate` method, or is there a specific reason for this to be separate?
</blockquote></details>

It's used in the test, so we can directly pass in this `ifType` map.
___
*[go/cs/beaconing/staticinfo_config.go, line 130 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYaY1h0moBUYkRiI3y:-MKdXdBD5ctFAT7Z_L9p:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/cs/beaconing/staticinfo_config.go#L130)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> inserts 
> ```
the comments on those methods are not 100% correct. It doesn't insert it just creates. I wonder if we should rename the methods to `create*` or `generate*`
</blockquote></details>

Done.
___
*[go/cs/beaconing/staticinfo_config.go, line 138 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYdqp7E3KQdiFL6lf-:-MKdVBlND3W2F5SjKOoy:b-5lrl3v) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/cs/beaconing/staticinfo_config.go#L138)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

isn't the `Intra` map just empty for the `0` ? 
</blockquote></details>

True. Done.
We should validate that some prankster doesn't use 0 interface IDs in the configuration file then :) I';; do this separately, there is another existing TODO regarding validation of this configuration file. And the configuration file syntax is a bit ... meh anyway.
___
*[go/cs/beaconing/staticinfo_config.go, line 163 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYco4gEOgFoaRBZaH3:-MKdUUpkEyTzbMaHr6hf:bt2vr1b) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/cs/beaconing/staticinfo_config.go#L163)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

hm why doesn't that use the exact same pattern as the method above?
</blockquote></details>

Fixed.
___
*[go/cs/beaconing/staticinfo_config.go, line 164 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYd5VLAQwoqmJSzXn8:-MKdUUZ-8N7UmsSeUNmV:b-tuomwa) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/cs/beaconing/staticinfo_config.go#L164)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

isn't that already handled by the loop below?
</blockquote></details>

Right! Done.
___
*[go/cs/beaconing/staticinfo_config.go, line 201 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYdWEtAgB7gAsK8CAK:-MKdW0q0Dok6SJJtaJIE:bhb1y4e) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/cs/beaconing/staticinfo_config.go#L201)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

why do we not need the `egress != 0` check here but we need it above in the other methods?
</blockquote></details>

Removed the checks above. Done.
___
*[go/cs/beaconing/staticinfo_config.go, line 255 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYbUM6-xQORN95TWP0:-MKdMqzRB_pIwHk88ees:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/cs/beaconing/staticinfo_config.go#L255)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

we should use the correct size for allocation:
```go
	ifMap := intfs.All()
	ifTypes := make(map[common.IFIDType]topology.LinkType, len(ifMap))
	for ifID, ifInfo := range ifMap {
```
</blockquote></details>

Done.
___
*[go/lib/infra/modules/combinator/graph.go, line 559 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYfGTQ5M6Z1GxWInE9:-MKdNTc47KMIV18Klf0Y:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/infra/modules/combinator/graph.go#L559)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> extensions
> ```
why extensions? it's just the whole ASEntry isn't it?
</blockquote></details>

Done.
___
*[go/lib/infra/modules/combinator/staticinfo_accumulator.go, line 24 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYnOwU2t4Fhy61HGO7:-MKdO-jE2Sqr0KrzGytp:bkx50vl) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/infra/modules/combinator/staticinfo_accumulator.go#L24)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

this comment should also specify the latency unit.
</blockquote></details>

Done. Btw. also changed the type to 64bit; probably doesn't hurt and allows values > 4Tbit/s (which seems not entirely inconceivable).
___
*[go/lib/infra/modules/combinator/staticinfo_accumulator.go, line 102 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYt7hH9gulMc30lk6v:-MKdOzGZ7-nUczlr2ueS:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/infra/modules/combinator/staticinfo_accumulator.go#L102)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> Were
> ```
We're
</blockquote></details>

Done.
___
*[go/lib/infra/modules/combinator/staticinfo_accumulator.go, line 113 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKYtieW7S9Nd2n2weFd:-MKdOvs4B45PI-o06MJy:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/infra/modules/combinator/staticinfo_accumulator.go#L113)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

we usually go for less indentation.
```go
if staticInfo == nil || staticInfo.Latency == nil {
   continue
}
```
</blockquote></details>

Done.
___
*[go/lib/infra/modules/combinator/staticinfo_accumulator.go, line 211 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKZAWE_EqEuQ1VYf2oU:-MKdPMxC1vKa9s2DO0xI:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/infra/modules/combinator/staticinfo_accumulator.go#L211)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

use negation and `continue`
</blockquote></details>

Done.
___
*[go/lib/infra/modules/combinator/staticinfo_accumulator.go, line 232 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKZANnd4faLyqwDj5wI:-MKdPO0dCxO-aTlb88CC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/infra/modules/combinator/staticinfo_accumulator.go#L232)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

us `if staticInfo == nil {continue}`
</blockquote></details>

Done.
___
*[go/lib/infra/modules/combinator/staticinfo_accumulator.go, line 285 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKZASct-BRhztG981EO:-MKdPXIOD4SDKIxJHsPz:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/infra/modules/combinator/staticinfo_accumulator.go#L285)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

use negation and `continue`
</ [...]

2020-10-28 07:10 UTC, lukedirtwalker reviewed
> Reviewed 15 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3899)* status: 18 of 20 files reviewed, all discussions resolved (waiting on @lukedirtwalker)

___
*[go/lib/infra/modules/combinator/staticinfo_accumulator.go, line 337 at r2](https://reviewable.io/reviews/scionproto/scion/3899#-MKZ93jc1s7z0_gAgeWh:-MKi1RZH7c928utklu8W:b-binenc) ([raw file](https://github.com/scionproto/scion/blob/5e70e44566400d7561f22d71ab5d533ccd58e990/go/lib/infra/modules/combinator/staticinfo_accumulator.go#L337)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Unfortunately this wouldn't give a stable order of the notes, so the concatenated notes could be randomly reordered.

Btw. I think a simpler implementation could be to collect the notes directly in a `map[addr.IA]string` and append to the note if a second entry is not identical to the existing. This would work "correctly" as long as there are only two AS entries for an IA on the path (which should usually be the case, right?), but would do something a bit weird with more than two entries (if some of the notes are different...).
Would seem like a good compromise?
</blockquote></details>

Ah ok, we can also leave it like this.


<!-- Sent from Reviewable.io -->

2020-10-28 09:28 UTC, lukedirtwalker requested changes
> Reviewed 2 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3899)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf)

___
*[go/lib/infra/modules/combinator/staticinfo_accumulator_test.go, line 134 at r3](https://reviewable.io/reviews/scionproto/scion/3899#-MKiWIoy5qdNoxEizR9w:-MKiWIoy5qdNoxEizR9x:bfsm94f) ([raw file](https://github.com/scionproto/scion/blob/625d38930cdb7aac0f4e4609ee397016f279f93a/go/lib/infra/modules/combinator/staticinfo_accumulator_test.go#L134)):*
> ```Go
> 
> 	if len(path) == 0 {
> 		assert.Equal(t, 0, len(latency))
> ```

`assert.Empty(t, latency)` here and everywhere else.
___
*[go/lib/infra/modules/combinator/staticinfo_accumulator_test.go, line 140 at r3](https://reviewable.io/reviews/scionproto/scion/3899#-MKiVnJf5xM69qsEiU3U:-MKiVnJf5xM69qsEiU3V:b-3uqjip) ([raw file](https://github.com/scionproto/scion/blob/625d38930cdb7aac0f4e4609ee397016f279f93a/go/lib/infra/modules/combinator/staticinfo_accumulator_test.go#L140)):*
> ```Go
> 	expected := []time.Duration{}
> 	for i := 0; i < len(path)-1; i++ {
> 		ifid_a := path[i].ID
> ```

`snake_case` is not really Go style. Please use camelCase instead. Maybe you can just directly use `path[i].ID``in the method call below?

here and in the rest of the file.
___
*[go/lib/infra/modules/combinator/staticinfo_accumulator_test.go, line 193 at r3](https://reviewable.io/reviews/scionproto/scion/3899#-MKiWaN494GyA_1_3NrL:-MKiWaN494GyA_1_3NrM:b-pkwmlb) ([raw file](https://github.com/scionproto/scion/blob/625d38930cdb7aac0f4e4609ee397016f279f93a/go/lib/infra/modules/combinator/staticinfo_accumulator_test.go#L193)):*
> ```
> })
> ```
I think it's slightly cleaner to move this to a new line.


<!-- Sent from Reviewable.io -->

2020-10-28 12:47 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3899)* status: all files reviewed, 3 unresolved discussions (waiting on @lukedirtwalker)

___
*[go/lib/infra/modules/combinator/staticinfo_accumulator_test.go, line 134 at r3](https://reviewable.io/reviews/scionproto/scion/3899#-MKiWIoy5qdNoxEizR9w:-MKjAOho9cv3JxKCRUv8:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/625d38930cdb7aac0f4e4609ee397016f279f93a/go/lib/infra/modules/combinator/staticinfo_accumulator_test.go#L134)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

`assert.Empty(t, latency)` here and everywhere else.
</blockquote></details>

Done.
___
*[go/lib/infra/modules/combinator/staticinfo_accumulator_test.go, line 140 at r3](https://reviewable.io/reviews/scionproto/scion/3899#-MKiVnJf5xM69qsEiU3U:-MKjAnwW1w5LW7zPZjmE:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/625d38930cdb7aac0f4e4609ee397016f279f93a/go/lib/infra/modules/combinator/staticinfo_accumulator_test.go#L140)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

`snake_case` is not really Go style. Please use camelCase instead. Maybe you can just directly use `path[i].ID``in the method call below?

here and in the rest of the file.
</blockquote></details>

Done.
___
*[go/lib/infra/modules/combinator/staticinfo_accumulator_test.go, line 193 at r3](https://reviewable.io/reviews/scionproto/scion/3899#-MKiWaN494GyA_1_3NrL:-MKjAv7K3bBbknWOZj4-:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/625d38930cdb7aac0f4e4609ee397016f279f93a/go/lib/infra/modules/combinator/staticinfo_accumulator_test.go#L193)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> })
> ```
I think it's slightly cleaner to move this to a new line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 13:22 UTC, lukedirtwalker approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3899)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-28 13:24 UTC, merged