combinator: avoid returning duplicate paths
scionproto/scion pull request #3930
Opened 2020-11-12 20:49 UTC by matzf

Duplicate paths can occur when multiple combinations of different path
segments result in identical sequences of path interfaces path after
applying short-cuts.

The old behaviour was to return all paths found. The rational for this
was that from a crypto point of view the paths are different; this made
sense with the old path header format, where shortcuts would include a
verify-only hop field that was realy separate from the effectively used
hop fields.
Now with the new path header format, the sequence of the hop fields for
such duplicate paths is really identical, the only differences are the
segment IDs and the MACs. While it's still conceivable that an AS could
misbehave and change the forwarding behaviour based on the segment IDs
or MACs, this would be really an exceptional case.
Thus, the new behaviour of the combinator is to return only one path for
each unique sequence of path interfaces found. If there are multiple
ways to construct the same sequence of path interfaces from the
available path segments, the construction with latest expiration time
will be returned.

To keep this change simple, duplicates are filtered in a separate
post-processing step. In a future change, duplicates could/should be
avoided directly by reducing the available options in the graph, as we
could potentially create a large number of duplicates in wide network
topologies.

2020-11-17 08:10 UTC, marcfrei reviewed
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3930)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-25 12:06 UTC, scrye requested changes
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3930)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/3930#-MMzGZ-FDnGflYyHG0TI:-MMzGZ-GDnzem2FXyZBz:b9ahkx2) (no related file):*
Some typos in the commit message:
- rational  -> rationale
- realy -> really
- identicaly -> identical

---
___
*[go/lib/infra/modules/combinator/combinator.go, line 110 at r2](https://reviewable.io/reviews/scionproto/scion/3930#-MMzH51TAzU3xxNzUfzz:-MMzH51TAzU3xxNzUg--:b-lltt53) ([raw file](https://github.com/scionproto/scion/blob/aa60c6ebff32245c52909bd1afd6f99280c4374a/go/lib/infra/modules/combinator/combinator.go#L110)):*
> ```Go
> // available options in the graph, as we could potentially create a large
> // number of duplicates in wide network topologies.
> func filterDuplicates(paths []Path) []Path {
> ```

Add unit tests for `filterDuplicates`. Use the export file pattern to unit test an unexported function. See the below for an example:

https://github.com/scionproto/scion/blob/ae63a60fe8ade106230f20a6e6eb086529f7a2e0/go/pkg/cs/trust/grpc/export_test.go#L15-L22
___
*[go/lib/infra/modules/combinator/combinator.go, line 111 at r2](https://reviewable.io/reviews/scionproto/scion/3930#-MMzFbIU4DkR30I6iZcV:-MMzFbIU4DkR30I6iZcW:b1hrypd) ([raw file](https://github.com/scionproto/scion/blob/aa60c6ebff32245c52909bd1afd6f99280c4374a/go/lib/infra/modules/combinator/combinator.go#L111)):*
> ```Go
> // number of duplicates in wide network topologies.
> func filterDuplicates(paths []Path) []Path {
> ```

Remove newline.


<!-- Sent from Reviewable.io -->

2020-11-25 12:06 UTC, scrye reviewed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3930)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2020-11-25 15:20 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3930)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @marcfrei and @scrye)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/3930#-MMzGZ-FDnGflYyHG0TI:-MMzP-af8yc5C5lHEf7d:b-896fix) (no related file):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Some typos in the commit message:
- rational  -> rationale
- realy -> really
- identicaly -> identical
</blockquote></details>

Done.

---
___
*[go/lib/infra/modules/combinator/combinator.go, line 110 at r2](https://reviewable.io/reviews/scionproto/scion/3930#-MMzH51TAzU3xxNzUfzz:-MMzzVUL-y6yq4LCNnqj:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/aa60c6ebff32245c52909bd1afd6f99280c4374a/go/lib/infra/modules/combinator/combinator.go#L110)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Add unit tests for `filterDuplicates`. Use the export file pattern to unit test an unexported function. See the below for an example:

https://github.com/scionproto/scion/blob/ae63a60fe8ade106230f20a6e6eb086529f7a2e0/go/pkg/cs/trust/grpc/export_test.go#L15-L22
</blockquote></details>

Done.
___
*[go/lib/infra/modules/combinator/combinator.go, line 111 at r2](https://reviewable.io/reviews/scionproto/scion/3930#-MMzFbIU4DkR30I6iZcV:-MMzPaQJ-rzBC6rD4Wp3:b2nhll9) ([raw file](https://github.com/scionproto/scion/blob/aa60c6ebff32245c52909bd1afd6f99280c4374a/go/lib/infra/modules/combinator/combinator.go#L111)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Remove newline.
</blockquote></details>

Ok.


<!-- Sent from Reviewable.io -->

2020-11-27 08:27 UTC, scrye requested changes
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3930)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[go/lib/infra/modules/combinator/combinator_test.go, line 596 at r3](https://reviewable.io/reviews/scionproto/scion/3930#-MN7nXNHDhTxgihyaiUz:-MN7nXNIBIu36nA0HcaS:b591x4r) ([raw file](https://github.com/scionproto/scion/blob/2bc3fde1919c12249d2e1b4ba3327f7fb1efa6ba/go/lib/infra/modules/combinator/combinator_test.go#L596)):*
> ```Go
> 		Expected []uint32
> 	}{
> 		{
> ```

Add tests for nil input slice and empty input slice.


<!-- Sent from Reviewable.io -->

2020-11-27 09:37 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3930)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @scrye)

___
*[go/lib/infra/modules/combinator/combinator_test.go, line 596 at r3](https://reviewable.io/reviews/scionproto/scion/3930#-MN7nXNHDhTxgihyaiUz:-MN83-2q7qVfMt2wIt5q:bl1h72v) ([raw file](https://github.com/scionproto/scion/blob/2bc3fde1919c12249d2e1b4ba3327f7fb1efa6ba/go/lib/infra/modules/combinator/combinator_test.go#L596)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Add tests for nil input slice and empty input slice.
</blockquote></details>

Ok, done.


<!-- Sent from Reviewable.io -->

2020-11-27 11:33 UTC, scrye approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3930)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-27 13:33 UTC, matzf commented
/rebase

2020-11-27 15:38 UTC, scrye approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3930)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2020-11-27 15:39 UTC, merged