gateway: determine default local IP
scionproto/scion pull request #3936
Opened 2020-11-24 12:24 UTC by matzf

Determine default local IP for SIG as documented in config sample,
analogous to old SIG implementation.
Instead of copying the findDefaultLocalIP logic again, move to
addrutil.DefaultLocalIP library function.

Additionally includes losely related small cleanup in
sciond.TopologyQuerier.

Closes #3933.

2020-11-26 07:21 UTC, Oncilla approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3936#-:-MN2QKGLD7sccSjRnnwj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf and @scrye)

___
*[go/lib/snet/addrutil/addrutil.go, line 103 at r1](https://reviewable.io/reviews/scionproto/scion/3936#-MN2PaLw2w9ezXG7x-ny:-MN2PaLx-bNrKsnrf9_x:b-s7z9v3) ([raw file](https://github.com/scionproto/scion/blob/9ae8256dab692ee00084422804bde83ddf48466f/go/lib/snet/addrutil/addrutil.go#L103)):*
> ```Go
> // This returns a sensible but arbitrary local IP. In the general case the
> // local IP would depend on the next hop of selected path. This approach will
> // not work in more complicated setups where e.g. different network interface
> ```

s/interface/interfaces


<!-- Sent from Reviewable.io -->

2020-11-26 07:47 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3936)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @Oncilla and @scrye)

___
*[go/lib/snet/addrutil/addrutil.go, line 103 at r1](https://reviewable.io/reviews/scionproto/scion/3936#-MN2PaLw2w9ezXG7x-ny:-MN2WAM90Xcm0hv36EHb:b-689a8e) ([raw file](https://github.com/scionproto/scion/blob/9ae8256dab692ee00084422804bde83ddf48466f/go/lib/snet/addrutil/addrutil.go#L103)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

s/interface/interfaces
</blockquote></details>

Well spotted :eyes:  Done.


<!-- Sent from Reviewable.io -->

2020-11-26 07:50 UTC, Oncilla approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3936)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @scrye)



<!-- Sent from Reviewable.io -->

2020-11-27 08:39 UTC, scrye requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3936)* status: all files reviewed, 4 unresolved discussions (waiting on @matzf)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/3936#-MN7qP4E9-GUmtTrENfp:-MN7qP4E9-GUmtTrENfq:b-uhxxoi) (no related file):*
I was thinking about adding a request for documenting the behavior in the Gateway manual, but I think I'll take care of that afterwards (the behaviors for some configuration options are quite complex, and need a lot of documentation).

Found a few nits here and there, but otherwise we can merge this.

---
___
*[go/lib/snet/addrutil/addrutil.go, line 99 at r2](https://reviewable.io/reviews/scionproto/scion/3936#-MN7oPe48pWmaBSqepNF:-MN7oPe48pWmaBSqepNG:bc6ej57) ([raw file](https://github.com/scionproto/scion/blob/be142c961cae9a4ad541298dcf796fe5867f969a/go/lib/snet/addrutil/addrutil.go#L99)):*
> ```Go
> }
> 
> // DefaultLocalIP returns _a_ IP of this host in the local AS.
> ```

Nit: "a" -> "an"
___
*[go/lib/snet/addrutil/addrutil.go, line 107 at r2](https://reviewable.io/reviews/scionproto/scion/3936#-MN7oWpd5fTuUtWu1f9h:-MN7oWpd5fTuUtWu1f9i:bog37kw) ([raw file](https://github.com/scionproto/scion/blob/be142c961cae9a4ad541298dcf796fe5867f969a/go/lib/snet/addrutil/addrutil.go#L107)):*
> ```Go
> //
> // This is a simple workaround for not being able to use wildcard addresses
> // with snet. Once a available, a wildcard address should be used instead and
> ```

Remove "a" before "available".
___
*[go/lib/snet/addrutil/addrutil.go, line 108 at r2](https://reviewable.io/reviews/scionproto/scion/3936#-MN7o_El0Pw7aWrOALoc:-MN7o_Em4ghAYEgYhS9q:bumolkt) ([raw file](https://github.com/scionproto/scion/blob/be142c961cae9a4ad541298dcf796fe5867f969a/go/lib/snet/addrutil/addrutil.go#L108)):*
> ```Go
> // This is a simple workaround for not being able to use wildcard addresses
> // with snet. Once a available, a wildcard address should be used instead and
> // this should simply be removed.
> ```

Remove "simply".


<!-- Sent from Reviewable.io -->

2020-11-27 09:27 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3936)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @Oncilla and @scrye)

___
*[go/lib/snet/addrutil/addrutil.go, line 107 at r2](https://reviewable.io/reviews/scionproto/scion/3936#-MN7oWpd5fTuUtWu1f9h:-MN80h_y9cZ-d4SVbV9E:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/be142c961cae9a4ad541298dcf796fe5867f969a/go/lib/snet/addrutil/addrutil.go#L107)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Remove "a" before "available".
</blockquote></details>

Done.
___
*[go/lib/snet/addrutil/addrutil.go, line 108 at r2](https://reviewable.io/reviews/scionproto/scion/3936#-MN7o_El0Pw7aWrOALoc:-MN80hz6DQu17DCWuPL3:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/be142c961cae9a4ad541298dcf796fe5867f969a/go/lib/snet/addrutil/addrutil.go#L108)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Remove "simply".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-27 10:35 UTC, Oncilla approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3936)* status: all files reviewed, 3 unresolved discussions (waiting on @scrye)



<!-- Sent from Reviewable.io -->

2020-11-27 11:32 UTC, scrye approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3936)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-27 11:33 UTC, merged