showpaths: show extended metadata
scionproto/scion pull request #3942
Opened 2020-11-25 17:22 UTC by matzf

Added extended metadata items to human readable showpaths output.
Restructure colored path output to allow line wrapping for the entries.

Example output to demonstrate the line-wrapping:
```
Available paths to 1-ff00:0:112
3 Hops:
[0] Hops: [1-ff00:0:111 41>1 1-ff00:0:110 2>1 1-ff00:0:112]
    MTU: 1280
    NextHop: 127.0.0.17:31014
    Expires: 2020-11-25 23:14:49 +0000 UTC (5h57m24s)
    Latency: N/A
    Bandwidth: N/A
    Geo: []
    LinkType: [unset, unset]
    InternalHops: []
    Notes: []
    Status: alive
    LocalIP: 127.0.0.1
```

Replaces #3779

2020-12-08 11:46 UTC, lukedirtwalker requested changes
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3942)* status: all files reviewed, 4 unresolved discussions (waiting on @matzf)

___
*[go/pkg/showpaths/showpaths.go, line 67 at r1](https://reviewable.io/reviews/scionproto/scion/3942#-MO17LWBDe7Vl-N7Ck6K:-MO17LWC5ZLa4fPJ9un4:bu8ilkh) ([raw file](https://github.com/scionproto/scion/blob/a18c576dfcb965d72b5bbec5928504156a30dd64/go/pkg/showpaths/showpaths.go#L67)):*
> ```Go
> 	cs := app.DefaultColorScheme(!colored)
> 
> 	/*
> ```

what's that? leftover?
___
*[go/pkg/showpaths/showpaths.go, line 76 at r1](https://reviewable.io/reviews/scionproto/scion/3942#-MO18pECBgMzIiFo7lyS:-MO18pECBgMzIiFo7lyT:byoyykz) ([raw file](https://github.com/scionproto/scion/blob/a18c576dfcb965d72b5bbec5928504156a30dd64/go/pkg/showpaths/showpaths.go#L76)):*
> ```Go
> 	entrySeparator := " "
> 	if showExtendedMetadata {
> 		entrySeparator = "\n" + strings.Repeat(" ", idxWidth+2+1)
> ```

maybe add some comment here what is done.
___
*[go/pkg/showpaths/showpaths.go, line 217 at r1](https://reviewable.io/reviews/scionproto/scion/3942#-MO19_MoB6onEOLAAb0I:-MO19_MoB6onEOLAAb0J:biccfim) ([raw file](https://github.com/scionproto/scion/blob/a18c576dfcb965d72b5bbec5928504156a30dd64/go/pkg/showpaths/showpaths.go#L217)):*
> ```
> qutation
> ```
quotation
___
*[go/scion/showpaths.go, line 117 at r1](https://reviewable.io/reviews/scionproto/scion/3942#-MO0yn7i47CKCYj5m5m8:-MO0yn7j2PgRWJV3EF2x:b-i22ixy) ([raw file](https://github.com/scionproto/scion/blob/6abe062f1d8854b3bdd926c2916da5c93726732c/go/scion/showpaths.go#L117)):*
> ```Go
> 	cmd.Flags().IntVarP(&flags.cfg.MaxPaths, "maxpaths", "m", 10,
> 		"Maximum number of paths that are displayed")
> 	cmd.Flags().BoolVarP(&flags.expiration, "expiration", "e", false,
> ```

I think we should keep that file. Having expiration information can be quite helpful for operations. In a system where static meta information is not setup I think seeing:
```
[0] Hops: [1-ff00:0:111 41>1 1-ff00:0:110 2>1 1-ff00:0:112]
    MTU: 1280
    NextHop: 172.20.0.26:30042
    Expires: 2020-12-08 16:47:52 +0000 UTC (5h57m15s)
    Latency: N/A
    Bandwidth: N/A
    Geo: []
    LinkType: [unset, unset]
    InternalHops: []
    Notes: []
    Status: alive
    LocalIP: 172.20.0.27
```
makes no sense.

We should keep the current `--expiration` and `-e` behavior and add `--extended` as an additional feature.


<!-- Sent from Reviewable.io -->

2020-12-08 14:55 UTC, lukedirtwalker reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3942)* status: all files reviewed, 5 unresolved discussions (waiting on @matzf)

___
*[go/pkg/app/helper.go, line 64 at r1](https://reviewable.io/reviews/scionproto/scion/3942#-MO1ppGj7ZUidtglZwqG:-MO1ppGj7ZUidtglZwqH:b-qi95gv) ([raw file](https://github.com/scionproto/scion/blob/a18c576dfcb965d72b5bbec5928504156a30dd64/go/pkg/app/helper.go#L64)):*
> ```Go
> // ChoosePath selects a path to the remote.
> func ChoosePath(ctx context.Context, conn sciond.Connector, remote addr.IA,
> 	interactive, refresh bool, seq string, cs ColorScheme) (snet.Path, error) {
> ```

So I checked back with @oncilla and it would be nice to have actual PathOptions. So the API of this method would only be:
`ChosePath(ctx context.Context, conn sciond.Connector, remote addr.IA, opts ...PathOption)`
and we'd have PathOptions like this:
```
func WithColorScheme(scheme ColorScheme) PathOption
func WithInteractive(interactive bool) PathOption 
```
now this actually goes a bit out of scope for this PR, so if you feel like doing that, I would be happy, otherwise I'm also fine if you don't do it. (thus non-blocking)


<!-- Sent from Reviewable.io -->

2020-12-09 14:32 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3942)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @lukedirtwalker and @matzf)

___
*[go/pkg/showpaths/showpaths.go, line 67 at r1](https://reviewable.io/reviews/scionproto/scion/3942#-MO17LWBDe7Vl-N7Ck6K:-MO6oXqv2NQZyOqv0Jzu:bmonfdi) ([raw file](https://github.com/scionproto/scion/blob/a18c576dfcb965d72b5bbec5928504156a30dd64/go/pkg/showpaths/showpaths.go#L67)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

what's that? leftover?
</blockquote></details>

Indeed! Sorry, removed.
___
*[go/pkg/showpaths/showpaths.go, line 76 at r1](https://reviewable.io/reviews/scionproto/scion/3942#-MO18pECBgMzIiFo7lyS:-MO6pRb-3xY1pDfpk517:bfbq99i) ([raw file](https://github.com/scionproto/scion/blob/a18c576dfcb965d72b5bbec5928504156a30dd64/go/pkg/showpaths/showpaths.go#L76)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

maybe add some comment here what is done.
</blockquote></details>

Good point, done.
___
*[go/pkg/showpaths/showpaths.go, line 217 at r1](https://reviewable.io/reviews/scionproto/scion/3942#-MO19_MoB6onEOLAAb0I:-MO6sVws2zDweyLZg6Dd:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a18c576dfcb965d72b5bbec5928504156a30dd64/go/pkg/showpaths/showpaths.go#L217)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> qutation
> ```
quotation
</blockquote></details>

Done.
___
*[go/scion/showpaths.go, line 117 at r1](https://reviewable.io/reviews/scionproto/scion/3942#-MO0yn7i47CKCYj5m5m8:-MO6sY-11oqkoNfyiiJg:blidsya) ([raw file](https://github.com/scionproto/scion/blob/6abe062f1d8854b3bdd926c2916da5c93726732c/go/scion/showpaths.go#L117)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I think we should keep that file. Having expiration information can be quite helpful for operations. In a system where static meta information is not setup I think seeing:
```
[0] Hops: [1-ff00:0:111 41>1 1-ff00:0:110 2>1 1-ff00:0:112]
    MTU: 1280
    NextHop: 172.20.0.26:30042
    Expires: 2020-12-08 16:47:52 +0000 UTC (5h57m15s)
    Latency: N/A
    Bandwidth: N/A
    Geo: []
    LinkType: [unset, unset]
    InternalHops: []
    Notes: []
    Status: alive
    LocalIP: 172.20.0.27
```
makes no sense.

We should keep the current `--expiration` and `-e` behavior and add `--extended` as an additional feature.
</blockquote></details>

Fair point. I wanted to avoid adding another flag because I fear that this would just hide this feature into oblivion. As an alternative proposal, would it make sense to keep this combined with the expiration flag and only show the items for which some value is set?


<!-- Sent from Reviewable.io -->

2020-12-11 13:43 UTC, lukedirtwalker requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3942)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[go/scion/showpaths.go, line 117 at r1](https://reviewable.io/reviews/scionproto/scion/3942#-MO0yn7i47CKCYj5m5m8:-MOH0m-85j4PMOlzEDAW:bt3xjsr) ([raw file](https://github.com/scionproto/scion/blob/6abe062f1d8854b3bdd926c2916da5c93726732c/go/scion/showpaths.go#L117)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Fair point. I wanted to avoid adding another flag because I fear that this would just hide this feature into oblivion. As an alternative proposal, would it make sense to keep this combined with the expiration flag and only show the items for which some value is set?
</blockquote></details>

So I was discussing this internally. We can go with the `--extended` flag instead of the `--expiry` but as long as there is no metada present there should still only be a single line of output. If there is metadata we can have the extended format like you propose.

Another idea would be to change the `--json` flag and instead have a `-o` flag that accepts `json` or `wide` where wide would display all the information in the key value format you propose.

Keep in mind that having so many lines per path can quickly lead to an explosion of output if you have many paths like 50 or so. 


<!-- Sent from Reviewable.io -->

2020-12-16 08:29 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3942)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker and @matzf)

___
*[go/scion/showpaths.go, line 117 at r1](https://reviewable.io/reviews/scionproto/scion/3942#-MO0yn7i47CKCYj5m5m8:-MOeeQnj5Cz_3eePOZtP:b-wyb4vp) ([raw file](https://github.com/scionproto/scion/blob/6abe062f1d8854b3bdd926c2916da5c93726732c/go/scion/showpaths.go#L117)):*
> We can go with the --extended flag instead of the --expiry but as long as there is no metada present there should still only be a single line of output. If there is metadata we can have the extended format like you propose.

Done.


<!-- Sent from Reviewable.io -->

2020-12-16 14:43 UTC, lukedirtwalker approved these changes
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3942)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2020-12-28 09:17 UTC, lukedirtwalker approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3942)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-28 09:17 UTC, lukedirtwalker requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3942)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/3942#-MPccmULDObALGF9pOz-:-MPccmULDObALGF9pOz0:bla61ok) (no related file):*
Needs a manual rebase. Sorry for that.

---


<!-- Sent from Reviewable.io -->

2021-01-05 15:40 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3942)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/3942#-MPccmULDObALGF9pOz-:-MQICESf1hC-PTSOFBMz:b-896fix) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Needs a manual rebase. Sorry for that.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-01-06 04:47 UTC, lukedirtwalker reviewed
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3942)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)



<!-- Sent from Reviewable.io -->

2021-01-06 04:47 UTC, lukedirtwalker approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3942)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-06 13:15 UTC, closed without merging