epic-hp: dataplane
scionproto/scion pull request #3951
Opened 2020-12-10 12:03 UTC by mawyss

This PR implements the EPIC dataplane as described in [1] and [2].
- Define EPIC packet structure.
- Add dataplane handling of EPIC packets.
- Add unit tests for packet parsing, EPIC functionality, and the dataplane.

Changes to existing code:
- mac.go: VerifyMAC() is changed to only do verification and not derivation of the hop field MAC.
- mac.go: add function FullMAC(), which returns the full 16 bytes (instead of only 6 bytes) of the MAC.
- dataplane.go: add processEPIC() function.
- dataplane.go: add "isSubheader" field to the scionPacketProcessor, which allows to process the SCION path type header also when it is contained in the EPIC path type header.
- dataplane.go: add "cachedMac" field to the scionPacketProcessor, which allows to cache the (full 16 bytes of the) hop field MAC, such that it does not need to be recalculated by EPIC.

Todo for later:
- Probably want to replace CMAC with CBC-MAC in PHVF/LHVF verification.
- Send back SCMP messages when PHVF/LHVF verification fails (at the moment the packet is just dropped).

[1] https://scion.docs.anapaya.net/en/latest/EPIC.html#data-plane
[2] https://scion.docs.anapaya.net/en/latest/protocols/scion-header.html#path-type-epic-hp

2020-12-17 12:23 UTC, karampok requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @mawyss)

___
*[go/lib/libepic/libepic.go, line 15 at r2](https://reviewable.io/reviews/scionproto/scion/3951#-MOkPx1aBarlQNKaJYNV:-MOkPx1aBarlQNKaJYNW:b-1x0u7q) ([raw file](https://github.com/scionproto/scion/blob/667100f4b935a88543b6c232b27b5d6520b60d2a/go/lib/libepic/libepic.go#L15)):*
> ```Go
> // limitations under the License.
> 
> package libepic
> ```

Please consider just `epic`, otherwise we have too many `lib` prefixes.
If needed import it as `libepic` when used.
___
*[go/lib/libepic/libepic.go, line 37 at r2](https://reviewable.io/reviews/scionproto/scion/3951#-MOkQ6Af0e_wztwdvPZt:-MOkQ6Af0e_wztwdvPZu:b-unuxna) ([raw file](https://github.com/scionproto/scion/blob/667100f4b935a88543b6c232b27b5d6520b60d2a/go/lib/libepic/libepic.go#L37)):*
> ```Go
> const (
> 	// Error messages
> 	ErrCipherFailure common.ErrMsg = "Unable to initialize AES cipher"
> ```

Do we need to export them? Also , check how the errors are created in https://github.com/scionproto/scion/blob/master/go/pkg/router/dataplane.go#L105-L115
___
*[go/lib/libepic/libepic.go, line 40 at r2](https://reviewable.io/reviews/scionproto/scion/3951#-MOkQird8CfnN3LXGzWb:-MOkQird8CfnN3LXGzWc:b-3gi6kk) ([raw file](https://github.com/scionproto/scion/blob/667100f4b935a88543b6c232b27b5d6520b60d2a/go/lib/libepic/libepic.go#L40)):*
> ```Go
> 	ErrMacFailure    common.ErrMsg = "Unable to initialize Mac"
> 	// Maximal lifetime of a packet in milliseconds
> 	PacketLifetimeMs uint16 = 2000
> ```

Do we need to export them?
If you need them for testing, see https://github.com/scionproto/scion/blob/master/go/pkg/router/export_test.go
___
*[go/lib/libepic/libepic.go, line 50 at r2](https://reviewable.io/reviews/scionproto/scion/3951#-MOkQyt5ELDmb8hqiF3h:-MOkQyt5ELDmb8hqiF3i:bfpnb5q) ([raw file](https://github.com/scionproto/scion/blob/667100f4b935a88543b6c232b27b5d6520b60d2a/go/lib/libepic/libepic.go#L50)):*
> ```Go
> 		return nil, serrors.Wrap(ErrCipherFailure, err)
> 	}
> 	// todo: CMAC is not ideal for EPIC due to its subkey generation overhead.
> ```

This todo in the code is not very clear, maybe you could create an issue describing the
limitation and how we should change this in the future.
___
*[go/lib/libepic/libepic.go, line 92 at r2](https://reviewable.io/reviews/scionproto/scion/3951#-MOkR__C4K9fbdxAg1sF:-MOkR__C4K9fbdxAg1sG:b-lu1er7) ([raw file](https://github.com/scionproto/scion/blob/667100f4b935a88543b6c232b27b5d6520b60d2a/go/lib/libepic/libepic.go#L92)):*
> ```Go
> }
> 
> func PrepareMacInput(epicpath *epic.EpicPath, s *slayers.SCION, timestamp uint32) ([]byte, error) {
> ```

Please bring the exported functions on the beginning of the file and have for each one a comment according to go standards.
You should be able to review how the comment looks like by `godoc -http=:6060`

(always check if you can avoid exporting the function, in which case you do not need comment)


General comments can be consolidated into a doc.go file e.g. https://github.com/scionproto/scion/blob/master/go/pkg/gateway/routing/doc.go


<!-- Sent from Reviewable.io -->

2020-12-18 17:15 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 0 of 15 files reviewed, 5 unresolved discussions (waiting on @karampok)

___
*[go/lib/libepic/libepic.go, line 15 at r2](https://reviewable.io/reviews/scionproto/scion/3951#-MOkPx1aBarlQNKaJYNV:-MOqoC5p-4FW9UgjRSzu:byvp0tb) ([raw file](https://github.com/scionproto/scion/blob/667100f4b935a88543b6c232b27b5d6520b60d2a/go/lib/libepic/libepic.go#L15)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

Please consider just `epic`, otherwise we have too many `lib` prefixes.
If needed import it as `libepic` when used.
</blockquote></details>

Done. Changed libepic to epic.
___
*[go/lib/libepic/libepic.go, line 37 at r2](https://reviewable.io/reviews/scionproto/scion/3951#-MOkQ6Af0e_wztwdvPZt:-MOqoLDgEbSnJzwAawgs:bo5esx9) ([raw file](https://github.com/scionproto/scion/blob/667100f4b935a88543b6c232b27b5d6520b60d2a/go/lib/libepic/libepic.go#L37)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

Do we need to export them? Also , check how the errors are created in https://github.com/scionproto/scion/blob/master/go/pkg/router/dataplane.go#L105-L115
</blockquote></details>

Done. Created the errors as described in your referenced file (and without exporting them).
___
*[go/lib/libepic/libepic.go, line 40 at r2](https://reviewable.io/reviews/scionproto/scion/3951#-MOkQird8CfnN3LXGzWb:-MOqo_NF2OwbfAT8fLbS:b-46g3q4) ([raw file](https://github.com/scionproto/scion/blob/667100f4b935a88543b6c232b27b5d6520b60d2a/go/lib/libepic/libepic.go#L40)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

Do we need to export them?
If you need them for testing, see https://github.com/scionproto/scion/blob/master/go/pkg/router/export_test.go

</blockquote></details>

Done. Thank you for the hint!
___
*[go/lib/libepic/libepic.go, line 50 at r2](https://reviewable.io/reviews/scionproto/scion/3951#-MOkQyt5ELDmb8hqiF3h:-MOqos6378_G23ZhddSA:b-5scpg8) ([raw file](https://github.com/scionproto/scion/blob/667100f4b935a88543b6c232b27b5d6520b60d2a/go/lib/libepic/libepic.go#L50)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

This todo in the code is not very clear, maybe you could create an issue describing the
limitation and how we should change this in the future.
</blockquote></details>

Done. Instead of creating an issue I solved it in the meantime.
___
*[go/lib/libepic/libepic.go, line 92 at r2](https://reviewable.io/reviews/scionproto/scion/3951#-MOkR__C4K9fbdxAg1sF:-MOqpBx43w19lelV6lb2:b-dyz7j0) ([raw file](https://github.com/scionproto/scion/blob/667100f4b935a88543b6c232b27b5d6520b60d2a/go/lib/libepic/libepic.go#L92)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

Please bring the exported functions on the beginning of the file and have for each one a comment according to go standards.
You should be able to review how the comment looks like by `godoc -http=:6060`

(always check if you can avoid exporting the function, in which case you do not need comment)


General comments can be consolidated into a doc.go file e.g. https://github.com/scionproto/scion/blob/master/go/pkg/gateway/routing/doc.go
</blockquote></details>

Done. Added comments for the exported functions and reordered them. Some of the exported functions are indeed only used for the tests at the moment, they will be used for the packet generation at the end hosts however (which will be a separate PR).


<!-- Sent from Reviewable.io -->

2021-01-07 09:05 UTC, karampok requested changes
> Reviewed 2 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 2 of 15 files reviewed, 12 unresolved discussions (waiting on @karampok and @mawyss)

___
*[go/pkg/router/dataplane.go, line 675 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQQvRJu25AJgdwy43Hq:-MQQvRJv80Q9dTI7ziAi:b3ivwqg) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L675)):*
> ```Go
> 	origPacket []byte, buffer gopacket.SerializeBuffer) (processResult, error) {
> 
> 	// Get the already parsed EPIC path header
> ```

you can also drop the comments, as the code should be clear what it does (all comments within that function)
___
*[go/pkg/router/dataplane.go, line 689 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQQw13D8aUH8A_jUUrJ:-MQQw13D8aUH8A_jUUrK:b-b0e7bj) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L689)):*
> ```Go
> 	// Parse the current info field to get the timestamp
> 	info, err := scionRaw.GetCurrentInfoField()
> 	if err != nil || info == nil {
> ```

The implementation of a function that returns (X,error) should (ideally) return a nil X only if err is not nil. And a not-nil X if err is nil.
In other words, if the err is nil you expect the X to be  meaningful happy path.

As of now, you hide what is happening under the `malformedPath` error string
___
*[go/pkg/router/dataplane.go, line 715 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQQxPMOBbv_12Oz9wV0:-MQQxPMOBbv_12Oz9wV1:b-44tvwj) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L715)):*
> ```Go
> 	// Get the cached authenticator
> 	auth := p.cachedMac
> 	if len(auth) != 16 {
> ```

this value should be a constant inside the epic package
___
*[go/pkg/router/dataplane.go, line 721 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQQyghy6ko1MWJD_y0p:-MQQyghy6ko1MWJD_y0q:bmngglt) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L721)):*
> ```Go
> 
> 	// Verify the PHVF and LHVF if necessary
> 	if b, err := libepic.IsPenultimateHop(scionRaw); b {
> ```

This if/else needs to be refactored to avoid else using a switch statement https://golang.org/doc/effective_go.html#switch. It is more go idiomatic and better readable.
Also, I suggest that this if/else is hidden into a unique function that is inside the epic package
___
*[go/pkg/router/dataplane.go, line 730 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQQzL473dQO1ZhHUaPm:-MQQzL48BPw59pOorcix:b-vhskmb) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L730)):*
> ```Go
> 		}
> 		if !ok {
> 			// todo: send back scmp packet?
> ```

There should be no todo. You can remove it and add later a PR about scmp. Also 
`// TODO(name): ` is the format we currently use
___
*[go/pkg/router/dataplane.go, line 857 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQR2H-_5AEz-ERZsrjk:-MQR2H-_5AEz-ERZsrjl:b-m8kog4) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L857)):*
> ```Go
> 		}
> 		p.path = epicpath.ScionRaw
> 	} else {
> ```

please provide an implementation without else
___
*[go/pkg/router/dataplane_test.go, line 53 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQR2u0pBfHwnOg3Sf7C:-MQR2u0pBfHwnOg3Sf7D:b-ftt45k) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane_test.go#L53)):*
> ```Go
> )
> 
> var cachedTsRel uint32
> ```

we want to avoid any global variable, is that possible? At least move inside the Test function
and have a more descriptive name?


<!-- Sent from Reviewable.io -->

2021-01-08 09:16 UTC, karampok requested changes
> Reviewed 4 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 6 of 15 files reviewed, 10 unresolved discussions (waiting on @mawyss)

___
*[go/lib/epic/doc.go, line 15 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQWG1J69BJF4HFASpo7:-MQWG1J73z9xDV4_WsOA:b-7olxk5) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/lib/epic/doc.go#L15)):*
> ```Go
> // limitations under the License.
> 
> /*
> ```

use `//` instead, see
https://github.com/scionproto/scion/blob/master/go/pkg/router/bfd/doc.go
___
*[go/lib/epic/export_test.go, line 22 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQWGqL1D3j76_lLPjkv:-MQWGqL1D3j76_lLPjkw:bjdqnzv) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/lib/epic/export_test.go#L22)):*
> ```Go
> )
> 
> func ExtractPacketLifetimeMs() uint16 {
> ```

you can avoid a function but have https://github.com/scionproto/scion/blob/master/go/lib/snet/export_test.go#L23 (same below)
___
*[go/lib/slayers/path/epic/epic.go, line 117 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQWH81e10O0sTnctg0j:-MQWH81e10O0sTnctg0k:b-o1g4ki) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/lib/slayers/path/epic/epic.go#L117)):*
> ```Go
> 		return 16
> 	}
> 	return 16 + p.ScionRaw.Len()
> ```

16 should be a const


<!-- Sent from Reviewable.io -->

2021-01-11 21:47 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 0 of 15 files reviewed, 10 unresolved discussions (waiting on @karampok)

___
*[go/lib/epic/doc.go, line 15 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQWG1J69BJF4HFASpo7:-MQnPB2O9gzuqUGoJk2f:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/lib/epic/doc.go#L15)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

use `//` instead, see
https://github.com/scionproto/scion/blob/master/go/pkg/router/bfd/doc.go
</blockquote></details>

Done.
___
*[go/lib/epic/export_test.go, line 22 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQWGqL1D3j76_lLPjkv:-MQnPCeI9-5L8jLDundQ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/lib/epic/export_test.go#L22)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

you can avoid a function but have https://github.com/scionproto/scion/blob/master/go/lib/snet/export_test.go#L23 (same below)
</blockquote></details>

Done.
___
*[go/lib/slayers/path/epic/epic.go, line 117 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQWH81e10O0sTnctg0j:-MQnPEJT2mpPRbaqsNV3:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/lib/slayers/path/epic/epic.go#L117)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

16 should be a const
</blockquote></details>

Done.
___
*[go/pkg/router/dataplane.go, line 675 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQQvRJu25AJgdwy43Hq:-MQnPFsrCg_28atFZnFw:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L675)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

you can also drop the comments, as the code should be clear what it does (all comments within that function)
</blockquote></details>

Done.
___
*[go/pkg/router/dataplane.go, line 689 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQQw13D8aUH8A_jUUrJ:-MQnPJgWC801LGGcwvxg:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L689)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

The implementation of a function that returns (X,error) should (ideally) return a nil X only if err is not nil. And a not-nil X if err is nil.
In other words, if the err is nil you expect the X to be  meaningful happy path.

As of now, you hide what is happening under the `malformedPath` error string
</blockquote></details>

Done.
___
*[go/pkg/router/dataplane.go, line 715 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQQxPMOBbv_12Oz9wV0:-MQnPKwQ7motX199AsYu:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L715)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

this value should be a constant inside the epic package
</blockquote></details>

Done.
___
*[go/pkg/router/dataplane.go, line 721 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQQyghy6ko1MWJD_y0p:-MQnPXAWAF7kcBd0mCeZ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L721)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

This if/else needs to be refactored to avoid else using a switch statement https://golang.org/doc/effective_go.html#switch. It is more go idiomatic and better readable.
Also, I suggest that this if/else is hidden into a unique function that is inside the epic package
</blockquote></details>

Done.
___
*[go/pkg/router/dataplane.go, line 730 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQQzL473dQO1ZhHUaPm:-MQnPYKa0Jt3K1oVefoB:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L730)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

There should be no todo. You can remove it and add later a PR about scmp. Also 
`// TODO(name): ` is the format we currently use
</blockquote></details>

Done.
___
*[go/pkg/router/dataplane.go, line 857 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQR2H-_5AEz-ERZsrjk:-MQnPa4o-NFhRuQh3HvQ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L857)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

please provide an implementation without else
</blockquote></details>

Done.
___
*[go/pkg/router/dataplane_test.go, line 53 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQR2u0pBfHwnOg3Sf7C:-MQnPfyi9MECfKIuH9_e:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane_test.go#L53)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

we want to avoid any global variable, is that possible? At least move inside the Test function
and have a more descriptive name?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-12 09:17 UTC, karampok requested changes
> Reviewed 1 of 13 files at r1, 1 of 2 files at r6, 3 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 5 of 15 files reviewed, 4 unresolved discussions (waiting on @karampok and @mawyss)

___
*[go/lib/epic/epic.go, line 165 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQpXqWu4Qks2EmZFZXH:-MQpXqWu4Qks2EmZFZXI:bp43dwa) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/lib/epic/epic.go#L165)):*
> ```Go
> // is either the penultimate or the last hop of the path.
> func VerifyHVFIfNecessary(scionRaw *scion.Raw, auth []byte, epicpath *epic.EpicPath,
> 	s *slayers.SCION, timestamp uint32) (bool, error) {
> ```

What is the reason why you need to return a bool?

The return values are  `bool,error` but I think it can only be `error`.
If `err!=nil` verification failed.
___
*[go/lib/epic/epic.go, line 207 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQpYEWL5RjWXgNYBqpx:-MQpYEWL5RjWXgNYBqpy:b-pm05bv) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/lib/epic/epic.go#L207)):*
> ```Go
> 	} else {
> 		hvf = epicpath.PHVF
> 	}
> ```

a more go idiomatic way is
```
hvf = epicpath.PHVF
if last{
hvf=epicpath.LHVF
}

```

(unless there is a function call that has significant process overhead)
___
*[go/lib/slayers/path/mac.go, line 40 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQprCAX7BITNoqnrr3M:-MQprCAYDlKxjVLZyVEJ:b-mfh52a) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/lib/slayers/path/mac.go#L40)):*
> ```Go
> 
> // FullMAC returns the full 16 bytes of the HopField MAC.
> func FullMAC(h hash.Hash, info *InfoField, hf *HopField) []byte {
> ```

The implementation of this  function is the same as the implementation of the function above.
The fullMAC description and implementation seems not optimal.
Can we only use the `MAC` function? Do we even need that outside the tests?
___
*[go/lib/slayers/path/mac.go, line 55 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQpsEu00W9NflzMlCEv:-MQpsEu00W9NflzMlCEw:b-gtbdik) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/lib/slayers/path/mac.go#L55)):*
> ```Go
> // otherwise an error is returned.
> func VerifyMAC(expectedMac []byte, hf *HopField) error {
> 	if !bytes.Equal(hf.Mac[:6], expectedMac[:6]) {
> ```

We could easily avoid having a VerifyMAC as currently, the only thing is doing is `!bytes.Equal()`.
See if you can drop it and how it looks.
___
*[go/pkg/router/dataplane.go, line 857 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQR2H-_5AEz-ERZsrjk:-MQpoL3HAZgtpoVfDD-c:b8n9s8d) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L857)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Do you know if the following implementation is working?
```
		var ok bool
		p.path, ok = p.scionLayer.Path.(*scion.Raw)
		if !ok {
			// TODO(lukedirtwalker) parameter problem invalid path?
			return processResult{}, malformedPath
		}
               if p.isSubheader {

               		epicpath, ok := p.scionLayer.Path.(*epic.EpicPath)
		if !ok {
			return processResult{}, malformedPath
		}
		p.path = epicpath.ScionRaw

             }

```
if we not, why not?


<!-- Sent from Reviewable.io -->

2021-01-12 09:25 UTC, karampok requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 5 of 15 files reviewed, 5 unresolved discussions (waiting on @karampok and @mawyss)

___
*[go/pkg/router/dataplane.go, line 709 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQpu7eo6HCrQhD5nviS:-MQpu7eo6HCrQhD5nviT:b63hku5) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/pkg/router/dataplane.go#L709)):*
> ```Go
> 
> 	auth := p.cachedMac
> 	if len(auth) != libepic.AuthLength {
> ```

I can not see how that can fail?
The `p.cachedMac` is always 16 bytes since you return  `return h.Sum(nil)[:6]`


<!-- Sent from Reviewable.io -->

2021-01-12 12:46 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 5 of 15 files reviewed, 5 unresolved discussions (waiting on @karampok)

___
*[go/lib/epic/epic.go, line 165 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQpXqWu4Qks2EmZFZXH:-MQq0XYO8Yh2F6GPCI4a:b-yyvnqx) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/lib/epic/epic.go#L165)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

What is the reason why you need to return a bool?

The return values are  `bool,error` but I think it can only be `error`.
If `err!=nil` verification failed.


</blockquote></details>

Yes, this would work too, at least for now. The idea is that the error indicates whether the operations succeeded (e.g., the initialization and calculation of the MAC), while the bool indicates (in case that there was no error) whether the calculated HVF corresponds to the HVF in the packet. This means that even if there was no error, the bool can be false. In the future this allows to send back SCMP packets when the HVF verification failed.
But I will gladly change it if you think it would make sense.
___
*[go/lib/epic/epic.go, line 207 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQpYEWL5RjWXgNYBqpx:-MQqbJOm8mezSqrdaYIA:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/lib/epic/epic.go#L207)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

a more go idiomatic way is
```
hvf = epicpath.PHVF
if last{
hvf=epicpath.LHVF
}

```

(unless there is a function call that has significant process overhead)
</blockquote></details>

Done.
___
*[go/lib/slayers/path/mac.go, line 40 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQprCAX7BITNoqnrr3M:-MQq5TVOCXlgwHudHwrn:bj16vi6) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/lib/slayers/path/mac.go#L40)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

The implementation of this  function is the same as the implementation of the function above.
The fullMAC description and implementation seems not optimal.
Can we only use the `MAC` function? Do we even need that outside the tests?
</blockquote></details>

Yes, the implementation is the same, with the only difference that FullMAC() returns 16 bytes and not only 6 bytes.
This is important because EPIC-HP needs the full 16 bytes to calculate the PHVF /LHVF.
I changed the description to make this more clear.

Initially I planned to change the MAC() function to return 16 bytes instead of 6. But this would affect > 20 files (mostly in /go/integration however), and I tried to avoid larger changes, especially if it affects a core mechanism like the MAC calculation. But please let me know if you want this to be changed.
___
*[go/lib/slayers/path/mac.go, line 55 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQpsEu00W9NflzMlCEv:-MQqR3Gl3cyDe-YbZ1ko:b6prycn) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/lib/slayers/path/mac.go#L55)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

We could easily avoid having a VerifyMAC as currently, the only thing is doing is `!bytes.Equal()`.
See if you can drop it and how it looks.
</blockquote></details>

I checked that now. I assume that the creator of this function did not want to rewrite the error output (expected vs. calculated MAC) everywhere this MAC verification is needed. This would lead to fairly long error messages (see verifyCurrentMAC() in dataplane.go).
Do you want me to change it anyway?
___
*[go/pkg/router/dataplane.go, line 857 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQR2H-_5AEz-ERZsrjk:-MQqZGje3yGnh6l1L9Dt:bt6cqc4) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L857)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

Do you know if the following implementation is working?
```
		var ok bool
		p.path, ok = p.scionLayer.Path.(*scion.Raw)
		if !ok {
			// TODO(lukedirtwalker) parameter problem invalid path?
			return processResult{}, malformedPath
		}
               if p.isSubheader {

               		epicpath, ok := p.scionLayer.Path.(*epic.EpicPath)
		if !ok {
			return processResult{}, malformedPath
		}
		p.path = epicpath.ScionRaw

             }

```
if we not, why not?
</blockquote></details>

I don't think this works: 
p.scionLayer.Path is either a pointer to a scion.Raw or epic.EpicPath. In the case of epic.EpicPath, the first assignment fails (ok = false), and the conditional branching on p.isSubheader will never be reached.

(I also checked it, with this implementation the router tests start failing with a malformedPath exception)
___
*[go/pkg/router/dataplane.go, line 709 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQpu7eo6HCrQhD5nviS:-MQqWfxK91bercGkn4x5:b-8izg5j) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/pkg/router/dataplane.go#L709)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

I can not see how that can fail?
The `p.cachedMac` is always 16 bytes since you return  `return h.Sum(nil)[:6]`
</blockquote></details>

You are right, and it is also checked later in VerifyHVF(). Removed this check here.


<!-- Sent from Reviewable.io -->

2021-01-14 12:50 UTC, karampok requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 5 of 15 files reviewed, 4 unresolved discussions (waiting on @karampok and @mawyss)

___
*[go/lib/epic/epic.go, line 165 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQpXqWu4Qks2EmZFZXH:-MQqlWA_3VJMBIHr7KHp:b-rlq0ng) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/lib/epic/epic.go#L165)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Yes, this would work too, at least for now. The idea is that the error indicates whether the operations succeeded (e.g., the initialization and calculation of the MAC), while the bool indicates (in case that there was no error) whether the calculated HVF corresponds to the HVF in the packet. This means that even if there was no error, the bool can be false. In the future this allows to send back SCMP packets when the HVF verification failed.
But I will gladly change it if you think it would make sense.
</blockquote></details>

okay, let's keep it simple and return only error. When we add functionality that requires error handling and separate ok value we can refactor.
___
*[go/lib/slayers/path/mac.go, line 40 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQprCAX7BITNoqnrr3M:-MQqmLe50sFf8pBEd-hG:b-nrr49f) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/lib/slayers/path/mac.go#L40)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Yes, the implementation is the same, with the only difference that FullMAC() returns 16 bytes and not only 6 bytes.
This is important because EPIC-HP needs the full 16 bytes to calculate the PHVF /LHVF.
I changed the description to make this more clear.

Initially I planned to change the MAC() function to return 16 bytes instead of 6. But this would affect > 20 files (mostly in /go/integration however), and I tried to avoid larger changes, especially if it affects a core mechanism like the MAC calculation. But please let me know if you want this to be changed.
</blockquote></details>

okay, I need to discuss that.
For the time being, please provide and implementation that the `MAC` function is re-using `FullMac`
```
func MAC()   ...{
return FullMAC[:6]
}
```
___
*[go/lib/slayers/path/mac.go, line 55 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQpsEu00W9NflzMlCEv:-MQqn2zTAPVLw9SUnG-C:bchjd5a) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/lib/slayers/path/mac.go#L55)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

I checked that now. I assume that the creator of this function did not want to rewrite the error output (expected vs. calculated MAC) everywhere this MAC verification is needed. This would lead to fairly long error messages (see verifyCurrentMAC() in dataplane.go).
Do you want me to change it anyway?
</blockquote></details>

I think it is being used only in two places, you can remove the function.
___
*[go/pkg/router/dataplane.go, line 857 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQR2H-_5AEz-ERZsrjk:-MQqnwEb4nIWEWfHdhjo:bii8una) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L857)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

I don't think this works: 
p.scionLayer.Path is either a pointer to a scion.Raw or epic.EpicPath. In the case of epic.EpicPath, the first assignment fails (ok = false), and the conditional branching on p.isSubheader will never be reached.

(I also checked it, with this implementation the router tests start failing with a malformedPath exception)
</blockquote></details>

Have you tried something like
```
C path type header.
type EpicPath struct {
	 scion.Raw
        
        PacketTimestamp uint64
	PHVF            []byte
	LHVF            []byte
}
```
no sure if it is the right way
___
*[go/pkg/router/dataplane.go, line 820 at r8](https://reviewable.io/reviews/scionproto/scion/3951#-MQqr11h0PZDXhIJilMm:-MQqr11h0PZDXhIJilMn:bcfa1oc) ([raw file](https://github.com/scionproto/scion/blob/d5a31ed239a5ff80b7d16e84097f24facbd60d93/go/pkg/router/dataplane.go#L820)):*
> ```Go
> 
> func (p *scionPacketProcessor) parsePath() (processResult, error) {
> 	switch p.isSubheader {
> ```

Subheader is  no ideal,  let's have is `isEpic`


<!-- Sent from Reviewable.io -->

2021-01-14 16:15 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 5 of 15 files reviewed, 4 unresolved discussions (waiting on @karampok)

___
*[go/lib/epic/epic.go, line 165 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQpXqWu4Qks2EmZFZXH:-MR0RRFr1Pg5sUUoOyUd:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/lib/epic/epic.go#L165)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

okay, let's keep it simple and return only error. When we add functionality that requires error handling and separate ok value we can refactor.
</blockquote></details>

Done.
___
*[go/lib/slayers/path/mac.go, line 40 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQprCAX7BITNoqnrr3M:-MR0G7X9CI-ugsC8auXP:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/lib/slayers/path/mac.go#L40)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

okay, I need to discuss that.
For the time being, please provide and implementation that the `MAC` function is re-using `FullMac`
```
func MAC()   ...{
return FullMAC[:6]
}
```
</blockquote></details>

Done.
___
*[go/lib/slayers/path/mac.go, line 55 at r7](https://reviewable.io/reviews/scionproto/scion/3951#-MQpsEu00W9NflzMlCEv:-MR0G9WR2b1SKquSOrrt:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b353d6b5f9a1bdf0da41f06c481054f12f7028a3/go/lib/slayers/path/mac.go#L55)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

I think it is being used only in two places, you can remove the function.
</blockquote></details>

Done.
___
*[go/pkg/router/dataplane.go, line 857 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQR2H-_5AEz-ERZsrjk:-MR0NBnN6svwoBjxEudF:b-3apbm7) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L857)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

Have you tried something like
```
C path type header.
type EpicPath struct {
	 scion.Raw
        
        PacketTimestamp uint64
	PHVF            []byte
	LHVF            []byte
}
```
no sure if it is the right way
</blockquote></details>

Ah ok, I see now what you meant before. But I still don't think that this approach will work:
In case the p.scionLayer.Path is a pointer to an epic.EpicPath, then the first assignment will still return (<nil>, false).
In particular, Go's type assertion seems not to allow those kind of assertions to struct compositions.
I also verified this behavior in form of a simplified example in the Go Playground (https://play.golang.org/).
___
*[go/pkg/router/dataplane.go, line 820 at r8](https://reviewable.io/reviews/scionproto/scion/3951#-MQqr11h0PZDXhIJilMm:-MR0JlUdBxjrCVhAf9so:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d5a31ed239a5ff80b7d16e84097f24facbd60d93/go/pkg/router/dataplane.go#L820)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

Subheader is  no ideal,  let's have is `isEpic`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-16 12:16 UTC, karampok requested changes
> Reviewed 1 of 13 files at r4, 1 of 2 files at r6, 3 of 9 files at r7, 4 of 5 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: all files reviewed, 1 unresolved discussion (waiting on @mawyss)

___
*[go/lib/slayers/path/epic/epic.go, line 59 at r10](https://reviewable.io/reviews/scionproto/scion/3951#-MTei2Jr90JADHsMkMDW:-MTei2Jr90JADHsMkMDX:b-fo3twy) ([raw file](https://github.com/scionproto/scion/blob/bc33252926315d39c302794b5ce3f80f746aea25/go/lib/slayers/path/epic/epic.go#L59)):*
> ```Go
> 		return serrors.New("epic path must not be nil")
> 	}
> 	if len(b) < 16 {
> ```

Ideally, all the int values  in this file should be on top on a constant (not exported)
___
*[go/pkg/router/dataplane.go, line 857 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQR2H-_5AEz-ERZsrjk:-MTefA36B8MP_wGFtTbE:b-cj70ip) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L857)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Ah ok, I see now what you meant before. But I still don't think that this approach will work:
In case the p.scionLayer.Path is a pointer to an epic.EpicPath, then the first assignment will still return (<nil>, false).
In particular, Go's type assertion seems not to allow those kind of assertions to struct compositions.
I also verified this behavior in form of a simplified example in the Go Playground (https://play.golang.org/).
</blockquote></details>

Ok, in that case, I have to ask to revert to a `if else` since the final switch on just on false/true seems a bit ackword. Sorry for that.


<!-- Sent from Reviewable.io -->

2021-03-01 09:13 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 12 of 15 files reviewed, 1 unresolved discussion (waiting on @karampok)

___
*[go/lib/slayers/path/epic/epic.go, line 59 at r10](https://reviewable.io/reviews/scionproto/scion/3951#-MTei2Jr90JADHsMkMDW:-MUh1ZQDE_dqyCTahYHV:b-i9vtex) ([raw file](https://github.com/scionproto/scion/blob/bc33252926315d39c302794b5ce3f80f746aea25/go/lib/slayers/path/epic/epic.go#L59)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

Ideally, all the int values  in this file should be on top on a constant (not exported)
</blockquote></details>

Done. Except for one occurrence of "return 0", all other values are now constants.
___
*[go/pkg/router/dataplane.go, line 857 at r5](https://reviewable.io/reviews/scionproto/scion/3951#-MQR2H-_5AEz-ERZsrjk:-MUh1o7O2tV2wmUdQeDq:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8970331cdb5bf77ffc10a704b621884eeb045f3f/go/pkg/router/dataplane.go#L857)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

Ok, in that case, I have to ask to revert to a `if else` since the final switch on just on false/true seems a bit ackword. Sorry for that.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-15 14:39 UTC, karampok reviewed
> Reviewed 1 of 1 files at r11, 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mawyss)



<!-- Sent from Reviewable.io -->

2021-03-26 18:58 UTC, shitz requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: all files reviewed, 36 unresolved discussions (waiting on @mawyss and @Oncilla)

___
*[go/lib/epic/epic.go, line 34 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWiejW3455iC1KuJJjN:-MWiejW40qKb222-ttBI:b-i5f0aa) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L34)):*
> ```Go
> const (
> 	// authLength denotes the size of the authenticator in bytes
> 	authLength = 16
> ```

`AuthLen`
___
*[go/lib/epic/epic.go, line 36 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWiefX57MMjI6pDikv8:-MWiefX57MMjI6pDikv9:bl9ctwm) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L36)):*
> ```Go
> 	authLength = 16
> 	// packetLifetimeMs denotes the maximal lifetime of a packet in milliseconds
> 	packetLifetimeMs uint16 = 2000
> ```

`MaxPacketLifetime`
___
*[go/lib/epic/epic.go, line 38 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWieZb62bVKR3TTVJIY:-MWieZb62bVKR3TTVJIZ:b7a78ko) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L38)):*
> ```Go
> 	packetLifetimeMs uint16 = 2000
> 	// clockSkewMs denotes the maximal clock skew in milliseconds
> 	clockSkewMs uint16 = 1000
> ```

`MaxClockSkew` or `MaxClockSkewMilliseconds`
___
*[go/lib/epic/epic.go, line 42 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWh_OywBM5xmLFOuz9C:-MWh_OywBM5xmLFOuz9D:b3krfug) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L42)):*
> ```Go
> 
> // CreateEpicTimestamp creates the EPIC packetTimestamp from tsRel, coreID, and coreCounter.
> func CreateEpicTimestamp(tsRel uint32, coreID uint8, coreCounter uint32) (packetTimestamp uint64) {
> ```

We don't use named return arguments in the code base. Please fix also in other places.
___
*[go/lib/epic/epic.go, line 42 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWiageM41Ld01uu_vrp:-MWh_pPx9pGrciL0c9Vp:b-1o441n) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L42)):*
> ```Go
> 
> // CreateEpicTimestamp creates the EPIC packetTimestamp from tsRel, coreID, and coreCounter.
> func CreateEpicTimestamp(tsRel uint32, coreID uint8, coreCounter uint32) (packetTimestamp uint64) {
> ```

Looking at this again, I find `Timestamp` not to be a suitable naming for the Epic Timestamp. More generically, it is a packet ID that contains a relative timestamp and a counter. Thus I propose you create something like

```
type PktID struct {
	Timestamp   uint32
	CoreID      uint8
	CoreCounter uint32
}

func (i *PktID) DecodeFromBytes(raw []byte) {
	i.Timestamp = binary.BigEndian.Uint32(raw[:4])
	coreInfo := binary.BigEndian.Uint32(raw[4:8])
	i.CoreID = uint8(coreInfo >> 24)
	i.CoreCounter = coreInfo & 0x00FFFFFF
}

func (i *PktID) SerializeTo(b []byte) {
	binary.BigEndian.PutUint32(b[:4], i.Timestamp)
	coreInfo := uint32(i.CoreID)<<24 | i.CoreCounter
	binary.BigEndian.PutUint32(b[4:8], coreInfo)
}
```

and work with that. 

Then, `Timestamp` would really only refer to what is now called `TsRel`
___
*[go/lib/epic/epic.go, line 59 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWha-tb--Nr_hPxfwtq:-MWha-tb--Nr_hPxfwtr:b-ai167q) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L59)):*
> ```Go
> 
> // CreateEpicTimestampCustom creates the EPIC packetTimestamp from tsRel and pckId.
> func CreateEpicTimestampCustom(tsRel uint32, pckId uint32) (packetTimestamp uint64) {
> ```

Would drop this function as it's not needed.
___
*[go/lib/epic/epic.go, line 88 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWib9uC-7_ODZj_IKNe:-MWib9uC-7_ODZj_IKNf:b-m7hodu) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L88)):*
> ```Go
> // time. It must not be in the future, otherwise an error is returned. The current time  must be at
> // most 1 day and 63 minutes after the input timestamp, otherwise an error is returned.
> func CreateTsRel(timestamp uint32) (uint32, error) {
> ```

This would now be called `CreateTimestamp`
___
*[go/lib/epic/epic.go, line 88 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWibDAX9C1QqvXLprck:-MWibDAX9C1QqvXLprcl:bveh19l) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L88)):*
> ```
> timestamp
> ```
I'd call this `input`
___
*[go/lib/epic/epic.go, line 95 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWid6qI3oNykGf3kGzt:-MWid6qI3oNykGf3kGzu:bq1rr5m) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L95)):*
> ```Go
> 		return 0, serrors.New("provided timestamp is in the future",
> 			"timestamp", tsMicro, "now", nowMicro)
> 	} else {
> ```

No need for the `else` since you return in the error case

Also, `diff` is not really needed, since it's only used in one expression.
___
*[go/lib/epic/epic.go, line 102 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWidXzgDXUfkoBXFGBa:-MWidXzgDXUfkoBXFGBb:b-3mf7hp) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L102)):*
> ```Go
> 	tsRel := max(0, (diff/21)-1)
> 	if tsRel >= (1 << 32) {
> 		return 0, serrors.New("current time is more than 1 day"+
> ```

`serrors.New("diff between input and now >1d63min", "diff", ...)`

Also, translate it to something that is readable by a human instead of milliseconds. 
___
*[go/lib/epic/epic.go, line 131 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWifbMs4ry7LQD8bU5n:-MWifbMt0CeJo0fKVmhR:bhqtinv) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L131)):*
> ```Go
> 		(nowMs > tsSenderMs+uint64(packetLifetimeMs)+uint64(clockSkewMs)) {
> 		return false
> 	} else {
> ```

drop `else` since you return anyway in the other branch
___
*[go/lib/epic/epic.go, line 138 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWikAIyB8ghg3wfonxI:-MWikAIyB8ghg3wfonxJ:bjrgrcz) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L138)):*
> ```Go
> // CalculateEpicMac derives the EPIC MAC (PHVF/LHVF) given the full 16 bytes of the SCION path type
> // MAC (auth), the EPIC path type header (epicpath), and the SCION common/address header (s).
> func CalculateEpicMac(auth []byte, epicpath *epic.EpicPath, s *slayers.SCION,
> ```

Should be called `CalcMac` -> reads then as `epic.CalcMac()`
___
*[go/lib/epic/epic.go, line 151 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWigaLRCXmWk_cOp0wt:-MWigaLRCXmWk_cOp0wu:bc4ith3) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L151)):*
> ```Go
> 		return nil, err
> 	}
> 	if len(input) < 16 || len(input)%16 != 0 {
> ```

You are in full control how the input is generated. No need for this check. If anything that goes into the MAC calculation is wrong it should be caught by `prepareMacInput`
___
*[go/lib/epic/epic.go, line 158 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWiixen5iWpfOq4wBEr:-MWiixen5iWpfOq4wBEs:b-yzbbcd) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L158)):*
> ```
> 16
> ```
This should be f.BlockSize()
___
*[go/lib/epic/epic.go, line 163 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWij1Ls0PWo8x9VKcZH:-MWij1Ls0PWo8x9VKcZI:bi56u47) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L163)):*
> ```Go
> // VerifyHVFIfN [...]

2021-03-27 10:47 UTC, shitz requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: all files reviewed, 52 unresolved discussions (waiting on @mawyss and @Oncilla)

___
*[go/lib/epic/epic.go, line 114 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWnCf1K08WJvHLeI5wa:-MWnCf1K08WJvHLeI5wb:bfvm2mo) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L114)):*
> ```Go
> // a possible clock drift between the packet source and the verifier of up to one second into
> // account.
> func VerifyTimestamp(timestamp uint32, packetTimestamp uint64) bool {
> ```

This should return an error instead of simply true or false.
___
*[go/lib/epic/epic.go, line 138 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWnEmr32Ln9ozRdJwKP:-MWnEmr32Ln9ozRdJwKQ:b-m56x2c) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L138)):*
> ```
> epicpath *epic.EpicPath
> ```
You don't need the entire path, only the `PktID` is needed (former timestamp)
___
*[go/lib/epic/epic.go, line 190 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWij7sM7EmfLqi_KMug:-MWnF5FK8zlr8JbP0BKo:b-vvmezt) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L190)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

instead of the `last` bool, simply pass in either the `PHVF` or the `LHVF`
</blockquote></details>

Also, you don't need the entire path. Only the `PktID` is needed here plus either the PHVF or LHVF
___
*[go/lib/epic/epic.go, line 209 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWnEMhcAMn22g-Wgz9d:-MWnEMhdCyAgkW3Cgc4h:b-l3o86b) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L209)):*
> ```Go
> 	err = nil
> 	if !bytes.Equal(hvf, mac) {
> 		err = serrors.New("epic hop validation field verification failed")
> ```

return `serrors.New(...)`
Also include the values as context.
___
*[go/lib/epic/epic.go, line 211 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWnEShD6fc891RZSgPQ:-MWnEShD6fc891RZSgPR:b-1gj4m2) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L211)):*
> ```Go
> 		err = serrors.New("epic hop validation field verification failed")
> 	}
> 	return err
> ```

return nil
___
*[go/lib/slayers/path/epic/epic_test.go, line 52 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWnH0Fg3m7ZbAPUVCep:-MWnH0Fg3m7ZbAPUVCeq:b4zf8tn) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/slayers/path/epic/epic_test.go#L52)):*
> ```Go
> )
> 
> func TestSerializeDecode(t *testing.T) {
> ```

Please also add tests for serialize and decode alone, as well as a test for reverse.
___
*[go/pkg/router/dataplane.go, line 690 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWn25b-Cry3GoFP-mJ_:-MWn25b-Cry3GoFP-mJa:brnoy3o) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/pkg/router/dataplane.go#L690)):*
> ```Go
> 	timestamp := info.Timestamp
> 	packetTimestamp := epicpath.PacketTimestamp
> 	libepic.VerifyTimestamp(timestamp, packetTimestamp)
> ```

Why do you verify the timestamp on each hop? Wouldn't just the last two hops need to do that?
___
*[go/pkg/router/dataplane.go, line 961 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWn5OTrAF6pYmerfaES:-MWn5OTrAF6pYmerfaET:b-yrpbpm) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/pkg/router/dataplane.go#L961)):*
> ```
> 6
> ```
All these 6's should be `path.MacLen` (defined in `hopfield.go`)
___
*[go/pkg/router/dataplane.go, line 967 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWn4acc7KTTSJTUgVt0:-MWn4acc7KTTSJTUgVt1:b9o1bsx) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/pkg/router/dataplane.go#L967)):*
> ```Go
> 			},
> 			&slayers.SCMPParameterProblem{Pointer: p.currentHopPointer()},
> 			serrors.New("MAC", "expected", fmt.Sprintf("%x", fullMac[:6]),
> ```

Change this to `MAC verification failed`
___
*[go/pkg/router/dataplane.go, line 1255 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWn59_1CTZb8eacDl5A:-MWn59_1CTZb8eacDl5B:b-uedv47) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/pkg/router/dataplane.go#L1255)):*
> ```Go
> 	// OHP leaving our IA
> 	if d.localIA.Equal(s.SrcIA) {
> 		fullMac := path.FullMAC(d.macFactory(), &p.Info, &p.FirstHop)
> ```

This can just use `path.MAC()`
___
*[go/lib/epic/epic_test.go, line 33 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWnFgbe1e08gMOz-deT:-MWnFgbe1e08gMOz-deU:b-cac54x) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic_test.go#L33)):*
> ```Go
> )
> 
> func TestMacInputGeneration(t *testing.T) {
> ```

Add a test for when the scion path would be nil
___
*[go/lib/epic/epic_test.go, line 46 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWnBcT92-BaI0EI-ojK:-MWnBcT92-BaI0EI-ojL:b-ldc2g1) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic_test.go#L46)):*
> ```Go
> }
> 
> func TestTimestamp(t *testing.T) {
> ```

This test only tests that `CreateEpicTimestamp` is the reverse of `ParseEpicTimestamp` but not that they are correct. You should test them individually.
___
*[go/lib/epic/epic_test.go, line 58 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWnC5XDBsoKDYSQAS_5:-MWnC5XDBsoKDYSQAS_6:b-8qp9cm) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic_test.go#L58)):*
> ```Go
> }
> 
> func TestTsRel(t *testing.T) {
> ```

This doesn't test the actual timestamp that is created, but only whether an error is returned or not. Please also check the actual timestamps.

Also, please convert to table driven tests with test names.
___
*[go/lib/epic/epic_test.go, line 87 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWnCpK78FTVcuJypprL:-MWnCpK78FTVcuJypprM:b-alb8av) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic_test.go#L87)):*
> ```Go
> 	csAndPl := uint32(libepic.ClockSkewMs + libepic.PacketLifetimeMs)
> 
> 	testCases := map[uint32]bool{
> ```

These test cases are hard to figure out what they do. Please follow our established pattern where 
```
testCases := map[string]struct{
    input uint32,
    expected bool
}{}
```
___
*[go/lib/epic/epic_test.go, line 104 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWnFJef-ha50yD-qAdh:-MWnFJef-ha50yD-qAdi:bxd80lx) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic_test.go#L104)):*
> ```Go
> }
> 
> func TestHVFVerification(t *testing.T) {
> ```

Please convert to table driven tests with test names. Make it much easier to verify (and later debug) what's going on.
___
*[go/lib/epic/epic_test.go, line 178 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWnFxjQBlSHBwJ-7WQe:-MWnFxjQBlSHBwJ-7WQf:bdhgs7x) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic_test.go#L178)):*
> ```Go
> 		createScionPath(1, 2):  true,
> 		createScionPath(2, 2):  false,
> 		createScionPath(0, -1): false,
> ```

Negative number of hops?
___
*[go/lib/epic/epic_test.go, line 222 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWnGDQh3TQnVtE2q3rG:-MWnGDQh3TQnVtE2q3rH:b-u9tkon) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic_test.go#L222)):*
> ```Go
> }
> 
> func randUint64() uint64 {
> ```

There is ` [...]

2021-03-30 12:29 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 6 of 17 files reviewed, 52 unresolved discussions (waiting on @karampok, @mawyss, @Oncilla, and @shitz)

___
*[go/lib/epic/epic.go, line 34 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWiejW3455iC1KuJJjN:-MWmklFl3hD8eeKcj6jg:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L34)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

`AuthLen`
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 36 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWiefX57MMjI6pDikv8:-MWmll885DYxqwHayzL9:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L36)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

`MaxPacketLifetime`
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 38 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWieZb62bVKR3TTVJIY:-MWmlm377Kf0F3bZ-7cz:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L38)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

`MaxClockSkew` or `MaxClockSkewMilliseconds`
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 42 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWh_OywBM5xmLFOuz9C:-MWmmg_Q8bWK-4oTs-nA:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L42)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

We don't use named return arguments in the code base. Please fix also in other places.
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 42 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWiageM41Ld01uu_vrp:-MX1GzPk2lqnPcuFFXBB:bplfiy) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L42)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Looking at this again, I find `Timestamp` not to be a suitable naming for the Epic Timestamp. More generically, it is a packet ID that contains a relative timestamp and a counter. Thus I propose you create something like

```
type PktID struct {
	Timestamp   uint32
	CoreID      uint8
	CoreCounter uint32
}

func (i *PktID) DecodeFromBytes(raw []byte) {
	i.Timestamp = binary.BigEndian.Uint32(raw[:4])
	coreInfo := binary.BigEndian.Uint32(raw[4:8])
	i.CoreID = uint8(coreInfo >> 24)
	i.CoreCounter = coreInfo & 0x00FFFFFF
}

func (i *PktID) SerializeTo(b []byte) {
	binary.BigEndian.PutUint32(b[:4], i.Timestamp)
	coreInfo := uint32(i.CoreID)<<24 | i.CoreCounter
	binary.BigEndian.PutUint32(b[4:8], coreInfo)
}
```

and work with that. 

Then, `Timestamp` would really only refer to what is now called `TsRel`
</blockquote></details>

Done. I added the code to the `epic.go` file from the `slayers` folder, because your code only does parsing.
___
*[go/lib/epic/epic.go, line 59 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWha-tb--Nr_hPxfwtq:-MWmoLuY4XbcBPpISa6t:b-e6ftpf) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L59)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Would drop this function as it's not needed.
</blockquote></details>

Done. (I added this function because the EPIC specification mentions that the combination of CoreID and CoreCounter is only a suggestion, but the end hosts could use their own identifier)
___
*[go/lib/epic/epic.go, line 88 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWib9uC-7_ODZj_IKNe:-MWmq6L-2AmIS0b_kAON:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L88)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

This would now be called `CreateTimestamp`
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 88 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWibDAX9C1QqvXLprck:-MWmq79DB24b3L5IWXf8:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L88)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> timestamp
> ```
I'd call this `input`
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 95 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWid6qI3oNykGf3kGzt:-MWmqbQ61oHk6yVQLtdw:bawevxv) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L95)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

No need for the `else` since you return in the error case

Also, `diff` is not really needed, since it's only used in one expression.
</blockquote></details>

Done. (I kept `diff` now because it is also used in the error)
___
*[go/lib/epic/epic.go, line 102 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWidXzgDXUfkoBXFGBa:-MWmuQEjDCEY9zs9QYlz:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L102)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

`serrors.New("diff between input and now >1d63min", "diff", ...)`

Also, translate it to something that is readable by a human instead of milliseconds. 
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 114 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWnCf1K08WJvHLeI5wa:-MX1ujtG5-WbZI7gXdFQ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L114)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

This should return an error instead of simply true or false.
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 131 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWifbMs4ry7LQD8bU5n:-MWmuWBl3zmSXWMqal3p:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L131)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

drop `else` since you return anyway in the other branch
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 138 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWikAIyB8ghg3wfonxI:-MWmuiXg7owNJxiPlKu_:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L138)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Should be called `CalcMac` -> reads then as `epic.CalcMac()`
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 138 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWnEmr32Ln9ozRdJwKP:-MWnTCZT-w2bWtYVfAjx:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L138)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> epicpath *epic.EpicPath
> ```
You don't need the entire path, only the `PktID` is needed (former timestamp)
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 151 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWigaLRCXmWk_cOp0wt:-MWmutQBAScmHu9x0XsS:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L151)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

You a [...]

2021-03-31 14:33 UTC, shitz requested changes
> Reviewed 7 of 11 files at r13.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 13 of 17 files reviewed, 23 unresolved discussions (waiting on @karampok, @mawyss, @Oncilla, and @shitz)

___
*[go/lib/epic/epic.go, line 59 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWha-tb--Nr_hPxfwtq:-MX7Ytga91YJo4LSth7b:bw1b817) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L59)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Done. (I added this function because the EPIC specification mentions that the combination of CoreID and CoreCounter is only a suggestion, but the end hosts could use their own identifier)
</blockquote></details>

see my comment about the `epic.PktID` below
___
*[go/lib/epic/epic.go, line 45 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7ZuaA87XhZRanlXcg:-MX7ZuaA87XhZRanlXch:b3zjeuc) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/lib/epic/epic.go#L45)):*
> ```Go
> // is returned. The current time  must be at most 1 day and 63 minutes after the input timestamp,
> // otherwise an error is returned.
> func CreateTimestamp(input uint32, nowNanoseconds int64) (uint32, error) {
> ```

It would be nicer to work with the `time` package
```
func CreateTimestamp(input time.Time, now time.Time) (uint32, error) {
	if input.After(now) {
		return 0, serrors.New("provided input timestamp is in the future",
			"input", input, "now", now)
	}
	diff := now.Sub(input).Microseconds()
	tsRel := diff/21 - 1
	if tsRel < 0 {
		tsRel = 0
	}
	if tsRel >= (1 << 32) {
		return 0, serrors.New("diff between input and now >1d63min",
			"diff", diff)
	}
	return uint32(tsRel), nil
}
```
___
*[go/lib/epic/epic.go, line 68 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7cN7g6Ce0zYCZ4PWf:-MX7cN7g6Ce0zYCZ4PWg:b-wdywt5) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/lib/epic/epic.go#L68)):*
> ```Go
> // a possible clock drift between the packet source and the verifier of up to one second into
> // account.
> func VerifyTimestamp(timestamp uint32, packetTimestamp uint32, nowNanoseconds int64) error {
> ```

This would also be nicer if it would work with the `time` package.
___
*[go/lib/epic/epic.go, line 93 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7cY3U0TBJtYPiH8Kx:-MX7cY3U0TBJtYPiH8Ky:brkgy1l) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/lib/epic/epic.go#L93)):*
> ```
> pktID *epic.PktID
> ```
Pass the `pktID` by value (it's fast). Then you can save yourself some nil-checks
___
*[go/lib/epic/epic.go, line 117 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7cjaZ2hHmYTjSMD1q:-MX7cjaZ2hHmYTjSMD1r:b-9q5qax) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/lib/epic/epic.go#L117)):*
> ```
> pktID *epic.PktID
> ```
pass by value
___
*[go/lib/epic/epic.go, line 181 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7dpHm4rrl6ccIBFa4:-MX7dpHm4rrl6ccIBFa5:be8vexo) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/lib/epic/epic.go#L181)):*
> ```Go
> 	// Fill input
> 	input[0] = srcAddrLen
> 	binary.BigEndian.PutUint32(input[1:5], timestamp)
> ```

Instead of these magic numbers it's cleaner if you use an offset counter
(see for example https://github.com/scionproto/scion/blob/master/go/lib/slayers/scion.go#L345)
___
*[go/lib/epic/epic.go, line 183 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7dRrUA6zTtYoBGmiM:-MX7dRrUA6zTtYoBGmiN:b-beb8b4) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/lib/epic/epic.go#L183)):*
> ```
> binary.BigEndian.PutUint64(input[13:21], uint64(s.SrcIA.A))
> ```
The IA can be written to bytes as
`s.SrcIA.Write(input[13:21])`
___
*[go/lib/slayers/path/epic/epic.go, line 62 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWjjvW_6ezV3VLK00k3:-MX7ehUb7bmA2CW_-65k:bfhqmln) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/slayers/path/epic/epic.go#L62)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Done. Thank you for the hint, I did not know so I went for the safer way.
</blockquote></details>

Not done?
___
*[go/lib/slayers/path/epic/epic.go, line 130 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7VbDv5tm6ycJ94_x7:-MX7VbDv5tm6ycJ94_x8:b-i1s754) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/lib/slayers/path/epic/epic.go#L130)):*
> ```Go
> 
> // PktID denotes the EPIC packet ID.
> type PktID struct {
> ```

Actually, I have a better suggestion that is more in line with the specification.

```
type PktID struct {
	Timestamp   uint32
	Counter uint32
}
```

and then in `go/lib/epic.go` define helper methods
```
func PktCounterFromCore(uint8 coreID, uint32 coreCounter) uint32
func CoreFromPktCounter(counter uint32) (uint8, uint32)
```

that way we leave the `epic.PktID` agnostic to the way the `Counter` is generated, but offer helper methods for one of the proposed procedures in the design doc.
___
*[go/pkg/router/dataplane.go, line 690 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWn25b-Cry3GoFP-mJ_:-MX7eyktD-l51uNHvNUd:b7kedpq) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/pkg/router/dataplane.go#L690)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

The idea is to block expired packets (timestamp in the past) already at the first hop(s), instead of letting the packet traverse the whole path until it is discarded by the last two hops only. But I understand if this is undesirable, as EPIC-HP should behave like SCION, except for the last two hops. Please let me know if you think it makes more sense to have it checked only at the penultimate and last hops.
</blockquote></details>

I'd prefer if only the last two border routers will treat the EPIC portion of a path. Sure, replays might travel a bit further, but in the benign (common) case intermediate routers have to do less work.
___
*[go/pkg/router/dataplane.go, line 716 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7gfAsEqR0dIq9Cmq2:-MX7gfAsEqR0dIq9Cmq3:bfca4im) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/pkg/router/dataplane.go#L716)):*
> ```Go
> 	}
> 
> 	if scionPath.IsPenultimateHop() {
> ```

I'd slightly prefer
```
	var hvf []byte
	if scionPath.IsPenultimateHop() {
		hvf = path.PHVF
	} else if scionPath.IsLastHop() {
		hvf = path.LHVF
	} else {
		return result, nil
	}

	if err := libepic.VerifyHVF(p.cachedMac, &path.PktID, &s, timestamp, hvf); err != nil {
		return processResult{}, err
	}
	return result, nil
```
(should create an SCMP reply of course)
___
*[go/pkg/router/dataplane.go, line 1256 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7guX9DXYZ7HJvgNZl:-MX7guX9DXYZ7HJvgNZm:bnrcozg) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/pkg/router/dataplane.go#L1256)):*
> ```
> 6
> ```
path.MacLen here and below


<!-- Sent from Reviewable.io -->

2021-03-31 21:08 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 7 of 17 files reviewed, 23 unresolved discussions (waiting on @karampok, @Oncilla, and @shitz)

___
*[go/lib/epic/epic.go, line 59 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWha-tb--Nr_hPxfwtq:-MX8zWhxCRGc_dDlJnKf:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/epic/epic.go#L59)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

see my comment about the `epic.PktID` below
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 45 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7ZuaA87XhZRanlXcg:-MX8n60NCxzlaH5pKcsW:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/lib/epic/epic.go#L45)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

It would be nicer to work with the `time` package
```
func CreateTimestamp(input time.Time, now time.Time) (uint32, error) {
	if input.After(now) {
		return 0, serrors.New("provided input timestamp is in the future",
			"input", input, "now", now)
	}
	diff := now.Sub(input).Microseconds()
	tsRel := diff/21 - 1
	if tsRel < 0 {
		tsRel = 0
	}
	if tsRel >= (1 << 32) {
		return 0, serrors.New("diff between input and now >1d63min",
			"diff", diff)
	}
	return uint32(tsRel), nil
}
```
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 68 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7cN7g6Ce0zYCZ4PWf:-MX8n1J0BJilhhz4llKB:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/lib/epic/epic.go#L68)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

This would also be nicer if it would work with the `time` package.
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 93 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7cY3U0TBJtYPiH8Kx:-MX8oeJX9rZ5ddnHMBsq:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/lib/epic/epic.go#L93)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> pktID *epic.PktID
> ```
Pass the `pktID` by value (it's fast). Then you can save yourself some nil-checks
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 117 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7cjaZ2hHmYTjSMD1q:-MX8oM3bBozrvDL-vSnQ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/lib/epic/epic.go#L117)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> pktID *epic.PktID
> ```
pass by value
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 181 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7dpHm4rrl6ccIBFa4:-MX8ojM82NEQJRGsGhDs:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/lib/epic/epic.go#L181)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Instead of these magic numbers it's cleaner if you use an offset counter
(see for example https://github.com/scionproto/scion/blob/master/go/lib/slayers/scion.go#L345)
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 183 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7dRrUA6zTtYoBGmiM:-MX8p2Fv3g7lphe3PKOM:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/lib/epic/epic.go#L183)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> binary.BigEndian.PutUint64(input[13:21], uint64(s.SrcIA.A))
> ```
The IA can be written to bytes as
`s.SrcIA.Write(input[13:21])`
</blockquote></details>

Done.
___
*[go/lib/slayers/path/epic/epic.go, line 62 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWjjvW_6ezV3VLK00k3:-MX8pHj4D5OkJxn_tkyV:bmfxgaw) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/lib/slayers/path/epic/epic.go#L62)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done :)
___
*[go/lib/slayers/path/epic/epic.go, line 130 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7VbDv5tm6ycJ94_x7:-MX8vWYH106rGQmzH2hH:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/lib/slayers/path/epic/epic.go#L130)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Actually, I have a better suggestion that is more in line with the specification.

```
type PktID struct {
	Timestamp   uint32
	Counter uint32
}
```

and then in `go/lib/epic.go` define helper methods
```
func PktCounterFromCore(uint8 coreID, uint32 coreCounter) uint32
func CoreFromPktCounter(counter uint32) (uint8, uint32)
```

that way we leave the `epic.PktID` agnostic to the way the `Counter` is generated, but offer helper methods for one of the proposed procedures in the design doc.
</blockquote></details>

Done.
___
*[go/pkg/router/dataplane.go, line 690 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWn25b-Cry3GoFP-mJ_:-MX7x6vQ-Ek0h7sMxYFI:bb6un1j) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/pkg/router/dataplane.go#L690)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

I'd prefer if only the last two border routers will treat the EPIC portion of a path. Sure, replays might travel a bit further, but in the benign (common) case intermediate routers have to do less work.
</blockquote></details>

Done
___
*[go/pkg/router/dataplane.go, line 703 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWjsbVq6i-6GAKujHlr:-MX8zqHj5A2VOHt2D6ms:b3ef5xc) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/pkg/router/dataplane.go#L703)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

You cannot simply discard the result of `p.process()`...
</blockquote></details>

I return `processResult{}` because I want to be sure the packet is dropped, I planned to implement SCMP responses in a separate PR. Please see my other comment regarding SCMP replies.
___
*[go/pkg/router/dataplane.go, line 709 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWjsNdRD53NgfmA3zlB:-MX9-XgZ7QLpAhVrzQ3-:bbcejdc) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/pkg/router/dataplane.go#L709)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

This should create a SCMP reply.
</blockquote></details>

If I understand correctly, the border router can currently only return SCMP packets for SCION path type packets, not for arbitrary path types: `prepareSCMP()` (`dataplane.go`) takes the path header as `path := s.scionL.Path.(*scion.Raw)`.
To implement EPIC SCMP replies I would go in the following direction:
- Try to parse the path as an EPIC path in the `prepareSCMP()` method.
- Send back a SCION SCMP response using the SCION path type header, not the EPIC path type header (the SCMP content would be the original EPIC packet however)
- The SCMP type would be a `Parameter Problem`, with a new code (e.g., 54)
- Add tests to `go/integration/braccept/cases`
Can you please let me know if this is the right way to approach this, or point me to a better direction?
___
*[go/pkg/router/dataplane.go, line 716 at r13](https://reviewable.io/reviews/scionproto/scion/3951#-MX7gfAsEqR0dIq9Cmq2:-MX7xrqL4dZgItlC12Tb:b-nzkrhc) ([raw file](https://github.com/scionproto/scion/blob/74113bcdcb50c424b458ca9f5a90005ca7f41975/go/pkg/router/dataplane.go#L716)) [...]

2021-04-01 09:41 UTC, shitz requested changes
> Reviewed 1 of 11 files at r13, 9 of 9 files at r14.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: all files reviewed, 24 unresolved discussions (waiting on @mawyss, @Oncilla, and @sgmonroy)

___
*[go/lib/epic/epic.go, line 34 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBS2vV13jmXT2A07Oj:-MXBS2vV13jmXT2A07Ok:brpwitz) ([raw file](https://github.com/scionproto/scion/blob/3db3d36b70bcd0b57d17664c157f90d3e42664a5/go/lib/epic/epic.go#L34)):*
> ```
> in microseconds
> ```
drop "in microsecond" here and below
___
*[go/lib/epic/epic.go, line 49 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBZM_u1Z_7y8q_qvrg:-MXBZM_u1Z_7y8q_qvrh:b-7s276y) ([raw file](https://github.com/scionproto/scion/blob/3db3d36b70bcd0b57d17664c157f90d3e42664a5/go/lib/epic/epic.go#L49)):*
> ```Go
> 			"input", input, "now", now)
> 	}
> 	diff := now.Sub(input).Microseconds()
> ```

With my suggestion below this block can become
```
        diff := now.Sub(input)/TimestampResolution - 1
	if diff < 0 {
		diff = 0
	}
	if diff >= (1 << 32) {
		return 0, serrors.New("diff between input and now >1d63min", "diff", diff)
	}
	return uint32(diff), nil
```
___
*[go/lib/epic/epic.go, line 56 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBT65FEG9SA1Pk4y7x:-MXBT65FEG9SA1Pk4y7y:b3kd1x6) ([raw file](https://github.com/scionproto/scion/blob/3db3d36b70bcd0b57d17664c157f90d3e42664a5/go/lib/epic/epic.go#L56)):*
> ```Go
> 	if tsRel >= (1 << 32) {
> 		return 0, serrors.New("diff between input and now >1d63min",
> 			"diff", diff)
> ```

This can now be one line.
___
*[go/lib/epic/epic.go, line 66 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBbSSd5HM-vkIIfDc4:-MXBbSSd5HM-vkIIfDc5:b-8ws05h) ([raw file](https://github.com/scionproto/scion/blob/3db3d36b70bcd0b57d17664c157f90d3e42664a5/go/lib/epic/epic.go#L66)):*
> ```
> packetTimestamp
> ```
let's call this `epicTimestamp`
___
*[go/lib/epic/epic.go, line 67 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBY0Y14fsWhM-KwAyy:-MXBY0Y26sWyN_cu61hC:b-3gtulq) ([raw file](https://github.com/scionproto/scion/blob/3db3d36b70bcd0b57d17664c157f90d3e42664a5/go/lib/epic/epic.go#L67)):*
> ```
> 21
> ```
Introduce a constant for this, e.g., `TimestampResolution = 21 * time.Microsecond
___
*[go/lib/epic/epic.go, line 200 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBa1Ih52763mKVZ7X2:-MXBa1Ih52763mKVZ7X3:b-y7l452) ([raw file](https://github.com/scionproto/scion/blob/3db3d36b70bcd0b57d17664c157f90d3e42664a5/go/lib/epic/epic.go#L200)):*
> ```Go
> }
> 
> func max(x, y uint64) uint64 {
> ```

This is not used anymore.
___
*[go/lib/slayers/path/epic/epic_test.go, line 71 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBmRiNCsBf67QoE8vh:-MXBmRiNCsBf67QoE8vi:bee2v85) ([raw file](https://github.com/scionproto/scion/blob/3db3d36b70bcd0b57d17664c157f90d3e42664a5/go/lib/slayers/path/epic/epic_test.go#L71)):*
> ```Go
> )
> 
> func TestSerialize(t *testing.T) {
> ```

Add tests for error conditions in `SerializeTo` (at least for a HVF that is not long enough and a nil scion path)
___
*[go/lib/slayers/path/epic/epic_test.go, line 249 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBn5_qDOy0NGNKPOHi:-MXBn5_qDOy0NGNKPOHj:b6zq78t) ([raw file](https://github.com/scionproto/scion/blob/3db3d36b70bcd0b57d17664c157f90d3e42664a5/go/lib/slayers/path/epic/epic_test.go#L249)):*
> ```Go
> 			PktID: epic.PktID{
> 				Timestamp: 1,
> 				Counter:   libepic.PktCounterFromCore(2, 3),
> ```

These test shouldn't use the helper methods, since `PktID.Counter` is agnostic to them.

`PktCounterFromCore` and `CoreFromPktCounter` should be tested in `go/lib/epic/epic_test.go`
___
*[go/pkg/router/dataplane.go, line 703 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWjsbVq6i-6GAKujHlr:-MXBbd6N8RT10DInWBVE:b-6pfqta) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/pkg/router/dataplane.go#L703)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

I return `processResult{}` because I want to be sure the packet is dropped, I planned to implement SCMP responses in a separate PR. Please see my other comment regarding SCMP replies.
</blockquote></details>

Ok no problem. Add TODOs then to add SCMP replies in the appropriate places.
___
*[go/pkg/router/dataplane.go, line 709 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWjsNdRD53NgfmA3zlB:-MXBdHFq1_TNZgBWvxvy:b-ea6k51) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/pkg/router/dataplane.go#L709)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

If I understand correctly, the border router can currently only return SCMP packets for SCION path type packets, not for arbitrary path types: `prepareSCMP()` (`dataplane.go`) takes the path header as `path := s.scionL.Path.(*scion.Raw)`.
To implement EPIC SCMP replies I would go in the following direction:
- Try to parse the path as an EPIC path in the `prepareSCMP()` method.
- Send back a SCION SCMP response using the SCION path type header, not the EPIC path type header (the SCMP content would be the original EPIC packet however)
- The SCMP type would be a `Parameter Problem`, with a new code (e.g., 54)
- Add tests to `go/integration/braccept/cases`
Can you please let me know if this is the right way to approach this, or point me to a better direction?
</blockquote></details>

Overall, that sounds ok to me. Generally, I'm not a big fan of mingling the EPIC handling code too much with the SCION path handling code, however, EPIC-HP is so close to SCION Path handling that it's ok in this case. For other path types we should definitely refactor the code and have different "processors" per path type.

Regarding new SCMP codes: I'm not sure we need to define new codes or if we should just map them to `Path Expired (52)` and `Invalid Hop Field MAC (51)` respectively. Paging @oncilla and @sgmonroy to weigh in on this as well.

For this PR, it's fine if you leave out SCMP replies. As discussed above, you should add the appropriate todos.
___
*[go/pkg/router/dataplane.go, line 714 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBbBZS0fHvOMSpL1d2:-MXBao4B6Rd3AfhP2veI:b-7xpbpw) ([raw file](https://github.com/scionproto/scion/blob/3db3d36b70bcd0b57d17664c157f90d3e42664a5/go/pkg/router/dataplane.go#L714)):*
> ```
> packetTimestamp
> ```
packetTimestamp and now can be rolled into the function call directly.
```
		timestamp := time.Unix(int64(info.Timestamp), 0)
		if err = libepic.VerifyTimestamp(timestamp, path.PktID.Timestamp, time.Now()); err != nil {
			return processResult{}, err
		}
```
___
*[go/pkg/router/dataplane_test.go, line 1070 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBghOn70lMHaAgJ1kI:-MXBghOn70lMHaAgJ1kJ:bg23pjc) ([raw file](https://github.com/scionproto/scion/blob/3db3d36b70bcd0b57d17664c157f90d3e42664a5/go/pkg/router/dataplane_test.go#L1070)):*
> ```Go
> 			assertFunc:   assert.Error,
> 		},
> 		"epic inbound": {
> ```

You should add a few more test regarding the epic processing:

* the happy case (this one you have already)
* a malformed epic path case
* an invalid timestamp case
* an invalid MAC case

ideally those would also test that the appropriate SCMP replies are generated, but I see that the current testing code also doesn't do that.
___
*[go/pkg/router/dataplane_test.go, line 1118 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBhxry5baX9GjGsDMa:-MXBhxry5baX9GjGsDMb:bmcxgf5) ([raw file](https://github.com/scionproto/scion/blob/3db3d36b70bcd0b57d17664c157f90d3e42664a5/go/pkg/router/dataplane_test.go#L1118)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 				var tsRel uint32
> 				if afterProcessing {
> 					tsRel = cachedEpicTsRel
> 				} else {
> 					tsRel, _ = libepic.CreateTimestamp(time.Unix(in [...]

2021-04-07 10:51 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 9 of 67 files reviewed, 24 unresolved discussions (waiting on @Oncilla, @sgmonroy, and @shitz)

___
*[go/lib/epic/epic.go, line 34 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBS2vV13jmXT2A07Oj:-MXba7cW74OjpiKw7ZC2:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b1ab3b2f61b8a3a596a8f55093d4ae5a190b638d/go/lib/epic/epic.go#L34)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> in microseconds
> ```
drop "in microsecond" here and below
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 49 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBZM_u1Z_7y8q_qvrg:-MXbb8mp4VqNX6SDGHcA:bltw6dw) ([raw file](https://github.com/scionproto/scion/blob/b1ab3b2f61b8a3a596a8f55093d4ae5a190b638d/go/lib/epic/epic.go#L49)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

With my suggestion below this block can become
```
        diff := now.Sub(input)/TimestampResolution - 1
	if diff < 0 {
		diff = 0
	}
	if diff >= (1 << 32) {
		return 0, serrors.New("diff between input and now >1d63min", "diff", diff)
	}
	return uint32(diff), nil
```
</blockquote></details>

Done, but I replaced `diff` by `tsRel`, because with your suggestion `diff` would not denote a time difference anymore, but the (relative) epic timestamp.
___
*[go/lib/epic/epic.go, line 56 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBT65FEG9SA1Pk4y7x:-MXbKhPSAmb4IMsDM4pN:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b1ab3b2f61b8a3a596a8f55093d4ae5a190b638d/go/lib/epic/epic.go#L56)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

This can now be one line.
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 66 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBbSSd5HM-vkIIfDc4:-MXbKwmDAjpEOZXTzKH7:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b1ab3b2f61b8a3a596a8f55093d4ae5a190b638d/go/lib/epic/epic.go#L66)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> packetTimestamp
> ```
let's call this `epicTimestamp`
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 67 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBY0Y14fsWhM-KwAyy:-MXbLKFKCTbyk4C8yybo:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b1ab3b2f61b8a3a596a8f55093d4ae5a190b638d/go/lib/epic/epic.go#L67)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> 21
> ```
Introduce a constant for this, e.g., `TimestampResolution = 21 * time.Microsecond
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 200 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBa1Ih52763mKVZ7X2:-MXbLOU910aRDGOszizm:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b1ab3b2f61b8a3a596a8f55093d4ae5a190b638d/go/lib/epic/epic.go#L200)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

This is not used anymore.
</blockquote></details>

Done.
___
*[go/lib/slayers/path/epic/epic_test.go, line 71 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBmRiNCsBf67QoE8vh:-MXce6LZ27j2XuQriDLK:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b1ab3b2f61b8a3a596a8f55093d4ae5a190b638d/go/lib/slayers/path/epic/epic_test.go#L71)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Add tests for error conditions in `SerializeTo` (at least for a HVF that is not long enough and a nil scion path)
</blockquote></details>

Done.
___
*[go/lib/slayers/path/epic/epic_test.go, line 249 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBn5_qDOy0NGNKPOHi:-MXcwkOn63BBfCsHTHFf:bamee9s) ([raw file](https://github.com/scionproto/scion/blob/b1ab3b2f61b8a3a596a8f55093d4ae5a190b638d/go/lib/slayers/path/epic/epic_test.go#L249)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

These test shouldn't use the helper methods, since `PktID.Counter` is agnostic to them.

`PktCounterFromCore` and `CoreFromPktCounter` should be tested in `go/lib/epic/epic_test.go`
</blockquote></details>

Done. I specified the `Counter` as hexadecimal value  so that it is easier to understand, and added the `PktCounterFromCore` and `CoreFromPktCounter` function following your suggestion.
___
*[go/pkg/router/dataplane.go, line 703 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWjsbVq6i-6GAKujHlr:-MXd-U3h6xAvYMkqbGZ9:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/pkg/router/dataplane.go#L703)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Ok no problem. Add TODOs then to add SCMP replies in the appropriate places.
</blockquote></details>

Done.
___
*[go/pkg/router/dataplane.go, line 709 at r12](https://reviewable.io/reviews/scionproto/scion/3951#-MWjsNdRD53NgfmA3zlB:-MXczb7-9kVTqp-XJkyJ:bp63w06) ([raw file](https://github.com/scionproto/scion/blob/78028d4a16cf2f3f995b522117e212f3abbe32b8/go/pkg/router/dataplane.go#L709)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Overall, that sounds ok to me. Generally, I'm not a big fan of mingling the EPIC handling code too much with the SCION path handling code, however, EPIC-HP is so close to SCION Path handling that it's ok in this case. For other path types we should definitely refactor the code and have different "processors" per path type.

Regarding new SCMP codes: I'm not sure we need to define new codes or if we should just map them to `Path Expired (52)` and `Invalid Hop Field MAC (51)` respectively. Paging @oncilla and @sgmonroy to weigh in on this as well.

For this PR, it's fine if you leave out SCMP replies. As discussed above, you should add the appropriate todos.
</blockquote></details>

I added TODOs to the SCION path type processing result, the timestamp verification and the PHVF/LHVF validation. Furthermore, I implemented a validation of the correct path type in `prepareSCMP`.
___
*[go/pkg/router/dataplane.go, line 714 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBbBZS0fHvOMSpL1d2:-MXcypQq-ITeGhvOnyys:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b1ab3b2f61b8a3a596a8f55093d4ae5a190b638d/go/pkg/router/dataplane.go#L714)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> packetTimestamp
> ```
packetTimestamp and now can be rolled into the function call directly.
```
		timestamp := time.Unix(int64(info.Timestamp), 0)
		if err = libepic.VerifyTimestamp(timestamp, path.PktID.Timestamp, time.Now()); err != nil {
			return processResult{}, err
		}
```
</blockquote></details>

Done.
___
*[go/pkg/router/dataplane_test.go, line 1070 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBghOn70lMHaAgJ1kI:-MXfgY6X8KLZ98pBNTv3:bcscilc) ([raw file](https://github.com/scionproto/scion/blob/b1ab3b2f61b8a3a596a8f55093d4ae5a190b638d/go/pkg/router/dataplane_test.go#L1070)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

You should add a few more test regarding the epic processing:

* the happy case (this one you have already)
* a malformed epic path case
* an invalid timestamp case
* an invalid MAC case

ideally those would also test that the appropriate SCMP replies are generated, but I see that the current testing code also doesn't do that.
</blockquote></details>

Done. I also wrote some auxiliary functions to get rid of redundant code.
___
*[go/pkg/router/dataplane_test.go, line 1118 at r14](https://reviewable.io/reviews/scionproto/scion/3951#-MXBhxry5baX9GjGsDMa:-MXbWv1HBc9gy95L5RPa:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b1ab3b2f61b8a3a596a8f55093d4 [...]

2021-04-07 17:24 UTC, shitz requested changes
> Reviewed 8 of 8 files at r15.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: all files reviewed, 5 unresolved discussions (waiting on @mawyss and @Oncilla)

___
*[go/cs/onehop/sender_test.go, line 59 at r15](https://reviewable.io/reviews/scionproto/scion/3951#-MXhAGd99qMj3nMZdgDo:-MXhAGd99qMj3nMZdgDp:bbxinza) ([raw file](https://github.com/scionproto/scion/blob/d649896395d0ba0c6b908b3799489949dbfac644/go/cs/onehop/sender_test.go#L59)):*
> ```Go
> 	assert.Equal(t, uint16(12), hop.ConsEgress)
> 	assert.Equal(t, uint8(63), hop.ExpTime)
> 	fullMac := libpath.FullMAC(createMac(t), &info, &hop)
> ```

nit - this can call `libpath.MAC`
___
*[go/lib/epic/epic.go, line 42 at r15](https://reviewable.io/reviews/scionproto/scion/3951#-MXhAhu_Cvx6UnHGAlOT:-MXhAhu_Cvx6UnHGAlOU:b4a5xrc) ([raw file](https://github.com/scionproto/scion/blob/d649896395d0ba0c6b908b3799489949dbfac644/go/lib/epic/epic.go#L42)):*
> ```
> tsRel
> ```
What do you think about renaming all `tsRel` instances with `epic timestamp` in doc strings and `epicTS` in code?
___
*[go/pkg/router/dataplane.go, line 1424 at r15](https://reviewable.io/reviews/scionproto/scion/3951#-MXhLB7PEpw4z8x5Zg-S:-MXhLB7PEpw4z8x5Zg-T:b-r3jkf6) ([raw file](https://github.com/scionproto/scion/blob/d649896395d0ba0c6b908b3799489949dbfac644/go/pkg/router/dataplane.go#L1424)):*
> ```
> reflect.TypeOf(path)
> ```
just use `s.scionL.Path.Type()`. reflect is very inefficient.
___
*[go/pkg/router/dataplane_test.go, line 1287 at r15](https://reviewable.io/reviews/scionproto/scion/3951#-MXhM7k42pLOWMug5eVz:-MXhM7k42pLOWMug5eW-:b-gmyb86) ([raw file](https://github.com/scionproto/scion/blob/d649896395d0ba0c6b908b3799489949dbfac644/go/pkg/router/dataplane_test.go#L1287)):*
> ```Go
> 	// Encapsulate in IPv4
> 	dst := &net.IPAddr{IP: net.ParseIP("10.0.100.100").To4()}
> 	_ = spkt.SetDstAddr(dst)
> ```

`require.NoError(t, spkt.SetDstAddr(dst))`
___
*[go/lib/epic/epic_test.go, line 81 at r15](https://reviewable.io/reviews/scionproto/scion/3951#-MXhIdiF4f63N_Zcn5wP:-MXhIdiF4f63N_Zcn5wQ:bq83sra) ([raw file](https://github.com/scionproto/scion/blob/d649896395d0ba0c6b908b3799489949dbfac644/go/lib/epic/epic_test.go#L81)):*
> ```Go
> 		},
> 		"Timestamp one day and 64 minutes in the past": {
> 			Timestamp: now.Add(-createTimeHMS(24, 64, 0)),
> ```

Shouldn


<!-- Sent from Reviewable.io -->

2021-04-07 23:23 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: 12 of 18 files reviewed, 4 unresolved discussions (waiting on @karampok, @Oncilla, and @shitz)

___
*[go/cs/onehop/sender_test.go, line 59 at r15](https://reviewable.io/reviews/scionproto/scion/3951#-MXhAGd99qMj3nMZdgDo:-MXiM8ih3q8fhPEH8sGz:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d649896395d0ba0c6b908b3799489949dbfac644/go/cs/onehop/sender_test.go#L59)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

nit - this can call `libpath.MAC`
</blockquote></details>

Done.
___
*[go/lib/epic/epic.go, line 42 at r15](https://reviewable.io/reviews/scionproto/scion/3951#-MXhAhu_Cvx6UnHGAlOT:-MXiZg9o-9qRPCfRGDCu:b-69hjjg) ([raw file](https://github.com/scionproto/scion/blob/d649896395d0ba0c6b908b3799489949dbfac644/go/lib/epic/epic.go#L42)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> tsRel
> ```
What do you think about renaming all `tsRel` instances with `epic timestamp` in doc strings and `epicTS` in code?
</blockquote></details>

Done. I also applied this to the header specification (`scion-header.rst`).
___
*[go/pkg/router/dataplane.go, line 1424 at r15](https://reviewable.io/reviews/scionproto/scion/3951#-MXhLB7PEpw4z8x5Zg-S:-MXiNmAc7Eb-UiW-g_Rb:b-jhc7ut) ([raw file](https://github.com/scionproto/scion/blob/d649896395d0ba0c6b908b3799489949dbfac644/go/pkg/router/dataplane.go#L1424)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> reflect.TypeOf(path)
> ```
just use `s.scionL.Path.Type()`. reflect is very inefficient.
</blockquote></details>

Done. Thank you for the hint, I was not aware that reflect does not perform well.
___
*[go/pkg/router/dataplane_test.go, line 1287 at r15](https://reviewable.io/reviews/scionproto/scion/3951#-MXhM7k42pLOWMug5eVz:-MXiOzcnEZ4ecDuiJKw5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d649896395d0ba0c6b908b3799489949dbfac644/go/pkg/router/dataplane_test.go#L1287)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

`require.NoError(t, spkt.SetDstAddr(dst))`
</blockquote></details>

Done.
___
*[go/lib/epic/epic_test.go, line 81 at r15](https://reviewable.io/reviews/scionproto/scion/3951#-MXhIdiF4f63N_Zcn5wP:-MXiN3RIDshFiiYpyDF_:b-o53bo9) ([raw file](https://github.com/scionproto/scion/blob/d649896395d0ba0c6b908b3799489949dbfac644/go/lib/epic/epic_test.go#L81)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Shouldn
</blockquote></details>

I don't understand this comment, it looks like the end of the sentence is missing?


<!-- Sent from Reviewable.io -->

2021-04-08 06:49 UTC, karampok reviewed
> Reviewed 2 of 11 files at r13, 1 of 9 files at r14, 4 of 8 files at r15, 6 of 6 files at r16.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951)* status: all files reviewed, 4 unresolved discussions (waiting on @Oncilla and @shitz)



<!-- Sent from Reviewable.io -->

2021-04-08 09:50 UTC, shitz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3951#-:-MXksu4EAAdBrlGI-5eP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Oncilla)

___
*[go/lib/epic/epic_test.go, line 81 at r15](https://reviewable.io/reviews/scionproto/scion/3951#-MXhIdiF4f63N_Zcn5wP:-MXkse2x5ej8mNwp24rd:b8mei10) ([raw file](https://github.com/scionproto/scion/blob/d649896395d0ba0c6b908b3799489949dbfac644/go/lib/epic/epic_test.go#L81)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

I don't understand this comment, it looks like the end of the sentence is missing?
</blockquote></details>

Sorry that was an unfinished thought that I abandoned, but somehow reviewable still picked it up.


<!-- Sent from Reviewable.io -->

2021-04-08 10:12 UTC, Oncilla commented
/rebase

2021-04-09 09:47 UTC, closed without merging