epic-hp: controlplane
scionproto/scion pull request #3954
Opened 2020-12-15 13:39 UTC by mawyss

This PR implements the EPIC control plane changes as described in [1]. It improves the structure of the previous PR [2] according to the suggestion from [3].

- Add an EPICDetachedExtension to the beacon. This extension does not get signed and can therefore be detached.
- Add a DigestExtension to the PathSegmentExtensions, which holds the hash of EPICDetachedExtension. This hash is therefore signed.
- Overhead: no new MAC needs to be calculated, only one additional hash per AS.

[1] https://scion.docs.anapaya.net/en/latest/EPIC.html#control-plane
[2] https://github.com/scionproto/scion/pull/3944
[3] https://github.com/scionproto/scion/commit/3a5ea8e8bce43ccb4407ce2e2056475c9320820c

2021-01-14 08:08 UTC, karampok commented
Hi @mawyss fyi, this PR has not been forgotten but we are lacking the time and the resources to have a look.

2021-01-14 12:22 UTC, mawyss reviewed
Ok, thank you for the info! 
Can you make a rough estimate on when you to have time/resources again? This would help me to plan the next steps, as I would like to start with implementing the EPIC path fetching and packet creation at the end host, for which I need the EPIC data and control plane to be ready.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3954#-:-MR-lzGj6EjvXWEjknP2:b5jwk4v)* status: 0 of 28 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-14 15:34 UTC, karampok commented
I cannot personally estimate but probably will be beginning of February.

2021-02-16 13:21 UTC, karampok reviewed
> Reviewed 2 of 27 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3954)* status: 3 of 28 files reviewed, 9 unresolved discussions (waiting on @mawyss and @Oncilla)

___
*[Makefile, line 36 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTenAo76zVP-seP78jD:-MTenAo76zVP-seP78jE:b-gjopby) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/Makefile#L36)):*
> ```Makefile
> 	rm -f go/pkg/proto/*/*.pb.go
> 	cp -r bazel-bin/go/pkg/proto/*/go_default_library_/github.com/scionproto/scion/go/pkg/proto/* go/pkg/proto
> 	cp -r bazel-bin/go/pkg/proto/*/*/go_default_library_/github.com/scionproto/scion/go/pkg/proto/* go/pkg/proto
> ```

I cannot really tell, what `*/*` is adding exactly.

I can see 
```
[I] kka@kkahost ~/w/scionproto (epic_cp ✖1)> tree -L 2 bazel-bin/go/pkg/proto/
bazel-bin/go/pkg/proto/
├── control_plane
│   ├── experimental
│   ├── go_default_library_
│   ├── go_default_library.a
│   └── go_default_library.x
├── crypto
│   ├── go_default_library_
│   ├── go_default_library.a
│   └── go_default_library.x
├── daemon
│   ├── go_default_library_
│   ├── go_default_library.a
│   └── go_default_library.x
├── discovery
│   ├── go_default_library_
│   ├── go_default_library.a
│   └── go_default_library.x
├── gateway
│   ├── go_default_library_
│   ├── go_default_library.a
│   └── go_default_library.x
└── hidden_segment
    ├── go_default_library_
    ├── go_default_library.a
```
___
*[go/cs/beaconing/extender.go, line 112 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTerkFm3DGDxFajm74E:-MTerkFm3DGDxFajm74F:bi1wp5t) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/cs/beaconing/extender.go#L112)):*
> ```Go
> 
> 	// Add the detachable Epic extension
> 	epicDetachedExtension := &epic_detached.EpicDetached{
> ```

For readability, this variable can have a sort name (like e )
___
*[go/cs/beaconing/extender.go, line 117 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTeq-meEFykv5IyeNtw:-MTeq-meEFykv5IyeNtx:b-98d4li) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/cs/beaconing/extender.go#L117)):*
> ```Go
> 	}
> 	asEntry.UnsignedExtensions.EpicDetached = epicDetachedExtension
> 	epicHash, err := digest.CalcEpicDigest(epicDetachedExtension)
> ```

This seems to me like it should be a method rather than a function. Any reason why it is like that?
(probably to be similar to something existing)

Also, use full name `CalculateEpicDigest` not `CalcX` or without `Calc` 
Also, if returns Digest, then the `epicHash` should be `epicDigest` (detail)
___
*[go/lib/ctrl/seg/as.go, line 52 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTesTK-3X9heSdlpL5W:-MTesTK-3X9heSdlpL5X:bz764yo) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/as.go#L52)):*
> ```Go
> 	// UnsignedExtensions holds all the unsigned beaconing extensions.
> 	UnsignedExtensions unsigned_extensions.UnsignedExtensions
> }
> ```

I see all the words triple.
Nevertheless,  I am not sure how it could look like.
Maybe  `UExtension UnsignedExtension` 

and  the UnsignedExtension to be under the Extension

(no specific ask, just discussing)
___
*[go/lib/ctrl/seg/as.go, line 95 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTeukJH27QEB8DTrony:-MTeukJH27QEB8DTronz:bloscx2) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/as.go#L95)):*
> ```Go
> 	extensions := extensionsFromPB(entry.Extensions)
> 	unsignedExtensions := unsigned_extensions.UnsignedExtensionsFromPB(pb.Unsigned)
> 	err = checkUnsignedExtensions(&unsignedExtensions, &extensions)
> ```

I  think having something like that
```
....

ret= ASEntry{  ...}

if ue:=  unsigned_extensions.UnsignedExtensionsFromPB(pb.Unsigned); ue !=nil{
  ret.UExtension= ue
  return er, checkUnsignedExtension()
}

return ret,nil

```

 
___
*[go/lib/ctrl/seg/as.go, line 115 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTewizg1zUrCia_-Jvb:-MTewizh1BVigVqj5dE7:b1hlq2e) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/as.go#L115)):*
> ```Go
> // signed hash. Furthermore, an unsigned extension is not valid if it is present in the
> // ASEntry, but the corresponding hash is not.
> func checkUnsignedExtensions(ue *unsigned_extensions.UnsignedExtensions, e *Extensions) error {
> ```

It would be nicer to hide this check function inside the UnsignedExtension packet.
And maybe the signature to have only what is really required (`ue.EpicDtached` `e.Digest`)
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 31 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTexJZw1vDca_yDzyB9:-MTexJZw1vDca_yDzyBA:bkjxdot) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions/digest/digest.go#L31)):*
> ```Go
> const EpicDigestLength = 16
> 
> type DigestExtension struct {
> ```

Do we plan to have more fields here?
Otherwise, it seems there is an extra level of nested struct that is not really needed
___
*[go/lib/ctrl/seg/unsigned_extensions/unsigned_extensions.go, line 22 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTexcHME-qM37XjaZz_:-MTexcHME-qM37XjaZza:bkjxdot) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/unsigned_extensions/unsigned_extensions.go#L22)):*
> ```Go
> )
> 
> type UnsignedExtensions struct {
> ```

Do we plan to have more fields here?
Otherwise, it seems there is an extra level of nested struct that is not really needed
___
*[go/lib/ctrl/seg/unsigned_extensions/epic_detached/epic_detached.go, line 15 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTexjpFAzvV9i0KPzeZ:-MTexjpFAzvV9i0KPze_:bk75nel) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/unsigned_extensions/epic_detached/epic_detached.go#L15)):*
> ```Go
> // limitations under the License.
> 
> package epic_detached
> ```

Is this something it needs to be in the control plane or we can have it in a `go/lib/epic` package?
In general, is possible to transfer the epic logic in its own package?


<!-- Sent from Reviewable.io -->

2021-02-16 14:17 UTC, Oncilla requested changes
> Reviewed 8 of 27 files at r1, 1 of 2 files at r3, 1 of 3 files at r4, 2 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3954)* status: 14 of 28 files reviewed, 12 unresolved discussions (waiting on @karampok and @mawyss)

___
*[go/lib/ctrl/seg/as.go, line 52 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTesTK-3X9heSdlpL5W:-MTf86TP-WJh34Xr7les:b-4e89a9) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/as.go#L52)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

I see all the words triple.
Nevertheless,  I am not sure how it could look like.
Maybe  `UExtension UnsignedExtension` 

and  the UnsignedExtension to be under the Extension

(no specific ask, just discussing)
</blockquote></details>

We have agreed that we support unsigned extensions.

I don't think this warrants its own package.

IMO, `UnsignedExtensions` should be a type defined in this package.
i.e., move the definition to `go/lib/ctrl/seg/unsigned_extensions.go`
___
*[go/lib/ctrl/seg/as.go, line 95 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTeukJH27QEB8DTrony:-MTf9CuVAvgGd_nlxdQw:bp74ck7) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/as.go#L95)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

I  think having something like that
```
....

ret= ASEntry{  ...}

if ue:=  unsigned_extensions.UnsignedExtensionsFromPB(pb.Unsigned); ue !=nil{
  ret.UExtension= ue
  return er, checkUnsignedExtension()
}

return ret,nil

```

 
</blockquote></details>

I don't think this functionality belongs here at all.

Putting validation logic with parsing logic leads to very convoluted design.
It also means that you cannot parse a malformed segment, which is not always desired.

This validation should be done as a step in `PathSegment.Validate`
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 31 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTexJZw1vDca_yDzyB9:-MTfBjnmABmVL_YGRfWe:bhzrnwo) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions/digest/digest.go#L31)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

Do we plan to have more fields here?
Otherwise, it seems there is an extra level of nested struct that is not really needed
</blockquote></details>

The structure is correct, this was agreed upon before hand.

The digest extension is a general concept not specific to Epic.
___
*[proto/control_plane/v1/seg_extensions.proto, line 28 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTeJsc_-w6JeIhZJ6Z-:-MTeJsc_-w6JeIhZJ6Z0:blzj4q2) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/proto/control_plane/v1/seg_extensions.proto#L28)):*
> ```protobuf
>     // Optional hidden path extension.
>     HiddenPathExtension hidden_path = 2;
>     
> ```

drop the four spaces here.
___
*[proto/control_plane/v1/seg_extensions.proto, line 133 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTeKLg13EiIW1JkD322:-MTeKLg13EiIW1JkD323:b-j20fak) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/proto/control_plane/v1/seg_extensions.proto#L133)):*
> ```protobuf
>     }
> 
>     // The digest of the detached EPIC extension.
> ```

Please add a description how the input for the digest is calculated,
similar to `ASEntry.signed` in `seg.proto`
___
*[proto/control_plane/v1/seg_extensions.proto, line 139 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTeLXDM1xLbGkipXgSN:-MTeLXDM1xLbGkipXgSO:b-4s9v2d) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/proto/control_plane/v1/seg_extensions.proto#L139)):*
> ```protobuf
> message PathSegmentUnsignedExtensions {
>     // Optional EPIC extension.
>     proto.control_plane.experimental.v1.EPICDetachedExtension epic_detached_extension = 1000;
> ```

just call this field `epic`. It is clear from the type that it is a detached extension.


<!-- Sent from Reviewable.io -->

2021-02-16 15:45 UTC, Oncilla requested changes
> Reviewed 5 of 27 files at r1, 6 of 8 files at r2, 1 of 2 files at r3, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3954)* status: all files reviewed, 28 unresolved discussions (waiting on @karampok and @mawyss)

___
*[go/cs/beaconing/extender.go, line 66 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfVVF384eBKEHz_EbW:-MTfVVF43HHWfKlwCqB7:bdxoclg) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/cs/beaconing/extender.go#L66)):*
> ```Go
> 	// StaticInfo contains the configuration used for the StaticInfo Extension.
> 	StaticInfo func() *StaticInfoCfg
> }
> ```

Please add a way to enable epic here.
By default, epic should be turned off.

So, something like a field `EPIC bool`

Also, please do not add the code to enable this through a config in this PR.
We can do it in a follow up PR, because this PR is already pretty large in size.

The smaller the PR, the faster we can iterate on it.
___
*[go/lib/ctrl/seg/extensions_test.go, line 26 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfGb8NBzpVDluIUQBf:-MTfGb8NBzpVDluIUQBg:b-9bo6w2) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions_test.go#L26)):*
> ```Go
> )
> 
> func TestDecodeEncodeEpicDigest(t *testing.T) {
> ```

What are you trying to test here? Maybe there is a more concise way.
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 27 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfCSkZ7ypthBMPYskc:-MTfCSkZ7ypthBMPYskd:bwyzu7v) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions/digest/digest.go#L27)):*
> ```Go
> )
> 
> type Digest []byte
> ```

I would rather this to be a struct to mimic the proto definition as close as possible.

When we decide to support more hash algorithms, having this a typed byte slice will become awkward because it will mean a API breaking change.

```go
type Digest struct {
    Digest []byte
}
```

Extending a struct with another field is easy, extending a typed basic type is hard.
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 29 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfDI6T9BNWx4DFyv0W:-MTfDI6T9BNWx4DFyv0X:b-e2kb25) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions/digest/digest.go#L29)):*
> ```Go
> type Digest []byte
> 
> const EpicDigestLength = 16
> ```

This is not specific to Epic, this is specific to the hash algorithm used to compute the digest. i.e., sha256

I wonder if it makes sense to add the hash algorithm already to the protobuf definition, just to make this obvious.
We agreed the default will be sha256, but maybe it makes more sense to be explicit in the definitions, and simply only support sha256 for now.

something like:

```proto
message DigestExtension {

    enum Algorithm {
        ALGORITHM_UNSPECIFED = 0;
        ALGORITHM_SHA256 = 1;
    } 

    message Digest {
        // Raw digest of the metadata.
        bytes digest = 1;
        // ....
        Algorithm algorithm = 2;
    }
    // The digest of the detached EPIC extension.
    Digest epic = 1000;
}
```
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 31 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfC2ys4c8OVH8otoKM:-MTfC2ys4c8OVH8otoKN:b-i1jlj0) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions/digest/digest.go#L31)):*
> ```Go
> const EpicDigestLength = 16
> 
> type DigestExtension struct {
> ```

Please, just call this `Extension`, at call sites this will then used as `digest.Extensions which means no stutter.

Otherwise, it is used at call sites as `digest.DigestExtension` which leads to stutter and is redundant.
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 45 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfJ00GDkaSdJwJ4NFS:-MTfJ00GDkaSdJwJ4NFT:buuoxqf) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions/digest/digest.go#L45)):*
> ```Go
> 		}
> 	}
> 	if len(d.Epic.Digest) != EpicDigestLength {
> ```

I don't think this check is necessary, if the length is wrong, it will fail during validation.
And it leads to surprising error cases, i.e., the protobuf has the digest, but the parsed struct does not.
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 46 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfItB-Bpz9rctAshXE:-MTfItB-Bpz9rctAshXF:bjgiuzy) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions/digest/digest.go#L46)):*
> ```Go
> 	}
> 	if len(d.Epic.Digest) != EpicDigestLength {
> 		log.Debug("Epic digest: invalid length")
> ```

Please do not log in libraries, the logger might not even be initialized depending on what application is using this.
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 62 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfKSFl0e1lj5ESTegO:-MTfKSFl0e1lj5ESTegP:bu4r33n) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions/digest/digest.go#L62)):*
> ```Go
> 		return nil
> 	}
> 	if len(d.Epic) != EpicDigestLength {
> ```

Don't do the checks here, simply put in the extension what is in the struct.
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 63 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfKQ6F940buYYZMyrx:-MTfKQ6F940buYYZMyry:b7b0coz) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions/digest/digest.go#L63)):*
> ```Go
> 	}
> 	if len(d.Epic) != EpicDigestLength {
> 		log.Debug("Epic digest: invalid length")
> ```

Please don't log
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 77 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfK_3u2yXjECFl5Auv:-MTfK_3u2yXjECFl5Auw:b1tzhq5) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions/digest/digest.go#L77)):*
> ```Go
> }
> 
> func CalcEpicDigest(ed *epic_detached.EpicDetached) ([]byte, error) {
> ```

I think this should be structured differently.

There should be a general method on `Digest` that computes the digest based on an input.

The Epic extensions should provide a way to calculate the input.

```go

func (d *Digest) Set(input []byte) error {
     b, err := s.calcDigest()
     if err != nil {
          return err
     }
     d.Digest = b
}

func (d *Digest) Validate(input []byte) error {
     b, err := s.calcDigest()
     if err != nil {
          return err
     }
     if !bytes.Equal(b, d.Digest) {
          // return error
     }
     return nil
}

func (d *Digest) calcDigest(input []byte) ([]byte, error) {
     switch d.Algorithm {
     case cppb....SHA256:
          // calculate digest with sha256.Sum and return
   
     default:
          return serrors.New("unsupported digest algorithm", "algo", d.Algorithm)
     }
}

```

To create a digest, you would do:

```go
var e epic.Extension // Initialized with the appropriate values
var d digest.Digest
if err := d.Set(e.DigestInput()); err != nil {
     //handle error
}
// now the digest is set correctly.
```

To verify the digest, you would do:


```go
var e epic.Extension // received from segment
var d digest.Digest // received from segment
if err := d.Validate(e.DigestInput()); err != nil {
     //handle error
}
// digest was correct
```
___
*[go/lib/ctrl/seg/unsigned_extensions/unsigned_extensions.go, line 15 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfPKdI26MONF3t947-:-MTfPKdI26MONF3t9470:bn6dq2e) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/unsigned_extensions/unsigned_ [...]

2021-03-08 17:22 UTC, Oncilla reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3954)* status: all files reviewed, 27 unresolved discussions (waiting on @karampok and @mawyss)



<!-- Sent from Reviewable.io -->

2021-03-10 10:37 UTC, mawyss reviewed
Thank you all for the feedback! Unfortunately I did not have time yet to implement your requests due to the Colibri paper submission. I expect to be able to do so until the end of next week.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3954#-:-MVQhY-212v_rcSmQfwb:b-z5xz2a)* status: all files reviewed, 27 unresolved discussions (waiting on @karampok and @mawyss)



<!-- Sent from Reviewable.io -->

2021-03-11 22:53 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3954)* status: 8 of 29 files reviewed, 23 unresolved discussions (waiting on @karampok and @Oncilla)

___
*[Makefile, line 36 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTenAo76zVP-seP78jD:-MVVCBy30ssiY0fmCx8K:b-jg5ulr) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/Makefile#L36)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

I cannot really tell, what `*/*` is adding exactly.

I can see 
```
[I] kka@kkahost ~/w/scionproto (epic_cp ✖1)> tree -L 2 bazel-bin/go/pkg/proto/
bazel-bin/go/pkg/proto/
├── control_plane
│   ├── experimental
│   ├── go_default_library_
│   ├── go_default_library.a
│   └── go_default_library.x
├── crypto
│   ├── go_default_library_
│   ├── go_default_library.a
│   └── go_default_library.x
├── daemon
│   ├── go_default_library_
│   ├── go_default_library.a
│   └── go_default_library.x
├── discovery
│   ├── go_default_library_
│   ├── go_default_library.a
│   └── go_default_library.x
├── gateway
│   ├── go_default_library_
│   ├── go_default_library.a
│   └── go_default_library.x
└── hidden_segment
    ├── go_default_library_
    ├── go_default_library.a
```
</blockquote></details>

For the folder structure you show here, it would just traverse the control_plane/experimental/go_default_library_/...
The important step happens at the very end of the path: the command copies  the folder...
```
control_plane
    └── experimental
        └── seg_detached_extensions.pb.go
```
... to go/pkg/proto, which is following the same idea as the previous command one line before.
___
*[go/cs/beaconing/extender.go, line 66 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfVVF384eBKEHz_EbW:-MVVMlQ60NOoON7P_7fS:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/cs/beaconing/extender.go#L66)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Please add a way to enable epic here.
By default, epic should be turned off.

So, something like a field `EPIC bool`

Also, please do not add the code to enable this through a config in this PR.
We can do it in a follow up PR, because this PR is already pretty large in size.

The smaller the PR, the faster we can iterate on it.

</blockquote></details>

Done.
___
*[go/cs/beaconing/extender.go, line 112 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTerkFm3DGDxFajm74E:-MVVMzJw-CaB7CXGom4t:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/cs/beaconing/extender.go#L112)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

For readability, this variable can have a sort name (like e )
</blockquote></details>

Done.
___
*[go/cs/beaconing/extender.go, line 117 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTeq-meEFykv5IyeNtw:-MVYAyyjC_vurpmn_M5C:b766lu1) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/cs/beaconing/extender.go#L117)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

This seems to me like it should be a method rather than a function. Any reason why it is like that?
(probably to be similar to something existing)

Also, use full name `CalculateEpicDigest` not `CalcX` or without `Calc` 
Also, if returns Digest, then the `epicHash` should be `epicDigest` (detail)
</blockquote></details>

Ok, this was resolved anyway by replacing it with the functions `Set/Validate/calculateDigest` as suggested by Dominik.
___
*[go/lib/ctrl/seg/as.go, line 52 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTesTK-3X9heSdlpL5W:-MVVSqx44zQlz7cwhJ_n:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/as.go#L52)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

We have agreed that we support unsigned extensions.

I don't think this warrants its own package.

IMO, `UnsignedExtensions` should be a type defined in this package.
i.e., move the definition to `go/lib/ctrl/seg/unsigned_extensions.go`



</blockquote></details>

Done.
___
*[go/lib/ctrl/seg/as.go, line 95 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTeukJH27QEB8DTrony:-MVVXS4j7jrHJZIeLLkG:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/as.go#L95)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I don't think this functionality belongs here at all.

Putting validation logic with parsing logic leads to very convoluted design.
It also means that you cannot parse a malformed segment, which is not always desired.

This validation should be done as a step in `PathSegment.Validate`



</blockquote></details>

Done.
___
*[go/lib/ctrl/seg/as.go, line 115 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTewizg1zUrCia_-Jvb:-MVWqKPs5iWAQq44rUIT:b-z7tbc6) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/as.go#L115)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

It would be nicer to hide this check function inside the UnsignedExtension packet.
And maybe the signature to have only what is really required (`ue.EpicDtached` `e.Digest`)
</blockquote></details>

Done. I moved the function to the (now renamed) `unsigned.go` file.
For the arguments: they are that general on purpose, so that also future digest extensions can be handled there.
___
*[go/lib/ctrl/seg/extensions_test.go, line 26 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfGb8NBzpVDluIUQBf:-MVVZcqI6WIRJWp0o14S:bi0h9ku) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions_test.go#L26)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

What are you trying to test here? Maybe there is a more concise way.
</blockquote></details>

Done. The test is more concise now and captures what I intended to test actually (protobuf encoding and decoding).
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 27 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfCSkZ7ypthBMPYskc:-MVVe9JA2sh2dUztf5uf:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions/digest/digest.go#L27)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I would rather this to be a struct to mimic the proto definition as close as possible.

When we decide to support more hash algorithms, having this a typed byte slice will become awkward because it will mean a API breaking change.

```go
type Digest struct {
    Digest []byte
}
```

Extending a struct with another field is easy, extending a typed basic type is hard.



</blockquote></details>

Done.
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 29 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfDI6T9BNWx4DFyv0W:-MVYDVQr75K67W5VvpEf:b-fj8gt6) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions/digest/digest.go#L29)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

This is not specific to Epic, this is specific to the hash algorithm used to compute the digest. i.e., sha256

I wonder if it makes sense to add the hash algorithm already to the protobuf definition, just to make this obvious.
We agreed the default will be sha256, but maybe it makes more sense to be explicit in the definitions, and simply only support sha256 for now.

something like:

```proto
message DigestExtension  [...]

2021-03-12 07:38 UTC, karampok reviewed
> Reviewed 6 of 27 files at r1, 1 of 2 files at r5, 1 of 1 files at r8, 2 of 11 files at r10, 22 of 22 files at r11.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3954)* status: all files reviewed, 20 unresolved discussions (waiting on @Oncilla)



<!-- Sent from Reviewable.io -->

2021-03-17 09:01 UTC, karampok reviewed
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3954)* status: all files reviewed, 20 unresolved discussions (waiting on @Oncilla)



<!-- Sent from Reviewable.io -->

2021-03-23 14:28 UTC, Oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3954)* status: all files reviewed, 12 unresolved discussions (waiting on @mawyss)

___
*[go/cs/beaconing/extender.go, line 122 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUFg7u2923cvs3-H2M:-MWUFg7u2923cvs3-H2N:b-iig3c2) ([raw file](https://github.com/scionproto/scion/blob/ef59d91b84c26bd379b29c249d70ed57f0c09115/go/cs/beaconing/extender.go#L122)):*
> ```Go
> 
> 		var d digest.Digest
> 		i, err := e.DigestInput()
> ```

We try to avoid using `i`  for variables outside of loop variables.
It is not very descriptive.

In this case, `input` would maybe be more explicit.
___
*[go/lib/ctrl/seg/unsigned.go, line 33 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUH0wM5_ziCuct6tPW:-MWUH0wM5_ziCuct6tPX:bo14acr) ([raw file](https://github.com/scionproto/scion/blob/ef59d91b84c26bd379b29c249d70ed57f0c09115/go/lib/ctrl/seg/unsigned.go#L33)):*
> ```Go
> 		return UnsignedExtensions{}
> 	}
> 	ed := epic.DetachedFromPB(ue.Epic)
> ```

directly initialize the filed here:

```go
return UnsignedExtensions{
    EpicDetached: epic.DetachedFromPB(ue.Epic)
}
```
___
*[go/lib/ctrl/seg/unsigned.go, line 67 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUKvR70AAehtWk68I4:-MWUKvR70AAehtWk68I5:bvbuci4) ([raw file](https://github.com/scionproto/scion/blob/ef59d91b84c26bd379b29c249d70ed57f0c09115/go/lib/ctrl/seg/unsigned.go#L67)):*
> ```Go
> 	// EPIC:
> 	if epicDetached && epicDigest {
> 		i, err := ue.EpicDetached.DigestInput()
> ```

please replace `i` with `input`.
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 29 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfDI6T9BNWx4DFyv0W:-MWULmE9CAy7n7qsEV7a:b49ip5x) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions/digest/digest.go#L29)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

I see the point of making it more explicit, but maybe it would make sense to solve the specification of cryptographic primitives not for each extension, but in a more general way. Last year, we worked on something related to that:

https://github.com/mawyss/scion/blob/1d410a25f3bca0c2d27509a341fc342b6a6580ac/doc/protocols/casa.rst
(CASA - Cryptographic Agility for SCION ASes)

Please let me know whether you think this makes sense, or if you want the algorithm to be part of the Digest protobuf message.
</blockquote></details>

That is an interesting proposal.

But I do not yet fully understand how this would interact with the digest extension here.
Someone/something needs to tell the digest extension what algorithm to use.
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 70 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUO2to70qj4acfC4_h:-MWUO2to70qj4acfC4_i:bep9x7g) ([raw file](https://github.com/scionproto/scion/blob/ef59d91b84c26bd379b29c249d70ed57f0c09115/go/lib/ctrl/seg/extensions/digest/digest.go#L70)):*
> ```Go
> func (d *Digest) Set(input []byte) {
> 	b := calculateDigest(input)
> 	d.Digest = b
> ```

assign directly here `d.Digest = calculateDigest(input)`
___
*[go/lib/ctrl/seg/extensions/digest/digest_test.go, line 39 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUOaso1Dnfca9x21Hx:-MWUOaso1Dnfca9x21Hy:b-z4gk7x) ([raw file](https://github.com/scionproto/scion/blob/ef59d91b84c26bd379b29c249d70ed57f0c09115/go/lib/ctrl/seg/extensions/digest/digest_test.go#L39)):*
> ```Go
> 
> 		var d digest.Digest
> 		i, err := ed.DigestInput()
> ```

s/i/input
___
*[go/pkg/cs/tasks.go, line 213 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUSxzU81O4jGk7Q3-v:-MWUSxzU81O4jGk7Q3-w:b-lw1t42) ([raw file](https://github.com/scionproto/scion/blob/ef59d91b84c26bd379b29c249d70ed57f0c09115/go/pkg/cs/tasks.go#L213)):*
> ```Go
> 		StaticInfo: t.StaticInfo,
> 		Task:       task,
> 		EPIC:       true,
> ```

Please do not set this field as part of this pull request.
This should be configurable via the config file.

The config file changes should be part of a follow-up pull request, as this PR already is of considerable size.
___
*[go/pkg/cs/api/testdata/segments-blob-by-id.txt, line 2 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUTKLR1tQRFkfWvkA3:-MWUTKLR1tQRFkfWvkA4:btp5ilg) ([raw file](https://github.com/scionproto/scion/blob/ef59d91b84c26bd379b29c249d70ed57f0c09115/go/pkg/cs/api/testdata/segments-blob-by-id.txt#L2)):*
> ```vimhelp
> -----BEGIN PATH SEGMENT-----
> CgkI8eCagAYQuQoSMQotCiAKBggDEgJpZBIWCJCCgICA4H8aDAoKEAEiBhERERER
> ```

This is surprising to me. I thought we designed the extensions such that they do not affect
current encoding without epic.

Can you please check why this encoding changed.
___
*[proto/control_plane/v1/seg_extensions.proto, line 133 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTeKLg13EiIW1JkD322:-MWUTjgnBhA0XKsxjiIF:bkh62z3) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/proto/control_plane/v1/seg_extensions.proto#L133)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Drop the added space in the beginning of the comment.
___
*[go/lib/ctrl/seg/extensions/epic/epic.go, line 96 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUQ2EZ1nnl4y-rFjmZ:-MWUQ2EZ1nnl4y-rFjm_:b-sv4b22) ([raw file](https://github.com/scionproto/scion/blob/ef59d91b84c26bd379b29c249d70ed57f0c09115/go/lib/ctrl/seg/extensions/epic/epic.go#L96)):*
> ```Go
> 
> 	if len(ed.AuthHopEntry) != AuthLen {
> 		return nil, serrors.New("authenticator for hop entry has wrong length",
> ```

`"hop entry authenticator of wrong length", "expected", AuthLen, "actual", len(ed.AuthHopEntry)`
___
*[go/lib/ctrl/seg/extensions/epic/epic.go, line 103 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWURvWJ92wnMPZn6sIf:-MWURvWJ92wnMPZn6sIg:b-rqxvo7) ([raw file](https://github.com/scionproto/scion/blob/ef59d91b84c26bd379b29c249d70ed57f0c09115/go/lib/ctrl/seg/extensions/epic/epic.go#L103)):*
> ```Go
> 	for i, peer := range ed.AuthPeerEntries {
> 		if len(peer) != AuthLen {
> 			return nil, serrors.New("authenticator for peer entry has wrong length",
> ```

ditto.
___
*[go/lib/ctrl/seg/extensions/epic/epic.go, line 106 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUSB_h2g0QR6Ptklf3:-MWUSB_h2g0QR6Ptklf4:b-n0fy53) ([raw file](https://github.com/scionproto/scion/blob/ef59d91b84c26bd379b29c249d70ed57f0c09115/go/lib/ctrl/seg/extensions/epic/epic.go#L106)):*
> ```Go
> 				"len(peer)", len(peer))
> 		}
> 		copy(b[12+(i*AuthLen):12+((i+1)*AuthLen)], peer)
> ```

you could make this more readable (and faster) with:

```go
offset := 12
for _, peer := range ed.AuthPeerEntries {
   //...
   copy(b[offset:offset+AuthLen], peer)
   offset += AuthLen
}
```
___
*[go/lib/ctrl/seg/unsigned_extensions/epic_detached/epic_detached.go, line 15 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTexjpFAzvV9i0KPzeZ:-MWUOremAE1-QDLSRVHj:bshz89p) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/unsigned_extensions/epic_detached/epic_detached.go#L15)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Ok, as `epic_detached` only contains the representation, I do not change anything here.
</blockquote></details>

Correct :thumbsup: 


<!-- Sent from Reviewable.io -->

2021-03-25 10:09 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3954)* status: 21 of 28 files reviewed, 12 unresolved discussions (waiting on @karampok and @Oncilla)

___
*[go/cs/beaconing/extender.go, line 122 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUFg7u2923cvs3-H2M:-MWYLzsl-1x0ps2ri1Cm:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a5e1c4b7c0449e42208a2a00e2c29e2eca1abe1a/go/cs/beaconing/extender.go#L122)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

We try to avoid using `i`  for variables outside of loop variables.
It is not very descriptive.

In this case, `input` would maybe be more explicit.


</blockquote></details>

Done.
___
*[go/lib/ctrl/seg/unsigned.go, line 33 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUH0wM5_ziCuct6tPW:-MWYMGJB2Tul_jN6Fp9N:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a5e1c4b7c0449e42208a2a00e2c29e2eca1abe1a/go/lib/ctrl/seg/unsigned.go#L33)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

directly initialize the filed here:

```go
return UnsignedExtensions{
    EpicDetached: epic.DetachedFromPB(ue.Epic)
}
```


</blockquote></details>

Done.
___
*[go/lib/ctrl/seg/unsigned.go, line 67 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUKvR70AAehtWk68I4:-MWYMZe11OH725SuWV0F:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a5e1c4b7c0449e42208a2a00e2c29e2eca1abe1a/go/lib/ctrl/seg/unsigned.go#L67)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

please replace `i` with `input`.
</blockquote></details>

Done.
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 29 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfDI6T9BNWx4DFyv0W:-MWYOwT0CZ3HChgU-lGB:bccmk1o) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions/digest/digest.go#L29)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

That is an interesting proposal.

But I do not yet fully understand how this would interact with the digest extension here.
Someone/something needs to tell the digest extension what algorithm to use.



</blockquote></details>

CASA could be used as follows:
- An AS adding a digest extension would specify  in the CASA extension which hash algorithm it used for detached extensions.
- As I would expect that an AS adds most extensions using the same algorithm, it would specify a _general_ hash algorithm (introduce CASA category: HASH). If there is a detached extension, call it EXT, for which the AS wants to use a different algorithm, it would specify this as a _protocol-specific_ hash algorithm, so there would be a CASA category HASH-EXT.
- An AS that then wants to verify the detached extensions that the other ASes added, can recompute the digest using the hash functions specified in the CASA extension.
___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 70 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUO2to70qj4acfC4_h:-MWYSwV4DJf4xA2kmoEK:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a5e1c4b7c0449e42208a2a00e2c29e2eca1abe1a/go/lib/ctrl/seg/extensions/digest/digest.go#L70)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

assign directly here `d.Digest = calculateDigest(input)`
</blockquote></details>

Done.
___
*[go/lib/ctrl/seg/extensions/digest/digest_test.go, line 39 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUOaso1Dnfca9x21Hx:-MWYTMp06kx6-N6QriQz:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a5e1c4b7c0449e42208a2a00e2c29e2eca1abe1a/go/lib/ctrl/seg/extensions/digest/digest_test.go#L39)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

s/i/input
</blockquote></details>

Done.
___
*[go/pkg/cs/tasks.go, line 213 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUSxzU81O4jGk7Q3-v:-MWYWiD771tBh1IuEPM3:b-aw4ngj) ([raw file](https://github.com/scionproto/scion/blob/a5e1c4b7c0449e42208a2a00e2c29e2eca1abe1a/go/pkg/cs/tasks.go#L213)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Please do not set this field as part of this pull request.
This should be configurable via the config file.

The config file changes should be part of a follow-up pull request, as this PR already is of considerable size.

</blockquote></details>

Done. I did not mean to set this field, I must have forgotten to change it after testing that it works, sorry.
___
*[go/pkg/cs/api/testdata/segments-blob-by-id.txt, line 2 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUTKLR1tQRFkfWvkA3:-MWcpnk9DrzFqiJykWGe:b60qt33) ([raw file](https://github.com/scionproto/scion/blob/a5e1c4b7c0449e42208a2a00e2c29e2eca1abe1a/go/pkg/cs/api/testdata/segments-blob-by-id.txt#L2)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

This is surprising to me. I thought we designed the extensions such that they do not affect
current encoding without epic.

Can you please check why this encoding changed.




</blockquote></details>

Done. The problem was in the function `UnsignedExtensionsToPB` (`unsigned.go`): if the argument was nil, I returned a pointer to an empty struct instead of `nil`.
___
*[proto/control_plane/v1/seg_extensions.proto, line 133 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTeKLg13EiIW1JkD322:-MWYXMpp3hCZuJLVQeH-:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/proto/control_plane/v1/seg_extensions.proto#L133)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Drop the added space in the beginning of the comment.
</blockquote></details>

Done.
___
*[go/lib/ctrl/seg/extensions/epic/epic.go, line 96 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUQ2EZ1nnl4y-rFjmZ:-MWYUjDDCcF21TRJ5gNg:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a5e1c4b7c0449e42208a2a00e2c29e2eca1abe1a/go/lib/ctrl/seg/extensions/epic/epic.go#L96)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

`"hop entry authenticator of wrong length", "expected", AuthLen, "actual", len(ed.AuthHopEntry)`
</blockquote></details>

Done.
___
*[go/lib/ctrl/seg/extensions/epic/epic.go, line 103 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWURvWJ92wnMPZn6sIf:-MWYUk6C6OOiB8QeUzxz:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a5e1c4b7c0449e42208a2a00e2c29e2eca1abe1a/go/lib/ctrl/seg/extensions/epic/epic.go#L103)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[go/lib/ctrl/seg/extensions/epic/epic.go, line 106 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUSB_h2g0QR6Ptklf3:-MWYW4lwB5NtmMEt8j67:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a5e1c4b7c0449e42208a2a00e2c29e2eca1abe1a/go/lib/ctrl/seg/extensions/epic/epic.go#L106)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

you could make this more readable (and faster) with:

```go
offset := 12
for _, peer := range ed.AuthPeerEntries {
   //...
   copy(b[offset:offset+AuthLen], peer)
   offset += AuthLen
}
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-25 12:22 UTC, Oncilla approved these changes
> Reviewed 8 of 8 files at r13.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3954)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mawyss)

___
*[go/lib/ctrl/seg/extensions/digest/digest.go, line 29 at r7](https://reviewable.io/reviews/scionproto/scion/3954#-MTfDI6T9BNWx4DFyv0W:-MWdKE6XAzyLb9nNZ4CS:b-sy7za5) ([raw file](https://github.com/scionproto/scion/blob/659af24cc24b5be630eae25c3512068b6889a904/go/lib/ctrl/seg/extensions/digest/digest.go#L29)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

CASA could be used as follows:
- An AS adding a digest extension would specify  in the CASA extension which hash algorithm it used for detached extensions.
- As I would expect that an AS adds most extensions using the same algorithm, it would specify a _general_ hash algorithm (introduce CASA category: HASH). If there is a detached extension, call it EXT, for which the AS wants to use a different algorithm, it would specify this as a _protocol-specific_ hash algorithm, so there would be a CASA category HASH-EXT.
- An AS that then wants to verify the detached extensions that the other ASes added, can recompute the digest using the hash functions specified in the CASA extension.
</blockquote></details>

I see. I guess we can adapt the code here when we get there.
___
*[go/pkg/cs/tasks.go, line 213 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUSxzU81O4jGk7Q3-v:-MWdJoXv6p4N3Ptj0f39:b-x00vyb) ([raw file](https://github.com/scionproto/scion/blob/a5e1c4b7c0449e42208a2a00e2c29e2eca1abe1a/go/pkg/cs/tasks.go#L213)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Done. I did not mean to set this field, I must have forgotten to change it after testing that it works, sorry.
</blockquote></details>

No worries :thumbsup: 
___
*[go/pkg/cs/api/testdata/segments-blob-by-id.txt, line 2 at r12](https://reviewable.io/reviews/scionproto/scion/3954#-MWUTKLR1tQRFkfWvkA3:-MWdJyHg05OJYJOukF3-:b-purkxa) ([raw file](https://github.com/scionproto/scion/blob/a5e1c4b7c0449e42208a2a00e2c29e2eca1abe1a/go/pkg/cs/api/testdata/segments-blob-by-id.txt#L2)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Done. The problem was in the function `UnsignedExtensionsToPB` (`unsigned.go`): if the argument was nil, I returned a pointer to an empty struct instead of `nil`.
</blockquote></details>

Right. Thanks for looking into this.


<!-- Sent from Reviewable.io -->

2021-03-25 12:22 UTC, Oncilla approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3954#-:-MWdKakv7kchhndRC3Qg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mawyss)



<!-- Sent from Reviewable.io -->

2021-03-25 13:01 UTC, Oncilla commented
/rebase

2021-03-25 13:04 UTC, Oncilla approved these changes
> Reviewed 1 of 24 files at r14, 20 of 23 files at r15.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3954)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mawyss)



<!-- Sent from Reviewable.io -->

2021-03-26 09:52 UTC, closed without merging