doc: add Authenticator End-to-End option
scionproto/scion pull request #4014
Opened 2021-04-09 15:18 UTC by matzf

The Authenticator End-to-End option roughly follows what was previously
described in the SCION book as the "SCION Packet Security Extension". As
the name implies, however, this does not intend to be applicable for
packet encryption -- I think that encrypted packets can be more
appropriately represented by a separate next-header type analogous to IP
Encapsulating Security Payload.

This Authenticator option will be used for authenticated SCMP (to be described in a separate document, see #3969).

[doc]

2021-04-09 15:20 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4014)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @matzf)

___
*[doc/protocols/authenticator-option.rst, line 17 at r1](https://reviewable.io/reviews/scionproto/scion/4014#-MXrCjip8FnXGAntpStS:-MXrCjiq-9fKie9Nwt1x:bxvwy5p) ([raw file](https://github.com/scionproto/scion/blob/2ec29bf03c81d58f8b4059e5800f31b0c419fcb5/doc/protocols/authenticator-option.rst#L17)):*
> ```reStructuredText
> Format of the Authenticator Option
> ==================================
> Alignment requirement: 4n + 1::
> ```

This is a bit awkward as it will require 3 padding bytes if this is the first / only end-to-end option. Better ideas?


<!-- Sent from Reviewable.io -->

2021-05-11 15:54 UTC, shitz requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4014)* status: all files reviewed, 4 unresolved discussions (waiting on @matzf)

___
*[doc/protocols/authenticator-option.rst, line 17 at r1](https://reviewable.io/reviews/scionproto/scion/4014#-MXrCjip8FnXGAntpStS:-M_R6EP43VtBdIgOmrDr:b-uydvb1) ([raw file](https://github.com/scionproto/scion/blob/2ec29bf03c81d58f8b4059e5800f31b0c419fcb5/doc/protocols/authenticator-option.rst#L17)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This is a bit awkward as it will require 3 padding bytes if this is the first / only end-to-end option. Better ideas?
</blockquote></details>

The only other option I see would be 8n+1, however, that still needs 3 bytes of padding and would potentially waste more space if there would be other end-to-end options included.
I don't think aligning to 8 bytes is worth it, so 4n+1 makes sense.
___
*[doc/protocols/authenticator-option.rst, line 4 at r2](https://reviewable.io/reviews/scionproto/scion/4014#-M_R7WZG1FZeH7KVOfA5:-M_R7WZG1FZeH7KVOfA6:b-3n2pb6) ([raw file](https://github.com/scionproto/scion/blob/1353d325b301c35969b517a379b1f39d6bede2ec/doc/protocols/authenticator-option.rst#L4)):*
> ```reStructuredText
> 
> **************************
> SCION Authenticator Option
> ```

Maybe call it `SCION Packet Authenticator Option`
___
*[doc/protocols/authenticator-option.rst, line 10 at r2](https://reviewable.io/reviews/scionproto/scion/4014#-M_R-MDxDhJJEbW4YEMi:-M_R-MDxDhJJEbW4YEMj:b-r2kabb) ([raw file](https://github.com/scionproto/scion/blob/1353d325b301c35969b517a379b1f39d6bede2ec/doc/protocols/authenticator-option.rst#L10)):*
> ```
> i.e.
> ```
i.e.,
___
*[doc/protocols/authenticator-option.rst, line 54 at r2](https://reviewable.io/reviews/scionproto/scion/4014#-M_R6dnJAedfvPt-_B6r:-M_R6dnJAedfvPt-_B6s:b-lwi49n) ([raw file](https://github.com/scionproto/scion/blob/1353d325b301c35969b517a379b1f39d6bede2ec/doc/protocols/authenticator-option.rst#L54)):*
> ```reStructuredText
> ======= ============= ======================================= =============
> 
> .. note:: Only AES-CMAC will be implemented at first, the rest are just defined as placeholders.
> ```

Any specific reasons for the numbering scheme? Do you want to group them by highest digit being set?
___
*[doc/protocols/extension-header.rst, line 101 at r2](https://reviewable.io/reviews/scionproto/scion/4014#-M_R7jivAAUGniYtv28t:-M_R7jivAAUGniYtv28u:b-s6ipwv) ([raw file](https://github.com/scionproto/scion/blob/1353d325b301c35969b517a379b1f39d6bede2ec/doc/protocols/extension-header.rst#L101)):*
> ```
> Authenticator Option
> ```
SCION Packet Authenticator Option


<!-- Sent from Reviewable.io -->

2021-05-12 09:18 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4014)* status: all files reviewed, 4 unresolved discussions (waiting on @matzf and @shitz)

___
*[doc/protocols/authenticator-option.rst, line 4 at r2](https://reviewable.io/reviews/scionproto/scion/4014#-M_R7WZG1FZeH7KVOfA5:-M_UokmM6syIavF6UD-R:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1353d325b301c35969b517a379b1f39d6bede2ec/doc/protocols/authenticator-option.rst#L4)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Maybe call it `SCION Packet Authenticator Option`
</blockquote></details>

Done.
___
*[doc/protocols/authenticator-option.rst, line 10 at r2](https://reviewable.io/reviews/scionproto/scion/4014#-M_R-MDxDhJJEbW4YEMi:-M_UomiN645U3a5qBgS3:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1353d325b301c35969b517a379b1f39d6bede2ec/doc/protocols/authenticator-option.rst#L10)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> i.e.
> ```
i.e.,
</blockquote></details>

Done.
___
*[doc/protocols/authenticator-option.rst, line 54 at r2](https://reviewable.io/reviews/scionproto/scion/4014#-M_R6dnJAedfvPt-_B6r:-M_Uorln2HcqPdQu8oX0:byd88ap) ([raw file](https://github.com/scionproto/scion/blob/1353d325b301c35969b517a379b1f39d6bede2ec/doc/protocols/authenticator-option.rst#L54)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Any specific reasons for the numbering scheme? Do you want to group them by highest digit being set?
</blockquote></details>

No strong reason; my thought was that grouping them losely by "type" and leaving some room in between will allow to add new entries a bit more naturally in the future. If you think that's a bit too arbitrary, we can also just use a simple incrementing number assignment. Or we can leave all of these undefined for now and come back to it once we actually want implement the different algorithms.


<!-- Sent from Reviewable.io -->

2021-05-12 12:55 UTC, shitz requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4014)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[doc/protocols/authenticator-option.rst, line 54 at r2](https://reviewable.io/reviews/scionproto/scion/4014#-M_R6dnJAedfvPt-_B6r:-M_Vd3qLBGAMV-15mjsw:b-rbhqdx) ([raw file](https://github.com/scionproto/scion/blob/1353d325b301c35969b517a379b1f39d6bede2ec/doc/protocols/authenticator-option.rst#L54)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

No strong reason; my thought was that grouping them losely by "type" and leaving some room in between will allow to add new entries a bit more naturally in the future. If you think that's a bit too arbitrary, we can also just use a simple incrementing number assignment. Or we can leave all of these undefined for now and come back to it once we actually want implement the different algorithms.
</blockquote></details>

I would only define CMAC for now.


<!-- Sent from Reviewable.io -->

2021-05-12 13:19 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4014)* status: all files reviewed, 1 unresolved discussion (waiting on @shitz)

___
*[doc/protocols/authenticator-option.rst, line 54 at r2](https://reviewable.io/reviews/scionproto/scion/4014#-M_R6dnJAedfvPt-_B6r:-M_ViqmLE0Cy_0WSEGMD:b14qjgr) ([raw file](https://github.com/scionproto/scion/blob/1353d325b301c35969b517a379b1f39d6bede2ec/doc/protocols/authenticator-option.rst#L54)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

I would only define CMAC for now.
</blockquote></details>

:+1: Done.


<!-- Sent from Reviewable.io -->

2021-05-12 13:20 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4014)* status: all files reviewed, 1 unresolved discussion (waiting on @shitz)

___
*[doc/protocols/extension-header.rst, line 101 at r2](https://reviewable.io/reviews/scionproto/scion/4014#-M_R7jivAAUGniYtv28t:-M_Viy8y-SNs58gmh-_f:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1353d325b301c35969b517a379b1f39d6bede2ec/doc/protocols/extension-header.rst#L101)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> Authenticator Option
> ```
SCION Packet Authenticator Option
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-12 15:36 UTC, shitz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4014#-:-M_WDFX4-X-fNd3ZL5i6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2021-05-14 09:31 UTC, shitz approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4014)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2021-05-17 16:24 UTC, closed without merging