router: reduce per-packet allocations
scionproto/scion pull request #4030
Opened 2021-04-27 15:38 UTC by matzf

Avoid allocating scionPacketProcessor; re-organized packet processing
functions. The scionPacketProcessor is now the main entry point for
packet processing and contains all the pre-allocated per-packet state.

Avoid allocation of message buffer for writing with WriteBatch.
We could just pre-allocate a buffer, but as we always write a batch of
size one, just use WriteTo instead.
For writing single packets, this is both more convenient and faster.
Additional benefit: Read/WriteBatch make rather large allocations
internally (see golang/go#26838) which is
avoided by using WriteTo.

The largest remaining allocations when processing SCION packets are:
- ReadBatch allocates temporary storage internally (as mentioned above).
  This is by far the biggest culprit, it accounts for almost 80% (after
  the changes in this patch).
- slayers/path.NewPath called during slayers.SCION.DecodeFromBytes:
  Could be avoided by reusing Path objects, but requires larger changes.
- slayers/path/scion.Raw.GetCurrentHopField and GetCurrentInfoField, called during parsePath:
  Both return pointer types. Should be possible to change this to value
  types instead, but requires larger changes.
- DataPlane.resolveLocalDst: allocates IP and UDPAddr. Can only really
  be fixed with better address types.
- slayers/path.FullMAC. Allocates both input and output. The function
  interface could be changed to allow reuse of the input buffer.
  The output buffer cannot be reused with this CMAC library.

Depends on (or actually includes) #4029.

2021-05-04 11:04 UTC, lukedirtwalker commented
/rebase

2021-05-04 14:44 UTC, lukedirtwalker requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4030)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[go/pkg/router/dataplane.go, line 80 at r1](https://reviewable.io/reviews/scionproto/scion/4030#-MZroS3wCsSeAzrNUSDO:-MZroS3wCsSeAzrNUSDP:bvshln6) ([raw file](https://github.com/scionproto/scion/blob/84a97eda022090123efccab72202142eafe93fb6/go/pkg/router/dataplane.go#L80)):*
> ```Go
> 	ReadBatch(underlayconn.Messages) (int, error)
> 	WriteTo([]byte, *net.UDPAddr) (int, error)
> 	WriteBatch(underlayconn.Messages) (int, error)
> ```

this no longer seems to be used, please remove and update the mock.
___
*[go/pkg/router/dataplane.go, line 487 at r1](https://reviewable.io/reviews/scionproto/scion/4030#-MZrofc72JM1nb08IDNH:-MZrofc72JM1nb08IDNI:bhb1g65) ([raw file](https://github.com/scionproto/scion/blob/84a97eda022090123efccab72202142eafe93fb6/go/pkg/router/dataplane.go#L487)):*
> ```
> , _
> ```
Please check the cast succeeds and if it doesn't the packet should be discarded. I think this address comes from user input so we can not simply assume that the cast works.


<!-- Sent from Reviewable.io -->

2021-05-04 15:54 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4030)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[go/pkg/router/dataplane.go, line 80 at r1](https://reviewable.io/reviews/scionproto/scion/4030#-MZroS3wCsSeAzrNUSDO:-MZrtyk9AaFknx88mX2F:by1r7bn) ([raw file](https://github.com/scionproto/scion/blob/84a97eda022090123efccab72202142eafe93fb6/go/pkg/router/dataplane.go#L80)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

this no longer seems to be used, please remove and update the mock.
</blockquote></details>

Done. I've not renamed it although the name doesn't seem very apt now. I cannot think of anything that's really better, both "Conn" or "UnderlayConn" would probably be net negative in clarity. The doc string is technically still correct: 'supports "batch reads" and "writes".' :wink: 
___
*[go/pkg/router/dataplane.go, line 487 at r1](https://reviewable.io/reviews/scionproto/scion/4030#-MZrofc72JM1nb08IDNH:-MZrtajQ89PGBDxtOFxp:bienmc8) ([raw file](https://github.com/scionproto/scion/blob/84a97eda022090123efccab72202142eafe93fb6/go/pkg/router/dataplane.go#L487)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> , _
> ```
Please check the cast succeeds and if it doesn't the packet should be discarded. I think this address comes from user input so we can not simply assume that the cast works.
</blockquote></details>

I've checked the different code paths setting this, the address is either nil (uninitialized) or UDPAddr. I've changed this to use a panic-y type assertion to make this expectation explicit.


<!-- Sent from Reviewable.io -->

2021-05-05 08:46 UTC, lukedirtwalker requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4030)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[go/pkg/router/dataplane.go, line 487 at r1](https://reviewable.io/reviews/scionproto/scion/4030#-MZrofc72JM1nb08IDNH:-MZv1zM8-KFPhi-JOFSA:b1qx25q) ([raw file](https://github.com/scionproto/scion/blob/84a97eda022090123efccab72202142eafe93fb6/go/pkg/router/dataplane.go#L487)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I've checked the different code paths setting this, the address is either nil (uninitialized) or UDPAddr. I've changed this to use a panic-y type assertion to make this expectation explicit.
</blockquote></details>

Hm then it would be cleaner to change the type of result.OutAddr, if that isn't too much work.


<!-- Sent from Reviewable.io -->

2021-05-05 11:19 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4030)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[go/pkg/router/dataplane.go, line 487 at r1](https://reviewable.io/reviews/scionproto/scion/4030#-MZrofc72JM1nb08IDNH:-MZwDQFW2lgx7d09YIS4:b-v3254i) ([raw file](https://github.com/scionproto/scion/blob/84a97eda022090123efccab72202142eafe93fb6/go/pkg/router/dataplane.go#L487)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Hm then it would be cleaner to change the type of result.OutAddr, if that isn't too much work.
</blockquote></details>

Done. This goes through quite a few places, now UDPAddr is now ubuquitous. I quite like that, though. I think it makes the previously hidden assumptions more clearly visible.


<!-- Sent from Reviewable.io -->

2021-05-05 12:20 UTC, lukedirtwalker approved these changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4030)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2021-05-06 08:59 UTC, closed without merging