Fix issue 4080
scionproto/scion pull request #4081
Opened 2021-07-04 16:23 UTC by jcp19

Fixes #4080 by introducing a bounds-check in the case for `HostTypeSVC`

2021-07-05 15:41 UTC, oncilla requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4081)* status: all files reviewed, 6 unresolved discussions (waiting on @jcp19)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4081#-MdrFxiL3kXQLXkuootH:-MdrFxiL3kXQLXkuootI:b-2fftke) (no related file):*
Thank you for contributing this fix.

I added some small comments to be more inline with the style we use in our repository.

---
___
*[go/lib/addr/host_test.go, line 2 at r1](https://reviewable.io/reviews/scionproto/scion/4081#-MdrFi6t9CqBwmtKkaey:-MdrFi6t9CqBwmtKkaez:b-itpka4) ([raw file](https://github.com/scionproto/scion/blob/66f493246e185a93425bdc55d05a4a670fd1a898/go/lib/addr/host_test.go#L2)):*
> ```Go
> // Copyright 2016 ETH Zurich
> // Copyright 2020 ETH Zurich, Anapaya Systems
> ```

You can simply put `// Copyright 2021 ETH Zurich, Anapaya Systems` here.
___
*[go/lib/addr/host_test.go, line 16 at r1](https://reviewable.io/reviews/scionproto/scion/4081#-MdrJjqL0hKzZ9wuVPF4:-MdrJjqL0hKzZ9wuVPF5:bm0kojn) ([raw file](https://github.com/scionproto/scion/blob/66f493246e185a93425bdc55d05a4a670fd1a898/go/lib/addr/host_test.go#L16)):*
> ```Go
> // limitations under the License.
> 
> package addr
> ```

For testing, we prefer using the `_test` package. I.e., `addr_test` in this specific case.
This ensures that we are only testing public APIs and not internal details. It also forces us to be a "consumer" of the package that we are exposing.
___
*[go/lib/addr/host_test.go, line 26 at r1](https://reviewable.io/reviews/scionproto/scion/4081#-MdrGDR08OwbrKlaTzlZ:-MdrGDR08OwbrKlaTzl_:bgtqv17) ([raw file](https://github.com/scionproto/scion/blob/66f493246e185a93425bdc55d05a4a670fd1a898/go/lib/addr/host_test.go#L26)):*
> ```Go
> func TestHostFromRaw(t *testing.T) {
> 	var testSlice = []byte{}
> 	var hostAddrTypes = []struct {
> ```

For table driven testing, we use the following pattern in our code base:

```go

testCases := map[string]struct{
    ... // fields for test cases
}{
    "<test-case name>": {
        field: value,
    }
}
for name, tc := range testCases {
    t.Run(name, func(t *testing.T) {
        // do test using tc.
    })
}
```

For this test, this translates to:

```go
func TestHostFromRaw(t *testing.T) {
	testCases := map[string]struct {
		input        []byte
		addrType     addr.HostAddrType
		expected     addr.HostAddr
		errAssertion assert.ErrorAssertionFunc
	}{
		"nil IPv4": {
			addrType:     addr.HostTypeIPv4,
			errAssertion: assert.Error,
		},
		"short IPv4": {
			input:        make([]byte, 3),
			addrType:     addr.HostTypeIPv4,
			errAssertion: assert.Error,
		},
		"valid IPv4": {
			input:        []byte{127, 0, 0, 1},
			addrType:     addr.HostTypeIPv4,
			expected:     addr.HostFromIP(net.IPv4(127, 0, 0, 1)),
			errAssertion: assert.NoError,
		},
		"nil IPv6": {
			addrType:     addr.HostTypeIPv6,
			errAssertion: assert.Error,
		},
		"short IPv6": {
			input:        make([]byte, 14),
			addrType:     addr.HostTypeIPv6,
			errAssertion: assert.Error,
		},
		"valid IPv6": {
			input:        net.ParseIP("dead::beef"),
			addrType:     addr.HostTypeIPv6,
			expected:     addr.HostFromIP(net.ParseIP("dead::beef")),
			errAssertion: assert.NoError,
		},
		// TODO: fill in SVC tests
	}
	for name, tc := range testCases {
		t.Run(name, func(t *testing.T) {
			got, err := addr.HostFromRaw(tc.input, tc.addrType)
			tc.errAssertion(t, err)
			assert.Equal(t, tc.expected, got)
		})
	}
}
```
___
*[go/lib/addr/host_test.go, line 30 at r1](https://reviewable.io/reviews/scionproto/scion/4081#-MdrJKm93KAqeq6adh0Q:-MdrJKm93KAqeq6adh0R:b8bzce1) ([raw file](https://github.com/scionproto/scion/blob/66f493246e185a93425bdc55d05a4a670fd1a898/go/lib/addr/host_test.go#L30)):*
> ```Go
> 		addrType HostAddrType
> 	}{
> 		{"HostTypeIPv4", HostTypeIPv4},
> ```

I think we can even go a bit further and also check the valid cases. See the sample above.
___
*[go/lib/addr/host_test.go, line 35 at r1](https://reviewable.io/reviews/scionproto/scion/4081#-MdrJQ75DfrF3sRjsZ5q:-MdrJQ75DfrF3sRjsZ5r:b-i0ugyv) ([raw file](https://github.com/scionproto/scion/blob/66f493246e185a93425bdc55d05a4a670fd1a898/go/lib/addr/host_test.go#L35)):*
> ```Go
> 	}
> 
> 	t.Log("HostFromRaw should return a non-nil error when the length of the slice argument is less than expected")
> ```

I don't think this log is needed as it does not really provide more information.
The test cases on their own are explicit enough.

If a test fails, one has to check the source here anyway.


<!-- Sent from Reviewable.io -->

2021-07-05 15:42 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4081)* status: all files reviewed, 6 unresolved discussions (waiting on @jcp19)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4081#-MdrFxiL3kXQLXkuootH:-MdrKSQZ2K408OU5wRQZ:bg2e127) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Thank you for contributing this fix.

I added some small comments to be more inline with the style we use in our repository.


</blockquote></details>

Oh, I also adapted the PR description to be a bit more inline with https://scion.docs.anapaya.net/en/latest/contribute/git.html#good-commit-messages

---


<!-- Sent from Reviewable.io -->

2021-07-05 15:45 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4081)* status: all files reviewed, 6 unresolved discussions (waiting on @jcp19)

___
*[go/lib/addr/host_test.go, line 35 at r1](https://reviewable.io/reviews/scionproto/scion/4081#-MdrJQ75DfrF3sRjsZ5q:-MdrL8NA-FdiHqO4D_WG:bphuesw) ([raw file](https://github.com/scionproto/scion/blob/66f493246e185a93425bdc55d05a4a670fd1a898/go/lib/addr/host_test.go#L35)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I don't think this log is needed as it does not really provide more information.
The test cases on their own are explicit enough.

If a test fails, one has to check the source here anyway.

</blockquote></details>

(also, this exceeds our 100 char limit)


<!-- Sent from Reviewable.io -->

2021-07-06 14:11 UTC, jcp19 commented
Thanks @oncilla for your thoughtful feedback. I incorporated your suggestions :)

2021-07-06 14:29 UTC, oncilla approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4081#-:-MdwDDyF2mz2w2GFn7sg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcp19)



<!-- Sent from Reviewable.io -->

2021-07-06 14:31 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4081)* status: all files reviewed, 1 unresolved discussion (waiting on @jcp19)

___
*[go/lib/addr/host_test.go, line 21 at r2](https://reviewable.io/reviews/scionproto/scion/4081#-MdwDKsT2XBpXE25xP9k:-MdwDKsT2XBpXE25xP9l:b-wx1dqk) ([raw file](https://github.com/scionproto/scion/blob/c415d3e82e40e6ddf76d52f15504d3ae1fa2cf73/go/lib/addr/host_test.go#L21)):*
> ```Go
> 	"testing"
> 
> 	"github.com/scionproto/scion/go/lib/addr"
> ```

We group the imports into three groups: std, third-party, local.

As you can see, the linter is also complaining:

```
==================== Test output for //go/lib/addr:go_default_test-impi:
../com_github_pavius_impi/cmd/impi/impi_/impi -scheme stdThirdPartyLocal -local github.com/scionproto/scion go/lib/addr
go/lib/addr/host_test.go: Imports of different types are not allowed in the same group (1): github.com/scionproto/scion/go/lib/addr != github.com/stretchr/testify/assert
 
impi verification failed: Found 1 errors
================================================================================
(14:18:21) INFO: Elapsed time: 19.881s, Critical Path: 1.17s
(14:18:21) INFO: 3293 processes: 1640 remote cache hit, 1644 internal, 5 linux-sandbox, 4 local.
//go/lib/addr:go_default_test-impi                                       FAILED in 0.5s
  bazel-testlogs/go/lib/addr/go_default_test-impi/test.log
```


Please change this to the following, and we are good to merge :thumbsup: 

```
import (
	"net"
	"testing"

	"github.com/stretchr/testify/assert"

	"github.com/scionproto/scion/go/lib/addr"
)
```


<!-- Sent from Reviewable.io -->

2021-07-06 14:38 UTC, jcp19 commented
> > _[Reviewable](https://reviewable.io/reviews/scionproto/scion/4081)_ status: all files reviewed, 1 unresolved discussion (waiting on @jcp19)
> 
> _[go/lib/addr/host_test.go, line 21 at r2](https://reviewable.io/reviews/scionproto/scion/4081#-MdwDKsT2XBpXE25xP9k:-MdwDKsT2XBpXE25xP9l:b-wx1dqk) ([raw file](https://github.com/scionproto/scion/blob/c415d3e82e40e6ddf76d52f15504d3ae1fa2cf73/go/lib/addr/host_test.go#L21)):_
> 
> > ```go
> > 	"testing"
> > 
> > 	"github.com/scionproto/scion/go/lib/addr"
> > ```
> 
> We group the imports into three groups: std, third-party, local.
> 
> As you can see, the linter is also complaining:
> 
> ```
> ==================== Test output for //go/lib/addr:go_default_test-impi:
> ../com_github_pavius_impi/cmd/impi/impi_/impi -scheme stdThirdPartyLocal -local github.com/scionproto/scion go/lib/addr
> go/lib/addr/host_test.go: Imports of different types are not allowed in the same group (1): github.com/scionproto/scion/go/lib/addr != github.com/stretchr/testify/assert
>  
> impi verification failed: Found 1 errors
> ================================================================================
> (14:18:21) INFO: Elapsed time: 19.881s, Critical Path: 1.17s
> (14:18:21) INFO: 3293 processes: 1640 remote cache hit, 1644 internal, 5 linux-sandbox, 4 local.
> //go/lib/addr:go_default_test-impi                                       FAILED in 0.5s
>   bazel-testlogs/go/lib/addr/go_default_test-impi/test.log
> ```
> 
> Please change this to the following, and we are good to merge 👍
> 
> ```
> import (
> 	"net"
> 	"testing"
> 
> 	"github.com/stretchr/testify/assert"
> 
> 	"github.com/scionproto/scion/go/lib/addr"
> )
> ```

Sorry, I missed this, I'm not used to *Reviewable* 😅 Should be fixed now

2021-07-06 14:45 UTC, oncilla approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4081)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcp19)



<!-- Sent from Reviewable.io -->

2021-07-06 14:46 UTC, oncilla approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4081)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcp19)

___
*[go/lib/addr/host_test.go, line 21 at r2](https://reviewable.io/reviews/scionproto/scion/4081#-MdwDKsT2XBpXE25xP9k:-MdwH6GT6H7lfK7hrSeX:b-ggwgg3) ([raw file](https://github.com/scionproto/scion/blob/c415d3e82e40e6ddf76d52f15504d3ae1fa2cf73/go/lib/addr/host_test.go#L21)):*
<details><summary><i>Previously, jcp19 (João Pereira) wrote…</i></summary><blockquote>

Sorry, I missed this, I'm not used to *Reviewable* 😅 Should be fixed now
</blockquote></details>

Thank you for the changes.

The PR will be integrated and open sourced shortly.


<!-- Sent from Reviewable.io -->

2021-07-06 14:47 UTC, oncilla commented
/rebase

2021-07-06 16:28 UTC, closed without merging