DRkey documentation
scionproto/scion pull request #4102
Opened 2021-08-12 07:48 UTC by JordiSubira

This PR contains the updated documentation for DRKey based on the discussion #4039.

2021-08-20 10:10 UTC, mlegner reviewed
Thanks for writing this up. Just finished my review until (excluding) key establishment.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102#-:-MhY1bDM-M7T0rWG3_EO:b-6z331s)* status: 0 of 2 files reviewed, 22 unresolved discussions (waiting on @JordiSubira)

___
*[doc/cryptography/DRKeyInfra.rst, line 15 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXwpat85bslwXRejmj:-MhXwpau72MlRf1q9dFJ:b59gcih) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L15)):*
> ```reStructuredText
> DRKey is used for the following systems:
> 
> - SCMP
> ```

Indirectly through the SPAO.
___
*[doc/cryptography/DRKeyInfra.rst, line 16 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXwrYe6z8ZFoCk8vSS:-MhXwrYe6z8ZFoCk8vST:b-tx3vme) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L16)):*
> ```reStructuredText
> 
> - SCMP
> - SIBRA / COLIBRI
> ```

I suggest removing the name "SIBRA"
___
*[doc/cryptography/DRKeyInfra.rst, line 17 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXwuIM4M0oXhYjeh38:-MhXwuIM4M0oXhYjeh39:b6hri0e) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L17)):*
> ```reStructuredText
> - SCMP
> - SIBRA / COLIBRI
> - Security Extension
> ```

This is now the "SCION Packet Authenticator Option (SPAO)"
___
*[doc/cryptography/DRKeyInfra.rst, line 18 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXwyIkBKKOXUIw6tb8:-MhXwyIkBKKOXUIw6tb9:b-l0ic8c) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L18)):*
> ```reStructuredText
> - SIBRA / COLIBRI
> - Security Extension
> - PISKES
> ```

No longer used.
___
*[doc/cryptography/DRKeyInfra.rst, line 19 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXwzn815qqUJAG1Tux:-MhXwzn815qqUJAG1Tuy:b-l0ic8c) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L19)):*
> ```reStructuredText
> - Security Extension
> - PISKES
> - OPT
> ```

No longer used.
___
*[doc/cryptography/DRKeyInfra.rst, line 31 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXx89P-06zi580ql3S:-MhXx89P-06zi580ql3T:b-cytlvc) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L31)):*
> ```reStructuredText
>     _                     subscript
> 
>     KDF_K (X)             key derivation function using key K and taking X as an input
> ```

Maybe emphasize the difference to the PRF somewhere? Both allow key derivation but they differ in their efficiency.
___
*[doc/cryptography/DRKeyInfra.rst, line 34 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXxZji4ll2xfOL_LV3:-MhXxZji4ll2xfOL_LV4:bbtzt51) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L34)):*
> ```reStructuredText
>     PRF_K (X)             pseudorandom function using key K and taking X as an input
> 
>     A                     autonomous system
> ```

Identified by the pair ISD and AS number?
___
*[doc/cryptography/DRKeyInfra.rst, line 35 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXxdBD4_UoaZU4zQvx:-MhXxdBD4_UoaZU4zQvy:b-pr6umv) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L35)):*
> ```reStructuredText
> 
>     A                     autonomous system
>     H_A                   end host identified by their IP address
> ```

Can also be a different address type.
___
*[doc/cryptography/DRKeyInfra.rst, line 52 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXxqSe75bCD-Opct6P:-MhXxqSe75bCD-Opct6Q:bbzq3zb) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L52)):*
> ```reStructuredText
> =================
> 
> In the DRKey protocol, the key establishment is offloaded to the certificate server
> ```

Maybe "system" would be better than "protocol".

Also, use "service" instead of "server". Not sure what the conventions are for "control service" vs. individual services like certificate service.
___
*[doc/cryptography/DRKeyInfra.rst, line 55 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXy4vP5iqAyGby2yjp:-MhXy4vP5iqAyGby2yjq:b560x98) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L55)):*
> ```reStructuredText
> (CS). The certificate server leverages efficient key derivation and
> pseudorandom functions to derive keys in the hierarchy from top
> to bottom. 
> ```

Nit: trailing whitespaces here and in some other places.
___
*[doc/cryptography/DRKeyInfra.rst, line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXy9ofDt-59rNrEt3u:-MhXy9ofDt-59rNrEt3v:b-d7xov0) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L58)):*
> ```reStructuredText
> 
> The first secret in the hierarchy (``SV_A``) is derived from a long-term ``master_secret``.
> How often the ``master_secret`` must be rotated is up for discussion.
> ```

This is very unclear. Is it up to the individual AS or is there simply no consensus yet?
___
*[doc/cryptography/DRKeyInfra.rst, line 64 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXyIm67XMX5ep_bDb4:-MhXyIm67XMX5ep_bDb5:bwdqzt7) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L64)):*
> ```reStructuredText
> =================
> 
> We define two types of derivation the :ref:`drkey-specific-derivation` derivation and 
> ```

Add a `:`.
___
*[doc/cryptography/DRKeyInfra.rst, line 68 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhY-HSH-lIB5jxr9iz6:-MhY-HSH-lIB5jxr9iz7:bg99fx2) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L68)):*
> ```reStructuredText
> 
> 4-level derivation
> --------------------
> ```

Nit: These should be as long as the heading text (also in other places).
___
*[doc/cryptography/DRKeyInfra.rst, line 75 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhY-VL3DrNRc7361wW3:-MhY-VL3DrNRc7361wW4:b-hxvfn6) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L75)):*
> ```reStructuredText
> 
>    * - Identifier
>      - Derivation
> ```

As the derivation is different depending on the hierarchy type, I suggest describing this separately.
___
*[doc/cryptography/DRKeyInfra.rst, line 81 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhY-2_LA8kTKzyWj1y6:-MhY-2_LA8kTKzyWj1y7:b-r8tdlq) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L81)):*
> ```reStructuredText
>      - Level 0 key, secret value
>    * - ``K_{A->B}``
>      - ``PRF_{SV_A^{proto}}(B)``
> ```

Why is "proto" only included here?
___
*[doc/cryptography/DRKeyInfra.rst, line 87 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhY-5sQA_sAniVm8YLz:-MhY-5sQA_sAniVm8YM-:bmpp4hr) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L87)):*
> ```reStructuredText
>      - Level 2 "to" key, AS-to-host
>    * - ``K_{A:H_A->B}``
>      - ``PRF_{K_{A->B}}(H_A)``
> ```

In the "generic" hierarchy, the second-level derivations also include the `protocol`.
___
*[doc/cryptography/DRKeyInfra.rst, line 99 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXz8eg4uy_hMiiORGi:-MhXz8eg4uy_hMiiORGj:b-sj4aj6)  [...]

2021-08-20 13:49 UTC, matzf reviewed
Thanks for the updated document! I had already started with the review when Markus published his comments; I tried to remove the comments where I said the same thing, sorry if there are still some left -- and sorry that it's so many comments now.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102#-:-MhYY98x1NLZ2d62PxfO:bh24t9e)* status: 0 of 2 files reviewed, 41 unresolved discussions (waiting on @JordiSubira and @mlegner)

___
*[doc/cryptography/DRKeyInfra.rst, line 1 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXzoRU0aoA3RdOgVvY:-MhXzoRU0aoA3RdOgVvZ:b-sablyy) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L1)):*
> ```reStructuredText
> ********************
> ```

Nit, the file name convention for the `.rst` files "kebab case" (lower case, words separated with dashes). Or just shorten it to`drkey.rst`.
___
*[doc/cryptography/DRKeyInfra.rst, line 29 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhY0NapCkaKdhbFHq9D:-MhY0NapCkaKdhbFHq9E:bd65bi8) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L29)):*
> ```reStructuredText
>     |                     bitstring concatenation
>     ^                     superscript
>     _                     subscript
> ```

RST supports math notation, this would improve the readability in this document. 
___
*[doc/cryptography/DRKeyInfra.rst, line 42 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhY0je-0IrhgOIHSVzy:-MhY0je-0IrhgOIHSVzz:b94fjhm) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L42)):*
> ```reStructuredText
> 
> 
> Note that the arrow notation does *not* refer to the communication direction of the key, but
> ```

Nit. The arrow notation has not been introduced at this point. This would make more sense further down, where the keys are actually introduced.
Perhaps this would also be a good place to introduce some terminology for the "from" and "to" sides -- I really dislike these terms as they are utterly confusing in the context of communication. I'd suggest something like "deriving side" and "requesting side", or "fast" and "slow" sides.
In fact, the arrow notation is rather unfortunate too -- maybe we can just chose a different delimiter; simply using a comma would work best I think.
___
*[doc/cryptography/DRKeyInfra.rst, line 110 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhYZ0L45ee3mVFOFqj1:-MhYZ0L45ee3mVFOFqj2:bs84bha) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L110)):*
> ```reStructuredText
> to derive keys on the fly for the specified protocol.
> 
> **1st level key**
> ```

I think using the "alternate" names for these section titles would be clearer, e.g. "AS-to-AS Key", "AS-to-Host Key (Level 2)", "Host-to-AS Key (Level 2)", "Host-To-Host Key (Level 3)". Even though I dislike the "to" terminology, as mentioned above -- perhaps we could just change these names, drop the "to"; "AS--AS", "AS--Host" etc.
___
*[doc/cryptography/DRKeyInfra.rst, line 113 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhYPZ1lAEDX1r1fqVqw:-MhYPZ1lAEDX1r1fqVqx:bruwv3w) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L113)):*
> ```reStructuredText
> 
> These keys are derived locally in the AS_A certificate server (CS_A) and exchanged
> with remote certificate servers (e.g. ``K_{A->B}`` is shared with the CS_B).
> ```

Here and for other keys; who the key is shared with should not be an example, this seems like an important part of the definition.
___
*[doc/cryptography/DRKeyInfra.rst, line 141 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhY-eIs5JDluKjV2vbf:-MhYFYo20d3hU_SX1ig_:bmywjqh) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L141)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Are the levels on the right aligned here? (Sorry, I'm only looking at the source code, not the rendered result.)
</blockquote></details>

Agreed + if we use math notation for the keys, this won't work for this diagram and it will stand out even more. I don't know what would be easiest; maybe some TeX drawing,  or creative use of a table in RST or just embed an image?
This diagram seems important enough to make it readable.
___
*[doc/cryptography/DRKeyInfra.rst, line 166 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhYFisq74qmMKK3OgSu:-MhYFisq74qmMKK3OgSv:beqt5ig) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L166)):*
> ```reStructuredText
>     +-----------------------------------------+
>     |                                         |
>     K_{A:H_A->B}^{protocol}           K_{A->B:H_B}^{protocol}         (2nd level)
> ```

Nit; protocol vs proto used above.
___
*[doc/cryptography/DRKeyInfra.rst, line 172 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhYFo10DCervlbVWe-n:-MhYFo10DCervlbVWe-o:bcr1z2o) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L172)):*
> ```reStructuredText
> The generic-protocol derivation can be thought of as a special case of the 
> protocol-specific derivation for the 0th and 1st level keys. 
> For instance, using a special `proto` value in the protocol-specific scheme, e.g. 0 or "". 
> ```

Either leave this out or clarify that the details of the first two derivation steps are an AS local decision.
___
*[doc/cryptography/DRKeyInfra.rst, line 175 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhY02Js0bATJeWd3KXg:-MhYG2ScAC-ruKch-f2J:b4c3z4w) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L175)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

To be able to use it in the SPAO, a fixed-size value would be preferred.
</blockquote></details>

Agreed + this is not a local decision and this must be specified in this document. I've been assuming we'd use a 16-bit identifier in the SPAO specs.
___
*[doc/cryptography/DRKeyInfra.rst, line 175 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhYQoN30RjXPcPFbW0n:-MhYQoN30RjXPcPFbW0o:b-3prtch) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L175)):*
> ```reStructuredText
> 
> This derivation scheme allows applications to define "niche" protocols. 
> `protocol` is a (variable or fixed size) value identifying this "niche" protocol.
> ```

Somewhere, this document needs to define how the choice is made between the two hierarchies. It should say that,
- the Lvl1 requests for the generic hierarchy work  normally, with the protocol identifier set to `GENERIC = 0`.
- the Lvl2/3 requests always include only the final protocol identifier. The key service chooses the protocol-specific derivation if it exists or the generic derivation otherwise. 
___
*[doc/cryptography/DRKeyInfra.rst, line 190 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhYVFPhA9xZ4lB1H7lN:-MhYVFPhA9xZ4lB1H7lO:b-gvdv9d) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L190)):*
> ```reStructuredText
> 
> Defining a reasonable lower bound for the epoch length used in DRKey to avoid 
> nonsensical scenarios is up for discussion.
> ```

This document should define this now. (There are a few other similar sentences; I think this document should really be a specification, stuff like this should not be left open. If it [...]

2021-08-23 06:46 UTC, mlegner reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: 0 of 2 files reviewed, 41 unresolved discussions (waiting on @JordiSubira, @matzf, and @mlegner)

___
*[doc/cryptography/DRKeyInfra.rst, line 141 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhY-eIs5JDluKjV2vbf:-Mhlk5kvC7OiUZpwmWyY:bx3zxe1) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L141)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Agreed + if we use math notation for the keys, this won't work for this diagram and it will stand out even more. I don't know what would be easiest; maybe some TeX drawing,  or creative use of a table in RST or just embed an image?
This diagram seems important enough to make it readable.
</blockquote></details>

In the SCION book, we currently have this figure, which you could maybe adapt:
```latex
\begin{tikzpicture}[level/.style={level distance=25mm,sibling distance=4cm},scale=.45,edge from parent/.style={draw,-latex}]
	\node (sv){($\sv{A}$)}
	child[sibling distance=8cm] {node (p1) {$\sv{A}^{p}$}
		child {node (1B) {$K_{A\to B}^{p}$}
			child {node (2from) {$K_{A:H_A\to B}^{p}$}
				child {node (3B) {$K_{A:H_A\to B:H_B}^{p}$}}
			}
			child {node (2to) {$K_{A\to B:H_B}^{p}$}}
		}
	}
	child[sibling distance=8cm] { node (ps) {$\sv{A}^{\star}$}
		child {node (1s) {$K_{A\to B}^{\star}$}
			child {node (2spfrom) {$K_{A:H_A\to B}^{\star,p}$}
				child {node (3sp) {$K_{A:H_A\to B:H_B}^{\star,p}$}}
			}
			child {node (2spto) {$K_{A\to B:H_B}^{\star,p}$}}
		}
	}
	;
	\path[font=\small] (8,0)
		+(ps|-ps) node {0th level}
		+(ps|-1s) node {1st level}
		+(ps|-2spto) node {2nd level}
		+(ps|-3sp) node {3rd level};
\end{tikzpicture}
```


<!-- Sent from Reviewable.io -->

2021-08-25 15:11 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: 0 of 3 files reviewed, 36 unresolved discussions (waiting on @JordiSubira, @matzf, and @mlegner)

___
*[doc/cryptography/DRKeyInfra.rst, line 15 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXwpat85bslwXRejmj:-MhxoJg-08GIOXnsqHAD:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L15)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Indirectly through the SPAO.
</blockquote></details>

Done.
___
*[doc/cryptography/DRKeyInfra.rst, line 16 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXwrYe6z8ZFoCk8vSS:-MhxoS8g0Hevyph9-7H2:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L16)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

I suggest removing the name "SIBRA"
</blockquote></details>

Done.
___
*[doc/cryptography/DRKeyInfra.rst, line 17 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXwuIM4M0oXhYjeh38:-MhxoShi5KFCbdjmHz6n:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L17)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

This is now the "SCION Packet Authenticator Option (SPAO)"
</blockquote></details>

Done.
___
*[doc/cryptography/DRKeyInfra.rst, line 18 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXwyIkBKKOXUIw6tb8:-MhxoT-F0ToLzE54ks8M:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L18)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

No longer used.
</blockquote></details>

Done.
___
*[doc/cryptography/DRKeyInfra.rst, line 19 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXwzn815qqUJAG1Tux:-MhxoTwg0j75xe7hxVYO:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L19)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

No longer used.
</blockquote></details>

Done.
___
*[doc/cryptography/DRKeyInfra.rst, line 29 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhY0NapCkaKdhbFHq9D:-MhxpVSM9Md7G06s97iC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L29)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

RST supports math notation, this would improve the readability in this document. 
</blockquote></details>

Done.
___
*[doc/cryptography/DRKeyInfra.rst, line 31 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXx89P-06zi580ql3S:-MhxoVTA-1cGHhIuvMnS:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L31)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Maybe emphasize the difference to the PRF somewhere? Both allow key derivation but they differ in their efficiency.
</blockquote></details>

Done.
___
*[doc/cryptography/DRKeyInfra.rst, line 34 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXxZji4ll2xfOL_LV3:-MhxoVr0EUS7EK-1Ry9p:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L34)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Identified by the pair ISD and AS number?
</blockquote></details>

Done.
___
*[doc/cryptography/DRKeyInfra.rst, line 35 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXxdBD4_UoaZU4zQvx:-MhxoWEJ8IpEcAsLTydK:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L35)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Can also be a different address type.
</blockquote></details>

Done.
___
*[doc/cryptography/DRKeyInfra.rst, line 52 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXxqSe75bCD-Opct6P:-MhxoX-EE7mfyr99vJbx:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L52)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Maybe "system" would be better than "protocol".

Also, use "service" instead of "server". Not sure what the conventions are for "control service" vs. individual services like certificate service.
</blockquote></details>

Done.
___
*[doc/cryptography/DRKeyInfra.rst, line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXy9ofDt-59rNrEt3u:-MhxoXpr2J7AxwtiHZ_1:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L58)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

This is very unclear. Is it up to the individual AS or is there simply no consensus yet?
</blockquote></details>

Done.
___
*[doc/cryptography/DRKeyInfra.rst, line 64 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXyIm67XMX5ep_bDb4:-MhxoYOE8ou6tfxQj5P6:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L64)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Add a `:`.
</blockquote></details>

Done.
___
*[doc/cryptography/DRKeyInfra.rst, line 75 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhY-VL3DrNRc7361wW3:-Mhxp4W42f-HPOj8BE0f:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L75)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

As the derivation is different depending on the hierarchy type, I suggest describing this separately.
</blockquote></details>

Done.
___
*[doc/cryptography/DRKeyInfra.rst, line 81 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhY-2_LA8kTKzyWj1y6:-MhxoyjYBjt-zzsGAEXY:b-h1fuvo) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L81)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Why is "proto" only included here?
</blockquote></details>

Now, it should be more clear.
___
*[doc/cryptography/DRKeyInfra.rst, line 87 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhY-5sQA_sAniVm8YLz:-Mhxp2jWC-SLP2fe9197:b-v0v7fm) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L87)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

In the "generic" hierarchy, the second-level derivations also include the `protocol`.
</blockquote></details>

Now, it should be more clear.
___
*[doc/cryptography/DRKeyInfra.rst, line 99 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXz8eg4uy_hMiiORGi:-MhxoZhz5twdhievusZo:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L99)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

How does it include it? Ideally, this would be added in the table above.
</blockquote></details>

Done.
___
*[doc/cryptography/DRKeyInfra.rst, line 100 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhXzBcy-RcNF8aI4H0k: [...]

2021-08-30 11:53 UTC, fstreun reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: 1 of 3 files reviewed, 18 unresolved discussions (waiting on @JordiSubira and @matzf)

___
*[doc/cryptography/drkey.rst, line 78 at r2](https://reviewable.io/reviews/scionproto/scion/4102#-MiLqmIWDPCHlQv3j_F_:-MiLqmIWDPCHlQv3j_Fa:brvc2f1) ([raw file](https://github.com/scionproto/scion/blob/ebe93fdd192d747128947cd5821b5623f9fd3ba0/doc/cryptography/drkey.rst#L78)):*
> ```reStructuredText
> :math:`CS_B`.
> 
> **AS-host (Level 2)**
> ```

I think this is supposed to be host-AS?
___
*[doc/cryptography/drkey.rst, line 86 at r2](https://reviewable.io/reviews/scionproto/scion/4102#-MiLr7fVBECJWdrNiRVw:-MiLr7fVBECJWdrNiRVx:bo9u1n1) ([raw file](https://github.com/scionproto/scion/blob/ebe93fdd192d747128947cd5821b5623f9fd3ba0/doc/cryptography/drkey.rst#L86)):*
> ```reStructuredText
> infrastructure.
> 
> **host-AS (Level 2)**
> ```

and this is supposed to be AS-host?


<!-- Sent from Reviewable.io -->

2021-08-30 13:57 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: 1 of 3 files reviewed, 18 unresolved discussions (waiting on @fstreun, @JordiSubira, and @matzf)

___
*[doc/cryptography/drkey.rst, line 78 at r2](https://reviewable.io/reviews/scionproto/scion/4102#-MiLqmIWDPCHlQv3j_F_:-MiML7pB7HbG1nf5otWn:b-yce1vq) ([raw file](https://github.com/scionproto/scion/blob/ebe93fdd192d747128947cd5821b5623f9fd3ba0/doc/cryptography/drkey.rst#L78)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

I think this is supposed to be host-AS?
</blockquote></details>

Indeed, my bad. Thank you for pointing that out.
___
*[doc/cryptography/drkey.rst, line 86 at r2](https://reviewable.io/reviews/scionproto/scion/4102#-MiLr7fVBECJWdrNiRVw:-MiMLKJa3U8l1LFz1xI-:b-89a4l7) ([raw file](https://github.com/scionproto/scion/blob/ebe93fdd192d747128947cd5821b5623f9fd3ba0/doc/cryptography/drkey.rst#L86)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

and this is supposed to be AS-host?
</blockquote></details>

Ditto


<!-- Sent from Reviewable.io -->

2021-09-08 07:49 UTC, matzf reviewed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: all files reviewed, 4 unresolved discussions (waiting on @fstreun and @JordiSubira)

___
*[doc/cryptography/drkey.rst, line 31 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj3KYxCBiMYqHA8dNFc:-Mj3KYxCBiMYqHA8dNFd:b7b5bub) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L31)):*
> ```reStructuredText
>      - key derivation function using key K and taking X as an input
>    * - :math:`PRF_K (X)`
>      - pseudorandom function using key K and taking X as an input
> ```

The choice of this PRF should be specified somewhere (as AES-CBC MAC). A related detail that's not currently defined is the exact, byte-for-byte, input format to the PRF (width of the type and protocol fields, representation of ISD-AS and address type/length). Perhaps add an additional subsection to "Derivation scheme" where we specify these details for the relevant derivation steps.
___
*[doc/cryptography/drkey.rst, line 48 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj3MJHf8kR0PrIueeus:-Mj3MJHf8kR0PrIueeut:b-c0x8w7) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L48)):*
> ```reStructuredText
> (CS). The certificate service leverages efficient key derivation and
> pseudorandom functions to derive keys in the hierarchy from top
> to bottom.
> ```

Nit, maybe combine this with "Overview"? 

Also, I think this section could introduce the ideas of exchanging of top-level keys and local derivation of the key hierarchy -- it's all defined below, but we can mention it in this introduction.
___
*[doc/cryptography/DRKeyInfra.rst, line 175 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhYQoN30RjXPcPFbW0n:-Mj3H4vq4gQHtBY1QTS_:b-8fx2u7) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L175)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I included it within the exchange sections, let me know what you think.
</blockquote></details>

:+1: 
___
*[doc/cryptography/DRKeyInfra.rst, line 251 at r1](https://reviewable.io/reviews/scionproto/scion/4102#-MhYmn-I-nMlDNwnpspH:-Mj3JNPr1hSVvcGNCqQd:b-8fx2u7) ([raw file](https://github.com/scionproto/scion/blob/803dfaf5aa78f84b98eef89234a195696955eb26/doc/cryptography/DRKeyInfra.rst#L251)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I also thought about that and I agree that if we consider the prefetcher as part of the specification (before it wasn't) we can use specify this expected behavior. Even, for the implementation I'd say that we can consider even not implementing this "spreading" mechanism at the moment. The prefetcher will be implemented as a periodic.Runner and I guess we could assume that different Runners (for different ASes)   start at different time, i.e. they will request Lvl1 keys also at different points in time.
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2021-09-08 13:14 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: all files reviewed, 5 unresolved discussions (waiting on @fstreun and @JordiSubira)

___
*[doc/cryptography/drkey.rst, line 1 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj4XdbFDth0uh6Ec0sY:-Mj4XdbFDth0uh6Ec0sZ:bpy7y6y) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L1)):*
> ```reStructuredText
> **************************************************
> ```

Note that after renaming the file, you need to update the corresponding entry in cryptography/index.rst


<!-- Sent from Reviewable.io -->

2021-09-08 13:57 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: all files reviewed, 5 unresolved discussions (waiting on @fstreun, @JordiSubira, and @matzf)

___
*[doc/cryptography/drkey.rst, line 31 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj3KYxCBiMYqHA8dNFc:-Mj4ancp-sTOjcEPfIVV:b-k5pixy) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L31)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The choice of this PRF should be specified somewhere (as AES-CBC MAC). A related detail that's not currently defined is the exact, byte-for-byte, input format to the PRF (width of the type and protocol fields, representation of ISD-AS and address type/length). Perhaps add an additional subsection to "Derivation scheme" where we specify these details for the relevant derivation steps.
</blockquote></details>

I  can add the section, no problem. However we should also include the choice for the KDF and "byte-for-byte" input format for it, shouldn't we? 

Related to that, do you (or anyone else in the discussion) have a strong opinion about prepending the master secret length? I inherited this input format and I am not sure about its purpose. PBKDF2 internally applies HMAC that does seem resistant to length extension attacks [1] (if that was the idea behind it).

[1] https://cseweb.ucsd.edu/~mihir/papers/kmd5.pdf


<!-- Sent from Reviewable.io -->

2021-09-08 16:07 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: all files reviewed, 5 unresolved discussions (waiting on @fstreun, @JordiSubira, and @matzf)

___
*[doc/cryptography/drkey.rst, line 31 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj3KYxCBiMYqHA8dNFc:-Mj58JZQDchLeOMHoZVx:bm60um1) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L31)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I  can add the section, no problem. However we should also include the choice for the KDF and "byte-for-byte" input format for it, shouldn't we? 

Related to that, do you (or anyone else in the discussion) have a strong opinion about prepending the master secret length? I inherited this input format and I am not sure about its purpose. PBKDF2 internally applies HMAC that does seem resistant to length extension attacks [1] (if that was the idea behind it).

[1] https://cseweb.ucsd.edu/~mihir/papers/kmd5.pdf
</blockquote></details>

Revisiting the message format we have defined (host are variable-size strings at the moment) I guess if we want to use CBC MAC ( which is a "good" PRF under fixed length input space) we should fix the size for the host field (I do not know if that could be a problem). Maybe I am missing something in my reasoning... 


<!-- Sent from Reviewable.io -->

2021-09-08 19:23 UTC, marcfrei commented
___
*[doc/cryptography/drkey.rst, line 121 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5r7J25IBXy6BGdYTz:-Mj5r7J25IBXy6BGdYU-:b-nbajkb) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L121)):*
> ```reStructuredText
>    * - :math:`K_{A:H_A,B}^{protocol}`
>      - :math:`PRF_{K_{A,B}^{protocol}}(type||H_A)`
>      - host-AS (Level 2)
> ```

`host-AS key (Level 2)`?


<!-- Sent from Reviewable.io -->

2021-09-08 19:24 UTC, marcfrei commented
___
*[doc/cryptography/drkey.rst, line 124 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5rOOB368cfjEq9gvI:-Mj5rOOCCjP_IAQC2fG7:b-4u8cxs) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L124)):*
> ```reStructuredText
>    * - :math:`K_{A:H_A,B:H_B}^{protocol}`
>      - :math:`PRF_{K_{A:H_A,B}^{protocol}}(type||H_B)`
>      - host-host (Level 3)
> ```

`host-host key (Level 3)`?


<!-- Sent from Reviewable.io -->

2021-09-08 19:25 UTC, marcfrei commented
___
*[doc/cryptography/drkey.rst, line 165 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5ri7hEIv15VSNesNE:-Mj5ri7hEIv15VSNesNF:b-ceyaq3) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L165)):*
> ```reStructuredText
>    * - :math:`K_{A:H_A,B}^{protocol}`
>      - :math:`PRF_{K_{A,B}}(protocol||type||H_A)`
>      - host-AS (Level 2)
> ```

`host-AS key (Level 2)`?


<!-- Sent from Reviewable.io -->

2021-09-08 19:25 UTC, marcfrei commented
___
*[doc/cryptography/drkey.rst, line 168 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5rpYB7sj4URkFNOjH:-Mj5rpYB7sj4URkFNOjI:btrqbuy) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L168)):*
> ```reStructuredText
>    * - :math:`K_{A:H_A,B:H_B}^{protocol}`
>      - :math:`PRF_{K_{A:H_A,B}^{protocol}}(type||H_B)`
>      - host-host (Level 3)
> ```

` host-host key (Level 3)`?


<!-- Sent from Reviewable.io -->

2021-09-08 19:29 UTC, marcfrei commented
___
*[doc/cryptography/drkey.rst, line 182 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5sZPD6XM4e1F_efdL:-Mj5sZPD6XM4e1F_efdM:b-f79tyx) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L182)):*
> ```reStructuredText
> must not overlap. Thus, a secret value is associated with exactly one epoch.
> 
> In the design, every AS can define different epoch lengths for each
> ```

Remove the prefix `In the design, `?


<!-- Sent from Reviewable.io -->

2021-09-08 19:36 UTC, marcfrei commented
___
*[doc/cryptography/drkey.rst, line 241 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5u7tuCN_yGz1Hc7Nb:-Mj5u7tuCN_yGz1Hc7Nc:b-aixhi) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L241)):*
> ```reStructuredText
> 
> Even though Level 0/2/3 key exchange happens within the same AS (i.e. intra-AS communication),
> the protocol should establish a secure channel. This would avoid that unintended hosts in the
> ```

Remove  `unintended`?


<!-- Sent from Reviewable.io -->

2021-09-08 19:37 UTC, marcfrei commented
___
*[doc/cryptography/drkey.rst, line 242 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5uYf34EFuGzmYwPpi:-Mj5uYf42ZzsbIAwMaAO:bufg2gp) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L242)):*
> ```reStructuredText
> Even though Level 0/2/3 key exchange happens within the same AS (i.e. intra-AS communication),
> the protocol should establish a secure channel. This would avoid that unintended hosts in the
> AS can eavesdrop on symmetric keys that are not intended to them.
> ```

"intended for"


<!-- Sent from Reviewable.io -->

2021-09-08 19:39 UTC, marcfrei commented
___
*[doc/cryptography/drkey.rst, line 237 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5uyCn9H5pRqtra0qK:-Mj5uyCn9H5pRqtra0qL:b-fimy18) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L237)):*
> ```reStructuredText
> the `generic-protocol` hierarchy or to the protocol number for the `protocol-specific` derivation.
> 
> Level 0/2/3 level key establishment
> ```

Remove the second "level".


<!-- Sent from Reviewable.io -->

2021-09-08 19:47 UTC, marcfrei commented
___
*[doc/cryptography/drkey.rst, line 320 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5vz5NBUSp1oB2PUjM:-Mj5vz5NBUSp1oB2PUjN:bbemwva) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L320)):*
> ```reStructuredText
>       Protocol protocol_id = 1;
>       // Point in time where requested DRKey is valid.
>       Timestamp val_time = 2;
> ```

Use the same order for the fields `protocol_id` and `val_time` as in the other request types?

Plus use everywhere the same comment to describe the same type of field. 


<!-- Sent from Reviewable.io -->

2021-09-08 19:48 UTC, marcfrei commented
___
*[doc/cryptography/drkey.rst, line 331 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5x1F-6CDDUeaYI6X1:-Mj5x1F-6CDDUeaYI6X2:b-8ouh6s) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L331)):*
> ```reStructuredText
>     }
> 
>     message Lvl2Response{
> ```

Use the same order of fields as in the other response types?


<!-- Sent from Reviewable.io -->

2021-09-08 19:49 UTC, marcfrei reviewed
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: all files reviewed, 15 unresolved discussions (waiting on @fstreun, @JordiSubira, and @matzf)



<!-- Sent from Reviewable.io -->

2021-09-08 19:51 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: all files reviewed, 15 unresolved discussions (waiting on @fstreun and @JordiSubira)

___
*[doc/cryptography/drkey.rst, line 31 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj3KYxCBiMYqHA8dNFc:-Mj5wLTE3mvQHhFc7Lr_:b-e63dr8) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L31)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Revisiting the message format we have defined (host are variable-size strings at the moment) I guess if we want to use CBC MAC ( which is a "good" PRF under fixed length input space) we should fix the size for the host field (I do not know if that could be a problem). Maybe I am missing something in my reasoning... 
</blockquote></details>

The KDF is not as critical as it is a local decision and does not need to be standardized. We can still suggest something though, I guess.

For CBC-MAC it's enough to include the length of the address field (probably best in the form of the length/type field as in the scion address header) in the first block, before the address.


<!-- Sent from Reviewable.io -->

2021-09-13 08:37 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: all files reviewed, 14 unresolved discussions (waiting on @fstreun, @marcfrei, and @matzf)

___
*[doc/cryptography/drkey.rst, line 1 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj4XdbFDth0uh6Ec0sY:-MjTHxyICtabLwOoJRGZ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L1)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Note that after renaming the file, you need to update the corresponding entry in cryptography/index.rst
</blockquote></details>

Done.
___
*[doc/cryptography/drkey.rst, line 31 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj3KYxCBiMYqHA8dNFc:-MjTI-s48cn_AZos72T1:b-8fx2u7) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L31)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The KDF is not as critical as it is a local decision and does not need to be standardized. We can still suggest something though, I guess.

For CBC-MAC it's enough to include the length of the address field (probably best in the form of the length/type field as in the scion address header) in the first block, before the address.
</blockquote></details>

:+1: 
___
*[doc/cryptography/drkey.rst, line 121 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5r7J25IBXy6BGdYTz:-MjTI7FT2pmfY3m_yyq8:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L121)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

`host-AS key (Level 2)`?
</blockquote></details>

Done.
___
*[doc/cryptography/drkey.rst, line 124 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5rOOB368cfjEq9gvI:-MjTI7la8dFSvOYrMMK7:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L124)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

`host-host key (Level 3)`?
</blockquote></details>

Done.
___
*[doc/cryptography/drkey.rst, line 165 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5ri7hEIv15VSNesNE:-MjTI8BZ-jcdMq9H-kb_:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L165)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

`host-AS key (Level 2)`?
</blockquote></details>

Done.
___
*[doc/cryptography/drkey.rst, line 168 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5rpYB7sj4URkFNOjH:-MjTI8_LDv7vOv6734bO:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L168)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

` host-host key (Level 3)`?
</blockquote></details>

Done.
___
*[doc/cryptography/drkey.rst, line 182 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5sZPD6XM4e1F_efdL:-MjTI97g6M6eZtgj8vhe:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L182)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Remove the prefix `In the design, `?
</blockquote></details>

Done.
___
*[doc/cryptography/drkey.rst, line 237 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5uyCn9H5pRqtra0qK:-MjTI9oS45QSXZjxk_UO:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L237)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Remove the second "level".
</blockquote></details>

Done.
___
*[doc/cryptography/drkey.rst, line 241 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5u7tuCN_yGz1Hc7Nb:-MjTIAZ96tHRgKX_WHTa:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L241)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Remove  `unintended`?
</blockquote></details>

Done.
___
*[doc/cryptography/drkey.rst, line 242 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5uYf34EFuGzmYwPpi:-MjTIAtX32-IwWSjQeAo:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L242)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

"intended for"
</blockquote></details>

Done.
___
*[doc/cryptography/drkey.rst, line 320 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5vz5NBUSp1oB2PUjM:-MjTICqo2cbuy-YTnIPi:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L320)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Use the same order for the fields `protocol_id` and `val_time` as in the other request types?

Plus use everywhere the same comment to describe the same type of field. 

</blockquote></details>

Done.
___
*[doc/cryptography/drkey.rst, line 331 at r4](https://reviewable.io/reviews/scionproto/scion/4102#-Mj5x1F-6CDDUeaYI6X1:-MjTIDArC4eHmqEiIi1-:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/dcf000d27f4a3b388f77495f1471026dd231d477/doc/cryptography/drkey.rst#L331)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Use the same order of fields as in the other response types?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-14 07:36 UTC, matzf reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102#-:-MjYE0JD6qSoMIgVrEjc:b-uwkowd)* status: all files reviewed, 13 unresolved discussions (waiting on @fstreun, @JordiSubira, and @marcfrei)

___
*[doc/cryptography/drkey.rst, line 204 at r5](https://reviewable.io/reviews/scionproto/scion/4102#-MjYCf2Y66csXCuKm5Vo:-MjYCf2ZCVwGCRL1sY_J:b-n4eqsv) ([raw file](https://github.com/scionproto/scion/blob/bc2eadd7a165ebe29007b49d77eb34baf5f1b7a4/doc/cryptography/drkey.rst#L204)):*
> ```reStructuredText
> 
> The derivation using CBC MAC is safe since all fields are of a fixed size,
> expect for the host address whose length is prepended.
> ```

Nit, typo `expect` -> `except`


<!-- Sent from Reviewable.io -->

2021-09-14 07:47 UTC, matzf reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: all files reviewed, 12 unresolved discussions (waiting on @fstreun and @marcfrei)



<!-- Sent from Reviewable.io -->

2021-11-11 15:09 UTC, oncilla requested changes
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira)

___
*[doc/cryptography/drkey.rst, line 19 at r6](https://reviewable.io/reviews/scionproto/scion/4102#-MoEVvT7EsZC5-yHUlX6:-MoEVvT8APRAQHdLxtBv:b8x6tk4) ([raw file](https://github.com/scionproto/scion/blob/74dce40660ec163cf3c406872e37e82762bf397b/doc/cryptography/drkey.rst#L19)):*
> ```reStructuredText
> - EPIC
> 
> In the DRKey system, the key establishment is offloaded to the certificate service
> ```

the certificate service does not exist anymore.
Replace this with `SCION Control Service`

(please also update the rest of this document in this regard.)
___
*[doc/cryptography/drkey.rst, line 351 at r6](https://reviewable.io/reviews/scionproto/scion/4102#-MoEXkb86e25KujsK7lS:-MoEXkb86e25KujsK7lT:bgfptxt) ([raw file](https://github.com/scionproto/scion/blob/74dce40660ec163cf3c406872e37e82762bf397b/doc/cryptography/drkey.rst#L351)):*
> ```reStructuredText
> 
>     // DRKeyLvl2Request encompasses 2nd and 3rd level key requests
>     message Lvl2Request{
> ```

Why do we pack the 2nd and 3rd level key requests in the same message?
I would separate them, such that they can evolve independently over time.


<!-- Sent from Reviewable.io -->

2021-11-11 15:09 UTC, oncilla reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2021-11-15 11:24 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @matzf and @oncilla)

___
*[doc/cryptography/drkey.rst, line 19 at r6](https://reviewable.io/reviews/scionproto/scion/4102#-MoEVvT7EsZC5-yHUlX6:-MoYG0tWA0FhuYQOFQdj:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74dce40660ec163cf3c406872e37e82762bf397b/doc/cryptography/drkey.rst#L19)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

the certificate service does not exist anymore.
Replace this with `SCION Control Service`

(please also update the rest of this document in this regard.)

</blockquote></details>

Done.
___
*[doc/cryptography/drkey.rst, line 351 at r6](https://reviewable.io/reviews/scionproto/scion/4102#-MoEXkb86e25KujsK7lS:-MoYG1yg6lqCbiiPl9gW:b-51lqxe) ([raw file](https://github.com/scionproto/scion/blob/74dce40660ec163cf3c406872e37e82762bf397b/doc/cryptography/drkey.rst#L351)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Why do we pack the 2nd and 3rd level key requests in the same message?
I would separate them, such that they can evolve independently over time.



</blockquote></details>

I'd rather change the naming for the keys, i.e. using "end-host keys" instead of Lvl2 and Lvl3, since both are keys that the end-host will request to the CS. The information within the request is what distinguishes between the three possible cases (AS-HOST, HOST-AS, HOST-HOST). In other words, Lvl3 key is another name for the HOST-HOST key. In case we really want to create a different message definition, I guess it would make more sense to have three, one for each case, rather than one for Lvl2 and Lvl3.


<!-- Sent from Reviewable.io -->

2021-11-15 12:20 UTC, oncilla requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @JordiSubira, @matzf, and @oncilla)

___
*[doc/cryptography/drkey.rst, line 351 at r6](https://reviewable.io/reviews/scionproto/scion/4102#-MoEXkb86e25KujsK7lS:-MoYXH2pB3FDnMwsFCMf:b-x4fw6x) ([raw file](https://github.com/scionproto/scion/blob/74dce40660ec163cf3c406872e37e82762bf397b/doc/cryptography/drkey.rst#L351)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I'd rather change the naming for the keys, i.e. using "end-host keys" instead of Lvl2 and Lvl3, since both are keys that the end-host will request to the CS. The information within the request is what distinguishes between the three possible cases (AS-HOST, HOST-AS, HOST-HOST). In other words, Lvl3 key is another name for the HOST-HOST key. In case we really want to create a different message definition, I guess it would make more sense to have three, one for each case, rather than one for Lvl2 and Lvl3.
</blockquote></details>

Yes, let's do this then. One request and one response per "end-host key". 
I prefer being explicit in the type we want, rather then derive it implicitly from the fields that are set in the request.


<!-- Sent from Reviewable.io -->

2021-11-16 09:37 UTC, JordiSubira reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102#-:-Moc5luJ7GJASKhkXfyd:bnfp4nl)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @matzf and @oncilla)

___
*[doc/cryptography/drkey.rst, line 351 at r6](https://reviewable.io/reviews/scionproto/scion/4102#-MoEXkb86e25KujsK7lS:-Moc5U-fDBGVrZh1zGAj:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74dce40660ec163cf3c406872e37e82762bf397b/doc/cryptography/drkey.rst#L351)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Yes, let's do this then. One request and one response per "end-host key". 
I prefer being explicit in the type we want, rather then derive it implicitly from the fields that are set in the request.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-16 12:30 UTC, oncilla reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)



<!-- Sent from Reviewable.io -->

2021-11-17 15:48 UTC, oncilla approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102#-:-Moi_SKG1dgB46Gd2TlQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @JordiSubira)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4102#-Moi_UDqB4FYo8fkx_xO:-Moi_UDqB4FYo8fkx_xP:b-p0hqif) (no related file):*
Thank you for the contribution.
This will be merged in the next open sourcing run.

---


<!-- Sent from Reviewable.io -->

2021-11-17 15:51 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4102)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4102#-Moi_UDqB4FYo8fkx_xO:-Moia1fS05970v3V2VSs:b-n9d8g2) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Thank you for the contribution.
This will be merged in the next open sourcing run.
</blockquote></details>

Brilliant, thank you!

---


<!-- Sent from Reviewable.io -->

2021-11-18 07:05 UTC, closed without merging