disp: add correct SCION next header for SCMP response
scionproto/scion pull request #4125
Opened 2021-11-06 08:40 UTC by mawyss

While the SCION dispatcher correctly parses SCMP packets that include extensions (e.g., SCION / HBH / SCMP), it sends back invalid responses, i.e., SCION / SCMP with the SCION next header field still set to the value corresponding to the extension header.
This PR explicitly sets the SCION next header field to the value corresponding to SCMP.

2021-11-11 17:51 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4125)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mawyss and @oncilla)

___
*[go/dispatcher/dispatcher/underlay.go, line 307 at r1](https://reviewable.io/reviews/scionproto/scion/4125#-MoF6fAbCJYzQIutL_dz:-MoF6fAbCJYzQIutL_e-:bocvhx3) ([raw file](https://github.com/scionproto/scion/blob/bcbc01b855d29b4eed16082f888511213c235fb7/go/dispatcher/dispatcher/underlay.go#L307)):*
> ```Go
> 		return nil, err
> 	}
> 	pkt.SCION.NextHdr = common.L4SCMP
> ```

I presume that this PR is in response to some error you saw while trying to make some HBH/E2E extension to work, otherwise this would already be SCMP here.

For the thing that you are working on, is it actually the correct behavior to drop the extensions without reversing them?


<!-- Sent from Reviewable.io -->

2021-11-11 17:51 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4125)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mawyss and @oncilla)

___
*[go/dispatcher/dispatcher/underlay.go, line 307 at r1](https://reviewable.io/reviews/scionproto/scion/4125#-MoF6fAbCJYzQIutL_dz:-MoF7-GQAEkaZ8GjN2cJ:b-4ley7y) ([raw file](https://github.com/scionproto/scion/blob/bcbc01b855d29b4eed16082f888511213c235fb7/go/dispatcher/dispatcher/underlay.go#L307)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I presume that this PR is in response to some error you saw while trying to make some HBH/E2E extension to work, otherwise this would already be SCMP here.

For the thing that you are working on, is it actually the correct behavior to drop the extensions without reversing them?


</blockquote></details>

If not, reverseSCION would need to be extended to reverse the extensions correctly.


<!-- Sent from Reviewable.io -->

2021-11-12 10:02 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4125)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @oncilla)

___
*[go/dispatcher/dispatcher/underlay.go, line 307 at r1](https://reviewable.io/reviews/scionproto/scion/4125#-MoF6fAbCJYzQIutL_dz:-MoIXAF64QXUQraSHfEx:bu5we8t) ([raw file](https://github.com/scionproto/scion/blob/bcbc01b855d29b4eed16082f888511213c235fb7/go/dispatcher/dispatcher/underlay.go#L307)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

If not, reverseSCION would need to be extended to reverse the extensions correctly.
</blockquote></details>

Yes exactly, I encountered this problem when trying to use a HBH extension in combination with scion ping.
For the HBH extension that I defined it is okay if it gets removed.


<!-- Sent from Reviewable.io -->

2021-11-12 10:47 UTC, oncilla requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4125)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @mawyss)

___
*[go/dispatcher/dispatcher/underlay.go, line 307 at r1](https://reviewable.io/reviews/scionproto/scion/4125#-MoF6fAbCJYzQIutL_dz:-MoIjgcxAN6zwSFFi8SR:b-yjkcvd) ([raw file](https://github.com/scionproto/scion/blob/bcbc01b855d29b4eed16082f888511213c235fb7/go/dispatcher/dispatcher/underlay.go#L307)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Yes exactly, I encountered this problem when trying to use a HBH extension in combination with scion ping.
For the HBH extension that I defined it is okay if it gets removed.
</blockquote></details>

Okay.

Please add the following comment:

```go
// XXX(roosd): This does not take HBH and E2E extensions into consideration.
// See: https://github.com/scionproto/scion/issues/4128
pkt.SCION.NextHdr = common.L4SCMP
```


<!-- Sent from Reviewable.io -->

2021-11-12 11:01 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4125)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @oncilla)

___
*[go/dispatcher/dispatcher/underlay.go, line 307 at r1](https://reviewable.io/reviews/scionproto/scion/4125#-MoF6fAbCJYzQIutL_dz:-MoIncYu3JB-x2ekZVK5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bcbc01b855d29b4eed16082f888511213c235fb7/go/dispatcher/dispatcher/underlay.go#L307)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Okay.

Please add the following comment:

```go
// XXX(roosd): This does not take HBH and E2E extensions into consideration.
// See: https://github.com/scionproto/scion/issues/4128
pkt.SCION.NextHdr = common.L4SCMP
```




</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-12 11:40 UTC, oncilla approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4125#-:-MoIwbikEavT2hIHBDSt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4125#-MoIweVN9lmVQmr6LkgH:-MoIweVN9lmVQmr6LkgI:b-ywl7aq) (no related file):*
Thank you for the contribution :tada:. This will be included in our next open sourcing run.

---


<!-- Sent from Reviewable.io -->

2021-11-12 11:41 UTC, oncilla approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4125)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mawyss)



<!-- Sent from Reviewable.io -->

2021-11-18 07:05 UTC, closed without merging