tools/build/doc: remove building from scion.sh topology
scionproto/scion pull request #4141
Opened 2022-01-19 10:44 UTC by matzf

The command `scion.sh topology` and `run` have automatically invoked a
build. The `scion.sh topology` command  has so featured in the setup
documentation as the one command to build everything. This has led to
various very confused questions from newcommers to the project.
At the same time, I have not found that building automatically in these
commands is helpful for my workflow.

tools/build:

Remove the build steps from `scion.sh topology` and `scion.sh run`.
At the same time, remove various broken/unnecessary/useless subcommands
from scion.sh.
Add make targets to build `scion-pki` and the docker images, for running
the docker-composed based local topology.
Move lint steps from `scion.sh` to a separate script `tools/lint`.
The idea is that scion.sh is responsible really only for the machinery
related to running a local topology. All the build related steps should
be in the Makefile -- we still  `bazel_remote` subcommand left which
doesn't fit the pattern, and this could also be cleaned up later.

ci:

Adapt a small number of CI pipeline steps to explicitly perform a build
before invoking `scion.sh topology`

doc:

Adapt the setup documentation to the changes above, i.e. split building
from running.

Split the information about running a local topology into a separate
subsection. Add a step describing how to use the `--sciond` parameter
for e.g. `scion showpaths` (another frequent question from newcommers).
To simplify the description and usage of this, a new subcommand
`sciond-addr` was added to `scion.sh`.

Add a subsection to describe building with go build. This fits in
relatively cleanly now, as the `scion.sh topology` script does not
overwrite everything by attempting to build with bazel.

2022-01-25 09:57 UTC, lukedirtwalker requested changes
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4141)* status: all files reviewed, 6 unresolved discussions (waiting on @matzf)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/scionproto/scion/4141#-MuFc4Ny5bjqxcU-6RFz):*
what are those questions?
___
*[-- commits, line 9 at r2](https://reviewable.io/reviews/scionproto/scion/4141#-MuFc6P34gGctKB8kdTq):*
why is that so?
We have wasted a lot of time by running outdated binaries that's why we included the build commands there.
___
*[Makefile, line 34 at r2](https://reviewable.io/reviews/scionproto/scion/4141#-MuFaG3b9I5CJ44Y2LN-:-MuFaG3b9I5CJ44Y2LN0:b-6w1jpl) ([raw file](https://github.com/scionproto/scion/blob/88cb3d935f561d80d5dbc97b064a5d15a298c4f9/Makefile#L34)):*
> ```Makefile
> docker-images:
> 	@echo "Build perapp images"
> 	bazel run -c opt //docker:prod
> ```

is that actually needed for Go only code? I think you can drop it.



_Code quote:_
```Makefile
-c opt
```
___
*[scion.sh, line 41 at r2](https://reviewable.io/reviews/scionproto/scion/4141#-MuFaYRZ0dmdpzEc01JF:-MuFaYRZ0dmdpzEc01JG:b-tazivf) ([raw file](https://github.com/scionproto/scion/blob/88cb3d935f561d80d5dbc97b064a5d15a298c4f9/scion.sh#L41)):*
> ```Shell
> 
> cmd_topodot() {
> 		./tools/topodot.py "$@"
> ```

4 spaces instead of 2 tabs
___
*[scion.sh, line 48 at r2](https://reviewable.io/reviews/scionproto/scion/4141#-MuFaeg07B-Sh8Dyq25v:-MuFaeg07B-Sh8Dyq25w:bxysna5) ([raw file](https://github.com/scionproto/scion/blob/88cb3d935f561d80d5dbc97b064a5d15a298c4f9/scion.sh#L48)):*
> ```Shell
>     echo "Running the network..."
>     if is_docker_be; then
>         docker-compose -f gen/scion-dc.yml -p scion up --build -d
> ```

I don't think this is needed at all.



_Code quote:_
```Shell
--build
```
___
*[doc/build/setup.rst, line 82 at r2](https://reviewable.io/reviews/scionproto/scion/4141#-MuFbnwICZePhID0ciJE:-MuFbnwICZePhID0ciJF:b4jr0jb) ([raw file](https://github.com/scionproto/scion/blob/88cb3d935f561d80d5dbc97b064a5d15a298c4f9/doc/build/setup.rst#L82)):*
> ```reStructuredText
> Alternatively to building with bazel, the SCION services and tools can be built
> with ``go build``.
> Please be aware that **this is not the recommended setup for development**.
> ```

if it's not recommended why do we even mention it then?


<!-- Sent from Reviewable.io -->

2022-01-25 11:37 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4141)* status: all files reviewed, 6 unresolved discussions (waiting on @lukedirtwalker)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/scionproto/scion/4141#-MuFc4Ny5bjqxcU-6RFz):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

what are those questions?
</blockquote></details>

The emphasis is on confusion, so not easy to give an example. Also, search is broken in the instant messenger that we use... :wink: Some people seemingly did not realize that `scion.sh topology` both runs the build  _and_ creates configuration. The documentation currently only mentions that it creates the config, and so when these people ran into build or setup problems of any sort, they would just be too confused to make any sense of it.

I expect that when seeing an instruction to run `make`, people have a reasonable expectation of what they are about to do and know that errors happening here must be related to their setup of the build tools (and not SCION itself) and so can help themselves better.
___
*[-- commits, line 9 at r2](https://reviewable.io/reviews/scionproto/scion/4141#-MuFc6P34gGctKB8kdTq):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

why is that so?
We have wasted a lot of time by running outdated binaries that's why we included the build commands there.
</blockquote></details>

Two reasons; 
- because it only helps when starting up a deployment from scratch. What I seem to do much more frequently is to have a running setup and restart bits and pieces after modifications, e.g. only restart the routers. For this, I manually need to build anyway.
- when iterating with restarting from scratch, I usually need to run multiple commands anyway, e.g. to stop, collect results, clean up logs, start again etc. Usually, I end up repeating the same bash line consisting of multiple commands. For this, inserting a `make && ...` or similar seems to make little to no difference.
___
*[Makefile, line 34 at r2](https://reviewable.io/reviews/scionproto/scion/4141#-MuFaG3b9I5CJ44Y2LN-:-MuFtSoc5ov_-xzlNGzv:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/88cb3d935f561d80d5dbc97b064a5d15a298c4f9/Makefile#L34)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

is that actually needed for Go only code? I think you can drop it.
</blockquote></details>

Done.
___
*[scion.sh, line 41 at r2](https://reviewable.io/reviews/scionproto/scion/4141#-MuFaYRZ0dmdpzEc01JF:-MuFs8bR6VoHYmw2sEf0:beeyab8) ([raw file](https://github.com/scionproto/scion/blob/88cb3d935f561d80d5dbc97b064a5d15a298c4f9/scion.sh#L41)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

4 spaces instead of 2 tabs
</blockquote></details>

Gah sorry, fixed.
___
*[scion.sh, line 48 at r2](https://reviewable.io/reviews/scionproto/scion/4141#-MuFaeg07B-Sh8Dyq25v:-MuFn5dh6eHA-yHOmss5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/88cb3d935f561d80d5dbc97b064a5d15a298c4f9/scion.sh#L48)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I don't think this is needed at all.
</blockquote></details>

Done.
___
*[doc/build/setup.rst, line 82 at r2](https://reviewable.io/reviews/scionproto/scion/4141#-MuFbnwICZePhID0ciJE:-MuFlMza0B1Oi8kUZoVK:bbfctey) ([raw file](https://github.com/scionproto/scion/blob/88cb3d935f561d80d5dbc97b064a5d15a298c4f9/doc/build/setup.rst#L82)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

if it's not recommended why do we even mention it then?
</blockquote></details>

It's not recommended _for development_. It's useful to have instructions on how to build SCION binaries with a comparably low entry bar, as a sort of "build from sources" installation instructions. Clearly, setting the entire development environment for just for building the binaries once is overkill.


<!-- Sent from Reviewable.io -->

2022-01-25 11:46 UTC, lukedirtwalker requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4141)* status: all files reviewed, 6 unresolved discussions (waiting on @lukedirtwalker and @matzf)

___
*[Makefile, line 34 at r2](https://reviewable.io/reviews/scionproto/scion/4141#-MuFaG3b9I5CJ44Y2LN-:-MuG2gJ1E_61jraQd4Vy:b-ij7n7w) ([raw file](https://github.com/scionproto/scion/blob/88cb3d935f561d80d5dbc97b064a5d15a298c4f9/Makefile#L34)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not pushed?


<!-- Sent from Reviewable.io -->

2022-01-25 12:05 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4141)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @lukedirtwalker)

___
*[Makefile, line 34 at r2](https://reviewable.io/reviews/scionproto/scion/4141#-MuFaG3b9I5CJ44Y2LN-:-MuG72x60xh4Z4ltMrcn:b-ozn2h) ([raw file](https://github.com/scionproto/scion/blob/88cb3d935f561d80d5dbc97b064a5d15a298c4f9/Makefile#L34)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

not pushed?
</blockquote></details>

Yep, sorry!


<!-- Sent from Reviewable.io -->

2022-01-25 14:21 UTC, lukedirtwalker approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4141)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2022-02-11 11:48 UTC, lukedirtwalker approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4141)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2022-03-10 15:45 UTC, closed without merging