Update SPAO extension header
scionproto/scion pull request #4190
Opened 2022-05-05 11:22 UTC by JordiSubira

This PR updates the SCION Packet Authenticator Option (a.k.a SPAO) to be compliant with the current specification (https://scion.docs.anapaya.net/en/latest/protocols/authenticator-option.html).

2022-05-10 15:05 UTC, marcfrei reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190#-:-N1iVI28BNABFn_2KE86:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira)

___
*[`pkg/slayers/extn.go` line 476 at r1](https://reviewable.io/reviews/scionproto/scion/4190#-N1iUas_6XQQ587l69Yq:-N1iUasaDaSSjKzPxS7s:b-h3y6di) ([raw file](https://github.com/scionproto/scion/blob/4170fc9cad13422da65ec6c9746ce57a827bd3dc/pkg/slayers/extn.go#L476)):*
> ```Go
> 
> // ParsePacketAuthenticatorOption parses o as a packet authenticator option.
> // Performs minimal checks to ensure that SPI, Algorithm, timestamp, RSV, and
> ```

"algorithm" instead of "Algorithm"
___
*[`pkg/slayers/extn.go` line 495 at r1](https://reviewable.io/reviews/scionproto/scion/4190#-N1iTS6U27yktuTqQ3Z0:-N1iTS6U27yktuTqQ3Z1:ba2gras) ([raw file](https://github.com/scionproto/scion/blob/4170fc9cad13422da65ec6c9746ce57a827bd3dc/pkg/slayers/extn.go#L495)):*
> ```Go
> // Reuses the OptData buffer if it is of sufficient capacity.
> func (o PacketAuthenticatorOption) Reset(spi uint32, alg PacketAuthAlg,
> 	ts uint32, sn uint32, auth []byte) {
> ```

Check that `ts` and `sn` are both 24-bit values (instead of just ignoring the higher order bits)? 


<!-- Sent from Reviewable.io -->

2022-05-11 08:29 UTC, matzf reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190#-:-N1mC37B2X6IL110pCgf:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @JordiSubira)

___
*[`pkg/slayers/extn.go` line 523 at r1](https://reviewable.io/reviews/scionproto/scion/4190#-N1mCEis2wq4i3aEbC2n:-N1mCEit16r_HZwjslzy:b-j8msow) ([raw file](https://github.com/scionproto/scion/blob/4170fc9cad13422da65ec6c9746ce57a827bd3dc/pkg/slayers/extn.go#L523)):*
> ```Go
> // SPI returns a slice of the underlying SPI buffer.
> // Changes to this slice will be reflected on the wire when
> // the extension is serialized.
> ```

Wrong comment (not a slice). Same for Timestamp and Sequence number. E.g.

`// SPI returns the Security Parameter Index stored in the data buffer.`
___
*[`pkg/slayers/extn.go` line 524 at r1](https://reviewable.io/reviews/scionproto/scion/4190#-N1mDnQj76cTkEcUGkb9:-N1mDnQj76cTkEcUGkbA:bbtcpt) ([raw file](https://github.com/scionproto/scion/blob/4170fc9cad13422da65ec6c9746ce57a827bd3dc/pkg/slayers/extn.go#L524)):*
> ```Go
> // Changes to this slice will be reflected on the wire when
> // the extension is serialized.
> func (o PacketAuthenticatorOption) SPI() uint32 {
> ```

Parsing the SPI for usage with DRKey would perhaps also fit into this package.

We could add a `type PacketAuthSPI uint32` with methods `IsDRKey`, `DrkeyProto` etc. and a `func MakePacketAuthSPIDrkey(proto, ...) PacketAuthSPI`.


<!-- Sent from Reviewable.io -->

2022-05-12 13:41 UTC, marcfrei reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @JordiSubira, @marcfrei, and @matzf)

___
*[`pkg/slayers/extn.go` line 495 at r1](https://reviewable.io/reviews/scionproto/scion/4190#-N1iTS6U27yktuTqQ3Z0:-N1sUS0x8IHuPbHUIwNi:b-mb4w9j) ([raw file](https://github.com/scionproto/scion/blob/4170fc9cad13422da65ec6c9746ce57a827bd3dc/pkg/slayers/extn.go#L495)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Ah, sorry, I was not specific enough. Since these are really preconditions, I would simply panic instead of returning an error:
```
f ts > (1 << 24) {
    panic("timestamp must not be larger than 2^24")
}
```
and
```
if sn > (1 << 24) {
    panic("sequence number must not be larger than 2^24")
}
```

</blockquote></details>

And the correct condition is as follows, right?
```
if ts > 1<<24 - 1 {
    panic("Timestamp must be smaller than 2^24")
}
```
Same for `sn`.


<!-- Sent from Reviewable.io -->

2022-05-12 13:52 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @marcfrei and @matzf)

___
*[`pkg/slayers/extn.go` line 495 at r1](https://reviewable.io/reviews/scionproto/scion/4190#-N1iTS6U27yktuTqQ3Z0:-N1sXXIZ3T2v58Ru7B2Y:bves986) ([raw file](https://github.com/scionproto/scion/blob/4170fc9cad13422da65ec6c9746ce57a827bd3dc/pkg/slayers/extn.go#L495)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

And the correct condition is as follows, right?
```
if ts > 1<<24 - 1 {
    panic("Timestamp must be smaller than 2^24")
}
```
Same for `sn`.
</blockquote></details>

Good catch! Fixed.


<!-- Sent from Reviewable.io -->

2022-05-12 13:54 UTC, marcfrei reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2022-05-27 10:38 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @marcfrei)

___
*[`pkg/slayers/extn.go` line 524 at r1](https://reviewable.io/reviews/scionproto/scion/4190#-N1mDnQj76cTkEcUGkb9:-N3453UEDGcyRuUIGRJV:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4170fc9cad13422da65ec6c9746ce57a827bd3dc/pkg/slayers/extn.go#L524)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Ok. This `SPI()` method should now return a `PacketAuthSPI`, right?

>  what's your idea to verify it is indeed a DRKey-type SPI

Yes. The specification of the SPAO allows to non-DRKey use; values >= 2^21 are non-DRKey.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-18 12:44 UTC, marcfrei reviewed
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190)* status: all files reviewed, 7 unresolved discussions (waiting on @JordiSubira)

___
*[`pkg/slayers/extn.go` line 453 at r5](https://reviewable.io/reviews/scionproto/scion/4190#-N7GJmaXEc_EmEy-vul-:-N7GJmaXEc_EmEy-vul0:b-c8dhqj) ([raw file](https://github.com/scionproto/scion/blob/d44de131ebf87a6c6d61edfbea56b36e815ef450/pkg/slayers/extn.go#L453)):*
> ```Go
> // packet authentication option. DRKey values are in the
> // range [1, 2^21-1].
> type PacketAuthSPI uint32
> ```

The following types and constants have pretty generic names within the slayers package. Maybe we should prefix them with, e.g., `PacketAuth` -- I'm not sure, though.
___
*[`pkg/slayers/extn.go` line 491 at r5](https://reviewable.io/reviews/scionproto/scion/4190#-N7GI7kE7PmgqK8wL3le:-N7GI7kE7PmgqK8wL3lf:bjtx2js) ([raw file](https://github.com/scionproto/scion/blob/d44de131ebf87a6c6d61edfbea56b36e815ef450/pkg/slayers/extn.go#L491)):*
> ```Go
> 
> func (p PacketAuthSPI) Epoch() DRKeyEpochType {
> 	if p^(1<<14) == 0 {
> ```

(1<<15)?
___
*[`pkg/slayers/extn.go` line 506 at r5](https://reviewable.io/reviews/scionproto/scion/4190#-N7GJ4DrBRu53Z2drUAb:-N7GJ4DrBRu53Z2drUAc:bapljbk) ([raw file](https://github.com/scionproto/scion/blob/d44de131ebf87a6c6d61edfbea56b36e815ef450/pkg/slayers/extn.go#L506)):*
> ```Go
> 
> func MakePacketAuthSPIDrkey(proto uint16, drkeyType DRKeyType,
> 	dir DRKeyDirection, epoch DRKeyEpochType) (PacketAuthSPI, error) {
> ```

No need to return an error here, see below
___
*[`pkg/slayers/extn.go` line 508 at r5](https://reviewable.io/reviews/scionproto/scion/4190#-N7GIiWEDLJ02_UR3hRA:-N7GIiWFCa-wrfQFXxyI:b-ze1zch) ([raw file](https://github.com/scionproto/scion/blob/d44de131ebf87a6c6d61edfbea56b36e815ef450/pkg/slayers/extn.go#L508)):*
> ```Go
> 	dir DRKeyDirection, epoch DRKeyEpochType) (PacketAuthSPI, error) {
> 	if proto < 1 {
> 		return 0, serrors.New("Invalid proto identifier value")
> ```

should panic here instead of returning an error
___
*[`pkg/slayers/extn.go` line 511 at r5](https://reviewable.io/reviews/scionproto/scion/4190#-N7GIq4HBkrzurTrTCcS:-N7GIq4HBkrzurTrTCcT:b-ze1zch) ([raw file](https://github.com/scionproto/scion/blob/d44de131ebf87a6c6d61edfbea56b36e815ef450/pkg/slayers/extn.go#L511)):*
> ```Go
> 	}
> 	if drkeyType > 1 {
> 		return 0, serrors.New("Invalid DRKeyType value")
> ```

should panic here instead of returning an error
___
*[`pkg/slayers/extn.go` line 514 at r5](https://reviewable.io/reviews/scionproto/scion/4190#-N7GIqog7UsC1RoVHLn9:-N7GIqog7UsC1RoVHLnA:b-ze1zch) ([raw file](https://github.com/scionproto/scion/blob/d44de131ebf87a6c6d61edfbea56b36e815ef450/pkg/slayers/extn.go#L514)):*
> ```Go
> 	}
> 	if dir > 1 {
> 		return 0, serrors.New("Invalid DRKeyDirection value")
> ```

should panic here instead of returning an error
___
*[`pkg/slayers/extn.go` line 517 at r5](https://reviewable.io/reviews/scionproto/scion/4190#-N7GIr_uAsymC1JJilwc:-N7GIr_uAsymC1JJilwd:b-ze1zch) ([raw file](https://github.com/scionproto/scion/blob/d44de131ebf87a6c6d61edfbea56b36e815ef450/pkg/slayers/extn.go#L517)):*
> ```Go
> 	}
> 	if epoch > 1 {
> 		return 0, serrors.New("Invalid DRKeyEpochType value")
> ```

should panic here instead of returning an error


<!-- Sent from Reviewable.io -->

2022-07-18 15:54 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @marcfrei)

___
*[`pkg/slayers/extn.go` line 453 at r5](https://reviewable.io/reviews/scionproto/scion/4190#-N7GJmaXEc_EmEy-vul-:-N7H-tJw0GTGV9VD2UW6:b-hq474u) ([raw file](https://github.com/scionproto/scion/blob/d44de131ebf87a6c6d61edfbea56b36e815ef450/pkg/slayers/extn.go#L453)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

The following types and constants have pretty generic names within the slayers package. Maybe we should prefix them with, e.g., `PacketAuth` -- I'm not sure, though.
</blockquote></details>

I decided to use `PacketAuthenticator` prefix, to be consistent to the already define `PacketAuthenticatorOption`. 
___
*[`pkg/slayers/extn.go` line 491 at r5](https://reviewable.io/reviews/scionproto/scion/4190#-N7GI7kE7PmgqK8wL3le:-N7H-zzW0MFxDGL_2TiR:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d44de131ebf87a6c6d61edfbea56b36e815ef450/pkg/slayers/extn.go#L491)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

(1<<15)?
</blockquote></details>

Done.
___
*[`pkg/slayers/extn.go` line 506 at r5](https://reviewable.io/reviews/scionproto/scion/4190#-N7GJ4DrBRu53Z2drUAb:-N7H00hb-6edEt2zCqf0:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d44de131ebf87a6c6d61edfbea56b36e815ef450/pkg/slayers/extn.go#L506)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

No need to return an error here, see below
</blockquote></details>

Done.
___
*[`pkg/slayers/extn.go` line 508 at r5](https://reviewable.io/reviews/scionproto/scion/4190#-N7GIiWEDLJ02_UR3hRA:-N7H016-2WR6XnH34F4W:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d44de131ebf87a6c6d61edfbea56b36e815ef450/pkg/slayers/extn.go#L508)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

should panic here instead of returning an error
</blockquote></details>

Done.
___
*[`pkg/slayers/extn.go` line 511 at r5](https://reviewable.io/reviews/scionproto/scion/4190#-N7GIq4HBkrzurTrTCcS:-N7H01QHCprrGIzZfaL4:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d44de131ebf87a6c6d61edfbea56b36e815ef450/pkg/slayers/extn.go#L511)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

should panic here instead of returning an error
</blockquote></details>

Done.
___
*[`pkg/slayers/extn.go` line 514 at r5](https://reviewable.io/reviews/scionproto/scion/4190#-N7GIqog7UsC1RoVHLn9:-N7H023W2y9pKQDvmWvz:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d44de131ebf87a6c6d61edfbea56b36e815ef450/pkg/slayers/extn.go#L514)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

should panic here instead of returning an error
</blockquote></details>

Done.
___
*[`pkg/slayers/extn.go` line 517 at r5](https://reviewable.io/reviews/scionproto/scion/4190#-N7GIr_uAsymC1JJilwc:-N7H02JI2qxa00NcS7dF:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d44de131ebf87a6c6d61edfbea56b36e815ef450/pkg/slayers/extn.go#L517)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

should panic here instead of returning an error
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-19 13:18 UTC, marcfrei reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190#-:-N7LaqL_0XalFrb557RT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

___
*[`pkg/slayers/extn.go` line 453 at r5](https://reviewable.io/reviews/scionproto/scion/4190#-N7GJmaXEc_EmEy-vul-:-N7L_MM6-ycdeNaKQsrr:b-nvjym4) ([raw file](https://github.com/scionproto/scion/blob/d44de131ebf87a6c6d61edfbea56b36e815ef450/pkg/slayers/extn.go#L453)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I decided to use `PacketAuthenticator` prefix, to be consistent to the already define `PacketAuthenticatorOption`. 
</blockquote></details>

I'm wondering whether we should prefix the constants as well, not only the types. Disadvantage would be that all the names get so long. 


<!-- Sent from Reviewable.io -->

2022-07-19 17:27 UTC, marcfrei reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190#-:-N7MUuXoENC8P5fWXKIJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2022-07-19 21:04 UTC, JordiSubira reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190#-:-N7NGZoC9YXeBm6l-Z3-:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2022-07-19 21:04 UTC, JordiSubira reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2022-08-24 18:28 UTC, shitz requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190)* status: all files reviewed, 10 unresolved discussions (waiting on @JordiSubira)

___
*[`pkg/slayers/extn.go` line 450 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG1fPR7ZfxFi4g26dD:-NAG1fPR7ZfxFi4g26dE:br2gzj9) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L450)):*
> ```Go
> }
> 
> // PacketAuthSPI is the identifier for the key used for the
> ```

This file is getting too large. Please move all the SPAO related entities to a file `pkt_auth.go`.

Also please add a comment at the top of the file that this is the implementation of the SPAO and link to the documentation
___
*[`pkg/slayers/extn.go` line 450 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG3AGJ6qbrbpOoAazy:-NAG3AGKAekCmQFo-pNq:undefined) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L450)):*
> ```Go
> }
> 
> // PacketAuthSPI is the identifier for the key used for the
> ```





_Suggestion:_
```Go
PacketAuthSPI (Security Parameter Index)
```
___
*[`pkg/slayers/extn.go` line 453 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG31kt3r7WXtmW6iTl:-NAG31ku-iRAK_x8XJho:b-8scikw) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L453)):*
> ```Go
> // packet authentication option. DRKey values are in the
> // range [1, 2^21-1].
> type PacketAuthSPI uint32
> ```

Move this type to just above the implementation of its methods
___
*[`pkg/slayers/extn.go` line 455 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG2gog0KqzF8w6ETXJ:-NAG2gog0KqzF8w6ETXK:bwet6hx) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L455)):*
> ```Go
> type PacketAuthSPI uint32
> 
> type PacketAuthDRKeyType uint8
> ```

I don't think that the types `PacketAuth{DRKeyType,DRKeyDirection,DRKeyEpochType}` are necessary. Simply define the constants as 0 and 1 and make them type `unit8`
___
*[`pkg/slayers/extn.go` line 512 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG3Vi0A8NmSRyG9EYE:-NAG3Vi0A8NmSRyG9EYF:b-n3099s) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L512)):*
> ```Go
> ) PacketAuthSPI {
> 
> 	if proto < 1 {
> ```

This method should not panic. Instead it should return an error.
___
*[`pkg/slayers/extn.go` line 573 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG45pLCXKGWCjzUVw1:-NAG45pLCXKGWCjzUVw2:b3j1jbs) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L573)):*
> ```Go
> 			serrors.New("wrong option type", "expected", OptTypeAuthenticator, "actual", o.OptType)
> 	}
> 	if len(o.OptData) < 12 {
> ```

Define this magic constant and describe why it's 12 bytes



_Code quote:_
```Go
12
```
___
*[`pkg/slayers/extn.go` line 582 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG4axpCbqG1pYIxFmB:-NAG4axpCbqG1pYIxFmC:bz8yj5y) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L582)):*
> ```Go
> // Reset reinitializes the underlying EndToEndOption with the SPAO data.
> // Reuses the OptData buffer if it is of sufficient capacity.
> func (o PacketAuthOption) Reset(
> ```

Create a type for the PacketAuthOption parameters and pass that instead



_Code snippet:_
```Go
type PacketAuthOptionParams struct {
	SPI PacketAuthSPI
	Algorithm PacketAuthAlg
	Timestamp uint32
	SequenceNumber uint32	
}
```
___
*[`pkg/slayers/extn.go` line 590 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG5Z_LC97NGgJjTRmD:-NAG5Z_LC97NGgJjTRmE:b7xeg9i) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L590)):*
> ```Go
> ) {
> 
> 	if ts >= (1 << 24) {
> ```

Library functions that panic are dangerous. Especially, when they will receive user input that you cannot control. You can either return an error here or then you need to document clearly under what conditions the function will panic.
___
*[`pkg/slayers/extn.go` line 622 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG4IiSEKmixkR7wd7_:-NAG4IiSEKmixkR7wd7a:b-6ga3zf) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L622)):*
> ```Go
> }
> 
> // SPI returns returns the value set in the homonym field in the extension.
> ```

What's the "homonym field"? Call it the security parameter index



_Suggestion:_
```Go
security parameter index
```
___
*[`pkg/slayers/extn_test.go` line 546 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG63g-Dug-bIVa7jsn:-NAG63g-Dug-bIVa7jso:b-w66vh8) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn_test.go#L546)):*
> ```Go
> }
> 
> var spi = slayers.MakePacketAuthSPIDRKey(
> ```

Make this a single var block
```
var (
...
)
```


<!-- Sent from Reviewable.io -->

2022-09-07 11:33 UTC, JordiSubira reviewed
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190)* status: all files reviewed, 10 unresolved discussions (waiting on @shitz)

___
*[`pkg/slayers/extn.go` line 450 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG1fPR7ZfxFi4g26dD:-NBMiMPR6OjQKC6jPkC9:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L450)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

This file is getting too large. Please move all the SPAO related entities to a file `pkt_auth.go`.

Also please add a comment at the top of the file that this is the implementation of the SPAO and link to the documentation
</blockquote></details>

Done.
___
*[`pkg/slayers/extn.go` line 450 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG3AGJ6qbrbpOoAazy:-NBMiOL4ECW6PJVtk9_9:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L450)):*
> ```Go
> }
> 
> // PacketAuthSPI is the identifier for the key used for the
> ```

Done.
___
*[`pkg/slayers/extn.go` line 453 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG31kt3r7WXtmW6iTl:-NBMiNgR7KcGvB-dFQDk:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L453)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Move this type to just above the implementation of its methods
</blockquote></details>

Done.
___
*[`pkg/slayers/extn.go` line 455 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG2gog0KqzF8w6ETXJ:-NBMiN433SYlfTccRR4s:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L455)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

I don't think that the types `PacketAuth{DRKeyType,DRKeyDirection,DRKeyEpochType}` are necessary. Simply define the constants as 0 and 1 and make them type `unit8`
</blockquote></details>

Done.
___
*[`pkg/slayers/extn.go` line 512 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG3Vi0A8NmSRyG9EYE:-NBMiOz9A-qUqCIBdZt9:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L512)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

This method should not panic. Instead it should return an error.
</blockquote></details>

Done.
___
*[`pkg/slayers/extn.go` line 573 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG45pLCXKGWCjzUVw1:-NBMiPWR5cPMBesdfXBw:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L573)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Define this magic constant and describe why it's 12 bytes
</blockquote></details>

Done.
___
*[`pkg/slayers/extn.go` line 582 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG4axpCbqG1pYIxFmB:-NBMiQynEO5fJ7_QZbFo:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L582)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Create a type for the PacketAuthOption parameters and pass that instead
</blockquote></details>

Done.
___
*[`pkg/slayers/extn.go` line 590 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG5Z_LC97NGgJjTRmD:-NBMiRMg-vOKW513nigq:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L590)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Library functions that panic are dangerous. Especially, when they will receive user input that you cannot control. You can either return an error here or then you need to document clearly under what conditions the function will panic.
</blockquote></details>

Done.
___
*[`pkg/slayers/extn.go` line 622 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG4IiSEKmixkR7wd7_:-NBMiQ2f5cyx5dE3T48Y:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn.go#L622)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

What's the "homonym field"? Call it the security parameter index
</blockquote></details>

Done.
___
*[`pkg/slayers/extn_test.go` line 546 at r8](https://reviewable.io/reviews/scionproto/scion/4190#-NAG63g-Dug-bIVa7jsn:-NBMiSpkBYy5_zES0r67:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/2c0d9155ed1bd532310e7aa86f688d8240bbf452/pkg/slayers/extn_test.go#L546)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Make this a single var block
```
var (
...
)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-09 06:02 UTC, shitz requested changes
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190)* status: all files reviewed, 4 unresolved discussions (waiting on @JordiSubira)

___
*[`pkg/slayers/pkt_auth.go` line 42 at r9](https://reviewable.io/reviews/scionproto/scion/4190#-NBVpIOm1sxC1fxpo-fi:-NBVpIOm1sxC1fxpo-fj:undefined) ([raw file](https://github.com/scionproto/scion/blob/f91e9ec9561a3e69e8e6654970cbe6910d8331df/pkg/slayers/pkt_auth.go#L42)):*
> ```Go
> 
> // MinOptDataLen is the minimum size of the SPAO OptData
> const MinOptDataLen = 12
> ```





_Suggestion:_
```Go
MinPacketAuthDataLen
```
___
*[`pkg/slayers/pkt_auth.go` line 172 at r9](https://reviewable.io/reviews/scionproto/scion/4190#-NBVp1455vOpF-NwlQ7c:-NBVp1455vOpF-NwlQ7d:b-hlylri) ([raw file](https://github.com/scionproto/scion/blob/f91e9ec9561a3e69e8e6654970cbe6910d8331df/pkg/slayers/pkt_auth.go#L172)):*
> ```Go
> 	o.OptType = OptTypeAuthenticator
> 
> 	n := 12 + len(p.Auth) // 4 + 1 + 3 + 1 + 3 + len(data)
> ```

This should use the constant.



_Suggestion:_
```Go
MinPacketAuthDataLen
```
___
*[`pkg/slayers/pkt_auth.go` line 172 at r9](https://reviewable.io/reviews/scionproto/scion/4190#-NBVp3Qq7fHz7aD_5GgW:-NBVp3Qq7fHz7aD_5GgX:b-qar3n8) ([raw file](https://github.com/scionproto/scion/blob/f91e9ec9561a3e69e8e6654970cbe6910d8331df/pkg/slayers/pkt_auth.go#L172)):*
> ```Go
> 	o.OptType = OptTypeAuthenticator
> 
> 	n := 12 + len(p.Auth) // 4 + 1 + 3 + 1 + 3 + len(data)
> ```

This should be added to the docstring of the minlen constant. Ideally, with an indication what each number refers to.



_Code quote:_
```Go
4 + 1 + 3 + 1 + 3
```
___
*[`pkg/slayers/pkt_auth_test.go` line 34 at r9](https://reviewable.io/reviews/scionproto/scion/4190#-NBVptBY7sNUNkxIRBy7:-NBVptBY7sNUNkxIRBy8:bc3o59w) ([raw file](https://github.com/scionproto/scion/blob/f91e9ec9561a3e69e8e6654970cbe6910d8331df/pkg/slayers/pkt_auth_test.go#L34)):*
> ```Go
> 	optAuthMAC = []byte("16byte_mac_foooo")
> )
> ```

This should be included in `pkt_auth.go`



_Code quote:_
```Go
// +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
// |   NextHdr=UDP |     ExtLen    |  OptType=2    |  OptDataLen   |
// +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
// |                   Security Parameter Index                    |
// +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
// |    Algorithm  |                    Timestamp                  |
// +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
// |      RSV      |                  Sequence Number              |
// +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
// |                                                               |
// +                                                               +
// |                                                               |
// +                        16-octet MAC data                      +
// |                                                               |
// +                                                               +
// |                                                               |
// +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```


<!-- Sent from Reviewable.io -->

2022-09-09 08:55 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @JordiSubira and @shitz)

___
*[`pkg/slayers/pkt_auth.go` line 42 at r9](https://reviewable.io/reviews/scionproto/scion/4190#-NBVpIOm1sxC1fxpo-fi:-NBWSGbH6GumiZECfEFu:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f91e9ec9561a3e69e8e6654970cbe6910d8331df/pkg/slayers/pkt_auth.go#L42)):*
> ```Go
> 
> // MinOptDataLen is the minimum size of the SPAO OptData
> const MinOptDataLen = 12
> ```

Done.
___
*[`pkg/slayers/pkt_auth.go` line 172 at r9](https://reviewable.io/reviews/scionproto/scion/4190#-NBVp1455vOpF-NwlQ7c:-NBWSIHy3tEMJtUUPrfA:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f91e9ec9561a3e69e8e6654970cbe6910d8331df/pkg/slayers/pkt_auth.go#L172)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

This should use the constant.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 172 at r9](https://reviewable.io/reviews/scionproto/scion/4190#-NBVp3Qq7fHz7aD_5GgW:-NBWSJm7-L5Kvy4opEuh:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f91e9ec9561a3e69e8e6654970cbe6910d8331df/pkg/slayers/pkt_auth.go#L172)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

This should be added to the docstring of the minlen constant. Ideally, with an indication what each number refers to.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth_test.go` line 34 at r9](https://reviewable.io/reviews/scionproto/scion/4190#-NBVptBY7sNUNkxIRBy7:-NBWSLYV0H33IqdJSPkv:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f91e9ec9561a3e69e8e6654970cbe6910d8331df/pkg/slayers/pkt_auth_test.go#L34)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

This should be included in `pkt_auth.go`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-09 09:09 UTC, shitz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4190#-:-NBWVhmEDWPtbUaVeWHj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2022-09-09 09:19 UTC, merged