lib: Refactor how periodic tasks use metrics
scionproto/scion pull request #4204
Opened 2022-05-30 05:50 UTC by Hygster

Add function to start Periodic tasks with specified metrics or without metrics at all

NO_RELEASE_NOTE

Fixes #5785

2022-06-10 08:00 UTC, lukedirtwalker requested changes
> Reviewed 6 of 9 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4204)* status: all files reviewed, 18 unresolved discussions (waiting on @Hygster)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4204#-N4BaXD65Wa0jHC4h9p9:-N4BaXD77p29ryH3Z7Ez:bfgz194) (no related file):*
> Fixes #5785

Please remove this reference, it doesn't have much meaning here since this is an internal ticket.

___
*[a discussion](https://reviewable.io/reviews/scionproto/scion/4204#-N4Bafkt8LD_tnkqeC8S:-N4Bafkt8LD_tnkqeC8T:b-mcimee) (no related file):*
title:
`lib/periodic: add function to inject metrics in task`

description:

Add `StartWithMetrics` function to the periodic task library to have full control over the metrics that are exposed by the library.

___
___
*[`gateway/gateway.go` line 318 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4Bc5f37LUfEPlI2j9u:-N4Bc5f37LUfEPlI2j9v:byhpey9) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/gateway/gateway.go#L318)):*
> ```Go
> 
> 	// periodicly clean up the revocation store.
> 	revCleaner := periodic.StartWithMetric(
> ```

actually let's keep the old implementation anyway so that we don't introduce any unexpected changes.
___
*[`private/file/periodicview.go` line 86 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4Bb6Az6iOcXbU3noeI:-N4Bb6Az6iOcXbU3noeJ:bzdngyx) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/file/periodicview.go#L86)):*
> ```Go
> 		v.readTask.read()
> 
> 		// Set up metrics for goroutine
> ```

Why are the changes in this file? can't we just use the `periodic.Start` still for this?
___
*[`private/periodic/periodic.go` line 24 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BXdd81gMgs9DvHwEj:-N4BXdd97wVOw8Uoxfxw:b-mqx5ej) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L24)):*
> ```Go
> 
> 	"github.com/scionproto/scion/pkg/log"
> 	emetrics "github.com/scionproto/scion/pkg/metrics"
> ```

Instead of naming this import let's change the name of the old import to `legacymetrics`
___
*[`private/periodic/periodic.go` line 47 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BXp330Y35wTTgDpeS:-N4BXp330Y35wTTgDpeT:undefined) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L47)):*
> ```Go
> )
> 
> // Metrics contins the relavant metrics for the task in the same Runner.
> ```





_Suggestion:_
```Go
contains
```
___
*[`private/periodic/periodic.go` line 47 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BXvAI5TE_JpDmC30-:-N4BXvAI5TE_JpDmC300:undefined) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L47)):*
> ```Go
> )
> 
> // Metrics contins the relavant metrics for the task in the same Runner.
> ```





_Suggestion:_
```Go
for a periodic task.
```
___
*[`private/periodic/periodic.go` line 59 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BY9S26WvR_LTlSUDO:-N4BY9S32noQhd1snK5E:b-nr7jbc) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L59)):*
> ```Go
> }
> 
> func (m Metrics) SetStartTimestamp(t time.Time) {
> ```

all those methods don't have to be public since they are just used here.

(applies to all 4 methods)
___
*[`private/periodic/periodic.go` line 60 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BYKGD1mm6BJVtxKdr:-N4BYKGD1mm6BJVtxKds:bfwnksm) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L60)):*
> ```Go
> 
> func (m Metrics) SetStartTimestamp(t time.Time) {
> 	if m.StartTime != nil {
> ```

you can use the metrics helpers for those methods then you don't need the if:
```go
	emetrics.GaugeSet(m.StartTime, float64(t.UnixNano() / 1e9))
```

(applies to all 4 methods)
___
*[`private/periodic/periodic.go` line 183 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BZY7w392utwOHK4XZ:-N4BZY7w392utwOHK4X_:bqat0c) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L183)):*
> ```Go
> }
> 
> // Start creates and starts a new Runner to run the given task peridiocally.
> ```

Since `Start` and `StartWithMetrics` are kind of constructors for the `Runner` struct let's move them directly after the declaration of the struct.
___
*[`private/periodic/periodic.go` line 187 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BZ-gsB2oQIgE_5yJh:-N4BZ-gsB2oQIgE_5yJi:buds62e) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L187)):*
> ```Go
> // larger than the periodicity of the task. That means if a tasks takes a long
> // time it will be immediately retriggered.
> func Start(task Task, period, timeout time.Duration) *Runner {
> ```

let's mark this as deprecated:
```
// Deprecated: Start exists for compatibility reasons, use StartWithMetrics instead
```
see also (https://github.com/golang/go/wiki/Deprecated)
___
*[`private/periodic/periodic.go` line 200 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BZX9l4qIzxQN_EBag:-N4BZX9l4qIzxQN_EBah:undefined) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L200)):*
> ```Go
> // StartWithMetric is identical to Start but allows the caller to
> // specify the metric or no metric at all to be used.
> func StartWithMetric(task Task, metric Metrics, period, timeout time.Duration) *Runner {
> ```





_Suggestion:_
```Go
 StartWithMetrics
```
___
*[`private/periodic/periodic.go` line 216 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BZmKR8aXfhigKk8Hc:-N4BZmKR8aXfhigKk8Hd:b-wlx0rv) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L216)):*
> ```Go
> 	}
> 	logger.Info("Starting periodic task", "task", task.Name())
> 	if r.metric.Period != nil {
> ```

why not use the `r.metric.setPeriod()` method? or if we don't want to use it we can just use the `metrics.GaugeSet` function
___
*[`private/periodic/periodic.go` line 219 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4B_3MH-f-wCf2JcVu7:-N4B_3MH-f-wCf2JcVu8:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L219)):*
> ```Go
> 		r.metric.Period.Set(period.Seconds())
> 	}
> 	if r.metric.StartTime != nil {
> ```

ditto
___
*[`private/periodic/periodic_test.go` line 55 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BbU7d6d-4plPPgezd:-N4BbU7d6d-4plPPgeze:b-hzeuw3) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic_test.go#L55)):*
> ```Go
> 	p := time.Duration(want) * 20 * time.Millisecond
> 	r := StartWithMetric(fn, met, p, time.Hour)
> 	// defer func() {
> ```

let's drop this.
___
*[`private/periodic/periodic_test.go` line 173 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BbkSz4sdlouXnR58h:-N4BbkSz4sdlouXnR58i:b-q9t09x) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic_test.go#L173)):*
> ```Go
> 		},
> 		// With additional metrics
> 		Period:    metrics.NewTestGauge(),
> ```

can we also check the values of those at the end.

You can use https://pkg.go.dev/github.com/stretchr/testify/assert?utm_source=godoc#InDelta for the Time metrics.
___
*[`private/periodic/internal/metrics/metrics.go` line 28 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BWn3g9X6SPymMLQAd:-N4BWn3g9X6SPymMLQAe:bj8tkfp) ([raw [...]

2022-06-13 08:39 UTC, Hygster reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4204)* status: 3 of 9 files reviewed, 18 unresolved discussions (waiting on @lukedirtwalker)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4204#-N4BaXD65Wa0jHC4h9p9:-N4CY0M-3Ejah5f-9nJ9:b6zyexe) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> Fixes #5785

Please remove this reference, it doesn't have much meaning here since this is an internal ticket.
</blockquote></details>


Is that always the case when working on the scionproto repo?
Done.

___
*[a discussion](https://reviewable.io/reviews/scionproto/scion/4204#-N4Bafkt8LD_tnkqeC8S:-N4CYc-y4XohpIl5BQps:b-896fix) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

title:
`lib/periodic: add function to inject metrics in task`

description:

Add `StartWithMetrics` function to the periodic task library to have full control over the metrics that are exposed by the library.
</blockquote></details>

Done.

___
___
*[`gateway/gateway.go` line 318 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4Bc5f37LUfEPlI2j9u:-N4CZn9C7S8GKJ0yVRdv:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/gateway/gateway.go#L318)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

actually let's keep the old implementation anyway so that we don't introduce any unexpected changes.
</blockquote></details>

Done.



_Code quote:_
```Go
	// periodicly clean up the revocation store.
	revCleaner := periodic.Start(periodic.Func{

		Task: func(ctx context.Context) {
			revStore.Cleanup(ctx)
		},
		TaskName: "revocation_store_cleaner",
	}, 30*time.Second, 30*time.Second)
```
___
*[`private/periodic/periodic.go` line 24 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BXdd81gMgs9DvHwEj:-N4ChcSx7ugEWn3bkOMV:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L24)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Instead of naming this import let's change the name of the old import to `legacymetrics`
</blockquote></details>

Done.
___
*[`private/periodic/periodic.go` line 47 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BXp330Y35wTTgDpeS:-N4CiWFtCoJCg-yzaVN0:b-2harbb) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L47)):*
> ```Go
> )
> 
> // Metrics contins the relavant metrics for the task in the same Runner.
> ```

just got a spell checker extension, so hopefully, that'll be the last time something like this slips through :sweat_smile: 
___
*[`private/periodic/periodic.go` line 47 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BXvAI5TE_JpDmC30-:-N4Cilyv6wrJd2sRlaAM:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L47)):*
> ```Go
> )
> 
> // Metrics contins the relavant metrics for the task in the same Runner.
> ```

Done.
___
*[`private/periodic/periodic.go` line 59 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BY9S26WvR_LTlSUDO:-N4CiydYEynUEMR6AHQ6:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L59)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

all those methods don't have to be public since they are just used here.

(applies to all 4 methods)
</blockquote></details>

Done.
___
*[`private/periodic/periodic.go` line 60 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BYKGD1mm6BJVtxKdr:-N4Q_eDO55AJitjPMSV9:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L60)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

you can use the metrics helpers for those methods then you don't need the if:
```go
	emetrics.GaugeSet(m.StartTime, float64(t.UnixNano() / 1e9))
```

(applies to all 4 methods)
</blockquote></details>

Done.
___
*[`private/periodic/periodic.go` line 183 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BZY7w392utwOHK4XZ:-N4QaFBxBTiQZNnRL1nk:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L183)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Since `Start` and `StartWithMetrics` are kind of constructors for the `Runner` struct let's move them directly after the declaration of the struct.
</blockquote></details>

Done.
___
*[`private/periodic/periodic.go` line 187 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BZ-gsB2oQIgE_5yJh:-N4QaqrrAq5T8ZVOot9u:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L187)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

let's mark this as deprecated:
```
// Deprecated: Start exists for compatibility reasons, use StartWithMetrics instead
```
see also (https://github.com/golang/go/wiki/Deprecated)
</blockquote></details>

Done.
___
*[`private/periodic/periodic.go` line 200 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BZX9l4qIzxQN_EBag:-N4Qavph8xnOC4XdPaAs:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L200)):*
> ```Go
> // StartWithMetric is identical to Start but allows the caller to
> // specify the metric or no metric at all to be used.
> func StartWithMetric(task Task, metric Metrics, period, timeout time.Duration) *Runner {
> ```

Done.
___
*[`private/periodic/periodic.go` line 216 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BZmKR8aXfhigKk8Hc:-N4QjBIlEUPpdjixglwp:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L216)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

why not use the `r.metric.setPeriod()` method? or if we don't want to use it we can just use the `metrics.GaugeSet` function
</blockquote></details>

Done.
___
*[`private/periodic/periodic.go` line 219 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4B_3MH-f-wCf2JcVu7:-N4QjBph3Zffibu5v8tk:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L219)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`private/periodic/periodic_test.go` line 55 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BbU7d6d-4plPPgezd:-N4QjSN0EuA6f72-4CcH:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic_test.go#L55)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

let's drop this.
</blockquote></details>

Done.
___
*[`private/periodic/periodic_test.go` line 173 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BbkSz4sdlouXnR58h:-N4R0IlS0ZMs3lbHFOK5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic_test.go#L173)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

can we also check the values of those at the end.

You can use https://pkg.go.dev/github.com/stretchr/testify/assert?utm_source=godoc#InDelta for the Time metrics.
</bl [...]

2022-06-13 12:30 UTC, lukedirtwalker requested changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4204)* status: all files reviewed, 5 unresolved discussions (waiting on @Hygster)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4204#-N4BaXD65Wa0jHC4h9p9:-N4Rnzl55TFIokJqPDVx:b-czzg68) (no related file):*
<details><summary><i>Previously, Hygster (August Rønberg) wrote…</i></summary><blockquote>


Is that always the case when working on the scionproto repo?
Done.
</blockquote></details>

Yes internal references never work. If there is a public issue then you can also a `Fixes #<public-issue-number>` comment.

___
___
*[`private/periodic/periodic.go` line 47 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4BXp330Y35wTTgDpeS:-N4S-Nsy5yRLUuTCJKn6:b-8ft9vm) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/periodic/periodic.go#L47)):*
<details><summary><i>Previously, Hygster (August Rønberg) wrote…</i></summary><blockquote>

just got a spell checker extension, so hopefully, that'll be the last time something like this slips through :sweat_smile: 
</blockquote></details>

:100:
___
*[`private/periodic/periodic.go` line 48 at r4](https://reviewable.io/reviews/scionproto/scion/4204#-N4S-PNhCLvsLoc4UFGl:-N4S-PNhCLvsLoc4UFGm:b-59s6tp) ([raw file](https://github.com/scionproto/scion/blob/bab73ef59cfd0e9531b19e1515f0afd9a6a849d1/private/periodic/periodic.go#L48)):*
> ```Go
> 
> // Metrics contains the relevant metrics for a periodic task.
> type Metrics struct {
> ```

The fields of the struct still have to be public, only the `set...` method below can be non-public.
Otherwise users of the package can no longer specify the metrics.
___
*[`private/periodic/periodic.go` line 111 at r4](https://reviewable.io/reviews/scionproto/scion/4204#-N4RzhV3B_Yx3SBmKOj4:-N4RzhV3B_Yx3SBmKOj5:undefined) ([raw file](https://github.com/scionproto/scion/blob/bab73ef59cfd0e9531b19e1515f0afd9a6a849d1/private/periodic/periodic.go#L111)):*
> ```Go
> // time it will be immediately retriggered.
> //
> // Deprecated: Start exists for compatibility reasons, use StartWithMetrics instead
> ```





_Suggestion:_
```Go
instead.
```
___
*[`private/periodic/periodic.go` line 142 at r4](https://reviewable.io/reviews/scionproto/scion/4204#-N4RzoRZ0B1WsQYe4z3a:-N4RzoRZ0B1WsQYe4z3b:b-l6mwxj) ([raw file](https://github.com/scionproto/scion/blob/bab73ef59cfd0e9531b19e1515f0afd9a6a849d1/private/periodic/periodic.go#L142)):*
> ```Go
> 	logger.Info("Starting periodic task", "task", task.Name())
> 	r.metric.setPeriod(period)
> 	// metrics.GaugeSet(r.metric.period, period.Seconds())
> ```

remove
___
*[`private/periodic/periodic_test.go` line 15 at r4](https://reviewable.io/reviews/scionproto/scion/4204#-N4S1jhU41QjrTuU7bpS:-N4S1jhU41QjrTuU7bpT:b-wsvcgy) ([raw file](https://github.com/scionproto/scion/blob/bab73ef59cfd0e9531b19e1515f0afd9a6a849d1/private/periodic/periodic_test.go#L15)):*
> ```Go
> // limitations under the License.
> 
> package periodic
> ```

could you try to make this `periodic_test` ?
___
*[`private/periodic/internal/metrics/metrics.go` line 28 at r4](https://reviewable.io/reviews/scionproto/scion/4204#-N4RzLdiC28ErhaNhxKh:-N4RzLdiC28ErhaNhxKi:undefined) ([raw file](https://github.com/scionproto/scion/blob/bab73ef59cfd0e9531b19e1515f0afd9a6a849d1/private/periodic/internal/metrics/metrics.go#L28)):*
> ```Go
> // Metrics is the standard metrics used in periodic.Runner
> 
> // Deprecated: Metrics is used only my the deprecated function periodic.Start
> ```





_Suggestion:_
```Go
in the 
```
___
*[`private/file/periodicview.go` line 86 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4Bb6Az6iOcXbU3noeI:-N4S0tT--bF6Mz1FyLUV:b-auq7bm) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/file/periodicview.go#L86)):*
<details><summary><i>Previously, Hygster (August Rønberg) wrote…</i></summary><blockquote>

This, and the change in gateway.go, were the example implementations of StartWithMetrics you asked me to do. Maybe I misunderstood: I thought you wanted me to make them a part of the PR. I've reverted this now as well
</blockquote></details>

Yes that's correct, but I actually realized that this would be a slightly breaking change because the metrics would suddenly change, therefore I thought it's cleaner to not do it. We verify in the test that the things work as expected. Sorry for the back and forth.


<!-- Sent from Reviewable.io -->

2022-06-13 13:57 UTC, Hygster reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4204)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @lukedirtwalker)

___
*[`private/periodic/periodic.go` line 48 at r4](https://reviewable.io/reviews/scionproto/scion/4204#-N4S-PNhCLvsLoc4UFGl:-N4SHhgr2J6beHQD9ATp:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4d3ffbbcad84963eedd5d4241f92c44c6d312ea0/private/periodic/periodic.go#L48)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

The fields of the struct still have to be public, only the `set...` method below can be non-public.
Otherwise users of the package can no longer specify the metrics.
</blockquote></details>

Done.
___
*[`private/periodic/periodic.go` line 111 at r4](https://reviewable.io/reviews/scionproto/scion/4204#-N4RzhV3B_Yx3SBmKOj4:-N4SLRkvBSryDNfvW7wf:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4d3ffbbcad84963eedd5d4241f92c44c6d312ea0/private/periodic/periodic.go#L111)):*
> ```Go
> // time it will be immediately retriggered.
> //
> // Deprecated: Start exists for compatibility reasons, use StartWithMetrics instead
> ```

Done.
___
*[`private/periodic/periodic.go` line 142 at r4](https://reviewable.io/reviews/scionproto/scion/4204#-N4RzoRZ0B1WsQYe4z3a:-N4SHtjI7GviJkNzk7xL:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4d3ffbbcad84963eedd5d4241f92c44c6d312ea0/private/periodic/periodic.go#L142)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`private/periodic/periodic_test.go` line 15 at r4](https://reviewable.io/reviews/scionproto/scion/4204#-N4S1jhU41QjrTuU7bpS:-N4SKx_eEPfUqbpkb_jR:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4d3ffbbcad84963eedd5d4241f92c44c6d312ea0/private/periodic/periodic_test.go#L15)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

could you try to make this `periodic_test` ?
</blockquote></details>

Done.
___
*[`private/periodic/internal/metrics/metrics.go` line 28 at r4](https://reviewable.io/reviews/scionproto/scion/4204#-N4RzLdiC28ErhaNhxKh:-N4SL1HcCAUy78ucadxW:bv9nd7u) ([raw file](https://github.com/scionproto/scion/blob/4d3ffbbcad84963eedd5d4241f92c44c6d312ea0/private/periodic/internal/metrics/metrics.go#L28)):*
> ```Go
> // Metrics is the standard metrics used in periodic.Runner
> 
> // Deprecated: Metrics is used only my the deprecated function periodic.Start
> ```

Sadly the spell checker doesn't catch those mistakes :sweat_smile: 
___
*[`private/file/periodicview.go` line 86 at r3](https://reviewable.io/reviews/scionproto/scion/4204#-N4Bb6Az6iOcXbU3noeI:-N4SLMkT3gSphYWLYRC2:b-u83mut) ([raw file](https://github.com/scionproto/scion/blob/c6b0c93c654f774030d84376cd0ab00f9a989cab/private/file/periodicview.go#L86)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Yes that's correct, but I actually realized that this would be a slightly breaking change because the metrics would suddenly change, therefore I thought it's cleaner to not do it. We verify in the test that the things work as expected. Sorry for the back and forth.
</blockquote></details>

I see, No worries


<!-- Sent from Reviewable.io -->

2022-06-13 15:23 UTC, lukedirtwalker requested changes
> Reviewed 4 of 4 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4204)* status: all files reviewed, 2 unresolved discussions (waiting on @Hygster)

___
*[`private/periodic/periodic_test.go` line 42 at r7](https://reviewable.io/reviews/scionproto/scion/4204#-N4Se-Xg0YcLz8VjjPi3:-N4Se-Xg0YcLz8VjjPi4:bhsj5ua) ([raw file](https://github.com/scionproto/scion/blob/7b64e789b22495f6dc3320605e279c27a4fd0cb7/private/periodic/periodic_test.go#L42)):*
> ```Go
> func TestPeriodicExecution(t *testing.T) {
> 	events := metrics.NewTestCounter()
> 	met := periodic.Metrics{
> ```

let's just name this `m` everywhere.



_Suggestion:_
```Go
m := periodic.Metrics
```
___
*[`private/periodic/periodic_test.go` line 81 at r7](https://reviewable.io/reviews/scionproto/scion/4204#-N4Se3w16JFw7PgAAEHa:-N4Se3w16JFw7PgAAEHb:b-3m7pbq) ([raw file](https://github.com/scionproto/scion/blob/7b64e789b22495f6dc3320605e279c27a4fd0cb7/private/periodic/periodic_test.go#L81)):*
> ```Go
> 	assert.NoError(t, err, "r.Stop() action timed out")
> 	// Check that  metrics work as expected
> 	assert.Equal(t, float64(1), metrics.CounterValue(r.GetMetric().Events(periodic.EventStop)))
> ```

here you can just refer to the metrics struct (`met` or after renaming `m`). Then you don't need the `export_test.go`



_Suggestion:_
```Go
m
```


<!-- Sent from Reviewable.io -->

2022-06-14 05:48 UTC, lukedirtwalker approved these changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4204)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Hygster)



<!-- Sent from Reviewable.io -->

2022-06-14 05:51 UTC, lukedirtwalker requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4204)* status: all files reviewed, 2 unresolved discussions (waiting on @Hygster)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4204#-N4Vkm-b1HGV_OYtIvaR:-N4Vkm-b1HGV_OYtIvaS:bfxmvyb) (no related file):*
You can `rm -r private/periodic/internal/metrics/mock_metrics` this should no longer be needed.

___
*[a discussion](https://reviewable.io/reviews/scionproto/scion/4204#-N4Vl-6c7E7Oe5vA9e7v:-N4Vl-6c7E7Oe5vA9e7w:b-eqcpew) (no related file):*
There are some golangci-lint reports here https://buildkite.com/scionproto/scion/builds/2890#018160af-ec54-489f-ad7c-3bf27925dcc4/153-326

___


<!-- Sent from Reviewable.io -->

2022-06-14 05:59 UTC, Hygster reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4204)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4204#-N4Vkm-b1HGV_OYtIvaR:-N4Vm3JMAFKnuboCC-M-:b-896fix) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

You can `rm -r private/periodic/internal/metrics/mock_metrics` this should no longer be needed.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/scionproto/scion/4204#-N4Vl-6c7E7Oe5vA9e7v:-N4Vmlfk8ItRxmWzsWU5:b-896fix) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

There are some golangci-lint reports here https://buildkite.com/scionproto/scion/builds/2890#018160af-ec54-489f-ad7c-3bf27925dcc4/153-326
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-06-14 06:20 UTC, lukedirtwalker approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4204)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Hygster)



<!-- Sent from Reviewable.io -->

2022-06-14 07:09 UTC, merged