drkey: add daemon client engine
scionproto/scion pull request #4232
Opened 2022-07-22 10:57 UTC by JordiSubira

This PR is the 10th in a series of PRs that add support for DRKey started with https://github.com/scionproto/scion/pull/4217.

This PR contains:
 -  The DRKey client engine for the daemon. It encompasses the logic for managing/requesting Lvl2/3Keys

2022-07-25 08:23 UTC, lukedirtwalker requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4232)* status: all files reviewed, 6 unresolved discussions (waiting on @JordiSubira)

___
*[`daemon/drkey/client_engine.go` line 27 at r1](https://reviewable.io/reviews/scionproto/scion/4232#-N7oOwyEDr4UZrDBLgXt:-N7oOwyEDr4UZrDBLgXu:bn4ulvg) ([raw file](https://github.com/scionproto/scion/blob/97402b8774d60e5bc05f8d06c934d3cbf09bb5a3/daemon/drkey/client_engine.go#L27)):*
> ```Go
> )
> 
> // Fetcher obtains a end host keys from the local CS.
> ```

Either it obtains `a end host key` or `end host keys` but right now there is both an `a` and the plural form `keys`



_Code quote:_
```Go
 Fetcher obtains a end host keys from the local CS.
```
___
*[`daemon/drkey/client_engine.go` line 42 at r1](https://reviewable.io/reviews/scionproto/scion/4232#-N7oPohr-Tgq_Tg-qzgr:-N7oPohs9eOTAj-mTOzF:bo7b21j) ([raw file](https://github.com/scionproto/scion/blob/97402b8774d60e5bc05f8d06c934d3cbf09bb5a3/daemon/drkey/client_engine.go#L42)):*
> ```Go
> 
> // GetASHostKey returns the ASHost key from the local DB or if not found, by asking our local CS.
> func (s *ClientEngine) GetASHostKey(ctx context.Context,
> ```

Let's format this way, for all methods that span multiple lines:
it's easier to read



_Suggestion:_
```Go
func (s *ClientEngine) GetASHostKey(
	ctx context.Context,
	meta drkey.ASHostMeta,
) (drkey.ASHostKey, error) {
```
___
*[`daemon/drkey/client_engine.go` line 42 at r1](https://reviewable.io/reviews/scionproto/scion/4232#-N7oQvmEA6cdQDuyBqLC:-N7oQvmEA6cdQDuyBqLD:bdk8kmu) ([raw file](https://github.com/scionproto/scion/blob/97402b8774d60e5bc05f8d06c934d3cbf09bb5a3/daemon/drkey/client_engine.go#L42)):*
> ```Go
> 
> // GetASHostKey returns the ASHost key from the local DB or if not found, by asking our local CS.
> func (s *ClientEngine) GetASHostKey(ctx context.Context,
> ```

Where is the `s` as variable name for the `ClientEngine` coming from? I would have expected `e` for Engine.



_Code quote:_
```Go
(s *ClientEngine)
```
___
*[`daemon/drkey/client_engine.go` line 77 at r1](https://reviewable.io/reviews/scionproto/scion/4232#-N7oQ9Yo0ejfQ5z-1cUy:-N7oQ9Yo0ejfQ5z-1cUz:b-7ighyh) ([raw file](https://github.com/scionproto/scion/blob/97402b8774d60e5bc05f8d06c934d3cbf09bb5a3/daemon/drkey/client_engine.go#L77)):*
> ```Go
> 		return drkey.HostASKey{}, serrors.WrapStr("looking up Host-AS key in DB", err)
> 	}
> 	// if not, ask our CS for it
> ```

move this one line below.
___
*[`daemon/drkey/client_engine.go` line 102 at r1](https://reviewable.io/reviews/scionproto/scion/4232#-N7oQCqV1TIXeR8U72kG:-N7oQCqV1TIXeR8U72kH:bmo5f5j) ([raw file](https://github.com/scionproto/scion/blob/97402b8774d60e5bc05f8d06c934d3cbf09bb5a3/daemon/drkey/client_engine.go#L102)):*
> ```Go
> 		return drkey.HostHostKey{}, serrors.WrapStr("looking up Host-Host key in DB", err)
> 	}
> 	// if not, ask our CS for it
> ```

move this one line below
___
*[`daemon/drkey/client_engine.go` line 115 at r1](https://reviewable.io/reviews/scionproto/scion/4232#-N7oQTGA-GwvpMmwlJP_:-N7oQTGA-GwvpMmwlJPa:bjty7kd) ([raw file](https://github.com/scionproto/scion/blob/97402b8774d60e5bc05f8d06c934d3cbf09bb5a3/daemon/drkey/client_engine.go#L115)):*
> ```Go
> 
> // DeleteExpiredKeys will remove any expired keys.
> func (s *ClientEngine) DeleteExpiredASHostKeys(ctx context.Context) (int, error) {
> ```

do we have those delete methods just so that we can pass the `ClientEngine` to the `New*Cleaner` function below? If that's the case we could also just have a method `func (s *ClientEngine) CreateStorageCleaners() []*cleaner.Cleaner` that is on the `ClientEngine` 


<!-- Sent from Reviewable.io -->

2022-07-25 13:27 UTC, lukedirtwalker requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4232)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira)

___
*[`daemon/drkey/client_engine.go` line 126 at r2](https://reviewable.io/reviews/scionproto/scion/4232#-N7pXZJh7EAcAbYZJbrv:-N7pXZJh7EAcAbYZJbrw:b-e9e8l0) ([raw file](https://github.com/scionproto/scion/blob/7c5238819ece6c2b30a95fe6f3ceadfb961e540e/daemon/drkey/client_engine.go#L126)):*
> ```Go
> 	cleaners[0] = cleaner.New(func(ctx context.Context) (int, error) {
> 		return e.DB.DeleteExpiredASHostKeys(ctx, time.Now())
> 	}, "drkey_client_store")
> ```

let's have a different name for each cleaner, that will be easier to track down any issues.



_Code quote:_
```Go
"drkey_client_store"
```


<!-- Sent from Reviewable.io -->

2022-07-25 14:03 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4232)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[`daemon/drkey/client_engine.go` line 102 at r1](https://reviewable.io/reviews/scionproto/scion/4232#-N7oQCqV1TIXeR8U72kG:-N7peo1NBNZLXMzDaFLP:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/97402b8774d60e5bc05f8d06c934d3cbf09bb5a3/daemon/drkey/client_engine.go#L102)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

move this one line below
</blockquote></details>

Done.
___
*[`daemon/drkey/client_engine.go` line 126 at r2](https://reviewable.io/reviews/scionproto/scion/4232#-N7pXZJh7EAcAbYZJbrv:-N7peuMS6fKHxsjuxAh6:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/7c5238819ece6c2b30a95fe6f3ceadfb961e540e/daemon/drkey/client_engine.go#L126)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

let's have a different name for each cleaner, that will be easier to track down any issues.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-25 14:34 UTC, lukedirtwalker requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4232)* status: all files reviewed, 1 unresolved discussion (waiting on @JordiSubira)

___
*[`daemon/drkey/client_engine.go` line 102 at r1](https://reviewable.io/reviews/scionproto/scion/4232#-N7oQCqV1TIXeR8U72kG:-N7plqSF1S7QUta-D3VD:b2ni8op) ([raw file](https://github.com/scionproto/scion/blob/97402b8774d60e5bc05f8d06c934d3cbf09bb5a3/daemon/drkey/client_engine.go#L102)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no?


<!-- Sent from Reviewable.io -->

2022-07-25 15:05 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4232)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[`daemon/drkey/client_engine.go` line 102 at r1](https://reviewable.io/reviews/scionproto/scion/4232#-N7oQCqV1TIXeR8U72kG:-N7psy9g9ZVFS0_6uFEt:btgbv5i) ([raw file](https://github.com/scionproto/scion/blob/97402b8774d60e5bc05f8d06c934d3cbf09bb5a3/daemon/drkey/client_engine.go#L102)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

no?
</blockquote></details>

Now it should be Done.


<!-- Sent from Reviewable.io -->

2022-07-26 06:43 UTC, lukedirtwalker approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4232)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2022-07-26 07:19 UTC, JordiSubira reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4232)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2022-07-26 07:19 UTC, merged