ca-frontend: refactor renewal metrics
scionproto/scion pull request #4239
Opened 2022-07-29 13:01 UTC by Hygster

Refactor ca/renewal metrics to avoid ca-frontend exposing metrics that are of no use.

NO_RELEASE_NOTE

Fixes #6147

2022-08-02 09:19 UTC, lukedirtwalker requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4239)* status: all files reviewed, 16 unresolved discussions (waiting on @Hygster)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4239#-N8Skpo5BDuEreqv_RSw:-N8Skpo5BDuEreqv_RSx:b-en8ncr) (no related file):*
please delete `private/ca/renewal/metrics/signer.go` and the `Signer` variable in `private/ca/renewal/metrics/metrics.go`
Let's just drop the whole metrics package and just write the result values directly in the code instead of using the constants.

___
___
*[`control/observability.go` line 256 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SpJKX39HIsFHaUp1l:-N8SpJKX39HIsFHaUp1m:b-rsjpts) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/control/observability.go#L256)):*
> ```Go
> 			CaSigners: func(result string) metrics.Counter {
> 				return metrics.NewPromCounter(promauto.NewCounterVec(
> 					prometheus.CounterOpts{
> ```

Store the creation of the countervec in a separate variable so that we don't have to do allocations every time we use the function:
```go
func NewMetrics() *Metrics {
    renewalSigners := metrics.NewPromCounter(promauto.NewCounterVec(
					prometheus.CounterOpts{
						Name: "renewal_generated_signers_total",
						Help: "Number of generated CA signers that sign certificate chains",
					},
					[]string{prom.LabelResult},
				))
    ....
return &Metrics{
    ...
     RenewalMetrics: renewal.Metrics{
            CASigners: func(result string) metrics.Counter { return renewalSigners.With(result)
```



_Code quote:_
```Go
				return metrics.NewPromCounter(promauto.NewCounterVec(
					prometheus.CounterOpts{
						Name: "renewal_generated_signers_total",
						Help: "Number of generated CA signers that sign certificate chains",
					},
					[]string{prom.LabelResult},
				)).With(prom.LabelResult)
```
___
*[`control/observability.go` line 261 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8Sp3qj5PMNy_Ke3zLG:-N8Sp3qj5PMNy_Ke3zLH:b-yvo780) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/control/observability.go#L261)):*
> ```Go
> 					},
> 					[]string{prom.LabelResult},
> 				)).With(prom.LabelResult)
> ```

in the `With` clause you should insert the value of the label not the name of the label.

This comment also applies to the counters below.



_Suggestion:_
```Go
.With(result)
```
___
*[`control/trust.go` line 111 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SqGzMDTi6TDeGgOu1:-N8SqGzMDTi6TDeGgOu2:bowh0c5) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/control/trust.go#L111)):*
> ```Go
> }
> 
> type MetricsOption func(*metricsOption)
> ```

drop this again?
___
*[`control/trust.go` line 113 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SqIlXD8NebeJXn242:-N8SqIlXD8NebeJXn243:bowh0c5) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/control/trust.go#L113)):*
> ```Go
> type MetricsOption func(*metricsOption)
> 
> func WithRegistry(registry prometheus.Registerer) MetricsOption {
> ```

drop this again?
___
*[`control/trust.go` line 119 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SqJUV7AFNyHj5coHz:-N8SqJUV7AFNyHj5coI-:bowh0c5) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/control/trust.go#L119)):*
> ```Go
> }
> 
> type metricsOption struct {
> ```

drop this again?
___
*[`control/trust.go` line 125 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SqNfoBnIssL6kGVQA:-N8SqNfoBnIssL6kGVQB:bc7b6ze) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/control/trust.go#L125)):*
> ```Go
> // NewChainBuilder creates a renewing chain builder.
> func NewChainBuilder(cfg ChainBuilderConfig) renewal.ChainBuilder {
> 	m := NewMetrics().RenewalMetrics
> ```

NewMetrics should only be called once in the main, and from there everything should take the value, you need to pass the metrics here, optimally in the Config struct.



_Code quote:_
```Go
NewMetrics()
```
___
*[`control/trust.go` line 149 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SqDkF0l1mOlhSZAZC:-N8SqDkG7H4ORSMEm2lh:b-l6mwxj) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/control/trust.go#L149)):*
> ```Go
> }
> 
> // func NewRenewalMetrics(opts ...MetricsOption) *renewal.Metrics {
> ```

remove
___
*[`private/ca/renewal/ca_signer_gen.go` line 44 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SmQq18095noivFjno:-N8SmQq18095noivFjnp:byzvsj7) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/private/ca/renewal/ca_signer_gen.go#L44)):*
> ```Go
> )
> 
> type Metrics struct {
> ```

for all fields please add a doc string what the metrics are used for.
___
*[`private/ca/renewal/ca_signer_gen.go` line 45 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SlqFm1_4pOChLQ0tz:-N8SlqFm1_4pOChLQ0u-:b-nazwhu) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/private/ca/renewal/ca_signer_gen.go#L45)):*
> ```Go
> 
> type Metrics struct {
> 	CaActive        func(string) metrics.Gauge
> ```

This doesn't take any label at all, the metric that you created in `obersvability.go` doesn't have any label, why is it a function?



_Suggestion:_
```Go
CAActive        metrics.Gauge
```
___
*[`private/ca/renewal/ca_signer_gen.go` line 48 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SmJft4__MP8ljqfkt:-N8SmJft4__MP8ljqfku:b5p0nsn) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/private/ca/renewal/ca_signer_gen.go#L48)):*
> ```Go
> 	CaSigners       func(string) metrics.Counter
> 	SignedChains    func(string) metrics.Counter
> 	LastGeneratedCA func(string) metrics.Gauge
> ```

this doesn't take a label.



_Suggestion:_
```Go
LastGeneratedCA metrics.Gauge
```
___
*[`private/ca/renewal/ca_signer_gen.go` line 49 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SmW1d0taaS54wCjdn:-N8SmW1d0taaS54wCjdo:bfq183z) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/private/ca/renewal/ca_signer_gen.go#L49)):*
> ```Go
> 	SignedChains    func(string) metrics.Counter
> 	LastGeneratedCA func(string) metrics.Gauge
> 	ExpirationCA    func(string) metrics.Gauge
> ```

doesn't take a label.



_Suggestion:_
```Go
ExpirationCA    metrics.Gauge
```
___
*[`private/ca/renewal/ca_signer_gen.go` line 117 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SmwEb9obgT7snrLUx:-N8SmwEc4xd6jBvi9XHe:bu20rpb) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/private/ca/renewal/ca_signer_gen.go#L117)):*
> ```Go
> 		log.FromCtx(ctx).Info("Failed to generate a new CA policy, "+
> 			"AS certificate signing not possible", "err", err)
> 		s.CaActive("active_ca").Set(0)
> ```

always use the `metrics.GaugeSet()` helper.
___
*[`private/ca/renewal/ca_signer_gen.go` line 128 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SmoMQEqDrKwGD6yXW:-N8SmoMQEqDrKwGD6yXX:bu20rpb) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/private/ca/renewal/ca_signer_gen.go#L128)):*
> ```Go
> 	s.cached, s.ok = policy, true
> 
> 	s.CaActive("active_ca").Set(1)
> ```

always use the `metrics.GaugeSet()` helper.
___
*[`private/ca/renewal/ca_signer_gen.go` line 129 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SmypBChgmJk6jLyPw:-N8SmypBChgmJk6jLyPx:b-4xx7p0) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/private/ca/renewal/ca_signer_gen.go#L129)):*
> ```Go
> 
> 	s.CaActive("active_ca").Set(1)
> 	s.LastGeneratedCA("last_generat [...]

2022-08-03 11:06 UTC, Hygster reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4239)* status: 0 of 9 files reviewed, 16 unresolved discussions (waiting on @lukedirtwalker)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4239#-N8Skpo5BDuEreqv_RSw:-N8XNmJ2DlIUJTt-BoIz:b-896fix) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

please delete `private/ca/renewal/metrics/signer.go` and the `Signer` variable in `private/ca/renewal/metrics/metrics.go`
Let's just drop the whole metrics package and just write the result values directly in the code instead of using the constants.
</blockquote></details>

Done.

___
___
*[`control/observability.go` line 256 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SpJKX39HIsFHaUp1l:-N8XcK4OElYuHo32r86I:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/control/observability.go#L256)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Store the creation of the countervec in a separate variable so that we don't have to do allocations every time we use the function:
```go
func NewMetrics() *Metrics {
    renewalSigners := metrics.NewPromCounter(promauto.NewCounterVec(
					prometheus.CounterOpts{
						Name: "renewal_generated_signers_total",
						Help: "Number of generated CA signers that sign certificate chains",
					},
					[]string{prom.LabelResult},
				))
    ....
return &Metrics{
    ...
     RenewalMetrics: renewal.Metrics{
            CASigners: func(result string) metrics.Counter { return renewalSigners.With(result)
```
</blockquote></details>

Done.
___
*[`control/observability.go` line 261 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8Sp3qj5PMNy_Ke3zLG:-N8Xcqod42o4I0lh5JHV:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/control/observability.go#L261)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

in the `With` clause you should insert the value of the label not the name of the label.

This comment also applies to the counters below.
</blockquote></details>

Done.
___
*[`control/trust.go` line 111 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SqGzMDTi6TDeGgOu1:-N8Xd1DC7oe4kv1mChOx:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/control/trust.go#L111)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

drop this again?
</blockquote></details>

Done.
___
*[`control/trust.go` line 113 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SqIlXD8NebeJXn242:-N8Xd1U71TWo7hOirCo9:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/control/trust.go#L113)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

drop this again?
</blockquote></details>

Done.
___
*[`control/trust.go` line 119 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SqJUV7AFNyHj5coHz:-N8Xd5F0E-P0U8Jl1Iu2:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/control/trust.go#L119)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

drop this again?
</blockquote></details>

Done.
___
*[`control/trust.go` line 125 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SqNfoBnIssL6kGVQA:-N8Y3dAh8AC_w8qdU4kp:bb6un1j) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/control/trust.go#L125)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

NewMetrics should only be called once in the main, and from there everything should take the value, you need to pass the metrics here, optimally in the Config struct.
</blockquote></details>

Done
___
*[`control/trust.go` line 149 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SqDkF0l1mOlhSZAZC:-N8Xd6l09FnrUrwQkDQw:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/control/trust.go#L149)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 44 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SmQq18095noivFjno:-N8XwiHJ9MKIDix4Xb1A:bb6un1j) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/private/ca/renewal/ca_signer_gen.go#L44)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

for all fields please add a doc string what the metrics are used for.
</blockquote></details>

Done
___
*[`private/ca/renewal/ca_signer_gen.go` line 45 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SlqFm1_4pOChLQ0tz:-N8XhyaX89GqwiRCzSTu:bdoh2ti) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/private/ca/renewal/ca_signer_gen.go#L45)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

This doesn't take any label at all, the metric that you created in `obersvability.go` doesn't have any label, why is it a function?
</blockquote></details>

I see, that didn't make sense. Done
___
*[`private/ca/renewal/ca_signer_gen.go` line 48 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SmJft4__MP8ljqfkt:-N8XfyRN8ERpQXP9Kya0:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/private/ca/renewal/ca_signer_gen.go#L48)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

this doesn't take a label.
</blockquote></details>

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 49 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SmW1d0taaS54wCjdn:-N8Xfy2-2Ja9MC2-FIoN:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/private/ca/renewal/ca_signer_gen.go#L49)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

doesn't take a label.
</blockquote></details>

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 117 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SmwEb9obgT7snrLUx:-N8Xk0ERBp7Vg5u8iNoV:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/private/ca/renewal/ca_signer_gen.go#L117)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

always use the `metrics.GaugeSet()` helper.
</blockquote></details>

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 128 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SmoMQEqDrKwGD6yXW:-N8Xk9hy203eg_RxjNIk:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/private/ca/renewal/ca_signer_gen.go#L128)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

always use the `metrics.GaugeSet()` helper.
</blockquote></details>

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 129 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8SmypBChgmJk6jLyPw:-N8XkA6t4mMwtfHqWhhM:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9765412740272dc9fe244adc315e439a542aa22c/private/ca/renewal/ca_signer_gen.go#L129)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

use metrics helper (`metrics.GaugeSetCurrentTime`)
</blockquote></details>

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 130 at r1](https://reviewable.io/reviews/scionproto/scion/4239#-N8Sn-ggCwz7_gkELTmH:-N8XkAUq1NCOiOLLhQlE:b-8 [...]

2022-08-04 08:38 UTC, lukedirtwalker requested changes
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4239)* status: all files reviewed, 9 unresolved discussions (waiting on @Hygster)

___
*[`control/cmd/control/main.go` line 405 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8c-9pJEu5aHXVpZvb9:-N8c-9pJEu5aHXVpZvbA:undefined) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/control/cmd/control/main.go#L405)):*
> ```Go
> 					MaxValidity: globalCfg.CA.MaxASValidity.Duration,
> 					ConfigDir:   globalCfg.General.ConfigDir,
> 					Metrics: renewal.Metrics{
> ```





_Suggestion:_
```Go
					Metrics:              metrics.RenewalMetrics,
```
___
*[`private/ca/renewal/ca_signer_gen.go` line 45 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8byBfA3pKz5cXjNWtw:-N8byBfA3pKz5cXjNWtx:undefined) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L45)):*
> ```Go
> 
> type Metrics struct {
> 	// CAActive describes whether or not setting the new CA policy was
> ```





_Suggestion:_
```Go
	// CAActive describes whether the CA signer is active and can sign certificate chains.
```
___
*[`private/ca/renewal/ca_signer_gen.go` line 48 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8byFFF28nhFOMeqKro:-N8byFFF28nhFOMeqKrp:undefined) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L48)):*
> ```Go
> 	// successful with 1 indicating success and o indicating fail.
> 	CAActive metrics.Gauge
> 	// CASigners tracks the status of the certificate signing process.
> ```





_Suggestion:_
```Go
// CASigners tracks the number of generated CA signers that sign certificate chains.
```
___
*[`private/ca/renewal/ca_signer_gen.go` line 50 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8bxB_00cUwqh6THcj0:-N8bxB_00cUwqh6THcj1:undefined) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L50)):*
> ```Go
> 	// CASigners tracks the status of the certificate signing process.
> 	CASigners func(string) metrics.Counter
> 	// SignedChains tracks the status of the certificate chain generation
> ```





_Suggestion:_
```Go
	// SignedChains tracks the number of certificate chains signed, labeled by the status of the signing.
```
___
*[`private/ca/renewal/ca_signer_gen.go` line 53 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8bxy2Q8aA-HWLOb9zk:-N8bxy2Q8aA-HWLOb9zl:undefined) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L53)):*
> ```Go
> 	// process.
> 	SignedChains func(string) metrics.Counter
> 	// LastGeneratedCA exports the time of the last generation of the CA policy.
> ```





_Suggestion:_
```Go
// LastGeneratedCA exports the last time a signer for creating AS certificates was successfully generated.
```
___
*[`private/ca/renewal/ca_signer_gen.go` line 55 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8bxoEY2PcYqPixb31v:-N8bxoEY2PcYqPixb31w:undefined) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L55)):*
> ```Go
> 	// LastGeneratedCA exports the time of the last generation of the CA policy.
> 	LastGeneratedCA metrics.Gauge
> 	// ExpirationCA exports the expiration of the most recently generated CA
> ```





_Suggestion:_
```Go
	// ExpirationCA exports the expiration time of the current CA signer.
```
___
*[`private/ca/renewal/ca_signer_gen.go` line 77 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8bzYzf2BRaD6rBvfzY:-N8bzYzf2BRaD6rBvfzZ:bah2kn2) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L77)):*
> ```Go
> 	policy, err := c.PolicyGen.Generate(ctx)
> 	if err != nil {
> 		metrics.CounterInc(c.SignedChains("err_inactive"))
> ```

this is not safe if the method is not set, use `c.incSignedChains("err_inactive")` instead and define:
```go
func (c ChainBuilder) incSignedChains(result string) {
	if c.SignedChains != nil {
		metrics.CounterInc(c.SignedChains(result))
	}
}
```
___
*[`private/ca/renewal/ca_signer_gen.go` line 82 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8byNuq4-w1LT1Y5n-z:-N8byNuq4-w1LT1Y5n0-:b-pd6ln3) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L82)):*
> ```Go
> 	chain, err := policy.CreateChain(csr)
> 	if err != nil {
> 		metrics.CounterInc(c.SignedChains(prom.ErrInternal))
> ```

let's not use the `prom` package anymore here in this file, instead just write the strings.



_Code quote:_
```Go
prom.ErrInternal
```
___
*[`private/ca/renewal/ca_signer_gen.go` line 174 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8bznei0sUH_w5XC7-h:-N8bznei0sUH_w5XC7-i:b-afn2hu) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L174)):*
> ```Go
> 	keys, err := g.KeyRing.PrivateKeys(ctx)
> 	if err != nil {
> 		metrics.CounterInc(g.CASigners("err_key"))
> ```

here also handle a possibly `nil` CASigners function.


<!-- Sent from Reviewable.io -->

2022-08-04 14:01 UTC, Hygster reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4239)* status: 6 of 9 files reviewed, 9 unresolved discussions (waiting on @lukedirtwalker)

___
*[`control/cmd/control/main.go` line 405 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8c-9pJEu5aHXVpZvb9:-N8d3x5vChv6Hx48VQ5f:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/control/cmd/control/main.go#L405)):*
> ```Go
> 					MaxValidity: globalCfg.CA.MaxASValidity.Duration,
> 					ConfigDir:   globalCfg.General.ConfigDir,
> 					Metrics: renewal.Metrics{
> ```

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 45 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8byBfA3pKz5cXjNWtw:-N8d4JY39iIAVXZZQQE4:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L45)):*
> ```Go
> 
> type Metrics struct {
> 	// CAActive describes whether or not setting the new CA policy was
> ```

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 48 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8byFFF28nhFOMeqKro:-N8d4R0OB75tlprzMLQi:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L48)):*
> ```Go
> 	// successful with 1 indicating success and o indicating fail.
> 	CAActive metrics.Gauge
> 	// CASigners tracks the status of the certificate signing process.
> ```

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 50 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8bxB_00cUwqh6THcj0:-N8d4Yt03IrkZIMlyjNN:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L50)):*
> ```Go
> 	// CASigners tracks the status of the certificate signing process.
> 	CASigners func(string) metrics.Counter
> 	// SignedChains tracks the status of the certificate chain generation
> ```

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 53 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8bxy2Q8aA-HWLOb9zk:-N8d4hlD5Xug70XkJ-NC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L53)):*
> ```Go
> 	// process.
> 	SignedChains func(string) metrics.Counter
> 	// LastGeneratedCA exports the time of the last generation of the CA policy.
> ```

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 55 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8bxoEY2PcYqPixb31v:-N8d51Z2AdS7wnqUne0b:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L55)):*
> ```Go
> 	// LastGeneratedCA exports the time of the last generation of the CA policy.
> 	LastGeneratedCA metrics.Gauge
> 	// ExpirationCA exports the expiration of the most recently generated CA
> ```

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 77 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8bzYzf2BRaD6rBvfzY:-N8d6pnK8bRk33GfsDOh:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L77)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

this is not safe if the method is not set, use `c.incSignedChains("err_inactive")` instead and define:
```go
func (c ChainBuilder) incSignedChains(result string) {
	if c.SignedChains != nil {
		metrics.CounterInc(c.SignedChains(result))
	}
}
```
</blockquote></details>

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 82 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8byNuq4-w1LT1Y5n-z:-N8d7xws-0R5MIzitMgU:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L82)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

let's not use the `prom` package anymore here in this file, instead just write the strings.
</blockquote></details>

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 174 at r2](https://reviewable.io/reviews/scionproto/scion/4239#-N8bznei0sUH_w5XC7-h:-N8d8r497-ACXwyxE_i5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1be6609472ff7b363dbb98527a34dd818545ac15/private/ca/renewal/ca_signer_gen.go#L174)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

here also handle a possibly `nil` CASigners function.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-05 06:24 UTC, lukedirtwalker requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4239)* status: all files reviewed, 5 unresolved discussions (waiting on @Hygster)

___
*[`private/ca/renewal/ca_signer_gen.go` line 82 at r3](https://reviewable.io/reviews/scionproto/scion/4239#-N8gem6Y47xdr_ry1yqX:-N8gem6Y47xdr_ry1yqY:bdp5xt3) ([raw file](https://github.com/scionproto/scion/blob/72a2dab929f35fd744c2667ea02a292d01d342ce/private/ca/renewal/ca_signer_gen.go#L82)):*
> ```Go
> 	chain, err := policy.CreateChain(csr)
> 	if err != nil {
> 		metrics.CounterInc(c.SignedChains("prom.ErrInternal"))
> ```

incSignedChains
___
*[`private/ca/renewal/ca_signer_gen.go` line 82 at r3](https://reviewable.io/reviews/scionproto/scion/4239#-N8gesFh9ZhLJvKHvO06:-N8gesFi-0IWShr9rf1u:b-cfft03) ([raw file](https://github.com/scionproto/scion/blob/72a2dab929f35fd744c2667ea02a292d01d342ce/private/ca/renewal/ca_signer_gen.go#L82)):*
> ```Go
> 	chain, err := policy.CreateChain(csr)
> 	if err != nil {
> 		metrics.CounterInc(c.SignedChains("prom.ErrInternal"))
> ```

I think we misunderstood, I wanted to put the value of the variable, not the name of it ;) 



_Suggestion:_
```Go
err_internal
```
___
*[`private/ca/renewal/ca_signer_gen.go` line 85 at r3](https://reviewable.io/reviews/scionproto/scion/4239#-N8geoKB9UcGA1XE9oQF:-N8geoKB9UcGA1XE9oQG:bdp5xt3) ([raw file](https://github.com/scionproto/scion/blob/72a2dab929f35fd744c2667ea02a292d01d342ce/private/ca/renewal/ca_signer_gen.go#L85)):*
> ```Go
> 		return nil, err
> 	}
> 	metrics.CounterInc(c.SignedChains("prom.Success"))
> ```

incSignedChains
___
*[`private/ca/renewal/ca_signer_gen.go` line 85 at r3](https://reviewable.io/reviews/scionproto/scion/4239#-N8gf1DdEM6wFybkqmuR:-N8gf1DdEM6wFybkqmuS:undefined) ([raw file](https://github.com/scionproto/scion/blob/72a2dab929f35fd744c2667ea02a292d01d342ce/private/ca/renewal/ca_signer_gen.go#L85)):*
> ```Go
> 		return nil, err
> 	}
> 	metrics.CounterInc(c.SignedChains("prom.Success"))
> ```





_Suggestion:_
```Go
ok_success
```
___
*[`private/ca/renewal/ca_signer_gen.go` line 220 at r3](https://reviewable.io/reviews/scionproto/scion/4239#-N8gf4RK5VTnlQvrymrt:-N8gf4RK5VTnlQvrymru:undefined) ([raw file](https://github.com/scionproto/scion/blob/72a2dab929f35fd744c2667ea02a292d01d342ce/private/ca/renewal/ca_signer_gen.go#L220)):*
> ```Go
> 			"num_private_keys", len(keys))
> 	}
> 	l.incCASigner("prom.Success")
> ```





_Suggestion:_
```Go
ok_success
```


<!-- Sent from Reviewable.io -->

2022-08-08 07:07 UTC, Hygster commented
*[`private/ca/renewal/ca_signer_gen.go` line 82 at r3](https://reviewable.io/reviews/scionproto/scion/4239#-N8gesFh9ZhLJvKHvO06:-N8wBJ04ESty_9_gKdX7:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/72a2dab929f35fd744c2667ea02a292d01d342ce/private/ca/renewal/ca_signer_gen.go#L82)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I think we misunderstood, I wanted to put the value of the variable, not the name of it ;) 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-08 07:19 UTC, lukedirtwalker reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4239)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Hygster)



<!-- Sent from Reviewable.io -->

2022-08-08 07:19 UTC, lukedirtwalker approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Hygster)



<!-- Sent from Reviewable.io -->

2022-08-08 07:41 UTC, Hygster reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4239)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @lukedirtwalker)

___
*[`private/ca/renewal/ca_signer_gen.go` line 82 at r3](https://reviewable.io/reviews/scionproto/scion/4239#-N8gem6Y47xdr_ry1yqX:-N8wB4UdDJwGd9ji3pYl:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/72a2dab929f35fd744c2667ea02a292d01d342ce/private/ca/renewal/ca_signer_gen.go#L82)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

incSignedChains
</blockquote></details>

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 82 at r3](https://reviewable.io/reviews/scionproto/scion/4239#-N8gesFh9ZhLJvKHvO06:-N8wGpob8Pyb9_MzX-qO:b-y0r93s) ([raw file](https://github.com/scionproto/scion/blob/72a2dab929f35fd744c2667ea02a292d01d342ce/private/ca/renewal/ca_signer_gen.go#L82)):*
<details><summary><i>Previously, Hygster (August Rønberg) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually, it turns out that CI complains about this:
private/ca/renewal/ca_signer_gen.go:82:39: c.incSignedChains("err_internal") used as value
private/ca/renewal/ca_signer_gen.go:85:38: c.incSignedChains("ok_success") used as value
___
*[`private/ca/renewal/ca_signer_gen.go` line 85 at r3](https://reviewable.io/reviews/scionproto/scion/4239#-N8geoKB9UcGA1XE9oQF:-N8wBLvF1iZIKPYqSlko:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/72a2dab929f35fd744c2667ea02a292d01d342ce/private/ca/renewal/ca_signer_gen.go#L85)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

incSignedChains
</blockquote></details>

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 85 at r3](https://reviewable.io/reviews/scionproto/scion/4239#-N8gf1DdEM6wFybkqmuR:-N8wBMDxDBdJANb9Fm0m:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/72a2dab929f35fd744c2667ea02a292d01d342ce/private/ca/renewal/ca_signer_gen.go#L85)):*
> ```Go
> 		return nil, err
> 	}
> 	metrics.CounterInc(c.SignedChains("prom.Success"))
> ```

Done.
___
*[`private/ca/renewal/ca_signer_gen.go` line 220 at r3](https://reviewable.io/reviews/scionproto/scion/4239#-N8gf4RK5VTnlQvrymrt:-N8wBM_J3-xSvqo5AsVw:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/72a2dab929f35fd744c2667ea02a292d01d342ce/private/ca/renewal/ca_signer_gen.go#L220)):*
> ```Go
> 			"num_private_keys", len(keys))
> 	}
> 	l.incCASigner("prom.Success")
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-08-08 09:22 UTC, lukedirtwalker requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4239)* status: all files reviewed, 1 unresolved discussion (waiting on @Hygster)

___
*[`private/ca/renewal/ca_signer_gen.go` line 221 at r6](https://reviewable.io/reviews/scionproto/scion/4239#-N8wkjW105lgMGwbsWm3:-N8wkjW105lgMGwbsWm4:b-8g3a26) ([raw file](https://github.com/scionproto/scion/blob/69d8bf8ab14ab008039971b68536901e24a8c3c4/private/ca/renewal/ca_signer_gen.go#L221)):*
> ```Go
> 			"num_private_keys", len(keys))
> 	}
> 	l.incCASigner(prom.Success)
> ```

please make sure that we don't have a depency on `prom` anymore, replace the variables with the string content as before.



_Code quote:_
```Go
prom.
```


<!-- Sent from Reviewable.io -->

2022-08-08 12:14 UTC, Hygster reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4239)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[`private/ca/renewal/ca_signer_gen.go` line 221 at r6](https://reviewable.io/reviews/scionproto/scion/4239#-N8wkjW105lgMGwbsWm3:-N8xN6SG31rJL5-RbKpP:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/69d8bf8ab14ab008039971b68536901e24a8c3c4/private/ca/renewal/ca_signer_gen.go#L221)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

please make sure that we don't have a depency on `prom` anymore, replace the variables with the string content as before.
</blockquote></details>

Done.



_Code quote:_
```Go
"ok_success"
```


<!-- Sent from Reviewable.io -->

2022-08-09 05:36 UTC, lukedirtwalker approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Hygster)



<!-- Sent from Reviewable.io -->

2022-08-09 05:40 UTC, merged