scion-pki/key: add command to calculate SubjectKeyID
scionproto/scion pull request #4253
Opened 2022-09-12 12:41 UTC by bunert

Add the ```scion-pki key fingerprint <key-file>``` sub-command to compute the SubjectKeyID of a public key. For a given private key, the SubjectKeyID is calculated on the corresponding public key. For certificates and certificate chains, the SubjectKeyID is calculated for the public key of the first certificate.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4253)

2022-09-26 06:57 UTC, matzf reviewed
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4253)* status: all files reviewed, 3 unresolved discussions (waiting on @bunert)

___
*[`scion-pki/key/fingerprint.go` line 56 at r1](https://reviewable.io/reviews/scionproto/scion/4253#-NCsX0q21wy4fzvUy3iZ:-NCsX0q21wy4fzvUy3i_:b-nv0nu4) ([raw file](https://github.com/scionproto/scion/blob/88c604c0f1901e14d2dc67f9e675f4015cd54a86/scion-pki/key/fingerprint.go#L56)):*
> ```Go
> in the file.
> 
> The subject key id is written to standard out.
> ```

To me this description suggested that this shows "the fingerprint of the subject key id of a public key", which rather confused me. I believe "subject key id" is just a specific name for this fingerprint of the public key.  Perhaps this could be reworded a bit to make this clearer.

Similarly, the description of the "full-key-digest" leaves me wondering what the difference is to the other digest type is.

Btw., I've just had a look at the description of (`step crypto key fingerprint`)[https://smallstep.com/docs/step-cli/reference/crypto/key/fingerprint], which seems a bit clearer on these points (assuming this really is the equivalent command).
___
*[`scion-pki/key/fingerprint.go` line 60 at r1](https://reviewable.io/reviews/scionproto/scion/4253#-NCULJw_3GtDRwwAXmBP:-NCULJw_3GtDRwwAXmBQ:b-cm09fb) ([raw file](https://github.com/scionproto/scion/blob/88c604c0f1901e14d2dc67f9e675f4015cd54a86/scion-pki/key/fingerprint.go#L60)):*
> ```Go
> 		Args: cobra.ExactArgs(1),
> 		RunE: func(cmd *cobra.Command, args []string) error {
> 			cmd.SilenceUsage = true
> ```

Nit. With a wrong `format` option, the help text will not be shown. Not sure if this is good or bad, but it's different from `scion-pki certificate fingerprint`.
___
*[`scion-pki/key/fingerprint.go` line 145 at r1](https://reviewable.io/reviews/scionproto/scion/4253#-NCULUjB0cmpZngBLUgB:-NCULUjCCLckzL8Nlj36:b-f2hu3l) ([raw file](https://github.com/scionproto/scion/blob/88c604c0f1901e14d2dc67f9e675f4015cd54a86/scion-pki/key/fingerprint.go#L145)):*
> ```Go
> 
> // encodeSubjectKeyID encodes the subject key id in provided format:
> // hex, base64, base64-url, base64-raw, base64-url-raw, emoji
> ```

Should the same formatting options also be added to `scion-pki certificate fingerprint`, e.g. by moving this into the `encoding` package?


<!-- Sent from Reviewable.io -->

2022-09-26 10:05 UTC, bunert reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4253)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf)

___
*[`scion-pki/key/fingerprint.go` line 56 at r1](https://reviewable.io/reviews/scionproto/scion/4253#-NCsX0q21wy4fzvUy3iZ:-NCt2xp-3JGWwBVlVvu5:betqpgh) ([raw file](https://github.com/scionproto/scion/blob/88c604c0f1901e14d2dc67f9e675f4015cd54a86/scion-pki/key/fingerprint.go#L56)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

To me this description suggested that this shows "the fingerprint of the subject key id of a public key", which rather confused me. I believe "subject key id" is just a specific name for this fingerprint of the public key.  Perhaps this could be reworded a bit to make this clearer.

Similarly, the description of the "full-key-digest" leaves me wondering what the difference is to the other digest type is.

Btw., I've just had a look at the description of (`step crypto key fingerprint`)[https://smallstep.com/docs/step-cli/reference/crypto/key/fingerprint], which seems a bit clearer on these points (assuming this really is the equivalent command).
</blockquote></details>

I adapted the description and tried to fix the confusion about the full-key-digest flag. Now the description should be formulated consistently to avoid confusion.
___
*[`scion-pki/key/fingerprint.go` line 60 at r1](https://reviewable.io/reviews/scionproto/scion/4253#-NCULJw_3GtDRwwAXmBP:-NCt5PNtDbelvSAFjCuN:b4i3w9v) ([raw file](https://github.com/scionproto/scion/blob/88c604c0f1901e14d2dc67f9e675f4015cd54a86/scion-pki/key/fingerprint.go#L60)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit. With a wrong `format` option, the help text will not be shown. Not sure if this is good or bad, but it's different from `scion-pki certificate fingerprint`.
</blockquote></details>

Now similar to `scion-pki certificate fingerprint`.
___
*[`scion-pki/key/fingerprint.go` line 145 at r1](https://reviewable.io/reviews/scionproto/scion/4253#-NCULUjB0cmpZngBLUgB:-NCtF6MW4cPF4hv8ZFcC:be1o0t6) ([raw file](https://github.com/scionproto/scion/blob/88c604c0f1901e14d2dc67f9e675f4015cd54a86/scion-pki/key/fingerprint.go#L145)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Should the same formatting options also be added to `scion-pki certificate fingerprint`, e.g. by moving this into the `encoding` package?
</blockquote></details>

Yeah good point, adjusted it.


<!-- Sent from Reviewable.io -->

2022-09-27 13:54 UTC, matzf approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4253)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bunert)

___
*[`scion-pki/key/fingerprint.go` line 56 at r1](https://reviewable.io/reviews/scionproto/scion/4253#-NCsX0q21wy4fzvUy3iZ:-NCy9Dwd4tOJrWxCzRDw:bmi8ppe) ([raw file](https://github.com/scionproto/scion/blob/88c604c0f1901e14d2dc67f9e675f4015cd54a86/scion-pki/key/fingerprint.go#L56)):*
<details><summary><i>Previously, bunert wrote…</i></summary><blockquote>

I adapted the description and tried to fix the confusion about the full-key-digest flag. Now the description should be formulated consistently to avoid confusion.
</blockquote></details>

:100: 


<!-- Sent from Reviewable.io -->

2022-09-28 08:09 UTC, oncilla requested changes
> Reviewed 5 of 6 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4253)* status: all files reviewed, 14 unresolved discussions (waiting on @bunert)

___
*[`scion-pki/certs/fingerprint.go` line 51 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND25DVT2qkDbHTcqasH:-ND25DVT2qkDbHTcqasI:b-lut0p6) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/certs/fingerprint.go#L51)):*
> ```Go
> 		Args: cobra.ExactArgs(1),
> 		RunE: func(cmd *cobra.Command, args []string) error {
> 			err := encoding.CheckEncodings(flags.format)
> ```

Always inline the assignment in the if statements when possible.
This reduces the scope of the error variable and makes referencing the wrong variable by mistake harder to do.



_Suggestion:_
```Go
			if err := encoding.CheckEncodings(flags.format); err != nil {
				return err
			}
```
___
*[`scion-pki/encoding/encoding.go` line 14 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND24tgU1xx-EbyVzFvz:-ND24tgU1xx-EbyVzFw-:b-ezipn0) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/encoding/encoding.go#L14)):*
> ```Go
> // See the License for the specific language governing permissions and
> // limitations under the License.
> package encoding
> ```

Add a new line between the license header and the package declaration.
Otherwise, godoc will recognize this as the package doc comment.
___
*[`scion-pki/encoding/encoding.go` line 24 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND254GyBBIGPXVkhQhe:-ND254GyBBIGPXVkhQhf:b-tn4og6) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/encoding/encoding.go#L24)):*
> ```Go
> )
> 
> func CheckEncodings(format string) error {
> ```

Add a doc comment.
___
*[`scion-pki/key/fingerprint.go` line 34 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND25_S8ALCVFgkLFfW_:-ND25_S8ALCVFgkLFfWa:undefined) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L34)):*
> ```Go
> 
> // NewFingerprintCmd returns a cobra command that returns the subject key id of a
> // public key. If a private key is given, the subject key id is computed for the
> ```





_Suggestion:_
```Go
// NewFingerprintCmd returns a cobra command that returns the subject key ID of a
// public key. If a private key is given, the subject key ID is computed for the
// corresponding public key. For certificated or certificates chains, the subject
// key ID is computed with respect to the public key of the first certificate in the file.
```
___
*[`scion-pki/key/fingerprint.go` line 53 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND25klEDZCXjcxblr0o:-ND25klF94S-OZxE1ue9:undefined) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L53)):*
> ```Go
> in the file.
> 
> By default the fingerprint calculated is SHA-1 hash of the marshaled public key defined in
> ```





_Suggestion:_
```Go
By default the fingerprint calculated is SHA-1 hash of the marshaled public key as defined in
https://tools.ietf.org/html/rfc5280#section-4.2.1.2 (1). With the '--full-key-digest' flag,
the computed fingerprint is the SHA-1 hash with ASN.1 DER-encoded subjectPublicKey.
```
___
*[`scion-pki/key/fingerprint.go` line 57 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND25zXO1D0qoSkTa6r4:-ND25zXO1D0qoSkTa6r5:undefined) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L57)):*
> ```Go
> the computed fingerprint is the SHA-1 hash with ASN.1 DER-encoded subjectPublicKey.
> 
> The subject key id is written to standard out.
> ```





_Suggestion:_
```Go
ID
```
___
*[`scion-pki/key/fingerprint.go` line 88 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND269n_C3THlhS4cpBi:-ND269n_C3THlhS4cpBj:undefined) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L88)):*
> ```Go
> 			output, err := encoding.EncodeBytes(skid, flags.format)
> 			if err != nil {
> 				return serrors.WrapStr("encoding subject key id", err)
> ```





_Suggestion:_
```Go
ID"
```
___
*[`scion-pki/key/fingerprint.go` line 104 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND26FSc2NbgOjVflzcJ:-ND26FSc2NbgOjVflzcK:b9jlscy) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L104)):*
> ```Go
> 
> // LoadPublicKey loads the public key from file and distinguishes what type of key it is.
> func LoadPublicKey(filename string) (crypto.PublicKey, error) {
> ```

This does not appear to be used anywhere else. Make it private.

Be vigilant when extending the API surface of a package. You will enter a contract that you will need to support that function for ever.
Changing or removing it will be considered a breaking change.

Once we need it somewhere else, we can always make it public.
___
*[`scion-pki/key/fingerprint.go` line 107 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND27VN949fHjHTvfxTh:-ND27VN949fHjHTvfxTi:undefined) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L107)):*
> ```Go
> 	raw, err := os.ReadFile(filename)
> 	if err != nil {
> 		return nil, serrors.WrapStr("reading input key", err)
> ```





_Suggestion:_
```Go
reading input file
```
___
*[`scion-pki/key/fingerprint.go` line 122 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND27dca8SLFzhzZFDrp:-ND27dca8SLFzhzZFDrq:undefined) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L122)):*
> ```Go
> 		pub, ok := key.(crypto.Signer)
> 		if !ok {
> 			return nil, serrors.New("cannot get public key from private key",
> ```





_Suggestion:_
```Go
unsupported private key type
```
___
*[`scion-pki/key/fingerprint.go` line 136 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND27RKw8OLjALMrcYu4:-ND27RKw8OLjALMrcYu5:undefined) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L136)):*
> ```Go
> 		cert, err := x509.ParseCertificate(block.Bytes)
> 		if err != nil {
> 			return nil, serrors.WrapStr("error parsing certificate", err)
> ```





_Suggestion:_
```Go
parsing certificate
```
___
*[`scion-pki/key/fingerprint.go` line 141 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND27I9W18fV535K7vbM:-ND27I9W18fV535K7vbN:undefined) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L141)):*
> ```Go
> 	default:
> 		return nil, serrors.New(
> 			"file is not a valid PEM encoding of a private/public key or certificate", "type",
> ```





_Suggestion:_
```Go
		return nil, serrors.New("unsupported PEM block", "type", block.Type)
```
___
*[`scion-pki/key/fingerprint_test.go` line 132 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND2863WCATwBbtls6Aq:-ND2863WCATwBbtls6Ar:b-spnqsf) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint_test.go#L132)):*
> ```Go
> 			cmd := key.NewFingerprintCmd(command.StringPather("test"))
> 
> 			// TODO: fullkeydigest flag
> ```

Drop the todo
___
*[`scion-pki/key/fingerprint_test.go` line 149 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND284Rl2PFukVEDj1xJ:-ND284Rl2PFukVEDj1xK:b-vyo32p) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint_test.go#L149)):*
> ```Go
> 		})
> 	}
> ```

drop the new line


<!-- Sent from Reviewable.io -->

2022-09-28 08:54 UTC, bunert reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4253)* status: all files reviewed, 14 unresolved discussions (waiting on @oncilla)

___
*[`scion-pki/certs/fingerprint.go` line 51 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND25DVT2qkDbHTcqasH:-ND2G1tWBPre_6A9Izq0:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/certs/fingerprint.go#L51)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Always inline the assignment in the if statements when possible.
This reduces the scope of the error variable and makes referencing the wrong variable by mistake harder to do.
</blockquote></details>

Done.
___
*[`scion-pki/encoding/encoding.go` line 14 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND24tgU1xx-EbyVzFvz:-ND2GmoyAduB2QLaTnzm:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/encoding/encoding.go#L14)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Add a new line between the license header and the package declaration.
Otherwise, godoc will recognize this as the package doc comment.


</blockquote></details>

Done.
___
*[`scion-pki/encoding/encoding.go` line 24 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND254GyBBIGPXVkhQhe:-ND2GzEz3E8HmxzBaZng:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/encoding/encoding.go#L24)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Add a doc comment.
</blockquote></details>

Done.
___
*[`scion-pki/key/fingerprint.go` line 34 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND25_S8ALCVFgkLFfW_:-ND2HFtH6HfpJ95HF1BZ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L34)):*
> ```Go
> 
> // NewFingerprintCmd returns a cobra command that returns the subject key id of a
> // public key. If a private key is given, the subject key id is computed for the
> ```

Done.
___
*[`scion-pki/key/fingerprint.go` line 53 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND25klEDZCXjcxblr0o:-ND2HKbMAaTB7DOzZEFu:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L53)):*
> ```Go
> in the file.
> 
> By default the fingerprint calculated is SHA-1 hash of the marshaled public key defined in
> ```

Done.
___
*[`scion-pki/key/fingerprint.go` line 57 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND25zXO1D0qoSkTa6r4:-ND2ISfj1uGOc9dQO8Pq:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L57)):*
> ```Go
> the computed fingerprint is the SHA-1 hash with ASN.1 DER-encoded subjectPublicKey.
> 
> The subject key id is written to standard out.
> ```

Done.
___
*[`scion-pki/key/fingerprint.go` line 88 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND269n_C3THlhS4cpBi:-ND2HTUgANj60MAjMmUK:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L88)):*
> ```Go
> 			output, err := encoding.EncodeBytes(skid, flags.format)
> 			if err != nil {
> 				return serrors.WrapStr("encoding subject key id", err)
> ```

Done.
___
*[`scion-pki/key/fingerprint.go` line 104 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND26FSc2NbgOjVflzcJ:-ND2Hjjt1CserwdVFpym:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L104)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

This does not appear to be used anywhere else. Make it private.

Be vigilant when extending the API surface of a package. You will enter a contract that you will need to support that function for ever.
Changing or removing it will be considered a breaking change.

Once we need it somewhere else, we can always make it public.

</blockquote></details>

Done.
___
*[`scion-pki/key/fingerprint.go` line 107 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND27VN949fHjHTvfxTh:-ND2Hn3FDmCzBhcpoAH5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L107)):*
> ```Go
> 	raw, err := os.ReadFile(filename)
> 	if err != nil {
> 		return nil, serrors.WrapStr("reading input key", err)
> ```

Done.
___
*[`scion-pki/key/fingerprint.go` line 122 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND27dca8SLFzhzZFDrp:-ND2HtNL5X7N6P69P9OY:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L122)):*
> ```Go
> 		pub, ok := key.(crypto.Signer)
> 		if !ok {
> 			return nil, serrors.New("cannot get public key from private key",
> ```

Done.
___
*[`scion-pki/key/fingerprint.go` line 136 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND27RKw8OLjALMrcYu4:-ND2HzN38uBVz-q7pPcb:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L136)):*
> ```Go
> 		cert, err := x509.ParseCertificate(block.Bytes)
> 		if err != nil {
> 			return nil, serrors.WrapStr("error parsing certificate", err)
> ```

Done.
___
*[`scion-pki/key/fingerprint.go` line 141 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND27I9W18fV535K7vbM:-ND2IB50-Rh5m5OTzr29:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint.go#L141)):*
> ```Go
> 	default:
> 		return nil, serrors.New(
> 			"file is not a valid PEM encoding of a private/public key or certificate", "type",
> ```

Done.
___
*[`scion-pki/key/fingerprint_test.go` line 132 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND2863WCATwBbtls6Aq:-ND2IKzUBf5y4AHHUk_5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint_test.go#L132)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Drop the todo
</blockquote></details>

Done.
___
*[`scion-pki/key/fingerprint_test.go` line 149 at r2](https://reviewable.io/reviews/scionproto/scion/4253#-ND284Rl2PFukVEDj1xJ:-ND2INUx5MiqqfbsLUa9:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a7b893efc651d69fbbf31117392fa3375f5c820b/scion-pki/key/fingerprint_test.go#L149)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

drop the new line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-28 13:32 UTC, oncilla approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4253#-:-ND3I2SpEpNq3FoqIC7k:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bunert)



<!-- Sent from Reviewable.io -->

2022-09-28 13:39 UTC, merged