scmp: add authenticated error messages using SPAO
scionproto/scion pull request #4255
Opened 2022-09-20 16:14 UTC by JordiSubira

This PR adds the SPAO header to SCMP error messages:

- Support for computing/slabbing the SPAO fields to the SCMP messages
- Adapt `braccept` tests.

Still missing:
- DRKey provider implementation for the BR
- Logic to authenticate SCMP informational responses.

2022-09-21 08:14 UTC, matzf requested changes
Great stuff!

I've not looked at the braccept tests in detail yet (:100: for adding these), but I saw that the actual authenticator tag is not checked there. That seems ok, but then we really need to have some unit tests for the computation of the MAC itself.

> Reviewed 5 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255#-:-NCU5WffA-sUgDOtxiLq:brazetf)* status: 5 of 15 files reviewed, 12 unresolved discussions (waiting on @JordiSubira and @matzf)

___
*[`pkg/slayers/extn.go` line 28 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCU3XvJEG1Zx3Nw5GS7:-NCU3XvJEG1Zx3Nw5GS8:b-ciom25) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/extn.go#L28)):*
> ```Go
> var (
> 	ErrOptionNotFound = serrors.New("Option not found")
> 	ZeroBlock         [aes.BlockSize]byte
> ```

Unused.
___
*[`pkg/slayers/pkt_auth.go` line 272 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCU3lc6CyX5TLiipG_P:-NCU3lc6CyX5TLiipG_Q:b-e0x2c) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/pkt_auth.go#L272)):*
> ```Go
> 	// Compute inputLen = FixAuthDataInputLen + variable 3. + variable 4. (path) +
> 	// variable (Upper layer payload)
> 	// (https://scion.docs.anapaya.net/en/latest/protocols/authenticator-option.html#authenticated-data)
> ```

Nit, it's docs.scion.org now.
___
*[`pkg/slayers/pkt_auth.go` line 285 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCU40F2EfV3ukxi9vfD:-NCU40F31pzJcswscFn5:b-cjtonp) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/pkt_auth.go#L285)):*
> ```Go
> 		(opt.SPI().Type() == PacketAuthASHost &&
> 			opt.SPI().Direction() == PacketAuthSenderSide) {
> 		inputLen += (int(scionL.DstAddrLen) + 1) * LineLen
> ```

Use `addrBytes()`, like below.
___
*[`pkg/slayers/pkt_auth.go` line 290 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCTmzU1-KkZ_U-rPaGj:-NCTmzU1-KkZ_U-rPaGk:b-ninzr4) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/pkt_auth.go#L290)):*
> ```Go
> 	inputLen += scionL.Path.Len()
> 	inputLen += len(pld)
> 	input := make([]byte, inputLen)
> ```

Creating a buffer for the headers makes sense. 
However, payload should not be copied into this buffer. It can be "written" directly to the CMAC. Ideally, we'd also avoid buffering the Path, but I'm not sure this would be easily possible.

At any rate, this input buffer be reusable to avoid allocating it for every call (either pass it as parameter or make this a member function of a struct that holds on to the buffer).
If the payload is not included in the buffer, there is a good upper bound for the required size of the buffer. Then we don't even need to compute the input length here.
___
*[`pkg/slayers/pkt_auth.go` line 296 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCTpVPRDxJMtkYPd3yQ:-NCTpVPRDxJMtkYPd3yR:bpmtx26) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/pkt_auth.go#L296)):*
> ```Go
> 	}
> 	cmac.Write(input)
> 	copy(mac, cmac.Sum(nil))
> ```

Write to the `mac` buffer directly and return the resulting buffer from the function. This will _append_ to the given output buffer and so will work even if the buffer is `nil` or does not have the correct length.
Change the function signature accordingly to return `([]byte, error)`.



_Suggestion:_
```Go
return cmac.Sum(mac[:0]), nil
```
___
*[`pkg/slayers/pkt_auth.go` line 330 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCTs9TK6dsO8uhJBch8:-NCTs9TK6dsO8uhJBch9:bf5jhnq) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/pkt_auth.go#L330)):*
> ```Go
> 		byte(s.SrcAddrType&0x3)<<2 | byte(s.SrcAddrLen&0x3)
> 	binary.BigEndian.PutUint16(buf[18:], 0)
> 	offset := 24
> ```

Shouldn't this be `offset := 20`  (== FixAuthDataInputLen)?
___
*[`pkg/slayers/pkt_auth.go` line 353 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCToKdtEvBsKND3B5Qq:-NCToKdtEvBsKND3B5Qr:bn7ond) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/pkt_auth.go#L353)):*
> ```Go
> 	if err := s.Path.SerializeTo(buf[offset:]); err != nil {
> 		return err
> 	}
> ```

Mutable fields in the path must be zeroed out: CurrINF, CurrHF, SegID, router alert flags. Not sure what's the most efficient way to do this.
___
*[`pkg/slayers/pkt_auth.go` line 359 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCTxNVSBT9KfwPRIlYg:-NCTxNVSBT9KfwPRIlYh:b-8jrw0u) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/pkt_auth.go#L359)):*
> ```Go
> }
> 
> func ComputeSPAOTimestamp(ts uint32) (uint32, error) {
> ```

The name of this function should somehow indicate that it creates a timestamp for the current time.
___
*[`router/dataplane.go` line 115 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCTyc8a6S4TAevWCU7W:-NCTyc8a6S4TAevWCU7X:b-2yidcm) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/router/dataplane.go#L115)):*
> ```Go
> 
> var (
> 	drkeyDeriver                  = specific.Deriver{}
> ```

Must be a member of `scionPacketProcessor` (otherwise it would be used by multiple processors concurrently).
___
*[`router/dataplane.go` line 130 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCU4s6E0BpumMvaBTfx:-NCU4s6E0BpumMvaBTfy:bvkct4x) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/router/dataplane.go#L130)):*
> ```Go
> 
> type drkeyProvider interface {
> 	GetSV() drkey.Key
> ```

This will need a timestamp parameter to find the SV for the correct epoch (e.g. when validating the traceroute requests).
___
*[`router/dataplane.go` line 1610 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCU-_-P52NTSD7AVV0V:-NCU-_-P52NTSD7AVV0W:bjtcllp) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/router/dataplane.go#L1610)):*
> ```Go
> 	drkeyType := slayers.PacketAuthASHost
> 	if scmpH.TypeCode.Type() >= slayers.SCMPTypeEchoRequest &&
> 		scmpH.TypeCode.Type() <= slayers.SCMPTypeTracerouteReply {
> ```

Traceroute Requests/Responses are authenticated with AS-Host keys, not Host-Host keys (because traceroute requests are not addressed to the router).

Also, Echo is not processed here. Instead, Echo requests are forwarded normally and will be received and processed by the end host stack running on the same machine.
___
*[`router/dataplane.go` line 1619 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCTwy6T8JsXb5GBZXVc:-NCTwy6T8JsXb5GBZXVd:b-gp4m2y) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/router/dataplane.go#L1619)):*
> ```Go
> 	}
> 
> 	timestamp, err := slayers.ComputeSPAOTimestamp(p.infoField.Timestamp)
> ```

`p.infoField` is the current info field, but the timestamp should be relative to `info[0]`.
___
*[`router/dataplane.go` line 1649 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCU1DEc7nWjObTWbKcb:-NCU1DEd9d5QVDL3kuk2:b-31kxkb) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/router/dataplane.go#L1649)):*
> ```Go
> 	if drkeyType == slayers.PacketAuthASHost {
> 
> 		key, err := drkeyDeriver.DeriveASHost(dstA.String(), lvl1)
> ```

Maybe the `DeriveASHost` interface should be adapted to take the address in some non-stringy form, to avoid the formatting + parsing steps here.
This might not be super nice for now, we'll have some cleanup work to do with these address types anyway (see #4149).


<!-- Sent from Reviewable.io -->

2022-09-27 07:14 UTC, matzf requested changes
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 3 of 15 files reviewed, 16 unresolved discussions (waiting on @JordiSubira and @matzf)

___
*[`pkg/slayers/pkt_auth.go` line 86 at r2](https://reviewable.io/reviews/scionproto/scion/4255#-NCxjyhz40VnxVOas4Cn:-NCxjyhz40VnxVOas4Co:b-oaf4mb) ([raw file](https://github.com/scionproto/scion/blob/784a5f444b3536fc3ad3257575d8cd042da43483/pkg/slayers/pkt_auth.go#L86)):*
> ```Go
> 	// 		   = PathMetaHdr + 3 IFs + 64 HFs
> 	// (see https://scion.docs.anapaya.net/en/latest/protocols/authenticator-option.html#authenticated-data)
> 	UpperBoundMACInput = 840
> ```

Use same name as used in other packages, `MACBufferSize`?

If it's already this big, perhaps just make it 12B (authenticator option meta) + 1020B (max SCION header length), then it will be sufficient for any possible path types.

Note: the documentation for the HdrLen field incorrectly says the max is 1024, but 255*4 == 1020. I'll fix that.
___
*[`pkg/slayers/pkt_auth.go` line 371 at r2](https://reviewable.io/reviews/scionproto/scion/4255#-NCxh7HE1kMUjN_I-JL9:-NCxh7HE1kMUjN_I-JLA:b-962k3x) ([raw file](https://github.com/scionproto/scion/blob/784a5f444b3536fc3ad3257575d8cd042da43483/pkg/slayers/pkt_auth.go#L371)):*
> ```Go
> 	case *scion.Raw:
> 		// Zero out CurrInf && CurrHF
> 		p.Raw[0] = 0
> ```

This modifies the original path that will later also be used for sending, which would probably be bad.
If we're doing this raw buffer mangling anyway, it might make sense to write the path to the input data buffer first and then modify it in that buffer. That way, we don't even need the code path for `Decoded`.
___
*[`pkg/slayers/pkt_auth.go` line 409 at r2](https://reviewable.io/reviews/scionproto/scion/4255#-NCxikVtC3RGltkl9rsx:-NCxikVtC3RGltkl9rsy:b-99d7qr) ([raw file](https://github.com/scionproto/scion/blob/784a5f444b3536fc3ad3257575d8cd042da43483/pkg/slayers/pkt_auth.go#L409)):*
> ```Go
> 		return dec, nil
> 	default:
> 		return nil, serrors.New(fmt.Sprintf("unknown path type %T", orig))
> ```

The one hop path should also be handled. 
The EPIC path type needs identical processing as SCION here, so we can perhaps support it without additional logic.
___
*[`router/dataplane.go` line 1607 at r2](https://reviewable.io/reviews/scionproto/scion/4255#-NCxgWwO9H3KxI5Hz-Ey:-NCxgWwP-SJNXGSp22Vd:b-e33lwq) ([raw file](https://github.com/scionproto/scion/blob/784a5f444b3536fc3ad3257575d8cd042da43483/router/dataplane.go#L1607)):*
> ```Go
> 	error,
> ) {
> 	sv := p.drkeyProvider.GetSV(time.Now())
> ```

The timestamp used here here must match the timestamp included in the SPAO. Perhaps the `slayers.ComputeSPAOCurrentTimestamp` function interface needs to be adapted (again, sorry) so that the current time can be passed as argument. 


<!-- Sent from Reviewable.io -->

2022-09-29 15:46 UTC, JordiSubira reviewed
Yes, you're right I will add those UTs in the still missing

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255#-:-NCdY-293hGDT9iC4fjg:b-k4ndyy)* status: 3 of 15 files reviewed, 14 unresolved discussions (waiting on @JordiSubira and @matzf)

___
*[`pkg/slayers/pkt_auth.go` line 285 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCU40F2EfV3ukxi9vfD:-NCdZ9Rn9iDu8GdeFtEG:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/pkt_auth.go#L285)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Use `addrBytes()`, like below.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 290 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCTmzU1-KkZ_U-rPaGj:-NCtoGgw1YXIHfibnYl2:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/pkt_auth.go#L290)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Creating a buffer for the headers makes sense. 
However, payload should not be copied into this buffer. It can be "written" directly to the CMAC. Ideally, we'd also avoid buffering the Path, but I'm not sure this would be easily possible.

At any rate, this input buffer be reusable to avoid allocating it for every call (either pass it as parameter or make this a member function of a struct that holds on to the buffer).
If the payload is not included in the buffer, there is a good upper bound for the required size of the buffer. Then we don't even need to compute the input length here.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 296 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCTpVPRDxJMtkYPd3yQ:-NCtoH6GEc40TY6t6jUY:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/pkt_auth.go#L296)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Write to the `mac` buffer directly and return the resulting buffer from the function. This will _append_ to the given output buffer and so will work even if the buffer is `nil` or does not have the correct length.
Change the function signature accordingly to return `([]byte, error)`.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 330 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCTs9TK6dsO8uhJBch8:-NCtoHij4JPZOhLdpWGd:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/pkt_auth.go#L330)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Shouldn't this be `offset := 20`  (== FixAuthDataInputLen)?
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 353 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCToKdtEvBsKND3B5Qq:-NCtoXiIEXTTulQbZPFm:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/pkt_auth.go#L353)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Mutable fields in the path must be zeroed out: CurrINF, CurrHF, SegID, router alert flags. Not sure what's the most efficient way to do this.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 359 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCTxNVSBT9KfwPRIlYg:-NCtoZ595632SfpPsm3u:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/pkt_auth.go#L359)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The name of this function should somehow indicate that it creates a timestamp for the current time.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 371 at r2](https://reviewable.io/reviews/scionproto/scion/4255#-NCxh7HE1kMUjN_I-JL9:-ND8v9RO98hNCJ794Kdd:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/784a5f444b3536fc3ad3257575d8cd042da43483/pkg/slayers/pkt_auth.go#L371)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This modifies the original path that will later also be used for sending, which would probably be bad.
If we're doing this raw buffer mangling anyway, it might make sense to write the path to the input data buffer first and then modify it in that buffer. That way, we don't even need the code path for `Decoded`.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 409 at r2](https://reviewable.io/reviews/scionproto/scion/4255#-NCxikVtC3RGltkl9rsx:-ND8vAuK00fqrJS8V5MX:brqj215) ([raw file](https://github.com/scionproto/scion/blob/784a5f444b3536fc3ad3257575d8cd042da43483/pkg/slayers/pkt_auth.go#L409)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The one hop path should also be handled. 
The EPIC path type needs identical processing as SCION here, so we can perhaps support it without additional logic.
</blockquote></details>

EPIC still pending
___
*[`router/dataplane.go` line 115 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCTyc8a6S4TAevWCU7W:-NCtoZk168ECD936bq4l:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/router/dataplane.go#L115)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Must be a member of `scionPacketProcessor` (otherwise it would be used by multiple processors concurrently).
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 130 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCU4s6E0BpumMvaBTfx:-NCto_AYED4XNWaVYCVv:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/router/dataplane.go#L130)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This will need a timestamp parameter to find the SV for the correct epoch (e.g. when validating the traceroute requests).
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 1610 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCU-_-P52NTSD7AVV0V:-NCto_yR2uyPsBBAJw0t:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/router/dataplane.go#L1610)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Traceroute Requests/Responses are authenticated with AS-Host keys, not Host-Host keys (because traceroute requests are not addressed to the router).

Also, Echo is not processed here. Instead, Echo requests are forwarded normally and will be received and processed by the end host stack running on the same machine.
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 1619 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCTwy6T8JsXb5GBZXVc:-NCtoaMI674AznG_u5R5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/router/dataplane.go#L1619)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`p.infoField` is the current info field, but the timestamp should be relative to `info[0]`.
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 1607 at r2](https://reviewable.io/reviews/scionproto/scion/4255#-NCxgWwO9H3KxI5Hz-Ey:-ND8vGli1yu-PqmjsIPH:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/784a5f444b3536fc3ad3257575d8cd042da43483/router/dataplane.go#L1607)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The timestamp used here here must match the timestamp included in the SPAO. Perhaps the `slayers.ComputeSPAOCurrentTimestamp` function interface needs to be adapted (again, sorry) so that the current time can be passed as argument. 
</blockquote></details>

Done.
___
*[`pkg/slayers/extn [...]

2022-10-04 13:19 UTC, matzf requested changes
> Reviewed 1 of 3 files at r2, 1 of 4 files at r3, 2 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 5 of 18 files reviewed, 9 unresolved discussions (waiting on @JordiSubira and @matzf)

___
*[`pkg/slayers/pkt_auth.go` line 359 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCTxNVSBT9KfwPRIlYg:-NDXQS7Y8nQy5uzvCj1J:b-53le24) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/pkt_auth.go#L359)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done.
</blockquote></details>

With the added `now` field, the name no longer really fits. Maybe call it _relative_ timestamp?

Btw. this needs documentation, especially for the `ts` parameter.
___
*[`pkg/slayers/pkt_auth.go` line 409 at r2](https://reviewable.io/reviews/scionproto/scion/4255#-NCxikVtC3RGltkl9rsx:-NDXHo7JEsTNqwowt1j5:b6u4p2v) ([raw file](https://github.com/scionproto/scion/blob/784a5f444b3536fc3ad3257575d8cd042da43483/pkg/slayers/pkt_auth.go#L409)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

EPIC still pending
</blockquote></details>

Handle can be handled in the SCION case statement (`case *scion.Raw, *scion.Decoded, *epic.Path`), just add something like `if epic { offset += epic.MetadataLen }` at the beginning
___
*[`pkg/slayers/pkt_auth.go` line 85 at r4](https://reviewable.io/reviews/scionproto/scion/4255#-NDXIq_MDzgsb5-nl12Q:-NDXIq_MDzgsb5-nl12R:bqcadmy) ([raw file](https://github.com/scionproto/scion/blob/66498182af721e507f1c7e22ce800bc878618aef/pkg/slayers/pkt_auth.go#L85)):*
> ```Go
> 	// 3. SCION Address Header
> 	// 4. Path
> 	// (see https://scion.docs.anapaya.net/en/latest/protocols/authenticator-option.html#authenticated-data)
> ```

Nit, url again, docs.scion.org 
___
*[`pkg/slayers/pkt_auth.go` line 340 at r4](https://reviewable.io/reviews/scionproto/scion/4255#-NDXJbj11JYpzX8q9uH3:-NDXJbj11JYpzX8q9uH4:b-ve3v7n) ([raw file](https://github.com/scionproto/scion/blob/66498182af721e507f1c7e22ce800bc878618aef/pkg/slayers/pkt_auth.go#L340)):*
> ```Go
> 		addrLen := addrBytes(s.DstAddrLen)
> 		copy(buf[offset:offset+addrLen], s.RawDstAddr)
> 		offset += addrLen
> ```

Could we just do copy directly? Is there any risk here that the length of `RawDstAddr` might not match `DstAddrLen` (and if so, what would the appropriate action be)?



_Suggestion:_
```Go
offset += copy(buf[offset::], s.RawDstAddr)
```
___
*[`pkg/slayers/pkt_auth.go` line 366 at r4](https://reviewable.io/reviews/scionproto/scion/4255#-NDXF6XQBUD0qlVDFqwl:-NDXF6XQBUD0qlVDFqwm:bqv4epp) ([raw file](https://github.com/scionproto/scion/blob/66498182af721e507f1c7e22ce800bc878618aef/pkg/slayers/pkt_auth.go#L366)):*
> ```Go
> }
> 
> func zeroOutMutablePath(orig path.Path, buff []byte) error {
> ```

Nit, `buf`, not `buff` 
___
*[`pkg/slayers/pkt_auth.go` line 374 at r4](https://reviewable.io/reviews/scionproto/scion/4255#-NDXD_jYD-GIvMLK4rUW:-NDXD_jYD-GIvMLK4rUX:b-ln7w89) ([raw file](https://github.com/scionproto/scion/blob/66498182af721e507f1c7e22ce800bc878618aef/pkg/slayers/pkt_auth.go#L374)):*
> ```Go
> 	// TODO(JordiSubira): process EPIC
> 
> 	case *scion.Raw:
> ```

Combine cases to avoid the duplicate logic:

```
case *scion.Raw, *scion.Decoded:
   ...

```
___
*[`pkg/slayers/pkt_auth_test.go` line 301 at r4](https://reviewable.io/reviews/scionproto/scion/4255#-NDXTg8y0psL_layAzeU:-NDXTg8y0psL_layAzeV:b-jvktdb) ([raw file](https://github.com/scionproto/scion/blob/66498182af721e507f1c7e22ce800bc878618aef/pkg/slayers/pkt_auth_test.go#L301)):*
> ```Go
> 				return
> 			}
> 			goldenFile := "testdata/" + xtest.SanitizedName(t)
> ```

These regression tests give us assurance that we're not unintentionally breaking this later, and this can be useful, especially for covering a wider range of cases. Not sure this is enough here; we'd like to have some assertion that our implementation computes the MAC as required by the specification, at least for some base cases. I think we should prepare a few cases where we manually, byte for byte type out the expected CMAC input and then compare the resulting MACs.

On the other hand, we can simplify things a tiny bit in the setup for the tests, because the Keys that we use don't need to be actual DRKeys. We can just pick a key, just like now you've picked the master secret, and so we don't need to worry about the key derivation steps. For the regression tests, that also decouples the test output from changes in the drkey derivation.
___
*[`router/dataplane.go` line 1588 at r4](https://reviewable.io/reviews/scionproto/scion/4255#-NDXLw6Y04KYDzgEX2r2:-NDXLw6Y04KYDzgEX2r3:bevvm15) ([raw file](https://github.com/scionproto/scion/blob/66498182af721e507f1c7e22ce800bc878618aef/router/dataplane.go#L1588)):*
> ```Go
> 			return nil, serrors.Wrap(cannotRoute, err, "details", "computing CMAC")
> 		}
> 		copy(optAuth.Authenticator(), mac)
> ```

That's a nop, source and destination slice are identical. 
___
*[`router/dataplane.go` line 1637 at r4](https://reviewable.io/reviews/scionproto/scion/4255#-NDXRU8l2rdVdv_8C2V-:-NDXRU8l2rdVdv_8C2V0:b-hgr2uf) ([raw file](https://github.com/scionproto/scion/blob/66498182af721e507f1c7e22ce800bc878618aef/router/dataplane.go#L1637)):*
> ```Go
> 	// with timestamp is always unique
> 	sn := uint32(0)
> 	optAuth, err := slayers.NewPacketAuthOption(slayers.PacketAuthOptionParams{
> ```

Ideally, this PacketAuthOption object would be recycled (using `Reset()`). This should also allow to get rid of the temporary allocation for `macBuf` in this function here.


<!-- Sent from Reviewable.io -->

2022-10-06 13:07 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 5 of 18 files reviewed, 5 unresolved discussions (waiting on @matzf)

___
*[`pkg/slayers/pkt_auth.go` line 359 at r1](https://reviewable.io/reviews/scionproto/scion/4255#-NCTxNVSBT9KfwPRIlYg:-NDh2Ayh-BZJH2jYSm67:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e326c60bcdd8761e5a71dee6626e226d0de5bb48/pkg/slayers/pkt_auth.go#L359)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

With the added `now` field, the name no longer really fits. Maybe call it _relative_ timestamp?

Btw. this needs documentation, especially for the `ts` parameter.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 409 at r2](https://reviewable.io/reviews/scionproto/scion/4255#-NCxikVtC3RGltkl9rsx:-NDh2L6zB4lHkZZI6M5V:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/784a5f444b3536fc3ad3257575d8cd042da43483/pkg/slayers/pkt_auth.go#L409)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Handle can be handled in the SCION case statement (`case *scion.Raw, *scion.Decoded, *epic.Path`), just add something like `if epic { offset += epic.MetadataLen }` at the beginning
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 340 at r4](https://reviewable.io/reviews/scionproto/scion/4255#-NDXJbj11JYpzX8q9uH3:-NDbwJmVDbLlLtgwVBUI:b-ptpwh5) ([raw file](https://github.com/scionproto/scion/blob/66498182af721e507f1c7e22ce800bc878618aef/pkg/slayers/pkt_auth.go#L340)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Could we just do copy directly? Is there any risk here that the length of `RawDstAddr` might not match `DstAddrLen` (and if so, what would the appropriate action be)?
</blockquote></details>

Yes, I think we can assume it. I made a minimal data-flow path inspection and it seems this is always set in the `DecodeAddrHdr(·)`
___
*[`pkg/slayers/pkt_auth.go` line 374 at r4](https://reviewable.io/reviews/scionproto/scion/4255#-NDXD_jYD-GIvMLK4rUW:-NDh2DikCLhf2RHK8sR3:btpiicc) ([raw file](https://github.com/scionproto/scion/blob/66498182af721e507f1c7e22ce800bc878618aef/pkg/slayers/pkt_auth.go#L374)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Combine cases to avoid the duplicate logic:

```
case *scion.Raw, *scion.Decoded:
   ...

```
</blockquote></details>

Done. I packed the duplicated in a function.
___
*[`pkg/slayers/pkt_auth_test.go` line 301 at r4](https://reviewable.io/reviews/scionproto/scion/4255#-NDXTg8y0psL_layAzeU:-NDh2NDJCS0b90G9gpxe:b-paxgd7) ([raw file](https://github.com/scionproto/scion/blob/66498182af721e507f1c7e22ce800bc878618aef/pkg/slayers/pkt_auth_test.go#L301)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

These regression tests give us assurance that we're not unintentionally breaking this later, and this can be useful, especially for covering a wider range of cases. Not sure this is enough here; we'd like to have some assertion that our implementation computes the MAC as required by the specification, at least for some base cases. I think we should prepare a few cases where we manually, byte for byte type out the expected CMAC input and then compare the resulting MACs.

On the other hand, we can simplify things a tiny bit in the setup for the tests, because the Keys that we use don't need to be actual DRKeys. We can just pick a key, just like now you've picked the master secret, and so we don't need to worry about the key derivation steps. For the regression tests, that also decouples the test output from changes in the drkey derivation.
</blockquote></details>

What do you think if we tackle the "manually"-checked tests in a separate PR?

Done, removing the key derivation.


<!-- Sent from Reviewable.io -->

2022-10-07 10:31 UTC, matzf requested changes
> Reviewed 5 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 7 of 19 files reviewed, 1 unresolved discussion (waiting on @JordiSubira and @matzf)

___
*[`pkg/slayers/pkt_auth_test.go` line 301 at r4](https://reviewable.io/reviews/scionproto/scion/4255#-NDXTg8y0psL_layAzeU:-NDlymeA9be5TDbezXc2:bcmgqn7) ([raw file](https://github.com/scionproto/scion/blob/66498182af721e507f1c7e22ce800bc878618aef/pkg/slayers/pkt_auth_test.go#L301)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

What do you think if we tackle the "manually"-checked tests in a separate PR?

Done, removing the key derivation.
</blockquote></details>

Hmm not sure, we don't have any checks to be confident that we're computing the MAC correctly. Or did you verify this manually in some form?
If this is about the size of the PR, I'd rather suggest to split the implementation of the MAC computation in `pkg/slayers` here into a first PR and move the the implementation in the router and the corresponding braccept tests into a second PR.


<!-- Sent from Reviewable.io -->

2022-10-07 10:40 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 7 of 19 files reviewed, 1 unresolved discussion (waiting on @JordiSubira and @matzf)

___
*[`pkg/slayers/pkt_auth_test.go` line 301 at r4](https://reviewable.io/reviews/scionproto/scion/4255#-NDXTg8y0psL_layAzeU:-NDm0iTf1DEGaCCAdtSE:b-2ym6nl) ([raw file](https://github.com/scionproto/scion/blob/66498182af721e507f1c7e22ce800bc878618aef/pkg/slayers/pkt_auth_test.go#L301)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Hmm not sure, we don't have any checks to be confident that we're computing the MAC correctly. Or did you verify this manually in some form?
If this is about the size of the PR, I'd rather suggest to split the implementation of the MAC computation in `pkg/slayers` here into a first PR and move the the implementation in the router and the corresponding braccept tests into a second PR.
</blockquote></details>

Yes, it was about the size, but you're probably right, it does make sense to have the tests in this PR. Also, I guess since we have already reviewed the rest of the files, I'll keep the PR as it is and will add the tests.


<!-- Sent from Reviewable.io -->

2022-10-11 13:12 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 2 of 19 files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[`pkg/slayers/pkt_auth_test.go` line 301 at r4](https://reviewable.io/reviews/scionproto/scion/4255#-NDXTg8y0psL_layAzeU:-NE6ABVW4yNy1QPMAvr9:bk5jixe) ([raw file](https://github.com/scionproto/scion/blob/66498182af721e507f1c7e22ce800bc878618aef/pkg/slayers/pkt_auth_test.go#L301)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Yes, it was about the size, but you're probably right, it does make sense to have the tests in this PR. Also, I guess since we have already reviewed the rest of the files, I'll keep the PR as it is and will add the tests.
</blockquote></details>

Done. I removed the regression tests which doesn't seem to add anything to these manual UTs.


<!-- Sent from Reviewable.io -->

2022-10-19 12:17 UTC, matzf requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 4 of 19 files reviewed, 11 unresolved discussions (waiting on @JordiSubira)

___
*[`pkg/slayers/pkt_auth.go` line 340 at r6](https://reviewable.io/reviews/scionproto/scion/4255#-NEjzXGWEAnRrg8VmP9q:-NEk9t0b4UwjD9XdnX_J:b-pzq4q4) ([raw file](https://github.com/scionproto/scion/blob/595f2c743ab7744f42bccd0e24b1c4e03b1f9cf0/pkg/slayers/pkt_auth.go#L340)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Bug. With AS-Host key and receiver-side key derivation, we must include the _source_ address in the MAC input (the destination address is already part of the key derivation).
Same below for sender-side, where the destination address should be included in the MAC input.
</blockquote></details>

Nope, sorry, I mixed things up.
___
*[`pkg/slayers/pkt_auth_test.go` line 268 at r6](https://reviewable.io/reviews/scionproto/scion/4255#-NEjKZUO3dOPCopvc7_K:-NEkA4yF3wzTWzZyV2Zn:b-5fc6ff) ([raw file](https://github.com/scionproto/scion/blob/595f2c743ab7744f42bccd0e24b1c4e03b1f9cf0/pkg/slayers/pkt_auth_test.go#L268)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

It would be nice to split this into lines of "line length" (4 bytes) to match the description in the specifications for easier visual parsing.
Also annotate the individual fields so that the thing can be "verified" by careful inspection. See proposal below:

There are two bugs (see comments, also added comments to the responsible code).
</blockquote></details>

As commented above, the src/dst address in the MAC input is actually correct and my comment was wrong.


<!-- Sent from Reviewable.io -->

2022-10-20 09:40 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 3 of 19 files reviewed, 10 unresolved discussions (waiting on @matzf)

___
*[`pkg/slayers/pkt_auth.go` line 402 at r6](https://reviewable.io/reviews/scionproto/scion/4255#-NEjzDxGESuEkgZtjNoz:-NEokdn-0a_itHkMz-Mt:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/595f2c743ab7744f42bccd0e24b1c4e03b1f9cf0/pkg/slayers/pkt_auth.go#L402)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Bug, SegID is two bytes that need to be zeroed.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth_test.go` line 42 at r6](https://reviewable.io/reviews/scionproto/scion/4255#-NEjvSQHDmbLbT1OEA8J:-NEokez89zbLux5ePlii:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/595f2c743ab7744f42bccd0e24b1c4e03b1f9cf0/pkg/slayers/pkt_auth_test.go#L42)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Why specify explicitly as little endian? That just seems needlessly confusing, because in the packet it will be big endian. Easiest option is just write it as hex `ts = 0x030201, sn = 0x060504` .
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth_test.go` line 47 at r6](https://reviewable.io/reviews/scionproto/scion/4255#-NEk03Iq-gT5H3G-PSlP:-NEokfWe8ExqgjZPC9Vz:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/595f2c743ab7744f42bccd0e24b1c4e03b1f9cf0/pkg/slayers/pkt_auth_test.go#L47)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

No need to specify these globally. The drkey options should be explicitly defined in the individual test cases.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth_test.go` line 50 at r6](https://reviewable.io/reviews/scionproto/scion/4255#-NEjtV9Y11PsilRSEWCC:-NEokgs44GwTqk3CFFFR:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/595f2c743ab7744f42bccd0e24b1c4e03b1f9cf0/pkg/slayers/pkt_auth_test.go#L50)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Set CurrINF/CurrHF to non-zero to test the zero-ing.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth_test.go` line 59 at r6](https://reviewable.io/reviews/scionproto/scion/4255#-NEjwUSHEppk_VAfW9c-:-NEokhkj0Lfp0eS3GTds:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/595f2c743ab7744f42bccd0e24b1c4e03b1f9cf0/pkg/slayers/pkt_auth_test.go#L59)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Use some SegID value with two non-zero bytes (to check the zeroing of both bytes)
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth_test.go` line 83 at r6](https://reviewable.io/reviews/scionproto/scion/4255#-NEjw3NkEaI-xitOAKYW:-NEokisQ0dDbwAmJ6AAC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/595f2c743ab7744f42bccd0e24b1c4e03b1f9cf0/pkg/slayers/pkt_auth_test.go#L83)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Set router alert in some hop fields to test the zeroing.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth_test.go` line 230 at r6](https://reviewable.io/reviews/scionproto/scion/4255#-NEjGUFh3fl7BNYwNqqs:-NEoklF37KTInQ5CRO6L:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/595f2c743ab7744f42bccd0e24b1c4e03b1f9cf0/pkg/slayers/pkt_auth_test.go#L230)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Does not need to be in this struct, can be allocated in the test function below.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth_test.go` line 268 at r6](https://reviewable.io/reviews/scionproto/scion/4255#-NEjKZUO3dOPCopvc7_K:-NEokmYD36EMOosvb-aR:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/595f2c743ab7744f42bccd0e24b1c4e03b1f9cf0/pkg/slayers/pkt_auth_test.go#L268)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

As commented above, the src/dst address in the MAC input is actually correct and my comment was wrong.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth_test.go` line 456 at r6](https://reviewable.io/reviews/scionproto/scion/4255#-NEjF1vU7S2nwXA79a2X:-NEoknx46deo3IojL1wN:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/595f2c743ab7744f42bccd0e24b1c4e03b1f9cf0/pkg/slayers/pkt_auth_test.go#L456)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

We don't care about testing these functions here in this test, and so we can make things a bit more straight forward by explicitly specifying the relative timestamp and the SPI. This can be specified as the `PacketAuthOptionParams` struct for the individual test cases and so we don't need this `getSPAO` function.
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 1612 at r6](https://reviewable.io/reviews/scionproto/scion/4255#-NEjBiuBERl4Exx0g85k:-NEokqx0CaIaXmi_RsbB:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/595f2c743ab7744f42bccd0e24b1c4e03b1f9cf0/router/dataplane.go#L1612)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The value is the same, but it would be more logical to use the destination IA/address of the `scionL` prepared in the calling function. Can either pass in the layer object or the IA/addr.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-08 16:27 UTC, matzf requested changes
> Reviewed 4 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 6 of 20 files reviewed, 12 unresolved discussions (waiting on @JordiSubira)

___
*[`pkg/slayers/pkt_auth.go` line 306 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMhz9C7NyDqn3dLDlp:-NGMhz9C7NyDqn3dLDlq:bn9pks6) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/pkg/slayers/pkt_auth.go#L306)):*
> ```Go
> }
> 
> func SerializeAutenticatedData(
> ```

Keep this private (plus typo, aut**h**enticated). Add `var SerializeAuthenticatedData = serializeAuthenticatedData` to `export_test.go`.
___
*[`pkg/slayers/pkt_auth.go` line 314 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMyGnmEY5MCAAeUMnI:-NGMyGnmEY5MCAAeUMnJ:b-la05v9) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/pkg/slayers/pkt_auth.go#L314)):*
> ```Go
> 
> 	buf[0] = byte(CmnHdrLen + s.AddrHdrLen() + s.Path.Len())
> 	buf[1] = byte(L4SCMP)
> ```

This must be the protocol type of the actual packet. As this requires ignoring the extension headers, we don't want to extract this from the `SCION` data and so this needs to be a parameter here (`pldType L4ProtocolType`). 
___
*[`pkg/slayers/pkt_auth.go` line 366 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMiUk_8SOHpavCuZ8q:-NGMiUk_8SOHpavCuZ8r:bj7pfqv) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/pkg/slayers/pkt_auth.go#L366)):*
> ```Go
> }
> 
> func TimeFromRelativeTimeStamp(spaoTS uint32, ts uint32) time.Time {
> ```

Nit. `TimeFromSPAORelativeTimestamp`.
`Timestamp`  (not `TimeStamp`) for consistency.
Arguments order reversed from `ComputeSPAORelativeTimestamp` (info[0].Timestamp is first)?
___
*[`pkg/slayers/pkt_auth_test.go` line 50 at r6](https://reviewable.io/reviews/scionproto/scion/4255#-NEjtV9Y11PsilRSEWCC:-NGMkXfJCIVtMi1mveTJ:b-hy2z1u) ([raw file](https://github.com/scionproto/scion/blob/595f2c743ab7744f42bccd0e24b1c4e03b1f9cf0/pkg/slayers/pkt_auth_test.go#L50)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`0xab` is a weird value for `CurrINF` because it cannot be represented in the two bit wire value. 
Same for `0xcd` which is not a valid `CurrHF` value.
___
*[`pkg/slayers/pkt_auth_test.go` line 234 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMnnKrACgymWUrO9h-:-NGMnnKrACgymWUrO9h0:undefined) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/pkg/slayers/pkt_auth_test.go#L234)):*
> ```Go
> 		pld             []byte
> 		rawMACInput     []byte
> 		assertFormatErr assert.ErrorAssertionFunc
> ```





_Suggestion:_
```Go
		assertErr assert.ErrorAssertionFunc
```
___
*[`router/dataplane.go` line 1537 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMqXLUBz7tGDBnJIvt:-NGMqXLV9lmIwKLnDXZJ:b-ioi459) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/router/dataplane.go#L1537)):*
> ```Go
> 	if cause != nil ||
> 		(scmpH.TypeCode.Type() == slayers.SCMPTypeTracerouteReply &&
> 			p.hasValidAuth()) {
> ```

Ideally we'd like to reuse the key from the auth valididty check for the reply. Maybe mention this in a comment if you want to defer this optimization for later.

Nit. Just assign the `needsAuth` bool directly, no if.
___
*[`router/dataplane.go` line 1654 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMrIJ060DFnCyKRsNC:-NGMrIJ060DFnCyKRsND:b-3hndfo) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/router/dataplane.go#L1654)):*
> ```Go
> 		return err
> 	}
> 	return nil
> ```

Just `return p.optAuth.Reset(...)`
___
*[`router/dataplane.go` line 1665 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMske-EoN5hYwaFeTC:-NGMske-EoN5hYwaFeTD:b-l1euy4) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/router/dataplane.go#L1665)):*
> ```Go
> 	); err != nil {
> 		return false
> 	}
> ```

This doesn't seem to check whether the E2E extension header is present. It could happen that we parse a UDP or SCMP payload or the HBH as the E2E.

During SCION packet processing we use the `EndToEndExtnSkipper` layer. This doesn't parse the options at all, but does keep a reference to the data slice if the extension header is present. We can create the `EndToEndExtn` from that (from `p.e2eLayer.Contents`).
The existing `p.e2eLayer` is not reset between different packets, you'll have to add this (`p.e2eLayer = slayers.EndToEndExtnSkipper{}`).

Note: ideally we'd have some sort of a scanning implementation of `FindOption` method for `EndToEndExtnSkipper` to avoid parsing all the tlvOptions, but we can do that as an optimisation later on.
___
*[`router/dataplane.go` line 1685 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMviMH2i76vG2fl-N9:-NGMviMH2i76vG2fl-NA:b-cx5lw1) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/router/dataplane.go#L1685)):*
> ```Go
> 	}
> 	// the sender should have use the receiver side key, i.e., K_{localIA-remoteIA:remoteHost}
> 	// where remoteIA == p.scionLayer.SrcIA and remoteHost == dstAddr
> ```

Confusing renaming. Why not just keep calling it `srcAddr`?
___
*[`router/dataplane.go` line 1695 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMwYJL5jmibkFNwiad:-NGMwYJL5jmibkFNwiae:b-318zpd) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/router/dataplane.go#L1695)):*
> ```Go
> 		authOption,
> 		&p.scionLayer,
> 		p.e2eLayer.Payload, // scmpH + scmpP
> ```

I'd use `p.lastLayer.LayerPayload()` here (same thing, but IMO clarifies the intent). 

The comment `// scmpH + scmpP` honestly just confused me.
___
*[`router/dataplane.go` line 1704 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMpKWR8CP4AlTk2yda:-NGMpKWR8CP4AlTk2ydb:b-f7ynx1) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/router/dataplane.go#L1704)):*
> ```Go
> 
> 	// compare incoming authField with computed authentication tag
> 	return bytes.Equal(authOption.Authenticator(), p.validAuthBuf)
> ```

`subtle.ConstantTimeCompare() != 0`.
___
*[`tools/braccept/cases/scmp_dest_unreachable.go` line 176 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGN2XmK3eyR-Q-VDMl_:-NGN2XmK3eyR-Q-VDMla:b85xw0o) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/tools/braccept/cases/scmp_dest_unreachable.go#L176)):*
> ```Go
> 			packAuthOpt.EndToEndOption,
> 		},
> 	}
> ```

Move the construction of `e2e` into a helper function in `scmp.go`, e.g. `func normalizedSCMPPacketAuth() *slayers.EndToEndExtn`.
This is absolutely identical for all cases that check SCMPs errors.


<!-- Sent from Reviewable.io -->

2022-11-09 14:31 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 3 of 21 files reviewed, 11 unresolved discussions (waiting on @matzf)

___
*[`pkg/slayers/pkt_auth.go` line 306 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMhz9C7NyDqn3dLDlp:-NGRn0h24W7zm1M2nK6b:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/pkg/slayers/pkt_auth.go#L306)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Keep this private (plus typo, aut**h**enticated). Add `var SerializeAuthenticatedData = serializeAuthenticatedData` to `export_test.go`.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 314 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMyGnmEY5MCAAeUMnI:-NGRn1_YEcI3x-USwLbk:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/pkg/slayers/pkt_auth.go#L314)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This must be the protocol type of the actual packet. As this requires ignoring the extension headers, we don't want to extract this from the `SCION` data and so this needs to be a parameter here (`pldType L4ProtocolType`). 
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth_test.go` line 50 at r6](https://reviewable.io/reviews/scionproto/scion/4255#-NEjtV9Y11PsilRSEWCC:-NGRn4yh8xC4JnLk2LGb:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/595f2c743ab7744f42bccd0e24b1c4e03b1f9cf0/pkg/slayers/pkt_auth_test.go#L50)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`0xab` is a weird value for `CurrINF` because it cannot be represented in the two bit wire value. 
Same for `0xcd` which is not a valid `CurrHF` value.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth_test.go` line 234 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMnnKrACgymWUrO9h-:-NGRn5eC8hb7UtMYTDIE:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/pkg/slayers/pkt_auth_test.go#L234)):*
> ```Go
> 		pld             []byte
> 		rawMACInput     []byte
> 		assertFormatErr assert.ErrorAssertionFunc
> ```

Done.
___
*[`router/dataplane.go` line 1537 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMqXLUBz7tGDBnJIvt:-NGRn7R21cH-FV4_nwf9:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/router/dataplane.go#L1537)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Ideally we'd like to reuse the key from the auth valididty check for the reply. Maybe mention this in a comment if you want to defer this optimization for later.

Nit. Just assign the `needsAuth` bool directly, no if.
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 1654 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMrIJ060DFnCyKRsNC:-NGRn8Y67AE1PiC3fnVD:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/router/dataplane.go#L1654)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Just `return p.optAuth.Reset(...)`
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 1665 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMske-EoN5hYwaFeTC:-NGRnBpw4MBbiMvJCT7b:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/router/dataplane.go#L1665)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This doesn't seem to check whether the E2E extension header is present. It could happen that we parse a UDP or SCMP payload or the HBH as the E2E.

During SCION packet processing we use the `EndToEndExtnSkipper` layer. This doesn't parse the options at all, but does keep a reference to the data slice if the extension header is present. We can create the `EndToEndExtn` from that (from `p.e2eLayer.Contents`).
The existing `p.e2eLayer` is not reset between different packets, you'll have to add this (`p.e2eLayer = slayers.EndToEndExtnSkipper{}`).

Note: ideally we'd have some sort of a scanning implementation of `FindOption` method for `EndToEndExtnSkipper` to avoid parsing all the tlvOptions, but we can do that as an optimisation later on.
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 1685 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMviMH2i76vG2fl-N9:-NGRnEAYAYt1qMKjinF1:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/router/dataplane.go#L1685)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Confusing renaming. Why not just keep calling it `srcAddr`?
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 1695 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMwYJL5jmibkFNwiad:-NGRnEnJ9EQ8mJt84_75:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/router/dataplane.go#L1695)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I'd use `p.lastLayer.LayerPayload()` here (same thing, but IMO clarifies the intent). 

The comment `// scmpH + scmpP` honestly just confused me.
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 1704 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMpKWR8CP4AlTk2yda:-NGRnFEB7pI4ZMG_aroW:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/router/dataplane.go#L1704)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`subtle.ConstantTimeCompare() != 0`.
</blockquote></details>

Done.
___
*[`tools/braccept/cases/scmp_dest_unreachable.go` line 176 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGN2XmK3eyR-Q-VDMl_:-NGRnGnf-hfs2uqGSTSv:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/tools/braccept/cases/scmp_dest_unreachable.go#L176)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Move the construction of `e2e` into a helper function in `scmp.go`, e.g. `func normalizedSCMPPacketAuth() *slayers.EndToEndExtn`.
This is absolutely identical for all cases that check SCMPs errors.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-22 10:36 UTC, matzf requested changes
> Reviewed 1 of 15 files at r1, 3 of 7 files at r6, 1 of 6 files at r8, 13 of 13 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: all files reviewed, 5 unresolved discussions (waiting on @JordiSubira)

___
*[`pkg/slayers/pkt_auth.go` line 306 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMhz9C7NyDqn3dLDlp:-NHTg-6iE9a1-ifN48Ru:bmaqi90) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/pkg/slayers/pkt_auth.go#L306)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still a typo. And btw. why not a shorter alias with `var ...`  instead of re-declaring the function in export_test.go?
___
*[`router/dataplane.go` line 1706 at r9](https://reviewable.io/reviews/scionproto/scion/4255#-NHTgn5V7WximZiNeDsi:-NHTgn5V7WximZiNeDsj:bjh8n9b) ([raw file](https://github.com/scionproto/scion/blob/186a026d6c7d871c24edd1ce177d20ce35873767/router/dataplane.go#L1706)):*
> ```Go
> 
> 	// Reset p.e2eLayer
> 	p.e2eLayer = slayers.EndToEndExtnSkipper{}
> ```

This should be in `scionPacketProcessor.reset`; and perhaps reset the hbh layer too for consistency.

Btw. resetting this is not strictly required with the `lastLayer.CanDecode(...)` check that you do now at the beginning of the function. I had had a different check in mind (something like `len(p.e2eLayer.Content) > 0`) where resetting would have been crucial.
___
*[`tools/braccept/main.go` line 84 at r9](https://reviewable.io/reviews/scionproto/scion/4255#-NHTqX2u1FOpRYg3NpDb:-NHTqX2vAWwWzaxVXU2I:b-euo8el) ([raw file](https://github.com/scionproto/scion/blob/186a026d6c7d871c24edd1ce177d20ce35873767/tools/braccept/main.go#L84)):*
> ```Go
> 		cases.SCMPTracerouteIngressWithSPAO(artifactsDir, hfMAC),
> 
> 		// cases.ParentToChild(artifactsDir, hfMAC),
> ```

Don't forget to re-enable these before merging.
___
*[`tools/braccept/cases/scmp_expired_hop.go` line 137 at r9](https://reviewable.io/reviews/scionproto/scion/4255#-NHTmGaJ0hnNErQ7ypv2:-NHTmGaJ0hnNErQ7ypv3:b2p1kmk) ([raw file](https://github.com/scionproto/scion/blob/186a026d6c7d871c24edd1ce177d20ce35873767/tools/braccept/cases/scmp_expired_hop.go#L137)):*
> ```Go
> 		ReadFrom:        "veth_131_host",
> 		Input:           input.Bytes(),
> 		Want:            nil,
> ```

Huh, that's a catch. I hadn't really noticed before that we can't send SCMPs for (very) expired segments because the timestamp cannot be represented.
Some time ago, @fstreun had proposed to represent the timestamps relative to the drkey epochs instead of relative to the info field (see https://github.com/scionproto/scion/issues/4062#issuecomment-1136102996 and following discussion). This would be a fix for this...
___
*[`tools/braccept/cases/scmp_traceroute.go` line 362 at r9](https://reviewable.io/reviews/scionproto/scion/4255#-NHTqFYc7f24lRwrBef8:-NHTqFYc7f24lRwrBef9:b-iqfcgg) ([raw file](https://github.com/scionproto/scion/blob/186a026d6c7d871c24edd1ce177d20ce35873767/tools/braccept/cases/scmp_traceroute.go#L362)):*
> ```Go
> 	}
> 
> 	// Skip Ethernet + IPv4 + UDP
> ```

Nit. Wrongly copy pasted comment?


<!-- Sent from Reviewable.io -->

2022-11-24 09:58 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 15 of 21 files reviewed, 3 unresolved discussions (waiting on @matzf)

___
*[`pkg/slayers/pkt_auth.go` line 306 at r8](https://reviewable.io/reviews/scionproto/scion/4255#-NGMhz9C7NyDqn3dLDlp:-NHd3Sbu-goUg8Lkl2-w:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bfe1bf428da2700fad7fdd5c8e8f4077d9aee9f2/pkg/slayers/pkt_auth.go#L306)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Still a typo. And btw. why not a shorter alias with `var ...`  instead of re-declaring the function in export_test.go?
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 1706 at r9](https://reviewable.io/reviews/scionproto/scion/4255#-NHTgn5V7WximZiNeDsi:-NHd3UDE9zhH7bOJWHSC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/186a026d6c7d871c24edd1ce177d20ce35873767/router/dataplane.go#L1706)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This should be in `scionPacketProcessor.reset`; and perhaps reset the hbh layer too for consistency.

Btw. resetting this is not strictly required with the `lastLayer.CanDecode(...)` check that you do now at the beginning of the function. I had had a different check in mind (something like `len(p.e2eLayer.Content) > 0`) where resetting would have been crucial.

</blockquote></details>

Done.
___
*[`tools/braccept/main.go` line 84 at r9](https://reviewable.io/reviews/scionproto/scion/4255#-NHTqX2u1FOpRYg3NpDb:-NHd3V9L9ZhnyZVjUPeJ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/186a026d6c7d871c24edd1ce177d20ce35873767/tools/braccept/main.go#L84)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Don't forget to re-enable these before merging.
</blockquote></details>

Done.
___
*[`tools/braccept/cases/scmp_expired_hop.go` line 137 at r9](https://reviewable.io/reviews/scionproto/scion/4255#-NHTmGaJ0hnNErQ7ypv2:-NHd3W6o2WAJgMuq6kta:b32405m) ([raw file](https://github.com/scionproto/scion/blob/186a026d6c7d871c24edd1ce177d20ce35873767/tools/braccept/cases/scmp_expired_hop.go#L137)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Huh, that's a catch. I hadn't really noticed before that we can't send SCMPs for (very) expired segments because the timestamp cannot be represented.
Some time ago, @fstreun had proposed to represent the timestamps relative to the drkey epochs instead of relative to the info field (see https://github.com/scionproto/scion/issues/4062#issuecomment-1136102996 and following discussion). This would be a fix for this...
</blockquote></details>

Sure, we can tackle this as was discussed in this thread. I will do it in a future commit if that's fine. 


<!-- Sent from Reviewable.io -->

2022-11-25 12:32 UTC, matzf commented
@JordiSubira, you'll need to rebase on master. With #4297,  the buildkite runs should work again.

2022-11-25 12:36 UTC, matzf reviewed
> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2022-11-30 13:47 UTC, matzf reviewed
> Reviewed 1 of 15 files at r1, 1 of 7 files at r6, 1 of 6 files at r8, 8 of 13 files at r9, 6 of 6 files at r10.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: all files reviewed, 5 unresolved discussions (waiting on @JordiSubira)

___
*[`pkg/slayers/pkt_auth.go` line 79 at r10](https://reviewable.io/reviews/scionproto/scion/4255#-NI7_k623S_OmtcKCag1:-NI7_k623S_OmtcKCag2:b-kr3j19) ([raw file](https://github.com/scionproto/scion/blob/8ea08673a0e510db3c133fd71e27cd4f67b406ac/pkg/slayers/pkt_auth.go#L79)):*
> ```Go
> 	// FixAuthDataInputLen is the unvariable fields length for the
> 	// authenticated data
> 	FixAuthDataInputLen = MinPacketAuthDataLen + 8
> ```

Make both of these constants private, nobody needs these now.
___
*[`pkg/slayers/pkt_auth.go` line 271 at r10](https://reviewable.io/reviews/scionproto/scion/4255#-NHyBrSMDYNJUiUcPpjE:-NHyBrSMDYNJUiUcPpjF:bxpq47l) ([raw file](https://github.com/scionproto/scion/blob/8ea08673a0e510db3c133fd71e27cd4f67b406ac/pkg/slayers/pkt_auth.go#L271)):*
> ```Go
> }
> 
> func ComputeAuthCMAC(
> ```

This should have docs. Suggestion:

```go
// ComputeAuthCMAC computes the authenticator tag for the AES-CMAC algorithm.
// The key should correspond to the SPI defined in opt.SPI.
// The SCION layer, payload type and payload define the input to the MAC, as defined in https://docs.scion.org/en/latest/protocols/authenticator-option.html#authenticated-data.
// 
// The input buffer is used as a temporary buffer for the MAC computation. It must be at least MACBufferSize long.
// The resulting MAC is written to macBuffer (appending, if necessary), and returned as a slice of length 16.
```
___
*[`pkg/slayers/pkt_auth.go` line 281 at r10](https://reviewable.io/reviews/scionproto/scion/4255#-NI7a8xxEKvfrCPhTOTw:-NI7a8xxEKvfrCPhTOTx:bo6umg8) ([raw file](https://github.com/scionproto/scion/blob/8ea08673a0e510db3c133fd71e27cd4f67b406ac/pkg/slayers/pkt_auth.go#L281)):*
> ```Go
> ) ([]byte, error) {
> 
> 	// TODO(matzf): avoid allocations, somehow?
> ```

Remove comment
___
*[`pkg/slayers/pkt_auth.go` line 381 at r10](https://reviewable.io/reviews/scionproto/scion/4255#-NI7_4_tET_XrE3_a0r3:-NI7_4_uEvy910nAGu_j:bo6umg8) ([raw file](https://github.com/scionproto/scion/blob/8ea08673a0e510db3c133fd71e27cd4f67b406ac/pkg/slayers/pkt_auth.go#L381)):*
> ```Go
> 	}
> 	switch p := orig.(type) {
> 	// TODO(JordiSubira): process EPIC
> ```

Remove comment
___
*[`pkg/slayers/pkt_auth.go` line 405 at r10](https://reviewable.io/reviews/scionproto/scion/4255#-NI7aoOJ9TO2KNIdgcU5:-NI7aoOJ9TO2KNIdgcU6:bisoiki) ([raw file](https://github.com/scionproto/scion/blob/8ea08673a0e510db3c133fd71e27cd4f67b406ac/pkg/slayers/pkt_auth.go#L405)):*
> ```Go
> }
> 
> func zeroOutWithBase(base scion.Base, offset int, buf []byte) {
> ```

Nit, tiny bit more elegant would be to only have `buf` parameter and pass in `buf[epic.MetadataLen:]` for Epic.


<!-- Sent from Reviewable.io -->

2022-12-02 16:17 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 15 of 21 files reviewed, 4 unresolved discussions (waiting on @matzf)

___
*[`pkg/slayers/pkt_auth.go` line 79 at r10](https://reviewable.io/reviews/scionproto/scion/4255#-NI7_k623S_OmtcKCag1:-NIIbmpl0IWOuFruCyWu:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8ea08673a0e510db3c133fd71e27cd4f67b406ac/pkg/slayers/pkt_auth.go#L79)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Make both of these constants private, nobody needs these now.
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 271 at r10](https://reviewable.io/reviews/scionproto/scion/4255#-NHyBrSMDYNJUiUcPpjE:-NIIbm0zEUzHAoK3vhGE:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8ea08673a0e510db3c133fd71e27cd4f67b406ac/pkg/slayers/pkt_auth.go#L271)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This should have docs. Suggestion:

```go
// ComputeAuthCMAC computes the authenticator tag for the AES-CMAC algorithm.
// The key should correspond to the SPI defined in opt.SPI.
// The SCION layer, payload type and payload define the input to the MAC, as defined in https://docs.scion.org/en/latest/protocols/authenticator-option.html#authenticated-data.
// 
// The input buffer is used as a temporary buffer for the MAC computation. It must be at least MACBufferSize long.
// The resulting MAC is written to macBuffer (appending, if necessary), and returned as a slice of length 16.
```
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 281 at r10](https://reviewable.io/reviews/scionproto/scion/4255#-NI7a8xxEKvfrCPhTOTw:-NIIblVJ8dwltSQinnty:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8ea08673a0e510db3c133fd71e27cd4f67b406ac/pkg/slayers/pkt_auth.go#L281)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Remove comment
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 381 at r10](https://reviewable.io/reviews/scionproto/scion/4255#-NI7_4_tET_XrE3_a0r3:-NIIc6bM695Uf7Y9vu7o:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8ea08673a0e510db3c133fd71e27cd4f67b406ac/pkg/slayers/pkt_auth.go#L381)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Remove comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-05 11:05 UTC, matzf requested changes
> Reviewed 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira)

___
*[`pkg/slayers/pkt_auth.go` line 337 at r11](https://reviewable.io/reviews/scionproto/scion/4255#-NIWuLWJ6hoOoPj4KgU6:-NIWuLWJ6hoOoPj4KgU7:b-xzj4mb) ([raw file](https://github.com/scionproto/scion/blob/725faa6242d41d2b675fc4926b501c7947edca33/pkg/slayers/pkt_auth.go#L337)):*
> ```Go
> 	binary.BigEndian.PutUint32(buf[12:], firstHdrLine)
> 	buf[16] = byte(s.PathType)
> 	buf[17] = byte(s.DstAddrType&0x3)<<6 | byte(s.DstAddrType.Length()&0x3)<<4 |
> ```

Length returns the length in bytes which is _not_ the value that should be encoded here. Accidentally passes the tests because the value is truncated back to 0 which is correct for IPv4; would not work for IPv6.

The type/length components don't need to be encoded separately (see #4160):



_Suggestion:_
```Go
	buf[17] = byte(s.DstAddrType&0x7)<<4 | byte(s.SrcAddrType&0x7)
```
___
*[`pkg/slayers/pkt_auth_test.go` line 251 at r11](https://reviewable.io/reviews/scionproto/scion/4255#-NIWwvnI72-lR8aFJtMK:-NIWwvnJAsxRUW9mVhx-:b6vkhr) ([raw file](https://github.com/scionproto/scion/blob/725faa6242d41d2b675fc4926b501c7947edca33/pkg/slayers/pkt_auth_test.go#L251)):*
> ```Go
> 				DstIA:        dstIA,
> 				SrcAddrType:  slayers.T4Ip,
> 				RawSrcAddr:   net.IPv4(192, 0, 0, 2).To4(),
> ```

See comment above related to encoding address type; could you change one of the test cases to use IPv6 and one to use a SVC address, to get broader coverage?


<!-- Sent from Reviewable.io -->

2022-12-05 14:35 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 19 of 21 files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`pkg/slayers/pkt_auth.go` line 337 at r11](https://reviewable.io/reviews/scionproto/scion/4255#-NIWuLWJ6hoOoPj4KgU6:-NIX_Nid0SNoRCqt55zt:b-igwe5o) ([raw file](https://github.com/scionproto/scion/blob/725faa6242d41d2b675fc4926b501c7947edca33/pkg/slayers/pkt_auth.go#L337)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Length returns the length in bytes which is _not_ the value that should be encoded here. Accidentally passes the tests because the value is truncated back to 0 which is correct for IPv4; would not work for IPv6.

The type/length components don't need to be encoded separately (see #4160):

</blockquote></details>

Done, it was an oversight from my side, sorry for the confussion. 
___
*[`pkg/slayers/pkt_auth_test.go` line 251 at r11](https://reviewable.io/reviews/scionproto/scion/4255#-NIWwvnI72-lR8aFJtMK:-NIXhbbd8-o5xFx_aLRR:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/725faa6242d41d2b675fc4926b501c7947edca33/pkg/slayers/pkt_auth_test.go#L251)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

See comment above related to encoding address type; could you change one of the test cases to use IPv6 and one to use a SVC address, to get broader coverage?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-05 14:49 UTC, matzf approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2022-12-08 13:10 UTC, oncilla requested changes
> Reviewed 1 of 3 files at r2, 4 of 7 files at r6, 1 of 6 files at r8, 6 of 13 files at r9, 3 of 6 files at r10, 4 of 6 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: all files reviewed, 5 unresolved discussions (waiting on @JordiSubira)

___
*[`pkg/slayers/pkt_auth.go` line 280 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIlhFcD1fPQzcaZHnh5:-NIlhFcD1fPQzcaZHnh6:bbfrk3s) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/pkg/slayers/pkt_auth.go#L280)):*
> ```Go
> // The resulting MAC is written to macBuffer (appending, if necessary),
> // and returned as a slice of length 16.
> func ComputeAuthCMAC(
> ```

I think this function is doing too much. (Which is also indicated by the number of arguments)

I would split this into three parts:

1. Constructing cipher
2. Computing the MAC input
3. Calculating the MAC

Out of these 3 things, I think only the second one belongs conceptually into the slayers package.

Slayers and subpackages are designed as a parsing/encoding layers. They should not do any complex logic.
(Currently we have the infamous `path.Path.Reverse` method which violates this rule)

I suggest we create a new  SPAO related package `pkg/spao` where we can move cipher construction (if even necessary)

As for the calculating the MAC: I don't think these needs to be abstracted in a function and can be done by the caller directly.
___
*[`pkg/slayers/pkt_auth.go` line 367 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIllk0WAAwHa4DYz0mG:-NIllk0WAAwHa4DYz0mH:b-a6awho) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/pkg/slayers/pkt_auth.go#L367)):*
> ```Go
> // now = ts+spaoTS⋅𝑞, (where q := 6 ms and ts =  info[0].Timestamp, i.e.,
> // the timestamp field in the first InfoField).
> func ComputeSPAORelativeTimestamp(ts uint32, now time.Time) (uint32, error) {
> ```

I think this would also be a candidate for the `spao` package alluded to above.
That would also make for nicer names on the caller side `spao.RelativeTimestamp()`
___
*[`pkg/slayers/pkt_auth.go` line 378 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIlmL_eCNLG02Isz77T:-NIlmL_eCNLG02Isz77U:bthwsp8) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/pkg/slayers/pkt_auth.go#L378)):*
> ```Go
> // then = ts + spaoTS⋅𝑞, (where q := 6 ms and ts =  info[0].Timestamp, i.e.,
> // the timestamp field in the first InfoField).
> func TimeFromRelativeTimestamp(ts uint32, spaoTS uint32) time.Time {
> ```

This function name is too generic. There is nothing that ties it to spao.

If we would move it to the spao package, this would read very well as `spao.Time()`
___
*[`router/dataplane.go` line 130 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIlppN7CxwNCt4Vkk7x:-NIlppN7CxwNCt4Vkk7y:btd6b1b) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/router/dataplane.go#L130)):*
> ```Go
> 	// zeroBuffer will be used to reset the Authenticator option in the
> 	// scionPacketProcessor.OptAuth
> 	zeroBuffer = make([]byte, 16)
> ```

I would allocate a zeroBuffer per packet processor.

I'm not exactly sure what the performance implications are of sharing this buffer, if the go routines are scheduled on different cores.
___
*[`router/dataplane.go` line 133 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIlnyzj73oKvZHuesrQ:-NIlnyzj73oKvZHuesrR:bjgjmww) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/router/dataplane.go#L133)):*
> ```Go
> )
> 
> type drkeyProvider interface {
> ```

This fits on one line.



_Suggestion:_
```Go
type drkeyProvider interface {
	GetAuthKey(validTime time.Time, dstIA addr.IA, dstAddr net.Addr) (drkey.Key, error)
}
```


<!-- Sent from Reviewable.io -->

2022-12-09 15:13 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 13 of 23 files reviewed, 5 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`pkg/slayers/pkt_auth.go` line 280 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIlhFcD1fPQzcaZHnh5:-NIrRZMT02VL8ywZ4r1w:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/pkg/slayers/pkt_auth.go#L280)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I think this function is doing too much. (Which is also indicated by the number of arguments)

I would split this into three parts:

1. Constructing cipher
2. Computing the MAC input
3. Calculating the MAC

Out of these 3 things, I think only the second one belongs conceptually into the slayers package.

Slayers and subpackages are designed as a parsing/encoding layers. They should not do any complex logic.
(Currently we have the infamous `path.Path.Reverse` method which violates this rule)

I suggest we create a new  SPAO related package `pkg/spao` where we can move cipher construction (if even necessary)

As for the calculating the MAC: I don't think these needs to be abstracted in a function and can be done by the caller directly.





</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 367 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIllk0WAAwHa4DYz0mG:-NIrRYUdAbBR7wX8QrJR:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/pkg/slayers/pkt_auth.go#L367)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I think this would also be a candidate for the `spao` package alluded to above.
That would also make for nicer names on the caller side `spao.RelativeTimestamp()`

</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 378 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIlmL_eCNLG02Isz77T:-NIrRY93EjYCdqKTsv8b:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/pkg/slayers/pkt_auth.go#L378)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

This function name is too generic. There is nothing that ties it to spao.

If we would move it to the spao package, this would read very well as `spao.Time()`
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 130 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIlppN7CxwNCt4Vkk7x:-NIrMNo32on92-4hSQ0v:b-volj22) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/router/dataplane.go#L130)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I would allocate a zeroBuffer per packet processor.

I'm not exactly sure what the performance implications are of sharing this buffer, if the go routines are scheduled on different cores.
</blockquote></details>

I can change it, but how is this different from sharing the errors above from different go routines? This buffer is expected to be read-only after initialization.  
___
*[`router/dataplane.go` line 133 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIlnyzj73oKvZHuesrQ:-NIrRNOT799Xkd5thC5p:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/router/dataplane.go#L133)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

This fits on one line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-12 11:28 UTC, oncilla reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: all files reviewed, 1 unresolved discussion (waiting on @JordiSubira)

___
*[`router/dataplane.go` line 130 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIlppN7CxwNCt4Vkk7x:-NJ54lNr6lHe8zfibrDq:bjmnnvh) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/router/dataplane.go#L130)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I can change it, but how is this different from sharing the errors above from different go routines? This buffer is expected to be read-only after initialization.  
</blockquote></details>

Conceptually, no difference. I'm also not sure if the have a performance impact.


<!-- Sent from Reviewable.io -->

2022-12-12 11:57 UTC, matzf requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira)

___
*[`pkg/slayers/pkt_auth.go` line 280 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIlhFcD1fPQzcaZHnh5:-NJ56hOuBhCiyLwqVs38:bspb3wv) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/pkg/slayers/pkt_auth.go#L280)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done.
</blockquote></details>

While I don't like the long list of parameters either, I don't really agree; why is it better to move this logic out to the caller? It's the same logic for _every_ caller.

Especially if we now move things to a `spao` package, I think it makes more sense to have the full `ComputeAuthCMAC` function to implement the entire logic for the `AES-CMAC` algorithm. 
IMO, there should be a separate function for every SPAO algorithm type. If you look at `SHA1-AES-CBC`, the only other algorithm type currently specified, to me it seems quite clear that computing the hash and MAC is exactly something that the library should be taking care of, not the caller.
___
*[`pkg/spao/timestamp.go` line 15 at r13](https://reviewable.io/reviews/scionproto/scion/4255#-NJ597UJ435tdqEtV4-E:-NJ597UJ435tdqEtV4-F:b-t07x2t) ([raw file](https://github.com/scionproto/scion/blob/00a168f252e22584b953968d760b45516c0434e4/pkg/spao/timestamp.go#L15)):*
> ```Go
> // limitations under the License.
> 
> package spao
> ```

If we have this spao package, then I think the entire content of `pkt_auth.go` file should be moved here (and renamed) too. In particular, the types `PacketAuthOption`  (just `spao.Option`?), `PacketAuthAlg`, `PacketAuthSPI`, etc. and all the constants.


<!-- Sent from Reviewable.io -->

2022-12-29 17:34 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 16 of 27 files reviewed, 2 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`pkg/slayers/pkt_auth.go` line 280 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIlhFcD1fPQzcaZHnh5:-NJegIng7ZOvXqsBe79E:b-rqzfn5) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/pkg/slayers/pkt_auth.go#L280)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

While I don't like the long list of parameters either, I don't really agree; why is it better to move this logic out to the caller? It's the same logic for _every_ caller.

Especially if we now move things to a `spao` package, I think it makes more sense to have the full `ComputeAuthCMAC` function to implement the entire logic for the `AES-CMAC` algorithm. 
IMO, there should be a separate function for every SPAO algorithm type. If you look at `SHA1-AES-CBC`, the only other algorithm type currently specified, to me it seems quite clear that computing the hash and MAC is exactly something that the library should be taking care of, not the caller.
</blockquote></details>

Okay, not too convinced about the organization of this. At the moment, I have decided to move the logic for the `ComputeAuthCMAC` to the `spao` package and leave the rest of the parsing in the `slayers` package. After revisiting it, I think it makes sense to encapsulate everything in the `ComputeAuthCMAC` as the input serialization will vary depending on the MAC algorithm used.
___
*[`pkg/spao/timestamp.go` line 15 at r13](https://reviewable.io/reviews/scionproto/scion/4255#-NJ54QLd7865DjXoWovt:-NKTwWCR2UGwE4z_PZ4M:b-7rl0jd) ([raw file](https://github.com/scionproto/scion/blob/00a168f252e22584b953968d760b45516c0434e4/pkg/spao/timestamp.go#L15)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Add a package level doc comment.
I think at least we should mention what spao stands for and a link to the related documentation pages

(see: https://go.dev/blog/godoc)
</blockquote></details>

done.
___
*[`pkg/spao/timestamp.go` line 15 at r13](https://reviewable.io/reviews/scionproto/scion/4255#-NJ597UJ435tdqEtV4-E:-NKTwYjfCNznjHF2Pnhn:boij7v1) ([raw file](https://github.com/scionproto/scion/blob/00a168f252e22584b953968d760b45516c0434e4/pkg/spao/timestamp.go#L15)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

If we have this spao package, then I think the entire content of `pkt_auth.go` file should be moved here (and renamed) too. In particular, the types `PacketAuthOption`  (just `spao.Option`?), `PacketAuthAlg`, `PacketAuthSPI`, etc. and all the constants.
</blockquote></details>

See comment on the `pkt_auth.go` file.


<!-- Sent from Reviewable.io -->

2023-01-05 19:24 UTC, matzf requested changes
> Reviewed 3 of 10 files at r13, 11 of 11 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: all files reviewed, 3 unresolved discussions (waiting on @JordiSubira and @oncilla)

___
*[`pkg/slayers/pkt_auth.go` line 280 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIlhFcD1fPQzcaZHnh5:-NKqs25b7M1vB7IubxiN:b437bdl) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/pkg/slayers/pkt_auth.go#L280)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Okay, not too convinced about the organization of this. At the moment, I have decided to move the logic for the `ComputeAuthCMAC` to the `spao` package and leave the rest of the parsing in the `slayers` package. After revisiting it, I think it makes sense to encapsulate everything in the `ComputeAuthCMAC` as the input serialization will vary depending on the MAC algorithm used.
</blockquote></details>

Ok, the ComputeAuthCMAC interface looks good to me.

I'd be interested to know what the reason for your choice to not move the parsing logic and type definitions to `spao` too.
___
*[`pkg/slayers/pkt_auth.go` line 78 at r14](https://reviewable.io/reviews/scionproto/scion/4255#-NKqrg70Cj2eJttEDya7:-NKqrg70Cj2eJttEDya8:b-bcstgp) ([raw file](https://github.com/scionproto/scion/blob/9f69982edf5f142eb8e93f9a8b5c12e794bdf801/pkg/slayers/pkt_auth.go#L78)):*
> ```Go
> 	// We round this up to 12B (authenticator option meta) + 1020B (max SCION header length)
> 	// To adapt to any possible path types.
> 	MACBufferSize = 1032
> ```

These three constants should go to the `spao` package (they are all concerned with the ComputeAuthCMAC functionality). Keep `fixAuthDataInputLen` private.
___
*[`pkg/spao/doc.go` line 21 at r14](https://reviewable.io/reviews/scionproto/scion/4255#-NKqsawH7SlIgRhWXZJX:-NKqsawH7SlIgRhWXZJY:b52zicc) ([raw file](https://github.com/scionproto/scion/blob/9f69982edf5f142eb8e93f9a8b5c12e794bdf801/pkg/spao/doc.go#L21)):*
> ```Go
> // It provides support for the MAC and the timestamp computations
> // used when utilizing the SPAO header.
> ```

Remove this newline here (otherwise it's not recognized as the package doc by godoc).


<!-- Sent from Reviewable.io -->

2023-01-06 12:15 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: 21 of 27 files reviewed, 3 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`pkg/slayers/pkt_auth.go` line 280 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIlhFcD1fPQzcaZHnh5:-NL5zdF-Aml0Aqm9p-Gx:bgkwi4t) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/pkg/slayers/pkt_auth.go#L280)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Ok, the ComputeAuthCMAC interface looks good to me.

I'd be interested to know what the reason for your choice to not move the parsing logic and type definitions to `spao` too.
</blockquote></details>

I decided to keep the SPAO layout and the parsing methods for the header in the same package as the rest of the parsing for the other headers, as @oncilla  mentioned in the past. I am open to move everything to the spao package, but I think it falls under the current criteria for slayers. Anyway, if someone has a stronger argument to move it outside the spao package, I will do it.
___
*[`pkg/slayers/pkt_auth.go` line 78 at r14](https://reviewable.io/reviews/scionproto/scion/4255#-NKqrg70Cj2eJttEDya7:-NL5yVxPCxmG1axDmoW9:b9skvxs) ([raw file](https://github.com/scionproto/scion/blob/9f69982edf5f142eb8e93f9a8b5c12e794bdf801/pkg/slayers/pkt_auth.go#L78)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

These three constants should go to the `spao` package (they are all concerned with the ComputeAuthCMAC functionality). Keep `fixAuthDataInputLen` private.
</blockquote></details>

Done. I kept the `AuthOptionMetadataLen` as I keep at the moment the layout and parsing logic for spao here.  As mentioned below, I do not have a strong opinion about it and open to change it.
___
*[`pkg/spao/doc.go` line 21 at r14](https://reviewable.io/reviews/scionproto/scion/4255#-NKqsawH7SlIgRhWXZJX:-NL6-VEh1cJu4YVXbGng:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9f69982edf5f142eb8e93f9a8b5c12e794bdf801/pkg/spao/doc.go#L21)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Remove this newline here (otherwise it's not recognized as the package doc by godoc).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-16 11:57 UTC, matzf approved these changes
> Reviewed 6 of 6 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)

___
*[`pkg/slayers/pkt_auth.go` line 280 at r12](https://reviewable.io/reviews/scionproto/scion/4255#-NIlhFcD1fPQzcaZHnh5:-NLuBqa-3ff4QQMywZeF:bkruud9) ([raw file](https://github.com/scionproto/scion/blob/5a7fdf0cb6864867e65bc84b02f3b4567191e353/pkg/slayers/pkt_auth.go#L280)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I decided to keep the SPAO layout and the parsing methods for the header in the same package as the rest of the parsing for the other headers, as @oncilla  mentioned in the past. I am open to move everything to the spao package, but I think it falls under the current criteria for slayers. Anyway, if someone has a stronger argument to move it outside the spao package, I will do it.
</blockquote></details>

Ok, thanks! Sure, I agree that it _also_ makes sense to be in `slayers`, and I don't object to leaving this here for now.

For the record, I think the arguments in favor (`+`) / against (`-`) moving the packet-auth option definitions and parsing functionality to the `spao` package are:

* `+` keep the SPAO related things together, as they will be used together
*  `-`keep all packet parsing related things together in `slayers`;  so a user of the library can quickly find all the things related to parsing a packet -- not very strong point IMO, as the TLV options only need to be parsed for processing (otherwise can be left opaque).
* `+` allows shorter names / less  `PacketAuth...`-clutter in `slayers` package
* `-` churn; no strong reason to move this _now_, can just as well move it later
___
*[`pkg/slayers/pkt_auth.go` line 78 at r14](https://reviewable.io/reviews/scionproto/scion/4255#-NKqrg70Cj2eJttEDya7:-NLuACCs1_ZiOgpboXmO:b-888lup) ([raw file](https://github.com/scionproto/scion/blob/9f69982edf5f142eb8e93f9a8b5c12e794bdf801/pkg/slayers/pkt_auth.go#L78)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done. I kept the `AuthOptionMetadataLen` as I keep at the moment the layout and parsing logic for spao here.  As mentioned below, I do not have a strong opinion about it and open to change it.
</blockquote></details>

Nit. Should be named either `PacketAuthOptionMetadataLen` or `PacketAuthMetadataLen` for consistency. 


<!-- Sent from Reviewable.io -->

2023-01-18 13:01 UTC, matzf approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255#-:-NM3y-xO-CAs0k_SIVth:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)



<!-- Sent from Reviewable.io -->

2023-01-20 15:53 UTC, oncilla reviewed
> Reviewed 5 of 11 files at r14, 4 of 6 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: all files reviewed, 1 unresolved discussion (waiting on @JordiSubira)

___
*[`pkg/spao/mac.go` line 112 at r16](https://reviewable.io/reviews/scionproto/scion/4255#-NMEqVX6ALSPIQ3wWZ8R:-NMEqVX6ALSPIQ3wWZ8S:b-vo3ybc) ([raw file](https://github.com/scionproto/scion/blob/440d4f7989c5c33501efbcb61ebe23e0683860b3/pkg/spao/mac.go#L112)):*
> ```Go
> 	pld []byte,
> ) (int, error) {
> ```

Given this will be on the "fast path" in the router, I think it would make sense to do bound check elimination.

https://go101.org/article/bounds-check-elimination.html

I suspect the compiler is not smart enough and will do many bound checks here. (Would need to verify this with the appropriate compiler flags or VS code extension though)

(non-blocking, needs to be benchmarked to justify)


<!-- Sent from Reviewable.io -->

2023-01-20 15:54 UTC, oncilla approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2023-01-23 13:52 UTC, oncilla approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2023-01-24 14:57 UTC, marcfrei approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 13 files at r9, 2 of 10 files at r13, 3 of 11 files at r14, 2 of 6 files at r15, 1 of 2 files at r16, 1 of 1 files at r17, 13 of 13 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255#-:-NMZ6NlCE7L0tsRKmrYh:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @JordiSubira and @oncilla)

___
*[`pkg/spao/doc.go` line 15 at r18](https://reviewable.io/reviews/scionproto/scion/4255#-NMZ8cri4Ns_fRtZoLoT:-NMZ8cri4Ns_fRtZoLoU:b-6gikrd) ([raw file](https://github.com/scionproto/scion/blob/35e484b31dcf0ab988407eac9193d08617232f97/pkg/spao/doc.go#L15)):*
> ```Go
> // limitations under the License.
> 
> // Package spao implements the logic needed to provide support to the
> ```

"support for"
___
*[`pkg/spao/mac.go` line 159 at r18](https://reviewable.io/reviews/scionproto/scion/4255#-NMZC1st93p-BYFznaSH:-NMZC1st93p-BYFznaSI:biz7l20) ([raw file](https://github.com/scionproto/scion/blob/35e484b31dcf0ab988407eac9193d08617232f97/pkg/spao/mac.go#L159)):*
> ```Go
> 	err := orig.SerializeTo(buf)
> 	if err != nil {
> 		return serrors.WrapStr("serializing path for reseting fields", err)
> ```

resetting
___
*[`router/dataplane.go` line 72 at r18](https://reviewable.io/reviews/scionproto/scion/4255#-NMZ-9yx9I11gKErosQw:-NMZ-9yx9I11gKErosQx:b-zhwlty) ([raw file](https://github.com/scionproto/scion/blob/35e484b31dcf0ab988407eac9193d08617232f97/router/dataplane.go#L72)):*
> ```Go
> 
> 	// e2eAuthHdrLen is the length in bytes of added information when a SCMP packet
> 	// needs to be authenticated: 16B (e2e.option.Len()) + 16 B(CMAC_tag.Len()).
> ```

16B (CMAC_tag.Len())
___
*[`router/dataplane.go` line 1637 at r18](https://reviewable.io/reviews/scionproto/scion/4255#-NMZ030l3em0x6pTdaO_:-NMZ030l3em0x6pTdaOa:b-hdf6za) ([raw file](https://github.com/scionproto/scion/blob/35e484b31dcf0ab988407eac9193d08617232f97/router/dataplane.go#L1637)):*
> ```Go
> 
> 	// Error messages must be authenticated.
> 	// Traceroute are OPTIONALLY authenticated ONLY IF the Request
> ```

request
___
*[`router/dataplane.go` line 1690 at r18](https://reviewable.io/reviews/scionproto/scion/4255#-NMZ2SPR7g1aJSpKWqfx:-NMZ2SPR7g1aJSpKWqfy:boveefl) ([raw file](https://github.com/scionproto/scion/blob/35e484b31dcf0ab988407eac9193d08617232f97/router/dataplane.go#L1690)):*
> ```Go
> 		key, err := p.drkeyProvider.GetAuthKey(now, scionL.DstIA, srcA)
> 		if err != nil {
> 			return nil, err
> ```

Wrap error with cannotRoute and "details"?
___
*[`router/dataplane.go` line 1693 at r18](https://reviewable.io/reviews/scionproto/scion/4255#-NMZ2dNa1ewvfo3P4lxu:-NMZ2dNa1ewvfo3P4lxv:boveefl) ([raw file](https://github.com/scionproto/scion/blob/35e484b31dcf0ab988407eac9193d08617232f97/router/dataplane.go#L1693)):*
> ```Go
> 		}
> 		if err := p.resetSPAOMetadata(now); err != nil {
> 			return nil, err
> ```

Wrap error with cannotRoute and "details"?
___
*[`router/dataplane.go` line 1728 at r18](https://reviewable.io/reviews/scionproto/scion/4255#-NMZ5AV7374Wyh9bMbNc:-NMZ5AV7374Wyh9bMbNd:b-uv9wrn) ([raw file](https://github.com/scionproto/scion/blob/35e484b31dcf0ab988407eac9193d08617232f97/router/dataplane.go#L1728)):*
> ```Go
> 	// For creating SCMP responses we use sender side.
> 	dir := slayers.PacketAuthSenderSide
> 	// TODO(JordiSubira): At the moment, We assume the later epoch at the moment.
> ```

Remove "At the moment, "
___
*[`tools/braccept/cases/scmp_expired_hop.go` line 144 at r18](https://reviewable.io/reviews/scionproto/scion/4255#-NMYq32vDYTGPWAhxKbW:-NMYq32vDYTGPWAhxKbX:b-kiv4vh) ([raw file](https://github.com/scionproto/scion/blob/35e484b31dcf0ab988407eac9193d08617232f97/tools/braccept/cases/scmp_expired_hop.go#L144)):*
> ```Go
> 
> // SCMPExpiredHopMessageBack tests a packet with an expired hop field. The relative timestamp
> // can be encoded in the SPAO header and send back to the src.
> ```

"sent back"? (multiple times in this file)


<!-- Sent from Reviewable.io -->

2023-01-24 15:15 UTC, marcfrei approved these changes
> Reviewed 4 of 4 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oncilla)



<!-- Sent from Reviewable.io -->

2023-01-24 15:16 UTC, marcfrei approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oncilla)



<!-- Sent from Reviewable.io -->

2023-01-25 11:20 UTC, merged