doc: design doc for end host without dispatcher
scionproto/scion pull request #4280
Opened 2022-10-11 09:06 UTC by matzf

Design document for proposal #3961.

[doc]

---

In a separate PR, once this is merged, I will attempt to improve the organisation of these design documents in and add a template.

2022-10-11 09:13 UTC, matzf commented
For the continued discussion: please continue discussing the overall idea in #3961, and discuss the specifics of the proposed design document in this PR here.

2022-10-25 09:09 UTC, marcfrei approved these changes
Thanks a lot, Matthias! I very much support this proposal, especially to have a convincing deployment story for mobile and small embedded platforms.

Another niche use-case that would benefit from this design are applications that rely on kernel or hardware based send and receive timestamps. In our ongoing time synchronization project we first tried to implement timestamping with a somewhat messy extension of the dispatcher and the ReliableSocket protocol over the UNIX domain socket before we finally decided not to have the default dispatcher on time server hosts and instead to listen directly on the end-host port from our application. This works for dedicated time servers but it wouldn't really be practical for end hosts where, for example, besides a time service client multiple other SCION based apps are deployed.

2022-10-25 09:09 UTC, marcfrei commented on doc/design/router-port-dispatch.rst
> +No SCMP Error messages for Port unreachable are sent. On the end host, there is simply no component that could trigger this. Instead, an ICMP port closed message for the UDP/IP port may be triggered.
`SCMP Error` > `SCMP error`, like above

2022-10-25 09:09 UTC, marcfrei commented on doc/design/router-port-dispatch.rst
> +.. Note:: This should not be considered a promise to never break compatiblity for end hosts again.
compatibility

2022-10-25 12:59 UTC, matzf commented on doc/design/router-port-dispatch.rst
> +.. Note:: This should not be considered a promise to never break compatiblity for end hosts again.
Thanks, done. Turns out my spell-checker ignores these admonition blocks...

2022-10-25 12:59 UTC, matzf commented on doc/design/router-port-dispatch.rst
> +No SCMP Error messages for Port unreachable are sent. On the end host, there is simply no component that could trigger this. Instead, an ICMP port closed message for the UDP/IP port may be triggered.
Done.

2022-10-25 13:14 UTC, marcfrei approved these changes

2022-11-10 09:59 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @matzf)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4280#-NGVwaD6ErVD7CYilfVf:-NGVyV_j7k5WNBN0diAJ:bx91rsn) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

One detail that has not been discussed yet is the SVC redirection.

Currently, the dispatcher delivers SVC packets to a random process that registered for this service.
Currently, we just have control service and discovery service that need to reply to SVC resolution.

As I see it, there are two ways of solve this problem:

- The router is currently configured with IP addresses where it dispatches SVC packets to. We could modify this list to be UDP addresses. The services then open 2 UDP ports. One for SVC redirects and one for the actual QUIC connections.

- The "SCMP daemon" handles the redirection directly. I.e., the Service registers the port where it will accept QUIC connections with the "SCMP daemon". The services then only have to open 1 UDP port.

I'm slightly preferring the first option because it seems more reliable, because it resolves less processes. E.g., if the SCMP daemon unexpectedly stops, all SVC redirects fail. Also, after it starts again, all the services would need to re-register.






</blockquote></details>

(fwiw, I played around with the second approach in a hackathon because it required no changes to the router. It is feasible, but requires quite some state management to handle edge cases.)

___


<!-- Sent from Reviewable.io -->

2022-11-11 08:41 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @oncilla)

___
*[`doc/design/router-port-dispatch.rst` line 168 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGRYQhJCbZjAdgagtCm:-NG_gyJo8rBaFw4dn3vo:b-tzgj69) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L168)):*
That's a very fair concern.

> Checking whether the shared application is installed is fairly simple and and the user can be instructed to install the right application, which is a one time operation.
From the complexity to a user it feels ~same as granting camera access for an application.
And as soon as this would make it to the kernel, the additional app is also no longer needed. (To be fair, that's gonna take some time)

I don't share this view. While such an approach may be appropriate for niche cases like SCION demo applications, this will not work for more "consumer" oriented applications that just want to make use of SCION whenever it is available. For example, consider a browser (let's say Brave) and/or some video chat tool (e.g. Zoom) add SCION support to their apps at some point. If these now suddenly prompt the user with "hey please install this third party application `SCION SCMP dispatcher` to make things even better", this would confuse and annoy a lot of people and only a tiny fraction would follow through.

Also, somebody would have to own the shared dependency application. That would probably need to be us -- maintaining a user-facing package for various different platforms does not seem fun.

> Furthermore, while SCMP messages are good for efficient fail-over, they are solely informational.
Everything should work without SCMP messages (if not, we need to address this).
I would not classify them as crucial (and nor should they be)

That's a good point. So we could just say, tough luck, no SCMPs on this platform. Or, alternatively, we could offload the SCMP quote parsing to the router as proposed, but strictly rate limit this -- as they are optional, dropping any fraction is fair game.

---

Alternative idea:

Set the SCION FlowID based on the source port for all UDP packets. The flow ID is a 20 bit field, so we have room for the port plus 4 free bits. SCMP errors (already now) use the flow ID of the offending packet.
When delivering the SCMP message to the end host, the underlay destination port is determined by extracting the corresponding bits from the flow ID of the SCMP message. The quote does not have to be inspected.
This approach could also be used for SCMP Echo and Traceroute replies.

Setting the FlowID in this particular way would be required only for hosts that want packets to be port-dispatched by the router. Once we don't need this anymore (because e.g. SCION support is available from the operating system), the Flow ID field can again be chosen as an arbitrary high-entropy identifier. 


<!-- Sent from Reviewable.io -->

2022-11-11 09:06 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4280#-NGVwaD6ErVD7CYilfVf:-NG_r8Qf23ewHXj8-XT2:b-6jr5lx) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

(fwiw, I played around with the second approach in a hackathon because it required no changes to the router. It is feasible, but requires quite some state management to handle edge cases.)
</blockquote></details>

Thanks for pointing this out!

The first approach seems perfectly appropriate to me. I'll include this in the document.
Just for the record, the 2 ports are only necessary due to "implementation details" in snet/appnet. The service could also listen on the same UDP/IP port for both purposes, the application could internally dispatch packets for the two cases (based on the SCION destination address type).

___


<!-- Sent from Reviewable.io -->

2022-11-11 13:30 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @matzf)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4280#-NGVwaD6ErVD7CYilfVf:-NGasQUj0vAIimo6FciE:b-xonxvu) (no related file):*
> The service could also listen on the same UDP/IP port for both purposes, the application could internally dispatch packets for the two cases (based on the SCION destination address type).

True. But I think it is easier to let the kernel take care of doing the dispatching instead of us needing to implement additional dispatching logic.

___


<!-- Sent from Reviewable.io -->

2022-11-14 13:27 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`doc/design/router-port-dispatch.rst` line 27 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGq8iE0-wO6KAhIbMxl:-NGq8iE0-wO6KAhIbMxm:b-m1g4w2) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L27)):*
> ```reStructuredText
> The application then receives and transmits SCION packets (exclusively) over this unix domain socket connection.
> 
> The dispatcher also implements other end host stack functionality; in particular, it replies to certain SCMP messages like SCMP Echo (ping).
> ```

Another



_Code quote:_
```reStructuredText
 other
```
___
*[`doc/design/router-port-dispatch.rst` line 34 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGq9ox26lT-CE5EgjGe:-NGq9ox26lT-CE5EgjGf:b62o1np) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L34)):*
> ```reStructuredText
> 
> - It is a single point of failure for the SCION network stack of a host. If it goes down, a lot of processes (control service, gateway, tooling) go haywire.
> - It lives in userspace, moving every forwarded packet from kernelspace to userspace and back to kernelspace, meaning a performance hit.
> ```

user space; or at least try to make it consistent, e.g., above we have user space



_Code quote:_
```reStructuredText
userspace
```
___
*[`doc/design/router-port-dispatch.rst` line 159 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGqF0F7DZS866C3dyaN:-NGqF0F85Jm_Hg1pIg3S:b-79nrxq) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L159)):*
> ```reStructuredText
> - it also fixes many of the problems listed above related to unix domain sockets, reconnection, etc.
> 
> However, this still requires a shared component on the end-host if multiple applications want to use SCION concurrently.
> ```

end host



_Code quote:_
```reStructuredText
end-host
```
___
*[`doc/design/router-port-dispatch.rst` line 168 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGRYQhJCbZjAdgagtCm:-NGqGWl_-_XgYy0Nxqm2:bc08rgo) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L168)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

That's a very fair concern.

> Checking whether the shared application is installed is fairly simple and and the user can be instructed to install the right application, which is a one time operation.
From the complexity to a user it feels ~same as granting camera access for an application.
And as soon as this would make it to the kernel, the additional app is also no longer needed. (To be fair, that's gonna take some time)

I don't share this view. While such an approach may be appropriate for niche cases like SCION demo applications, this will not work for more "consumer" oriented applications that just want to make use of SCION whenever it is available. For example, consider a browser (let's say Brave) and/or some video chat tool (e.g. Zoom) add SCION support to their apps at some point. If these now suddenly prompt the user with "hey please install this third party application `SCION SCMP dispatcher` to make things even better", this would confuse and annoy a lot of people and only a tiny fraction would follow through.

Also, somebody would have to own the shared dependency application. That would probably need to be us -- maintaining a user-facing package for various different platforms does not seem fun.

> Furthermore, while SCMP messages are good for efficient fail-over, they are solely informational.
Everything should work without SCMP messages (if not, we need to address this).
I would not classify them as crucial (and nor should they be)

That's a good point. So we could just say, tough luck, no SCMPs on this platform. Or, alternatively, we could offload the SCMP quote parsing to the router as proposed, but strictly rate limit this -- as they are optional, dropping any fraction is fair game.

---

Alternative idea:

Set the SCION FlowID based on the source port for all UDP packets. The flow ID is a 20 bit field, so we have room for the port plus 4 free bits. SCMP errors (already now) use the flow ID of the offending packet.
When delivering the SCMP message to the end host, the underlay destination port is determined by extracting the corresponding bits from the flow ID of the SCMP message. The quote does not have to be inspected.
This approach could also be used for SCMP Echo and Traceroute replies.

Setting the FlowID in this particular way would be required only for hosts that want packets to be port-dispatched by the router. Once we don't need this anymore (because e.g. SCION support is available from the operating system), the Flow ID field can again be chosen as an arbitrary high-entropy identifier. 
</blockquote></details>

I find this alternative idea just fine if we want to spare the quoted packet inspection.  How are SCMP errors using the flowID now? In a similar way to decide the upper-layer process that must process the packet?


<!-- Sent from Reviewable.io -->

2022-11-15 09:36 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @JordiSubira, @marcfrei, and @oncilla)

___
*[`doc/design/router-port-dispatch.rst` line 27 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGq8iE0-wO6KAhIbMxl:-NGuYBJb5llMrnkcOLlV:bnoxinu) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L27)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Another
</blockquote></details>

Hmm, "functionality" is in plural here (uncountable) . To me, "other" seems better, or at least also acceptable.
___
*[`doc/design/router-port-dispatch.rst` line 34 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGq9ox26lT-CE5EgjGe:-NGuZXTm8fXWfmQJByad:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L34)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

user space; or at least try to make it consistent, e.g., above we have user space
</blockquote></details>

Done.
___
*[`doc/design/router-port-dispatch.rst` line 159 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGqF0F7DZS866C3dyaN:-NGuZYGnA4XxsjbaLAqN:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L159)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

end host
</blockquote></details>

Done.
___
*[`doc/design/router-port-dispatch.rst` line 168 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGRYQhJCbZjAdgagtCm:-NGuZlDb9I_iXh65TOt-:b5k3iao) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L168)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I find this alternative idea just fine if we want to spare the quoted packet inspection.  How are SCMP errors using the flowID now? In a similar way to decide the upper-layer process that must process the packet?
</blockquote></details>

The FlowID is meant to be consumed by network devices, in particular the routers, to allow safely processing packets in parallel; only packets with the same FlowID are required to be kept in order.

Currently, this is not currently used in any more specific way for SCMPs. The router sets the FlowID of any SCMP error/traceroute response packet to the FlowID of the offending/request packet. That's simply the most sensible choice, but currently nothing depends on this behavior; with the proposed alternative idea, this would become mandatory.

The application process to receive an SCMP error message is determined by inspecting the source UDP port from the quoted offending message. SCMP traceroute or echo reply packets are delivered to applications based on the identifier field of these messages. Currently this happens in the dispatcher, in the long term future, this would happen in the OS network stack.


<!-- Sent from Reviewable.io -->

2022-11-15 09:46 UTC, JordiSubira reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280#-:-NGufdJq2gsyDBtZkXKW:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`doc/design/router-port-dispatch.rst` line 27 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGq8iE0-wO6KAhIbMxl:-NGueDIE8q8MNVEoxBhL:b9cxri5) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L27)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Hmm, "functionality" is in plural here (uncountable) . To me, "other" seems better, or at least also acceptable.
</blockquote></details>

No big deal, it can behave as both according to the dict.
___
*[`doc/design/router-port-dispatch.rst` line 168 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGRYQhJCbZjAdgagtCm:-NGuetL8DyUKeCBiFvtK:b-stz2te) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L168)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The FlowID is meant to be consumed by network devices, in particular the routers, to allow safely processing packets in parallel; only packets with the same FlowID are required to be kept in order.

Currently, this is not currently used in any more specific way for SCMPs. The router sets the FlowID of any SCMP error/traceroute response packet to the FlowID of the offending/request packet. That's simply the most sensible choice, but currently nothing depends on this behavior; with the proposed alternative idea, this would become mandatory.

The application process to receive an SCMP error message is determined by inspecting the source UDP port from the quoted offending message. SCMP traceroute or echo reply packets are delivered to applications based on the identifier field of these messages. Currently this happens in the dispatcher, in the long term future, this would happen in the OS network stack.
</blockquote></details>

Thanks for the explanation! If we decide we adopt this alternative, I'd summarize and add this explanation.


<!-- Sent from Reviewable.io -->

2023-02-21 10:39 UTC, marcfrei approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`doc/design/router-port-dispatch.rst` line 83 at r5](https://reviewable.io/reviews/scionproto/scion/4280#-NOnYGtAC5eMXND7Q7vl:-NOnYGtAC5eMXND7Q7vm:b-97dvvn) ([raw file](https://github.com/scionproto/scion/blob/4a1f243cf8afe511dd682aad5e67fb4ea066dc30/doc/design/router-port-dispatch.rst#L83)):*
> ```reStructuredText
> ^^^^^^^^^^^
> 
> The remaining functionality of the dispatcher, namely responding to SCMP echo requests, is implemented to a new, very simple "SCMP daemon".
> ```

"implemented in"?


<!-- Sent from Reviewable.io -->

2023-02-23 13:49 UTC, marcfrei approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`doc/design/router-port-dispatch.rst` line 168 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGRYQhJCbZjAdgagtCm:-NOySDya09bbBeaFDiMf:bpmmvtu) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L168)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Any more opinions on this point?

Summary of the proposed options:
- SCMP daemon (leading to no SCMPs on systems where this is not running/available)
- SCMP quote parsing in the router (as currently described in the design document), possibly with strict rate limits
- (ab-)using the FlowID to encode an underlay port for SCMP error message replies.

My current personal favorite is the FlowID hack.
I understood that @oncilla, you preferred the SCMP daemon variant over the parsing in the router, but what is your opinion about the FlowID hack?
</blockquote></details>

Two questions to better understand the three proposed alternatives:
- How likely is it that some future SCMP message types will not be "solely informational"? I.e., for example, that a particular SCMP error message type will become important for applications on the end host to work properly? I think this question is important because the new design really should not (or cannot) assume the presence of a shared SCMP daemon on the end host.
- Setting the FlowID based on the underlay port only for SCMP traffic wouldn't work because the assumption here is that peeking into the L4 payload could be too expensive also at the source of an SCMP message, right?


<!-- Sent from Reviewable.io -->

2023-02-23 14:33 UTC, marcfrei approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`doc/design/router-port-dispatch.rst` line 168 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGRYQhJCbZjAdgagtCm:-NOyeHUw5Ewab0PUqAfW:b-xck6qn) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L168)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

> How likely is it that some future SCMP message types will not be "solely informational"? I.e., for example, that a particular SCMP error message type will become important for applications on the end host to work properly? I think this question is important because the new design really should not (or cannot) assume the presence of a shared SCMP daemon on the end host.

The "interface down" error messages already fall into this category, to some extent. While applications need to be aware that they cannot solely rely on these SCMP error messages to determine path health (as the SCMPs are rate limited and e.g. are not available if the first router on the path is dead), having the information about where the path failure occurs can help _a lot_ in handling this. Otherwise applications are just tapping in the dark; in many cases it's hard to even tell whether the path is down or whether the remote host or application failed. So applications either need to give up after some retries, pessimistically avoid a large section of the internet ("the failure might be in _any_ of the ASes on this path, so avoid them all"), or explore large number of paths to determine the broken link.


> Setting the FlowID based on the underlay port only for SCMP traffic wouldn't work because the assumption here is that peeking into the L4 payload could be too expensive also at the source of an SCMP message, right?

The idea was to set this "specially crafted" FlowID already when sending out the UDP packets. For SCMP error messages, we just use the FlowID of the offending packet (i.e. the value in the first line of the packet). The router already does this, and this seems like a sensible choice anyway.
The good thing is that only the sending host needs to be aware of this scheme. The bad bit is that all applications running on this host need to be aware of this scheme.
</blockquote></details>

Thanks! By using the underlay source port as the FlowID,  applications would loose the ability to implement recommendations like, e.g, the use of flow labels in QUIC [1]. This wouldn't be too big of a disadvantage?

[1] https://www.rfc-editor.org/rfc/rfc9000.html#name-use-of-ipv6-flow-label-and- 


<!-- Sent from Reviewable.io -->

2023-02-23 18:21 UTC, marcfrei approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`doc/design/router-port-dispatch.rst` line 168 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGRYQhJCbZjAdgagtCm:-NOzTjo86mLE4B3x4yF2:bxnvc4) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L168)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Correct, although there are still 4 bits left to play with :wink: 
In the particular case, it seems unproblematic; the recommendation is to avoid reusing the same flow ID when migrating QUIC connection to a new address. When a new socket opened for this new address to migrate to, it will be assigned a different (random) port and thus, with the proposed approach, automatically use a different flow ID.

I don't know how big of a problem this is in general. Reading [RFC6437 ](https://www.rfc-editor.org/rfc/rfc6437.html), it doesn't feel like this would be super terrible though.
</blockquote></details>

So using the FlowID seems to have no obvious disadvantages so far, ignoring the fact that the source port would appear three times in an outgoing UDP/SCION packet...


<!-- Sent from Reviewable.io -->

2023-04-14 11:38 UTC, JordiSubira commented
For the record, I've started with the implementation of the part among which there's consensus (i.e., I'll leave the SCMP daemon for later). Any idea if how long and what range should we use to have compatibility.

2023-04-18 14:16 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 2 unresolved discussions (waiting on @marcfrei and @matzf)

___
*[`doc/design/router-port-dispatch.rst` line 168 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGRYQhJCbZjAdgagtCm:-NTE7HVZ9Njy65ZKED16:bbzjdbc) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L168)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

So using the FlowID seems to have no obvious disadvantages so far, ignoring the fact that the source port would appear three times in an outgoing UDP/SCION packet...
</blockquote></details>

Sorry for the late response.

This is quite an important topic, and the decision has a large impact on current and future deployments.
Because these changes are so fundamental, I have also brought up this topic internally at Anapaya, and we have discussed them extensively.

There are three main concerns that we have when changing such fundamental parts of the networking stack.

1. Can the change be rolled out incrementally?
2. Do we fragment the ecosystem?
3. Do we obstruct future progress?

Concern 1 is very important to us (Anapaya), because we already have a large productive deployment which must be updated incrementally.
We cannot have a single update day where the behavior of a full AS changes atomically. We must provide an interrupt free upgrade path on the granularity of one host/router.

Concern 2 is important if we want to keep the ecosystem coherent. It is also required if we want to support ASes that contain components from different vendors.

Concern 3 is important to us long-term. We do not want to back ourselves into a corner that we cannot get out of anymore. While this discussion is about an implementation detail that will not be put in the standard, we think it will still serve as a reference implementation and will be considered as the de-facto standard.

## Thoughts

Given these three concerns, here are our thoughts on the proposed solutions:

### Doing all the processing in the endhost (replace dispatcher ebpf solution)

This would be the cleanest solution because it does not introduce yet another layer violation.
Conceptually, the underlay port should not be tied to the UDP/SCION port. This change is compatible with the current deployment,
and does not fragment the ecosystem. It can also be incrementally rolled out.

However, it obstructs future progress in the mobile platforms. Running ebpf on an android host requires either root
privileges or a system code signature. Whether it is supported on iOS, is unknown to me.

### UDP/SCION Port == Underlay Port && SCMP Daemon does SCMP error dispatching

This solution introduces a layer violation by tying the underlay to the UDP/SCION layer.
It is incrementally deployable with the proposed reserved port range for packets where the rewrite should happen.
We run the risk of fragmenting the ecosystem, but it is rather low. The current dispatcher allocates ports 
sequentially in the range [32768-65535](https://github.com/scionproto/scion/blob/8b41109bcfdaa8c5dc2fd49a4e3a3274aa40de16/dispatcher/dispatcher.go#L66)
If the reserved range is chosen carefully, it is very unlikely that there is a clash.

The drawback of this approach is the SCMP daemon. According to @marcfrei it is hard to implement it on mobile platforms.
Thus, we might obstruct future progress with this solution.

###  UDP/SCION Port == Underlay Port && SCMP Quote parsing

This solution is essentially the same as the solution above, except that the SCMP Quote is read by the router and the underlay port is set to the original source port.
Same as above, this change should be incrementally deployable, and we run low risk of fragmenting the ecosystem.

The additional benefit is that the end hosts do not need the SCMP daemon to receive SCMP error messages. This will simplify deployments on mobile platforms a lot. However, this has a severe performance impact. Limiting the performance of routers (that are under heavy load) for a hack because the OS of a mobile platform can not provide the necessary tooling feels off.

### Flow ID

This solution introduces two layer violations. It ties both the underlay and the flow id to UDP/SCION.
This change can be incrementally rolled out, if we assume that the flow ID has not been used so far.
However, it is important to note that all other proposals above are AS-local changes. This change on the other hand requires all ASes to behave in an expected manner around the flow ID (re-using flow id for scmp error packet)

Tying the flow ID to the source port limits the number of different flows to 16. This might not be an issue for client applications that can open as many ports as they want, but on the server side, this can be quite restrictive.

According to [RFC6437](https://www.rfc-editor.org/rfc/rfc6437) "flow label values should be chosen such that their bits exhibit a high degree of variability".
This would be violated because even though ports can be chosen from the 16-bit space, usually they have very low variability.
Of course, the flow ID is not the single input, so it might be fine. But I don't really like going against an IPv6 RFC that was the inspiration for our flow ID.

While the flow ID is currently not used by scionproto, we (Anapaya) are actively working on RSS that includes the flow ID. We were planning to use in the order of hundreds of flow IDs per connection. Limiting the number of different flows to 16 is concerning to us as this heavily restricts the possible values.


## Conclusion

While replacing the dispatcher with an ebpf program that deals with the rewriting would be our favorite solution, we understand that it is not feasible at the moment for many platforms. In the interest of bringing native SCION applications to the end hosts, I'm in favor of going forward with one of the other proposals.

However the choice is not obvious to me yet. I would push against sticking it in the flow ID, for the reasons outlined above.  It is one more layer violation and limits the usefulness of the flow ID to much for its actual purpose .


Parsing the quote on the router is quite expensive. Essentially, we at least double the parsing effort. It would be best to avoid this if possible. Thus, I'm torn between parsing the SCMP packets in the router, and having an SCMP daemon on the end host. If we were to implement the parsing option, we will definitely start with SCMP rate limiting.

@marcfrei could you elaborate on the challenges of implementing an SCMP daemon on mobile platforms?


<!-- Sent from Reviewable.io -->

2023-04-20 16:26 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 2 unresolved discussions (waiting on @oncilla)

___
*[`doc/design/router-port-dispatch.rst` line 168 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGRYQhJCbZjAdgagtCm:-NTTWauQDLqb4_y7jUZ2:b-8vs893) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L168)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Sorry for the late response.

This is quite an important topic, and the decision has a large impact on current and future deployments.
Because these changes are so fundamental, I have also brought up this topic internally at Anapaya, and we have discussed them extensively.

There are three main concerns that we have when changing such fundamental parts of the networking stack.

1. Can the change be rolled out incrementally?
2. Do we fragment the ecosystem?
3. Do we obstruct future progress?

Concern 1 is very important to us (Anapaya), because we already have a large productive deployment which must be updated incrementally.
We cannot have a single update day where the behavior of a full AS changes atomically. We must provide an interrupt free upgrade path on the granularity of one host/router.

Concern 2 is important if we want to keep the ecosystem coherent. It is also required if we want to support ASes that contain components from different vendors.

Concern 3 is important to us long-term. We do not want to back ourselves into a corner that we cannot get out of anymore. While this discussion is about an implementation detail that will not be put in the standard, we think it will still serve as a reference implementation and will be considered as the de-facto standard.

## Thoughts

Given these three concerns, here are our thoughts on the proposed solutions:

### Doing all the processing in the endhost (replace dispatcher ebpf solution)

This would be the cleanest solution because it does not introduce yet another layer violation.
Conceptually, the underlay port should not be tied to the UDP/SCION port. This change is compatible with the current deployment,
and does not fragment the ecosystem. It can also be incrementally rolled out.

However, it obstructs future progress in the mobile platforms. Running ebpf on an android host requires either root
privileges or a system code signature. Whether it is supported on iOS, is unknown to me.

### UDP/SCION Port == Underlay Port && SCMP Daemon does SCMP error dispatching

This solution introduces a layer violation by tying the underlay to the UDP/SCION layer.
It is incrementally deployable with the proposed reserved port range for packets where the rewrite should happen.
We run the risk of fragmenting the ecosystem, but it is rather low. The current dispatcher allocates ports 
sequentially in the range [32768-65535](https://github.com/scionproto/scion/blob/8b41109bcfdaa8c5dc2fd49a4e3a3274aa40de16/dispatcher/dispatcher.go#L66)
If the reserved range is chosen carefully, it is very unlikely that there is a clash.

The drawback of this approach is the SCMP daemon. According to @marcfrei it is hard to implement it on mobile platforms.
Thus, we might obstruct future progress with this solution.

###  UDP/SCION Port == Underlay Port && SCMP Quote parsing

This solution is essentially the same as the solution above, except that the SCMP Quote is read by the router and the underlay port is set to the original source port.
Same as above, this change should be incrementally deployable, and we run low risk of fragmenting the ecosystem.

The additional benefit is that the end hosts do not need the SCMP daemon to receive SCMP error messages. This will simplify deployments on mobile platforms a lot. However, this has a severe performance impact. Limiting the performance of routers (that are under heavy load) for a hack because the OS of a mobile platform can not provide the necessary tooling feels off.

### Flow ID

This solution introduces two layer violations. It ties both the underlay and the flow id to UDP/SCION.
This change can be incrementally rolled out, if we assume that the flow ID has not been used so far.
However, it is important to note that all other proposals above are AS-local changes. This change on the other hand requires all ASes to behave in an expected manner around the flow ID (re-using flow id for scmp error packet)

Tying the flow ID to the source port limits the number of different flows to 16. This might not be an issue for client applications that can open as many ports as they want, but on the server side, this can be quite restrictive.

According to [RFC6437](https://www.rfc-editor.org/rfc/rfc6437) "flow label values should be chosen such that their bits exhibit a high degree of variability".
This would be violated because even though ports can be chosen from the 16-bit space, usually they have very low variability.
Of course, the flow ID is not the single input, so it might be fine. But I don't really like going against an IPv6 RFC that was the inspiration for our flow ID.

While the flow ID is currently not used by scionproto, we (Anapaya) are actively working on RSS that includes the flow ID. We were planning to use in the order of hundreds of flow IDs per connection. Limiting the number of different flows to 16 is concerning to us as this heavily restricts the possible values.


## Conclusion

While replacing the dispatcher with an ebpf program that deals with the rewriting would be our favorite solution, we understand that it is not feasible at the moment for many platforms. In the interest of bringing native SCION applications to the end hosts, I'm in favor of going forward with one of the other proposals.

However the choice is not obvious to me yet. I would push against sticking it in the flow ID, for the reasons outlined above.  It is one more layer violation and limits the usefulness of the flow ID to much for its actual purpose .


Parsing the quote on the router is quite expensive. Essentially, we at least double the parsing effort. It would be best to avoid this if possible. Thus, I'm torn between parsing the SCMP packets in the router, and having an SCMP daemon on the end host. If we were to implement the parsing option, we will definitely start with SCMP rate limiting.

@marcfrei could you elaborate on the challenges of implementing an SCMP daemon on mobile platforms?

</blockquote></details>

Thanks for the very structured write up, that's great. For what it's worth, I believe we've implicitly considered exactly these three concerns when we discussed this design, but it's great to spell this out explicitly.

As a general point regarding the "layer violation" objection. The way I see the UDP underlay is that this is already a stop-gap approach. There is a mismatch between the address type in the SCION header (IP v4/v6) and the underlay (UDP, i.e. IP + port). Now, actually having the UDP port to the SCION address would seem very odd. Instead, the "right" approach should be to have IP directly as the underlay.
My guess as to why we don't have IP underlay directly (yet) is that it's just much more practical to use UDP compared to defining a new protocol number which would certainly be dropped by all kinds of middleboxes. So, the UDP underlay is just a pragmatic, convenient choice to aid deployability. 
So, the UDP underlay is already "wrong", so milking this UDP underlay a bit more to aid deployability _more_ seems fair game.
I admit this is a bit of a foot-in-the-door argument.

What we ideally want to achieve is to make it possible to deploy multiple SCION-native applications independently and fully self-contained. There should be no requirement for any non-standard system components to be installed or running, and no coordination between different applications.
The ebpf-dispatcher approach does not achieve this (generally, not only on mobile plat [...]

2023-04-21 11:11 UTC, marcfrei commented
> ... could you elaborate on the challenges of implementing an SCMP daemon on mobile platforms?

I don't know whether and how this could work on Android but at least on iOS/iPadOS there is as far as I can see simply no concept of a user-installable background daemon. There is however the possibility to install and enable a separate app that provides a so-called Network Extension (https://developer.apple.com/documentation/networkextension) which could come close to what is needed here.

We would need to investigate whether it is feasible in principle to implement SCMP daemon functionality based on what the network extension model allows. In addition, there's then also the question how such a network extension would work together with other network extensions. VPN apps (like, e.g. Tailscale) have to be implemented as network extensions and at least VPN extensions are mutually exclusive among each other. Independent of the technical feasibility it also seems to me that such a solution would be rather finicky to manage for typical end-users. Installing a network extension requires entry of the device passcode which already feels a little scary to begin with. It's then very easy to imagine support situations where a SCION-based application doesn't work as expected. The provider of such an app would need to ask the user to check whether the separate SCION SCMP daemon app that provides the network extension is already installed and enabled correctly. The approach thus wouldn't really satisfy Matthias's requirement:

> What we ideally want to achieve is to make it possible to deploy multiple SCION-native applications independently and fully self-contained. There should be no requirement for any non-standard system components to be installed or running, and no coordination between different applications.

2023-06-05 08:17 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @JordiSubira, @marcfrei, and @oncilla)

___
*[`doc/dev/design/router-port-dispatch.rst` line 227 at r8](https://reviewable.io/reviews/scionproto/scion/4280#-NX9bZ5zDWhB55kH40VJ:-NX9bZ5zDWhB55kH40VK:bs7neqv) ([raw file](https://github.com/scionproto/scion/blob/1df97866af9b591d4c35c0ab49069416277742c3/doc/dev/design/router-port-dispatch.rst#L227)):*
> ```reStructuredText
>   packet forwarder. This forwarder listens on UDP port 30041. It inspects the L4 header and forwards
>   all SCION packets to corresponding underlay port on the local host, following the processing
>   rules for the router outlined above.
> ```

As mentioned in https://github.com/scionproto/scion/pull/4344#pullrequestreview-1443688080 and discussed in the [TC Implementation meeting on 1st June](https://github.com/scionproto/scion/issues/4327#issuecomment-1573359749), this design document was missing a compatibility mechanism to ensure that applications/services can function even if the port-dispatching feature is only partially available in the routers of the AS.


<!-- Sent from Reviewable.io -->

2023-10-23 13:19 UTC, JordiSubira commented
While I was implementing this, one question strikes me as a relevant one. Perhaps, you have already discussed this on some TC meeting or elsewhere, however I don't remember discussing it with anyone.

As it is implemented right now in #4344 , the shim has become a UDP datagram forwarder.  In practice, we are not simulating the SCION underlay on the endhost stack as before. Previously, if one application doesn't register explicitly for SCION/UDP address,the dispatcher wouldn't send packets to this (IP:port). In contrast, right now, the shim would send packets to this IP:Port. Perhaps, explicitly documenting this, for helping operator on setting mechanism as network namespaces (or similar) is desirable.

On top of that, if the shim listens on address any, the shim MAY send packets intended to "internal" services. Of course, this will be subject on the NW traffic rules, whether they allow the BR to send packets to this "internal" address and whether by configuration the operator configures the shim with the ANY address.

Finally, I think it's weird having legitimate use case, in which the IP address for UDP/IP is different from the IP for SCION/UDP at the endhost. For this, we can add a check ( as suggested here https://github.com/scionproto/scion/pull/4344#pullrequestreview-1692508277).

2023-10-24 08:37 UTC, matzf commented
Ah, good points, Jordi.

So the "shim" unintentionally allows bypassing the firewalls. That's certainly a concern. As we forward the packet to the address listed in the SCION address header, there is also the risk that the shim is abused as a reflector to forward packets to different hosts.
I think the suggested additional check to validate that the underlay destination IP corresponds to the SCION destination address would be a good mitigation. It ensures that we only send packets to addresses on this host and also that at least the IP destination is routable from the sender (some strange routing rules could still invalidate this, but still...). 
The only thing that we'd then allow to bypass is filtering of specific UDP ports based on the source address. If we make this clear in the documentation, it should be relatively straight forward to extend the rules to also block packets from the shim.

To implement this check, we'll need to obtain the underlay destination IP address of the UDP packet. I believe we'll have to use sockopt `IP_PKTINFO`. I don't know in detail how portable this is, but quite certainly we'll have to have some platform specific code for this.

2023-10-30 14:17 UTC, JordiSubira commented
Another point to discuss, which was raised in a discussion started by @marcfrei: How should we handle the server side running with a shim component? Currently the reader uses the udp address of the lastHop to send the reply back (https://github.com/JordiSubira/scion/blob/dispatcher_off/pkg/snet/reader.go#L105C3-L105C34). For traffic going from a legacy BR -> shim dispatcher -> endhost app, the endhost app listening on the UDP/SCION socket will see the shim address as the _lastHop_.

In this discussion 3 alternatives came up, although each one of them with its own pros/cons:
1. The shim adds the udpAddress of the BR in one especial extension before sending the packet to the endhost application. The reader will check whether the incoming packet includes this extension and, if so, it will use the address encoded as the nextHop for sending the reply back. This would add a new extension header (it would feel weird to use H2H or E2E for this) and the packet will grow some extra bytes between the shim and the endhost app. We could also abuse the H2H extension and include there the information.
2. Since the path contains the interface ID (ifID) of the BR, the endhost application (via the library) could poll periodically the Interface information from the Daemon (https://github.com/JordiSubira/scion/blob/dispatcher_off/daemon/internal/servers/grpc.go#L259) and then resolve this interface address for setting the NextHop address in the reply packets. The issue is how often this poll is done. Even though, the topology information is not expected to change often, when it does so and until the next poll, the server will be effectually down. Thus we might want that this poll is in the order of some seconds. 
3. Instead of polling the daemon, the endhost application would consume this information from the topology file. The topology loader allows to reload the information based on signaling and thus could reload the information if this ever changes on the FS. The downside is that we make the end applications having to deal also with the topology file, which doesn't seem convinient at all.
4. Create some subscrption-like RPC on the daemon, i.e., the end application subscribes to it and receives topology changes whenever the daemon is aware of those (if ever). Then it uses the locally stored information to reply back.

Let us know what do you think is the best approach or suggest yours if it's not listed before :)

2023-12-15 10:06 UTC, JordiSubira commented
> > Ah, good points, Jordi.
> > So the "shim" unintentionally allows bypassing the firewalls. That's certainly a concern. As we forward the packet to the address listed in the SCION address header, there is also the risk that the shim is abused as a reflector to forward packets to different hosts. I think the suggested additional check to validate that the underlay destination IP corresponds to the SCION destination address would be a good mitigation. It ensures that we only send packets to addresses on this host and also that at least the IP destination is routable from the sender (some strange routing rules could still invalidate this, but still...). The only thing that we'd then allow to bypass is filtering of specific UDP ports based on the source address. If we make this clear in the documentation, it should be relatively straight forward to extend the rules to also block packets from the shim.
> > To implement this check, we'll need to obtain the underlay destination IP address of the UDP packet. I believe we'll have to use sockopt `IP_PKTINFO`. I don't know in detail how portable this is, but quite certainly we'll have to have some platform specific code for this.
> 
> I took a look at this and I would like to follow the discussion in here. After looking more deeply into this, I reached the conclusion that Windows support in Golang for this is far from being great. There's no proper support for doing this using x/net/ipv[4,6] and this issue [https://github.com/[golang/go/issues/7175](https://github.com/golang/go/issues/7175)] is still open since 2014... so it's a bit unclear. Similarly, there is no support from syscall/windows for auxiliary classes which could help parsing this ancillary information, .e.g., https://pkg.go.dev/syscall#Cmsghdr.
> 
> I think we could get our hands dirty by dealing with lower level code, doing something like this: https://gist.github.com/JordiSubira/775693d03e6fcfe71f9c67779013e136. However, I do not know whether this is a path we want to go through.
> 
> Thus, there are two alternatives (at least):
> 
>     1. Fiddling with `syscall/windows` and low-level code, hoping that we don't mess with anything.
> 
>     2. Changing the approach in Windows (or by extension in all platforms) Hooking the binding to "0.0.0.0"  and binding on all reasonable addresses in parallel in different go routines and do the proper check.
> 
> 
> Please, share your thoughts on that @martenwallewein since you were also playing with this PR your contribution would be useful as well :)

After offline discussion, we finally opted for discontinuing the shim component for windows. Therefore, in network environments with legacy BRs, scion-enabled Windows applications with the new endhost stack (as described in this documentation) will not be able to communicate with those legacy BRs. Take into account, that so far the scion endhost stack (more concretely, the dispatcher) could not be compiled for Windows.

2023-12-15 11:11 UTC, martenwallewein commented
> > Ah, good points, Jordi.
> > So the "shim" unintentionally allows bypassing the firewalls. That's certainly a concern. As we forward the packet to the address listed in the SCION address header, there is also the risk that the shim is abused as a reflector to forward packets to different hosts. I think the suggested additional check to validate that the underlay destination IP corresponds to the SCION destination address would be a good mitigation. It ensures that we only send packets to addresses on this host and also that at least the IP destination is routable from the sender (some strange routing rules could still invalidate this, but still...). The only thing that we'd then allow to bypass is filtering of specific UDP ports based on the source address. If we make this clear in the documentation, it should be relatively straight forward to extend the rules to also block packets from the shim.
> > To implement this check, we'll need to obtain the underlay destination IP address of the UDP packet. I believe we'll have to use sockopt `IP_PKTINFO`. I don't know in detail how portable this is, but quite certainly we'll have to have some platform specific code for this.
> 
> I took a look at this and I would like to follow the discussion in here. After looking more deeply into this, I reached the conclusion that Windows support in Golang for this is far from being great. There's no proper support for doing this using x/net/ipv[4,6] and this issue [https://github.com/[golang/go/issues/7175](https://github.com/golang/go/issues/7175)] is still open since 2014... so it's a bit unclear. Similarly, there is no support from syscall/windows for auxiliary classes which could help parsing this ancillary information, .e.g., https://pkg.go.dev/syscall#Cmsghdr.
> 
> I think we could get our hands dirty by dealing with lower level code, doing something like this: https://gist.github.com/JordiSubira/775693d03e6fcfe71f9c67779013e136. However, I do not know whether this is a path we want to go through.
> 
> Thus, there are two alternatives (at least):
> 
> 1. Fiddling with `syscall/windows` and low-level code, hoping that we don't mess with anything.
> 2. Changing the approach in Windows (or by extension in all platforms) Hooking the binding to "0.0.0.0"  and binding on all reasonable addresses in parallel in different go routines and do the proper check.
> 
> Please, share your thoughts on that @martenwallewein since you were also playing with this PR your contribution would be useful as well :)

Hey @JordiSubira thanks for summarizing this. I've thought some time about this and here is my conclusion:

For me it feels like the windows low-level code is more a shot in our own knee, that is probably resulting in some effort to maintain this and to keep it up-to-date with other features.

The approach of binding to each reasonable interface manually with an own go routine is o.k. for me (I mean if I remember correctly it was my idea). If the core processing routine is the same for all interfaces which just checks different addresses then I think the overhead of a bit of concurrency is fine.

What's the state of the idea of dropping shim support for windows? I mean we still have the firewall issue, and running the newest routers seems like a good idea anyway. Hope this helps, thanks all for your work on this!

2023-12-15 11:47 UTC, JordiSubira commented
Hello @martenwallewein, thank you for jumping in. Of course, this is a possibility, having different code for each platform. However, we should either specify somewhere that in windows the user of the library shouldn't bind to 0.0.0.0 or do it under their own risk of bypassing firewall rules, as you said. Or we limit it futher with more platform specific condition, in which we don't allow to bind to 0.0.0.0 in Windows. If we agree on that, I can try to have this for future iterations.

2024-03-26 09:05 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @JordiSubira, @marcfrei, and @oncilla)

___
*[`doc/design/router-port-dispatch.rst` line 168 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGRYQhJCbZjAdgagtCm:-Nttr5YH3XkrfCy-WAO5:bklw6hl) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L168)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

> My guess as to why we don't have IP underlay directly (yet) is that it's just much more practical to use UDP compared to defining a new protocol number which would certainly be dropped by all kinds of middleboxes. So, the UDP underlay is just a pragmatic, convenient choice to aid deployability.

Yes, this is exactly the reason. This is also why QUIC builds on top of UDP/IP. Protocol numbers unfortunately have ossified, and are hard to introduce.

> So, the UDP underlay is already "wrong", so milking this UDP underlay a bit more to aid deployability _more_ seems fair game.  

I don't agree with this. The closer you keep everything to the target state, the less do you back yourself in the corner.
IMO, every layer violation counts, because every layer violation gets you further away from the target. Just because we have one violation, doesn't mean we should introduce another one. This is a slippery slope, and we should try our best not to slip.

> I admit this is a bit of a foot-in-the-door argument.

good :)

> What we ideally want to achieve is to make it possible to deploy multiple SCION-native applications independently and fully self-contained. There should be no requirement for any non-standard system components to be installed or running, and no coordination between different applications.  
The ebpf-dispatcher approach does not achieve this (generally, not only on mobile platforms); something will need to install this ebpf program (and even needs special privileges for this).  
Requiring an SCMP daemon fails this ideal goal in the same way (needs to be installed and started _somehow_).

I think we all agree that having kernel support would be beautiful.

(quoting @marcfrei response from above)

> I don't know whether and how this could work on Android but at least on iOS/iPadOS there is as far as I can see simply no concept of a user-installable background daemon. There is however the possibility to install and enable a separate app that provides a so-called Network Extension ([https://developer.apple.com/documentation/networkextension](https://developer.apple.com/documentation/networkextension)) which could come close to what is needed here.
>
> We would need to investigate whether it is feasible in principle to implement SCMP daemon functionality based on what the network extension model allows. In addition, there's then also the question how such a network extension would work together with other network extensions. VPN apps (like, e.g. Tailscale) have to be implemented as network extensions and at least VPN extensions are mutually exclusive among each other. Independent of the technical feasibility it also seems to me that such a solution would be rather finicky to manage for typical end-users. Installing a network extension requires entry of the device passcode which already feels a little scary to begin with. It's then very easy to imagine support situations where a SCION-based application doesn't work as expected. The provider of such an app would need to ask the user to check whether the separate SCION SCMP daemon app that provides the network extension is already installed and enabled correctly. The approach thus wouldn't really satisfy Matthias's requirement:
>
> What we ideally want to achieve is to make it possible to deploy multiple SCION-native applications independently and fully self-contained. There should be no requirement for any non-standard system components to be installed or running, and no coordination between different applications.

Okay, that sounds painful. I think quote parsing and an assigned range is probably the most feasible path that does not back us into a corner.
Putting information in the flow ID or reserved bits of the header might work right now, but transitioning away from these hacks will be nasty IMO, and we should try to avoid them.






</blockquote></details>

I realized that we never concluded this discussion. From your last statement, @oncilla, I understand that you agree with moving ahead with the approach outlined in the design document (which is the variant "UDP/SCION Port == Underlay Port && SCMP Quote parsing").
This is what @JordiSubira has implemented in his epic #4344. There, the SCMP Quote parsing exists in two places, in the router and in the "shim" dispatcher which incidentally makes it quite easy to experiment with the different approaches.

If you agree, I'd like to conclude this discussion for now and merge this design document, so Jordi has something more solid to refer to.

Small detail changed based on your first comment: updated the proposed port range in the document so there is no intersection with the range that the dispatcher currently uses. "Legacy" end hosts should thus be mostly unaffected by the port dispatching in the router.


<!-- Sent from Reviewable.io -->

2024-03-27 13:35 UTC, lukedirtwalker requested changes
> Reviewed 1 of 3 files at r6, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`doc/dev/design/router-port-dispatch.rst` line 225 at r9](https://reviewable.io/reviews/scionproto/scion/4280#-Nu-6js53f-6QgNwitMF:-Nu-6js53f-6QgNwitMG:undefined) ([raw file](https://github.com/scionproto/scion/blob/6e52ec1f91712bff2b19e8a3bf7f3bdebc354d06/doc/dev/design/router-port-dispatch.rst#L225)):*
> ```reStructuredText
> - Add support for dispatched/forwarded port ranges to the topology.json configuration.
> 
>   As the topology.json parsing is lenient about unkown keys by default, tue updated topology.json file can still be consumed by "legacy" applications.
> ```





_Suggestion:_
```reStructuredText
the
```


<!-- Sent from Reviewable.io -->

2024-03-29 10:55 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`doc/dev/design/router-port-dispatch.rst` line 227 at r8](https://reviewable.io/reviews/scionproto/scion/4280#-NX9bZ5zDWhB55kH40VJ:-NhRSCse4gI8qBjyqpsZ:bz1pz23) ([raw file](https://github.com/scionproto/scion/blob/1df97866af9b591d4c35c0ab49069416277742c3/doc/dev/design/router-port-dispatch.rst#L227)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

As mentioned in https://github.com/scionproto/scion/pull/4344#pullrequestreview-1443688080 and discussed in the [TC Implementation meeting on 1st June](https://github.com/scionproto/scion/issues/4327#issuecomment-1573359749), this design document was missing a compatibility mechanism to ensure that applications/services can function even if the port-dispatching feature is only partially available in the routers of the AS.
</blockquote></details>

While I was implementing this. In fact, I already did it, I realized that this shim has to be used "carefully". Since, essentially, it has become a stateless UDP datagram forwarder, no registration from the application is expected to happen. In certain scenarios, one attacker could send packets which reach services that were not intended to be accessible from"remote. Let's say host X with  address X.X.X.X, has two services: SCION service listening on port S and non-scion service listening on port Y. Assuming, network rules allow traffic to X.X.X.X 
___
*[`doc/dev/design/router-port-dispatch.rst` line 166 at r10](https://reviewable.io/reviews/scionproto/scion/4280#-Nu8nKGWAJoDgFJ-Gjfv:-Nu8nKGWAJoDgFJ-Gjfw:b-ps3rg8) ([raw file](https://github.com/scionproto/scion/blob/ac167a959d0cae0cb70fd5819ca1ed6c582e9e14/doc/dev/design/router-port-dispatch.rst#L166)):*
> ```reStructuredText
>             "max": <port>
>          },
>          "<ip-subnet>": { # any number of subnet-specific port-range configurations (in CIDR-notation)
> ```

@lukedirtwalker brought this up in the implementation PR and I realized I never stated my doubts about this idea. Is it really worth it to allow different port ranges per prefix? It is clear that it brings flexibility for the AS to have a clear segmentation between deployments, i.e., you put different deployments in different subnets. However, this brings complexity. I guess what concerns me the most is complexity on the BR. I know this only affects to the last-mile BR, but now the BR also has to do longest matching prefix. Besides, from the point of view of the application, it is more counterintuitive binding to 0.0.0.0:port (it is true now we don't even allow this due to finding out the address of the next hop BR, but we could). This would force us to have some wrapper implementation under the hood that decides on potentially different ports depending on the address of the interfaces if the belong to different subnets.

Note: at the moment the current implementation PR only implements the common port range. I can adapt it if this is the right way to go.


<!-- Sent from Reviewable.io -->

2024-04-02 05:49 UTC, lukedirtwalker requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira and @oncilla)

___
*[`doc/dev/design/router-port-dispatch.rst` line 166 at r10](https://reviewable.io/reviews/scionproto/scion/4280#-Nu8nKGWAJoDgFJ-Gjfv:-NuSLXhY2ssMPqR5SX4-:b-ctyubi) ([raw file](https://github.com/scionproto/scion/blob/ac167a959d0cae0cb70fd5819ca1ed6c582e9e14/doc/dev/design/router-port-dispatch.rst#L166)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

@lukedirtwalker brought this up in the implementation PR and I realized I never stated my doubts about this idea. Is it really worth it to allow different port ranges per prefix? It is clear that it brings flexibility for the AS to have a clear segmentation between deployments, i.e., you put different deployments in different subnets. However, this brings complexity. I guess what concerns me the most is complexity on the BR. I know this only affects to the last-mile BR, but now the BR also has to do longest matching prefix. Besides, from the point of view of the application, it is more counterintuitive binding to 0.0.0.0:port (it is true now we don't even allow this due to finding out the address of the next hop BR, but we could). This would force us to have some wrapper implementation under the hood that decides on potentially different ports depending on the address of the interfaces if the belong to different subnets.

Note: at the moment the current implementation PR only implements the common port range. I can adapt it if this is the right way to go.
</blockquote></details>

Do we remember why we brought this up initially? IMO we don't necessarily need it. But I would like to know the reasoning behind why it was brought up.


<!-- Sent from Reviewable.io -->

2024-04-02 07:30 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, and @oncilla)

___
*[`doc/dev/design/router-port-dispatch.rst` line 166 at r10](https://reviewable.io/reviews/scionproto/scion/4280#-Nu8nKGWAJoDgFJ-Gjfv:-NuScTDvEg5LEK_n0g2h:b-l1aq13) ([raw file](https://github.com/scionproto/scion/blob/ac167a959d0cae0cb70fd5819ca1ed6c582e9e14/doc/dev/design/router-port-dispatch.rst#L166)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Do we remember why we brought this up initially? IMO we don't necessarily need it. But I would like to know the reasoning behind why it was brought up.
</blockquote></details>

This was my suggestion. The idea was mostly to demonstrate that this approach can be tuned flexibly by the AS operator, and that per-host or per-subnet overrides could be applied if port ranges clash or if other issues occur e.g. with future modifications to the end host stack.

Just to clarify regarding applications binding on 0.0.0.0: the subnets-overrides would (only) be configuration for the router; the thought was that end hosts would get "tailored" topology files with only port range relevant to them, so they don't need to explicitly manage this.

I agree that this feature is not immediately useful. We have port ranges that don't overlap with the legacy-dispatcher's ports, which should make this per-host/per-subnet override mostly unnecessary for now. Also, this can still be added in a router implementation later on, so we don't block anything by omitting this in a first pass.
I'll revise the document to remove it.


<!-- Sent from Reviewable.io -->

2024-04-02 08:30 UTC, lukedirtwalker approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira and @oncilla)



<!-- Sent from Reviewable.io -->

2024-04-02 11:11 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira and @oncilla)

___
*[`doc/dev/design/router-port-dispatch.rst` line 166 at r10](https://reviewable.io/reviews/scionproto/scion/4280#-Nu8nKGWAJoDgFJ-Gjfv:-NuSt5DN-QKB-aqlp9AO:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ac167a959d0cae0cb70fd5819ca1ed6c582e9e14/doc/dev/design/router-port-dispatch.rst#L166)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This was my suggestion. The idea was mostly to demonstrate that this approach can be tuned flexibly by the AS operator, and that per-host or per-subnet overrides could be applied if port ranges clash or if other issues occur e.g. with future modifications to the end host stack.

Just to clarify regarding applications binding on 0.0.0.0: the subnets-overrides would (only) be configuration for the router; the thought was that end hosts would get "tailored" topology files with only port range relevant to them, so they don't need to explicitly manage this.

I agree that this feature is not immediately useful. We have port ranges that don't overlap with the legacy-dispatcher's ports, which should make this per-host/per-subnet override mostly unnecessary for now. Also, this can still be added in a router implementation later on, so we don't block anything by omitting this in a first pass.
I'll revise the document to remove it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-02 12:08 UTC, oncilla reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 1 unresolved discussion (waiting on @JordiSubira)

___
*[`doc/design/router-port-dispatch.rst` line 168 at r3](https://reviewable.io/reviews/scionproto/scion/4280#-NGRYQhJCbZjAdgagtCm:-NuThKLo69Gu94lKUSYq:b-alch2x) ([raw file](https://github.com/scionproto/scion/blob/d0277dce4ba4d58041b46030c871a19a6aa8cdd3/doc/design/router-port-dispatch.rst#L168)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I realized that we never concluded this discussion. From your last statement, @oncilla, I understand that you agree with moving ahead with the approach outlined in the design document (which is the variant "UDP/SCION Port == Underlay Port && SCMP Quote parsing").
This is what @JordiSubira has implemented in his epic #4344. There, the SCMP Quote parsing exists in two places, in the router and in the "shim" dispatcher which incidentally makes it quite easy to experiment with the different approaches.

If you agree, I'd like to conclude this discussion for now and merge this design document, so Jordi has something more solid to refer to.

Small detail changed based on your first comment: updated the proposed port range in the document so there is no intersection with the range that the dispatcher currently uses. "Legacy" end hosts should thus be mostly unaffected by the port dispatching in the router.
</blockquote></details>

ack. Resolved from my side.


<!-- Sent from Reviewable.io -->

2024-04-09 12:06 UTC, marcfrei commented
*[`doc/dev/design/router-port-dispatch.rst` line 172 at r11](https://reviewable.io/reviews/scionproto/scion/4280#-NuYnxUa-xi3GC-T72BQ:-Nv1jaus017nFeIjCNT5:bz4tfzy) ([raw file](https://github.com/scionproto/scion/blob/5eeee19007b260c0f2479dbdc17c31824529e0b2/doc/dev/design/router-port-dispatch.rst#L172)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

For well known listener ports this seems sufficient, but I worry a bit about the number of available ephemeral client ports. In one project, we discussed sending out UDP requests to ca. 2k - 10k servers in parallel. With this default allocation of ports, we would need to introduce a somewhat complicated sharing scheme for source ports (net.UDPConns), right?
</blockquote></details>

Resolved in an offline discussion: the port range is intended to get removed or made wider again after an AS is updated completely.


<!-- Sent from Reviewable.io -->

2024-04-09 12:21 UTC, lukedirtwalker approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira and @matzf)



<!-- Sent from Reviewable.io -->

2024-04-10 10:52 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf)

___
*[`doc/dev/design/router-port-dispatch.rst` line 164 at r11](https://reviewable.io/reviews/scionproto/scion/4280#-Nv6bV7D56FVqKe5T7h8:-Nv6bV7D56FVqKe5T7h9:ba231pr) ([raw file](https://github.com/scionproto/scion/blob/5eeee19007b260c0f2479dbdc17c31824529e0b2/doc/dev/design/router-port-dispatch.rst#L164)):*
> ```reStructuredText
>          "min": <port>,
>          "max": <port>
>        }
> ```

Right now I am using the following format based on a Marc's suggestion on the implementation PR (https://reviewable.io/reviews/scionproto/scion/4344#-NqRlyUyA8rSxIAJFYWy):
```
"endhost_port_range": "1024-65535",
```
It also allows the syntax "" and "-" to indicate an empty port range. Where should we change it?



_Code quote:_
```reStructuredText
       "dispatched_ports": {
         "min": <port>,
         "max": <port>
       }
```


<!-- Sent from Reviewable.io -->

2024-04-11 14:03 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, and @marcfrei)

___
*[`doc/dev/design/router-port-dispatch.rst` line 164 at r11](https://reviewable.io/reviews/scionproto/scion/4280#-Nv6bV7D56FVqKe5T7h8:-NvCRDlZ8jEEdwEKyEcS:b-9wl963) ([raw file](https://github.com/scionproto/scion/blob/5eeee19007b260c0f2479dbdc17c31824529e0b2/doc/dev/design/router-port-dispatch.rst#L164)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Right now I am using the following format based on a Marc's suggestion on the implementation PR (https://reviewable.io/reviews/scionproto/scion/4344#-NqRlyUyA8rSxIAJFYWy):
```
"endhost_port_range": "1024-65535",
```
It also allows the syntax "" and "-" to indicate an empty port range. Where should we change it?
</blockquote></details>

Done, i've changed it here. I've also added an `"all"` value that is a shorthand for `1-65535`. When documenting the intended procedure for the update, I realized that this will be the value used for most of the time once the update is complete, so it makes sense to have a short value.
___
*[`doc/dev/design/router-port-dispatch.rst` line 172 at r11](https://reviewable.io/reviews/scionproto/scion/4280#-NuYnxUa-xi3GC-T72BQ:-NvCRl80-w_Z25dIfHwU:b-epyxgd) ([raw file](https://github.com/scionproto/scion/blob/5eeee19007b260c0f2479dbdc17c31824529e0b2/doc/dev/design/router-port-dispatch.rst#L172)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Resolved in an offline discussion: the port range is intended to get removed or made wider again after an AS is updated completely.
</blockquote></details>

I've added more details on the compatibility mechanisms and the intended update procedure now, as discussed in the chat and in tuesday's call.
The significance of this port range has been somewhat reduced since the first version of this document (which had not yet included the "shim dispatcher"). Now it is really only the range of (mostly ephemeral) ports that can be used by "new" devices/applications without the shim dispatcher, during the transition phase before the update of the AS is complete. I hope this is clearer now  -- admittedly, it had not been entirely clear to me before thinking it through again to write it down.


<!-- Sent from Reviewable.io -->

2024-04-11 14:05 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, and @marcfrei)

___
*[`doc/dev/design/router-port-dispatch.rst` line 215 at r11](https://reviewable.io/reviews/scionproto/scion/4280#-NuZ0nVuDwyxvzOPC0kD:-NvCTM5Q8l428EIIuo0z:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5eeee19007b260c0f2479dbdc17c31824529e0b2/doc/dev/design/router-port-dispatch.rst#L215)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

unknown
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-11 14:36 UTC, lukedirtwalker approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 3 unresolved discussions (waiting on @JordiSubira and @matzf)

___
*[`doc/dev/design/router-port-dispatch.rst` line 208 at r13](https://reviewable.io/reviews/scionproto/scion/4280#-NvC_KMd5VC51OXSz0i4:-NvC_YTd6JFAZSwxlULu:b-7ilvfz) ([raw file](https://github.com/scionproto/scion/blob/75c395bf76471f7d8511096c1f356bf28a2f177d/doc/dev/design/router-port-dispatch.rst#L208)):*
> ```reStructuredText
> 
> Conversely, if our long term vision materializes and we'd have SCION support directly built-in to the operating system's network stack, then this workaround becomes obsolete.
> In an optimistic scenario, where there are millions of end hosts running SCION-enabled applications, we can not expect that all devices and applications will updated to the same level of SCION support within a useful time frame.
> ```

typo:


<!-- Sent from Reviewable.io -->

2024-05-06 18:18 UTC, marcfrei approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280#-:-NxE7Ce77Vmzyy_jgEdX:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @JordiSubira and @matzf)

___
*[`doc/dev/design/router-port-dispatch.rst` line 153 at r13](https://reviewable.io/reviews/scionproto/scion/4280#-NxDVvTiDc7g9wg7E8z7:-NxDVvTjCoYEmI5rFVei:b-vfefa1) ([raw file](https://github.com/scionproto/scion/blob/75c395bf76471f7d8511096c1f356bf28a2f177d/doc/dev/design/router-port-dispatch.rst#L153)):*
> ```reStructuredText
>   The processing rule above is extended:
> 
>   2. If the underlay UDP/IP destination port determined above is within the port range specified in the topology configuration,
> ```

above, i.e. in processing rule 1,



_Code quote:_
```reStructuredText
above
```
___
*[`doc/dev/design/router-port-dispatch.rst` line 202 at r13](https://reviewable.io/reviews/scionproto/scion/4280#-NxDc33_931smKvLINV0:-NxDc33_931smKvLINV1:b-x62ska) ([raw file](https://github.com/scionproto/scion/blob/75c395bf76471f7d8511096c1f356bf28a2f177d/doc/dev/design/router-port-dispatch.rst#L202)):*
> ```reStructuredText
>    new applications/devices without the shim dispatcher, they can pick the empty range in step 1.,
>    and state 3. is skipped.
> ```

Should we add an additional note that explicitly explains how the transition works for server applications listening on well-known ports? I guess they wouldn't start listening in the dispatched_ports range but just use the shim dispatcher until dispatched_ports gets extended to also cover the well known ports?
___
*[`doc/dev/design/router-port-dispatch.rst` line 216 at r13](https://reviewable.io/reviews/scionproto/scion/4280#-NxDfsfc6iMiDt3Wq7l8:-NxDfsfc6iMiDt3Wq7l9:btpy57d) ([raw file](https://github.com/scionproto/scion/blob/75c395bf76471f7d8511096c1f356bf28a2f177d/doc/dev/design/router-port-dispatch.rst#L216)):*
> ```reStructuredText
> 
> - enable shim dispatcher for services outside of intended ``dispatched_port`` range
> - shrink ``dispatched_ports`` range and configure this on routers and hosts
> ```

When can this step safely be initiated, i.e., when do we know that all hosts in a given AS have enabled the shim dispatchers again?
___
*[`doc/dev/design/router-port-dispatch.rst` line 279 at r13](https://reviewable.io/reviews/scionproto/scion/4280#-NxE6M454idEu658j26F:-NxE6M46BmMfO5beFkAE:b-l0tgoz) ([raw file](https://github.com/scionproto/scion/blob/75c395bf76471f7d8511096c1f356bf28a2f177d/doc/dev/design/router-port-dispatch.rst#L279)):*
> ```reStructuredText
>      Remove the packet dispatching/forwarding functionality from "dispatcher".
>      Only SCMP echo responder remains in dispatcher. Rename to "SCMP Daemon" (scmpd).
>    - set suitable default for port range in ``dispatched_ports`` topology configuration
> ```

configuration.



_Code quote:_
```reStructuredText
configuration
```


<!-- Sent from Reviewable.io -->

2024-05-21 09:58 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, and @marcfrei)

___
*[`doc/dev/design/router-port-dispatch.rst` line 202 at r13](https://reviewable.io/reviews/scionproto/scion/4280#-NxDc33_931smKvLINV0:-NyP_VRg3YC3EUyNzYav:b-fznogt) ([raw file](https://github.com/scionproto/scion/blob/75c395bf76471f7d8511096c1f356bf28a2f177d/doc/dev/design/router-port-dispatch.rst#L202)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Should we add an additional note that explicitly explains how the transition works for server applications listening on well-known ports? I guess they wouldn't start listening in the dispatched_ports range but just use the shim dispatcher until dispatched_ports gets extended to also cover the well known ports?
</blockquote></details>

Good idea, done.
___
*[`doc/dev/design/router-port-dispatch.rst` line 216 at r13](https://reviewable.io/reviews/scionproto/scion/4280#-NxDfsfc6iMiDt3Wq7l8:-Ny4mlbQ18C5dYG214YW:b-e5w7mo) ([raw file](https://github.com/scionproto/scion/blob/75c395bf76471f7d8511096c1f356bf28a2f177d/doc/dev/design/router-port-dispatch.rst#L216)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

When can this step safely be initiated, i.e., when do we know that all hosts in a given AS have enabled the shim dispatchers again?
</blockquote></details>

Good question, I don't have a good answer. I've added a note to point out this flaw.


<!-- Sent from Reviewable.io -->

2024-05-21 12:19 UTC, marcfrei approved these changes
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2024-05-23 08:49 UTC, matzf reviewed
> Dismissed @JordiSubira from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4280)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2024-05-23 08:51 UTC, merged