Issue/2653
scionproto/scion pull request #4287
Opened 2022-10-27 11:35 UTC by bunert

2022-10-28 08:34 UTC, matzf requested changes
What do we gain by supporting yaml output explicitly here? The existing json output can be consumed by a yaml parser either way. 

:100: for adding machine readable output to ping/traceroute though.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287#-:-NFSgiX04wtRZ-3hHTVf:b-ofyg2d)* status: 0 of 11 files reviewed, 8 unresolved discussions (waiting on @bunert)

___
*[`pkg/snet/path/path.go` line 44 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFST7y1ECcw2zq6SQJx:-NFST7y1ECcw2zq6SQJy:b-gj3rdg) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/pkg/snet/path/path.go#L44)):*
> ```Go
> 	Interface int    `json:"interface" yaml:"interface"`
> 	IA        string `json:"isd_as" yaml:"isd_as"`
> }
> ```

Why not just use `snet.PathInterface`?
___
*[`scion/cmd/scion/ping.go` line 281 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSauHqDNMX5Q6hyRgh:-NFSauHqDNMX5Q6hyRgi:b-p7t0gt) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/cmd/scion/ping.go#L281)):*
> ```Go
> 				},
> 			})
> 			pktLoss := pingSummary(stats, remote, time.Since(start), cmdout)
> ```

It would be great if this could additionally print `min/avg/max/mdev` round trip time both in "human" and machine readable output formats. The "human" format should match the format of IP `ping`.
Create the Statistics struct with calculated loss and RTT values first and adapt the pingSummary function to print the values from this struct.
___
*[`scion/ping/ping.go` line 88 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSeiGZ-pMQkdsNxY1c:-NFSeiGZ-pMQkdsNxY1d:b-xjlw4t) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/ping/ping.go#L88)):*
> ```Go
> }
> 
> type Result struct {
> ```

These new types really seem to be specific to the update handler used in the `cmd` package. Move all of these new types to `scion/cmd/scion/ping.go`.
___
*[`scion/ping/ping.go` line 110 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSUlkw9rrqESz4QR_E:-NFSUlkw9rrqESz4QR_F:b-duk556) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/ping/ping.go#L110)):*
> ```Go
> 	// Hex-string representing the paths fingerprint.
> 	Fingerprint string     `json:"fingerprint" yaml:"fingerprint"`
> 	Hops        []path.Hop `json:"hops" yaml:"hops"`
> ```

Here and for all the tools (in particular also for showpaths); it would be useful to print a "sequence" representation of the path which can be  to select the path with the `--sequence` flag in a next tool invocation. For example, this could look like `"sequence": "1-ff00:0:133#5 1-ff00:0:120#2,1 1-ff00:0:110#3"`.
This could either be in addition or as replacement of the `hops` array -- even if a consumer wants to process the individual hops in some form, parsing the full sequence representation is quite straight forward.
___
*[`scion/ping/ping.go` line 119 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSYsw32UdrcLYK-kEc:-NFSYsw32UdrcLYK-kEd:b-6mo1d4) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/ping/ping.go#L119)):*
> ```Go
> 
> 	// The internal UDP/IP underlay address of the SCION router that forwards traffic for this path.
> 	NextHop string `json:"next_hop" yaml:"next_hop"`
> ```

I'd not show the metadata fields (MTU, Latency, Expiry) here. That's what we have showpaths for, or not?
___
*[`scion/ping/ping.go` line 124 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSfZDj8TuPR-k7HeaU:-NFSfZDj8TuPR-k7HeaV:b-hl3e0p) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/ping/ping.go#L124)):*
> ```Go
> // PingRun defines model for PingRun.
> type PingUpdate struct {
> 	RoundTripTime string `json:"round_trip_time" yaml:"round_trip_time"`
> ```

Perhaps it would be more useful to represent durations as numbers, e.g. duration in millisecond as floats. Processing durations with different units is not super easy.
___
*[`scion/ping/ping.go` line 134 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSZ1Lk6yHIhY4sbhtG:-NFSZ1Lk6yHIhY4sbhtH:bk81g16) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/ping/ping.go#L134)):*
> ```Go
> 	// Source host address
> 	SourceHost string `json:"source_host" yaml:"source_host"`
> 	SourceIA   string `json:"source_isd_as" yaml:"source_isd_as"`
> ```

Combine these two fields into a source address in the `<ISD>-<AS>,<Host>` form?
___
*[`scion/ping/ping.go` line 137 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFShopfA3wDLI6LY5To:-NFShopfA3wDLI6LY5Tp:bvjw622) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/ping/ping.go#L137)):*
> ```Go
> 
> 	// Status describing the outcome of a ping response.
> 	State string `json:"state" yaml:"state"`
> ```

Use `State` type and add a `String` method to it.


<!-- Sent from Reviewable.io -->

2022-10-28 16:24 UTC, oncilla requested changes
The additional effort to encode it in yaml is trivial.

I think the benefit of an additional format outweighs this additional effort.

> Reviewed 3 of 11 files at r1, 4 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287#-:-NFU1qpPEyAeYmGAUMV6:b-u1pq7n)* status: 7 of 14 files reviewed, 22 unresolved discussions (waiting on @bunert and @matzf)

___
*[`pkg/snet/path.go` line 73 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFU2uXFCX-1FzgKUtkV:-NFU2uXG1xW3lLTuYaLk:b-urdyme) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/pkg/snet/path.go#L73)):*
> ```Go
> type PathInterface struct {
> 	// ID is the ID of the interface.
> 	ID common.IFIDType `json:"interface" yaml:"interface"`
> ```

Data representation is not a concern of this library package.
I don't think we should extend this specific type with encoding tags.
___
*[`pkg/snet/path/epic.go` line 50 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFU37Mb5Dbxu2KWHm1D:-NFU37Mb5Dbxu2KWHm1E:b-7obamp) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/pkg/snet/path/epic.go#L50)):*
> ```Go
> }
> 
> func CloneEICDataplanePath(p *EPIC) *EPIC {
> ```

Make this a method on the pointer receiver of EPIC.

But I'm questioning now whether this is even a valid thing to do.
The cloned path should not be used to create actual dataplane packets.

Maybe we could have a private field `cloned` and return an error in `SetPath` if the path is cloned.

@matzf thoughts?
___
*[`pkg/snet/path/epic.go` line 51 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFU3wbl43aGiCZCi686:-NFU3wbl43aGiCZCi687:b-jtyvt8) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/pkg/snet/path/epic.go#L51)):*
> ```Go
> 
> func CloneEICDataplanePath(p *EPIC) *EPIC {
> 	res := &EPIC{}
> ```

If we were to keep this, I would write it like so:



_Suggestion:_
```Go
	return &EPIC{
	  AuthPHVF: append(p.AuthPHVF[:0:0], p.AuthPHVF...)
	  AuthLHVF: append(p.AuthLHVF [:0:0], p.AuthLHVF...)
	  SCION: append(p.SCION[:0:0], p.SCION...)
	  counter: counter 
	}
```
___
*[`private/path/pathpol/sequence.go` line 299 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFUJAyl78fvbe92YQr8:-NFUJAyl78fvbe92YQr9:bcrhk5) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/private/path/pathpol/sequence.go#L299)):*
> ```Go
> 
> // GetSequence constructs the sequence string from snet path
> // example format: "1-ff00:0:133#0 1-ff00:0:120#2,1 0 0 1-ff00:0:110#0"
> ```

The sequence that is being built is always fully qualified.
Thus the example should not have any wild cards.

Also, let's use a "code block" for the example:
https://tip.golang.org/doc/comment



_Code quote:_
```Go
// example format: "1-ff00:0:133#0 1-ff00:0:120#2,1 0 0 1-ff00:0:110#0"
```
___
*[`scion/cmd/scion/ping.go` line 67 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFUJwrhB7-ZIrMtMxxO:-NFUJwrhB7-ZIrMtMxxP:undefined) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/scion/cmd/scion/ping.go#L67)):*
> ```Go
> 	// describes the latency between interface i and i+1.
> 	Latency []time.Duration `json:"latency,omitempty" yaml:"latency,omitempty"`
> 	LocalIp net.IP          `json:"local_ip,omitempty" yaml:"local_ip,omitempty"`
> ```





_Suggestion:_
```Go
LocalIP
```
___
*[`scion/cmd/scion/ping.go` line 71 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFUJzzUBh3t8NB-zxRw:-NFUJzzUBh3t8NB-zxRx:undefined) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/scion/cmd/scion/ping.go#L71)):*
> ```Go
> 	// The maximum transmission unit in bytes for SCION packets. This represents the protocol data
> 	// unit (PDU) of the SCION layer on this path.
> 	Mtu int `json:"mtu" yaml:"mtu"`
> ```





_Suggestion:_
```Go
MTU
```
___
*[`scion/cmd/scion/ping.go` line 139 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFUKQaj3GMi0WkS1e0W:-NFUKQaj3GMi0WkS1e0X:b-ne2w65) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/scion/cmd/scion/ping.go#L139)):*
> ```Go
> 			}
> 			defer closer()
> 			var cmdout io.Writer
> ```

I would abstract this a step further.

```go
printf := func(fmt string, ctx ...interface{}) {}
if flags.format == human {
  printf := func(fmt string, ctx ...interface{}) {
    fmt.Fprintf(cmd.OutOrStdout(), fmt, ctx...)
  }
}
```

Furthermore, this code appears in all commands.
Let's extract this into a helper.



_Code quote:_
```Go
			var cmdout io.Writer
			switch flags.format {
			case "human":
				cmdout = os.Stdout
			case "json", "yaml":
				cmdout = io.Discard
			default:
				return serrors.New("format not supported", "format", flags.format)
			}
```
___
*[`scion/cmd/scion/ping.go` line 431 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFULH1-BVI2Mqj-B4Wo:-NFULH1-BVI2Mqj-B4Wp:b-crvqjb) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/scion/cmd/scion/ping.go#L431)):*
> ```Go
> }
> 
> // JSON writes the ping result as a json object to the writer.
> ```

I think these two methods do not really add value.
Just call the encoders directly and drop the methods here.
___
*[`scion/cmd/scion/showpaths.go` line 86 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFULaBoC01LoS3o3XU4:-NFULaBoC01LoS3o3XU5:b-bx4fjw) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/scion/cmd/scion/showpaths.go#L86)):*
> ```Go
> 			}
> 			defer closer()
> 			var cmdout io.Writer
> ```

same comment.
___
*[`scion/cmd/scion/showpaths.go` line 166 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFULsyX-fvwSFMDwULx:-NFULsyX-fvwSFMDwULy:bopbpwk) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/scion/cmd/scion/showpaths.go#L166)):*
> ```Go
> 	cmd.Flags().StringVar(&flags.tracer, "tracing.agent", "", "Tracing agent address")
> 	cmd.Flags().BoolVar(&flags.cfg.Epic, "epic", false, "Enable EPIC.")
> 	cmd.Flags().MarkDeprecated("json", "json flag is deprecated, use format flag")
> ```

If you only mark it as deprectated, you will also need to assign flgas.format appropriately if the json flag is set.
___
*[`scion/ping/ping.go` line 110 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSUlkw9rrqESz4QR_E:-NFUOXtZ4cm5X23wQJxK:br2i8e6) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/ping/ping.go#L110)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Here and for all the tools (in particular also for showpaths); it would be useful to print a "sequence" representation of the path which can be  to select the path with the `--sequence` flag in a next tool invocation. For example, this could look like `"sequence": "1-ff00:0:133#5 1-ff00:0:120#2,1 1-ff00:0:110#3"`.
This could either be in addition or as replacement of the `hops` array -- even if a consumer wants to process the individual hops in some form, parsing the full sequence representation is quite straight forward.
</blockquote></details>

I like the sequence. I still think we should keep the hops.
Having to parse the sequence in jq for example would be painful.
___
*[`scion/ping/ping.go` line 119 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSYsw32UdrcLYK-kEc:-NFUOgV88qX2Y5nM66zo:b4c9lyr) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/ping/ping.go#L119)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I'd not show the metadata fields (MTU, Latency, Expiry) here. That's what we have showpaths for, or not?
</blockquote></details>

:thumbsup: 
___
*[`scion/ping/ping.go` line 134 at r1](https://reviewable.i [...]

2022-10-31 07:47 UTC, oncilla reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 7 of 14 files reviewed, 21 unresolved discussions (waiting on @bunert and @matzf)

___
*[`scion/cmd/scion/showpaths.go` line 166 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFULsyX-fvwSFMDwULx:-NFh-WFj6gwXqQ84xSQh:bfvtppg) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/scion/cmd/scion/showpaths.go#L166)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

If you only mark it as deprectated, you will also need to assign flgas.format appropriately if the json flag is set.
</blockquote></details>

Never mind. This does the right thing, keep as is.


<!-- Sent from Reviewable.io -->

2022-10-31 09:44 UTC, bunert reviewed
There is no overhead by adding yaml support as well, so I thought it would be nice to add it. But I don't really have an opinion on that, we can also remove it and adjust it to just support the `--json` boolean flag.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287#-:-NFSj86H2W01JBbTQkLI:b-ptcef3)* status: 7 of 14 files reviewed, 21 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`pkg/snet/path.go` line 73 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFU2uXFCX-1FzgKUtkV:-NFgyd-SAGKvqbL9WA6R:bbd1y2r) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/pkg/snet/path.go#L73)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Data representation is not a concern of this library package.
I don't think we should extend this specific type with encoding tags.


</blockquote></details>

So we add another type as a wrapper with tags or just no tags for this struct in the output?
___
*[`pkg/snet/path/epic.go` line 50 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFU37Mb5Dbxu2KWHm1D:-NFhPNs88r0E3PuozT39:b-x9jlsj) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/pkg/snet/path/epic.go#L50)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Make this a method on the pointer receiver of EPIC.

But I'm questioning now whether this is even a valid thing to do.
The cloned path should not be used to create actual dataplane packets.

Maybe we could have a private field `cloned` and return an error in `SetPath` if the path is cloned.

@matzf thoughts?




</blockquote></details>

When changing the remote struct in the traceroute updates this is not required anymore. 
___
*[`pkg/snet/path/epic.go` line 51 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFU3wbl43aGiCZCi686:-NFgzSW58TP9FyZNYGH5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/pkg/snet/path/epic.go#L51)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

If we were to keep this, I would write it like so:
</blockquote></details>

Done.
___
*[`pkg/snet/path/path.go` line 44 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFST7y1ECcw2zq6SQJx:-NFSlZK86F_hR9_L34Up:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/pkg/snet/path/path.go#L44)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Why not just use `snet.PathInterface`?
</blockquote></details>

Done.
___
*[`private/path/pathpol/sequence.go` line 299 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFUJAyl78fvbe92YQr8:-NFgzzBk5dOzu7IXDftF:b-m0ixzm) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/private/path/pathpol/sequence.go#L299)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

The sequence that is being built is always fully qualified.
Thus the example should not have any wild cards.

Also, let's use a "code block" for the example:
https://tip.golang.org/doc/comment


</blockquote></details>

correct that way?
___
*[`scion/cmd/scion/ping.go` line 281 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSauHqDNMX5Q6hyRgh:-NFSy6Wq--OPZfxzP2PC:b-64rrsh) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/cmd/scion/ping.go#L281)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

It would be great if this could additionally print `min/avg/max/mdev` round trip time both in "human" and machine readable output formats. The "human" format should match the format of IP `ping`.
Create the Statistics struct with calculated loss and RTT values first and adapt the pingSummary function to print the values from this struct.
</blockquote></details>

Added it using the same format as the time in each update:
`rtt min/avg/max/mdev = 396µs/849µs/1.547ms/501µs`

Should I adjust it to match the `ip ping` format?
`rtt min/avg/max/mdev = 0.028/0.057/0.089/0.023 ms`
___
*[`scion/cmd/scion/ping.go` line 67 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFUJwrhB7-ZIrMtMxxO:-NFh-6PoEyArqwDDcxgS:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/scion/cmd/scion/ping.go#L67)):*
> ```Go
> 	// describes the latency between interface i and i+1.
> 	Latency []time.Duration `json:"latency,omitempty" yaml:"latency,omitempty"`
> 	LocalIp net.IP          `json:"local_ip,omitempty" yaml:"local_ip,omitempty"`
> ```

Done.
___
*[`scion/cmd/scion/ping.go` line 71 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFUJzzUBh3t8NB-zxRw:-NFh-8CA2Gggc__zdKgS:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/scion/cmd/scion/ping.go#L71)):*
> ```Go
> 	// The maximum transmission unit in bytes for SCION packets. This represents the protocol data
> 	// unit (PDU) of the SCION layer on this path.
> 	Mtu int `json:"mtu" yaml:"mtu"`
> ```

Done.
___
*[`scion/cmd/scion/ping.go` line 139 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFUKQaj3GMi0WkS1e0W:-NFh6Wkq7a7SVEPMu4tg:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/scion/cmd/scion/ping.go#L139)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I would abstract this a step further.

```go
printf := func(fmt string, ctx ...interface{}) {}
if flags.format == human {
  printf := func(fmt string, ctx ...interface{}) {
    fmt.Fprintf(cmd.OutOrStdout(), fmt, ctx...)
  }
}
```

Furthermore, this code appears in all commands.
Let's extract this into a helper.

</blockquote></details>

Done.
___
*[`scion/cmd/scion/ping.go` line 431 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFULH1-BVI2Mqj-B4Wo:-NFh7d_a1CxMZ6c3CfXy:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/scion/cmd/scion/ping.go#L431)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I think these two methods do not really add value.
Just call the encoders directly and drop the methods here.
</blockquote></details>

Done.
___
*[`scion/cmd/scion/showpaths.go` line 86 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFULaBoC01LoS3o3XU4:-NFh7etm91QALnO_PsY6:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/scion/cmd/scion/showpaths.go#L86)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

same comment.
</blockquote></details>

Done.
___
*[`scion/ping/ping.go` line 88 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSeiGZ-pMQkdsNxY1c:-NFT-2dw7l9Dqm-xW-SK:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/ping/ping.go#L88)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

These new types really seem to be specific to the update handler used in the `cmd` package. Move all of these new types to `scion/cmd/scion/ping.go`.
</blockquote></details>

Done.
___
*[`scion/ping/ping.go` line 110 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSUlkw9rrqESz4QR_E:-NFTThiT4zoP1eAGBkVZ:bk15i99) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/ping/ping.go#L110)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I like the sequence. I still think we should keep the hops.
Having to parse the sequence in jq for example would be painful.
</blockquote></details>

I added the `hops_sequence` field for it. If we remove th [...]

2022-10-31 09:54 UTC, bunert reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 0 of 15 files reviewed, 21 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`scion/traceroute/traceroute.go` line 346 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFUO1te8oFCL6qBkwW1:-NFhSFkt2dVSnxjYOK8e:b-91gwlj) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/scion/traceroute/traceroute.go#L346)):*
<details><summary><i>Previously, bunert wrote…</i></summary><blockquote>

Thanks for pointing this out. Much cleaner now.
</blockquote></details>

Not sure about the changes as it is not a pointer anymore. Would be great to check if it is okay if  we skip those checks, for example in this function:
`func (u Update) empty() bool {`
___
*[`pkg/snet/path.go` line 73 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFU2uXFCX-1FzgKUtkV:-NFhSB3A9SVD-SWG5rY5:b-vpmwtz) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/pkg/snet/path.go#L73)):*
<details><summary><i>Previously, bunert wrote…</i></summary><blockquote>

So we add another type as a wrapper with tags or just no tags for this struct in the output?
</blockquote></details>

^ done


<!-- Sent from Reviewable.io -->

2022-10-31 15:07 UTC, matzf requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 0 of 15 files reviewed, 15 unresolved discussions (waiting on @bunert and @oncilla)

___
*[`scion/cmd/scion/ping.go` line 281 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSauHqDNMX5Q6hyRgh:-NFiPEuA9Zal9l8mNZ4w:b-ns7jlr) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/cmd/scion/ping.go#L281)):*
<details><summary><i>Previously, bunert wrote…</i></summary><blockquote>

Added it using the same format as the time in each update:
`rtt min/avg/max/mdev = 396µs/849µs/1.547ms/501µs`

Should I adjust it to match the `ip ping` format?
`rtt min/avg/max/mdev = 0.028/0.057/0.089/0.023 ms`
</blockquote></details>

Great!

In my opinion, the formatting with mixed units  (milliseconds vs microseconds) makes processing of the results harder, both for humans and machines. Something simple like `fmt.Sprintf("%.3fms", float64(v.Nanoseconds())/1e6)` would work nicely both here and for the individual ping updates.
Not blocking, this can also be revisited later.
___
*[`scion/ping/ping.go` line 110 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSUlkw9rrqESz4QR_E:-NFiRfOr3_LlTK8MGSJ9:b5d2lpp) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/ping/ping.go#L110)):*
<details><summary><i>Previously, bunert wrote…</i></summary><blockquote>

I added the `hops_sequence` field for it. If we remove the additional path information (MTU, Latency, Expiry) from the `ping` cmd, I was thinking about removing the hops array as well. So if the user really wants the additional path information, the showpath cmd is the way to go while the ping cmd provides the update information. What do you think?
</blockquote></details>

Sounds good to me.
___
*[`scion/ping/ping.go` line 43 at r5](https://reviewable.io/reviews/scionproto/scion/4287#-NFiR80z-228TREMk12y:-NFiR80z-228TREMk12z:bcd4oni) ([raw file](https://github.com/scionproto/scion/blob/ca0ef39c5550afc4c7f62bd374d68b3c73d49f0c/scion/ping/ping.go#L43)):*
> ```Go
> 	AvgRTT   time.Duration `json:"avg_RTT" yaml:"avg_RTT"`
> 	MaxRTT   time.Duration `json:"max_RTT" yaml:"max_RTT"`
> 	MdevRTT  time.Duration `json:"mdev_RTT" yaml:"mdev_RTT"`
> ```

Having all of this information here would be nice _if_ the ping.Run would actually compute these. As the values are computed outside, it seems a bit odd returning this incomplete struct from `ping.Run`. I'd move the extended stats (and the encoding flags) to a separate type in the `cmd/scion/ping` package.


<!-- Sent from Reviewable.io -->

2022-10-31 15:40 UTC, oncilla requested changes
> we can also remove it and adjust it to just support the --json boolean flag.

Even if we would only support json and human encoding, I would still go for --format flag.
you never know what the future holds, and boolean flags are not very flexible/extendible.

In any case. I think we should keep yaml. IMO, it is the more human friendly machine readable format anyway.

> Reviewed 2 of 11 files at r3, 12 of 13 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287#-:-NFigXmf-7vULVIvv151:b-rysfy6)* status: all files reviewed, 8 unresolved discussions (waiting on @bunert and @matzf)

___
*[`private/path/pathpol/sequence.go` line 299 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFUJAyl78fvbe92YQr8:-NFiZzgN-7kBcgUQMEmh:bmex56q) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/private/path/pathpol/sequence.go#L299)):*
<details><summary><i>Previously, bunert wrote…</i></summary><blockquote>

correct that way?
</blockquote></details>

No, no wildcards. All the #0 need to be replaced.

E.g., `1-ff00:0:133#42 1-ff00:0:120#2,1 1-ff00:0:110#21`
___
*[`scion/cmd/scion/common.go` line 19 at r5](https://reviewable.io/reviews/scionproto/scion/4287#-NFi_URH92tgp4mrTteq:-NFi_URH92tgp4mrTter:bbgi69e) ([raw file](https://github.com/scionproto/scion/blob/ca0ef39c5550afc4c7f62bd374d68b3c73d49f0c/scion/cmd/scion/common.go#L19)):*
> ```Go
> 	Fingerprint string `json:"fingerprint" yaml:"fingerprint"`
> 	Hops        []Hop  `json:"hops" yaml:"hops"`
> 	Sequence    string `json:"hops_sequence" yaml:"hops_sequence"`
> ```

We have decided internally to call this `hop_pattern`, at least in the Anapaya Appliance management API it is called this way.
We feel this is a more accurate name for this.

It has been on our todo list to get this also upstreamed to the scion tools. In light of this, I think we should already use the new name here.
And eventually deprecate the old naming.

@matzf thoughts?



_Suggestion:_
```Go
	HopPattern    string `json:"hop_pattern" yaml:"hop_pattern"`
```
___
*[`scion/cmd/scion/common.go` line 49 at r5](https://reviewable.io/reviews/scionproto/scion/4287#-NFicYWh0enpT8I9GXMR:-NFicYWh0enpT8I9GXMS:b22vhuu) ([raw file](https://github.com/scionproto/scion/blob/ca0ef39c5550afc4c7f62bd374d68b3c73d49f0c/scion/cmd/scion/common.go#L49)):*
> ```Go
> // getPrintf returns a printf function for the "human" formatting flag and an empty one for machine
> // readable format flags
> func getPrintf(outputFlag string, writer io.Writer) (
> ```

No need for the printf variable.
Also, never return anything else but the zero value when an error is returned.



_Suggestion:_
```Go
func getPrintf(outputFlag string, writer io.Writer) (
	func(format string, ctx ...interface{}),
	error,
) {
	switch outputFlag {
	case "human":
		return func(format string, ctx ...interface{}) {
			fmt.Fprintf(writer, format, ctx...)
		}, nil
	case "yaml", "json":
		return func(format string, ctx ...interface{}) {}, nil
	default:
		return nil, serrors.New("format not supported", "format", outputFlag)
	}
}
```
___
*[`scion/cmd/scion/traceroute.go` line 52 at r5](https://reviewable.io/reviews/scionproto/scion/4287#-NFidJFO7ttNAcla6p35:-NFidJFO7ttNAcla6p36:b-xgjey0) ([raw file](https://github.com/scionproto/scion/blob/ca0ef39c5550afc4c7f62bd374d68b3c73d49f0c/scion/cmd/scion/traceroute.go#L52)):*
> ```Go
> 
> // Path defines model for Path.
> type TraceroutePath struct {
> ```

Why is there a specific type fro traceroute?
I would expect this to be exactly the same as ping.
___
*[`scion/cmd/scion/traceroute.go` line 97 at r5](https://reviewable.io/reviews/scionproto/scion/4287#-NFidV--DEK8IvseGWyP:-NFidV--DEK8IvseGWyQ:bqkikpy) ([raw file](https://github.com/scionproto/scion/blob/ca0ef39c5550afc4c7f62bd374d68b3c73d49f0c/scion/cmd/scion/traceroute.go#L97)):*
> ```Go
> SCMP traceroute packets.
> 
> 'showpaths' can be instructed to output the paths in a specific format using the \--format flag.
> ```

That line seems to be a copy paste mistake.
This is the traceroute tool.

TBH, I don't think this adds value. If you do --help, you will see the format flag anyway.
___
*[`scion/ping/ping.go` line 110 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSUlkw9rrqESz4QR_E:-NFieD6R3nPBed4C8M3F:bpbe3zo) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/ping/ping.go#L110)):*
> So if the user really wants the additional path information, the showpath cmd is the way to go while the ping cmd provides the update information. What do you think?

I would rather keep the hops always. IMO, the a remote address without the path is underspecified because in SCION the path information is actually crucial to know where the packet is traveling through. Thus, I also consider the output underspecified if the path is not there. Having to do showpaths just to get the path hops is cumbersome and also prone to race conditions.

For me, this is in a different category then the extended path information like advertised latencies etc..
___
*[`scion/traceroute/traceroute.go` line 49 at r5](https://reviewable.io/reviews/scionproto/scion/4287#-NFifcsL8H0Ctekj7MZQ:-NFifcsL8H0Ctekj7MZR:bumn26) ([raw file](https://github.com/scionproto/scion/blob/ca0ef39c5550afc4c7f62bd374d68b3c73d49f0c/scion/traceroute/traceroute.go#L49)):*
> ```Go
> 
> func (u Update) empty() bool {
> 	return u.Index == 0 && u.Interface == 0 && len(u.RTTs) == 0
> ```

you still need to check that remote is of zero value



_Suggestion:_
```Go
return u.Index == 0 && u.Remote == (snet.SCIONAddress{}) && u.Interface == 0 && len(u.RTTs) == 0
```


<!-- Sent from Reviewable.io -->

2022-10-31 19:45 UTC, matzf reviewed
Ok. My view was that as this provides no additional usage options, this is only bloat. This is not a very strong opinion though, so let's go ahead with both yaml and json if you both think it's worth it.


> In any case. I think we should keep yaml. IMO, it is the more human friendly machine readable format anyway.

With this, I disagree (but it's a moot point, see above...). Yes, for things like configuration files, I would also choose yaml over json -- here, yaml features like comments and more concise notation are very advantageous.
For machine generated output that is intended for machine consumption, I'd argue that simplicity of processing is more important, and so json as the lower common denominator wins.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287#-:-NFjVhsf1G8_k5zMJNKO:b-3tlsdn)* status: all files reviewed, 8 unresolved discussions (waiting on @bunert and @oncilla)

___
*[`scion/cmd/scion/common.go` line 19 at r5](https://reviewable.io/reviews/scionproto/scion/4287#-NFi_URH92tgp4mrTteq:-NFjTDpJA5LsOJkbitwD:bnu1lui) ([raw file](https://github.com/scionproto/scion/blob/ca0ef39c5550afc4c7f62bd374d68b3c73d49f0c/scion/cmd/scion/common.go#L19)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

We have decided internally to call this `hop_pattern`, at least in the Anapaya Appliance management API it is called this way.
We feel this is a more accurate name for this.

It has been on our todo list to get this also upstreamed to the scion tools. In light of this, I think we should already use the new name here.
And eventually deprecate the old naming.

@matzf thoughts?
</blockquote></details>

While hop pattern does seem like a good name to me too, I think it's simpler for now to keep the naming consistent. Just `sequence`, like everywhere else.
___
*[`scion/ping/ping.go` line 110 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSUlkw9rrqESz4QR_E:-NFjTxVJ7sschHxyIjVe:bjuui9l) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/ping/ping.go#L110)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

> So if the user really wants the additional path information, the showpath cmd is the way to go while the ping cmd provides the update information. What do you think?

I would rather keep the hops always. IMO, the a remote address without the path is underspecified because in SCION the path information is actually crucial to know where the packet is traveling through. Thus, I also consider the output underspecified if the path is not there. Having to do showpaths just to get the path hops is cumbersome and also prone to race conditions.

For me, this is in a different category then the extended path information like advertised latencies etc..
</blockquote></details>

Fair enough, also sounds good to me. :)


<!-- Sent from Reviewable.io -->

2022-11-01 08:34 UTC, bunert reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 8 of 15 files reviewed, 7 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`private/path/pathpol/sequence.go` line 299 at r3](https://reviewable.io/reviews/scionproto/scion/4287#-NFUJAyl78fvbe92YQr8:-NFm3Kyf925ZtIHoQ13l:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/7aa2e924ef10cb1a52a9dd2d4e6db540b8486c20/private/path/pathpol/sequence.go#L299)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

No, no wildcards. All the #0 need to be replaced.

E.g., `1-ff00:0:133#42 1-ff00:0:120#2,1 1-ff00:0:110#21`
</blockquote></details>

Done.
___
*[`scion/cmd/scion/common.go` line 19 at r5](https://reviewable.io/reviews/scionproto/scion/4287#-NFi_URH92tgp4mrTteq:-NFm3V179hd9T8fR_mwV:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ca0ef39c5550afc4c7f62bd374d68b3c73d49f0c/scion/cmd/scion/common.go#L19)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

While hop pattern does seem like a good name to me too, I think it's simpler for now to keep the naming consistent. Just `sequence`, like everywhere else.
</blockquote></details>

Done.
___
*[`scion/cmd/scion/common.go` line 49 at r5](https://reviewable.io/reviews/scionproto/scion/4287#-NFicYWh0enpT8I9GXMR:-NFm4VTH2yjtlGkLsd0X:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ca0ef39c5550afc4c7f62bd374d68b3c73d49f0c/scion/cmd/scion/common.go#L49)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

No need for the printf variable.
Also, never return anything else but the zero value when an error is returned.
</blockquote></details>

Done.
___
*[`scion/cmd/scion/ping.go` line 281 at r1](https://reviewable.io/reviews/scionproto/scion/4287#-NFSauHqDNMX5Q6hyRgh:-NFm8io6BnJo8LROzs2_:b-hzneor) ([raw file](https://github.com/scionproto/scion/blob/b10510b8cb63a192370a050bfef812abd627ff78/scion/cmd/scion/ping.go#L281)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Great!

In my opinion, the formatting with mixed units  (milliseconds vs microseconds) makes processing of the results harder, both for humans and machines. Something simple like `fmt.Sprintf("%.3fms", float64(v.Nanoseconds())/1e6)` would work nicely both here and for the individual ping updates.
Not blocking, this can also be revisited later.
</blockquote></details>

Added it. I also updated the traceroute update formats to match. 
___
*[`scion/cmd/scion/traceroute.go` line 52 at r5](https://reviewable.io/reviews/scionproto/scion/4287#-NFidJFO7ttNAcla6p35:-NFm97Je0wydXEnOBtXi:bm1kw77) ([raw file](https://github.com/scionproto/scion/blob/ca0ef39c5550afc4c7f62bd374d68b3c73d49f0c/scion/cmd/scion/traceroute.go#L52)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Why is there a specific type fro traceroute?
I would expect this to be exactly the same as ping.
</blockquote></details>

It includes the additional expiry, latency, and MTU information which I removed from the ping cmd as discussed in the review. 
___
*[`scion/cmd/scion/traceroute.go` line 97 at r5](https://reviewable.io/reviews/scionproto/scion/4287#-NFidV--DEK8IvseGWyP:-NFm9j035Imn1BErxvFQ:bqog7zb) ([raw file](https://github.com/scionproto/scion/blob/ca0ef39c5550afc4c7f62bd374d68b3c73d49f0c/scion/cmd/scion/traceroute.go#L97)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

That line seems to be a copy paste mistake.
This is the traceroute tool.

TBH, I don't think this adds value. If you do --help, you will see the format flag anyway.
</blockquote></details>

Agree.
___
*[`scion/ping/ping.go` line 43 at r5](https://reviewable.io/reviews/scionproto/scion/4287#-NFiR80z-228TREMk12y:-NFmHh82CGC4K5bITrTs:b-su8a69) ([raw file](https://github.com/scionproto/scion/blob/ca0ef39c5550afc4c7f62bd374d68b3c73d49f0c/scion/ping/ping.go#L43)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Having all of this information here would be nice _if_ the ping.Run would actually compute these. As the values are computed outside, it seems a bit odd returning this incomplete struct from `ping.Run`. I'd move the extended stats (and the encoding flags) to a separate type in the `cmd/scion/ping` package.
</blockquote></details>

Adapted but the json tags for the initial stats struct remain in the ping package, is that okay?
___
*[`scion/traceroute/traceroute.go` line 49 at r5](https://reviewable.io/reviews/scionproto/scion/4287#-NFifcsL8H0Ctekj7MZQ:-NFmIXOX6O2c3rtn0_TN:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ca0ef39c5550afc4c7f62bd374d68b3c73d49f0c/scion/traceroute/traceroute.go#L49)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

you still need to check that remote is of zero value
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-01 09:43 UTC, oncilla requested changes
> Reviewed 4 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 12 of 15 files reviewed, 7 unresolved discussions (waiting on @bunert and @matzf)

___
*[`scion/cmd/scion/common.go` line 19 at r5](https://reviewable.io/reviews/scionproto/scion/4287#-NFi_URH92tgp4mrTteq:-NFmWyJjDevNsITlQJLC:b-jafz2c) ([raw file](https://github.com/scionproto/scion/blob/ca0ef39c5550afc4c7f62bd374d68b3c73d49f0c/scion/cmd/scion/common.go#L19)):*
<details><summary><i>Previously, bunert wrote…</i></summary><blockquote>

Done.
</blockquote></details>

in that case the json tag should be `sequence` IMO
___
*[`scion/cmd/scion/common.go` line 57 at r6](https://reviewable.io/reviews/scionproto/scion/4287#-NFmZMllAWmd4tcnvxN8:-NFmZMllAWmd4tcnvxN9:b-ih0lly) ([raw file](https://github.com/scionproto/scion/blob/4fee854be16588cee839ea36571c89aceccb053d/scion/cmd/scion/common.go#L57)):*
> ```Go
> 		return func(format string, ctx ...interface{}) {}
> 	default:
> 		return nil
> ```

Why do we no longer return an error in case of unsupported format?

AFAICT, you always need to do the nil check now and the API of this function just became a little less obvious than with an explicit error return value.



_Code quote:_
```Go
	return nil
```
___
*[`scion/cmd/scion/ping.go` line 56 at r6](https://reviewable.io/reviews/scionproto/scion/4287#-NFmX8Qx2AlYobvXI5OT:-NFmX8Qx2AlYobvXI5OU:undefined) ([raw file](https://github.com/scionproto/scion/blob/4fee854be16588cee839ea36571c89aceccb053d/scion/cmd/scion/ping.go#L56)):*
> ```Go
> 	ping.Stats
> 	MinRTT  time.Duration `json:"min_RTT" yaml:"min_RTT"`
> 	AvgRTT  time.Duration `json:"avg_RTT" yaml:"avg_RTT"`
> ```





_Suggestion:_
```Go
	MinRTT  time.Duration `json:"min_rtt" yaml:"min_rtt"`
	AvgRTT  time.Duration `json:"avg_rtt" yaml:"avg_rtt"`
	MaxRTT  time.Duration `json:"max_rtt" yaml:"max_rtt"`
	MdevRTT time.Duration `json:"mdev_rtt" yaml:"mdev_rtt"`
```
___
*[`scion/cmd/scion/ping.go` line 363 at r6](https://reviewable.io/reviews/scionproto/scion/4287#-NFmXb4dD_pEq7y11ntn:-NFmXb4dD_pEq7y11nto:b-gp3bac) ([raw file](https://github.com/scionproto/scion/blob/4fee854be16588cee839ea36571c89aceccb053d/scion/cmd/scion/ping.go#L363)):*
> ```Go
> }
> 
> func (s *Stats) pingSummary(
> ```

This method does too much. It should only have one single responsibility.
At the moment, it calculates the statistics and prints some output.

This should be split into two individual steps.
___
*[`scion/cmd/scion/ping.go` line 386 at r6](https://reviewable.io/reviews/scionproto/scion/4287#-NFmXgr8A95-cXDBdOI8:-NFmXgr8A95-cXDBdOI9:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/4fee854be16588cee839ea36571c89aceccb053d/scion/cmd/scion/ping.go#L386)):*
> ```Go
> 
> // processRTTs computes the min, average, max and standard deviation of the update RTTs
> func (s *Stats) processRTTs(replies []PingUpdate) {
> ```

ditto
___
*[`scion/cmd/scion/traceroute.go` line 52 at r5](https://reviewable.io/reviews/scionproto/scion/4287#-NFidJFO7ttNAcla6p35:-NFmYUg51Q7EutSPmPeF:b34btxt) ([raw file](https://github.com/scionproto/scion/blob/ca0ef39c5550afc4c7f62bd374d68b3c73d49f0c/scion/cmd/scion/traceroute.go#L52)):*
<details><summary><i>Previously, bunert wrote…</i></summary><blockquote>

It includes the additional expiry, latency, and MTU information which I removed from the ping cmd as discussed in the review. 
</blockquote></details>

Yes, but why do you want these extra fields on the traceroute path?

From my point of view, either both ping and traceroute have them, or none.
The two commands are very similar in their purpose, so I would also expect the paths to contain the exact same amount of infromation.

I think @matzf had in mind that you will adapt both and not just ping.


<!-- Sent from Reviewable.io -->

2022-11-01 09:48 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 12 of 15 files reviewed, 7 unresolved discussions (waiting on @bunert and @matzf)

___
*[`scion/cmd/scion/ping.go` line 363 at r6](https://reviewable.io/reviews/scionproto/scion/4287#-NFmXb4dD_pEq7y11ntn:-NFmZlh38B6U3LxjIx7P:b-fvmuis) ([raw file](https://github.com/scionproto/scion/blob/4fee854be16588cee839ea36571c89aceccb053d/scion/cmd/scion/ping.go#L363)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

This method does too much. It should only have one single responsibility.
At the moment, it calculates the statistics and prints some output.

This should be split into two individual steps.
</blockquote></details>

So, IMO. You should have:

```go

res.Statistics = calculateStats(stats, res.Replies)

// ...


func calculateStats(stats ping.Stats, replies []PingUpdate) Stats {
  // calculate stats
}

func printStats(stats Stats, printf func(string, ...interface{})) {
  // print here
}
```

You might even consider dropping printStats and move that functionality into the switch statement


<!-- Sent from Reviewable.io -->

2022-11-01 09:49 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 12 of 15 files reviewed, 6 unresolved discussions (waiting on @bunert and @matzf)

___
*[`scion/cmd/scion/ping.go` line 363 at r6](https://reviewable.io/reviews/scionproto/scion/4287#-NFmXb4dD_pEq7y11ntn:-NFm_wXv5s-DG3J3kBBf:b-oti3h9) ([raw file](https://github.com/scionproto/scion/blob/4fee854be16588cee839ea36571c89aceccb053d/scion/cmd/scion/ping.go#L363)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

So, IMO. You should have:

```go

res.Statistics = calculateStats(stats, res.Replies)

// ...


func calculateStats(stats ping.Stats, replies []PingUpdate) Stats {
  // calculate stats
}

func printStats(stats Stats, printf func(string, ...interface{})) {
  // print here
}
```

You might even consider dropping printStats and move that functionality into the switch statement
</blockquote></details>

(also, for the record. I think making this a method with side effects is surprising.)


<!-- Sent from Reviewable.io -->

2022-11-01 14:50 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 11 of 15 files reviewed, 6 unresolved discussions (waiting on @oncilla)

___
*[`scion/cmd/scion/ping.go` line 363 at r6](https://reviewable.io/reviews/scionproto/scion/4287#-NFmXb4dD_pEq7y11ntn:-NFncRyR1Ta7TDUlZc3F:b-2fe7gs) ([raw file](https://github.com/scionproto/scion/blob/4fee854be16588cee839ea36571c89aceccb053d/scion/cmd/scion/ping.go#L363)):*
<details><summary><i>Previously, bunert wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Almost. This should not write to the `ping.Stats` struct but _return_ a `Stats` object. I think that's what @oncilla meant also.
Perhaps it makes more sense to move `Loss` and `Time` to `Stats` too (currently in `ping.Stats`). Then it's clearer that all these fields should be populated here, in calculateStats.

Instead of
```go
			calculateStats(&stats, time.Since(start))
			res.Statistics.Stats = stats
			processRTTs(&res.Statistics, res.Replies)
```

we should have

```go
			res.Statistics = calculateStats(stats, time.Since(start), res.Replies)
```


<!-- Sent from Reviewable.io -->

2022-11-01 15:16 UTC, bunert reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 11 of 15 files reviewed, 6 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`scion/cmd/scion/ping.go` line 363 at r6](https://reviewable.io/reviews/scionproto/scion/4287#-NFmXb4dD_pEq7y11ntn:-NFnhPp39-neGm-FCEMF:b-sla47c) ([raw file](https://github.com/scionproto/scion/blob/4fee854be16588cee839ea36571c89aceccb053d/scion/cmd/scion/ping.go#L363)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Almost. This should not write to the `ping.Stats` struct but _return_ a `Stats` object. I think that's what @oncilla meant also.
Perhaps it makes more sense to move `Loss` and `Time` to `Stats` too (currently in `ping.Stats`). Then it's clearer that all these fields should be populated here, in calculateStats.

Instead of
```go
			calculateStats(&stats, time.Since(start))
			res.Statistics.Stats = stats
			processRTTs(&res.Statistics, res.Replies)
```

we should have

```go
			res.Statistics = calculateStats(stats, time.Since(start), res.Replies)
```

</blockquote></details>

Ah got it thanks.


<!-- Sent from Reviewable.io -->

2022-11-01 16:16 UTC, matzf requested changes
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 11 of 15 files reviewed, 6 unresolved discussions (waiting on @bunert and @oncilla)

___
*[`scion/cmd/scion/ping.go` line 316 at r8](https://reviewable.io/reviews/scionproto/scion/4287#-NFnwn292v809P2X7xhU:-NFnwn292v809P2X7xhV:bjp69y0) ([raw file](https://github.com/scionproto/scion/blob/f3b6e00579d1e430c5f0244da9a22994d045d09b/scion/cmd/scion/ping.go#L316)):*
> ```Go
> 						fmt.Sprintf("%.3f", float64(res.Statistics.AvgRTT.Nanoseconds())/1e6),
> 						fmt.Sprintf("%.3f", float64(res.Statistics.MaxRTT.Nanoseconds())/1e6),
> 						fmt.Sprintf("%.3f", float64(res.Statistics.MdevRTT.Nanoseconds())/1e6),
> ```

This is already in a formatting call, no need to Sprintf first.



_Suggestion:_
```Go
					printf("rtt min/avg/max/mdev = %.3f/%.3f/%.3f/%.3f ms\n",
						float64(res.Statistics.MinRTT.Nanoseconds())/1e6,
						float64(res.Statistics.AvgRTT.Nanoseconds())/1e6,
						float64(res.Statistics.MaxRTT.Nanoseconds())/1e6,
						float64(res.Statistics.MdevRTT.Nanoseconds())/1e6,
```


<!-- Sent from Reviewable.io -->

2022-11-01 16:32 UTC, bunert reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 11 of 15 files reviewed, 6 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`scion/cmd/scion/ping.go` line 316 at r8](https://reviewable.io/reviews/scionproto/scion/4287#-NFnwn292v809P2X7xhU:-NFo1LpH6sae4jnjqOrA:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f3b6e00579d1e430c5f0244da9a22994d045d09b/scion/cmd/scion/ping.go#L316)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This is already in a formatting call, no need to Sprintf first.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-02 13:28 UTC, oncilla requested changes
> Reviewed 2 of 4 files at r7, 1 of 2 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: all files reviewed, 2 unresolved discussions (waiting on @bunert and @matzf)

___
*[`scion/cmd/scion/common.go` line 57 at r6](https://reviewable.io/reviews/scionproto/scion/4287#-NFmZMllAWmd4tcnvxN8:-NFsW9eWDBtAtSkMBfyn:b-kwm4hw) ([raw file](https://github.com/scionproto/scion/blob/4fee854be16588cee839ea36571c89aceccb053d/scion/cmd/scion/common.go#L57)):*
<details><summary><i>Previously, bunert (Tobias Buner) wrote…</i></summary><blockquote>

Your previous comment mentioned removing the printf variable and return nil instead of an error. We still return an error if the function returns nil just on the caller side. 
</blockquote></details>

No, my previous comment was that you should return nil instead of an actual value for the **first** return value in case that the second return value (error) is non-nil.

Check out the suggestion I added (which you can copy paste one-to-one)

![image.png](https://files.reviewableusercontent.io/images/reviewable/5121633/Wgz50QfP9es3NIy5AMtgLhF_/image.png)


<!-- Sent from Reviewable.io -->

2022-11-02 13:39 UTC, bunert reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`scion/cmd/scion/common.go` line 57 at r6](https://reviewable.io/reviews/scionproto/scion/4287#-NFmZMllAWmd4tcnvxN8:-NFsYv7oAa2PEfksLn9e:b-2ror93) ([raw file](https://github.com/scionproto/scion/blob/4fee854be16588cee839ea36571c89aceccb053d/scion/cmd/scion/common.go#L57)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

No, my previous comment was that you should return nil instead of an actual value for the **first** return value in case that the second return value (error) is non-nil.

Check out the suggestion I added (which you can copy paste one-to-one)

![image.png](https://files.reviewableusercontent.io/images/reviewable/5121633/Wgz50QfP9es3NIy5AMtgLhF_/image.png)

</blockquote></details>

Got it thanks.


<!-- Sent from Reviewable.io -->

2022-11-02 14:03 UTC, oncilla requested changes
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: all files reviewed, 2 unresolved discussions (waiting on @bunert and @matzf)

___
*[`scion/cmd/scion/common.go` line 49 at r10](https://reviewable.io/reviews/scionproto/scion/4287#-NFsco7O4-wdS5MVOM47:-NFsco7O4-wdS5MVOM48:bimspg4) ([raw file](https://github.com/scionproto/scion/blob/597e3fba33b055a3df8ace8a66cadd07a7fe0ed2/scion/cmd/scion/common.go#L49)):*
> ```Go
> // getPrintf returns a printf function for the "human" formatting flag and an empty one for machine
> // readable format flags
> func getPrintf(outputFlag string, writer io.Writer) (
> ```

We do not split up the return values. So this would be formatted as

```
func getPrintf(
	outputFlag string,
	writer io.Writer,
) (func(format string, ctx ...interface{}), error) {
```

But we can just rename `outputFlag` to `output` and it will fit on one line.


<!-- Sent from Reviewable.io -->

2022-11-02 14:08 UTC, bunert reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`scion/cmd/scion/common.go` line 49 at r10](https://reviewable.io/reviews/scionproto/scion/4287#-NFsco7O4-wdS5MVOM47:-NFsf5qCEW-fJuoYHJpg:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/597e3fba33b055a3df8ace8a66cadd07a7fe0ed2/scion/cmd/scion/common.go#L49)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

We do not split up the return values. So this would be formatted as

```
func getPrintf(
	outputFlag string,
	writer io.Writer,
) (func(format string, ctx ...interface{}), error) {
```

But we can just rename `outputFlag` to `output` and it will fit on one line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-02 14:11 UTC, oncilla reviewed
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2022-11-02 14:11 UTC, oncilla approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2022-11-02 16:26 UTC, matzf requested changes
> Reviewed 1 of 11 files at r3, 7 of 13 files at r4, 1 of 7 files at r6, 1 of 2 files at r8, 1 of 3 files at r9, 3 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: all files reviewed, 5 unresolved discussions (waiting on @bunert)

___
*[`private/path/pathpol/sequence.go` line 325 at r11](https://reviewable.io/reviews/scionproto/scion/4287#-NFsjOep6efvka6wEed7:-NFsjOep6efvka6wEed8:bn086xy) ([raw file](https://github.com/scionproto/scion/blob/b7b06b9e1709b9c78b2e1cb797f4fac1701a261c/private/path/pathpol/sequence.go#L325)):*
> ```Go
> 		}
> 		hops = append(hops, hop(ifaces[len(ifaces)-1].IA, ifaces[len(ifaces)-1].ID, 0))
> 		desc = strings.Join(hops, " ") + " "
> ```

Nit. This adds a trailing whitespace:

```
"sequence": "1-ff00:0:112#0,1 1-ff00:0:110#2,1 1-ff00:0:111#41,0 ",
                                                                ^
```

Not sure if this is relevant for the operation of the sequence matcher, but in the output it looks a bit odd.
___
*[`scion/cmd/scion/common.go` line 1 at r11](https://reviewable.io/reviews/scionproto/scion/4287#-NFso67620tzN0D1_ie_:-NFso67620tzN0D1_iea:b-lek9x9) ([raw file](https://github.com/scionproto/scion/blob/b7b06b9e1709b9c78b2e1cb797f4fac1701a261c/scion/cmd/scion/common.go#L1)):*
> ```Go
> package main
> ```

Missing license text.
___
*[`scion/cmd/scion/common.go` line 33 at r11](https://reviewable.io/reviews/scionproto/scion/4287#-NFshVTl6NP63YLSjzOo:-NFshVTl6NP63YLSjzOp:bp10mfq) ([raw file](https://github.com/scionproto/scion/blob/b7b06b9e1709b9c78b2e1cb797f4fac1701a261c/scion/cmd/scion/common.go#L33)):*
> ```Go
> }
> 
> // GetHops constructs a list of snet path interfaces from an snet path
> ```

nit, `getHops`.
___
*[`scion/cmd/scion/ping.go` line 60 at r11](https://reviewable.io/reviews/scionproto/scion/4287#-NFskrdz1OZN7D9JAAaD:-NFskrdz1OZN7D9JAAaE:b-mgiyzs) ([raw file](https://github.com/scionproto/scion/blob/b7b06b9e1709b9c78b2e1cb797f4fac1701a261c/scion/cmd/scion/ping.go#L60)):*
> ```Go
> 	AvgRTT  time.Duration `json:"avg_rtt" yaml:"avg_rtt"`
> 	MaxRTT  time.Duration `json:"max_rtt" yaml:"max_rtt"`
> 	MdevRTT time.Duration `json:"mdev_rtt" yaml:"mdev_rtt"`
> ```

Nit. I've noticed that in json, `time.Duration` is formatted as an integer number in nanoseconds, but in yaml it's a string including the unit. Ideally this would be consistent. IMO the number is more practical for consumers. Nanoseconds does not feel like a very natural unit for this, perhaps it could be expressed as a float in milliseconds instead.
If you want to tackle this, add a wrapper type that implements the yaml and json marshaller interfaces.
___
*[`scion/cmd/scion/showpaths.go` line 164 at r11](https://reviewable.io/reviews/scionproto/scion/4287#-NFt6dPA-CxpFM2HY2GJ:-NFt6dPA-CxpFM2HY2GK:bkppjjz) ([raw file](https://github.com/scionproto/scion/blob/b7b06b9e1709b9c78b2e1cb797f4fac1701a261c/scion/cmd/scion/showpaths.go#L164)):*
> ```Go
> 	cmd.Flags().StringVar(&flags.tracer, "tracing.agent", "", "Tracing agent address")
> 	cmd.Flags().BoolVar(&flags.cfg.Epic, "epic", false, "Enable EPIC.")
> 	err := cmd.Flags().MarkDeprecated("json", "json flag is deprecated, use format flag")
> ```

Would be nice to still honor the `--json` flag even if it is deprecated. Something like this, somewhere before `getPrintf` :
```go
			if flags.json && !cmd.Flags().Lookup("format").Changed {
				flags.format = "json"
			}

```


<!-- Sent from Reviewable.io -->

2022-11-04 08:40 UTC, matzf approved these changes
> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: all files reviewed, 1 unresolved discussion (waiting on @bunert)

___
*[`scion/cmd/scion/ping.go` line 60 at r11](https://reviewable.io/reviews/scionproto/scion/4287#-NFskrdz1OZN7D9JAAaD:-NG0jWeHA9azpfx0MVnH:b-cg9j6v) ([raw file](https://github.com/scionproto/scion/blob/b7b06b9e1709b9c78b2e1cb797f4fac1701a261c/scion/cmd/scion/ping.go#L60)):*
<details><summary><i>Previously, bunert (Tobias Buner) wrote…</i></summary><blockquote>

Yeah, but I was thinking that adding the unit does not really help when processing it in scripts and without unit, the default behavior seemed reasonable. Otherwise, we display milliseconds assuming the consumer is sure it is about milliseconds. What do you think?
</blockquote></details>

I agree, it's more convenient for processing to have a number value, not a string including a unit. Currently, the yaml output is formatted as a string with a unit -- in my comment I meant to propose changing the yaml output format to also only show a number.

I'm not sure I understand what you mean by "Otherwise, we display milliseconds assuming the consumer is sure it is about milliseconds"; this is true regardless of which unit the value is displayed in. IMO milliseconds would just be the most natural option.


<!-- Sent from Reviewable.io -->

2022-11-07 09:30 UTC, bunert reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[`scion/cmd/scion/ping.go` line 60 at r11](https://reviewable.io/reviews/scionproto/scion/4287#-NFskrdz1OZN7D9JAAaD:-NG2Jj9288EZ9dWnUpnq:bwcoyi7) ([raw file](https://github.com/scionproto/scion/blob/b7b06b9e1709b9c78b2e1cb797f4fac1701a261c/scion/cmd/scion/ping.go#L60)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I agree, it's more convenient for processing to have a number value, not a string including a unit. Currently, the yaml output is formatted as a string with a unit -- in my comment I meant to propose changing the yaml output format to also only show a number.

I'm not sure I understand what you mean by "Otherwise, we display milliseconds assuming the consumer is sure it is about milliseconds"; this is true regardless of which unit the value is displayed in. IMO milliseconds would just be the most natural option.
</blockquote></details>

Got it. I adjusted it to be milliseconds with 3 digits precision. To be consistent I also adjusted the traceroute RTTs.


<!-- Sent from Reviewable.io -->

2022-11-08 14:54 UTC, oncilla reviewed
> Reviewed 4 of 4 files at r12, 1 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2022-11-08 17:57 UTC, matzf requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @bunert and @oncilla)

___
*[`scion/cmd/scion/ping.go` line 60 at r11](https://reviewable.io/reviews/scionproto/scion/4287#-NFskrdz1OZN7D9JAAaD:-NGMGxuMBzM9E1qw3Od_:b-f07yna) ([raw file](https://github.com/scionproto/scion/blob/b7b06b9e1709b9c78b2e1cb797f4fac1701a261c/scion/cmd/scion/ping.go#L60)):*
<details><summary><i>Previously, bunert (Tobias Buner) wrote…</i></summary><blockquote>

Got it. I adjusted it to be milliseconds with 3 digits precision. To be consistent I also adjusted the traceroute RTTs.
</blockquote></details>

Ok great, functionally that's exactly what I had in mind.
In terms of the implementation, I think it's not entirely ideal that this formatting logic is now replicated for every value. 

One way to get around this would be to use a wrapper type for `time.Duration` to take care of the formatting. Here's a specific proposal (only for ping, traceroute not adapted). Feel free to apply this or change it as you see fit.

```diff
diff --git a/scion/cmd/scion/common.go b/scion/cmd/scion/common.go
index 89246babb..1bd4abe35 100644
--- a/scion/cmd/scion/common.go
+++ b/scion/cmd/scion/common.go
@@ -15,9 +15,12 @@
 package main
 
 import (
+	"encoding/json"
 	"fmt"
 	"io"
+	"math"
 	"net"
+	"time"
 
 	"github.com/scionproto/scion/pkg/addr"
 	"github.com/scionproto/scion/pkg/private/common"
@@ -72,3 +75,28 @@ func getPrintf(output string, writer io.Writer) (func(format string, ctx ...inte
 		return nil, serrors.New("format not supported", "format", output)
 	}
 }
+
+type durationMillis time.Duration
+
+func (d durationMillis) String() string {
+	return fmt.Sprintf("%.3fms", d.Millis())
+}
+
+func (d durationMillis) MarshalJSON() ([]byte, error) {
+	return json.Marshal(d.MillisRounded())
+}
+
+func (d durationMillis) MarshalYAML() (interface{}, error) {
+	return d.MillisRounded(), nil
+}
+
+// millis returns the duration as a floating point number of milliseconds
+func (d durationMillis) Millis() float64 {
+	return float64(d) / 1e6
+}
+
+// millisRounded returns the duration as a floating point number of
+// milliseconds, rounded to microseconds (3 digits precision).
+func (d durationMillis) MillisRounded() float64 {
+	return math.Round(float64(d)/1000) / 1000
+}
diff --git a/scion/cmd/scion/ping.go b/scion/cmd/scion/ping.go
index 63289473f..36c8b2467 100644
--- a/scion/cmd/scion/ping.go
+++ b/scion/cmd/scion/ping.go
@@ -52,20 +52,20 @@ type Result struct {
 
 type Stats struct {
 	ping.Stats
-	Loss    int     `json:"packet_loss" yaml:"packet_loss"`
-	Time    float64 `json:"time" yaml:"time"`
-	MinRTT  float64 `json:"min_rtt" yaml:"min_rtt"`
-	AvgRTT  float64 `json:"avg_rtt" yaml:"avg_rtt"`
-	MaxRTT  float64 `json:"max_rtt" yaml:"max_rtt"`
-	MdevRTT float64 `json:"mdev_rtt" yaml:"mdev_rtt"`
+	Loss    int            `json:"packet_loss" yaml:"packet_loss"`
+	Time    durationMillis `json:"time" yaml:"time"`
+	MinRTT  durationMillis `json:"min_rtt" yaml:"min_rtt"`
+	AvgRTT  durationMillis `json:"avg_rtt" yaml:"avg_rtt"`
+	MaxRTT  durationMillis `json:"max_rtt" yaml:"max_rtt"`
+	MdevRTT durationMillis `json:"mdev_rtt" yaml:"mdev_rtt"`
 }
 
 type PingUpdate struct {
-	Size     int     `json:"scion_packet_size" yaml:"scion_packet_size"`
-	Source   string  `json:"source_isd_as" yaml:"source_isd_as"`
-	Sequence int     `json:"scmp_seq" yaml:"scmp_seq"`
-	RTT      float64 `json:"round_trip_time" yaml:"round_trip_time"`
-	State    string  `json:"state" yaml:"state"`
+	Size     int            `json:"scion_packet_size" yaml:"scion_packet_size"`
+	Source   string         `json:"source_isd_as" yaml:"source_isd_as"`
+	Sequence int            `json:"scmp_seq" yaml:"scmp_seq"`
+	RTT      durationMillis `json:"round_trip_time" yaml:"round_trip_time"`
+	State    string         `json:"state" yaml:"state"`
 }
 
 func newPing(pather CommandPather) *cobra.Command {
@@ -289,12 +289,12 @@ On other errors, ping will exit with code 2.
 						Size:     update.Size,
 						Source:   update.Source.String(),
 						Sequence: update.Sequence,
-						RTT:      float64(update.RTT.Nanoseconds()) / 1e6,
+						RTT:      durationMillis(update.RTT),
 						State:    update.State.String(),
 					})
 					printf("%d bytes from %s,%s: scmp_seq=%d time=%s%s\n",
 						update.Size, update.Source.IA, update.Source.Host, update.Sequence,
-						fmt.Sprintf("%.3fms", float64(update.RTT.Nanoseconds())/1e6), additional)
+						durationMillis(update.RTT), additional)
 				},
 			})
 			if err != nil {
@@ -308,14 +308,14 @@ On other errors, ping will exit with code 2.
 				printf("\n--- %s,%s statistics ---\n", remote.IA, remote.Host.IP)
 				printf("%d packets transmitted, %d received, %d%% packet loss, time %v\n",
 					s.Sent, s.Received, res.Statistics.Loss,
-					time.Duration(res.Statistics.Time)*time.Millisecond,
+					res.Statistics.Time,
 				)
 				if s.Received != 0 {
 					printf("rtt min/avg/max/mdev = %.3f/%.3f/%.3f/%.3f ms\n",
-						res.Statistics.MinRTT,
-						res.Statistics.AvgRTT,
-						res.Statistics.MaxRTT,
-						res.Statistics.MdevRTT,
+						res.Statistics.MinRTT.Millis(),
+						res.Statistics.AvgRTT.Millis(),
+						res.Statistics.MaxRTT.Millis(),
+						res.Statistics.MdevRTT.Millis(),
 					)
 				}
 				if stats.Received == 0 {
@@ -384,32 +384,35 @@ func calculateStats(s ping.Stats, replies []PingUpdate, run time.Duration) Stats
 	stats := Stats{
 		Stats: s,
 		Loss:  loss,
-		Time:  math.Round((float64(run.Nanoseconds())/1e6)*1000) / 1000,
+		Time:  durationMillis(run),
 	}
 
 	if len(replies) == 0 {
 		return stats
 	}
-	stats.MinRTT = replies[0].RTT
-	stats.MaxRTT = replies[0].RTT
-	var sum float64
+	minRTT := replies[0].RTT
+	maxRTT := replies[0].RTT
+	var sum durationMillis
 	for i := 0; i < len(replies); i++ {
-		if replies[i].RTT < stats.MinRTT {
-			stats.MinRTT = replies[i].RTT
+		if replies[i].RTT < minRTT {
+			minRTT = replies[i].RTT
 		}
-		if replies[i].RTT > stats.MaxRTT {
-			stats.MaxRTT = replies[i].RTT
+		if replies[i].RTT > maxRTT {
+			maxRTT = replies[i].RTT
 		}
 		sum += replies[i].RTT
 	}
-	stats.AvgRTT = math.Round(sum/float64(len(replies))*1000) / 1000
+	avgRTT := durationMillis(int(sum) / len(replies))
 
 	// standard deviation
 	var sd float64
 	for i := 0; i < len(replies); i++ {
-		sd += math.Pow(replies[i].RTT-stats.AvgRTT, 2)
+		sd += math.Pow(float64(replies[i].RTT-avgRTT), 2)
 	}
-	stats.MdevRTT = math.Round(math.Sqrt(sd/float64(len(replies)))*1000) / 1000
-
+	mdevRTT := math.Sqrt(sd / float64(len(replies)))
+	stats.MinRTT = durationMillis(minRTT)
+	stats.MaxRTT = durationMillis(maxRTT)
+	stats.AvgRTT = durationMillis(avgRTT)
+	stats.MdevRTT = durationMillis(mdevRTT)
 	return stats
 }
```
___
*[`scion/cmd/scion/ping.go` line 54 at r13](https://reviewable.io/reviews/scionproto/scion/4287#-NGMQk7BA1ee3upRIhxL:-NGMQk7BA1ee3upRIhxM:b-y3s7rw) ([raw file](https://github.com/scionproto/scion/blob/13e007aef812126042780400e61ae452fd6cf046/scion/cmd/scion/ping.go#L54)):*
> ```Go
> 
> type Stats struct {
> 	ping.Stats
> ```

In yaml, this creates a `stats` sub-dictionary. Add inline annotation.



_Suggestion:_
```Go
ping.Stats `yaml:",inline"`
```
___
*[`scion/cmd/scion/ping.go` line 65 at r13](https://reviewable.io/reviews/scionproto/scion/4287#-NGMS6ASE_-mYYXCEQxt:-NGMS6ASE_-mYYXCEQxu:b-ss2joa) ([raw file](https://github.com/scionproto/scion/blob/13e007aef812126042780400e61ae452fd6cf046/scion/cmd/scion/ping.go#L65)):*
> ```Go
> type PingUpdate struct {
> 	Size     int     `json:"scion_packet_size" yaml:"scion_packet_size"`
> 	Source   string  `json:"source_isd_as" yaml:"source_isd_as"`
> ```

json/yaml tags don't match usage, the field contains the full SCION address not only ISD-AS.


<!-- Sent from Reviewable.io -->

2022-11-09 14:32 UTC, oncilla reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @bunert and @matzf)

___
*[`scion/cmd/scion/ping.go` line 60 at r11](https://reviewable.io/reviews/scionproto/scion/4287#-NFskrdz1OZN7D9JAAaD:-NGRnTBZ0G9ZpMmGqgkZ:b-529roy) ([raw file](https://github.com/scionproto/scion/blob/b7b06b9e1709b9c78b2e1cb797f4fac1701a261c/scion/cmd/scion/ping.go#L60)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Ok great, functionally that's exactly what I had in mind.
In terms of the implementation, I think it's not entirely ideal that this formatting logic is now replicated for every value. 

One way to get around this would be to use a wrapper type for `time.Duration` to take care of the formatting. Here's a specific proposal (only for ping, traceroute not adapted). Feel free to apply this or change it as you see fit.

```diff
diff --git a/scion/cmd/scion/common.go b/scion/cmd/scion/common.go
index 89246babb..1bd4abe35 100644
--- a/scion/cmd/scion/common.go
+++ b/scion/cmd/scion/common.go
@@ -15,9 +15,12 @@
 package main
 
 import (
+	"encoding/json"
 	"fmt"
 	"io"
+	"math"
 	"net"
+	"time"
 
 	"github.com/scionproto/scion/pkg/addr"
 	"github.com/scionproto/scion/pkg/private/common"
@@ -72,3 +75,28 @@ func getPrintf(output string, writer io.Writer) (func(format string, ctx ...inte
 		return nil, serrors.New("format not supported", "format", output)
 	}
 }
+
+type durationMillis time.Duration
+
+func (d durationMillis) String() string {
+	return fmt.Sprintf("%.3fms", d.Millis())
+}
+
+func (d durationMillis) MarshalJSON() ([]byte, error) {
+	return json.Marshal(d.MillisRounded())
+}
+
+func (d durationMillis) MarshalYAML() (interface{}, error) {
+	return d.MillisRounded(), nil
+}
+
+// millis returns the duration as a floating point number of milliseconds
+func (d durationMillis) Millis() float64 {
+	return float64(d) / 1e6
+}
+
+// millisRounded returns the duration as a floating point number of
+// milliseconds, rounded to microseconds (3 digits precision).
+func (d durationMillis) MillisRounded() float64 {
+	return math.Round(float64(d)/1000) / 1000
+}
diff --git a/scion/cmd/scion/ping.go b/scion/cmd/scion/ping.go
index 63289473f..36c8b2467 100644
--- a/scion/cmd/scion/ping.go
+++ b/scion/cmd/scion/ping.go
@@ -52,20 +52,20 @@ type Result struct {
 
 type Stats struct {
 	ping.Stats
-	Loss    int     `json:"packet_loss" yaml:"packet_loss"`
-	Time    float64 `json:"time" yaml:"time"`
-	MinRTT  float64 `json:"min_rtt" yaml:"min_rtt"`
-	AvgRTT  float64 `json:"avg_rtt" yaml:"avg_rtt"`
-	MaxRTT  float64 `json:"max_rtt" yaml:"max_rtt"`
-	MdevRTT float64 `json:"mdev_rtt" yaml:"mdev_rtt"`
+	Loss    int            `json:"packet_loss" yaml:"packet_loss"`
+	Time    durationMillis `json:"time" yaml:"time"`
+	MinRTT  durationMillis `json:"min_rtt" yaml:"min_rtt"`
+	AvgRTT  durationMillis `json:"avg_rtt" yaml:"avg_rtt"`
+	MaxRTT  durationMillis `json:"max_rtt" yaml:"max_rtt"`
+	MdevRTT durationMillis `json:"mdev_rtt" yaml:"mdev_rtt"`
 }
 
 type PingUpdate struct {
-	Size     int     `json:"scion_packet_size" yaml:"scion_packet_size"`
-	Source   string  `json:"source_isd_as" yaml:"source_isd_as"`
-	Sequence int     `json:"scmp_seq" yaml:"scmp_seq"`
-	RTT      float64 `json:"round_trip_time" yaml:"round_trip_time"`
-	State    string  `json:"state" yaml:"state"`
+	Size     int            `json:"scion_packet_size" yaml:"scion_packet_size"`
+	Source   string         `json:"source_isd_as" yaml:"source_isd_as"`
+	Sequence int            `json:"scmp_seq" yaml:"scmp_seq"`
+	RTT      durationMillis `json:"round_trip_time" yaml:"round_trip_time"`
+	State    string         `json:"state" yaml:"state"`
 }
 
 func newPing(pather CommandPather) *cobra.Command {
@@ -289,12 +289,12 @@ On other errors, ping will exit with code 2.
 						Size:     update.Size,
 						Source:   update.Source.String(),
 						Sequence: update.Sequence,
-						RTT:      float64(update.RTT.Nanoseconds()) / 1e6,
+						RTT:      durationMillis(update.RTT),
 						State:    update.State.String(),
 					})
 					printf("%d bytes from %s,%s: scmp_seq=%d time=%s%s\n",
 						update.Size, update.Source.IA, update.Source.Host, update.Sequence,
-						fmt.Sprintf("%.3fms", float64(update.RTT.Nanoseconds())/1e6), additional)
+						durationMillis(update.RTT), additional)
 				},
 			})
 			if err != nil {
@@ -308,14 +308,14 @@ On other errors, ping will exit with code 2.
 				printf("\n--- %s,%s statistics ---\n", remote.IA, remote.Host.IP)
 				printf("%d packets transmitted, %d received, %d%% packet loss, time %v\n",
 					s.Sent, s.Received, res.Statistics.Loss,
-					time.Duration(res.Statistics.Time)*time.Millisecond,
+					res.Statistics.Time,
 				)
 				if s.Received != 0 {
 					printf("rtt min/avg/max/mdev = %.3f/%.3f/%.3f/%.3f ms\n",
-						res.Statistics.MinRTT,
-						res.Statistics.AvgRTT,
-						res.Statistics.MaxRTT,
-						res.Statistics.MdevRTT,
+						res.Statistics.MinRTT.Millis(),
+						res.Statistics.AvgRTT.Millis(),
+						res.Statistics.MaxRTT.Millis(),
+						res.Statistics.MdevRTT.Millis(),
 					)
 				}
 				if stats.Received == 0 {
@@ -384,32 +384,35 @@ func calculateStats(s ping.Stats, replies []PingUpdate, run time.Duration) Stats
 	stats := Stats{
 		Stats: s,
 		Loss:  loss,
-		Time:  math.Round((float64(run.Nanoseconds())/1e6)*1000) / 1000,
+		Time:  durationMillis(run),
 	}
 
 	if len(replies) == 0 {
 		return stats
 	}
-	stats.MinRTT = replies[0].RTT
-	stats.MaxRTT = replies[0].RTT
-	var sum float64
+	minRTT := replies[0].RTT
+	maxRTT := replies[0].RTT
+	var sum durationMillis
 	for i := 0; i < len(replies); i++ {
-		if replies[i].RTT < stats.MinRTT {
-			stats.MinRTT = replies[i].RTT
+		if replies[i].RTT < minRTT {
+			minRTT = replies[i].RTT
 		}
-		if replies[i].RTT > stats.MaxRTT {
-			stats.MaxRTT = replies[i].RTT
+		if replies[i].RTT > maxRTT {
+			maxRTT = replies[i].RTT
 		}
 		sum += replies[i].RTT
 	}
-	stats.AvgRTT = math.Round(sum/float64(len(replies))*1000) / 1000
+	avgRTT := durationMillis(int(sum) / len(replies))
 
 	// standard deviation
 	var sd float64
 	for i := 0; i < len(replies); i++ {
-		sd += math.Pow(replies[i].RTT-stats.AvgRTT, 2)
+		sd += math.Pow(float64(replies[i].RTT-avgRTT), 2)
 	}
-	stats.MdevRTT = math.Round(math.Sqrt(sd/float64(len(replies)))*1000) / 1000
-
+	mdevRTT := math.Sqrt(sd / float64(len(replies)))
+	stats.MinRTT = durationMillis(minRTT)
+	stats.MaxRTT = durationMillis(maxRTT)
+	stats.AvgRTT = durationMillis(avgRTT)
+	stats.MdevRTT = durationMillis(mdevRTT)
 	return stats
 }
```
</blockquote></details>

I think if you use https://pkg.go.dev/encoding#TextMarshaler you can cover both JSON and YAML marshaling with one method.


<!-- Sent from Reviewable.io -->

2022-11-09 14:51 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @bunert and @oncilla)

___
*[`scion/cmd/scion/ping.go` line 60 at r11](https://reviewable.io/reviews/scionproto/scion/4287#-NFskrdz1OZN7D9JAAaD:-NGRqkKrDmVZ23dZYTws:bbyjqrq) ([raw file](https://github.com/scionproto/scion/blob/b7b06b9e1709b9c78b2e1cb797f4fac1701a261c/scion/cmd/scion/ping.go#L60)):*
The TextMarshaler  works if we want to encode something as a JSON/YAML string, but we want it to be a number type.

In [json](https://pkg.go.dev/encoding/json@go1.19.3#Marshal):

> Marshal calls its MarshalText method and encodes the result as a JSON string

The behaviour seems to be the same in yaml (but not documented).


<!-- Sent from Reviewable.io -->

2022-11-09 14:56 UTC, oncilla reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @bunert and @matzf)

___
*[`scion/cmd/scion/ping.go` line 60 at r11](https://reviewable.io/reviews/scionproto/scion/4287#-NFskrdz1OZN7D9JAAaD:-NGRt4Tj56nBSlE_9J8z:b5qwrks) ([raw file](https://github.com/scionproto/scion/blob/b7b06b9e1709b9c78b2e1cb797f4fac1701a261c/scion/cmd/scion/ping.go#L60)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The TextMarshaler  works if we want to encode something as a JSON/YAML string, but we want it to be a number type.

In [json](https://pkg.go.dev/encoding/json@go1.19.3#Marshal):

> Marshal calls its MarshalText method and encodes the result as a JSON string

The behaviour seems to be the same in yaml (but not documented).
</blockquote></details>

Right, sorry for the confusion.


<!-- Sent from Reviewable.io -->

2022-11-10 18:09 UTC, bunert reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 12 of 15 files reviewed, 3 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`scion/cmd/scion/ping.go` line 60 at r11](https://reviewable.io/reviews/scionproto/scion/4287#-NFskrdz1OZN7D9JAAaD:-NGXipq_-AvwioowgpjI:bssozzd) ([raw file](https://github.com/scionproto/scion/blob/b7b06b9e1709b9c78b2e1cb797f4fac1701a261c/scion/cmd/scion/ping.go#L60)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Right, sorry for the confusion.
</blockquote></details>

Great thanks a lot! Adjusted it with your patch and the traceroute part. 
___
*[`scion/cmd/scion/ping.go` line 54 at r13](https://reviewable.io/reviews/scionproto/scion/4287#-NGMQk7BA1ee3upRIhxL:-NGXeH1G2Xs1hMgQs7h_:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/13e007aef812126042780400e61ae452fd6cf046/scion/cmd/scion/ping.go#L54)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

In yaml, this creates a `stats` sub-dictionary. Add inline annotation.
</blockquote></details>

Done.
___
*[`scion/cmd/scion/ping.go` line 65 at r13](https://reviewable.io/reviews/scionproto/scion/4287#-NGMS6ASE_-mYYXCEQxt:-NGXezSE5OXZzdo7yz9D:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/13e007aef812126042780400e61ae452fd6cf046/scion/cmd/scion/ping.go#L65)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

json/yaml tags don't match usage, the field contains the full SCION address not only ISD-AS.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-11 09:28 UTC, matzf requested changes
> Reviewed 2 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @bunert and @oncilla)

___
*[`scion/cmd/scion/traceroute.go` line 214 at r14](https://reviewable.io/reviews/scionproto/scion/4287#-NG_yCjc0BZPvYBIRdEr:-NG_yCjc0BZPvYBIRdEs:b2j57dd) ([raw file](https://github.com/scionproto/scion/blob/a239a37ccb43d7851a90ef9c9d3048494925b38e/scion/cmd/scion/traceroute.go#L214)):*
> ```Go
> 				res.Hops = append(res.Hops, HopInfo{
> 					InterfaceID:    uint16(update.Interface),
> 					IP:             update.Remote.Host.IP().String(),
> ```

Sorry, just one more thing: this panics if Remote is nil. This occurs for hops where no reply packets are received. You can reproduce this by setting a very low timeout like `1us`.

Side note: the traceroute implementation does not handle timeouts very gracefully. Replies arriving after the timeout are still processed and can even lead to negative RTTs for the subsequent packets. This could be fixed by setting the sequence number in the request packet and only process the responses with matching sequence IDs. I'll create an issue for this.


<!-- Sent from Reviewable.io -->

2022-11-11 13:09 UTC, bunert reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @matzf and @oncilla)

___
*[`scion/cmd/scion/traceroute.go` line 214 at r14](https://reviewable.io/reviews/scionproto/scion/4287#-NG_yCjc0BZPvYBIRdEr:-NGafS88BJePNUXKIrfl:bbl69wr) ([raw file](https://github.com/scionproto/scion/blob/a239a37ccb43d7851a90ef9c9d3048494925b38e/scion/cmd/scion/traceroute.go#L214)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Sorry, just one more thing: this panics if Remote is nil. This occurs for hops where no reply packets are received. You can reproduce this by setting a very low timeout like `1us`.

Side note: the traceroute implementation does not handle timeouts very gracefully. Replies arriving after the timeout are still processed and can even lead to negative RTTs for the subsequent packets. This could be fixed by setting the sequence number in the request packet and only process the responses with matching sequence IDs. I'll create an issue for this.

</blockquote></details>

Should now check correctly if the remote is empty and act accordingly. The formatted output contains the interface ID and IA from the path resulting in the following example hop: 
```
    {
      "interface_id": 41,
      "ip": "",
      "isd_as": "1-ff00:0:111",
      "round_trip_times": null
    }
```


<!-- Sent from Reviewable.io -->

2022-11-14 13:03 UTC, oncilla approved these changes
> Reviewed 2 of 3 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2022-11-15 07:32 UTC, matzf approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Thanks for your patience throughout the many feedback rounds. Great work!

> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287#-:-NGu744i5YbSEzL6UQyQ:bncuwf9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bunert)

___
*[`scion/cmd/scion/traceroute.go` line 214 at r14](https://reviewable.io/reviews/scionproto/scion/4287#-NG_yCjc0BZPvYBIRdEr:-NGu6eYiDFAwrnpdDv5I:bmi8ppe) ([raw file](https://github.com/scionproto/scion/blob/a239a37ccb43d7851a90ef9c9d3048494925b38e/scion/cmd/scion/traceroute.go#L214)):*
<details><summary><i>Previously, bunert (Tobias Buner) wrote…</i></summary><blockquote>

Should now check correctly if the remote is empty and act accordingly. The formatted output contains the interface ID and IA from the path resulting in the following example hop: 
```
    {
      "interface_id": 41,
      "ip": "",
      "isd_as": "1-ff00:0:111",
      "round_trip_times": null
    }
```
</blockquote></details>

:100: 


<!-- Sent from Reviewable.io -->

2022-11-28 10:15 UTC, matzf approved these changes
> Reviewed 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4287)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bunert)



<!-- Sent from Reviewable.io -->

2022-11-28 10:55 UTC, merged