doc: update timestamp spec
scionproto/scion pull request #4300
Opened 2022-11-28 16:19 UTC by JordiSubira

This PR updates the Timestamp definition in the SPAO specification. This update follows the discussion in https://github.com/scionproto/scion/issues/4062, making the Timestamp relative to the DRKey Epoch for DRKey SPI associations. Please, use this PR to discuss details, e.g., the upper bound defined for the Epoch length, necessary to define the granularity of the timestamp.

2022-11-29 10:33 UTC, fstreun reviewed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 3 unresolved discussions (waiting on @JordiSubira)

___
*[`doc/cryptography/drkey.rst` line 236 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1vPoH6hVtbDtY1Vys:-NI1vPoH6hVtbDtY1Vyt:bl7hho2) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/cryptography/drkey.rst#L236)):*
> ```reStructuredText
> 
> The upper bound for the epoch length is defined to 3 days, looking for a
> between efﬁciency and security.
> ```

Where does this play a role (besides in the SPAO?)

Maybe we could set a special requirement for the SPAO. DRKey usage in another context (not SPAO) might profit from a more relaxed definition.
___
*[`doc/cryptography/drkey.rst` line 276 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1uToM1b3Te0y9sjwX:-NI1uToM1b3Te0y9sjwY:bvre69f) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/cryptography/drkey.rst#L276)):*
> ```reStructuredText
> the CP-PKI infrastructure.
> 
> The Level 1 key request message contains the ``validTime`` for which the key must be active
> ```

Would it be ok to return a key that is active only due to the grace period? I.e., the validTime is outside epoch end but within the grace period?
Otherwise:

``validTime`` which must be within the key's epoch and ...
___
*[`doc/protocols/authenticator-option.rst` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1qbEREoLbkYkxmAAr:-NI1qbEREoLbkYkxmAAs:b-1qohke) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/protocols/authenticator-option.rst#L58)):*
> ```reStructuredText
>   The granularity must enable to cover the maximum epoch length for DRKey (plus
>   the :ref:`Grace period<drkey-grace>`). 
>   At all times, at most two key
> ```

I understand what you mean here, but I think it's technically phrased wrongly.
Key-epochs can not overlap. Hence, only one key epoch can be active.
However, two keys could be active at the same time.

At all times, at most two keys can be active due to the grace period; ...

If the expressed timestamp is smaller than the epoch length of the current key, the current key has been used.
If the expressed timestamp is larger than the epoch length of the previous key but not by more than the grace period, the previous key has been used.


<!-- Sent from Reviewable.io -->

2022-11-30 10:58 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 3 unresolved discussions (waiting on @fstreun and @JordiSubira)

___
*[`doc/protocols/authenticator-option.rst` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1qbEREoLbkYkxmAAr:-NI6hF6f3ITXM5HNEz7t:b-yr6xy4) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/protocols/authenticator-option.rst#L58)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

I understand what you mean here, but I think it's technically phrased wrongly.
Key-epochs can not overlap. Hence, only one key epoch can be active.
However, two keys could be active at the same time.

At all times, at most two keys can be active due to the grace period; ...

If the expressed timestamp is smaller than the epoch length of the current key, the current key has been used.
If the expressed timestamp is larger than the epoch length of the previous key but not by more than the grace period, the previous key has been used.
</blockquote></details>

Both of these descriptions refer to the active epochs at the time of receiving the packet on the clock of the receiver. However, the timestamp refers to the clock of the sender, at the time of sending the packet. 
For example, if the receiver's clock is a bit behind, and it so receives a packet "from the future", it would wrongly attribute this to the previous epoch.

We mention already that the Timestamp field should be used to filter packets outside of a sensible range around the current time. We can use this range to also help determine the matching epoch, even in the presence of some clock differences:

- The receiver defines an acceptable range of timestamps around the current time; this range must be wide enough to accommodate clock differences between the two end hosts, plus network latency from the sender to the receiver.
- The DRKey epochs (including grace period) overlapping this range are candidates; for each candidate epoch, the receiver checks whether the relative timestamp for this epoch results in a time inside the acceptable range.
- As long as the acceptable range is smaller than the min length of a DRKey epoch (6 minutes, clocks _very_ roughly synchronized), this results in at most one matching epoch. 
- If no matching candidate epoch is found, then the packet is discarded (replay).


<!-- Sent from Reviewable.io -->

2022-11-30 13:03 UTC, fstreun reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 3 unresolved discussions (waiting on @JordiSubira and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1qbEREoLbkYkxmAAr:-NI7_iFB5n7LGbrC8EZq:bigixhr) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/protocols/authenticator-option.rst#L58)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Or perhaps a different way to address this issue of clock differences would be to compare the time resulting from the adding the timestamp value to the start times of the previous, current and next DRKey epochs, and pick the epoch where this result is _closest_ to the current time.

That should lead to the same result as the procedure above, but does not require explicitly specifying a max clock difference (instead, the max acceptable clock difference would be the length of the DRKey epoch).
</blockquote></details>

I like all of your descriptions for the reconstruction of the absolute timestamp.

Especially the statement that the acceptance range must be smaller than the min length of a DRKey epoch.


<!-- Sent from Reviewable.io -->

2022-12-01 11:23 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @fstreun)

___
*[`doc/cryptography/drkey.rst` line 236 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1vPoH6hVtbDtY1Vys:-NICNJP20_DFPf1Q3rUR:bzh8lnu) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/cryptography/drkey.rst#L236)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

Where does this play a role (besides in the SPAO?)

Maybe we could set a special requirement for the SPAO. DRKey usage in another context (not SPAO) might profit from a more relaxed definition.
</blockquote></details>

In a similar vein as for the lower bound, I think it makes sense to define an upper bound. I picked it up as the same maximum validity as for CP AS certificates. We could obviously relax this, but I believe that durations longer than some days would be weird use cases for DRKey. 
___
*[`doc/cryptography/drkey.rst` line 276 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1uToM1b3Te0y9sjwX:-NICPdOo-8QIy78Z13lv:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/cryptography/drkey.rst#L276)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

Would it be ok to return a key that is active only due to the grace period? I.e., the validTime is outside epoch end but within the grace period?
Otherwise:

``validTime`` which must be within the key's epoch and ...
</blockquote></details>

Done.
___
*[`doc/protocols/authenticator-option.rst` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1qbEREoLbkYkxmAAr:-NI7jvso4UIYeXPtm430:b-tr9pbu) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/protocols/authenticator-option.rst#L58)):*
> Or perhaps a different way to address this issue of clock differences would be to compare the time resulting from the adding the timestamp value to the start times of the previous, current and next DRKey epochs, and pick the epoch where this result is closest to the current time.

I added a "Absolute time derivation" section and try to link it to the candidate key for further packet process. This follows the last approach regarding adding the Ts to the previous, current and next epochs. Note that I consider the minimum DRKey Epoch length possible, keeping in mind that Epochs lengths can change from one Epoch to the next.


<!-- Sent from Reviewable.io -->

2022-12-08 15:11 UTC, fstreun reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 5 unresolved discussions (waiting on @JordiSubira and @matzf)

___
*[`doc/cryptography/drkey.rst` line 236 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1vPoH6hVtbDtY1Vys:-NIm7W6v2yeUf3IF-PCg:b-9m9293) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/cryptography/drkey.rst#L236)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

In a similar vein as for the lower bound, I think it makes sense to define an upper bound. I picked it up as the same maximum validity as for CP AS certificates. We could obviously relax this, but I believe that durations longer than some days would be weird use cases for DRKey. 
</blockquote></details>

For the use cases that we are currently thinking about, I agree with you. 
What about adding a note, like for the lower bound, or combining it with the other note? Stating that for currently unknown use cases, the upper bound could be adjusted.
But I don't have a strong opinion about it.
___
*[`doc/protocols/authenticator-option.rst` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1qbEREoLbkYkxmAAr:-NImCJl_7EMpr6Nxwjkw:b-49dp58) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/protocols/authenticator-option.rst#L58)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

> Or perhaps a different way to address this issue of clock differences would be to compare the time resulting from the adding the timestamp value to the start times of the previous, current and next DRKey epochs, and pick the epoch where this result is closest to the current time.

I added a "Absolute time derivation" section and try to link it to the candidate key for further packet process. This follows the last approach regarding adding the Ts to the previous, current and next epochs. Note that I consider the minimum DRKey Epoch length possible, keeping in mind that Epochs lengths can change from one Epoch to the next.
</blockquote></details>

It was a bit confusing what the *at* meant.
Also, it should be stated here what the timestamp actually means (send time).

That *at* is within the epoch E_x is stated later.

For me, it's a bit weird that we use *at* to get the corresponding DRKey/epoch because in the derivation of *at*, the corresponding epoch is already derived.



_Suggestion:_
```reStructuredText
  In turn, this timestamp MAY be used to compute the absolute time (*at*) value, which corresponds to the time at which the packet was sent.
  The section:ref:`Abosulte time derivation<spao-timestamp>` describes the derivation of *at* in detail.
  To retrieve the associated DRKey, if:
```
___
*[`doc/protocols/authenticator-option.rst` line 184 at r2](https://reviewable.io/reviews/scionproto/scion/4300#-NImHBw6AmPbdUjnqNAV:-NImHBw7DgCJ5Xwe-4Rh:undefined) ([raw file](https://github.com/scionproto/scion/blob/166859fa4d4d4aa38826372803c54098280f5857/doc/protocols/authenticator-option.rst#L184)):*
> ```reStructuredText
> :math:`aw := [T-a/2, T +a/2)`
> 
> (i) We consider the minimum epoch length period as the upper bound for the acceptance windows.
> ```





_Suggestion:_
```reStructuredText
We consider the minimum DRKey epoch period as the upper bound for the acceptance windows.
```
___
*[`doc/protocols/authenticator-option.rst` line 189 at r2](https://reviewable.io/reviews/scionproto/scion/4300#-NImGICJD2sdvvQLe_A-:-NImGICJD2sdvvQLe_A0:undefined) ([raw file](https://github.com/scionproto/scion/blob/166859fa4d4d4aa38826372803c54098280f5857/doc/protocols/authenticator-option.rst#L189)):*
> ```reStructuredText
> 1. Given a time instant *T*, considering:
>   - The current epoch (:math:`E_{i}`) as the one whose time range includes *T*.
>   - The previous epoch (:math:`E_{i-1}`) as the prior epoch to (:math:`E_{i}`).
> ```





_Suggestion:_
```reStructuredText
  - Epoch :math:`E_{i}` as the one whose time range includes *T*.
  - Epoch :math:`E_{i-1}` as the prior epoch to :math:`E_{i}`.
  - Epoch :math:`E_{i+1}` as the subsequent epoch to :math:`E_{i}`.
```
___
*[`doc/protocols/authenticator-option.rst` line 197 at r2](https://reviewable.io/reviews/scionproto/scion/4300#-NImH-6T8inQdPk2LGRT:-NImH-6T8inQdPk2LGRU:undefined) ([raw file](https://github.com/scionproto/scion/blob/166859fa4d4d4aa38826372803c54098280f5857/doc/protocols/authenticator-option.rst#L197)):*
> ```reStructuredText
>    :math:`at_{i-1}`, :math:`at_{i}` and :math:`at_{i+1}`.
> 3. Given (i) at most one *absolute time* will be within *aw*. 
>    *at* is then considered as the time used by the sender in the packet authentication.
> ```




<!-- Sent from Reviewable.io -->

2022-12-09 16:25 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @fstreun)

___
*[`doc/protocols/authenticator-option.rst` line 189 at r2](https://reviewable.io/reviews/scionproto/scion/4300#-NImGICJD2sdvvQLe_A-:-NIrhA9D0QGP6ZzLFL0D:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/166859fa4d4d4aa38826372803c54098280f5857/doc/protocols/authenticator-option.rst#L189)):*
> ```reStructuredText
> 1. Given a time instant *T*, considering:
>   - The current epoch (:math:`E_{i}`) as the one whose time range includes *T*.
>   - The previous epoch (:math:`E_{i-1}`) as the prior epoch to (:math:`E_{i}`).
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-12-19 21:44 UTC, fstreun reviewed
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

___
*[`doc/protocols/authenticator-option.rst` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1qbEREoLbkYkxmAAr:-NJgJkKzBtpZDtonzhQH:b45h) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/protocols/authenticator-option.rst#L58)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done.
</blockquote></details>





_Suggestion:_
```reStructuredText
Assume *at* is within the epoch :math:`E_x`.
- If *Ts* is smaller than the epoch's duration ->
  The candidate DRKey is the key whose epoch is :math:`E_{x}`
-  Otherwise ->
    The candidate DRKey is the key whose epoch is :math:`E_{x-1}`.
```


<!-- Sent from Reviewable.io -->

2022-12-19 22:48 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

___
*[`doc/protocols/authenticator-option.rst` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1qbEREoLbkYkxmAAr:-NJgZLe7EppAe6nZAOFQ:btzmxgg) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/protocols/authenticator-option.rst#L58)):*
> ```reStructuredText
>   The granularity must enable to cover the maximum epoch length for DRKey (plus
>   the :ref:`Grace period<drkey-grace>`). 
>   At all times, at most two key
> ```

I think this way to define this is more confusing when considering different validity periods. The grace period extension is defined and fixed. Since grace period duration is << min epoch duration, this will never be ambiguous.


<!-- Sent from Reviewable.io -->

2022-12-20 08:50 UTC, fstreun reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @JordiSubira)

___
*[`doc/protocols/authenticator-option.rst` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1qbEREoLbkYkxmAAr:-NJiayT45dh8isKcI95r:b61l1g0) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/protocols/authenticator-option.rst#L58)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I think this way to define this is more confusing when considering different validity periods. The grace period extension is defined and fixed. Since grace period duration is << min epoch duration, this will never be ambiguous.
</blockquote></details>

I see.
In any case, I still have some concerns:
First, the description should state that *at* is within the epoch of :math:`E_x`. (Otherwise, the "Otherwise" can be anything)
Second, in my understanding, the grace period of :math:`E_x` is within the epoch :math:`E_{x+1}`.
Third, I think it's a bit unfortunate to start with the exceptional case.
Fourth, an implementation should anyways not use this derivation to obtain the correct epoch. Instead, it should obtain the epoch when deriving the absolute time *at*.

Side note: Now I am questioning how fixed the grace period really is. Starting to like again the flag that indicates the usages of the previous epoch's key. With that, the grace



_Suggestion:_
```reStructuredText
Assume *at* is within the epoch :math:`E_x`.
- If *at* is within the :ref:`Grace period<drkey-grace>` of :math:`E_{x-1}` AND
  *Ts* is greater than the Grace period duration ->
  The candidate DRKey is the key whose epoch is :math:`E_{x-1}`
-  Otherwise ->
    The candidate DRKey is the key whose epoch is :math:`E_{x}`.
```


<!-- Sent from Reviewable.io -->

2022-12-20 16:45 UTC, matzf requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @fstreun and @JordiSubira)

___
*[`doc/cryptography/drkey.rst` line 230 at r4](https://reviewable.io/reviews/scionproto/scion/4300#-NJkKd1G0D-K7vyzJvZ8:-NJkKd1G0D-K7vyzJvZ9:b6ul2jp) ([raw file](https://github.com/scionproto/scion/blob/f377f5cb412b0bdf164c45a474bf386574cb7667/doc/cryptography/drkey.rst#L230)):*
> ```reStructuredText
> globally set to 6 minutes.
> 
> The upper bound for the epoch length is defined to 3 days, looking for a
> ```

Missing word.
___
*[`doc/cryptography/drkey.rst` line 276 at r4](https://reviewable.io/reviews/scionproto/scion/4300#-NJkKiOXCkSW7eiOVZD1:-NJkKiOXCkSW7eiOVZD2:bhmosfi) ([raw file](https://github.com/scionproto/scion/blob/f377f5cb412b0bdf164c45a474bf386574cb7667/doc/cryptography/drkey.rst#L276)):*
> ```reStructuredText
> the CP-PKI infrastructure.
> 
> The Level 1 key request message contains the ``validTime`` which must be within the key's epoch
> ```

Nit, previous phrasing seemed better; the `validTime` specifies the key's epoch, not vice versa.
___
*[`doc/protocols/authenticator-option.rst` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1qbEREoLbkYkxmAAr:-NJkJqp48TmYxMOGFcZG:b-yvi3up) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/protocols/authenticator-option.rst#L58)):*
> For me, it's a bit weird that we use at to get the corresponding DRKey/epoch because in the derivation of *at*, the corresponding epoch is already derived.

>  Fourth, an implementation should anyways not use this derivation to obtain the correct epoch. Instead, it should obtain the epoch when deriving the absolute time at.

+1, describing both together would simplify this.

> Side note: Now I am questioning how fixed the grace period really is. Starting to like again the flag that indicates the usages of the previous epoch's key. With that, the grace

Unfinished sentence?
FWIW, I think this scheme also works just fine if the grace period is not fixed. In fact, I think when addressing the concern above (i.e. changing the description to so that *at* and the epoch are determined in one go), the grace period will no longer be explicitly needed in the description.


<!-- Sent from Reviewable.io -->

2022-12-20 19:53 UTC, fstreun reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @JordiSubira)

___
*[`doc/protocols/authenticator-option.rst` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1qbEREoLbkYkxmAAr:-NJl41IsCZafpeLVsSEw:b2cx5o5) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/protocols/authenticator-option.rst#L58)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

> For me, it's a bit weird that we use at to get the corresponding DRKey/epoch because in the derivation of *at*, the corresponding epoch is already derived.

>  Fourth, an implementation should anyways not use this derivation to obtain the correct epoch. Instead, it should obtain the epoch when deriving the absolute time at.

+1, describing both together would simplify this.

> Side note: Now I am questioning how fixed the grace period really is. Starting to like again the flag that indicates the usages of the previous epoch's key. With that, the grace

Unfinished sentence?
FWIW, I think this scheme also works just fine if the grace period is not fixed. In fact, I think when addressing the concern above (i.e. changing the description to so that *at* and the epoch are determined in one go), the grace period will no longer be explicitly needed in the description.
</blockquote></details>

Yes, the scheme would work fine even with a different grace period.
However, the granularity of the timestamp would then only depend on the max DRKey epoch length. Potentially making the scheme a bit simpler, while requiring only one of the reserved bits.


<!-- Sent from Reviewable.io -->

2022-12-21 09:18 UTC, matzf requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @fstreun and @JordiSubira)

___
*[`doc/protocols/authenticator-option.rst` line 40 at r4](https://reviewable.io/reviews/scionproto/scion/4300#-NJnuVs3CiWp8xS1A7LN:-NJnuVs3CiWp8xS1A7LO:bb7dzaw) ([raw file](https://github.com/scionproto/scion/blob/f377f5cb412b0bdf164c45a474bf386574cb7667/doc/protocols/authenticator-option.rst#L40)):*
> ```reStructuredText
>     |    Algorithm  |                    Timestamp                  |
>     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
>     |      RSV      |                  Sequence Number              |
> ```

In an offline discussion some time ago, @fstreun had also suggested to re-arrange the fields in this header as the reserved byte between timestamp and sequence number is rather awkward. Now would still be a good time to change this, especially as we're also mucking around with the timestamp granularity now.

Here's a proposal:

```
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |               Timestamp / Sequence Number                     |
    +                               +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |                               |      RSV      |   Algorithm   |
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

Either this, or the other way around, with algorithm + reserverd byte first, not sure if there is any real difference.

With this, a relatively straight forward approach to set the granularity for the timestamp for DRKey; the timestamp value is in nanoseconds, giving a range of ~78 hours. The applications can choose freely how many bits of the timestamp they set based on a clock vs from a counter.


<!-- Sent from Reviewable.io -->

2022-12-21 10:41 UTC, fstreun reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @JordiSubira and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1qbEREoLbkYkxmAAr:-NJo7T5ADBSsUNJmJggc:b764kw3) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/protocols/authenticator-option.rst#L58)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

How does the flag bit affect the range/granularity of the timestamp? Timestamps in the grace period must be represent-able either way.
</blockquote></details>

With a grace period flag, the timestamp only has to range the max DRKey epoch length.
If the flag is not set, nothing changes.
If the flag is set, simply the DRKey epoch length (of the previous epoch) must be added to the provided timestamp to obtain the epoch's relative timestamp. To derive the correct epoch (out of the three possibilities) the same approach as already described can be used.
Because all epoch starts and ends are known, also the epoch lengths are known. Hence, no new information is required for this approach.

However, with a nanosecond representation 
___
*[`doc/protocols/authenticator-option.rst` line 40 at r4](https://reviewable.io/reviews/scionproto/scion/4300#-NJnuVs3CiWp8xS1A7LN:-NJoC7fkAOBNuNooczMf:b1z80tb) ([raw file](https://github.com/scionproto/scion/blob/f377f5cb412b0bdf164c45a474bf386574cb7667/doc/protocols/authenticator-option.rst#L40)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

In an offline discussion some time ago, @fstreun had also suggested to re-arrange the fields in this header as the reserved byte between timestamp and sequence number is rather awkward. Now would still be a good time to change this, especially as we're also mucking around with the timestamp granularity now.

Here's a proposal:

```
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |               Timestamp / Sequence Number                     |
    +                               +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |                               |      RSV      |   Algorithm   |
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

Either this, or the other way around, with algorithm + reserverd byte first, not sure if there is any real difference.

With this, a relatively straight forward approach to set the granularity for the timestamp for DRKey; the timestamp value is in nanoseconds, giving a range of ~78 hours. The applications can choose freely how many bits of the timestamp they set based on a clock vs from a counter.


</blockquote></details>

+1, using nanoseconds and leaving it up to the application to use a less accurate clock in combination with a counter to ensure uniqueness.

I also do not see much difference between the two representations. However, I like to give the following argument for the other representation (alg | rsv | ts):
If the timestamp is located after the other fields, to obtain the nanoseconds, only a mask (& operation) is required. If the timestamp is located before the other fields, something like a shift would be required to obtain the nanoseconds.
(Implicitly assuming the 64-bit byte order conversion)

Hence, the (alg | rsv | ts) representation seems to be more straightforward to me.


<!-- Sent from Reviewable.io -->

2022-12-27 16:32 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @fstreun and @matzf)

___
*[`doc/cryptography/drkey.rst` line 230 at r4](https://reviewable.io/reviews/scionproto/scion/4300#-NJkKd1G0D-K7vyzJvZ8:-NKJPsmq5XCweK9uaJ_O:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f377f5cb412b0bdf164c45a474bf386574cb7667/doc/cryptography/drkey.rst#L230)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Missing word.
</blockquote></details>

Done.
___
*[`doc/cryptography/drkey.rst` line 276 at r4](https://reviewable.io/reviews/scionproto/scion/4300#-NJkKiOXCkSW7eiOVZD1:-NKJPnHh1TEaQajjoAmY:b-v6kbm) ([raw file](https://github.com/scionproto/scion/blob/f377f5cb412b0bdf164c45a474bf386574cb7667/doc/cryptography/drkey.rst#L276)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit, previous phrasing seemed better; the `validTime` specifies the key's epoch, not vice versa.
</blockquote></details>

I modified it so that it reads in a simpler way
___
*[`doc/protocols/authenticator-option.rst` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1qbEREoLbkYkxmAAr:-NKJPtzHDFH-jjHrmDBZ:b-uicg3n) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/protocols/authenticator-option.rst#L58)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

With a grace period flag, the timestamp only has to range the max DRKey epoch length.
If the flag is not set, nothing changes.
If the flag is set, simply the DRKey epoch length (of the previous epoch) must be added to the provided timestamp to obtain the epoch's relative timestamp. To derive the correct epoch (out of the three possibilities) the same approach as already described can be used.
Because all epoch starts and ends are known, also the epoch lengths are known. Hence, no new information is required for this approach.

However, with a nanosecond representation 
</blockquote></details>

At the moment, I don't see much benefit of having the flag, tbh. I merged both definitions and now it reads more easily and as Matthias mentioned, no need to explicitly mention the grace period, nonetheless, I added a note so that the reader is aware of the previously described situation (if it is too much noise for the reading I will remove it).


<!-- Sent from Reviewable.io -->

2022-12-28 10:35 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @fstreun and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 40 at r4](https://reviewable.io/reviews/scionproto/scion/4300#-NJnuVs3CiWp8xS1A7LN:-NKNHRRSAgxxJlNeUE0V:bx75y4h) ([raw file](https://github.com/scionproto/scion/blob/f377f5cb412b0bdf164c45a474bf386574cb7667/doc/protocols/authenticator-option.rst#L40)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

+1, using nanoseconds and leaving it up to the application to use a less accurate clock in combination with a counter to ensure uniqueness.

I also do not see much difference between the two representations. However, I like to give the following argument for the other representation (alg | rsv | ts):
If the timestamp is located after the other fields, to obtain the nanoseconds, only a mask (& operation) is required. If the timestamp is located before the other fields, something like a shift would be required to obtain the nanoseconds.
(Implicitly assuming the 64-bit byte order conversion)

Hence, the (alg | rsv | ts) representation seems to be more straightforward to me.
</blockquote></details>

Done. I changed the layout, also merged the description. I do not think there's much difference between any of those, it will depend on the (de-)serializing implementation, both seem fine to me. Anyways I picked ( alg | rsv | ts) because I also like it better.


<!-- Sent from Reviewable.io -->

2023-01-03 10:09 UTC, matzf requested changes
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @fstreun and @JordiSubira)

___
*[`doc/protocols/authenticator-option.rst` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1qbEREoLbkYkxmAAr:-NKr1Bx83apq2kppJnHw:bowmejb) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/protocols/authenticator-option.rst#L58)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

At the moment, I don't see much benefit of having the flag, tbh. I merged both definitions and now it reads more easily and as Matthias mentioned, no need to explicitly mention the grace period, nonetheless, I added a note so that the reader is aware of the previously described situation (if it is too much noise for the reading I will remove it).
</blockquote></details>

Ok :+1: 
I think to keep it short, just mention here that the timestamp granularity is 1ns for DRKey and move the discussion to the appendix at the end of the file (which now needs to be updated anyway).
___
*[`doc/protocols/authenticator-option.rst` line 40 at r4](https://reviewable.io/reviews/scionproto/scion/4300#-NJnuVs3CiWp8xS1A7LN:-NKr5rT39TgOdP8N7Zsb:b-4cj3s9) ([raw file](https://github.com/scionproto/scion/blob/f377f5cb412b0bdf164c45a474bf386574cb7667/doc/protocols/authenticator-option.rst#L40)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done. I changed the layout, also merged the description. I do not think there's much difference between any of those, it will depend on the (de-)serializing implementation, both seem fine to me. Anyways I picked ( alg | rsv | ts) because I also like it better.
</blockquote></details>

Excellent :+1: 
___
*[`doc/protocols/authenticator-option.rst` line 54 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr1xZA2zBAcMLo0Pox:-NKr1xZA2zBAcMLo0Poy:b-pl75wc) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L54)):*
> ```reStructuredText
> Timestamp (Sequence Number):
>   Unsigned 48-bit integer value.
>   The applications can choose freely how many bits of this field can be used to represent the Timestamp
> ```

The "freely choose" is only accurate for the DRKey timestamp interpretation. I'd rephrase this introduction; "The Timestamp/Sequence Number field contains a unique value for each packet that can be used for replay detection by the receiver.
The detailed interpretation of the Timestamp/Sequence Number field depends on the SPI."

And then discuss the different cases; DRKey (in detail) and non-DRKey (just as a filler, just keep the old text on the "wrapping counter"/"sliding window").

Mention the "choose freely how many bits" only for the DRKey timestamp (which is defined as nanoseconds, but we allow the sender to set the value be more freely).
___
*[`doc/protocols/authenticator-option.rst` line 62 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr4b_6CzaaKrvluV8g:-NKr4b_6CzaaKrvluV8h:br534fi) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L62)):*
> ```reStructuredText
>   the uniqueness of the combination of timestamp and sequence number.
>   For example, the value can be chosen based on a counter, randomly or even as
>   a constant, provided that the send rate is low enough.
> ```

This paragraph above is no longer accurate and the packet identifier tuple cannot be represented without reference to the DRKey epoch (or the absolute send timestamp).

Move this information down into the section discussion the DRKey case.



_Code quote:_
```reStructuredText
  The sender can arbitrarily choose this value, but it SHOULD ensure
  the uniqueness of the combination of timestamp and sequence number.
  For example, the value can be chosen based on a counter, randomly or even as
  a constant, provided that the send rate is low enough.
  The receiver SHOULD drop packets with duplicate

  .. math::
    (\mathrm{Source\ Address, info[0].Timestamp, Timestamp, Sequence\ Number})

  Moreover, the receiver SHOULD drop packets with timestamps outside of a locally chosen
  range around the current time.
```
___
*[`doc/protocols/authenticator-option.rst` line 81 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr-cWI-f89BDTOT6qE:-NKr-cWI-f89BDTOT6qF:b3we1h8) ([raw file](https://github.com/scionproto/scion/blob/82198c64e2c6fecc83713f56c894698b95d7cdef/doc/protocols/authenticator-option.rst#L81)):*
> ```reStructuredText
>   When used with a :ref:`SPI <spao-spi>` referring to an established
>   security association, this is used as a wrapping counter and replay detection
>   is based on sliding window of expected counter values.
> ```

Please keep this (somewhere, either before or after the DRKey case). I think it makes sense to hint at something other than the DRKey case.



_Code quote:_
```reStructuredText
  When used with a :ref:`SPI <spao-spi>` referring to an established
  security association, this is used as a wrapping counter and replay detection
  is based on sliding window of expected counter values.
  This use case is not specified in detail here. Extending this specification
  in the future will closely follow [`RFC 4302 <https://tools.ietf.org/html/rfc4302>`_].
```


<!-- Sent from Reviewable.io -->

2023-01-04 09:44 UTC, fstreun reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 4 unresolved discussions (waiting on @JordiSubira and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4300#-NI1qbEREoLbkYkxmAAr:-NKw6Riw-RJSiX6-VKhF:b-cu0wwt) ([raw file](https://github.com/scionproto/scion/blob/89ef7dc25706c47d5a53ac9da1c8049013afa47d/doc/protocols/authenticator-option.rst#L58)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Ok :+1: 
I think to keep it short, just mention here that the timestamp granularity is 1ns for DRKey and move the discussion to the appendix at the end of the file (which now needs to be updated anyway).
</blockquote></details>

No idea why there is again an incomplete sentence...
I also don't see much benefit in having a flag when using the nanosecond representation.
___
*[`doc/protocols/authenticator-option.rst` line 54 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr1xZA2zBAcMLo0Pox:-NKw84p2AoJ4mUDE02j8:b-6y97vz) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L54)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The "freely choose" is only accurate for the DRKey timestamp interpretation. I'd rephrase this introduction; "The Timestamp/Sequence Number field contains a unique value for each packet that can be used for replay detection by the receiver.
The detailed interpretation of the Timestamp/Sequence Number field depends on the SPI."

And then discuss the different cases; DRKey (in detail) and non-DRKey (just as a filler, just keep the old text on the "wrapping counter"/"sliding window").

Mention the "choose freely how many bits" only for the DRKey timestamp (which is defined as nanoseconds, but we allow the sender to set the value be more freely).
</blockquote></details>

+1 for rephrasing.
However, in the case of DRKey, the value in the Timestamp/Sequence Number field is not unique. So I would just state that the value can be used for replay detection.


<!-- Sent from Reviewable.io -->

2023-01-04 10:21 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @fstreun and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 54 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr1xZA2zBAcMLo0Pox:-NKwHgCR-7ZcOOKv3_rx:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L54)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

+1 for rephrasing.
However, in the case of DRKey, the value in the Timestamp/Sequence Number field is not unique. So I would just state that the value can be used for replay detection.
</blockquote></details>

Done.
___
*[`doc/protocols/authenticator-option.rst` line 62 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr4b_6CzaaKrvluV8g:-NKwHkDYEtc-sUuN1MTn:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L62)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This paragraph above is no longer accurate and the packet identifier tuple cannot be represented without reference to the DRKey epoch (or the absolute send timestamp).

Move this information down into the section discussion the DRKey case.


</blockquote></details>

Done.
___
*[`doc/protocols/authenticator-option.rst` line 81 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr-cWI-f89BDTOT6qE:-NKwHgmpChHeDxSkoRm4:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/82198c64e2c6fecc83713f56c894698b95d7cdef/doc/protocols/authenticator-option.rst#L81)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Please keep this (somewhere, either before or after the DRKey case). I think it makes sense to hint at something other than the DRKey case.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-04 11:39 UTC, fstreun reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 4 unresolved discussions (waiting on @JordiSubira and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 54 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr1xZA2zBAcMLo0Pox:-NKwRn3K-KmdG_3-u99B:b91xz6k) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L54)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done.
</blockquote></details>

As mentioned, in the DRKey case, this field does not contain a unique value for each packet.
___
*[`doc/protocols/authenticator-option.rst` line 62 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr4b_6CzaaKrvluV8g:-NKwSgTv0mm2NxREdsHt:bphjcoi) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L62)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In the DRKey case with the nanosecond timestamp, I would not mention sequence numbers as this is a different concept.
Furthermore, the nanosecond timestamp still has to be interpreted over all bits of the field (it's not like the nanosecond timestamp suddenly is represented with just 32 bits instead of 48 bits).

Only when it comes to accuracy, an application can choose to reuse the same timestamp multiple times and add it to a counter (that resets after the timestamp is updated) to ensure uniqueness.



_Suggestion:_
```reStructuredText
  When used with a DRKey :ref:`SPI <spao-spi>`, the Timestamp/Sequence Number field contains a timestamp (*Ts) in nanoseconds relative to the :ref:`Epoch<drkey-epoch>` starting time of the associated DRKey.
  Within the associated DRKey :ref:`Epoch<drkey-epoch>`, Ts must be a unique value for each packet.
  Since nanosecond accuracy is not always required, an application can also opt for a less accurate timestamp and use a counter to ensure uniqueness.
```


<!-- Sent from Reviewable.io -->

2023-01-04 11:59 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 4 unresolved discussions (waiting on @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 54 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr1xZA2zBAcMLo0Pox:-NKwcdLj8oUEG2avEB5M:b-pyr0z2) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L54)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

As mentioned, in the DRKey case, this field does not contain a unique value for each packet.
</blockquote></details>

I think this comment applies to the discussion below about the uniqueness of the tuple. Otherwise, could you quote what part are you referring to about the uniqueness?
___
*[`doc/protocols/authenticator-option.rst` line 62 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr4b_6CzaaKrvluV8g:-NKwcPOR-9-AEd7Czk0N:bkw53xb) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L62)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

In the DRKey case with the nanosecond timestamp, I would not mention sequence numbers as this is a different concept.
Furthermore, the nanosecond timestamp still has to be interpreted over all bits of the field (it's not like the nanosecond timestamp suddenly is represented with just 32 bits instead of 48 bits).

Only when it comes to accuracy, an application can choose to reuse the same timestamp multiple times and add it to a counter (that resets after the timestamp is updated) to ensure uniqueness.
</blockquote></details>

I also think this comment belongs to the previous discussion. In any case, I think in the discussion we agreed on letting the application decide on how many bits are used for each item in the case of DRKey SPI. The rational about it was moved to the appendix section as Matthias suggested.


<!-- Sent from Reviewable.io -->

2023-01-04 13:53 UTC, fstreun reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 4 unresolved discussions (waiting on @JordiSubira and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 62 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr4b_6CzaaKrvluV8g:-NKx2Wsz42QIe-TBSNuL:b-w1jkp8) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L62)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

As far as I understand it, we agreed on using a nanosecond timestamp (without any sequence number) in the case of DRKey SPI, and the application can choose how accurate the timestamp is.
E.g., an application could provide an accuracy of ~1024 ns and the last 10 bits of the filed are occupied by a counter to ensure uniqueness. But the timestamp is still nanoseconds over all 48 bits (and the last 10 bits are just for uniqueness).

With the current description, I would interpret it as possible:
An application can use the first 32 bits to represent the relative nanosecond timestamp and use the other bits for something else. But this is not intended as 32 bits are not enough to cover the maximum timespan of a DRKey epoch.

Overall, I guess, I disagree that, in the DRKey case, there is a free choice on splitting the bits of the timestamp/sequence number filed.
There is only a free choice on the accuracy of the timestamp, which to me is something else.
</blockquote></details>

The original suggestion, that I agree with, was as follows:

The applications can choose freely how many bits of the timestamp they set based on a clock vs from a counter.


<!-- Sent from Reviewable.io -->

2023-01-04 14:05 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 4 unresolved discussions (waiting on @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 54 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr1xZA2zBAcMLo0Pox:-NKx20xQ7Je-pj4lvNF5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L54)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

Yes, this one.
</blockquote></details>

Done.
___
*[`doc/protocols/authenticator-option.rst` line 62 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr4b_6CzaaKrvluV8g:-NKx3Dk56Zqy2jDJhCkU:b-gzi8zl) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L62)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

The original suggestion, that I agree with, was as follows:

The applications can choose freely how many bits of the timestamp they set based on a clock vs from a counter.
</blockquote></details>

I personally find both very similar. In any case, it is stated bellow that the granularity MUST enable covering the maximum epoch length. The granularity will depend on how many bits are chosen to be used for the Ts. I see the Ts as a multiple of the chosen granularity, as it is defined in the formula, not as a ns counter. So if you pick 32-bits, the granularity will be ~1ms, otherwise it violates the previous statement.



_Code snippet:_
```reStructuredText
  When used with a DRKey SPI, the granularity must enable to cover the maximum epoch length for DRKey (plus
  the :ref:`Grace period<drkey-grace>`).
```


<!-- Sent from Reviewable.io -->

2023-01-04 14:26 UTC, fstreun reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 4 unresolved discussions (waiting on @JordiSubira and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 62 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr4b_6CzaaKrvluV8g:-NKx9rpT2B-0CnJJqcM3:b4v36wn) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L62)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

The original suggestion:
The field contains a nanosecond timestamp that is relative to ....
A few bits of the timestamp can also be set by a counter, e.g., if accuracy is not available.

Your suggestion:
The field contains a nanosecond timestamp that is relative to ...., and a sequence number.
How many bits each of the two occupies is up to the application.

These two suggestions have different meanings.

The original (48-bit nanosecond) suggestion provides enough bits to ensure uniqueness and to cover the DRKey epoch length.
With that, no granularity calculation has to be done anymore, simplifying everything.
</blockquote></details>

Furthermore, in the original (48-bit nanosecond) suggestion, we agreed on fixing the granularity to 1ns.
While allowing the application to freely choose accuracy.


<!-- Sent from Reviewable.io -->

2023-01-04 14:27 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 4 unresolved discussions (waiting on @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 62 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr4b_6CzaaKrvluV8g:-NKx9JfCCv5OWU7OgXST:b-f6v4h) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L62)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

Furthermore, in the original (48-bit nanosecond) suggestion, we agreed on fixing the granularity to 1ns.
While allowing the application to freely choose accuracy.
</blockquote></details>

The discussion is only restricted to DRKey case. If  I'm not wrong we decided that the application can opt for how many bits are used for each  Ts and SN, we are not fixing that for DRKey 48-bit value is used. This is also what Matthias seems to suggest here: 'The "freely choose" is only accurate for the DRKey timestamp interpretation. I'd rephrase this introduction; "The Timestamp/Sequence Number field contains a unique value for each packet that can be used for replay detection by the receiver.'


<!-- Sent from Reviewable.io -->

2023-01-04 14:30 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 4 unresolved discussions (waiting on @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 62 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr4b_6CzaaKrvluV8g:-NKxAi502FMoce8eITvk:b6hcxt2) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L62)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

The discussion is only restricted to DRKey case. If  I'm not wrong we decided that the application can opt for how many bits are used for each  Ts and SN, we are not fixing that for DRKey 48-bit value is used. This is also what Matthias seems to suggest here: 'The "freely choose" is only accurate for the DRKey timestamp interpretation. I'd rephrase this introduction; "The Timestamp/Sequence Number field contains a unique value for each packet that can be used for replay detection by the receiver.'
</blockquote></details>

Btw, this is growing too much for anyone to make sense out of it. Since we are not introducing any new insight, I'd suggest we continue the discussion offline and get back here once we agree on this.


<!-- Sent from Reviewable.io -->

2023-01-05 19:55 UTC, matzf requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @fstreun and @JordiSubira)

___
*[`doc/protocols/authenticator-option.rst` line 62 at r6](https://reviewable.io/reviews/scionproto/scion/4300#-NKr4b_6CzaaKrvluV8g:-NL2UzxECgcdHgwD2vIU:b4z9mpw) ([raw file](https://github.com/scionproto/scion/blob/a62a94bd18f53b831c643798e7873ad9d166b330/doc/protocols/authenticator-option.rst#L62)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

After an offline discussion with @fstreun, we decided to simplify a bit the text in the Timestamp field description for DRKey and move the application choice for bits used with a clock time vs bits used for a counter to the end. This also simplifies the replay detection now only based on the recovered *at* and source.
</blockquote></details>

Great! :100: 
___
*[`doc/protocols/authenticator-option.rst` line 128 at r9](https://reviewable.io/reviews/scionproto/scion/4300#-NL2TNYwCaZ6-Gt9DcOp:-NL2TNYwCaZ6-Gt9DcOq:bpiagu9) ([raw file](https://github.com/scionproto/scion/blob/cf2f37787740767be0ae6ba04c6f461dcc9c1ffe/doc/protocols/authenticator-option.rst#L128)):*
> ```reStructuredText
>      0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
>     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
>     |             0       |R R T D R|       Protocol Identifier     |
> ```

We're changing the format anyway, should we move these bits up to make it look tidy?


<!-- Sent from Reviewable.io -->

2023-01-06 10:30 UTC, fstreun reviewed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 1 unresolved discussion (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2023-01-06 11:07 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 128 at r9](https://reviewable.io/reviews/scionproto/scion/4300#-NL2TNYwCaZ6-Gt9DcOp:-NL5ku647L9676yQz5TO:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/cf2f37787740767be0ae6ba04c6f461dcc9c1ffe/doc/protocols/authenticator-option.rst#L128)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

We're changing the format anyway, should we move these bits up to make it look tidy?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-16 10:33 UTC, matzf approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 3 unresolved discussions (waiting on @JordiSubira)

___
*[`doc/protocols/authenticator-option.rst` line 71 at r10](https://reviewable.io/reviews/scionproto/scion/4300#-NLtrR8IEbTM1O6Tpjh7:-NLtrR8IEbTM1O6Tpjh8:b-ecqpvx) ([raw file](https://github.com/scionproto/scion/blob/2f5ee1d874249032ffb4ccc809efe9f63d5dc7f6/doc/protocols/authenticator-option.rst#L71)):*
> ```reStructuredText
>   This allows covering the maximum epoch length for DRKey (plus
>   the :ref:`Grace period<drkey-grace>`).
>   See Appendix for a more detailed explanation. 
> ```

Nit. Would seem nicer to keep the two paragraphs related to duplicate suppression closer together. Perhaps remove this paragraph:
Include the "in nanoseconds" when introducing the relative timestamp above ("When used with a DRKey ... a relative timestamp (*Ts*), _counting the nanoseconds since the starting time of the Epoch of the associated DRKey._").

Maybe we don't need to explicitly point out that the range of the field is sufficient here, it seems rather self-evident.
___
*[`doc/protocols/authenticator-option.rst` line 407 at r10](https://reviewable.io/reviews/scionproto/scion/4300#-NLtqwqQ0GQt_7VfBSCC:-NLtqwqQ0GQt_7VfBSCD:btkl7jo) ([raw file](https://github.com/scionproto/scion/blob/2f5ee1d874249032ffb4ccc809efe9f63d5dc7f6/doc/protocols/authenticator-option.rst#L407)):*
> ```reStructuredText
> - this does not appear to work with less than 3 rows. We use the available
>   room to make the timestamp and sequence number 3 bytes each and leave one
>   reserved byte for future extensions (e.g. flags or extended timestamp or
> ```

Nit. This is no longer accurate:



_Suggestion:_
```reStructuredText
- this does not appear to work with less than 3 rows. We use the available
  room for a 48-bit timestamp / sequence number field and leave one
  reserved byte for future extensions (e.g. flags or extended timestamp or
  sequence number).
```
___
*[`doc/protocols/authenticator-option.rst` line 424 at r10](https://reviewable.io/reviews/scionproto/scion/4300#-NLtq9nQ91oqFA8XO3ML:-NLtq9nR5vAbPP1v16Gl:bwdx1ee) ([raw file](https://github.com/scionproto/scion/blob/2f5ee1d874249032ffb4ccc809efe9f63d5dc7f6/doc/protocols/authenticator-option.rst#L424)):*
> ```reStructuredText
> - When the *Ts*/*SN* field is used with DRKey SPI, the application can use a clock that is less
>   accurate than 1 nanosecond and fill out the less significant bits with a counter that represents
>   at every clock tick.
> ```

Nit. Broken sentence "that represents at every clock tick". Not sure what you wanted to say, maybe just end at "counter"?


<!-- Sent from Reviewable.io -->

2023-01-25 15:33 UTC, matzf reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 4 unresolved discussions (waiting on @JordiSubira)

___
*[`doc/protocols/authenticator-option.rst` line 148 at r11](https://reviewable.io/reviews/scionproto/scion/4300#-NMdVTmY4vU22pqnYfHx:-NMdVTmY4vU22pqnYfHy:bc78bii) ([raw file](https://github.com/scionproto/scion/blob/4587083b93326102a72ed39232068cb4860cca5e/doc/protocols/authenticator-option.rst#L148)):*
> ```reStructuredText
> 
> Absolute time and DRKey derivation
> =============================
> ```

Nit. ` WARNING: Title underline too short.`
___
*[`doc/protocols/authenticator-option.rst` line 156 at r11](https://reviewable.io/reviews/scionproto/scion/4300#-NMdWHwt0u3ImSfxo1le:-NMdWHwt0u3ImSfxo1lf:b11t3ci) ([raw file](https://github.com/scionproto/scion/blob/4587083b93326102a72ed39232068cb4860cca5e/doc/protocols/authenticator-option.rst#L156)):*
> ```reStructuredText
> :math:`aw := [T-a/2, T +a/2)`
> 
> (i) We consider the minimum DRKey epoch length as the upper bound for the acceptance windows.
> ```

Nit: this is rendered as `1.` (i believe this is a bug in the read-the-docs theme), so the references to `(i)` below don't really make sense.
___
*[`doc/protocols/authenticator-option.rst` line 163 at r11](https://reviewable.io/reviews/scionproto/scion/4300#-NMdYO-BCA8T7NYmtU3w:-NMdYO-BCA8T7NYmtU3x:b55cdl3) ([raw file](https://github.com/scionproto/scion/blob/4587083b93326102a72ed39232068cb4860cca5e/doc/protocols/authenticator-option.rst#L163)):*
> ```reStructuredText
>   - Epoch :math:`E_{i}` as the one whose time range includes *T*.
>   - Epoch :math:`E_{i-1}` as the prior epoch to :math:`E_{i}`.
>   - Epoch :math:`E_{i+1}` as the subsequent epoch to :math:`E_{i}`.
> ```

Nit. The sub-list is underindented and slightly broken; add one more space to the left and a blank line before the first item (before the first `- Epoch ...`).
___
*[`doc/protocols/authenticator-option.rst` line 413 at r11](https://reviewable.io/reviews/scionproto/scion/4300#-NMdV2TG5lvMh7dOr4PN:-NMdV2TG5lvMh7dOr4PO:b-nm5nf9) ([raw file](https://github.com/scionproto/scion/blob/4587083b93326102a72ed39232068cb4860cca5e/doc/protocols/authenticator-option.rst#L413)):*
> ```reStructuredText
>   .. math::
>       q := \left\lceil\left(
>         \frac{3 \times 24 \times 60 \times 60 \times 10^9}
> ```

Nit. Looks like left-over stuff from copy-pasted formula? Why the ceiling, and what's the `ms` doing here? 
Maybe simpler:



_Suggestion:_
```reStructuredText
  cover the maximum DRKey epoch length with granularity of 1 nanosecond, since
  :math:`2^{48}\,\mathrm{ns} \approx 78.2\,\mathrm{h} \gt 3\,\mathrm{d}`.
```


<!-- Sent from Reviewable.io -->

2023-02-02 15:45 UTC, marcfrei reviewed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 26 unresolved discussions (waiting on @JordiSubira)

___
*[`doc/cryptography/drkey.rst` line 231 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNGZl2S44y2Er1z3KKp:-NNGVz6JC2MIqoLLyybh:blsds1c) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/cryptography/drkey.rst#L231)):*
> ```reStructuredText
> 
> The upper bound for the epoch length is defined to 3 days, looking for a trade-off
> between efﬁciency and security.
> ```

Is that the "ﬁ" ligature? I would just use "f" and "i". 

(Maybe we could use this PR to fix two additional typos in this file:
- "indistingushible" > "indistinguishable" (twice)
- "succesful" > "successful")
___
*[`doc/cryptography/drkey.rst` line 277 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNGUbLNB5YbXBafUZar:-NNGUbLO42YHMrFHjDCb:b-ntjcog) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/cryptography/drkey.rst#L277)):*
> ```reStructuredText
> 
> The Level 1 key request message contains the ``validTime`` that specifies for what time the requested
> key must be valid (it implicitly specifies the epoch for which the key will be valid).
> ```

Remove ".", the sentence is not yet finished here.
___
*[`doc/protocols/authenticator-option.rst` line 40 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNGij-XCODxJNsViQrr:-NNGij-Y83YEE5U1lT2o:b-ue0qfx) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L40)):*
> ```reStructuredText
>     |    Algorithm  |      RSV      |                               |
>     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+                               +
>     |                     Timestamp/Sequence Number                 |
> ```

"Timestamp / Sequence Number" like below in the metadata diagram for the MAC.



_Code quote:_
```reStructuredText
Timestamp/Sequence Number
```
___
*[`doc/protocols/authenticator-option.rst` line 52 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNGipJD09terZ4_N-fj:-NNGipJD09terZ4_N-fk:b-m62twu) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L52)):*
> ```reStructuredText
>   (12 + length of Authenticator).
>   The length depends on algorithm used.
> Timestamp (Sequence Number):
> ```

"Timestamp / Sequence Number"



_Code quote:_
```reStructuredText
Timestamp (Sequence Number)
```
___
*[`doc/protocols/authenticator-option.rst` line 54 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNGjBJ26igJCglCPEYV:-NNGjBJ26igJCglCPEYW:b-g326u3) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L54)):*
> ```reStructuredText
> Timestamp (Sequence Number):
>   Unsigned 48-bit integer value.
>   The Timestamp/Sequence Number field contains a value for each packet that 
> ```

Use "Timestamp / Sequence Number" (spaces around the slash) everywhere. Makes it a little easier to parse (at least for me) and it would be more consistent with the existing text in the appendix 



_Code quote:_
```reStructuredText
Timestamp/Sequence Number
```
___
*[`doc/protocols/authenticator-option.rst` line 58 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNGf83-EdAwrrpp5H30:-NNGf83-EdAwrrpp5H31:b503viz) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L58)):*
> ```reStructuredText
>   The detailed interpretation of the Timestamp/Sequence Number field depends on the SPI.
> 
>   When used with a DRKey :ref:`SPI <spao-spi>`, the field represent a relative Timestamp (*Ts*),
> ```

represents a relative timestamp,
___
*[`doc/protocols/authenticator-option.rst` line 60 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHQ6Qn-B4KxNtX1N3l:-NNHQ6Qo8K4nLjGREpa7:bnnsweq) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L60)):*
> ```reStructuredText
>   When used with a DRKey :ref:`SPI <spao-spi>`, the field represent a relative Timestamp (*Ts*),
>   counting the nanoseconds since the starting time of the associated DRKey :ref:`Epoch<drkey-epoch>`.
>   (See Appendix for a more detailed explanation about the field interpretation).
> ```

Make "Appendix" a link/reference? 
___
*[`doc/protocols/authenticator-option.rst` line 63 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNG_sOiBZB_-TIJ2uXM:-NNG_sOiBZB_-TIJ2uXN:b-56sk10) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L63)):*
> ```reStructuredText
>   The timestamp MAY be used to compute the absolute time (*at*) value, 
>   which corresponds to the time when the packet was sent.
>   The section:ref:`Abosulte time derivation<spao-timestamp>` describes the derivation of *at* and
> ```

Absolute



_Code quote:_
```reStructuredText
Abosulte
```
___
*[`doc/protocols/authenticator-option.rst` line 63 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHF_3eDg3chJyFFYOh:-NNHF_3eDg3chJyFFYOi:b-rxcdvp) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L63)):*
> ```reStructuredText
>   The timestamp MAY be used to compute the absolute time (*at*) value, 
>   which corresponds to the time when the packet was sent.
>   The section:ref:`Abosulte time derivation<spao-timestamp>` describes the derivation of *at* and
> ```

Maybe `AbsTime` instead of `at`, like, e.g., `ExpTime` in doc/protocols/scion-header.rst?
___
*[`doc/protocols/authenticator-option.rst` line 69 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHHBilEFaedlvJRRsf:-NNHHBilEFaedlvJRRsg:b94jk8f) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L69)):*
> ```reStructuredText
>   range around the current time.
> 
>   The sender SHOULD ensure the uniqueness of the absolute time (*at*) per packet.
> ```

meaning "of each packet"? Isn't this too restrictive, given that on the source host many independent processes could be communicating in parallel with the receiver over the same or different higher level (transport and application layer) protocols?
___
*[`doc/protocols/authenticator-option.rst` line 71 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHKIP1BmFoF4maxbTx:-NNHKIP23CukI3kjklqn:b-a7mlu6) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L71)):*
> ```reStructuredText
>   The sender SHOULD ensure the uniqueness of the absolute time (*at*) per packet.
>   The receiver will use the *at* for replay detection and, thus, 
>   it SHOULD drop packets with a duplicate:
> ```

Too restrictive, see above? My picture up till now was that the timestamp could be used to detect and scrub outdated traffic ("drop packets with *at* outside of a locally chosen range around the current time"). The actual duplicate suppression would then happen within the acceptance window of the timestamp-based filtering, based on additional contents of the packet, e.g., the MAC.
___
*[`doc/protocols/authenticator-option.rst` line 74 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHOfTe6ovTzNcg85JX:-NNHOfTfCOvwU7COXKPp:b-xqmtmr) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L74)):*
> ```reStructuredText
> 
>   .. math::
>     (\mathrm{Source\ Address, *at*})
> ```

Maybe mention that "Source Address" means the combination of SrcISD, SrcA [...]

2023-02-02 16:38 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 26 unresolved discussions (waiting on @JordiSubira and @marcfrei)

___
*[`doc/protocols/authenticator-option.rst` line 71 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHKIP1BmFoF4maxbTx:-NNHrLWs2R-nuTDc-Oo0:byrn3bv) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L71)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Too restrictive, see above? My picture up till now was that the timestamp could be used to detect and scrub outdated traffic ("drop packets with *at* outside of a locally chosen range around the current time"). The actual duplicate suppression would then happen within the acceptance window of the timestamp-based filtering, based on additional contents of the packet, e.g., the MAC.
</blockquote></details>

(not sure which one of your comments to reply to)

Note that in the "old" SPAO definition, we had a Timestamp and separate Sequence number field which together were required to be unique. Now these fields have just been combined, but the idea has not changed much.
Now, you propose to include the MAC itself for duplicate detection. To be honest, I don't think we had previously considered this. This seems like a _great_ idea though!

By including the MAC into the "key" for duplicate suppression, the granularity of the timestamp would only limit the rate of _identical_ messages, whereas it previously limited the rate of _any_ message. Surely this would mean that we could lower this timestamp granularity _a lot_, right?
Perhaps this could be even low enough s.t. it becomes reasonable to use an absolute timestamp instead of a relative timestamp -- this would reduce complexity a lot.
___
*[`doc/protocols/authenticator-option.rst` line 147 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHizIJ5t2aTNmnbmzN:-NNHuw4U4r8g1TxQCd_I:bn6z7ji) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L147)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

What is the motivation to associate the timestamp with the DRKey selection? In early prototypes of LightningFilter, the receiver simply tried also to use the key of adjacent epochs (plus grace period) if MAC validation based on the current epoch at the receiver failed. Was this considered as not secure enough? -- Sorry, if this has been discussed before and I missed it.
</blockquote></details>

The main idea of this proposal was to encode the timestamp value relative to the DRKey epoch. The "formalism" described here allows to recover the absolute timestamp _without_ attempting to validate the MAC. 
This would help to weed out outdated packets quickly. It's a small win though, as a flood attack can just fake the timestamps to "advance" to flooding the MAC validation step.


<!-- Sent from Reviewable.io -->

2023-02-02 19:46 UTC, marcfrei reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 26 unresolved discussions (waiting on @JordiSubira and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 71 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHKIP1BmFoF4maxbTx:-NNI_Vpy2uIlQmH4A3uP:b-9umd2c) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L71)):*
> By including the MAC into the "key" for duplicate suppression, the granularity of the timestamp would only limit the rate of identical messages, whereas it previously limited the rate of any message.

The timestamp would still also be useful to get rid of outdated packets and therefore to limit the size of the actual duplicate suppression filter in a later step of the pipeline. I'm not sure how granular the resolution of such a timestamp needs to be. If we would use a resolution of 1ms, e.g., we would "only" get about 9'000 years: 2**48 / 1000 / 60 / 60 / 24 /365 = 8925. But with the additional remark below at the beginning of section "Absolute time and DRKey derivation", I actually think that timestamps relative to the DRKeys epoch would be simple enough as long as we use them after they have been authenticated and thus been associated with the correct DRkey epoch.
___
*[`doc/protocols/authenticator-option.rst` line 147 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHizIJ5t2aTNmnbmzN:-NNIW9au9VurUR3xp_Yx:b-mbmkgt) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L147)):*
> It's a small win though, as a flood attack can just fake the timestamps to "advance" to flooding the MAC validation step.

Yes, that's the reason why in the original LightningFilter design (as far as I understand it) the timestamp based filtering happens based on the authenticated timestamp. In the LightningFilter approach of simply trying the adjacent DRKeys (as a fallback) to see if one of them authenticates the packet, it would then also be clear relative to which epoch the (then already authenticated) timestamp is defined.


<!-- Sent from Reviewable.io -->

2023-02-07 10:33 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 26 unresolved discussions (waiting on @marcfrei and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 69 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHHBilEFaedlvJRRsf:-NNfCTj82WueZ8_5IBz5:b-7urf4) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L69)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

meaning "of each packet"? Isn't this too restrictive, given that on the source host many independent processes could be communicating in parallel with the receiver over the same or different higher level (transport and application layer) protocols?
</blockquote></details>

Indeed, it is to restrictive as we formulate it here. It should be unique per security association, i.e. per DRKey associated protocol. Even more lenient than that would be acceptable, based on the discussion below.
___
*[`doc/protocols/authenticator-option.rst` line 147 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHizIJ5t2aTNmnbmzN:-NNbTYKC6MQ76hzAUCp4:bxa2bb5) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L147)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

> It's a small win though, as a flood attack can just fake the timestamps to "advance" to flooding the MAC validation step.

Yes, that's the reason why in the original LightningFilter design (as far as I understand it) the timestamp based filtering happens based on the authenticated timestamp. In the LightningFilter approach of simply trying the adjacent DRKeys (as a fallback) to see if one of them authenticates the packet, it would then also be clear relative to which epoch the (then already authenticated) timestamp is defined.
</blockquote></details>

If we try first to authenticate the packet, in the worst case we will try out with three different keys (assuming minimum epoch lengths and maximum accepting window length). If an attacker sends a packet which is not correctly authenticated we will compute the MAC three times. In the case that we select the key based on the method described above, we will only try one key, even if the packet has forced to be within the acceptance window.

In https://www.rfc-editor.org/rfc/rfc4302#section-3.4.3 The sequence number is unique per SA, it then verifies that the SN falls into the sliding window and after that it checks the duplication suppression mechanism and finally carries out the Integrity Check Validation. In our case, the procedure described is our method to find out the SA (i.e. what DRKey are we using for that protocol, one out of 3, at most, possible keys). Of course we can do it differently. 


<!-- Sent from Reviewable.io -->

2023-02-07 12:10 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @fstreun, @marcfrei, and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 63 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHF_3eDg3chJyFFYOh:-NNflvgo2MQE-mchaZmC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L63)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Maybe `AbsTime` instead of `at`, like, e.g., `ExpTime` in doc/protocols/scion-header.rst?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-07 19:01 UTC, fstreun reviewed
> Reviewed 1 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @marcfrei and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 71 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHKIP1BmFoF4maxbTx:-NNhDIXm47efu4LjuTph:b-lycqyu) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L71)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

> By including the MAC into the "key" for duplicate suppression, the granularity of the timestamp would only limit the rate of identical messages, whereas it previously limited the rate of any message.

The timestamp would still also be useful to get rid of outdated packets and therefore to limit the size of the actual duplicate suppression filter in a later step of the pipeline. I'm not sure how granular the resolution of such a timestamp needs to be. If we would use a resolution of 1ms, e.g., we would "only" get about 9'000 years: 2**48 / 1000 / 60 / 60 / 24 /365 = 8925. But with the additional remark below at the beginning of section "Absolute time and DRKey derivation", I actually think that timestamps relative to the DRKeys epoch would be simple enough as long as we use them after they have been authenticated and thus been associated with the correct DRkey epoch.
</blockquote></details>

I think we considered to include the MAC into the duplicate detection instead of requiring uniqueness in the timestamp (or at  least I did). I decided against it because this approach assumes that the MAC actually provides some uniqueness. However, identical packets create the same MAC if they use the same timestamp. Hence, protocols would not be allowed to send equal packets. Which I think is too strict. 


<!-- Sent from Reviewable.io -->

2023-02-07 19:14 UTC, marcfrei reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @fstreun and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 71 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHKIP1BmFoF4maxbTx:-NNhHRfFBFcwQ2cw-eKS:b4f14qg) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L71)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

I think we considered to include the MAC into the duplicate detection instead of requiring uniqueness in the timestamp (or at  least I did). I decided against it because this approach assumes that the MAC actually provides some uniqueness. However, identical packets create the same MAC if they use the same timestamp. Hence, protocols would not be allowed to send equal packets. Which I think is too strict. 
</blockquote></details>

Correct. That's why the timestamp is included in the MAC computation, according to the original LF design.


<!-- Sent from Reviewable.io -->

2023-02-09 08:51 UTC, lukedirtwalker requested changes
> Reviewed 1 of 2 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 11 unresolved discussions (waiting on @fstreun, @JordiSubira, @marcfrei, and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 56 at r14](https://reviewable.io/reviews/scionproto/scion/4300#-NNpG7ut0icGeIhJa5ji:-NNpG7ut0icGeIhJa5jj:b-wrs213) ([raw file](https://github.com/scionproto/scion/blob/636f2d98b3b6b3034ddcbaaacedddbfaa22f1125/doc/protocols/authenticator-option.rst#L56)):*
> ```reStructuredText
>   The Timestamp / Sequence Number field contains a value for each packet that 
>   can be used for replay detection by the receiver.
>   The detailed interpretation of the Timestamp / Sequence Number field depends on the SPI.
> ```

wouldn't it make sense to already have the link here and not only below in the next paragraph?



_Suggestion:_
```reStructuredText
:ref:`SPI <spao-spi>`
```
___
*[`doc/protocols/authenticator-option.rst` line 61 at r14](https://reviewable.io/reviews/scionproto/scion/4300#-NNpH4IuBI8f_ZuAaqhq:-NNpH4IuBI8f_ZuAaqhr:bn6g6rr) ([raw file](https://github.com/scionproto/scion/blob/636f2d98b3b6b3034ddcbaaacedddbfaa22f1125/doc/protocols/authenticator-option.rst#L61)):*
> ```reStructuredText
>   counting the nanoseconds since the starting time of the associated DRKey :ref:`Epoch<drkey-epoch>`.
>   (See :ref:`Appendix<spao-appendix>` for a more detailed explanation about the field interpretation).
>   The timestamp MAY be used to compute the absolute time (*AbsTime*) value, 
> ```

trailing space



_Suggestion:_
```reStructuredText
,
```
___
*[`doc/protocols/authenticator-option.rst` line 63 at r14](https://reviewable.io/reviews/scionproto/scion/4300#-NNpGZBX6iSlaEOyk-vy:-NNpGZBX6iSlaEOyk-vz:b-tn7gob) ([raw file](https://github.com/scionproto/scion/blob/636f2d98b3b6b3034ddcbaaacedddbfaa22f1125/doc/protocols/authenticator-option.rst#L63)):*
> ```reStructuredText
>   The timestamp MAY be used to compute the absolute time (*AbsTime*) value, 
>   which corresponds to the time when the packet was sent.
>   The section:ref:`Absolute time derivation<spao-timestamp>` describes the derivation of *AbsTime* and
> ```

This link is somehow broken, maybe it just needs a space between `section :ref:`



_Code quote:_
```reStructuredText
section:ref:`Absolute time derivation<spao-timestamp>`
```
___
*[`doc/protocols/authenticator-option.rst` line 75 at r14](https://reviewable.io/reviews/scionproto/scion/4300#-NNpHOzHBnjFCKqYzXUh:-NNpHOzHBnjFCKqYzXUi:b88ta8c) ([raw file](https://github.com/scionproto/scion/blob/636f2d98b3b6b3034ddcbaaacedddbfaa22f1125/doc/protocols/authenticator-option.rst#L75)):*
> ```reStructuredText
>   .. math::
>     (\mathrm{SRC\ ISD, SRC\ AS, SrcHostAddr, *AbsTime*})
>   
> ```

trailing spaces
___
*[`doc/protocols/authenticator-option.rst` line 175 at r14](https://reviewable.io/reviews/scionproto/scion/4300#-NNpLqQo4ypLVzjKvgRd:-NNpLqQo4ypLVzjKvgRe:b-cgrxir) ([raw file](https://github.com/scionproto/scion/blob/636f2d98b3b6b3034ddcbaaacedddbfaa22f1125/doc/protocols/authenticator-option.rst#L175)):*
> ```reStructuredText
>    e.g., if *AbsTime* is :math:`at_{i-1}` the key belonging to :math:`E_{i-1}`.
> 
> Note that `at_{i-1}` might, for instance be within the :ref:`Grace period<drkey-grace>`, i.e.,
> ```

I think we want the math here as well



_Suggestion:_
```reStructuredText
:math:`at_{i-1}`
```
___
*[`doc/protocols/authenticator-option.rst` line 176 at r14](https://reviewable.io/reviews/scionproto/scion/4300#-NNpLvXeDcFeNQQhCreb:-NNpLvXeDcFeNQQhCrec:undefined) ([raw file](https://github.com/scionproto/scion/blob/636f2d98b3b6b3034ddcbaaacedddbfaa22f1125/doc/protocols/authenticator-option.rst#L176)):*
> ```reStructuredText
> 
> Note that `at_{i-1}` might, for instance be within the :ref:`Grace period<drkey-grace>`, i.e.,
> overlapping at `E_{i}`. Nevertheless, due to [i] we can unambiguously distinguish it.
> ```





_Suggestion:_
```reStructuredText
:math:`E_{i}`
```
___
*[`doc/protocols/authenticator-option.rst` line 412 at r14](https://reviewable.io/reviews/scionproto/scion/4300#-NNpMgmxEfTnCIPWYxy6:-NNpMgmxEfTnCIPWYxy7:bn6g6rr) ([raw file](https://github.com/scionproto/scion/blob/636f2d98b3b6b3034ddcbaaacedddbfaa22f1125/doc/protocols/authenticator-option.rst#L412)):*
> ```reStructuredText
>   with granularity of 1 nanosecond, since:
> 
>   .. math:: 
> ```

trailing space



_Suggestion:_
```reStructuredText
. math::
```


<!-- Sent from Reviewable.io -->

2023-02-09 13:18 UTC, lukedirtwalker approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 4 unresolved discussions (waiting on @fstreun, @marcfrei, and @matzf)



<!-- Sent from Reviewable.io -->

2023-02-10 10:07 UTC, matzf reviewed
> Reviewed 1 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 4 unresolved discussions (waiting on @fstreun and @marcfrei)

___
*[`doc/protocols/authenticator-option.rst` line 71 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHKIP1BmFoF4maxbTx:-NNubAVQ1A_AcJLmsraP:b60fu3w) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L71)):*
> I think we considered to include the MAC into the duplicate detection instead of requiring uniqueness in the timestamp (or at least I did). I decided against it because this approach assumes that the MAC actually provides some uniqueness. However, identical packets create the same MAC if they use the same timestamp. Hence, protocols would not be allowed to send equal packets. Which I think is too strict.

This argument sounds somewhat backwards to me. Just to be clear, what I was considering including the MAC into duplicate detection _in addition to_ (not _instead of_) the timestamp. As the timestamp is included in the MAC, I suppose it would end up being  mostly the same thing though anyway.

So, yes, streams are not be able to send equal packets _with the same timestamp_. That's currently the case, as we use only the timestamp (`AbsTime`) for duplicate suppression. Thus the resolution of the timestamp is an upperbound for the packet throughput.

If we include the MAC to the duplicate suppression "tuple", streams can theoretically send 2^MAC-length packets with the same timestamp. Assuming that accidental MAC collisions are very unlikely (within one timestamp!), the practical maximum throughput becomes effectively unlimited (at least not limited by the duplicate suppression). The resolution of the timestamp is now only an upperbound for the throughput of identical packets.

The question was now, is it sensible to assume that we don't need to be able to send _identical_ packets at quite 1Gpps (per stream!), the rate that we've currently chosen the timestamp resolution for? I'd guess that it would be quite safe to limit this to, 1K identical packets per second.

> The timestamp would still also be useful to get rid of outdated packets and therefore to limit the size of the actual duplicate suppression filter in a later step of the pipeline. I'm not sure how granular the resolution of such a timestamp needs to be. If we would use a resolution of 1ms, e.g., we would "only" get about 9'000 years: 2**48 / 1000 / 60 / 60 / 24 /365 = 8925. But with the additional remark below at the beginning of section "Absolute time and DRKey derivation", I actually think that timestamps relative to the DRKeys epoch would be simple enough as long as we use them after they have been authenticated and thus been associated with the correct DRkey epoch.

Yes, for this part, millisecond accuracy seems amply accurate -- without fine clock synchronisation and unknown network latency, this valid timeframe will have to be at least many seconds long anyway.

Ok, so we keep the timestamp relative to the DRKey epoch.
Could we gain anything by making it shorter? If we choose milliseconds granularity (so, max 1K identical packets per second) , we could do with (a bit under) 32 bit. To fit it into 24bits, and thus allowing the whole SPAO to require one fewer lines, we'd still get about 15ms resolution (and thus about 60 identical packets per second, a bit low?).

What do you think?


<!-- Sent from Reviewable.io -->

2023-02-10 16:02 UTC, FR4NK-W reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 4 unresolved discussions (waiting on @fstreun, @marcfrei, and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 160 at r16](https://reviewable.io/reviews/scionproto/scion/4300#-NNvwpn-1v11UkXW3CdW:-NNvwpn-1v11UkXW3CdX:b-hvyy6v) ([raw file](https://github.com/scionproto/scion/blob/c347a94713b94d84975f7a037bab3862adb8573a/doc/protocols/authenticator-option.rst#L160)):*
> ```reStructuredText
> 
> 
> [i] The acceptance window is equal or smaller than the minumum DRKey epoch length.
> ```

minimum



_Code quote:_
```reStructuredText
 minumum
```


<!-- Sent from Reviewable.io -->

2023-02-13 14:49 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 4 unresolved discussions (waiting on @fstreun, @marcfrei, and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 71 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHKIP1BmFoF4maxbTx:-NOABGBIBo84KVGI-Bvd:b-c4te4l) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L71)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

> I think we considered to include the MAC into the duplicate detection instead of requiring uniqueness in the timestamp (or at least I did). I decided against it because this approach assumes that the MAC actually provides some uniqueness. However, identical packets create the same MAC if they use the same timestamp. Hence, protocols would not be allowed to send equal packets. Which I think is too strict.

This argument sounds somewhat backwards to me. Just to be clear, what I was considering including the MAC into duplicate detection _in addition to_ (not _instead of_) the timestamp. As the timestamp is included in the MAC, I suppose it would end up being  mostly the same thing though anyway.

So, yes, streams are not be able to send equal packets _with the same timestamp_. That's currently the case, as we use only the timestamp (`AbsTime`) for duplicate suppression. Thus the resolution of the timestamp is an upperbound for the packet throughput.

If we include the MAC to the duplicate suppression "tuple", streams can theoretically send 2^MAC-length packets with the same timestamp. Assuming that accidental MAC collisions are very unlikely (within one timestamp!), the practical maximum throughput becomes effectively unlimited (at least not limited by the duplicate suppression). The resolution of the timestamp is now only an upperbound for the throughput of identical packets.

The question was now, is it sensible to assume that we don't need to be able to send _identical_ packets at quite 1Gpps (per stream!), the rate that we've currently chosen the timestamp resolution for? I'd guess that it would be quite safe to limit this to, 1K identical packets per second.

> The timestamp would still also be useful to get rid of outdated packets and therefore to limit the size of the actual duplicate suppression filter in a later step of the pipeline. I'm not sure how granular the resolution of such a timestamp needs to be. If we would use a resolution of 1ms, e.g., we would "only" get about 9'000 years: 2**48 / 1000 / 60 / 60 / 24 /365 = 8925. But with the additional remark below at the beginning of section "Absolute time and DRKey derivation", I actually think that timestamps relative to the DRKeys epoch would be simple enough as long as we use them after they have been authenticated and thus been associated with the correct DRkey epoch.

Yes, for this part, millisecond accuracy seems amply accurate -- without fine clock synchronisation and unknown network latency, this valid timeframe will have to be at least many seconds long anyway.

Ok, so we keep the timestamp relative to the DRKey epoch.
Could we gain anything by making it shorter? If we choose milliseconds granularity (so, max 1K identical packets per second) , we could do with (a bit under) 32 bit. To fit it into 24bits, and thus allowing the whole SPAO to require one fewer lines, we'd still get about 15ms resolution (and thus about 60 identical packets per second, a bit low?).

What do you think?
</blockquote></details>

Indeed, we can focus on the data rate for identical packets rather than all packets by including the MAC. I believe it is hard to argue in favor of some exact "identical packet per second" (ipp)  estimation, for me, at least, it is hard to think about real use cases for upper-layer protocols requiring this metric. Gut feeling is that 1Kipps is (should be) okay for any current/future protocol, not that sure either for 60 ipps. What about using 4 bits for the algorithm ( I don't think we should support more than 16 protocols) and using 28 bits for the timestamp? That would yield something around this 1Kipps. If this is to stiff, I think 32-bit timestamp and reserving the rest might be okay.


<!-- Sent from Reviewable.io -->

2023-02-14 08:31 UTC, marcfrei requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 3 unresolved discussions (waiting on @fstreun, @JordiSubira, and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 69 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHHBilEFaedlvJRRsf:-NODzms8DuV44dM3YjN1:b-xv7p0j) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L69)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Indeed, it is to restrictive as we formulate it here. It should be unique per security association, i.e. per DRKey associated protocol. Even more lenient than that would be acceptable, based on the discussion below.
</blockquote></details>

+1 for "even more lenient" as discussed below. Otherwise, two independent processes on the same source host communicating concurrently via the same DRKey protocol with the same destination host would still need to somehow coordinate with each other to avoid running into duplicate suppression.
___
*[`doc/protocols/authenticator-option.rst` line 71 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHKIP1BmFoF4maxbTx:-NODyj6D1z-eG3en_Kwy:b-q5b0k) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L71)):*
> Gut feeling is that 1Kipps is (should be) okay for any current/future protocol, not that sure either for 60 ipps.
+1


<!-- Sent from Reviewable.io -->

2023-02-21 14:21 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @fstreun, @lukedirtwalker, @marcfrei, and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 69 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHHBilEFaedlvJRRsf:-NOoLGFj2UKxpXoR2YDn:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L69)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

+1 for "even more lenient" as discussed below. Otherwise, two independent processes on the same source host communicating concurrently via the same DRKey protocol with the same destination host would still need to somehow coordinate with each other to avoid running into duplicate suppression.
</blockquote></details>

Done.
___
*[`doc/protocols/authenticator-option.rst` line 71 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHKIP1BmFoF4maxbTx:-NOoIY3g1TnjVbD59ctp:bivilsq) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L71)):*
> about using 4 bits for the algorithm ( I don't think we should support more than 16 protocols) and using 28 bits for the timestamp? That would yield something around this 1Kipps. If this is to stiff, I think 32-bit timestamp and reserving the rest might be okay.
Ideas about this proposal?
___
*[`doc/protocols/authenticator-option.rst` line 147 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHizIJ5t2aTNmnbmzN:-NOoIfA4AUEk5srRGq9g:bs4evcl) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L147)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

If we try first to authenticate the packet, in the worst case we will try out with three different keys (assuming minimum epoch lengths and maximum accepting window length). If an attacker sends a packet which is not correctly authenticated we will compute the MAC three times. In the case that we select the key based on the method described above, we will only try one key, even if the packet has forced to be within the acceptance window.

In https://www.rfc-editor.org/rfc/rfc4302#section-3.4.3 The sequence number is unique per SA, it then verifies that the SN falls into the sliding window and after that it checks the duplication suppression mechanism and finally carries out the Integrity Check Validation. In our case, the procedure described is our method to find out the SA (i.e. what DRKey are we using for that protocol, one out of 3, at most, possible keys). Of course we can do it differently. 
</blockquote></details>

I added explicitly that this is a proposed implementation method, in practice can be done differently.


<!-- Sent from Reviewable.io -->

2023-02-22 06:02 UTC, lukedirtwalker approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 2 unresolved discussions (waiting on @fstreun, @marcfrei, and @matzf)



<!-- Sent from Reviewable.io -->

2023-02-22 17:57 UTC, fstreun reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 3 unresolved discussions (waiting on @JordiSubira, @marcfrei, and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 71 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHKIP1BmFoF4maxbTx:-NOuDwQ_E2W-kkMRhfmb:b-y67av3) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L71)):*
> [...] I was considering including the MAC into duplicate detection in addition to (not instead of) the timestamp.

I misunderstood you on that one. Including the MAC into duplicate detection is an option.
If 1 Kipps is a reasonable limit, I cannot tell. Nevertheless, it seems pretty restrictive to me.
___
*[`doc/protocols/authenticator-option.rst` line 405 at r17](https://reviewable.io/reviews/scionproto/scion/4300#-NOuGCgA9qKCOTuyDvSf:-NOuGCgA9qKCOTuyDvSg:undefined) ([raw file](https://github.com/scionproto/scion/blob/d8e5dd9a309d83a7129d0131f76db21d9782b3a2/doc/protocols/authenticator-option.rst#L405)):*
> ```reStructuredText
> 
> - this does not appear to work with less than 3 rows. We use the available
>   room to make a 48-bit timestamp / sequence number field and leave one
> ```





_Suggestion:_
```reStructuredText
Timestamp / Sequence Number
```


<!-- Sent from Reviewable.io -->

2023-04-14 11:51 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 3 unresolved discussions (waiting on @fstreun, @marcfrei, and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 71 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHKIP1BmFoF4maxbTx:-NSzaKyc3dfPzbr6pI-F:b-bpyycs) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L71)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

> [...] I was considering including the MAC into duplicate detection in addition to (not instead of) the timestamp.

I misunderstood you on that one. Including the MAC into duplicate detection is an option.
If 1 Kipps is a reasonable limit, I cannot tell. Nevertheless, it seems pretty restrictive to me.
</blockquote></details>

Any more feedback regarding the upper-bound on the "identical packet rate". Also, any feedback about using less bits for the algorithm field to make the TS at least 28 bits long?


<!-- Sent from Reviewable.io -->

2023-04-25 06:04 UTC, lukedirtwalker approved these changes
> Reviewed 1 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira, @marcfrei, and @matzf)



<!-- Sent from Reviewable.io -->

2023-05-19 07:49 UTC, lukedirtwalker approved these changes
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira, @marcfrei, and @matzf)



<!-- Sent from Reviewable.io -->

2023-05-19 07:49 UTC, lukedirtwalker approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira, @marcfrei, and @matzf)



<!-- Sent from Reviewable.io -->

2023-05-19 08:05 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 2 unresolved discussions (waiting on @fstreun, @marcfrei, and @matzf)

___
*[`doc/protocols/authenticator-option.rst` line 71 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHKIP1BmFoF4maxbTx:-NVmweYQ8UuRsfobPZhd:b-wqlkmi) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L71)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Any more feedback regarding the upper-bound on the "identical packet rate". Also, any feedback about using less bits for the algorithm field to make the TS at least 28 bits long?
</blockquote></details>

@marcfrei @matzf Any more feedback regarding how many bits we decide to use for the `Timestamp / Sequence Number` field? The proposed options are the following:
- 32 bits -> ~16.5 Kipps
- 28 bits -> ~ 1Kipps
- 24 bits -> ~ 66 ipps.

Since it seems that no one has a strong opinion, I would go for 32 bits which gives more room and looks more standard (e.g. Sequence Number in rfc4303). The downside is that we end up having some reserved bits (24 bit apparently subject to alignment requirements).
___
*[`doc/protocols/authenticator-option.rst` line 405 at r17](https://reviewable.io/reviews/scionproto/scion/4300#-NOuGCgA9qKCOTuyDvSf:-NVmwa7Z3A8Lo5isSULp:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d8e5dd9a309d83a7129d0131f76db21d9782b3a2/doc/protocols/authenticator-option.rst#L405)):*
> ```reStructuredText
> 
> - this does not appear to work with less than 3 rows. We use the available
>   room to make a 48-bit timestamp / sequence number field and leave one
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-05-22 11:37 UTC, matzf approved these changes
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 2 unresolved discussions (waiting on @fstreun and @marcfrei)

___
*[`doc/protocols/authenticator-option.rst` line 71 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHKIP1BmFoF4maxbTx:-NW2CBUv6j35JWPk_uoE:bliqn2l) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L71)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

@marcfrei @matzf Any more feedback regarding how many bits we decide to use for the `Timestamp / Sequence Number` field? The proposed options are the following:
- 32 bits -> ~16.5 Kipps
- 28 bits -> ~ 1Kipps
- 24 bits -> ~ 66 ipps.

Since it seems that no one has a strong opinion, I would go for 32 bits which gives more room and looks more standard (e.g. Sequence Number in rfc4303). The downside is that we end up having some reserved bits (24 bit apparently subject to alignment requirements).
</blockquote></details>

My gut feeling opinion on these options:
- 24 bits: too short / 66 ipps could bite us
- 28 bits: the 1Kipps looks ok, but the restriction to 16 algorithms seems very low and could bite us
- 32 bits: works, but somewhat pointless to give up so many reserved bits.

So, ultimately none of these options seems overly convincing and I think I'd now vote to keep it as it's currently proposed in this PR, that is 48 bits with somewhat overkill nanosecond granularity.

To come back to the start of this discussion, we should still append the MAC to the duplicate suppression tuple.


<!-- Sent from Reviewable.io -->

2023-05-22 14:46 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 4 unresolved discussions (waiting on @fstreun and @marcfrei)

___
*[`doc/protocols/authenticator-option.rst` line 71 at r18](https://reviewable.io/reviews/scionproto/scion/4300#-NW2ALbe0kqsHkIF_brX:-NW2unRiBBJab-Tk2TCO:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a15b7cc9c10eca5dca92364953523cf3665a3afa/doc/protocols/authenticator-option.rst#L71)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

"SHOULD drop identical packets"?
</blockquote></details>

Done.
___
*[`doc/protocols/authenticator-option.rst` line 170 at r18](https://reviewable.io/reviews/scionproto/scion/4300#-NW2BgkP2Mj_dk3OiAtl:-NW2uu5k6CTbxqSHhuIw:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a15b7cc9c10eca5dca92364953523cf3665a3afa/doc/protocols/authenticator-option.rst#L170)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

"RelTime" since it's also "AbsTime"?
</blockquote></details>

Done.
___
*[`doc/protocols/authenticator-option.rst` line 399 at r18](https://reviewable.io/reviews/scionproto/scion/4300#-NW2DRcnAd4wbh7aCiXo:-NW2uzPr3GiVg-f2975N:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a15b7cc9c10eca5dca92364953523cf3665a3afa/doc/protocols/authenticator-option.rst#L399)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

LightningFilter
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-22 15:20 UTC, marcfrei approved these changes
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 1 unresolved discussion (waiting on @fstreun)



<!-- Sent from Reviewable.io -->

2023-05-22 18:13 UTC, fstreun reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

___
*[`doc/protocols/authenticator-option.rst` line 71 at r12](https://reviewable.io/reviews/scionproto/scion/4300#-NNHKIP1BmFoF4maxbTx:-NW3_zWdBK8ErCAHdaeC:b-kacdhh) ([raw file](https://github.com/scionproto/scion/blob/1eade1203e4e62af258f0d76a35ed59b627a57fe/doc/protocols/authenticator-option.rst#L71)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

> So, ultimately none of these options seems overly convincing and I think I'd now vote to keep it as it's currently proposed in this PR, that is 48 bits with somewhat overkill nanosecond granularity.
> 
> To come back to the start of this discussion, we should still append the MAC to the duplicate suppression tuple.

+1
</blockquote></details>

+1

So, timestamp shoud be unique? (Or is it if we use the same timestamp?)
For duplicate suppression, only using the MAC sould then be sufficient and we can suggest this approach. However, we don't have to specify that and can leave it up to the application how it detects duplicates.


<!-- Sent from Reviewable.io -->

2023-05-23 16:03 UTC, fstreun reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300#-:-NW8LNlcEIhpFHzWcIRB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2023-05-24 11:45 UTC, lukedirtwalker requested changes
> Reviewed 1 of 1 files at r20, 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 4 unresolved discussions (waiting on @JordiSubira)

___
*[`doc/protocols/authenticator-option.rst` line 76 at r21](https://reviewable.io/reviews/scionproto/scion/4300#-NWCYnCM6hOxISKC_sEV:-NWCYnCM6hOxISKC_sEW:bn6g6rr) ([raw file](https://github.com/scionproto/scion/blob/a9ad049c4e3b72770873374c82a9cd1bf4d63d52/doc/protocols/authenticator-option.rst#L76)):*
> ```reStructuredText
>     (\mathrm{SRC\ ISD, SRC\ AS, SrcHostAddr, Authenticator})
> 
> .. note:: 
> ```

trailing space
___
*[`doc/protocols/authenticator-option.rst` line 77 at r21](https://reviewable.io/reviews/scionproto/scion/4300#-NWCYvAK0O2k9NbVuzZt:-NWCYvAK0O2k9NbVuzZu:undefined) ([raw file](https://github.com/scionproto/scion/blob/a9ad049c4e3b72770873374c82a9cd1bf4d63d52/doc/protocols/authenticator-option.rst#L77)):*
> ```reStructuredText
> 
> .. note:: 
>   In other words, the duplicate suppression would happend within the
> ```





_Suggestion:_
```reStructuredText
 happen
```
___
*[`doc/protocols/authenticator-option.rst` line 80 at r21](https://reviewable.io/reviews/scionproto/scion/4300#-NWCZ1nZ6-BXY4rL7z11:-NWCZ1nZ6-BXY4rL7z12:bn6g6rr) ([raw file](https://github.com/scionproto/scion/blob/a9ad049c4e3b72770873374c82a9cd1bf4d63d52/doc/protocols/authenticator-option.rst#L80)):*
> ```reStructuredText
>   acceptance windows considering identical values for the Authenticator field, which is
>   computed based on packet contents, such as the Timestamp (used to derived the *AbsTime*)
>   and the upper layer payload 
> ```

trailing space
___
*[`doc/protocols/authenticator-option.rst` line 189 at r21](https://reviewable.io/reviews/scionproto/scion/4300#-NWCZ6341fblTfbX9gIC:-NWCZ6341fblTfbX9gID:b-ok1bmd) ([raw file](https://github.com/scionproto/scion/blob/a9ad049c4e3b72770873374c82a9cd1bf4d63d52/doc/protocols/authenticator-option.rst#L189)):*
> ```reStructuredText
> 
> 
> .. _authenticated-date:
> ```

Why not data?


<!-- Sent from Reviewable.io -->

2023-05-24 12:00 UTC, lukedirtwalker reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @fstreun)



<!-- Sent from Reviewable.io -->

2023-05-24 12:01 UTC, lukedirtwalker approved these changes
> Reviewed 1 of 1 files at r22.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2023-05-25 13:28 UTC, matzf commented
Going forward, we're **likely** going accept this **proposal**. The final comment period starts now, and unless there are objections during this period, the proposal will be marked as accepted.

This documentation PR serves as impromptu design document. Once the proposal is accepted, we can accept a PR with the implementation. Once the implementation is done, this PR with the updated documentation will be merged immediately.

2023-06-05 07:20 UTC, matzf commented
No objections were raised during the final comment period, which means that this proposal is now **accepted**.

This documentation PR remains open as an impromptu design document. Once the implementation is done, this PR will be merged.

2023-06-05 09:05 UTC, fstreun reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2023-09-22 07:39 UTC, matzf reviewed
> Reviewed 1 of 1 files at r21, 3 of 3 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: all files reviewed, 1 unresolved discussion (waiting on @JordiSubira)

___
*[`doc/manuals/control.rst` line 26 at r23](https://reviewable.io/reviews/scionproto/scion/4300#-NevmOvG9rgSJhIvOT37:-NevmOvG9rgSJhIvOT38:b-rvmbf4) ([raw file](https://github.com/scionproto/scion/blob/6de2f71a3b97b697ca6ed86585f4f92faccaf794/doc/manuals/control.rst#L26)):*
> ```reStructuredText
> 
>    Defines the global DRKey :ref:`Epoch<drkey-epoch>` duration that the Control Service
>    assumes.
> ```

Note: this file needs to be updated from master; this information is already there. 
___
*[`doc/protocols/authenticator-option.rst` line 76 at r23](https://reviewable.io/reviews/scionproto/scion/4300#-NevoYV08ybKQhHPceBC:-NevoYV14wq7_0a6FOEM:bmgfokj) ([raw file](https://github.com/scionproto/scion/blob/6de2f71a3b97b697ca6ed86585f4f92faccaf794/doc/protocols/authenticator-option.rst#L76)):*
> ```reStructuredText
>     (\mathrm{SRC\ ISD, SRC\ AS, SrcHostAddr, Authenticator})
> 
> .. note::
> ```

Lacking indention for the note block? (Note: see preview https://scion--4300.org.readthedocs.build/en/4300/protocols/authenticator-option.html#format-of-the-authenticator-option)


<!-- Sent from Reviewable.io -->

2023-09-26 14:23 UTC, fstreun reviewed
> Reviewed 2 of 4 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-09-26 16:23 UTC, matzf approved these changes
> Reviewed 4 of 4 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4300)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2023-09-26 16:41 UTC, merged