lint: fix errcheck violations
scionproto/scion pull request #4310
Opened 2023-01-30 08:54 UTC by matzf

Remove (most) golangci-lint exceptions for the errcheck linter. This linter is generally very helpful and it seems better not to give blanket exceptions for violations. It's rarely necessary to use nolint to silence specific false positives, as it's usually enough to explicitly ignore errors by assigning to a blank identifier, which seems seems helpful for readers of the code.

Fix errcheck violations:
- Explicitly ignore or log errors where this seems appropriate
  - In http.Handler code, ignore errors when writing the response body. Use rw.Write where possible to make it as clear as possible that the Write is the only remaining possibility for errors. Some of the diagnostics pages would require more restructuring to handle errors properly; in some cases, errors are ignored by using fmt.Fprint (for which errcheck ignores errors), instead of Write.
- Assert or panic on errors in tests
- Remove some unused code snippets with violations (TestMain, log/testlog.SetupGlobals)
- Restructure control/beacon.ParsePolicyYaml so initDefaults does not return an error (and btw, use correct input file in test)
- Handle SetDeadline errors in sock/reliable/reconnect
- Handle UnderlayPacket.DecodeFromBytes error in sock/reliable.Conn

2023-01-30 10:42 UTC, marcfrei approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 76 of 76 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310#-:-NN1GDHo3zC0nhH6pD0H:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @lukedirtwalker, @matzf, and @oncilla)

___
*[`control/beacon/policy.go` line 211 at r1](https://reviewable.io/reviews/scionproto/scion/4310#-NN1Cqq6EFjlkoov1lOj:-NN1Ckrg8R7-z3pUVIs1:bkme3yh) ([raw file](https://github.com/scionproto/scion/blob/535389b5cf7c417ee54b9f4bc90dbdc703fc935b/control/beacon/policy.go#L211)):*
> ```Go
> 	if p.Type == "" {
> 		p.Type = t
> 	}
> ```

panic on `else if p.Type != t {`?
___
*[`pkg/log/log.go` line 143 at r1](https://reviewable.io/reviews/scionproto/scion/4310#-NN1EOe1BXBFvckv6jJy:-NN1EGCP0MAmcuKH12-k:ba0opnk) ([raw file](https://github.com/scionproto/scion/blob/535389b5cf7c417ee54b9f4bc90dbdc703fc935b/pkg/log/log.go#L143)):*
> ```Go
> 	if err := zap.L().Sync(); err != nil {
> 		zap.L().Error("flushing log", zap.Error(err))
> 		_ = zap.L().Sync() // retry...
> ```

Really necessary?
___
*[`pkg/sock/reliable/reliable.go` line 223 at r1](https://reviewable.io/reviews/scionproto/scion/4310#-NN1F69-AeYRX5JXGaoW:-NN1F69-AeYRX5JXGaoX:b58flxs) ([raw file](https://github.com/scionproto/scion/blob/535389b5cf7c417ee54b9f4bc90dbdc703fc935b/pkg/sock/reliable/reliable.go#L223)):*
> ```Go
> 		// Disable deadline to not affect future I/O
> 		_ = conn.SetDeadline(time.Time{})
> 		return conn, registrationReturn.port, err
> ```

`err == nil` here, isn't it? I would probably just return `nil`.
___
*[`private/service/statuspages.go` line 135 at r1](https://reviewable.io/reviews/scionproto/scion/4310#-NN1Ff-r6htixUKu5II_:-NN1Ff-r6htixUKu5IIa:bnkgtgg) ([raw file](https://github.com/scionproto/scion/blob/535389b5cf7c417ee54b9f4bc90dbdc703fc935b/private/service/statuspages.go#L135)):*
> ```Go
> 		if err != nil {
> 			w.WriteHeader(http.StatusInternalServerError)
> 			fmt.Fprint(w, err.Error())
> ```

Couldn't this leak internal details? Maybe just return an error message instead.


<!-- Sent from Reviewable.io -->

2023-01-30 10:44 UTC, marcfrei approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310)* status: all files reviewed, 5 unresolved discussions (waiting on @lukedirtwalker, @matzf, and @oncilla)

___
*[`pkg/log/log.go` line 143 at r1](https://reviewable.io/reviews/scionproto/scion/4310#-NN1GYat0TtzWlYqMdnN:-NN1GYat0TtzWlYqMdnO:be57bm9) ([raw file](https://github.com/scionproto/scion/blob/535389b5cf7c417ee54b9f4bc90dbdc703fc935b/pkg/log/log.go#L143)):*
> ```Go
> 	if err := zap.L().Sync(); err != nil {
> 		zap.L().Error("flushing log", zap.Error(err))
> 		_ = zap.L().Sync() // retry...
> ```

I.e.: "is the retry really necessary?"


<!-- Sent from Reviewable.io -->

2023-01-30 11:25 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310)* status: 74 of 76 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker, @marcfrei, and @oncilla)

___
*[`control/beacon/policy.go` line 211 at r1](https://reviewable.io/reviews/scionproto/scion/4310#-NN1Cqq6EFjlkoov1lOj:-NN1L7AjETrc6v2e-Vw2:bew6yit) ([raw file](https://github.com/scionproto/scion/blob/535389b5cf7c417ee54b9f4bc90dbdc703fc935b/control/beacon/policy.go#L211)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

panic on `else if p.Type != t {`?
</blockquote></details>

No, I think the `Validation` is supposed to do the checking.
___
*[`pkg/log/log.go` line 143 at r1](https://reviewable.io/reviews/scionproto/scion/4310#-NN1GYat0TtzWlYqMdnN:-NN1LZYQEBmj5NJZctNL:bsi454c) ([raw file](https://github.com/scionproto/scion/blob/535389b5cf7c417ee54b9f4bc90dbdc703fc935b/pkg/log/log.go#L143)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

I.e.: "is the retry really necessary?"
</blockquote></details>

No idea, to be honest. I just thought it could make sense to attempt logging this error, but, without flushing, the entry will probably never show up anywhere, so maybe just try flushing, again.
I fully admit that this seems rather arbitrary... I don't mind removing it and silently ignore the Sync error.
___
*[`pkg/sock/reliable/reliable.go` line 223 at r1](https://reviewable.io/reviews/scionproto/scion/4310#-NN1F69-AeYRX5JXGaoW:-NN1PFgJ682vn8eLvm79:b-eey1rd) ([raw file](https://github.com/scionproto/scion/blob/535389b5cf7c417ee54b9f4bc90dbdc703fc935b/pkg/sock/reliable/reliable.go#L223)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

`err == nil` here, isn't it? I would probably just return `nil`.
</blockquote></details>

Good catch, phew. I meant to return the error from `SetDeadline`.
___
*[`private/service/statuspages.go` line 135 at r1](https://reviewable.io/reviews/scionproto/scion/4310#-NN1Ff-r6htixUKu5II_:-NN1Ohuu0SZhITD7DTeb:bvj1tt2) ([raw file](https://github.com/scionproto/scion/blob/535389b5cf7c417ee54b9f4bc90dbdc703fc935b/private/service/statuspages.go#L135)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Couldn't this leak internal details? Maybe just return an error message instead.
</blockquote></details>

Done (and changed to use the more concise `http.Error`). 
FWIW, I believe these status pages are meant to be fully internal and thus not very sensitive.


<!-- Sent from Reviewable.io -->

2023-01-30 12:14 UTC, marcfrei approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker and @oncilla)



<!-- Sent from Reviewable.io -->

2023-01-31 08:52 UTC, lukedirtwalker requested changes
> Reviewed 74 of 76 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310)* status: all files reviewed, 11 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`control/beacon/policy.go` line 221 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN26_KXABJrSCsPtWgX:-NN26_KXABJrSCsPtWgY:b7p7nmw) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/control/beacon/policy.go#L221)):*
> ```Go
> 	}
> 	if p.Type != "" && p.Type != t {
> 		return nil, serrors.New("Specified policy type does not match",
> ```

usually error messages should not start with capital letter.
___
*[`control/cmd/control/main.go` line 511 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN26s27Cr1ODA1STg3V:-NN26s27Cr1ODA1STg3W:b-hoenz7) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/control/cmd/control/main.go#L511)):*
> ```Go
> 	}
> 
> 	// Frequently regenerate signers to catch problems, and update the metrics.
> ```

given the comment, should we log in case it fails? or we don't care because we have metrics that tell us things are about to expire?
___
*[`pkg/experimental/epic/epic_test.go` line 388 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN27YWu1j4RS5Ci-Qg4:-NN27YWu1j4RS5Ci-Qg5:bw6iej) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/pkg/experimental/epic/epic_test.go#L388)):*
> ```Go
> 	ip4Addr := &net.IPAddr{IP: net.ParseIP("10.0.0.100")}
> 	if err := spkt.SetSrcAddr(ip4Addr); err != nil {
> 		panic(err)
> ```

if it isn't too much work I would prefer an `require.NoError(t, err)` and mark `createScionCmnAddrHdr` as a `t.Helper()`. It's nicer to work with if it would ever fail.
___
*[`pkg/experimental/hiddenpath/store_test.go` line 164 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN27odq7BJb3FHWjg22:-NN27odq7BJb3FHWjg23:b-7l6xnm) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/pkg/experimental/hiddenpath/store_test.go#L164)):*
> ```Go
> 	ps, _ := seg.CreateSegment(time.Now(), 1337)
> 	if err := ps.AddASEntry(context.Background(), asEntry, graph.NewSigner()); err != nil {
> 		panic(err)
> ```

ditto if not too much work, preferably use `require.NoError`
___
*[`pkg/experimental/hiddenpath/grpc/registerer_test.go` line 130 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN281Q98-m_cPf7DG3G:-NN281Q98-m_cPf7DG3H:b7fqsht) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/pkg/experimental/hiddenpath/grpc/registerer_test.go#L130)):*
> ```Go
> 	ps, _ := seg.CreateSegment(time.Now(), 1337)
> 	if err := ps.AddASEntry(context.Background(), asEntry, graph.NewSigner()); err != nil {
> 		panic(err)
> ```

ditto `require.NoError` if not too much work
___
*[`private/app/appnet/infraenv.go` line 281 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN5zaasChDjvqHKzT8Q:-NN5zaasChDjvqHKzT8R:bhi8r3z) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/private/app/appnet/infraenv.go#L281)):*
> ```Go
> 				return
> 			default:
> 				_, _ = conn.Read(buf)
> ```

why can we ignore the error here?
___
*[`private/config/sample.go` line 42 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN5zoKWE2tdEsI1Bsce:-NN5zoKWE2tdEsI1Bscf:bhi8r3z) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/private/config/sample.go#L42)):*
> ```Go
> 		}
> 		sampler.Sample(&buf, path, ctx)
> 		_, _ = io.Copy(dst, &buf)
> ```

why can we ignore the error here?
___
*[`private/revcache/revcachetest/revcachetest.go` line 271 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN6-4eHBbJugckBG_9z:-NN6-4eHBbJugckBG_A-:b-n5of1i) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/private/revcache/revcachetest/revcachetest.go#L271)):*
> ```Go
> 	revCache.InsertExpired(t, ctx, revNew)
> 	rev110_19 := defaultRevInfo(ia110, ifId19)
> 	_, _ = revCache.Insert(ctx, rev110_19)
> ```

why not `assert.NoError` here?
___
*[`private/revcache/revcachetest/revcachetest.go` line 289 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN6-8Fr2USinBa9VdB2:-NN6-8Fr2USinBa9VdB3:b-n5of1i) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/private/revcache/revcachetest/revcachetest.go#L289)):*
> ```Go
> 	SoMsg("DeleteExpired on empty should delete 0", del, ShouldEqual, 0)
> 	rev110_19 := defaultRevInfo(ia110, ifId19)
> 	_, _ = revCache.Insert(ctx, rev110_19)
> ```

why not `assert.NoError` here?
___
*[`private/svc/internal/ctxconn/ctxconn.go` line 44 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN6-Izl0TzW04C2-O9Y:-NN6-Izm46ynMKeS33ok:bmjyfpx) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/private/svc/internal/ctxconn/ctxconn.go#L44)):*
> ```Go
> func CloseConnOnDone(ctx context.Context, conn DeadlineCloser) CancelFunc {
> 	if deadline, ok := ctx.Deadline(); ok {
> 		_ = conn.SetDeadline(deadline)
> ```

please add a comment why we ignore the error
___
*[`router/bfd/main_test.go` line 24 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN6-gyu0ClQd0Yhlr1S:-NN6-gyv8KeylEB0KbzG:bt2gwu) ([raw file](https://github.com/scionproto/scion/blob/f3b508f14f8c38c9cc1c50f74195b6fba9fff16d/router/bfd/main_test.go#L24)):*
> ```Go
> )
> 
> func TestMain(m *testing.M) {
> ```

so we don't have logging anymore now?


<!-- Sent from Reviewable.io -->

2023-02-02 12:59 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310)* status: 69 of 76 files reviewed, 11 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, and @oncilla)

___
*[`control/beacon/policy.go` line 221 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN26_KXABJrSCsPtWgX:-NNGV7oL-JsCEHdVIl5a:b-q5txow) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/control/beacon/policy.go#L221)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

usually error messages should not start with capital letter.
</blockquote></details>

Done. Not changed the rest of the strings in this file though to avoid more churn.
___
*[`control/cmd/control/main.go` line 511 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN26s27Cr1ODA1STg3V:-NNGVZMO7Jc8SZjpCz7S:b-rq8awl) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/control/cmd/control/main.go#L511)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

given the comment, should we log in case it fails? or we don't care because we have metrics that tell us things are about to expire?
</blockquote></details>

Added a log entry analogous to other periodic health checks.
The wording ("signer" and "renewal signer") matches the names of the corresponding metrics.
___
*[`pkg/experimental/epic/epic_test.go` line 388 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN27YWu1j4RS5Ci-Qg4:-NNGd4E5ESBWdIprJzoh:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/pkg/experimental/epic/epic_test.go#L388)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

if it isn't too much work I would prefer an `require.NoError(t, err)` and mark `createScionCmnAddrHdr` as a `t.Helper()`. It's nicer to work with if it would ever fail.
</blockquote></details>

Done.
___
*[`pkg/experimental/hiddenpath/store_test.go` line 164 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN27odq7BJb3FHWjg22:-NNGd_ZT6RgkpQcaDZL-:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/pkg/experimental/hiddenpath/store_test.go#L164)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

ditto if not too much work, preferably use `require.NoError`
</blockquote></details>

Done.
___
*[`pkg/experimental/hiddenpath/grpc/registerer_test.go` line 130 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN281Q98-m_cPf7DG3G:-NNGd_r15tocUGWoVwzb:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/pkg/experimental/hiddenpath/grpc/registerer_test.go#L130)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

ditto `require.NoError` if not too much work
</blockquote></details>

Done.
___
*[`private/app/appnet/infraenv.go` line 281 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN5zaasChDjvqHKzT8Q:-NNH37ByA5eBe85mzpos:bj8ds5q) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/private/app/appnet/infraenv.go#L281)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

why can we ignore the error here?
</blockquote></details>

Done. Added a comment and log / handle some of the errors.
___
*[`private/config/sample.go` line 42 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN5zoKWE2tdEsI1Bsce:-NNH4eCV7OlOSsRYt_qr:b-4gzlon) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/private/config/sample.go#L42)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

why can we ignore the error here?
</blockquote></details>

Good catch. I think I just didn't see any way to handle the error without changing all the interfaces. Now I saw that this it's explicitly documented that Sampler can panic on errors; already, `WriteSample` (indirectly) calls `WriteString` which panics on error. I've changed it to panic on errors in the `io.Copy` call too (and added a note about this to the function doc).
___
*[`private/revcache/revcachetest/revcachetest.go` line 271 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN6-4eHBbJugckBG_9z:-NNH7UR12yOnxd-HPZ7a:bkwt150) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/private/revcache/revcachetest/revcachetest.go#L271)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

why not `assert.NoError` here?
</blockquote></details>

Done.  Added it as `assert.NoError` even though this sticks out like a sore thumb from the goconvey tests... Hope this is ok.
___
*[`private/revcache/revcachetest/revcachetest.go` line 289 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN6-8Fr2USinBa9VdB2:-NNH7lf9E3uAPzE7qmJu:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/private/revcache/revcachetest/revcachetest.go#L289)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

why not `assert.NoError` here?
</blockquote></details>

Done.
___
*[`private/svc/internal/ctxconn/ctxconn.go` line 44 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN6-Izl0TzW04C2-O9Y:-NNHB1A9Cc-BhNzgi_Kj:bs7wumb) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/private/svc/internal/ctxconn/ctxconn.go#L44)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

please add a comment why we ignore the error
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-02 13:09 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310)* status: 67 of 76 files reviewed, 11 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, and @oncilla)

___
*[`private/svc/internal/ctxconn/ctxconn.go` line 57 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NNHCAkK7B0MIl5DxJTX:-NNHCAkK7B0MIl5DxJTY:bno2hn5) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/private/svc/internal/ctxconn/ctxconn.go#L57)):*
> ```Go
> 		case <-cancelSignal:
> 			// shut down goroutine, free up resources
> 			return
> ```

Unrelated: this seems to be missing  `conn.Close` here?


<!-- Sent from Reviewable.io -->

2023-02-02 13:36 UTC, lukedirtwalker reviewed
> Reviewed 7 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf and @oncilla)

___
*[`private/svc/internal/ctxconn/ctxconn.go` line 57 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NNHCAkK7B0MIl5DxJTX:-NNHKiqy-ZvSzWUB5OqH:b-zagnfo) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/private/svc/internal/ctxconn/ctxconn.go#L57)):*
Hm from the documentation of the function I would not say so :/ 

> // Call the returned cancellation function to free up resources. Calling this
// function does not guarantee that the connection has been closed.


<!-- Sent from Reviewable.io -->

2023-02-02 15:12 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)

___
*[`private/svc/internal/ctxconn/ctxconn.go` line 57 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NNHCAkK7B0MIl5DxJTX:-NNHWbLG3UswtdSzWMbI:bw1njgy) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/private/svc/internal/ctxconn/ctxconn.go#L57)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Hm from the documentation of the function I would not say so :/ 

> // Call the returned cancellation function to free up resources. Calling this
// function does not guarantee that the connection has been closed.
</blockquote></details>

Ah, I misread this. But then there is a bug in the (only) caller of this function, in svc/resolver.go: this never seems to close the conn (and some printf-debugging seems to suggest that indeed the conn is never closed).


<!-- Sent from Reviewable.io -->

2023-02-02 15:47 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @oncilla)

___
*[`router/bfd/main_test.go` line 24 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN6-gyu0ClQd0Yhlr1S:-NNHhPG3ACfsH0Zh-2Y1:bflim1p) ([raw file](https://github.com/scionproto/scion/blob/f3b508f14f8c38c9cc1c50f74195b6fba9fff16d/router/bfd/main_test.go#L24)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

so we don't have logging anymore now?
</blockquote></details>

This is only for this specific package, or am I misunderstanding something? 
It seems that all the logging for the session tests is already done with more specific loggers (latest version, injected into the context: 64b403a1886caa56fd42d7d6c89dcaf6deb54765). I've just checked, only the `TestMetrics` test seems to have logged anything with the default global logger setup in this TestMain, and this is not the test that had been hard to debug.


<!-- Sent from Reviewable.io -->

2023-02-03 08:45 UTC, lukedirtwalker approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oncilla)

___
*[`private/svc/internal/ctxconn/ctxconn.go` line 57 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NNHCAkK7B0MIl5DxJTX:-NNLRlpZ946Qa2kC6teo:b-qkfakw) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/private/svc/internal/ctxconn/ctxconn.go#L57)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Ah, I misread this. But then there is a bug in the (only) caller of this function, in svc/resolver.go: this never seems to close the conn (and some printf-debugging seems to suggest that indeed the conn is never closed).
</blockquote></details>

then let's fix it and close the conn :) 
___
*[`router/bfd/main_test.go` line 24 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NN6-gyu0ClQd0Yhlr1S:-NNLRweBEar2rYng8Ghz:b32w0x) ([raw file](https://github.com/scionproto/scion/blob/f3b508f14f8c38c9cc1c50f74195b6fba9fff16d/router/bfd/main_test.go#L24)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This is only for this specific package, or am I misunderstanding something? 
It seems that all the logging for the session tests is already done with more specific loggers (latest version, injected into the context: 64b403a1886caa56fd42d7d6c89dcaf6deb54765). I've just checked, only the `TestMetrics` test seems to have logged anything with the default global logger setup in this TestMain, and this is not the test that had been hard to debug.

</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2023-02-03 15:13 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310)* status: 78 of 79 files reviewed, all discussions resolved (waiting on @lukedirtwalker, @marcfrei, and @oncilla)

___
*[`pkg/log/log.go` line 143 at r1](https://reviewable.io/reviews/scionproto/scion/4310#-NN1GYat0TtzWlYqMdnN:-NNMpN52-OdXOadMlBCu:bkwslan) ([raw file](https://github.com/scionproto/scion/blob/535389b5cf7c417ee54b9f4bc90dbdc703fc935b/pkg/log/log.go#L143)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

No idea, to be honest. I just thought it could make sense to attempt logging this error, but, without flushing, the entry will probably never show up anywhere, so maybe just try flushing, again.
I fully admit that this seems rather arbitrary... I don't mind removing it and silently ignore the Sync error.
</blockquote></details>

Turned out this was a bit useless as it showed spurious errors, recommended workaround seems to be to ignore errors from Sync (see linked issue).
___
*[`private/svc/internal/ctxconn/ctxconn.go` line 57 at r2](https://reviewable.io/reviews/scionproto/scion/4310#-NNHCAkK7B0MIl5DxJTX:-NNMpb8zAF-XBxY2Gqck:bdzpbfv) ([raw file](https://github.com/scionproto/scion/blob/37f7303398a4d30ccdfc663c09c4c998b88b7e3a/private/svc/internal/ctxconn/ctxconn.go#L57)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

then let's fix it and close the conn :) 
</blockquote></details>

Yup, see #4314 


<!-- Sent from Reviewable.io -->

2023-02-06 08:44 UTC, lukedirtwalker approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oncilla)



<!-- Sent from Reviewable.io -->

2023-02-06 10:50 UTC, oncilla requested changes
> Reviewed 64 of 76 files at r1, 2 of 2 files at r2, 7 of 7 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310)* status: all files reviewed, 9 unresolved discussions (waiting on @matzf)

___
*[`gateway/control/engine_test.go` line 45 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaIfaj6-GyVlXXu41r:-NNaIfaj6-GyVlXXu41s:b-mkzwt4) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/gateway/control/engine_test.go#L45)):*
> ```Go
> 
> 		go func() {
> 			assert.NoError(t, engine.Run(context.Background()))
> ```

You should not mark a test as failed outside of the go routine that is running the test.

Either consume the error in the main go routine, or panic instead.
___
*[`gateway/control/enginecontroller_test.go` line 51 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaIt8D5bXwFWbnq_gu:-NNaIt8D5bXwFWbnq_gv:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/gateway/control/enginecontroller_test.go#L51)):*
> ```Go
> 
> 		go func() {
> 			assert.NoError(t, engineController.Run(context.Background()))
> ```

ditto
___
*[`gateway/control/watcher_test.go` line 82 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaJN5p3k5pK1UgPvSH:-NNaJN5p3k5pK1UgPvSI:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/gateway/control/watcher_test.go#L82)):*
> ```Go
> 	remotes.Set(0)
> 	ctx, cancel := context.WithTimeout(context.Background(), 50*time.Millisecond)
> 	go func() { assert.NoError(t, w.Run(ctx)) }()
> ```

ditto
___
*[`gateway/control/watcher_test.go` line 173 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaJO8BDDS0L77P_s_7:-NNaJO8BDDS0L77P_s_8:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/gateway/control/watcher_test.go#L173)):*
> ```Go
> 	defer cancel()
> 
> 	go func() { assert.NoError(t, w.Run(ctx)) }()
> ```

ditto
___
*[`pkg/grpc/dialer_test.go` line 46 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaJfFYCJQxzI-pUEiy:-NNaJfFYCJQxzI-pUEiz:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/pkg/grpc/dialer_test.go#L46)):*
> ```Go
> 	s := grpc.NewServer()
> 	helloworldpb.RegisterGreeterServer(s, &server{})
> 	go func() { assert.NoError(t, s.Serve(lis)) }()
> ```

ditto
___
*[`pkg/private/xtest/grpc.go` line 74 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaJnA60IeKnWrBgaHx:-NNaJnA60IeKnWrBgaHy:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/pkg/private/xtest/grpc.go#L74)):*
> ```Go
> func (s *GRPCService) Start(t *testing.T) {
> 	go func() {
> 		err := s.server.Serve(s.listener)
> ```

ditto
___
*[`private/app/path/pathprobe/paths.go` line 207 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaKUsw1Ak-hzzexMt7:-NNaKUsw1Ak-hzzexMt8:b-gd1wo) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/private/app/path/pathprobe/paths.go#L207)):*
> ```Go
> 			defer conn.Close()
> 			if err := conn.SetDeadline(deadline); err != nil {
> 				return serrors.New("setting deadline", "err", err)
> ```

I think this should be a serrors.WrapStr instead, no?
___
*[`private/worker/worker_test.go` line 35 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaKzyNA0Rz1pzLrJTp:-NNaKzyNA0Rz1pzLrJTq:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/private/worker/worker_test.go#L35)):*
> ```Go
> 
> 		go func() {
> 			assert.NoError(t, worker.Run())
> ```

ditto
___
*[`private/worker/worker_test.go` line 47 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaL-iP8bu6t4lhmnoX:-NNaL-iP8bu6t4lhmnoY:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/private/worker/worker_test.go#L47)):*
> ```Go
> 
> 		go func() {
> 			assert.NoError(t, worker.Run())
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-02-09 15:12 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310)* status: 73 of 82 files reviewed, 9 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, and @oncilla)

___
*[`gateway/control/engine_test.go` line 45 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaIfaj6-GyVlXXu41r:-NNq_Grk5juE3MzBo6jr:bs2jl4t) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/gateway/control/engine_test.go#L45)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

You should not mark a test as failed outside of the go routine that is running the test.

Either consume the error in the main go routine, or panic instead.

</blockquote></details>

Right, I see, I had not considered this. 
I've changed this here and below by using an `errgroup` and `Wait`ing for the _thing_ to complete. In some cases, this required to add some more shutdown logic to the tests. Please stop me if you think is just making things needlessly more complicated.

Just for the record, it _is_ ok to fail a test in a goroutine, as long as its done _before_ the main go routine running the test has completed. However, `FailNow` (and thus `require....`) indeed must not be called from  goroutines created during the test.

A quick "semgrep" search showed a few more cases of this, other than the ones I've newly added. I'll open a separate issue for this.
___
*[`gateway/control/enginecontroller_test.go` line 51 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaIt8D5bXwFWbnq_gu:-NNqhlpmDZQ-oIFKkc-w:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/gateway/control/enginecontroller_test.go#L51)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`gateway/control/watcher_test.go` line 82 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaJN5p3k5pK1UgPvSH:-NNqhp8W8TPA8KgR1ynQ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/gateway/control/watcher_test.go#L82)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`gateway/control/watcher_test.go` line 173 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaJO8BDDS0L77P_s_7:-NNqhpT7CVAbVebtd8ta:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/gateway/control/watcher_test.go#L173)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/grpc/dialer_test.go` line 46 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaJfFYCJQxzI-pUEiy:-NNqhsmi1bxaK1ocWIHq:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/pkg/grpc/dialer_test.go#L46)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/private/xtest/grpc.go` line 74 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaJnA60IeKnWrBgaHx:-NNqhyiy1NDxMMw5zP_-:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/pkg/private/xtest/grpc.go#L74)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`private/app/path/pathprobe/paths.go` line 207 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaKUsw1Ak-hzzexMt7:-NNqimV306twVX3EBpgl:bb77uf3) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/private/app/path/pathprobe/paths.go#L207)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I think this should be a serrors.WrapStr instead, no?
</blockquote></details>

Yes!
___
*[`private/worker/worker_test.go` line 35 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaKzyNA0Rz1pzLrJTp:-NNqi25f7g9l46sFBae_:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/private/worker/worker_test.go#L35)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`private/worker/worker_test.go` line 47 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaL-iP8bu6t4lhmnoX:-NNqi2Z44AxPgqaY7taE:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/private/worker/worker_test.go#L47)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-09 17:06 UTC, oncilla approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 10 files at r7, 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310#-:-NNr8E6Q6RoHIkZTovCy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

___
*[`gateway/control/engine_test.go` line 45 at r6](https://reviewable.io/reviews/scionproto/scion/4310#-NNaIfaj6-GyVlXXu41r:-NNr7m600HhQltn3GZn2:b-aub5x6) ([raw file](https://github.com/scionproto/scion/blob/d231e72ebe10fda7f7b20dccb63d33f80003ae42/gateway/control/engine_test.go#L45)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Right, I see, I had not considered this. 
I've changed this here and below by using an `errgroup` and `Wait`ing for the _thing_ to complete. In some cases, this required to add some more shutdown logic to the tests. Please stop me if you think is just making things needlessly more complicated.

Just for the record, it _is_ ok to fail a test in a goroutine, as long as its done _before_ the main go routine running the test has completed. However, `FailNow` (and thus `require....`) indeed must not be called from  goroutines created during the test.

A quick "semgrep" search showed a few more cases of this, other than the ones I've newly added. I'll open a separate issue for this.
</blockquote></details>

I think for this specific case, an error channel would be enough.
But error group is also fine with me :thumbsup: 


<!-- Sent from Reviewable.io -->

2023-02-09 20:29 UTC, oncilla approved these changes
> Reviewed 1 of 10 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4310)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-02-10 08:25 UTC, merged