control: close connection in SVC resolver
scionproto/scion pull request #4314
Opened 2023-02-03 14:50 UTC by matzf

When performing a service address resolution with `svc.Resolver.LookupSVC`, a new connection was opened but never closed.
One possible reason for this bug was that the unclear responsibility for closing the connection; the `svc.RoundTripper.RoundTrip` function closes the connection if the context ends, but not otherwise.

Fixed always closing the conn after the request in `LookupSVC`. Also move `CloseConnOnDone` here too, to make it clearer where the connection is closed.

2023-02-06 10:53 UTC, lukedirtwalker requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4314)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4314#-NNaL-4wB-1B4CYX4GeT:-NNaL-4wB-1B4CYX4GeU:b-d1539e) (no related file):*
So looking at the implementation of the `CloseConnOnDone` I wonder why it's so complex and whether we shouldn't simply change that implementation. I would do it like this:

```go
// CloseConnOnDone closes conn whenever ctx is Done. This includes if ctx is
// canceled via its cancellation function.
//
// Call the returned cancellation function to free up resources and closing the
// connection.
func CloseConnOnDone(ctx context.Context, conn DeadlineCloser) context.CancelFunc {
	if deadline, ok := ctx.Deadline(); ok {
		conn.SetDeadline(deadline)
	}

	ctx, cancel := context.WithCancel(ctx)

	go func() {
		defer log.HandlePanic()
		<-ctx.Done()
		if err := conn.Close(); err != nil {
			log.Info("Error closing conn when ctx canceled", "err", err)
		}
	}()
	return cancel
}
```
then in the code below you only the the `cancel()` call.

___
___
*[`private/svc/resolver.go` line 106 at r1](https://reviewable.io/reviews/scionproto/scion/4314#-NNaLqjM5tM-zh5wpOeL:-NNaLqjM5tM-zh5wpOeM:b-9vexsi) ([raw file](https://github.com/scionproto/scion/blob/6dc15dd83da6c6059734dca75c4e39a94f7f4eb2/private/svc/resolver.go#L106)):*
> ```Go
> 	}
> 	reply, err := r.getRoundTripper().RoundTrip(ctx, conn, requestPacket, p.UnderlayNextHop())
> ```

I wouldn't have the extra empty line.


<!-- Sent from Reviewable.io -->

2023-02-10 09:14 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4314)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4314#-NNaL-4wB-1B4CYX4GeT:-NNuYZax-9v1jA4CU3xo:blr6q7b) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

So looking at the implementation of the `CloseConnOnDone` I wonder why it's so complex and whether we shouldn't simply change that implementation. I would do it like this:

```go
// CloseConnOnDone closes conn whenever ctx is Done. This includes if ctx is
// canceled via its cancellation function.
//
// Call the returned cancellation function to free up resources and closing the
// connection.
func CloseConnOnDone(ctx context.Context, conn DeadlineCloser) context.CancelFunc {
	if deadline, ok := ctx.Deadline(); ok {
		conn.SetDeadline(deadline)
	}

	ctx, cancel := context.WithCancel(ctx)

	go func() {
		defer log.HandlePanic()
		<-ctx.Done()
		if err := conn.Close(); err != nil {
			log.Info("Error closing conn when ctx canceled", "err", err)
		}
	}()
	return cancel
}
```
then in the code below you only the the `cancel()` call.
</blockquote></details>

Sounds good to me too. I've made it just a little bit more complicated than this, so that the cancel function waits for the `Close` to be done (and return the error). This is mostly relevant for the tests where this would otherwise run too late for the call to `Close` to be recorded during the test, unless we sleep or so. Returning the error also allows handling it (by logging) one level higher up.

___
___
*[`private/svc/resolver.go` line 106 at r1](https://reviewable.io/reviews/scionproto/scion/4314#-NNaLqjM5tM-zh5wpOeL:-NNuaVNZ2hO_ZisPMFYa:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/6dc15dd83da6c6059734dca75c4e39a94f7f4eb2/private/svc/resolver.go#L106)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I wouldn't have the extra empty line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-13 07:31 UTC, lukedirtwalker requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4314)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`-- commits` line 23 at r2](https://reviewable.io/reviews/scionproto/scion/4314#-NO8er2r1D90BIKn-1RV):*
Make sure that this is the description of the PR.
___
*[`private/svc/internal/ctxconn/ctxconn_test.go` line 63 at r2](https://reviewable.io/reviews/scionproto/scion/4314#-NO8fPYd3XZry4apBsLa:-NO8fPYd3XZry4apBsLb:b-8hxtbd) ([raw file](https://github.com/scionproto/scion/blob/cd1182b39c41c02502c96fb9fbbf88b273abc60f/private/svc/internal/ctxconn/ctxconn_test.go#L63)):*
> ```Go
> 		ctrl := gomock.NewController(t)
> 		defer ctrl.Finish()
> 		deadline := time.Now().Add(20 * time.Millisecond)
> ```

have you considered just using the `ctxCancelF` directly then the test doesn't need to wait until the context is expired.


<!-- Sent from Reviewable.io -->

2023-02-13 08:08 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4314)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[`-- commits` line 23 at r2](https://reviewable.io/reviews/scionproto/scion/4314#-NO8er2r1D90BIKn-1RV):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Make sure that this is the description of the PR.
</blockquote></details>

Done, thanks!



_Code quote:_
```
  When performing a service address resolution with svc.Resolver.LookupSVC,
  a new connection was opened but never closed.
  One possible reason for this bug was that the unclear responsibility for
  closing the connection; the svc.RoundTripper.RoundTrip function closes
  the connection if the context ends, but not otherwise.

  Fix this by always closing the conn in CloseConnOnDone.
  The cancel function of CloseConnOnDone now also blocks until the
  connection is closed (relevant mostly for testing) and returns any
  errors from closing.
  Also move the CloseConnOnDone to LookupSVC, so the responsibility for
  closing the connection is right next to where it's opened.
```
___
*[`private/svc/internal/ctxconn/ctxconn_test.go` line 63 at r2](https://reviewable.io/reviews/scionproto/scion/4314#-NO8fPYd3XZry4apBsLa:-NO8nWv29wvH4x-9GInn:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/cd1182b39c41c02502c96fb9fbbf88b273abc60f/private/svc/internal/ctxconn/ctxconn_test.go#L63)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

have you considered just using the `ctxCancelF` directly then the test doesn't need to wait until the context is expired.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-13 09:03 UTC, oncilla requested changes
> Reviewed 1 of 2 files at r1, 2 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4314)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @lukedirtwalker and @matzf)

___
*[`private/svc/internal/ctxconn/ctxconn.go` line 45 at r3](https://reviewable.io/reviews/scionproto/scion/4314#-NO9-QGT8QiXaEFoEuN1:-NO9-QGT8QiXaEFoEuN2:byvzorf) ([raw file](https://github.com/scionproto/scion/blob/f06d8365f164225a21f6ddcbab24277432d21c81/private/svc/internal/ctxconn/ctxconn.go#L45)):*
> ```Go
> 
> 	ctx, cancelCtx := context.WithCancel(ctx)
> 	errChan := make(chan error)
> ```

make this a buffered channel of size 1.

Otherwise, the go routine leaks until the cancel function is invoked.


<!-- Sent from Reviewable.io -->

2023-02-13 09:04 UTC, oncilla reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4314)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[`private/svc/internal/ctxconn/ctxconn.go` line 45 at r3](https://reviewable.io/reviews/scionproto/scion/4314#-NO9-QGT8QiXaEFoEuN1:-NO908jF6-4UWTzKumQQ:btz7u6t) ([raw file](https://github.com/scionproto/scion/blob/f06d8365f164225a21f6ddcbab24277432d21c81/private/svc/internal/ctxconn/ctxconn.go#L45)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

make this a buffered channel of size 1.

Otherwise, the go routine leaks until the cancel function is invoked.
</blockquote></details>

:facepalm: 

Nevermind me, we block anyway until the cancel function is invoked.


<!-- Sent from Reviewable.io -->

2023-02-13 09:10 UTC, lukedirtwalker approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4314)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-02-13 09:10 UTC, lukedirtwalker approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4314)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-02-13 09:33 UTC, lukedirtwalker approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4314)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-02-13 10:52 UTC, oncilla approved these changes
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4314)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-02-13 11:24 UTC, merged