doc: reorganize and extend documentation
scionproto/scion pull request #4325
Opened 2023-03-07 11:17 UTC by matzf

The documentation has been a somewhat unsorted bag of documents. It was mostly focused on contributors to this project, but some sections did target users of the software, without a clear distinction.

This PR attempts to bring some more structure into this. There are now three separate sections:
   - SCION:
     Explanations and Specifications. Explain SCION on a conceptual level.
     Should introduce concepts that a user or dev needs to make sense of the manuals etc.

     Target audience: anyone (users, developers, outsiders)
   - Reference manuals:
     Target audience: users of this SCION implementation (operator of SCION infrastructure or hosts), users of any of the SCION APIs.
   - Developer section:
     Target audience: contributors to this SCION implementation
     
In particular, the developer section now "hides" the design documents away a bit and the intended workflow for these documents is clarified.

There is still a lot TODO.

2023-03-16 16:07 UTC, nicorusti reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4325)* status: 0 of 74 files reviewed, 3 unresolved discussions (waiting on @matzf)

___
*[`doc/index.rst` line 23 at r1](https://reviewable.io/reviews/scionproto/scion/4325#-NQf7GZaEuSUuNQ0gJVj:-NQf7GZaEuSUuNQ0gJVk:bngfy7t) ([raw file](https://github.com/scionproto/scion/blob/d890793baa678ad0cf5a776930846063495e4faf/doc/index.rst#L23)):*
> ```reStructuredText
> 
>    - Developer section:
>      Target audience: contributors to this SCION implementation
> ```

Currently, SCION and the open source implementation are tightly coupled (they are nearly the same thing). However, with standardisation efforts, I think it is important to decouple them. On one side we have the technology (SCION, its properties, use cases, specification), and on the other side the open source implementation. 
I therefore suggest a different naming:  

- Technology: I would move here the first paragraph, and then add link placeholders for Overview, Specification, advanced features, extensions..  
- Reference implementation: what you have under reference manuals
- Contribute: what you have under Developer Documentation. I think in the long term, this section could potentially be split in two: Contribute, focusing on who wants to contribute to the open source, and something like build/deploy, aimed at who wants to try or run the SCION reference implementation (this could be a link to https://docs.scionlab.org for now)



_Code quote:_
```reStructuredText
.. (Comment)
   This documentation is structured into sections with different purposes/audiences

   - SCION:
     Explanations and Specifications. Explain SCION on a conceptual level.
     Should introduce concepts that a user or dev needs to make sense of the manuals etc.

     Target audience: anyone (users, developers, outsiders)

   - Reference manuals:
     Target audience: users of this SCION implementation (operator of SCION
     infrastructure or hosts), users of any of the SCION APIs.

   - Developer section:
     Target audience: contributors to this SCION implementation
```
___
*[`doc/manuals/common.rst` line 72 at r1](https://reviewable.io/reviews/scionproto/scion/4325#-NQewaeZAFqMkgPoYXsK:-NQewaeZAFqMkgPoYXsL:b-7i2two) ([raw file](https://github.com/scionproto/scion/blob/d890793baa678ad0cf5a776930846063495e4faf/doc/manuals/common.rst#L72)):*
When I had to deal with it, I was confused about why the full AS topology.json is needed by the daemon on end-host applications. It is good that you mention this, perhaps it would be good to further elaborate on why it is like this. Something like:
 
> for the sake of simplicity, you can use the same topology.json file on all SCION components within the SCION AS. In more advanced configurations, an extract of the topology.json file can be presented to each specific component.".  



_Code quote:_
```reStructuredText
.. Note::

   The topology.json configuration file contains information that is not relevant for all consumers
   of the file.
```
___
*[`doc/manuals/common.rst` line 187 at r1](https://reviewable.io/reviews/scionproto/scion/4325#-NQercqvCxdlxaAU-D-s:-NQercqvCxdlxaAU-D-t:babm8g3) ([raw file](https://github.com/scionproto/scion/blob/d890793baa678ad0cf5a776930846063495e4faf/doc/manuals/common.rst#L187)):*
> ```reStructuredText
>       .. option:: link_to = "parent"|"child"|"peer"|"core", required
> 
>          Type of the relation to the neighbor AS.
> ```

It would be perhaps good to mention that peering links are not working until https://github.com/scionproto/scion/issues/4093 is solved. 



_Code quote:_
```reStructuredText
      .. option:: link_to = "parent"|"child"|"peer"|"core", required

         Type of the relation to the neighbor AS.
```


<!-- Sent from Reviewable.io -->

2023-04-21 09:19 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4325)* status: 0 of 75 files reviewed, 3 unresolved discussions (waiting on @nicorusti)

___
*[`doc/index.rst` line 23 at r1](https://reviewable.io/reviews/scionproto/scion/4325#-NQf7GZaEuSUuNQ0gJVj:-NTY2mMc10NLFjmOXMmu:b-6mydek) ([raw file](https://github.com/scionproto/scion/blob/d890793baa678ad0cf5a776930846063495e4faf/doc/index.rst#L23)):*
<details><summary><i>Previously, nicorusti (Nicola Rustignoli) wrote…</i></summary><blockquote>

Currently, SCION and the open source implementation are tightly coupled (they are nearly the same thing). However, with standardisation efforts, I think it is important to decouple them. On one side we have the technology (SCION, its properties, use cases, specification), and on the other side the open source implementation. 
I therefore suggest a different naming:  

- Technology: I would move here the first paragraph, and then add link placeholders for Overview, Specification, advanced features, extensions..  
- Reference implementation: what you have under reference manuals
- Contribute: what you have under Developer Documentation. I think in the long term, this section could potentially be split in two: Contribute, focusing on who wants to contribute to the open source, and something like build/deploy, aimed at who wants to try or run the SCION reference implementation (this could be a link to https://docs.scionlab.org for now)
</blockquote></details>

Thanks for looking at this and the feedback. I've implemented some of this.
I prefer the title "Reference Manuals" as that's what is in there. I added some text to indicate that this refers to the scionproto/scion implementation of SCION. I don't really want to start calling this the "reference implementation".
I also left the title "Developer Documentation". Yes, there will need to be some "how to build" instructions at some point, or more generally "how to install (from packages/images/sources...)". Either we'll have a separate "How-to-guides and tutorials" section or this would be a part of the reference manuals.
___
*[`doc/manuals/common.rst` line 72 at r1](https://reviewable.io/reviews/scionproto/scion/4325#-NQewaeZAFqMkgPoYXsK:-NTY5qUi7VOHK7oJdjO7:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d890793baa678ad0cf5a776930846063495e4faf/doc/manuals/common.rst#L72)):*
<details><summary><i>Previously, nicorusti (Nicola Rustignoli) wrote…</i></summary><blockquote>

When I had to deal with it, I was confused about why the full AS topology.json is needed by the daemon on end-host applications. It is good that you mention this, perhaps it would be good to further elaborate on why it is like this. Something like:
 
> for the sake of simplicity, you can use the same topology.json file on all SCION components within the SCION AS. In more advanced configurations, an extract of the topology.json file can be presented to each specific component.".  

</blockquote></details>

Done.
___
*[`doc/manuals/common.rst` line 187 at r1](https://reviewable.io/reviews/scionproto/scion/4325#-NQercqvCxdlxaAU-D-s:-NTY4OUb1ZIKQ3tuCqo2:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d890793baa678ad0cf5a776930846063495e4faf/doc/manuals/common.rst#L187)):*
<details><summary><i>Previously, nicorusti (Nicola Rustignoli) wrote…</i></summary><blockquote>

It would be perhaps good to mention that peering links are not working until https://github.com/scionproto/scion/issues/4093 is solved. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-04 11:45 UTC, oncilla requested changes
> Reviewed 3 of 74 files at r1, 3 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4325)* status: 6 of 75 files reviewed, 6 unresolved discussions (waiting on @matzf and @nicorusti)

___
*[`doc/glossary.rst` line 2 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaTuxe8TmF2FUANCuB:-NUaTuxf87B1CYgvn1g7:b-dv2pzm) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/glossary.rst#L2)):*
> ```reStructuredText
> ********
> Glossary
> ```

I think this will need to grow over time :) 
___
*[`doc/glossary.rst` line 30 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaTcnS5g3LK5jCj_Mi:-NUaTcnS5g3LK5jCj_Mj:b-o1adn3) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/glossary.rst#L30)):*
> ```reStructuredText
>       and trigger :term:`SCMP` error messages
> 
>    CP-PKI
> ```

Out of curiosity: Is this the spelling that is used in the book?

We commonly spell it as `CPPKI` and I think even the ietf draft uses `CPPKI`
___
*[`doc/hidden-paths.rst` line 5 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaVWlH76sVys_Yl5Yf:-NUaVWlH76sVys_Yl5Yg:b88n8rg) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/hidden-paths.rst#L5)):*
> ```reStructuredText
> ************
> 
> .. TODO
> ```

Would it make sense add a `.. note::` that there are missing sections or this is a work in progress?
___
*[`doc/index.rst` line 35 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaWfj2BIrcvyQZfof-:-NUaWfj2BIrcvyQZfof0:bf7125x) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/index.rst#L35)):*
> ```reStructuredText
>    :hidden:
> 
>    Protocols <protocols/index>
> ```

Protocols feels a bit like a misnomer. AFAICT, these are mostly wire format specs.

It is also a bit odd to group SCION header (which is the basics of the SCION dataplane) with the SIG framing protocol (which is an application on top of SCION).

The BFD/SCION section also feels a bit out of place there.
___
*[`doc/index.rst` line 38 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaXjJR3VJb3ImP-cpA:-NUaXjJR3VJb3ImP-cpB:bxxfnyu) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/index.rst#L38)):*
> ```reStructuredText
>    Cryptography <cryptography/index>
>    hidden-paths
>    beacon-metadata
> ```

Having this as a top-level is a bit odd.
I would expect this to be a sub-section of a path exploration document (or similar)

I guess this is here because there is a lack of documentation around path exploration.
___
*[`doc/index.rst` line 95 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaT9li1RqkxW4rgxkI:-NUaT9li1RqkxW4rgxkJ:b-v7sqf1) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/index.rst#L95)):*
> ```reStructuredText
> .. TODO
>    snet documentation should be a good starting point for using SCION as an application library.
>    For this, the package documentation needs to be streamlined a bit...
> ```

I think here we should make extensive use of godoc examples.
___
*[`doc/manuals/router/http-api.rst` line 1 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaZjFR4rfb-1t2srOM:-NUaZjFR4rfb-1t2srON:b-gqv0su) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/manuals/router/http-api.rst#L1)):*
> ```reStructuredText
> The HTTP API is exposed by the :program:`router` application.
> ```

Instead of manually maintaining this, we should just use the generated openapi spec.

E.g., for closed source code we include the redocly generated docs:
https://docs.anapaya.net/en/latest/configuration/api/
___
*[`doc/manuals/router/metrics.rst` line 1 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaYqHsEaiwjlcyPZHg:-NUaYqHsEaiwjlcyPZHh:b-lnxbum) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/manuals/router/metrics.rst#L1)):*
> ```reStructuredText
> Metrics can expose any combination of the following set of labels:
> ```

We generate this type of information in our closed source code.

E.g., https://docs.anapaya.net/en/latest/management/telemetry/ is generated automatically.

If you want, I can contribute code, such that this section is always up to date.


<!-- Sent from Reviewable.io -->

2023-05-08 08:15 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4325)* status: 4 of 80 files reviewed, 6 unresolved discussions (waiting on @nicorusti and @oncilla)

___
*[`doc/glossary.rst` line 30 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaTcnS5g3LK5jCj_Mi:-NUaq-MK4y2urRMdDgI4:b-vj60ih) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/glossary.rst#L30)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Out of curiosity: Is this the spelling that is used in the book?

We commonly spell it as `CPPKI` and I think even the ietf draft uses `CPPKI`

</blockquote></details>

Ah, I hadn't realized that there are different spellings. I just checked, the spelling "CP-PKI" is used in the book and in the [draft-dekater-scion-pki](https://datatracker.ietf.org/doc/draft-dekater-scion-pki) (with the exception of the abbreviated title shown in the page breaks, which seems to be a mistake that will be corrected).
Outside of variable or package names, the only occurrences of the spelling "CPPKI" in the code base seems to be the documentation strings related to the management API.
Unless you object, I'd keep the dash
___
*[`doc/hidden-paths.rst` line 5 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaVWlH76sVys_Yl5Yf:-NUuQ_bk8-0LRrcZ62v3:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/hidden-paths.rst#L5)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Would it make sense add a `.. note::` that there are missing sections or this is a work in progress?
</blockquote></details>

Done.
___
*[`doc/index.rst` line 35 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaWfj2BIrcvyQZfof-:-NUuIj724YX8z5qlgYAb:bv6c2up) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/index.rst#L35)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Protocols feels a bit like a misnomer. AFAICT, these are mostly wire format specs.

It is also a bit odd to group SCION header (which is the basics of the SCION dataplane) with the SIG framing protocol (which is an application on top of SCION).

The BFD/SCION section also feels a bit out of place there.
</blockquote></details>

Ack. Moved out the SIG. I agree that BFD does not really fit well in there, but I didn't find a better place yet and kept it for now.

This section is now called "Data plane"; there should also be some overview and more detailed explanations.
___
*[`doc/index.rst` line 38 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaXjJR3VJb3ImP-cpA:-NUerWpeDH96lK0zj_8M:b-8nb26b) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/index.rst#L38)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Having this as a top-level is a bit odd.
I would expect this to be a sub-section of a path exploration document (or similar)

I guess this is here because there is a lack of documentation around path exploration.


</blockquote></details>

Ack.
I've added a bit of overview text and a placeholder control plane section, to illustrate the intended structure.
The overview text is mostly copy-pasted from the [scion overview IETF draft](https://datatracker.ietf.org/doc/draft-dekater-panrg-scion-overview/) for now.
___
*[`doc/index.rst` line 95 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaT9li1RqkxW4rgxkI:-NUauKv75R2BEf35rSvB:bb6sh2i) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/index.rst#L95)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I think here we should make extensive use of godoc examples.
</blockquote></details>

Ack.
___
*[`doc/manuals/router/http-api.rst` line 1 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaZjFR4rfb-1t2srOM:-NUaih206-ZsbRGuW41A:b-gyp4tn) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/manuals/router/http-api.rst#L1)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Instead of manually maintaining this, we should just use the generated openapi spec.

E.g., for closed source code we include the redocly generated docs:
https://docs.anapaya.net/en/latest/configuration/api/



</blockquote></details>

Note that this here only documents the "metrics.prometheus" HTTP API, not the OpenAPI one.
To document the OpenAPI, I agree that we should generate this. I've already started with this, but I'll contribute this as a separate PR together with the work on the rest of the manuals. The [sphinxcontrib.openapi](https://sphinxcontrib-openapi.readthedocs.io/) package is trivial to use and integrates nicely with the rest of the documentation structure, although its of course not quite as pretty as the redocly. 
___
*[`doc/manuals/router/metrics.rst` line 1 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaYqHsEaiwjlcyPZHg:-NUayzAK21HnVs3JuhNt:bi06se9) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/manuals/router/metrics.rst#L1)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

We generate this type of information in our closed source code.

E.g., https://docs.anapaya.net/en/latest/management/telemetry/ is generated automatically.

If you want, I can contribute code, such that this section is always up to date.



</blockquote></details>

Interesting. Yeah, that could be nice.
Ideally, I think, we'd check-in a  generated yaml/json file, that we can then render using [sphinx-contrib.datatemplates](https://github.com/sphinx-contrib/datatemplates), in order to separate the generation logic from the "presentation" in the documentation markup.


<!-- Sent from Reviewable.io -->

2023-05-08 18:02 UTC, oncilla requested changes
> Reviewed 63 of 74 files at r1, 3 of 7 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4325)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`doc/glossary.rst` line 30 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaTcnS5g3LK5jCj_Mi:-NUwVttnBovIPgm_mvV8:b-h287hu) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/glossary.rst#L30)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Ah, I hadn't realized that there are different spellings. I just checked, the spelling "CP-PKI" is used in the book and in the [draft-dekater-scion-pki](https://datatracker.ietf.org/doc/draft-dekater-scion-pki) (with the exception of the abbreviated title shown in the page breaks, which seems to be a mistake that will be corrected).
Outside of variable or package names, the only occurrences of the spelling "CPPKI" in the code base seems to be the documentation strings related to the management API.
Unless you object, I'd keep the dash
</blockquote></details>

No strong opinions.
___
*[`doc/manuals/router/http-api.rst` line 1 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaZjFR4rfb-1t2srOM:-NUwV1dQ9mT4a8aqSDKP:bf3f098) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/manuals/router/http-api.rst#L1)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Note that this here only documents the "metrics.prometheus" HTTP API, not the OpenAPI one.
To document the OpenAPI, I agree that we should generate this. I've already started with this, but I'll contribute this as a separate PR together with the work on the rest of the manuals. The [sphinxcontrib.openapi](https://sphinxcontrib-openapi.readthedocs.io/) package is trivial to use and integrates nicely with the rest of the documentation structure, although its of course not quite as pretty as the redocly. 
</blockquote></details>

With iframe magic, it can also be made to look like it is a proper RTD page.
But up to you. Both works for me.
___
*[`doc/manuals/router/metrics.rst` line 1 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaYqHsEaiwjlcyPZHg:-NUwVS8cC5YSD6cnOezT:b4ttwfr) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/manuals/router/metrics.rst#L1)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Interesting. Yeah, that could be nice.
Ideally, I think, we'd check-in a  generated yaml/json file, that we can then render using [sphinx-contrib.datatemplates](https://github.com/sphinx-contrib/datatemplates), in order to separate the generation logic from the "presentation" in the documentation markup.
</blockquote></details>

We can generate whatever is needed.

If you have a specific data template in mind, let me know how the input should look like.


<!-- Sent from Reviewable.io -->

2023-05-09 15:32 UTC, nicorusti reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4325)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[`doc/glossary.rst` line 2 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaTuxe8TmF2FUANCuB:-NV07Crl1wCLDr5sLgl6:btv0pq4) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/glossary.rst#L2)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I think this will need to grow over time :) 
</blockquote></details>

@matzf the current Internal CP and CP-PKI specifications both have a terminology section with quite a few more words.. I think you could take many definitions from there. 
Perhaps it makes sense if you chat with @cdekater about it


<!-- Sent from Reviewable.io -->

2023-05-11 06:34 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4325)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

___
*[`doc/glossary.rst` line 2 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaTuxe8TmF2FUANCuB:-NV8VSoODf5wSAiWBQa6:b-lgx5ik) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/glossary.rst#L2)):*
<details><summary><i>Previously, nicorusti (Nicola Rustignoli) wrote…</i></summary><blockquote>

@matzf the current Internal CP and CP-PKI specifications both have a terminology section with quite a few more words.. I think you could take many definitions from there. 
Perhaps it makes sense if you chat with @cdekater about it
</blockquote></details>

Sure, I haven't forgotten about that. I've just been adding terms as needed.
___
*[`doc/manuals/router/metrics.rst` line 1 at r2](https://reviewable.io/reviews/scionproto/scion/4325#-NUaYqHsEaiwjlcyPZHg:-NV8VuZD9mMKo56rTeki:b5mph5e) ([raw file](https://github.com/scionproto/scion/blob/caba8eb6dc6ad19384f1322e0e1c8e150e038fb2/doc/manuals/router/metrics.rst#L1)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

We can generate whatever is needed.

If you have a specific data template in mind, let me know how the input should look like.

</blockquote></details>

Ok great thanks. I'll get back to this in a separate PR.


<!-- Sent from Reviewable.io -->

2023-05-14 11:43 UTC, marcfrei approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thanks a lot!

> Reviewed 65 of 74 files at r1, 5 of 7 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4325#-:-NVP1nBj-sIAy2mBpUT_:b-118695)* status: all files reviewed, 30 unresolved discussions (waiting on @matzf)

___
*[`doc/control-plane.rst` line 14 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVKWozy6q5XvlDiRFET:-NVKWozy6q5XvlDiRFEU:b-c84w0v) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/control-plane.rst#L14)):*
> ```reStructuredText
> 
> The SCION control plane is responsible for discovering path segments and making them available to
> endpoints. This includes path-segment exploration (also called "beaconing"), registration, lookup
> ```

end hosts



_Code quote:_
```reStructuredText
endpoints
```
___
*[`doc/control-plane.rst` line 19 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVKX2Ba0iHs-LnYxmRg:-NVKX2Ba0iHs-LnYxmRh:b6xhthg) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/control-plane.rst#L19)):*
> ```reStructuredText
> .. admonition:: TODO
> 
>    Control plane overview and detailed description of beaconing, registration, lookup and
> ```

lookup, and



_Code quote:_
```reStructuredText
lookup and
```
___
*[`doc/glossary.rst` line 11 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVKftZw0bwAfUgcWKsM:-NVKftZw0bwAfUgcWKsN:bkmkxpf) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/glossary.rst#L11)):*
> ```reStructuredText
> 
>       An autonomous system is a computer network controlled by a single entity, typically an
>       internet-service provider or a larger organization like a university, participating in the
> ```

Capitalize "Internet" everywhere, like in the book?



_Code quote:_
```reStructuredText
internet
```
___
*[`doc/glossary.rst` line 13 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVKg8c18G5kLMFW1oHh:-NVKg8c18G5kLMFW1oHi:b-442ye6) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/glossary.rst#L13)):*
> ```reStructuredText
>       internet-service provider or a larger organization like a university, participating in the
>       internet routing.
>       In traditional BGP-based internet, ASes are assigned 32-bit autonomous system numbers (ASN).
> ```

In the traditional



_Code quote:_
```reStructuredText
In traditional
```
___
*[`doc/glossary.rst` line 14 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVKgITkE6xbJW5v45nn:-NVKgITkE6xbJW5v45no:b-7lr5kp) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/glossary.rst#L14)):*
> ```reStructuredText
>       internet routing.
>       In traditional BGP-based internet, ASes are assigned 32-bit autonomous system numbers (ASN).
>       The AS identifiers in SCION are longer, 48-bit, and usually occurs in combination with the
> ```

occur



_Code quote:_
```reStructuredText
occurs
```
___
*[`doc/glossary.rst` line 28 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVKgaur8992WJqYOBtg:-NVKgaur8992WJqYOBth:bteslpc) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/glossary.rst#L28)):*
> ```reStructuredText
> 
>       In SCION, BFD is used to determine the liveness of the link between two border routers
>       and trigger :term:`SCMP` error messages
> ```

"." at the end.
___
*[`doc/glossary.rst` line 47 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVP2PEE9lvG9ySoJgNY:-NVP2PEE9lvG9ySoJgNZ:b-nzlj98) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/glossary.rst#L47)):*
> ```reStructuredText
> 
>       At the same time Isolation Domains also serve as a local routing domain.
>       Inside an isolation domain, inter-domain links form a directed acyclic graph, allowing
> ```

links between ASes



_Code quote:_
```reStructuredText
inter-domain links
```
___
*[`doc/index.rst` line 72 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJQzRo48is3MZCti1g:-NVJQzRp3lGTMIgPYchp:bvd398) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L72)):*
> ```reStructuredText
>    snet API <https://pkg.go.dev/github.com/scionproto/scion/pkg/snet>
> 
> * **For operators of a SCION end host**:
> ```

I would put this into plural like "applications" below, i.e.: "For operators of SCION end hosts"
___
*[`doc/index.rst` line 77 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJRLUqDv9NFfW5LVA_:-NVJRLUqDv9NFfW5LVAa:b-fkqct5) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L77)):*
> ```reStructuredText
>   :doc:`manuals/dispatcher`
> 
> * **For operators of a SCION AS**:
> ```

"For operators of SCION ASes". Maybe also link to "AS" in the Glossary as the term might not be familiar to all potential readers.
___
*[`doc/index.rst` line 81 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJYInb64oOhIGLV7bL:-NVJYInb64oOhIGLV7bM:bu5lliy) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L81)):*
> ```reStructuredText
>   :doc:`manuals/control` |
>   :doc:`manuals/gateway` |
>   :doc:`manuals/common` |
> ```

Just call this "Configuration" and get rid of the subsection "Configuration" in "Common settings"?

(If not: Put all headings of subsections like this into title case, especially in the developers section? Currently it's a bit of a mix. Exceptions only for `scion`, `scion-pki`, and `snet`)
___
*[`doc/index.rst` line 112 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJWWUUAqlakiXqq8Wi:-NVJWWUUAqlakiXqq8Wj:b-6stmgu) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L112)):*
> ```reStructuredText
>   :ref:`governance` |
>   :ref:`change-proposal-process` |
>   :doc:`dev/style/index`
> ```

Just " Style Guides" instead of " Language style guides".
___
*[`doc/index.rst` line 114 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJUiH3D163BWnlXERl:-NVJUiH3D163BWnlXERm:b-wg2tfj) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L114)):*
> ```reStructuredText
>   :doc:`dev/style/index`
> 
> * **Building and running**
> ```

"Running" instead of "running" to align case of all three bullet points.
___
*[`doc/index.rst` line 114 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJV23-2kjMcX8skLZD:-NVJV2307BE9kSsglE1I:bcczpc4) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L114)):*
> ```reStructuredText
>   :doc:`dev/style/index`
> 
> * **Building and running**
> ```

":" at the end, like above and below.
___
*[`doc/index.rst` line 117 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJWlhsE0Bu1qQ3OP2B:-NVJWlhsE0Bu1qQ3OP2C:b8qwmqc) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L117)):*
> ```reStructuredText
>   :doc:`dev/setup` |
>   :doc:`dev/run` |
>   :doc:`dev/dependencies` |
> ```

Just "Dependencies" instead of "Managing external dependencies". Together with the  proposed "Style Guides" change "Testing then does not stick out that much as the shortest caption in the sidebar.
___
*[`doc/index.rst` line 120 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJVCll5nA7VE7bqLbk:-NVJVCll5nA7VE7bqLbl:b-szst1o) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L120)):*
> ```reStructuredText
>   :doc:`dev/testing/index`
> 
> * **Design Documen [...]

2023-05-15 08:23 UTC, nicorusti reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4325)* status: all files reviewed, 30 unresolved discussions (waiting on @marcfrei and @matzf)

___
*[`doc/control-plane.rst` line 14 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVKWozy6q5XvlDiRFET:-NVTRu6T3Ktz4_3rV-7f:b-wp6gmy) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/control-plane.rst#L14)):*
@marcfrei in accordance with https://datatracker.ietf.org/doc/draft-irtf-panrg-path-properties/ (that is soon to become an RFC), we are using the word "endpoint"  in the SCION specification and related IETF drafts. The definition in the draft above is: 

>  Endpoint:  The endpoints of a path are the start and end node of the
      path.  For example, an endpoint can be a host as defined in
      [RFC1122], which can be a client (e.g., a node running a web
      browser) or a server (e.g., a node running a web server).

I find using "endpoint" clearer. Whenever you have a SIG,  the SIG acts as a SCION "endpoint", and the hosts connecting via the SIG are "end hosts".  I guess the text above comes from one of the SCION drafts, @matzf  would it make sense to also use endpoint in the documentation here? 

From a specification point of view, we are waiting for the vocabulary draft to become an RFC. Then, at some point we would like to make a deeper vocabulary pass to try to align our vocabulary with the one in the draft.  


<!-- Sent from Reviewable.io -->

2023-05-15 08:29 UTC, marcfrei commented
*[`doc/control-plane.rst` line 14 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVKWozy6q5XvlDiRFET:-NVTWGypDunIF6o72UWF:b-1zturf) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/control-plane.rst#L14)):*
<details><summary><i>Previously, nicorusti (Nicola Rustignoli) wrote…</i></summary><blockquote>

@marcfrei in accordance with https://datatracker.ietf.org/doc/draft-irtf-panrg-path-properties/ (that is soon to become an RFC), we are using the word "endpoint"  in the SCION specification and related IETF drafts. The definition in the draft above is: 

>  Endpoint:  The endpoints of a path are the start and end node of the
      path.  For example, an endpoint can be a host as defined in
      [RFC1122], which can be a client (e.g., a node running a web
      browser) or a server (e.g., a node running a web server).

I find using "endpoint" clearer. Whenever you have a SIG,  the SIG acts as a SCION "endpoint", and the hosts connecting via the SIG are "end hosts".  I guess the text above comes from one of the SCION drafts, @matzf  would it make sense to also use endpoint in the documentation here? 

From a specification point of view, we are waiting for the vocabulary draft to become an RFC. Then, at some point we would like to make a deeper vocabulary pass to try to align our vocabulary with the one in the draft.  

</blockquote></details>

Ah, didn't know about that, thanks Nicola. My point is mostly about consistency. So you would recommend replacing "end host" everywhere with "endpoint"?


<!-- Sent from Reviewable.io -->

2023-05-15 11:33 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4325)* status: 64 of 82 files reviewed, 30 unresolved discussions (waiting on @marcfrei, @nicorusti, and @oncilla)

___
*[`doc/control-plane.rst` line 14 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVKWozy6q5XvlDiRFET:-NVTX0Vw3goU7UOFxoEQ:b-crnecf) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/control-plane.rst#L14)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Ah, didn't know about that, thanks Nicola. My point is mostly about consistency. So you would recommend replacing "end host" everywhere with "endpoint"?
</blockquote></details>

I have attempted to use "endpoint" in new text, but I've not made a pass to adapt old text.
However, in many cases the word "endpoint" seems rather awkward. Perhaps that's because  "endpoint" is more generic than "end host" in some way.

My feeling is that "endpoint" makes sense in text that explains SCION abstractly, because it's more generic, but in more hands-on documentation  "end host" is clearer.

I've added a combined glossary entry for "end host" and "endpoint", hope this helps.
___
*[`doc/control-plane.rst` line 19 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVKX2Ba0iHs-LnYxmRg:-NVU0uacCGw-8d8iDhd4:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/control-plane.rst#L19)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

lookup, and
</blockquote></details>

Done.
___
*[`doc/glossary.rst` line 11 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVKftZw0bwAfUgcWKsM:-NVU9TlI4ssF6XO3YZn7:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/glossary.rst#L11)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Capitalize "Internet" everywhere, like in the book?
</blockquote></details>

Done.
___
*[`doc/glossary.rst` line 13 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVKg8c18G5kLMFW1oHh:-NVU1f9E2UbYrN6C2BNC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/glossary.rst#L13)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

In the traditional
</blockquote></details>

Done.
___
*[`doc/glossary.rst` line 14 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVKgITkE6xbJW5v45nn:-NVU1k0w7ifV-rJSWpjh:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/glossary.rst#L14)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

occur
</blockquote></details>

Done.
___
*[`doc/glossary.rst` line 28 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVKgaur8992WJqYOBtg:-NVUARvLAukGNZHGX0SO:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/glossary.rst#L28)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

"." at the end.
</blockquote></details>

Done.
___
*[`doc/glossary.rst` line 47 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVP2PEE9lvG9ySoJgNY:-NVU1utm2jB7jB3V-o8I:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/glossary.rst#L47)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

links between ASes
</blockquote></details>

Done.
___
*[`doc/index.rst` line 72 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJQzRo48is3MZCti1g:-NVTDVaT0c6RnI6bN0AC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L72)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

I would put this into plural like "applications" below, i.e.: "For operators of SCION end hosts"
</blockquote></details>

Done.
___
*[`doc/index.rst` line 77 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJRLUqDv9NFfW5LVA_:-NVTDWVaBmfqo4k58s8b:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L77)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

"For operators of SCION ASes". Maybe also link to "AS" in the Glossary as the term might not be familiar to all potential readers.
</blockquote></details>

Done.
___
*[`doc/index.rst` line 81 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJYInb64oOhIGLV7bL:-NVU1xY5Cux25qFanQ8h:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L81)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Just call this "Configuration" and get rid of the subsection "Configuration" in "Common settings"?

(If not: Put all headings of subsections like this into title case, especially in the developers section? Currently it's a bit of a mix. Exceptions only for `scion`, `scion-pki`, and `snet`)
</blockquote></details>

Done.
___
*[`doc/index.rst` line 112 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJWWUUAqlakiXqq8Wi:-NVTF34W2gNLdREsLyNo:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L112)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Just " Style Guides" instead of " Language style guides".
</blockquote></details>

Done.
___
*[`doc/index.rst` line 114 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJUiH3D163BWnlXERl:-NVTF9Gq9bpM5il7M1TE:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L114)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

"Running" instead of "running" to align case of all three bullet points.
</blockquote></details>

Done.
___
*[`doc/index.rst` line 114 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJV23-2kjMcX8skLZD:-NVTGlxe2KvE67LBGkwU:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L114)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

":" at the end, like above and below.
</blockquote></details>

Done.
___
*[`doc/index.rst` line 117 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJWlhsE0Bu1qQ3OP2B:-NVTHGii4pkU6_mtF80L:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L117)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Just "Dependencies" instead of "Managing external dependencies". Together with the  proposed "Style Guides" change "Testing then does not stick out that much as the shortest caption in the sidebar.
</blockquote></details>

Done.
___
*[`doc/index.rst` line 120 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVJVCll5nA7VE7bqLbk:-NVTHS7e-M6lrZV6jkMR:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/index.rst#L120)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Just have the link for now as the bullet point? Instead of the redundant "Design Documents: Design Documents".
</blockquote></details>

Done.
___
*[`doc/overview.rst` line 43 at r3](https://reviewable.io/reviews/scionproto/scion/4325#-NVKjtKk8PDEJ6kywsuI:-NVU7Ffq26FqOd5xRFbU:bv19vxa) ([raw file](https://github.com/scionproto/scion/blob/eb0f129cdbcdaabc39167b3e29ab6f7e21266604/doc/overview.rst#L43)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>
 [...]

2023-05-15 12:34 UTC, marcfrei approved these changes
> Reviewed 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4325)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-05-15 12:51 UTC, marcfrei reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4325)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[`doc/index.rst` line 66 at r5](https://reviewable.io/reviews/scionproto/scion/4325#-NVUSEI_EZc77AbE2lAc:-NVUSEI_EZc77AbE2lAd:b-oaccik) ([raw file](https://github.com/scionproto/scion/blob/ed379af2749388bb7d8fb3f0486748ab5c424013/doc/index.rst#L66)):*
> ```reStructuredText
>    manuals/gateway
>    manuals/common
> ```

Is there a system behind the order above? Otherwise, I would suggest the following

```
Control Service
Router
Gateway
Daemon
Dispatcher
Configuration
...
```

(First control plane then data plane, and for the end host related services Daemon which is more important before Dispatcher)


<!-- Sent from Reviewable.io -->

2023-05-15 13:03 UTC, marcfrei approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4325)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-05-16 09:00 UTC, merged