Dispatcher removal
scionproto/scion pull request #4344
Opened 2023-05-17 11:04 UTC by JordiSubira

This PR intents to implement the dispatcher removal with the workaround discussed in https://github.com/scionproto/scion/pull/4280. The `dispatcher` and `reliable/sock` packages have been removed. 

Yet to be done:
- [ ] SCMP support (to be discussed)
- [ ] Fixing integration tests (dependent on previous task)
- [ ] Adapt metrics/error handling (if needed)

2023-05-25 11:36 UTC, matzf reviewed
Thank you or this contribution, great to see action on this topic!

This PR now contains multiple breaking changes and we'll need to figure out how to merge and deploy these with the least amount of friction. The implementation plan in the design document has some proposal for this, but its never been discussed much and there seem to be some concerns compatibility. As far as I can see, the main question is whether we should make provisions for running _old_ routers (i.e. routers not supporting the port dispatching) together with _new_ services / applications. By removing the dispatcher entirely (wow, -11k LoC :tada:), we wouldn't have that option.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344#-:-NWHB-1VD9rdVLVN5665:byf76y6)* status: 0 of 183 files reviewed, 3 unresolved discussions (waiting on @JordiSubira)

___
*[`pkg/snet/snet.go` line 69 at r1](https://reviewable.io/reviews/scionproto/scion/4344#-NWHCB8c3Dk7s3DzG1M1:-NWHCB8c3Dk7s3DzG1M2:b-r749wg) ([raw file](https://github.com/scionproto/scion/blob/1a1a9a63a1d1add608220623f9c4e487dc034e74/pkg/snet/snet.go#L69)):*
> ```Go
> 
> func (d *DefaultConnector) OpenUDP(addr *net.UDPAddr) (PacketConn, error) {
> 	pconn, err := conn.OpenConn(addr)
> ```

I don't think it's worth using the `underlay/conn` wrapper here. The main functionality provided by that wrapper is that it exposes a batched read/write call, but these are hidden away by the `net.PacketConn` interface. I'd use `net.UDPConn` directly here.

Setting the receive and send buffer sizes is not critical for the individual application sockets, and the same huge buffer sizes probably no longer make sense. In fact, they can relatively easily be set by the `SetReadBuffer`/`SetWriteBuffer` functions on the UDPConn. If we expose these functions and the `SyscallConn` from `SCIONPacketConn`, we can give the applications more direct control over these buffers -- in particular, quic-go could then set its desired buffer sizes.
___
*[`private/topology/topology.go` line 39 at r1](https://reviewable.io/reviews/scionproto/scion/4344#-NWHfmD52o4L9z4xRysN:-NWHfmD52o4L9z4xRysO:b-31zywv) ([raw file](https://github.com/scionproto/scion/blob/1a1a9a63a1d1add608220623f9c4e487dc034e74/private/topology/topology.go#L39)):*
> ```Go
> 	// TODO(JordiSubira): Yet to be defined.
> 	HostPortRangeLow  = 0
> 	HostPortRangeHigh = 1<<16 - 1
> ```

My understanding was that these ranges would be configurable in the topology configuration, maybe even allowing different ranges for different IP subnets.
___
*[`router/dataplane.go` line 1466 at r1](https://reviewable.io/reviews/scionproto/scion/4344#-NWHQ123AoDK_vhlka4E:-NWHQ124DdvUxn9Yp4VJ:brgnf8p) ([raw file](https://github.com/scionproto/scion/blob/1a1a9a63a1d1add608220623f9c4e487dc034e74/router/dataplane.go#L1466)):*
> ```Go
> 		return &net.UDPAddr{IP: dst.IP, Port: topology.EndhostPort}, nil
> 	default:
> 		panic(fmt.Sprintf("Port rewriting not supported for protcol number %v", l4Type))
> ```

That's just for debugging, right? :wink:
I think in any error cases it should just fall back to the default endhost port.


<!-- Sent from Reviewable.io -->

2023-09-28 13:52 UTC, JordiSubira reviewed
I added this shim component (it is still under the package disptacher, we can call it differently if this would make things clearer).

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344#-:-NfR2syn370qz_N8YbCj:b-nwul0g)* status: 0 of 190 files reviewed, 3 unresolved discussions (waiting on @matzf)

___
*[`pkg/snet/snet.go` line 69 at r1](https://reviewable.io/reviews/scionproto/scion/4344#-NWHCB8c3Dk7s3DzG1M1:-NfR2XZtD3SCEfjXnUaA:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1a1a9a63a1d1add608220623f9c4e487dc034e74/pkg/snet/snet.go#L69)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I don't think it's worth using the `underlay/conn` wrapper here. The main functionality provided by that wrapper is that it exposes a batched read/write call, but these are hidden away by the `net.PacketConn` interface. I'd use `net.UDPConn` directly here.

Setting the receive and send buffer sizes is not critical for the individual application sockets, and the same huge buffer sizes probably no longer make sense. In fact, they can relatively easily be set by the `SetReadBuffer`/`SetWriteBuffer` functions on the UDPConn. If we expose these functions and the `SyscallConn` from `SCIONPacketConn`, we can give the applications more direct control over these buffers -- in particular, quic-go could then set its desired buffer sizes.
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 1466 at r1](https://reviewable.io/reviews/scionproto/scion/4344#-NWHQ123AoDK_vhlka4E:-NfR2dyv-NmElQEl9QG1:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1a1a9a63a1d1add608220623f9c4e487dc034e74/router/dataplane.go#L1466)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

That's just for debugging, right? :wink:
I think in any error cases it should just fall back to the default endhost port.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-28 15:04 UTC, JordiSubira reviewed
> Reviewed 93 of 183 files at r1, 67 of 81 files at r2, 29 of 29 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 189 of 190 files reviewed, 20 unresolved discussions (waiting on @matzf)

___
*[`dispatcher/dispatcher.go` line 41 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRHjRp2bicilaO9KYW:-NfRHjRp2bicilaO9KYX:b-fsqvki) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/dispatcher/dispatcher.go#L41)):*
> ```Go
> 	// 	ErrMalformedL4Quote           common.ErrMsg = "malformed L4 quote"
> 	// ReceiveBufferSize is the size of receive buffers used by the dispatcher.
> 	ReceiveBufferSize = 1 << 20
> ```

Remove it is unused
___
*[`dispatcher/dispatcher.go` line 43 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRHnSu1-opikwWkjBp:-NfRHnSu1-opikwWkjBq:b-fsqvki) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/dispatcher/dispatcher.go#L43)):*
> ```Go
> 	ReceiveBufferSize = 1 << 20
> 	// SendBufferSize is the size of the send buffers used by the dispatcher.
> 	SendBufferSize = 1 << 20
> ```

Remove it is unused
___
*[`dispatcher/dispatcher.go` line 46 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRHyYz2-DeYBefjf8r:-NfRHyYz2-DeYBefjf8s:b-k0xzp2) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/dispatcher/dispatcher.go#L46)):*
> ```Go
> )
> 
> // Server is the main object allowing to create new SCION connections.
> ```

Update description
___
*[`dispatcher/cmd/dispatcher/main.go` line 57 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRICgi2Xrtu0xIbtXO:-NfRICgi2Xrtu0xIbtXP:b-pygr6m) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/dispatcher/cmd/dispatcher/main.go#L57)):*
> ```Go
> func realMain(ctx context.Context) error {
> 	path.StrictDecoding(false)
> 	topos, err := globalCfg.Topolgies(ctx)
> ```

Same as in other comment, give support for ignoring having access to the topology file, if we are not running on SVC environement (CS, DS, test environment...).
___
*[`dispatcher/cmd/dispatcher/main_test.go` line 16 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRIagxAvipFJisp1uP:-NfRIagy0uP_DY6TPNWd:bcomjxp) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/dispatcher/cmd/dispatcher/main_test.go#L16)):*
> ```Go
> // limitations under the License.
> 
> package main
> ```

Keep or delete?
___
*[`dispatcher/config/config.go` line 113 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRIiEH34uVDGDYlsnx:-NfRIiEH34uVDGDYlsny:bckp6w3) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/dispatcher/config/config.go#L113)):*
> ```Go
> }
> 
> func (cfg *Config) Topolgies(ctx context.Context) (map[addr.AS]*topology.Loader, error) {
> ```

See previous comments.
___
*[`dispatcher/internal/metrics/metrics.go` line 15 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRIt3XBJ8pZPseJuVK:-NfRIt3XBJ8pZPseJuVL:b-81nw90) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/dispatcher/internal/metrics/metrics.go#L15)):*
> ```Go
> // limitations under the License.
> 
> package metrics
> ```

Redo?
___
*[`gateway/gateway.go` line 477 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRJ26zC1T4CvS-BugN:-NfRJ26zC1T4CvS-BugO:byp18fd) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/gateway/gateway.go#L477)):*
> ```Go
> 		LocalIA: localIA,
> 		Connector: &snet.DefaultConnector{
> 			// Enable transparent reconnections to the dispatcher
> ```

Remove
___
*[`gateway/pathhealth/pathwatcher.go` line 81 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRJ9m72FIhSG53AhDN:-NfRJ9m72FIhSG53AhDO:bo6umg8) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/gateway/pathhealth/pathwatcher.go#L81)):*
> ```Go
> 		return create(remote)
> 	}
> 	// FIXME(JordiSubira): Keep or change the listening port, once we decide
> ```

Remove comment
___
*[`private/app/path/pathprobe/paths.go` line 106 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfR5_qm9bbbylnclUO5:-NfR5_qn0_f7VqDKAwQv:b-sdkclr) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/private/app/path/pathprobe/paths.go#L106)):*
> ```Go
> 	// should not be set, unless you know what you are doing.
> 	LocalIP net.IP
> 	// Metrics injected into snet.SCIONPacketConnMetrics.
> ```

DefaultConnector



_Code quote:_
```Go
SCIONPacketConnMetrics
```
___
*[`private/env/logging.go` line 36 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfR66jLCiUM-0pTsebp:-NfR66jLCiUM-0pTsebq:b-y3qivp) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/private/env/logging.go#L36)):*
> ```Go
> func LogAppStarted(svcType, elemID string) error {
> 	inDocker := false
> 	if runtime.GOOS == "linux" {
> ```

Add comment to clarify. Right now RunsInDocker() only is compatible with Linux. If we are going to run apps in docker also in macOS (and potentially in Windows) we should make the method compatible.
___
*[`private/service/statuspages.go` line 151 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfR765s9OJsOM_xC7Ie:-NfR765s9OJsOM_xC7If:b-7waofi) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/private/service/statuspages.go#L151)):*
> ```Go
> 		info := env.VersionInfo()
> 		inDocker := false
> 		if runtime.GOOS == "linux" {
> ```

Same as in other code snippet.
___
*[`router/dataplane.go` line 1769 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRAuCi23plihiA3PtD:-NfRAuCi23plihiA3PtE:byp18fd) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/router/dataplane.go#L1769)):*
> ```Go
> 			port = topology.EndhostPort
> 		}
> 		log.Debug("TBR XXXJ:", "udp port that will be rewritten", port)
> ```

Remove
___
*[`router/dataplane.go` line 1772 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRAxM7BTN2mlALSn25:-NfRAxM7BTN2mlALSn26:bduew77) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/router/dataplane.go#L1772)):*
> ```Go
> 		return &net.UDPAddr{IP: dst, Port: int(port)}, nil
> 	case slayers.L4SCMP:
> 		// TODO(JordiSubira): On-going discussion regarding SCMP dst port
> ```

Remove comment and log
___
*[`tools/topology/docker_utils.py` line 59 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfREKfX3gqqsZLyeiKj:-NfREKfX3gqqsZLyeiKk:byp18fd) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/tools/topology/docker_utils.py#L59)):*
> ```Python
>         return self.dc_conf
> 
>     # TODO(JordiSubira): Remove container if not needed
> ```

Remove
___
*[`tools/topology/go.py` line 173 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfREo4dBrghY2Ze5Bh1:-NfREo4dBrghY2Ze5Bh2:b-cpanc6) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/tools/topology/go.py#L173)):*
> ```Python
>         return raw_entry
> 
>     def generate_disp(self, topo_dicts):
> ```

Seems to be unused



_Code quote:_
```Python
 topo_dicts
```
___
*[`tools/topology/go.py` line 203 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRGdIP0WhkSxqA4ano:-NfRGdIP0WhkSxqA4anp:bo8cous) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/tools/topology/go.py#L203)):*
> ```Python
>             'dispatcher': {
>                 'id': name,
>                 "config_dir": config_dir,
> ```

The config_dir is the path were the topology.json file is located. This is only needed when the dispatcher is running to give support to the SVC se [...]

2023-09-29 12:57 UTC, JordiSubira reviewed
> Reviewed 11 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 189 of 190 files reviewed, 8 unresolved discussions (waiting on @matzf and @oncilla)



<!-- Sent from Reviewable.io -->

2023-10-23 13:13 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 183 of 190 files reviewed, 9 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`dispatcher/dispatcher.go` line 146 at r5](https://reviewable.io/reviews/scionproto/scion/4344#-NhReOEJ0Z9m6RYCrwew:-NhReOEJ0Z9m6RYCrwex:b-ux58w4) ([raw file](https://github.com/scionproto/scion/blob/22d9f1df789316d19b93e0c88760487f0be10b1f/dispatcher/dispatcher.go#L146)):*
> ```Go
> 			s.outBuffer.PushLayer(s.scmpLayer.LayerType())
> 		case slayers.LayerTypeSCIONUDP:
> 			dstAddrPort, err = s.getDstSCIONUDP()
> ```

We MAY want to check that the underlay IP address (in the UDP/IP layer) is the same IP as in the inner SCION/UDP header. 


<!-- Sent from Reviewable.io -->

2024-02-12 14:59 UTC, marcfrei reviewed
> Reviewed 87 of 183 files at r1, 37 of 81 files at r2, 13 of 29 files at r3, 4 of 12 files at r4, 1 of 7 files at r5, 2 of 2 files at r6, 2 of 3 files at r7, 62 of 73 files at r8, 20 of 20 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 22 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, @matzf, and @oncilla)

___
*[`control/cmd/control/main.go` line 688 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqRZg9JDBkL8LTGaxGH:-NqRZg9JDBkL8LTGaxGI:b-8224by) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/control/cmd/control/main.go#L688)):*
> ```Go
> 	})
> 	cleanup.Add(func() error { tcpServer.GracefulStop(); return nil })
> 	if hpInterASServer != nil {
> ```

We have three types of spelling in the error messages here:

- "Hidden path"
- "HP"
- "Hidden Path"
___
*[`dispatcher/dispatcher.go` line 100 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqSa9hs8iHTij4LahxP:-NqSa9hs8iHTij4LahxQ:b-aefzin) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher.go#L100)):*
> ```Go
> 		s.buf = s.buf[:cap(s.buf)]
> 
> 		n, nn, _, previousHop, err := s.conn.ReadMsgUDPAddrPort(s.buf, s.oobuf)
> ```

Or just `prevHop`?



_Code quote:_
```Go
previousHop
```
___
*[`dispatcher/dispatcher.go` line 402 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqScL0u4jGEFf3DvJ9C:-NqScL0u4jGEFf3DvJ9D:b-hbrjoi) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher.go#L402)):*
> ```Go
> }
> 
> // validateNextHopAddr returnS true if the underlay address on the UDP/IP wrapper
> ```

returns



_Code quote:_
```Go
returnS
```
___
*[`dispatcher/dispatcher_test.go` line 40 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqSd0kKBlL_EX2rD788:-NqSd0kKBlL_EX2rD789:bb7kry6) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher_test.go#L40)):*
> ```Go
> 
> func testRunTestCase(t *testing.T, tc testCase) {
> ```

Remove empty line
___
*[`dispatcher/cmd/dispatcher/main_test.go` line 16 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRIagxAvipFJisp1uP:-NqSOcRpExVOdcFLdHpi:b-73fvpi) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/dispatcher/cmd/dispatcher/main_test.go#L16)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Keep or delete?
</blockquote></details>

Imo, it doesn't make sense to keep fully commented out files, we can still look up this information in the git history.
___
*[`dispatcher/internal/metrics/metrics.go` line 15 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRIt3XBJ8pZPseJuVK:-NqRfju11vsQ2gaftwGN:bvp3316) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/dispatcher/internal/metrics/metrics.go#L15)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Redo?
</blockquote></details>

What's the state of this file? Could it also be removed?
___
*[`pkg/daemon/grpc.go` line 86 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqRo0BQ172Bn_j6xfEL:-NqRo0BQ172Bn_j6xfEM:b-7mo7en) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/pkg/daemon/grpc.go#L86)):*
> ```Go
> 
> func (c grpcConn) Interfaces(ctx context.Context) (map[uint16]*net.UDPAddr, error) {
> ```

Remove empty line?
___
*[`pkg/experimental/hiddenpath/discovery.go` line 67 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqRp9Ze4X5fp3GlZXyc:-NqRp9Ze4X5fp3GlZXyd:b-fpo325) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/pkg/experimental/hiddenpath/discovery.go#L67)):*
> ```Go
> // CSResolver resolves the address of a Control Service
> // server in an IA. This is needed to get the needed
> // certificates from the Register to verify the segments.
> ```

To what exactly does "Register" refer here?



_Code quote:_
```Go
from the Register
```
___
*[`pkg/snet/packet_conn.go` line 212 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqSPliIBae7u1ViLAbK:-NqSPliIBae7u1ViLAbL:bj08n74) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/pkg/snet/packet_conn.go#L212)):*
> ```Go
> 	lastHop, err := c.lastHop(pkt)
> 	if err != nil {
> 		return serrors.WrapStr("extracting next hop based on packet path", err)
> ```

"last"?



_Code quote:_
```Go
next
```
___
*[`pkg/snet/snet.go` line 101 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqSLV-M3MiJvn32R13G:-NqSLV-M3MiJvn32R13H:buebt0c) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/pkg/snet/snet.go#L101)):*
> ```Go
> 		SCMPHandler: d.SCMPHandler,
> 		Metrics:     d.Metrics,
> 		getLastHopAddr: func(id uint16) (*net.UDPAddr, error) {
> ```

Why not explicitly add a reference to the controller to `SCIONPacketConn` and make `getLastHopAddr` a normal helper function instead of capturing `ifAddrs` implicitly here?
___
*[`pkg/snet/snet.go` line 127 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqSZerh1qxcxH-a5Aah:-NqSZerh1qxcxH-a5Aai:b-we9khm) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/pkg/snet/snet.go#L127)):*
> ```Go
> 		return pconn, nil
> 	}
> 	return nil, serrors.New("There are no UDP ports available in range", "start", start, "end", end)
> ```

Or just `syscall.EADDRINUSE` for consistency with bind(2), https://man7.org/linux/man-pages/man2/bind.2.html?



_Code quote:_
```Go
serrors.New("There are no UDP ports available in range", "start", start, "end", end)
```
___
*[`private/topology/json/json.go` line 79 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqRlyUyA8rSxIAJFYWy:-NqRlyUyA8rSxIAJFYWz:b-s42eqw) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/private/topology/json/json.go#L79)):*
> ```Go
> 	MTU              int    `json:"mtu"`
> 	EndhostStartPort int    `json:"endhost_start_port"`
> 	EndhostEndPort   int    `json:"endhost_end_port"`
> ```

Did we also consider only having a single field `endhost_port_range" in the JSON with a port range format like, e.g., in Caddy: https://caddyserver.com/docs/conventions#network-addresses?



_Code quote:_
```Go
	EndhostStartPort int    `json:"endhost_start_port"`
	EndhostEndPort   int    `json:"endhost_end_port"`
```
___
*[`router/dataplane.go` line 1770 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqSGCaj2Ngyuu4BrDvY:-NqSGCaj2Ngyuu4BrDvZ:broxgt5) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/router/dataplane.go#L1770)):*
> ```Go
> 	switch l4Type {
> 	case slayers.L4UDP:
> 		// TODO(JordiSubira): Treat this as a parameter problem?
> ```

Yes, imo.



_Code quote:_
```Go
Treat this as a parameter problem?
```
___
*[`router/dataplane.go` line 1878 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqSHxba-zlwbR6oMqzo:-NqSHxba-zlwbR6oMqzp:b-7mo7f4) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/router/dataplane.go#L1878)):*
> ```Go
> 	}
> 	return 0, serrors.New("Unknown SCION SCMP content")
> ```

Remove empty line.
___
*[`router/config/config.go` line 76 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqRtOlO6dxdRdVOKRVh:-NqRtOlO6dxdRdVOKRVi:b4z4091) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/router/config/config.go#L76)):*
> ```Go
> 				"EndHostEndPort is nil; EndHostStartPort isn't")
> 		}
> 		if *cfg.EndhostStartPort < 0 {
> ```

`< 1`, right?



_Code quote:_
```Go
< 0
```


<!-- Sent from Reviewable.io -->

2024-02-15 16:14 UTC, matzf requested changes
> Reviewed 32 of 183 files at r1, 3 of 81 files at r2, 5 of 29 files at r3, 1 of 7 files at r5, 1 of 3 files at r7, 10 of 73 files at r8, 9 of 20 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 40 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, and @oncilla)

___
*[`acceptance/old_new_br/test.py` line 43 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqXECRCEdFFMUjP5uc0:-NqXECRCEdFFMUjP5uc1:b-6u6qt5) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/acceptance/old_new_br/test.py#L43)):*
> ```Python
>             / ("%s.toml" % br_as_2_id)
>         scion.update_toml({"router.endhost_start_port": 0}, [br_as_2_file])
>         scion.update_toml({"router.endhost_end_port": 0}, [br_as_2_file])
> ```

Nit: combine the two `update_toml` calls.
___
*[`acceptance/old_new_br/test.py` line 47 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhXaTJ3XqFdSI3pGt5:-NqhXaTJ3XqFdSI3pGt6:bngoeq) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/acceptance/old_new_br/test.py#L47)):*
> ```Python
>     def setup_start(self):
>         super().setup_start()
>         time.sleep(10)  # Give applications time to download configurations
> ```

Who downloads config (copy-pasta comment?)? Maybe just use `self.await_connectivity()` instead? 
___
*[`control/cmd/control/main.go` line 586 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhTiRHCczNavBm8AlV:-NqhTiRHCczNavBm8AlW:b-pm749i) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/control/cmd/control/main.go#L586)):*
> ```Go
> 	// because the client side, uses the DS to discover the address of the remote
> 	// HP server, thus it should use whatever is written in the topology file.
> 	hpInterASServer, hpWriterCfg, err := hpCfg.Setup(globalCfg.PS.HiddenPathsCfg)
> ```

How does this relate to the dispatcher removal? Isn't this a problem that we could fix separately?
___
*[`dispatcher/dispatcher.go` line 98 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqgjwoZ16BOg7pVoPTK:-NqgjwoZ16BOg7pVoPTL:b-t0mpap) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher.go#L98)):*
> ```Go
> func (s *Server) Serve() error {
> 	for {
> 		s.buf = s.buf[:cap(s.buf)]
> ```

Nit: this seems superfluous, we never resize `s.buf` anyway.
___
*[`dispatcher/dispatcher.go` line 118 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqghUXRCGokTEkNhUK7:-NqghUXRCGokTEkNhUK8:b93zc0w) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher.go#L118)):*
> ```Go
> 		// If the outgoing message is SCMP Informational message (Echo or Traceroute)
> 		// the dispatcher has already processed the response, and the nextHop address
> 		// belongs to the BR.
> ```

Move the `validateNextHopAddr` call into the processing function, so we don't need determine which case we're in here.
For this, perhaps it makes sense to parse the control message stuff first, and pass the destination address into the `processMsgNextHop` call.
___
*[`dispatcher/dispatcher.go` line 203 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-Nqgj_ir5roFzYG6jA06:-Nqgj_ir5roFzYG6jA07:b-28jtc8) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher.go#L203)):*
> ```Go
> 			return nil, nil
> 		}
> 		s.outBuffer.PushLayer(s.udpLayer.LayerType())
> ```

There does not seem to be a reason to perform this packet re-serialization in the forwarding cases, we can use the unchanged input buffer.
Only the SCMP replies need to be assembled.

One idea to do this would be to restructure such that this method `processMsgNextHop` returns a `[]byte` in addition to the address. For the forwarding cases, just return `buf`. For the SCMP reply case, assemble the packet and return `s.outBuffer.Bytes()`.
___
*[`dispatcher/dispatcher.go` line 223 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-Nqgm7Tg7wsw_L5AJxeP:-Nqgm7Tg7wsw_L5AJxeQ:bkaopvn) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher.go#L223)):*
> ```Go
> }
> 
> func (s *Server) reverseSCMPInfo() error {
> ```

`replyToSCMPInfoRequest`?
___
*[`dispatcher/dispatcher.go` line 463 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhQU6WAjiJslka1mub:-NqhQU6WAjiJslka1muc:blgt701) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher.go#L463)):*
> ```Go
> 	}()
> 
> 	return <-errChan
> ```

Looks like this go routine is not needed?



_Suggestion:_
```Go
	return dispServer.Serve()
```
___
*[`dispatcher/dispatcher.go` line 500 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqgsFkG6R5V2nvLj9mg:-NqgsFkG6R5V2nvLj9mh:busgrcu) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher.go#L500)):*
> ```Go
> 	}
> 
> 	if udpAddr.AddrPort().Addr().Unmap().Is4() {
> ```


It seems a bit confusing how this interacts with dual stack IPv4/6. As far as I can tell, this should work, but I was rather confused by the setup here.
I believe, this IPv4 code path will only be taken on hosts that don't support IPv6 (because we listen on a wildcard address and with the "udp" network type).  Otherwise, the IPv6 code path will take care of both 6 and 4 (with mapped addresses).
If I got this right, the structure does not need to be changed; but perhaps this could be documented in a code comment: IPv6 includes the dual stack case, IPv4 case is only fallback for IPv4-only host.

Btw. oerhaps the appropriate control message parser (ipv4ControlMessage or ipv6ControlMessage) could be initialized here too, so we don't need to figure this out again later.
___
*[`dispatcher/dispatcher.go` line 501 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqgsEvbC9b9xobqJ_e2:-NqgsEvbC9b9xobqJ_e3:b-8rcjyr) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher.go#L501)):*
> ```Go
> 
> 	if udpAddr.AddrPort().Addr().Unmap().Is4() {
> 		err := ipv4.NewPacketConn(conn).SetControlMessage(ipv4.FlagDst|ipv4.FlagInterface, true)
> ```

As far as I understand, the `FlagInterface` requests the `IfIndex` to be set, but we don't actually use that.
___
*[`dispatcher/config/config.go` line 48 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqgUe-B9qNoob1fGl67:-NqgUe-B9qNoob1fGl68:b5p03y4) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/config/config.go#L48)):*
> ```Go
> 	config.NoDefaulter
> 	// ID is the SCION element ID. This is used to choose the relevant
> 	// portion of the topology file for some services.
> ```

Nit: this does not apply here. The ID is used only for logging I think.
___
*[`dispatcher/config/config.go` line 56 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqgKXfcDNywQD53wHcj:-NqgKXfcDNywQD53wHck:b-bu2byy) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/config/config.go#L56)):*
> ```Go
> 	// topologies for their respective ASes. Normally, in a developer/testing
> 	// environment this list may contain multiple ASes.
> 	Topologies []string `toml:"topologies,omitempty"`
> ```

If I understand correctly, from these topology files we _only_ extract the information to resolve the service addresses.
I think I would prefer to directly list this information here instead, like this:

```toml
[dispatcher]
id = "dispatcher"

[dispatcher.service_addresses]
"1-ff00:0:1,CS" = "127.0.0.18:31006"
"1-ff00:0:5,CS" = "..."
```


I think this would make it much clearer what is going on and what bits of information are relevant.
In  [...]

2024-02-26 16:56 UTC, JordiSubira reviewed
> Reviewed 1 of 20 files at r9.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 198 of 232 files reviewed, 28 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, and @oncilla)

___
*[`control/cmd/control/main.go` line 586 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhTiRHCczNavBm8AlV:-Nr4wf6LCjGJlxAv7Lnm:b-aru2ey) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/control/cmd/control/main.go#L586)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

How does this relate to the dispatcher removal? Isn't this a problem that we could fix separately?
</blockquote></details>

Revisit after rebasing and move out to separate PR if applicable
___
*[`control/cmd/control/main.go` line 688 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqRZg9JDBkL8LTGaxGH:-Nr4xNBX4CylpaJxpf8j:b-aru2ey) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/control/cmd/control/main.go#L688)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

We have three types of spelling in the error messages here:

- "Hidden path"
- "HP"
- "Hidden Path"
</blockquote></details>

Revisit after rebasing and move out to separate PR if applicable
___
*[`dispatcher/dispatcher.go` line 118 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqghUXRCGokTEkNhUK7:-NrFEyEpEiAQA-vGJKnQ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher.go#L118)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Move the `validateNextHopAddr` call into the processing function, so we don't need determine which case we're in here.
For this, perhaps it makes sense to parse the control message stuff first, and pass the destination address into the `processMsgNextHop` call.
</blockquote></details>

Done.
___
*[`dispatcher/dispatcher.go` line 203 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-Nqgj_ir5roFzYG6jA06:-NrFF09F1L9uir5R16yp:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher.go#L203)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

There does not seem to be a reason to perform this packet re-serialization in the forwarding cases, we can use the unchanged input buffer.
Only the SCMP replies need to be assembled.

One idea to do this would be to restructure such that this method `processMsgNextHop` returns a `[]byte` in addition to the address. For the forwarding cases, just return `buf`. For the SCMP reply case, assemble the packet and return `s.outBuffer.Bytes()`.
</blockquote></details>

Done.
___
*[`dispatcher/dispatcher.go` line 223 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-Nqgm7Tg7wsw_L5AJxeP:-NrFFJYy-yRTzM8lUNTx:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher.go#L223)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`replyToSCMPInfoRequest`?
</blockquote></details>

Done.
___
*[`dispatcher/dispatcher.go` line 463 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhQU6WAjiJslka1mub:-NrFLTRDBy5xrpQ89ZRj:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher.go#L463)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Looks like this go routine is not needed?
</blockquote></details>

Done.
___
*[`dispatcher/dispatcher.go` line 500 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqgsFkG6R5V2nvLj9mg:-NrFNOu272gj7D795Ryp:b-4tb3lc) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher.go#L500)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

It seems a bit confusing how this interacts with dual stack IPv4/6. As far as I can tell, this should work, but I was rather confused by the setup here.
I believe, this IPv4 code path will only be taken on hosts that don't support IPv6 (because we listen on a wildcard address and with the "udp" network type).  Otherwise, the IPv6 code path will take care of both 6 and 4 (with mapped addresses).
If I got this right, the structure does not need to be changed; but perhaps this could be documented in a code comment: IPv6 includes the dual stack case, IPv4 case is only fallback for IPv4-only host.

Btw. oerhaps the appropriate control message parser (ipv4ControlMessage or ipv6ControlMessage) could be initialized here too, so we don't need to figure this out again later.
</blockquote></details>

Yes, this is what I thought. I add the documentation part.
Done.
___
*[`dispatcher/dispatcher.go` line 501 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqgsEvbC9b9xobqJ_e2:-NrGGXNK0UY_qJ8rcmB1:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher.go#L501)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

As far as I understand, the `FlagInterface` requests the `IfIndex` to be set, but we don't actually use that.
</blockquote></details>

Done.
___
*[`dispatcher/dispatcher_test.go` line 40 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqSd0kKBlL_EX2rD788:-NrGHODG2foBbW2eDEG4:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/dispatcher_test.go#L40)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Remove empty line
</blockquote></details>

Done.
___
*[`dispatcher/cmd/dispatcher/main_test.go` line 16 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRIagxAvipFJisp1uP:-NrGHkGjDBLD9S_PVbzu:b-lqdppc) ([raw file](https://github.com/scionproto/scion/blob/768a4424a0e533787bcc973c0edea4dfe1a1c1f2/dispatcher/cmd/dispatcher/main_test.go#L16)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Imo, it doesn't make sense to keep fully commented out files, we can still look up this information in the git history.
</blockquote></details>

Yes, I agree I wanted to decide whether to adapt this code for the shim dispatcher or directly remove it. I think if new tests are thought to be necessary for the shim dispatcher they can be added in the newly created `dispatcher_test.go` which already contains some test.
___
*[`dispatcher/config/config.go` line 56 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqgKXfcDNywQD53wHcj:-Nra4-k4-SU_ZGkobp_r:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/dispatcher/config/config.go#L56)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

If I understand correctly, from these topology files we _only_ extract the information to resolve the service addresses.
I think I would prefer to directly list this information here instead, like this:

```toml
[dispatcher]
id = "dispatcher"

[dispatcher.service_addresses]
"1-ff00:0:1,CS" = "127.0.0.18:31006"
"1-ff00:0:5,CS" = "..."
```


I think this would make it much clearer what is going on and what bits of information are relevant.
In the longer term, we want to change the organization of the configuration for the other services to such a style too (i.e. don't use a shared config dir and "topology.json" file, but include the relevant bits into the configuration files for the individual services).
</blockquote></details>

Done.
___
*[`dispatcher/internal/metrics/metrics.go` line 15 at r3](https://reviewable.io/reviews/scionproto/scion/4344#-NfRIt3XBJ8pZPseJuVK:-Nra66UX3l1XwyOniMeM:bqdvqsy) ( [...]

2024-02-27 16:34 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 198 of 232 files reviewed, 28 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, and @oncilla)

___
*[`acceptance/old_new_br/test.py` line 47 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhXaTJ3XqFdSI3pGt5:-NrdkLQQ4ydlA4VBh2Go:bz8zziq) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/acceptance/old_new_br/test.py#L47)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Who downloads config (copy-pasta comment?)? Maybe just use `self.await_connectivity()` instead?
</blockquote></details>

Revisit after rebasing
___
*[`pkg/snet/packet_conn.go` line 210 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhCDGKDJznmXiGuuRD:-Nrf8-QA00MLXZAqNRs6:b-7ll9qc) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/pkg/snet/packet_conn.go#L210)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Couldn't we bypass this step if the packet was received directly, i.e. not via the shim-dispatcher?
Perhaps we can look at the sender address and only do this interfaced based lookup if the packet came from localhost:endhostport?

Aside: I think it would complicate things too much to include this in the same PR, but in my opinion, we should restructure the library interface here; instead of passing this underlay address up and down through the stack, we should get rid of `snet/UDPAddr.NextHop` and do exactly this path-interface-based lookup when _writing_ the packet. 

Btw; maybe change this `readFrom` helper function to return a `netip.AddrPort`, instead of this somewhat strange output-parameter-passing with.
</blockquote></details>

Done. I agree with restructuring it, for me this is what makes more sense. As a temporary workaround I agree, here we can avoid the lookup. 
___
*[`pkg/snet/snet.go` line 184 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhJ8zp6LmXCQze7KEu:-Nren4gK89kXlyTJuqvr:brq8hd7) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/pkg/snet/snet.go#L184)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

As far as I can tell, this `svc` parameter no longer influences anything. Remove this (here and in Dial)?

Related: I wonder if we need to add checks to ensure that packets received are actually destined to us. If we add this, we might still need this `svc` -- or perhaps not, possibly this case is "filtered" out in `ResolverPacketConn`? If this resolverPacketConn deals with all the SVC address cases, we could get away with saying that the higher level `snet.Conn` does not deal with svc addresses.
</blockquote></details>

Done. I followed your suggestion and moved it within `ResolverPacketConn`
___
*[`pkg/snet/writer.go` line 89 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhIRsW7YEJuDuCwFIC:-Nrf8RykDxXEPDGFuqKr:b-o1at2x) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/pkg/snet/writer.go#L89)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The overhead of this must be enormous. Note that previously, wildcard bind addresses have simply been forbidden. I'm not sure it makes sense to support this at all if it involves such an overhead. To do this "properly", we'd have to keep a copy of the system's routing table and keep this up to date by subscribing to changes to it -- in Linux this can be done with netlink, but it would be quite a project on it's own...

If you revert this, please also move the `ResolveLocal` function back to `addrutil`.
</blockquote></details>

Done. Indeed, I just wanted to provide a workaround for unspecified addresses. Although, I agree if we do it, we should do it in a more sensible way. 


<!-- Sent from Reviewable.io -->

2024-03-05 10:31 UTC, matzf reviewed
> Reviewed 4 of 34 files at r10, 1 of 20 files at r11, 1 of 20 files at r12.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 178 of 234 files reviewed, 13 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, @marcfrei, and @oncilla)

___
*[`dispatcher/dispatcher.go` line 428 at r12](https://reviewable.io/reviews/scionproto/scion/4344#-NsCyf9J13W6ZerIu8as:-NsCyf9J13W6ZerIu8at:br1tl5n) ([raw file](https://github.com/scionproto/scion/blob/8b957f4eeda9e58fc287750b333d28c585425626/dispatcher/dispatcher.go#L428)):*
> ```Go
> // UDP/SCION header. This refers to the safeguard for traffic reflection as discussed in:
> // https://github.com/scionproto/scion/pull/4280#issuecomment-1775177351
> func (s *Server) parseUnderlayAddr(oobuffer []byte) *netip.Addr {
> ```

Nit: `netip.Addr` is designed to be passed by value (so it avoids heap allocations). Use `.IsValid()` instead of `== nil`.
___
*[`dispatcher/config/config.go` line 84 at r12](https://reviewable.io/reviews/scionproto/scion/4344#-NsD7LsYC6ekrZ0aRljC:-NsD7LsYC6ekrZ0aRljD:by1uo8k) ([raw file](https://github.com/scionproto/scion/blob/8b957f4eeda9e58fc287750b333d28c585425626/dispatcher/config/config.go#L84)):*
> ```Go
> 	ID                     string            `toml:"id,omitempty"`
> 	ServiceAddresses       map[string]string `toml:"service_addresses,omitempty"`
> 	ParsedServiceAddresses map[addr.Addr]netip.AddrPort
> ```

With go-toml v2, this map can be marshalled directly. I'll merge #4342, then you can simplify this after rebasing. The custom parsing routine can go away too, only a check for `a.Host.Type() == addr.HostTypeSvc` in the `Validate` is left to do.



_Suggestion:_
```Go
	ServiceAddresses map[addr.Addr]netip.AddrPort `toml:"service_addresses,omitempty"`
```


<!-- Sent from Reviewable.io -->

2024-03-08 10:17 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 155 of 242 files reviewed, 13 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, and @oncilla)

___
*[`control/cmd/control/main.go` line 586 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhTiRHCczNavBm8AlV:-NsSIQ4B4UvP4iZrs2Pc:b-oesrzq) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/control/cmd/control/main.go#L586)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Revisit after rebasing and move out to separate PR if applicable
</blockquote></details>

I took a look at https://github.com/scionproto/scion/pull/4376 and IIUC this PR would not work with that modification of the address binding for the resolver and the CS,DS service sockets. The `initSVCredirect` socket listens now on a dynamic port, which works fine, because it is registered into the "old" dispatcher, which then intercepts requests addresses to some SVC address and passes it through the socket that register for the concrete SVC. However, now the BR will send the messages with SVC addresses to the port specified in the `topology.json`. Therefore, this has to be changed in any case for this PR to work, while doing it first in a separate PR, in which the BR still behaves like the "old" BR seems a bit weird. My suggestion is that we merge this PR with the current solution and we discuss in a new one how to improve this. As you guys have pointed out previously, in any case, the SVC resolution mechanism should be refactor, so I guess those changes can be part of the future PR.


<!-- Sent from Reviewable.io -->

2024-03-11 08:26 UTC, matzf requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 155 of 242 files reviewed, 13 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, @marcfrei, and @oncilla)

___
*[`control/cmd/control/main.go` line 586 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhTiRHCczNavBm8AlV:-NsgTGMA-rkbnnGisH6p:b-d7wu1q) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/control/cmd/control/main.go#L586)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I took a look at https://github.com/scionproto/scion/pull/4376 and IIUC this PR would not work with that modification of the address binding for the resolver and the CS,DS service sockets. The `initSVCredirect` socket listens now on a dynamic port, which works fine, because it is registered into the "old" dispatcher, which then intercepts requests addresses to some SVC address and passes it through the socket that register for the concrete SVC. However, now the BR will send the messages with SVC addresses to the port specified in the `topology.json`. Therefore, this has to be changed in any case for this PR to work, while doing it first in a separate PR, in which the BR still behaves like the "old" BR seems a bit weird. My suggestion is that we merge this PR with the current solution and we discuss in a new one how to improve this. As you guys have pointed out previously, in any case, the SVC resolution mechanism should be refactor, so I guess those changes can be part of the future PR.
</blockquote></details>

One way to make this work is to unify the addresses; use the same (underlay) port for the SVC CS address, and QUIC (both  UDP and UDP/SCION port). We only open a single underlay socket for both the QUIC server and the SVC redirector. As you've already created (or kept) the "ResolverPacketConn` as a wrapper around the normal connection, we can just plug this under the QUIC server. (To keep backwards compat, we can optionally open two separate sockets, if quic.Address != public address. Unsure if this is useful, possibly this is the right time to cut out the quic.address config option instead.)
This may look different, but on the underlay this is very close to what we had before; previously, this was demuxed in the dispatcher, now the application has to do it manually.

Generally, I think it makes sense to allow binding the hidden path service on a separate address, but it seems like this is not strictly necessary here.


<!-- Sent from Reviewable.io -->

2024-03-11 08:48 UTC, JordiSubira commented
> > _[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)_ status: 155 of 242 files reviewed, 13 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, @marcfrei, and @oncilla)
> 
> _[`control/cmd/control/main.go` line 586 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhTiRHCczNavBm8AlV:-NsgTGMA-rkbnnGisH6p:b-d7wu1q) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/control/cmd/control/main.go#L586)):_
> Previously, JordiSubira wrote…
> 
> One way to make this work is to unify the addresses; use the same (underlay) port for the SVC CS address, and QUIC (both UDP and UDP/SCION port). We only open a single underlay socket for both the QUIC server and the SVC redirector. As you've already created (or kept) the "ResolverPacketConn` as a wrapper around the normal connection, we can just plug this under the QUIC server. (To keep backwards compat, we can optionally open two separate sockets, if quic.Address != public address. Unsure if this is useful, possibly this is the right time to cut out the quic.address config option instead.) This may look different, but on the underlay this is very close to what we had before; previously, this was demuxed in the dispatcher, now the application has to do it manually.
> 
> Generally, I think it makes sense to allow binding the hidden path service on a separate address, but it seems like this is not strictly necessary here.

Yes, I guess this would work. However, was there any reason for having a dynamic port for the QUIC server originally, instead of only registering one socket (with the `ResolverPacketConn` wrapper) with the dispatcher and use it for both?

2024-03-11 16:06 UTC, matzf requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 155 of 242 files reviewed, 13 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, @marcfrei, and @oncilla)

___
*[`control/cmd/control/main.go` line 586 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhTiRHCczNavBm8AlV:-NsiA6v4-QgV5fk321sm:b-4utl0q) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/control/cmd/control/main.go#L586)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Yes, I guess this would work. However, was there any reason for having a dynamic port for the QUIC server originally, instead of only registering one socket (with the `ResolverPacketConn` wrapper) with the dispatcher and use it for both?
</blockquote></details>

It's a long story, but as far as I know there is no strong reason left to keep them separate. 

A brief history of ~~time~~infraenv.go (I wasn't personally involved with most things though, so no guarantees on accuracy).
- once upon a time, the message based request (capn-proto) were done directly with SVC addresses, thus there was only a single socket
- then quic (grpc) was added; the message based request handling was left as backwards compatibility; a new request was added to resolve the SVC address to a "quic address" where the actual new RPC would happen.
- at that time, for QUIC a dynamic port was used, the message based requests used a statically assigned port  (which is however unused with SVC addressing).
- the old message based requests were removed, only the SVC resolver was left (because its used to initiate the QUIC connection)
- during #4376, it was discovered that the discovery service needs to know statically the port of the QUIC socket (because of hiddenpaths). As a solution, the ports used for SVC resolution (was static, now dynamic) and QUIC (was dynamic, now static) were swapped.
- alternatively, at that point we could have combined the two sockets; but we didn't have to and it seemed like a smaller change


<!-- Sent from Reviewable.io -->

2024-03-18 08:44 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 146 of 249 files reviewed, 10 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, and @oncilla)

___
*[`control/cmd/control/main.go` line 586 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhTiRHCczNavBm8AlV:-NtFikh7AJEd9G3Ksu8F:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/control/cmd/control/main.go#L586)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

It's a long story, but as far as I know there is no strong reason left to keep them separate. 

A brief history of ~~time~~infraenv.go (I wasn't personally involved with most things though, so no guarantees on accuracy).
- once upon a time, the message based request (capn-proto) were done directly with SVC addresses, thus there was only a single socket
- then quic (grpc) was added; the message based request handling was left as backwards compatibility; a new request was added to resolve the SVC address to a "quic address" where the actual new RPC would happen.
- at that time, for QUIC a dynamic port was used, the message based requests used a statically assigned port  (which is however unused with SVC addressing).
- the old message based requests were removed, only the SVC resolver was left (because its used to initiate the QUIC connection)
- during #4376, it was discovered that the discovery service needs to know statically the port of the QUIC socket (because of hiddenpaths). As a solution, the ports used for SVC resolution (was static, now dynamic) and QUIC (was dynamic, now static) were swapped.
- alternatively, at that point we could have combined the two sockets; but we didn't have to and it seemed like a smaller change
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-20 16:12 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 146 of 249 files reviewed, 6 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, and @oncilla)

___
*[`acceptance/old_new_br/test.py` line 47 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhXaTJ3XqFdSI3pGt5:-NtRcd4mEZNJw3LOF9PC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/acceptance/old_new_br/test.py#L47)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Revisit after rebasing
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-22 09:27 UTC, matzf requested changes
> Reviewed 23 of 183 files at r1, 25 of 81 files at r2, 3 of 29 files at r3, 3 of 12 files at r4, 8 of 73 files at r8, 4 of 20 files at r9, 7 of 34 files at r10, 11 of 20 files at r11, 17 of 20 files at r12, 21 of 38 files at r13, 17 of 19 files at r14, 7 of 7 files at r15, 10 of 10 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 237 of 249 files reviewed, 30 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, @marcfrei, and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_7SCr00URpuCbtI8c:-Nt_7SCs6iNcdQRXoWUA:by153tj) (no related file):*
In the "cooked" `snet.Conn`, in `snet/reader.go`:`func read()`, we should now probably add a check to ensure that the packet that was read is destined to "us". This was previously done by the dispatcher (i _think_), but now it's possible that we receive SCION/UDP packets to our underlay port that have a different SCION destination address or destination port.

___
___
*[`acceptance/common/docker.py` line 66 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtVAn9c3skMAOT_kpne:-NtVAn9c3skMAOT_kpnf:b-c5az3i) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/acceptance/common/docker.py#L66)):*
> ```Python
>             print(svc)
>             with open(dst_f, "w") as log_file:
>                 cmd.docker.run(args=("logs", "scion-"+svc+"-1"), stdout=log_file,
> ```

Nit: good catch, but prefer to invoke docker _compose_ instead of mangling the name.
The `print` above is probably a debug left over?
___
*[`acceptance/hidden_paths/test.py` line 104 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtVBuCf8pbBoHVqfOw7:-NtVBuCf8pbBoHVqfOw8:b-wx14cn) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/acceptance/hidden_paths/test.py#L104)):*
> ```Python
>                     control_service_addr,
>             }
>             topology_file = as_dir_path / "topology.json"
> ```

No-op, does not seem to change variable.
___
*[`acceptance/old_new_br/test.py` line 16 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtWx_nhBYUy8eyaw1WD:-NtWx_nhBYUy8eyaw1WE:b-iyi6yr) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/acceptance/old_new_br/test.py#L16)):*
> ```Python
>     endhost default port) and routers with the new behaviour (i.e., they
>     will rewrite the underlay UDP/IP destination port with the UDP/SCION
>     port).
> ```

Nit: terminology and name: "old" and "new" will quickly become unclear outside the context of this PR. Maybe should find descriptive names for the two modes. Idea: "router port dispatch" vs "endhost port dispatch"?
___
*[`acceptance/old_new_br/test.py` line 25 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtWxToO2rV0EblhN-FP:-NtWxToO2rV0EblhN-FQ:undefined) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/acceptance/old_new_br/test.py#L25)):*
> ```Python
>     AS1 contains a BR with the port rewriting configuration to the default
>     range. It also includes a shim dispatcher.
>     AS2 contains a BR with a configuration that reassembles the old
> ```





_Suggestion:_
```Python
resembles
```
___
*[`acceptance/sig_short_exp_time/testdata/1-ff00_0_110/dispatcher/disp.toml` line 5 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_D1v76DtAHpxTGrRq:-Nt_D1v76DtAHpxTGrRr:b-rw4ojz) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/acceptance/sig_short_exp_time/testdata/1-ff00_0_110/dispatcher/disp.toml#L5)):*
> ```TOML
> 
> [log.console]
> level = "debug"
> ```

Nit: whitespace (missing newline at end of file)
___
*[`acceptance/sig_short_exp_time/testdata/1-ff00_0_111/dispatcher/disp.toml` line 5 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_DZAREIzX-VWPdDqi:-Nt_DZAS0G8Mojm9nUuU:b-85utc9) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/acceptance/sig_short_exp_time/testdata/1-ff00_0_111/dispatcher/disp.toml#L5)):*
> ```TOML
> 
> [log.console]
> level = "debug"
> ```

Nit: whitespace
___
*[`control/cmd/control/main.go` line 944 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtWTLoe32duNScty3K8:-NtWTLof2F3F9TP47bXe:b8o9qmr) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/control/cmd/control/main.go#L944)):*
> ```Go
> 	for i, v := range ifMap {
> 		if i > (1<<16)-1 {
> 			return nil, serrors.New("Invalid interface id", "id", i)
> ```

Shouldn't this check just be in the topology file parser or wherever this comes from?
___
*[`dispatcher/dispatcher_test.go` line 84 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_EY-X1nIik9G3fq6c:-Nt_EY-X1nIik9G3fq6d:bo65kor) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/dispatcher/dispatcher_test.go#L84)):*
> ```Go
> 						IA:   xtest.MustParseIA("1-ff00:0:2"),
> 						Host: addr.HostIP(clientAddr.AddrPort().Addr()),
> 					},
> ```

This test setup can be much more concise if we consistently only use the `netip.Addr` and `pkg/addr.Addr` types. Convert to `net.UDPAddr` only at the last moment (with `net.UDPAddrFromAddrPort()`).
___
*[`pkg/snet/snet.go` line 52 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhGGXn3Ct6t1RhF9Jc:-NtWcCUI77Le6lFaUaDJ:bcmp65f) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/pkg/snet/snet.go#L52)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I changed it by CPInfoProvider, not the best name, but more descriptive I guess...
</blockquote></details>

Thinking about this NAME again; isn't this  (snet's view of) the `Topology`? 
Perhaps we could also add the `LocalIA(ctx)`, so there is one fewer things that need to be initialized in the `SCIONNEtwork`?
___
*[`pkg/snet/snet.go` line 101 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqSLV-M3MiJvn32R13G:-NtW_kL5DWqxs7tYO9pf:b-mu9d8l) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/pkg/snet/snet.go#L101)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

This is somehow aligned with the model discussed here: https://github.com/matzf/scion/blob/doc-endhost-overview/doc/dev/design/endhost-overview.rst?plain=1#L92-L102. The main reason is that we do not want to trigger the `CPInfoProvider`, which will in turn make a request to the Daemon, for every read operation. This getLastHopAddr callbacks basically hides this interface->Addr mapping within snet for the callers. If I misunderstood your point, please let me know :)
</blockquote></details>

We could still make `ifAddrs` a field of `SCIONPacketConn` and a separate function `func getLastHop(ifAddrs map[uint16]*net.UDPAddr, id uint16) (*net.UDPAddr, error)` ; or make this a `type interfaceMap map[uint16]*UDPAddr` and `func (m interfaceMap) get(id uint16) (*net.UDPAddr, error)`.
___
*[`pkg/snet/snet.go` line 57 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtWd6nKBqCoklsbnGj4:-NtWd6nKBqCoklsbnGj5:brfph4i) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/pkg/snet/snet.go#L57)):*
> ```Go
> }
> 
> type Connector interface {
> ```

This is slightly tangential as you've translated the previous organisation with the "dispatcher" object into this connector. But perhaps this could be a chance to take this a bit further; I wonder if we could get rid of this interface altogether; the only use case for providing an alternative implementation appears to be wrapping  the `PacketConn`, as is done with `ResolverPacketConnector`.
What about this idea: we remove the `Connector` from `SCIONNetwork`. The `DefaultConnector.OpenUDP(...)` is added as  [...]

2024-03-22 12:03 UTC, tzaeschke reviewed
> Reviewed 84 of 183 files at r1, 29 of 81 files at r2, 7 of 29 files at r3, 3 of 12 files at r4, 15 of 73 files at r8, 5 of 20 files at r9, 10 of 34 files at r10, 14 of 20 files at r11, 19 of 20 files at r12, 28 of 38 files at r13, 17 of 19 files at r14, 7 of 7 files at r15, 10 of 10 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 37 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, @marcfrei, and @oncilla)

___
*[`pkg/snet/snet.go` line 179 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nta0KuEDfCmHXAvpo5T:-Nta0KuEDfCmHXAvpo5U:undefined) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/pkg/snet/snet.go#L179)):*
> ```Go
> // Listen opens a Conn. The returned connection's ReadFrom and WriteTo methods
> // can be used to receive and send SCION packets with per-packet addressing.
> // Parameter network must be "udp". If listen is unspecified address a suitable address
> ```





_Suggestion:_
```Go
 If listen is unspecified a suitable address
```
___
*[`private/topology/interface.go` line 45 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_xuPD88cGR2vEr_R7:-Nt_xuPD88cGR2vEr_R8:undefined) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/topology/interface.go#L45)):*
> ```Go
> 	// PortRange returns the first and last ports of the port range (both included),
> 	// in which endhost listen for SCION/UDP applicaction using the underlay UDP/IP
> 	// underlay.
> ```





_Suggestion:_
```Go
	// in which endhost listen for SCION/UDP applicaction using the UDP/IP underlay.
	
```
___
*[`private/topology/topology.go` line 229 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nta-lbA6uNFuLvD3a07:-Nta-lbA6uNFuLvD3a08:undefined) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/topology/topology.go#L229)):*
> ```Go
> 	ports := strings.Split(portRange, "-")
> 	if len(ports) != 2 {
> 		return 0, 0, serrors.New("invalid format: expected startPort-endPort", "got", portRange)
> ```





_Suggestion:_
```Go
Invalid
```
___
*[`private/topology/topology.go` line 234 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_yiTcB7ZZi-29V8bw:-Nt_yiTcB7ZZi-29V8bx:undefined) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/topology/topology.go#L234)):*
> ```Go
> 	endPort, errEnd := strconv.Atoi(ports[1])
> 	if errStart != nil || errEnd != nil {
> 		return 0, 0, serrors.New("invalid port numbers", "got", portRange)
> ```





_Suggestion:_
```Go
Invalid
```
___
*[`router/dataplane.go` line 2034 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_z1bJ3tCW53Cdv7zY:-Nt_z1bJ3tCW53Cdv7zZ:b45h) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/router/dataplane.go#L2034)):*
> ```Go
> 		if err != nil {
> 			// TODO(JordiSubira): Treat this as a parameter problem.
> 			return nil, serrors.WrapStr("decoding scmp layer for extracting endhost dst port", err)
> ```





_Suggestion:_
```Go
SCMP
```
___
*[`router/dataplane_test.go` line 1537 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_zn8A8vNxVVDraPdQ:-Nt_zn8A8vNxVVDraPdR:undefined) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/router/dataplane_test.go#L1537)):*
> ```Go
> 	payload := []byte("actualpayloadbytes")
> 	err := gopacket.SerializeLayers(buffer, gopacket.SerializeOptions{FixLengths: true},
> 		spkt, scionudpLayer, gopacket.Payload(payload))
> ```





_Suggestion:_
```Go
	scionUdpLayer := &slayers.UDP{}
	scionUdpLayer.SrcPort = uint16(srcUDPPort)
	scionUdpLayer.DstPort = uint16(dstUDPPort)
	scionUdpLayer.SetNetworkLayerForChecksum(spkt)
	payload := []byte("actualpayloadbytes")
	err := gopacket.SerializeLayers(buffer, gopacket.SerializeOptions{FixLengths: true},
		spkt, scionUdpLayer, gopacket.Payload(payload))
```
___
*[`router/dataplane_test.go` line 1558 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_ztCU-J3R_KUYCVIV:-Nt_ztCU-J3R_KUYCVIW:undefined) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/router/dataplane_test.go#L1558)):*
> ```Go
> 		SrcIA:        xtest.MustParseIA("2-ff00:0:222"),
> 		Path:         &scion.Raw{},
> 		PayloadLen:   26, // scionudpLayer + len("actualpayloadbytes")
> ```





_Suggestion:_
```Go
scionUdpLaye
```


<!-- Sent from Reviewable.io -->

2024-03-26 16:42 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 229 of 250 files reviewed, 31 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`acceptance/common/docker.py` line 66 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtVAn9c3skMAOT_kpne:-NtaRLwb02McEm_FNEuN:bd0m6vm) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/acceptance/common/docker.py#L66)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: good catch, but prefer to invoke docker _compose_ instead of mangling the name.
The `print` above is probably a debug left over?
</blockquote></details>

I shouldn't have pushed this... it was suppose to be a local change for debugging and we would sort this out in a separate commit that fixes https://github.com/scionproto/scion/issues/4473. I'll remove it and we can fix it aside. 
___
*[`acceptance/hidden_paths/test.py` line 104 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtVBuCf8pbBoHVqfOw7:-NtaRxV6Dbyu4chnShNj:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/acceptance/hidden_paths/test.py#L104)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

No-op, does not seem to change variable.
</blockquote></details>

Done.
___
*[`control/cmd/control/main.go` line 944 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtWTLoe32duNScty3K8:-NtqM6v_6kGIHvdQNxfL:b83ayeo) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/control/cmd/control/main.go#L944)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Shouldn't this check just be in the topology file parser or wherever this comes from?
</blockquote></details>

Yes, it should. However, here https://github.com/scionproto/scion/blob/master/private/topology/json/json.go#L96 it still uses the deprecated IFIDType. Then either we change it in the topology parser or I create a [uint64]net.UDPAddr. At the moment, we never configure interfaces bigger than 2^16-1, so it would make more sense to change this directly into the `json.go`. If we change the topology parsing, should I do it in this PR?
___
*[`pkg/snet/snet.go` line 52 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhGGXn3Ct6t1RhF9Jc:-Ntuy78zBrd7j97L9GNC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/pkg/snet/snet.go#L52)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Thinking about this NAME again; isn't this  (snet's view of) the `Topology`? 
Perhaps we could also add the `LocalIA(ctx)`, so there is one fewer things that need to be initialized in the `SCIONNEtwork`?
</blockquote></details>

Done.
___
*[`pkg/snet/snet.go` line 179 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nta0KuEDfCmHXAvpo5T:-Ntab_ws5TmtSadCkGOJ:b9ursue) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/pkg/snet/snet.go#L179)):*
> ```Go
> // Listen opens a Conn. The returned connection's ReadFrom and WriteTo methods
> // can be used to receive and send SCION packets with per-packet addressing.
> // Parameter network must be "udp". If listen is unspecified address a suitable address
> ```

Done. The comment doesn't apply anymore.
___
*[`private/app/appnet/infraenv.go` line 226 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtVc_Ay332BNKZbiDcR:-NtacoQoBqwmEFQUxGxN:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/app/appnet/infraenv.go#L226)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Dead code.
</blockquote></details>

Done.
___
*[`private/topology/interface.go` line 44 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_KwAw6M8S7HnECg_u:-Ntadkf53K0sFZJxzB6W:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/topology/interface.go#L44)):*
> ```Go
> 	InterfaceIDs() []common.IFIDType
> 	// PortRange returns the first and last ports of the port range (both included),
> 	// in which endhost listen for SCION/UDP applicaction using the underlay UDP/IP
> ```

Done.
___
*[`private/topology/interface.go` line 45 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_xuPD88cGR2vEr_R7:-Ntadl1m3S4Opn7ndY82:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/topology/interface.go#L45)):*
> ```Go
> 	// PortRange returns the first and last ports of the port range (both included),
> 	// in which endhost listen for SCION/UDP applicaction using the underlay UDP/IP
> 	// underlay.
> ```

Done.
___
*[`private/topology/topology.go` line 229 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nta-lbA6uNFuLvD3a07:-NtadtlS-1GBlxGNZqp6:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/topology/topology.go#L229)):*
> ```Go
> 	ports := strings.Split(portRange, "-")
> 	if len(ports) != 2 {
> 		return 0, 0, serrors.New("invalid format: expected startPort-endPort", "got", portRange)
> ```

Done.
___
*[`private/topology/topology.go` line 232 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtVwYRW9_18wK3Q4FYd:-NtafgPJ1qMns0kl-zvw:b-i4w4nm) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/topology/topology.go#L232)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Use `strconv.ParseUInt(x, 10, 16)`, which already includes the 16 bit range checks below.
</blockquote></details>

Done. I am still keeping the check for not allowing to set port 0 as a valid starting port in the topology. Port 0 may be confusing in this context and we should also check afterwards that we do not assign it in the `listenUDPRange()`.
___
*[`private/topology/topology.go` line 234 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_yiTcB7ZZi-29V8bw:-NtaduGt9OltL7i81pbQ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/topology/topology.go#L234)):*
> ```Go
> 	endPort, errEnd := strconv.Atoi(ports[1])
> 	if errStart != nil || errEnd != nil {
> 		return 0, 0, serrors.New("invalid port numbers", "got", portRange)
> ```

Done.
___
*[`router/dataplane.go` line 2034 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_z1bJ3tCW53Cdv7zY:-NtarJiQ5E6K-pvzN7Cu:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/router/dataplane.go#L2034)):*
> ```Go
> 		if err != nil {
> 			// TODO(JordiSubira): Treat this as a parameter problem.
> 			return nil, serrors.WrapStr("decoding scmp layer for extracting endhost dst port", err)
> ```

Done.
___
*[`router/dataplane_test.go` line 1537 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_zn8A8vNxVVDraPdQ:-NtarrERAYx08MPiX2fR:b-p30yoo) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/router/dataplane_test.go#L1537)):*
> ```Go
> 	payload := []byte("actualpayloadbytes")
> 	err := gopacket.SerializeLayers(buffer, gopacket.SerializeOptions{FixLengths: true},
> 		spkt, scionudpLayer, gopacket.Payload(payload))
> ```

In several other places in the code we use `scionudp`, I'll keep it for consistency
___
*[`router/dataplane_test.go` line 1558 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_ztCU-J3R_KUYCVIV:-Ntas1XBDQjtUAiGfAS9:b-p30yoo) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/router/dataplane_test.go#L1558)):*
> ```Go
> 		SrcIA:        xtest.MustParseIA("2-ff00:0:222"),
> 		Path:     [...]

2024-03-27 06:54 UTC, lukedirtwalker requested changes
> Reviewed 61 of 183 files at r1, 16 of 81 files at r2, 4 of 29 files at r3, 2 of 73 files at r8, 1 of 20 files at r9, 6 of 20 files at r11, 5 of 38 files at r13, 1 of 19 files at r14, 5 of 10 files at r16, 6 of 17 files at r18, 3 of 19 files at r19.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 234 of 250 files reviewed, 46 unresolved discussions (waiting on @JordiSubira, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`pkg/snet/packet_conn.go` line 200 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Nty_ASh1n-4bHGOpNrQ:-Nty_ASh1n-4bHGOpNrR:byx2vyh) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L200)):*
> ```Go
> 	if err != nil {
> 		metrics.CounterInc(c.Metrics.UnderlayConnectionErrors)
> 		return nil, serrors.WrapStr("Reliable socket read error", err)
> ```

I think this error message is now wrong, didn't we remove the reliable socket?



_Suggestion:_
```Go
"reading underlay connection", err
```
___
*[`pkg/snet/packet_conn.go` line 246 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Ntyaroo1u7CaOzeNDwu:-Ntyaroo1u7CaOzeNDwv:bzb7a74) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L246)):*
> ```Go
> 
> func (c *SCIONPacketConn) lastHop(p *Packet) (*net.UDPAddr, error) {
> 	rpath, ok := p.Path.(RawPath)
> ```

why the extra handling of this case? couldn't you simply let it run in the default case in the switch below?
___
*[`pkg/snet/packet_conn.go` line 248 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Ntyb-oWCif5RLQSXMVH:-Ntyb-oWCif5RLQSXMVI:undefined) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L248)):*
> ```Go
> 	rpath, ok := p.Path.(RawPath)
> 	if !ok {
> 		return nil, serrors.New("Unexpected path", "type", common.TypeOf(p.Path))
> ```





_Suggestion:_
```Go
"raw path type not supported"
```
___
*[`pkg/snet/packet_conn.go` line 253 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Ntyb7ty7ao0rR5oEYFK:-Ntyb7ty7ao0rR5oEYFL:undefined) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L253)):*
> ```Go
> 	case empty.PathType:
> 		if p.Source.Host.Type() != addr.HostTypeIP {
> 			return nil, serrors.New("Unexpected source address in packet",
> ```





_Suggestion:_
```Go
unexpected source address in packet
```
___
*[`pkg/snet/packet_conn.go` line 269 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Ntybn5S9UHtRifZ8J89:-Ntybn5S9UHtRifZ8J8A:bbn0hkf) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L269)):*
> ```Go
> 			IP:   p.Source.Host.IP().AsSlice(),
> 			Port: port,
> 		}, nil
> ```

I would use an anonymous function to make the code slightly cleaner. Also I don't think we need to special case the SCMPPayload



_Suggestion:_
```Go
		return &net.UDPAddr{
			IP: p.Source.Host.IP().AsSlice(),
			Port: func() int {
				switch p := p.PacketInfo.Payload.(type) {
				case UDPPayload:
					return int(p.SrcPort)
				default:
					// Use endhost port for SCMP and unknown payloads.
					return underlay.EndhostPort
				}
			}(),
		}, nil
```
___
*[`pkg/snet/packet_conn.go` line 275 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtycCbJ71uNnS-caddv:-NtycCbJ71uNnS-caddw:bnx59jz) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L275)):*
> ```Go
> 		if err != nil {
> 			return nil, err
> 		}
> ```

Use short circuit version



_Suggestion:_
```Go
		if err := path.DecodeFromBytes(rpath.Raw); err != nil {
			return nil, err
		}
```
___
*[`pkg/snet/packet_conn.go` line 284 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtycNKQ81jDQoFyE14j:-NtycNKQ81jDQoFyE14k:bnx59jz) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L284)):*
> ```Go
> 		var path epic.Path
> 		err := path.DecodeFromBytes(rpath.Raw)
> 		if err != nil {
> ```

Use short circuit version



_Suggestion:_
```Go
		if err := path.DecodeFromBytes(rpath.Raw); err != nil {
```
___
*[`pkg/snet/packet_conn.go` line 305 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtycYsz1YA7cUCQtpOP:-NtycYsz1YA7cUCQtpOQ:b-js4aqu) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L305)):*
> ```Go
> 		if err != nil {
> 			return nil, err
> 		}
> ```

combine



_Suggestion:_
```Go
		if err := path.DecodeFromBytes(rpath.Raw); err != nil {
			return nil, err
		}
```
___
*[`pkg/snet/packet_conn.go` line 320 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Nty_15a-qxWNplAXUdE:-Nty_15a-qxWNplAXUdF:b-sn5x5u) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L320)):*
> ```Go
> 		return c.interfaceMap.get(ifid)
> 	default:
> 		return nil, serrors.New("Unknown type", "type", rpath.PathType.String())
> ```

Errors should not start with capital letter.



_Suggestion:_
```Go
"unknown path type", "type", rpath.PathType.String()
```
___
*[`pkg/snet/packet_conn.go` line 344 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtyZp-k1PPeMxR5IEgj:-NtyZp-k1PPeMxR5IEgk:b-sn5x5u) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L344)):*
> ```Go
> 	addr, ok := m[id]
> 	if !ok {
> 		return nil, serrors.New("Interface number not found", "if", id)
> ```

Errors should not start with capital letter.



_Suggestion:_
```Go
"interface number not found", "interface", id
```
___
*[`pkg/snet/snet.go` line 52 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhGGXn3Ct6t1RhF9Jc:-NtyfVIB5-zBkaXbWh0Q:b22l4mx) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/pkg/snet/snet.go#L52)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Does the LocalIA on this interface mean we always call out (via RPC) to the daemon?
___
*[`pkg/snet/snet.go` line 76 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtydmKa786NvycdnHD6:-NtydmKa786NvycdnHD7:undefined) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/snet.go#L76)):*
> ```Go
> 	var err error
> 	if addr == nil || addr.IP.IsUnspecified() {
> 		return nil, serrors.New("Nil or unspecified address is not permitted")
> ```





_Suggestion:_
```Go
nil or unspecified address is not permitted
```
___
*[`pkg/snet/snet.go` line 92 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtydxaKD9zWt2Gri5uN:-NtydxaKD9zWt2Gri5uO:undefined) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/snet.go#L92)):*
> ```Go
> 		// port range for the endhost.
> 		if addr.Port < int(start) || addr.Port > int(end) {
> 			return nil, serrors.New("Provided port is outside the SCION/UDP range",
> ```





_Suggestion:_
```Go
provided 
```
___
*[`pkg/snet/snet.go` line 121 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtyeMmp1bbwX_r_ly0k:-NtyeMmp1bbwX_r_ly0l:b-flhuq6) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/snet.go#L121)):*
> ```Go
> 			}
> 			continue
> 		}
> ```

I would slightly re-order this code, it has a bit less nesting and returns early in the happy path.



_Suggestion:_
```Go
		if err == nil {
			return pconn, nil
		}
		if errors.Is(err, syscall.EADDRINUSE) {
			continue
		}
		return nil, err
```
___
*[`pkg/snet/writer.go` line 62 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtyYn2AC0mwHNc8kwKs:-NtyYn2AC0mwHNc8kwKt:bkfh7h2) ([raw file](https://github.com/scionproto/s [...]

2024-03-27 13:31 UTC, lukedirtwalker requested changes
> Reviewed 22 of 183 files at r1, 11 of 81 files at r2, 3 of 29 files at r3, 1 of 12 files at r4, 10 of 73 files at r8, 3 of 20 files at r9, 5 of 34 files at r10, 2 of 20 files at r11, 17 of 20 files at r12, 19 of 38 files at r13, 15 of 19 files at r14, 7 of 7 files at r15, 2 of 10 files at r16, 7 of 17 files at r18, 16 of 19 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 55 unresolved discussions (waiting on @JordiSubira, @marcfrei, @matzf, @oncilla, and @tzaeschke)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4344#-NtzzLA4CTQFPcyw40ju:-NtzzLA4CTQFPcyw40jv:b-upjmpi) (no related file):*
Overall: error messages should not start with capital letter, there are many instances where this rule is violated.

___
___
*[`acceptance/hidden_paths/test.py` line 95 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-0umTBStJq6WDpuDk:-Nu-0umTBStJq6WDpuDl:b-pnskwe) ([raw file](https://github.com/scionproto/scion/blob/4a8bc98ec7d969dd622c5a90fe677e3c980aaa88/acceptance/hidden_paths/test.py#L95)):*
> ```Python
>             as_dir_path = self.artifacts / "gen" / ("ASff00_0_%s" % as_number)
> 
>             # The hidden_segment services are behind the same server as the control_service.
> ```

maybe also revert this change and this file doesn't change at all in this PR.
___
*[`acceptance/topo_cs_reload/docker-compose.yml` line 19 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-1AjT9uPRodMbKRUS:-Nu-1AjT9uPRodMbKRUT:bbvnzz6) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/acceptance/topo_cs_reload/docker-compose.yml#L19)):*
> ```YAML
>       bridge1:
>         ipv4_address: 242.253.100.2
> version: '2.4'
> ```

add a newline at the end of the file
___
*[`acceptance/topo_daemon_reload/docker-compose.yml` line 20 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-1G8317ua8J3s0yic:-Nu-1G8317ua8J3s0yid:b-7rfc1p) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/acceptance/topo_daemon_reload/docker-compose.yml#L20)):*
> ```YAML
> version: '2.4'
> volumes:
>   vol_topo_daemon_reload_certs: null
> ```

add newline at the end of the file
___
*[`acceptance/trc_update/test.py` line 87 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Ntyqnev4k098KCHAQmp:-Ntyqnev4k098KCHAQmq:bejo1y6) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/acceptance/trc_update/test.py#L87)):*
> ```Python
>         for cs in cs_services:
>             self.dc.start_container(cs)
>         time.sleep(20)
> ```

why do we need to increase that so much?
___
*[`dispatcher/dispatcher.go` line 40 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-51zz-FsSNL00x-0d:-Nu-51zz-FsSNL00x-0e:bla08hy) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/dispatcher/dispatcher.go#L40)):*
> ```Go
> // from legacy BR to the final endhost application and to handle SCMP
> // info packets destined to this endhost.
> type Server struct {
> ```

I wonder if we should have a flag to only reply to SCMP Info messages. And in that mode everything else would be dropped? Basically that is then the leftover application once all routers in an AS have migrated. Or am I missing something?
___
*[`dispatcher/config/config.go` line 84 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-3-5p8vOy6vQ_awG_:-Nu-3-5p8vOy6vQ_awGa:bkli3bm) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/dispatcher/config/config.go#L84)):*
> ```Go
> 	ServiceAddresses map[addr.Addr]netip.AddrPort `toml:"service_addresses,omitempty"`
> 	// UnderlayPort is the native port opened by the dispatcher (default 30041)
> 	UnderlayPort int `toml:"underlay_port,omitempty"`
> ```

would it make sense to specify a full address here? or do we still need the bind-all always?
___
*[`dispatcher/config/sample.go` line 25 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-3KgrCmp-xWFtlACk:-Nu-3KgrCmp-xWFtlACl:ba9vrbz) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/dispatcher/config/sample.go#L25)):*
> ```Go
> 
> # The native port opened by the dispatcher. (default 30041)
> underlay_port = 30041
> ```

can you also add an example for the new properties?
___
*[`gateway/gateway.go` line 448 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtzTTO293pgf77dVQKq:-NtzTTO293pgf77dVQKr:b-wjci82) ([raw file](https://github.com/scionproto/scion/blob/4a8bc98ec7d969dd622c5a90fe677e3c980aaa88/gateway/gateway.go#L448)):*
> ```Go
> 			// Enable transparent reconnections to the dispatcher
> 			Dispatcher: reconnectingDispatcher,
> 			// Discard all SCMP propagation, to avoid accept/read errors on the
> ```

can we keep that comment? or why do you remove it?
___
*[`private/env/logging.go` line 37 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_IGRG4RbvC-PCVToV:-NtytjY07tMNm-9KHbGP:b-5brij4) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/env/logging.go#L37)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Ok, but I do wonder if this is really interesting information to have in the log, or if we should just remove this.
</blockquote></details>

Also this seems kind of unrelated to the PR. Maybe resolve that in a separate PR beforehands?
___
*[`private/svc/svc.go` line 118 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtVfWMuDBo5vcMMT_Jx:-NtzYBJa5jCbIh_8MRQi:bem0nhh) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/svc/svc.go#L118)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Should this `continue` instead? Otherwise the packet is forwarded to the application, which does not seem to make sense to me.
Perhaps it would be cleaner to move this check into the `Handler`; the handler could check the address and reply with `Forward` if this is really the desired behavior.
As we only care about the wildcard, I think we can also just remove this (i.e. make it the Handlers responsibility and not implement it in our handler).
</blockquote></details>

ack, I would also move this check into the handler
___
*[`private/topology/topology.go` line 229 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nta-lbA6uNFuLvD3a07:-Ntyrcqf05xyje5uGlrG:bxz3tyi) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/topology/topology.go#L229)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I would also vote for lower case
___
*[`private/topology/topology.go` line 234 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_yiTcB7ZZi-29V8bw:-Ntyrg1j066-hwkP-IpB:bkunf3u) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/topology/topology.go#L234)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done.
</blockquote></details>

lower case...
___
*[`private/topology/topology.go` line 226 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtyrMQx1064idrAu9Xc:-NtyrMQx1064idrAu9Xd:bxqvay4) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/private/topology/topology.go#L226)):*
> ```Go
> }
> 
> func validatePortRange(portRange string) (uint16, uint16, error) {
> ```

btw is there a specific reason why you went with the `start-end` notation in the topology json? Why not simply have start and end as separate fields? the parsing would become lighter?

No strong feeling, I'm also ok to keep it this way. 

Ah I see there was another comment to do it this way. So nevermind me.
___
*[`router/datapl [...]

2024-03-27 13:36 UTC, lukedirtwalker requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 56 unresolved discussions (waiting on @JordiSubira, @marcfrei, @matzf, @oncilla, and @tzaeschke)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-63iSAueVMErLkDX_:-Nu-63iSAueVMErLkDXa:b-brhx60) (no related file):*
did a full pass now :100: great work.

Could you maybe also outline quickly how the upgrade path looks like?
Especially with multiple hosts in an AS, where not all of them can be updated at the same time.

___


<!-- Sent from Reviewable.io -->

2024-03-27 13:37 UTC, lukedirtwalker reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 57 unresolved discussions (waiting on @JordiSubira, @marcfrei, @matzf, @oncilla, and @tzaeschke)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-7HH35zYb4BCZkxXb:-Nu-7HH35zYb4BCZkxXc:b-6sbgrk) (no related file):*
btw before merging I would suggest to change the title. maybe simply `remove dispatcher` ?

___


<!-- Sent from Reviewable.io -->

2024-03-28 11:35 UTC, matzf reviewed
> Reviewed 1 of 19 files at r19.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 52 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, @marcfrei, @oncilla, and @tzaeschke)

___
*[`control/cmd/control/main.go` line 944 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtWTLoe32duNScty3K8:-Nu3kte-0fdXwD9rS3A0:b-ub7eeo) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/control/cmd/control/main.go#L944)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Yes, it should. However, here https://github.com/scionproto/scion/blob/master/private/topology/json/json.go#L96 it still uses the deprecated IFIDType. Then either we change it in the topology parser or I create a [uint64]net.UDPAddr. At the moment, we never configure interfaces bigger than 2^16-1, so it would make more sense to change this directly into the `json.go`. If we change the topology parsing, should I do it in this PR?
</blockquote></details>

I see, leave it then.
___
*[`pkg/snet/snet.go` line 52 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhGGXn3Ct6t1RhF9Jc:-Nu3lS333AS3rFGwozhf:bjzob8f) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/pkg/snet/snet.go#L52)):*
> Does the LocalIA on this interface mean we always call out (via RPC) to the daemon?

It would make sense to cache these values in the daemon API. I think we could always do this, i.e. have `daemon.Service.Connect` return something that caches `LocalIA` (and `ASInfo`). We always assume that this never changes anyway, so there is not really a point in ever asking again.
Alternatively this could be explicitly enabled by the application by instantiating a wrapper around `daemon.Connector`, but I don't really see the use case to bypass the caching.
___
*[`router/dataplane.go` line 2086 at r18](https://reviewable.io/reviews/scionproto/scion/4344#-NtqbTYGAKIMRJk6REC0:-Nu3pT6D5UuorUYfZIBh:b4sgq3m) ([raw file](https://github.com/scionproto/scion/blob/75def9d56ec819affcd40dea1af63a01a3687320/router/dataplane.go#L2086)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Given this should only be triggered by relatively few packets I would be willing to merge it the way it currently is and make an issue to optimize this later. To not further block the merging of this PR.
</blockquote></details>

You're right. Just a comment a la  "XXX: this is far slower than it could be" works for now.
___
*[`tools/topology/topo.py` line 247 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtWxFMQEG9E6wUrgXm4:-Nu3ePx7EDlKDFqeCAhh:b-doqucm) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/tools/topology/topo.py#L247)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

no AFAICT this is actually used.
</blockquote></details>

Aha I see, this is used to pass information around within the topogen scripts.

Correcter/nicer would be to pass the `ConfigGenerator.topo_config`  via the `DockerGenArgs` to `DockerGenerator` and check the `test_dispatcher` flag for the individual AS in `DockerGenerator.generate` before the call to `self._gen_topo`.

Ok to leave it for now, but add a `XXX` comment, explaining that this is used internally in the script.


<!-- Sent from Reviewable.io -->

2024-03-29 16:17 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 50 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`acceptance/hidden_paths/test.py` line 95 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-0umTBStJq6WDpuDk:-Nu3Qiz1BT5pYOdZSgCS:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4a8bc98ec7d969dd622c5a90fe677e3c980aaa88/acceptance/hidden_paths/test.py#L95)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

maybe also revert this change and this file doesn't change at all in this PR.
</blockquote></details>

Done.
___
*[`acceptance/topo_cs_reload/docker-compose.yml` line 19 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-1AjT9uPRodMbKRUS:-Nu3Qy_BBA00DvIBDShx:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/acceptance/topo_cs_reload/docker-compose.yml#L19)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

add a newline at the end of the file
</blockquote></details>

Done.
___
*[`acceptance/topo_daemon_reload/docker-compose.yml` line 20 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-1G8317ua8J3s0yic:-Nu3R2-cBMQAitobVQqd:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/acceptance/topo_daemon_reload/docker-compose.yml#L20)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

add newline at the end of the file
</blockquote></details>

Done.
___
*[`acceptance/trc_update/test.py` line 87 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Ntyqnev4k098KCHAQmp:-Nu3VA6NDEB8BgIA9-En:b-o0ox5f) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/acceptance/trc_update/test.py#L87)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

why do we need to increase that so much?
</blockquote></details>

Done. I think the test was flaky at the beginning, in any case, I am wondering whether we should keep this timers or also use the await_connectivity tool under the hood, instead of the end2end one.
___
*[`dispatcher/config/config.go` line 84 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-3-5p8vOy6vQ_awG_:-Nu3WSvO5jIA__VUWnza:b-v3cvk2) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/dispatcher/config/config.go#L84)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

would it make sense to specify a full address here? or do we still need the bind-all always?
</blockquote></details>

I guess we could allow a full address instead of binding to all, although the "by default" behavior is still having one dispatcher per host service to all interfaces. 
___
*[`gateway/gateway.go` line 448 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtzTTO293pgf77dVQKq:-Nu8W__wAJ1KEmJJ2gaI:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4a8bc98ec7d969dd622c5a90fe677e3c980aaa88/gateway/gateway.go#L448)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

can we keep that comment? or why do you remove it?
</blockquote></details>

Done.
___
*[`pkg/snet/packet_conn.go` line 200 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Nty_ASh1n-4bHGOpNrQ:-Nu8X5sXCNbefhh62m7f:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L200)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I think this error message is now wrong, didn't we remove the reliable socket?
</blockquote></details>

Done.
___
*[`pkg/snet/packet_conn.go` line 246 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Ntyaroo1u7CaOzeNDwu:-Nu8e99B5-XtkiF_4hSG:b-hlgabh) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L246)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

why the extra handling of this case? couldn't you simply let it run in the default case in the switch below?
</blockquote></details>

It is to separate the casting from `DataplanePath` interface to `RawPath`. If I am not wrong we shouldn't expect anything different from `RawPacket` when reading from the underlay. 
The default in the switch covers the case of the  `RawPath.PathType` being sth different than the rest. I think it would be contrived to have it everything at once, but I am gald to change it if you suggest the code snippet, probably there's a clear a concise way of expressing this.
___
*[`pkg/snet/packet_conn.go` line 248 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Ntyb-oWCif5RLQSXMVH:-Nu8g6kZ8PHrrvjEVFB_:biqqu61) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L248)):*
> ```Go
> 	rpath, ok := p.Path.(RawPath)
> 	if !ok {
> 		return nil, serrors.New("Unexpected path", "type", common.TypeOf(p.Path))
> ```

I adapt it a bit until we discuss the previous point
___
*[`pkg/snet/packet_conn.go` line 269 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Ntybn5S9UHtRifZ8J89:-Nu8gqp_7x7Oo1gWUEcR:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L269)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I would use an anonymous function to make the code slightly cleaner. Also I don't think we need to special case the SCMPPayload
</blockquote></details>

Done.
___
*[`pkg/snet/packet_conn.go` line 275 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtycCbJ71uNnS-caddv:-Nu8h-1M3RpwidecoYT8:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L275)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Use short circuit version
</blockquote></details>

Done.
___
*[`pkg/snet/packet_conn.go` line 284 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtycNKQ81jDQoFyE14j:-Nu8h8sw55UDWgdu-xvA:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L284)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Use short circuit version
</blockquote></details>

Done.
___
*[`pkg/snet/packet_conn.go` line 320 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Nty_15a-qxWNplAXUdE:-Nu8hOaD0YTJQbvDJgUm:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L320)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Errors should not start with capital letter.
</blockquote></details>

Done.
___
*[`pkg/snet/packet_conn.go` line 344 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtyZp-k1PPeMxR5IEgj:-Nu8jvgD945hYtJACw94:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L344)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Errors should not start with capital letter.
</blockquote></details>

Done.
___
*[`pkg/snet/snet.go` line 76 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtydmKa786NvycdnHD6:-Nu8k5NKChazv1g32vid:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/snet.go#L76)):*
> ```Go
> 	var err error
> 	if addr == nil || addr.IP.IsUnspe [...]

2024-04-02 06:20 UTC, lukedirtwalker reviewed
> Reviewed 27 of 27 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 30 unresolved discussions (waiting on @JordiSubira, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`pkg/snet/packet_conn.go` line 246 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Ntyaroo1u7CaOzeNDwu:-NuSRk2P5cFvsY6YzM6b:b8d702t) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/packet_conn.go#L246)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

It is to separate the casting from `DataplanePath` interface to `RawPath`. If I am not wrong we shouldn't expect anything different from `RawPacket` when reading from the underlay. 
The default in the switch covers the case of the  `RawPath.PathType` being sth different than the rest. I think it would be contrived to have it everything at once, but I am gald to change it if you suggest the code snippet, probably there's a clear a concise way of expressing this.
</blockquote></details>

No it's also fine this way.
___
*[`acceptance/trc_update/test.py` line 87 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Ntyqnev4k098KCHAQmp:-NuSSm5W-O_4C3NiUQOd:b-ff6yyb) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/acceptance/trc_update/test.py#L87)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done. I think the test was flaky at the beginning, in any case, I am wondering whether we should keep this timers or also use the await_connectivity tool under the hood, instead of the end2end one.
</blockquote></details>

yeah awati connectivity would probably make more sense. But maybe in a separate PR?


<!-- Sent from Reviewable.io -->

2024-04-02 08:32 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 30 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, @marcfrei, @oncilla, and @tzaeschke)

___
*[`private/topology/topology.go` line 226 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtyrMQx1064idrAu9Xc:-NuSuBAY0XLbC_emmR_S:b-uf7e2y) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/private/topology/topology.go#L226)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

btw is there a specific reason why you went with the `start-end` notation in the topology json? Why not simply have start and end as separate fields? the parsing would become lighter?

No strong feeling, I'm also ok to keep it this way. 

Ah I see there was another comment to do it this way. So nevermind me.
</blockquote></details>

I don't have strong preference for the structure of this configuration item. 
It should, however, be possible to specify an empty range to completely disable the feature. In thge design doc, I suggested to use two separate json fields for the range, and interpret `max < min` as empty range, but I don't actually think this is very obvious.

This could possibly be expressed more clearly with the range as a string (e.g. "" or "-" could denote an empty range). 
However, the current validation logic does not seem to allow any such empty port range.


<!-- Sent from Reviewable.io -->

2024-04-02 09:41 UTC, lukedirtwalker reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 29 unresolved discussions (waiting on @JordiSubira, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`pkg/snet/writer.go` line 62 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtyYn2AC0mwHNc8kwKs:-NuTAVVn4-A_bLgNItPl:b-aat603) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/pkg/snet/writer.go#L62)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

That's a good observation, indeed. The implementation so far only considers a common port range per AS. The ip_prefix was introduced later on the design document. I didn't engage to much in this specific change. I have to think a bit more on the trade-off of having the port range configurable per prefix and having a common range for the AS. I will state there my doubts. Thank you for bringing this up.
</blockquote></details>

Now that it's gone again from the doc, I resolve my comment here.


<!-- Sent from Reviewable.io -->

2024-04-02 13:23 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 28 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4344#-NtzzLA4CTQFPcyw40ju:-NuTlGewAL_rtD6IpeKm:b-65dz6z) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Overall: error messages should not start with capital letter, there are many instances where this rule is violated.
</blockquote></details>

Done. I tried to fix it on all the changes introduced in this PR. 

___
___
*[`dispatcher/dispatcher.go` line 40 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-51zz-FsSNL00x-0d:-NuT5V_l96hQVp_Qai6z:b-1lrxp0) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/dispatcher/dispatcher.go#L40)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I wonder if we should have a flag to only reply to SCMP Info messages. And in that mode everything else would be dropped? Basically that is then the leftover application once all routers in an AS have migrated. Or am I missing something?
</blockquote></details>

Yes, with this the dispatcher would take the role of a scmp daemon. I wonder though if this should be a runtime flag, a compilation flag or even having two different components, i.e., shim dispatcher and scmpd whose role is explicitly clear by its name.
___
*[`tools/braccept/cases/child_to_internal.go` line 39 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_BO1k51nRMGd2saWP:-NuT8lAZBJSxMNGDExno:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/tools/braccept/cases/child_to_internal.go#L39)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Following the organization of these test cases: just type out the number at every occurrence, or define a separate const in each case function.
</blockquote></details>

Done.
___
*[`tools/braccept/cases/svc.go` line 128 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_9Uaq9x4z8byLlL1A:-NuTDcxV-XPSNAxjnJsh:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/tools/braccept/cases/svc.go#L128)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I think the port should be hard coded here (`const csPort = 20007`) instead of loading it from the topology file. Just like with the IP addresses and everything else.
I can see that it's tempting to make this more automatic, but it's the style of these tests to be very explicit and it seems best to keep this pattern. For what it's worth, the `router_benchmark/cases` have a slightly nicer approach to explicitly represent the topology without repeating IP addresses, ports etc. all over the place, and we intend to apply the same pattern to the `braccept` eventually too.
</blockquote></details>

Done.
___
*[`tools/end2end/main.go` line 355 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_PxAd2c1Yi64mbVSx:-NuTGDa_9POXiePTytIy:b69p5d5) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/tools/end2end/main.go#L355)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Not entirely sure, but wouldn't it also make sense to allow omitting the address entirely? In that case, currently checks above will already fail.

Otherwise, `Unmap` is not necessary here I think.
</blockquote></details>

I remove Unmap. Regarding allowing omitting the address I will add a TODO in the integration to add this behavior when processing the local flag.
___
*[`tools/topology/docker_utils.py` line 63 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtVuTW53rhLTjoTQLxd:-NuTcXqRD1a7ivBf7lOj:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/tools/topology/docker_utils.py#L63)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Please don't set container name, just let docker compose to manage this.
</blockquote></details>

Done.
___
*[`acceptance/trc_update/test.py` line 87 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Ntyqnev4k098KCHAQmp:-NuTegXj7X4VigZxOknm:boefsdx) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/acceptance/trc_update/test.py#L87)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

yeah awati connectivity would probably make more sense. But maybe in a separate PR?
</blockquote></details>

Yes, I also believe in a separate PR would make sense, I add a TODO.


<!-- Sent from Reviewable.io -->

2024-04-03 05:32 UTC, lukedirtwalker requested changes
> Reviewed 17 of 17 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 27 unresolved discussions (waiting on @JordiSubira, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`dispatcher/dispatcher.go` line 40 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-51zz-FsSNL00x-0d:-NuXQQWo8b0G783HoDl1:b-p0rz06) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/dispatcher/dispatcher.go#L40)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Yes, with this the dispatcher would take the role of a scmp daemon. I wonder though if this should be a runtime flag, a compilation flag or even having two different components, i.e., shim dispatcher and scmpd whose role is explicitly clear by its name.
</blockquote></details>

I think for now I would have it as runtime flag, eventually we simply drop the option and we only keep the shim.
___
*[`private/svc/svc.go` line 118 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtVfWMuDBo5vcMMT_Jx:-NuXQjX70k95VKTC0K-7:b-bvp54m) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/svc/svc.go#L118)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I tried to replicate the same logic as above more `svc.IsMulticastI()`. I guess you are right about not caring about anything else than Wildcard, so I will remove it. What about the multicast and anycast case. Do we ever use the multicast addresses?
</blockquote></details>

AFAIR multicast is not used anywhere anymore.


<!-- Sent from Reviewable.io -->

2024-04-03 12:23 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 27 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`pkg/snet/snet.go` line 52 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhGGXn3Ct6t1RhF9Jc:-NuYmhiMAVfCA0CwrkHS:b-vjh9t5) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/pkg/snet/snet.go#L52)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

> Does the LocalIA on this interface mean we always call out (via RPC) to the daemon?

It would make sense to cache these values in the daemon API. I think we could always do this, i.e. have `daemon.Service.Connect` return something that caches `LocalIA` (and `ASInfo`). We always assume that this never changes anyway, so there is not really a point in ever asking again.
Alternatively this could be explicitly enabled by the application by instantiating a wrapper around `daemon.Connector`, but I don't really see the use case to bypass the caching.
</blockquote></details>

Should I introduce the caching in this PR? Otherwise it seems a bit suboptimal indeed to have an RPC call for each LocalIA call
___
*[`private/env/logging.go` line 37 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_IGRG4RbvC-PCVToV:-NuYo6TbDg2Tycqbi-H7:batthq7) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/env/logging.go#L37)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Also this seems kind of unrelated to the PR. Maybe resolve that in a separate PR beforehands?
</blockquote></details>

Done. Reverting and solving this in a separate PR
___
*[`private/service/statuspages.go` line 157 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_Jkq72kzwxyZGTQmY:-NuYrf1C-dYJN-ZTD38w:bb6un1j) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/service/statuspages.go#L157)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Broken err check, this now only displays something if there _was_ an error.
I think you can just revert the change in this file; it will only show something if "RunsInDocker" was successful.
</blockquote></details>

Done
___
*[`private/svc/svc.go` line 118 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtVfWMuDBo5vcMMT_Jx:-NuYGKnb8-kOcz0lS1eZ:b3075wc) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/svc/svc.go#L118)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

AFAIR multicast is not used anywhere anymore.
</blockquote></details>

Done. Then I guess we can still handle it as SVC unicast and ignore the multicast label. 


<!-- Sent from Reviewable.io -->

2024-04-03 17:56 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 26 unresolved discussions (waiting on @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`private/topology/topology.go` line 226 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtyrMQx1064idrAu9Xc:-Nu_44_SA2UvIAKekXzj:bwdje4h) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/private/topology/topology.go#L226)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I don't have strong preference for the structure of this configuration item. 
It should, however, be possible to specify an empty range to completely disable the feature. In thge design doc, I suggested to use two separate json fields for the range, and interpret `max < min` as empty range, but I don't actually think this is very obvious.

This could possibly be expressed more clearly with the range as a string (e.g. "" or "-" could denote an empty range). 
However, the current validation logic does not seem to allow any such empty port range.
</blockquote></details>

What does it exactly mean "disabling the feature" from the point of view of the snet library? I kind of anticipated this need for the BRs, but not for the snet library, which consumes the port range info from the topology (in the future via daemon). Right now, we open underlay UDP/IP sockets on the ports defined on the the given range. Should we return an error on snet if the topology has configured empty range at the moment, or how would this be handled?


<!-- Sent from Reviewable.io -->

2024-04-03 19:07 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 26 unresolved discussions (waiting on @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`router/cmd/router/main.go` line 80 at r18](https://reviewable.io/reviews/scionproto/scion/4344#-NtqxdhsAc2gWiTjbMyt:-Nu_K4riDMhdQCkNDmtv:b-eje4z3) ([raw file](https://github.com/scionproto/scion/blob/75def9d56ec819affcd40dea1af63a01a3687320/router/cmd/router/main.go#L80)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The existing pattern to do this would be:
- store the values from the gloablCfg.Router in the `router.Connector` object
- expose `SetPortRange` on the `router/control.DataPlane` interface
- during `router/control.ConfigDataplane`:
  - combine the values from the topology with the stored overrides from the toml globalCfg, and
  - call `dp.SetPortRange`

This is all a bit obscure, I suspect the history has to do with hot-reload the configuration. Probably best to stick with the pattern for now.
</blockquote></details>

Done as instructed although it also seems a bit obscure to me.


<!-- Sent from Reviewable.io -->

2024-04-04 06:21 UTC, lukedirtwalker reviewed
> Reviewed 4 of 4 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 26 unresolved discussions (waiting on @JordiSubira, @marcfrei, @matzf, @oncilla, and @tzaeschke)



<!-- Sent from Reviewable.io -->

2024-04-05 10:40 UTC, lukedirtwalker requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 26 unresolved discussions (waiting on @JordiSubira, @marcfrei, @matzf, @oncilla, and @tzaeschke)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-63iSAueVMErLkDX_:-Nuhq74a3WvY0Nkt5rEO:b-u90j93) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

did a full pass now :100: great work.

Could you maybe also outline quickly how the upgrade path looks like?
Especially with multiple hosts in an AS, where not all of them can be updated at the same time.
</blockquote></details>

I think this was mostly covered in https://scionproto.slack.com/archives/C8ADA9CEP/p1712218260299339 as summary of that should be enough.

___


<!-- Sent from Reviewable.io -->

2024-04-08 10:36 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 230 of 252 files reviewed, 26 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`pkg/snet/snet.go` line 57 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtWd6nKBqCoklsbnGj4:-NuxFujDBvDkVdj84q_p:b-411baj) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/pkg/snet/snet.go#L57)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This is slightly tangential as you've translated the previous organisation with the "dispatcher" object into this connector. But perhaps this could be a chance to take this a bit further; I wonder if we could get rid of this interface altogether; the only use case for providing an alternative implementation appears to be wrapping  the `PacketConn`, as is done with `ResolverPacketConnector`.
What about this idea: we remove the `Connector` from `SCIONNetwork`. The `DefaultConnector.OpenUDP(...)` is added as a method to `SCIONNetwork`, perhaps as `OpenRaw`.
To still allow the wrapping of the `snet.PacketConn` for use in `snet.Conn` , we can go two ways;
-  add an explicit, optional hook to wrap this, e.g. `SCIONNetwork.OpenRawInterceptor` (either a `func` or an interface).
- or, open up the making of the "high level" `snet.Conn` from the raw `snet.PacketConn`, e.g. as `snet.NewCookedConn(snet.PacketConn, remote snet.Addr) snet.Conn`. This could also open up the space to allow overriding the `SCMPHandler`, `ReplyPather` and what nots in some extended Dial/Listen call (instead of creating a "network" object for a single Dial call, which seems rather awkward to me). 

The advantage would be that using snet becomes more straight forward (fewer types, fewer interfaces, fewer things to initialize). In the simplest case, the initialization could be:
``` go
sn := &snet.Network {
   Topology: daemon
}
```
Moving the `OpenRaw` to the network also makes the usage more uniform; all apps create a `Network`, while currently (e.g. ping) some only use the `DefaultConnector`. 

----

Regarding the name: "Connector" is a bit unlucky; this does not `connect` (in the socket/syscall sense), it only `open`s. Also, there is a relatively big potential for confusion with `daemon.Connector`, which lives on a fairly similar level of the application-facing API. If we keep it, `Opener`?
</blockquote></details>

Done. I opted for the second alternative, i.e., `NewCookedConn()` (not sure about the naming though, perhaps NewConn is enough since we already explain on the interface itself that it represents a "cooked" connection). I also removed the scionConnBase, which just seem unnecessary to me, and maintain scionWritter and scionReader, to have the former logic split . Let me know what you think and I will adapt


<!-- Sent from Reviewable.io -->

2024-04-09 08:29 UTC, lukedirtwalker requested changes
> Reviewed 22 of 22 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 29 unresolved discussions (waiting on @JordiSubira, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`pkg/snet/snet.go` line 80 at r24](https://reviewable.io/reviews/scionproto/scion/4344#-Nv0wmnREJ3axjh6V1Ak:-Nv0wmnREJ3axjh6V1Al:b-t6iyc0) ([raw file](https://github.com/scionproto/scion/blob/bbaa4bd6587660f1e15a40a8eb07f647c2137c6b/pkg/snet/snet.go#L80)):*
> ```Go
> 	// SCMPHandler describes the network behaviour upon receiving SCMP traffic.
> 	SCMPHandler       SCMPHandler
> 	PacketConnMetrics SCIONPacketConnMetrics
> ```

I wonder if that should only be an argument to OpenRaw given that is the only place where we really use it?
But I guess this would make it awkward for the Listen API.
___
*[`pkg/snet/snet.go` line 174 at r24](https://reviewable.io/reviews/scionproto/scion/4344#-Nv0qRuy384sr8wOLl6D:-Nv0qRuy384sr8wOLl6E:bway25a) ([raw file](https://github.com/scionproto/scion/blob/bbaa4bd6587660f1e15a40a8eb07f647c2137c6b/pkg/snet/snet.go#L174)):*
> ```Go
> // send/receive SCION traffic with the usual methods.
> // It takes as arguments a non-nil PacketConn and a non-nil Topology parameter.
> // If replyPather is nil it will use a default ReplyPather.
> ```

I think here it would be nice to use the options pattern, then you could simply have a list of options as last argument and `WithReplyPather` would be used to set the reply pather.

From infraenv.go it seems that the remote is also optional, so I would also turn that into an option.
___
*[`pkg/snet/snet.go` line 215 at r24](https://reviewable.io/reviews/scionproto/scion/4344#-Nv0qwTf8Mwd9x0xTc2F:-Nv0qwTf8Mwd9x0xTc2G:b-j1ye37) ([raw file](https://github.com/scionproto/scion/blob/bbaa4bd6587660f1e15a40a8eb07f647c2137c6b/pkg/snet/snet.go#L215)):*
> ```Go
> 		return nil, err
> 	}
> 	return nil, serrors.WrapStr("binding to port range", syscall.EADDRINUSE)
> ```

probably it makes sense to also put the "start" and "end" in the context.


<!-- Sent from Reviewable.io -->

2024-04-11 13:09 UTC, matzf requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 30 unresolved discussions (waiting on @JordiSubira, @marcfrei, @oncilla, and @tzaeschke)

___
*[`pkg/snet/snet.go` line 109 at r24](https://reviewable.io/reviews/scionproto/scion/4344#-NvCDw15198Pn_vJeZw2:-NvCDw15198Pn_vJeZw3:b5xjp6j) ([raw file](https://github.com/scionproto/scion/blob/bbaa4bd6587660f1e15a40a8eb07f647c2137c6b/pkg/snet/snet.go#L109)):*
> ```Go
> 			return nil, serrors.New("provided port is outside the SCION/UDP range",
> 				"start", start, "end", end, "port", addr.Port)
> 		}
> ```

I think we cannot error out here!
Otherwise, we cannot use the shim dispatcher to run applications with specific ports outside of the range.

Should we try to warn users if the shim dispatcher is not running, though?


<!-- Sent from Reviewable.io -->

2024-04-11 13:19 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 30 unresolved discussions (waiting on @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`pkg/snet/snet.go` line 109 at r24](https://reviewable.io/reviews/scionproto/scion/4344#-NvCDw15198Pn_vJeZw2:-NvCIkyuBvzZXjOH1azQ:btaizud) ([raw file](https://github.com/scionproto/scion/blob/bbaa4bd6587660f1e15a40a8eb07f647c2137c6b/pkg/snet/snet.go#L109)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I think we cannot error out here!
Otherwise, we cannot use the shim dispatcher to run applications with specific ports outside of the range.

Should we try to warn users if the shim dispatcher is not running, though?
</blockquote></details>

Done, I had changed this after the last discussion, I changed it for a log info message


<!-- Sent from Reviewable.io -->

2024-04-11 15:37 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 248 of 252 files reviewed, 31 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`pkg/snet/packet_conn.go` line 246 at r26](https://reviewable.io/reviews/scionproto/scion/4344#-NvCnXFP07lnzIJt-QmX:-NvCnXFP07lnzIJt-QmY:b-ytngri) ([raw file](https://github.com/scionproto/scion/blob/ebc3c2c91d0b90cccb58c5a27cc48ac009ffd955/pkg/snet/packet_conn.go#L246)):*
> ```Go
> // from the shim dispatcher to the destination endhost. Thus, we check here if the packet
> // comes from *localhost:30041*.
> func (c *SCIONPacketConn) isShimDispatcher(udpAddr *net.UDPAddr) bool {
> ```

Actually, I am not convinced by this. Perhaps there are more complex setups that I am not considering and it may be good enough just to check whether the traffic comes from the "endhostPort". In any case, the `SCIONPacketConn.lastHop()` should always return the proper lastHop (BR or endhost) (i.e., this functions returns the proper value even if the traffic is not coming from the dispatcher). 

Besides, here we are basically assuming, as in general, that the dispatcher is listening on 30041. However, we allow to change it in `disp.toml`. If really want to allow have a dispatcher running on a different port and still be useful, we should have a way to indicate applications running `snet` that the dispatcher port is sth different (perhaps an env variable??).


<!-- Sent from Reviewable.io -->

2024-04-11 15:38 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 248 of 252 files reviewed, 31 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`pkg/snet/packet_conn.go` line 246 at r26](https://reviewable.io/reviews/scionproto/scion/4344#-NvCnXFP07lnzIJt-QmX:-NvCnm5N8sVwvAq8hPh0:b-lmtap) ([raw file](https://github.com/scionproto/scion/blob/ebc3c2c91d0b90cccb58c5a27cc48ac009ffd955/pkg/snet/packet_conn.go#L246)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Actually, I am not convinced by this. Perhaps there are more complex setups that I am not considering and it may be good enough just to check whether the traffic comes from the "endhostPort". In any case, the `SCIONPacketConn.lastHop()` should always return the proper lastHop (BR or endhost) (i.e., this functions returns the proper value even if the traffic is not coming from the dispatcher). 

Besides, here we are basically assuming, as in general, that the dispatcher is listening on 30041. However, we allow to change it in `disp.toml`. If really want to allow have a dispatcher running on a different port and still be useful, we should have a way to indicate applications running `snet` that the dispatcher port is sth different (perhaps an env variable??).
</blockquote></details>

@matzf @lukedirtwalker 


<!-- Sent from Reviewable.io -->

2024-04-12 10:59 UTC, lukedirtwalker reviewed
> Reviewed 3 of 3 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 251 of 252 files reviewed, 31 unresolved discussions (waiting on @JordiSubira, @marcfrei, @matzf, @oncilla, and @tzaeschke)



<!-- Sent from Reviewable.io -->

2024-04-12 11:22 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 251 of 252 files reviewed, 31 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4344#-Nt_7SCr00URpuCbtI8c:-NvH1n8V93L-q4r5R0CB:b-g0olvv) (no related file):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

In the "cooked" `snet.Conn`, in `snet/reader.go`:`func read()`, we should now probably add a check to ensure that the packet that was read is destined to "us". This was previously done by the dispatcher (i _think_), but now it's possible that we receive SCION/UDP packets to our underlay port that have a different SCION destination address or destination port.
</blockquote></details>

Done. Please double check the logic/comment

___


<!-- Sent from Reviewable.io -->

2024-04-12 14:01 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 227 of 252 files reviewed, 32 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-63iSAueVMErLkDX_:-NvH5KPa-TmoQZJBAc77:bxisez1) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I think this was mostly covered in https://scionproto.slack.com/archives/C8ADA9CEP/p1712218260299339 as summary of that should be enough.
</blockquote></details>

One can also refer to the section "Update procedure" in the resulting documentation for this PR https://github.com/scionproto/scion/pull/4280

___
___
*[`pkg/snet/snet.go` line 80 at r24](https://reviewable.io/reviews/scionproto/scion/4344#-Nv0wmnREJ3axjh6V1Ak:-NvH6pfa5lNi27NlJYxA:b-jgqkul) ([raw file](https://github.com/scionproto/scion/blob/bbaa4bd6587660f1e15a40a8eb07f647c2137c6b/pkg/snet/snet.go#L80)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I wonder if that should only be an argument to OpenRaw given that is the only place where we really use it?
But I guess this would make it awkward for the Listen API.
</blockquote></details>

I think for this reason I wouldn't modify it, if you think changing `Listen()` is okay I can change this, no problem.
___
*[`pkg/snet/snet.go` line 215 at r24](https://reviewable.io/reviews/scionproto/scion/4344#-Nv0qwTf8Mwd9x0xTc2F:-NvHayLy3GAXhB0sJuvP:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bbaa4bd6587660f1e15a40a8eb07f647c2137c6b/pkg/snet/snet.go#L215)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

probably it makes sense to also put the "start" and "end" in the context.
</blockquote></details>

Done.
___
*[`pkg/snet/snet.go` line 208 at r27](https://reviewable.io/reviews/scionproto/scion/4344#-NvHb0Dc3FpR7U1trYiU:-NvHb0Dc3FpR7U1trYiV:b-r7rslm) ([raw file](https://github.com/scionproto/scion/blob/a791e56b800fd463c27dfdb19878c3a0954958dc/pkg/snet/snet.go#L208)):*
> ```Go
> 
> func listenUDPRange(addr *net.UDPAddr, start, end uint16) (*net.UDPConn, error) {
> 	// XXX(JordiSubira): For now, we iterate on the complete SCION/UDP
> ```

@lukedirtwalker @matzf, please, also take a look at this dynamic port assignment, I am happy to change it for sth better.


<!-- Sent from Reviewable.io -->

2024-04-12 14:21 UTC, lukedirtwalker reviewed
> Reviewed 20 of 25 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 247 of 252 files reviewed, 31 unresolved discussions (waiting on @JordiSubira, @marcfrei, @matzf, @oncilla, and @tzaeschke)



<!-- Sent from Reviewable.io -->

2024-04-29 14:10 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 242 of 252 files reviewed, 28 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`dispatcher/dispatcher.go` line 40 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-Nu-51zz-FsSNL00x-0d:-NweBLD37eTX4Q1QNRba:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/dispatcher/dispatcher.go#L40)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I think for now I would have it as runtime flag, eventually we simply drop the option and we only keep the shim.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-02 09:13 UTC, lukedirtwalker requested changes
> Reviewed 1 of 25 files at r27, 4 of 6 files at r28.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 247 of 252 files reviewed, 29 unresolved discussions (waiting on @JordiSubira, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`pkg/snet/packet_conn.go` line 246 at r26](https://reviewable.io/reviews/scionproto/scion/4344#-NvCnXFP07lnzIJt-QmX:-NwsVAQx5O-PFC_WG8hB:b-5bedoi) ([raw file](https://github.com/scionproto/scion/blob/ebc3c2c91d0b90cccb58c5a27cc48ac009ffd955/pkg/snet/packet_conn.go#L246)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

@matzf @lukedirtwalker
</blockquote></details>

I don't really understand the first part. Could you maybe rephrase it, or explain it a bit more?
For the latter part: I think the 30041 assumption is hardcoded, so I'd rather remove the option to change it for now.
___
*[`pkg/snet/packet_conn.go` line 242 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-NwsVgf5De3pD2g6d3Lq:-NwsVgf5De3pD2g6d3Lr:undefined) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/pkg/snet/packet_conn.go#L242)):*
> ```Go
> // the shim dispatcher forwards the packets.
> //
> // A special case is the developer setup we use a unique shim dispatcher instance
> ```





_Suggestion:_
```Go
 A special case is the developer setup: we use a single shim dispatcher instance
```
___
*[`pkg/snet/packet_conn.go` line 250 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-NwsVY0X7wR5r6yJPrYS:-NwsVY0X7wR5r6yJPrYT:b3bxp8n) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/pkg/snet/packet_conn.go#L250)):*
> ```Go
> 	localAddr := c.LocalAddr().(*net.UDPAddr)
> 	if (udpAddr.IP.Equal(localAddr.IP) ||
> 		udpAddr.AddrPort().Addr().Compare(netip.MustParseAddr("127.0.0.1")) == 0) &&
> ```

would https://pkg.go.dev/net/netip#Addr.IsLoopback not be better as check here?
___
*[`pkg/snet/snet.go` line 208 at r27](https://reviewable.io/reviews/scionproto/scion/4344#-NvHb0Dc3FpR7U1trYiU:-NwsXtyw0cqvo9oQDOUA:b-guiquq) ([raw file](https://github.com/scionproto/scion/blob/a791e56b800fd463c27dfdb19878c3a0954958dc/pkg/snet/snet.go#L208)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

@lukedirtwalker @matzf, please, also take a look at this dynamic port assignment, I am happy to change it for sth better.
</blockquote></details>

Hm so I wonder if we should actually do that here. Given it's standard UDP we could also leverage sysctl: ```
net.ipv4.ip_local_port_range
```

then we could simply open with `:0`. However it's a bit awkward because the users will have configure it from outside.

But other than that I don't think there is anything much better that just trying the ports...
```



<!-- Sent from Reviewable.io -->

2024-05-02 13:07 UTC, matzf requested changes
> Reviewed 4 of 27 files at r20, 3 of 17 files at r21, 1 of 4 files at r22, 2 of 22 files at r24, 8 of 25 files at r27, 1 of 6 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 248 of 252 files reviewed, 28 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, @marcfrei, @oncilla, and @tzaeschke)

___
*[`dispatcher/config/config.go` line 89 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-NwtNzK85cyD4TabRAKc:-NwtNzK85cyD4TabRAKd:b-4m4nl5) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/dispatcher/config/config.go#L89)):*
> ```Go
> 	//  where the CS for the local IA runs.
> 	ServiceAddresses map[addr.Addr]netip.AddrPort `toml:"service_addresses,omitempty"`
> 	// UnderlayAddr is the UDP address where the shim dispatcher listens on (default [::]:30041)
> ```

This says "default", the sample says "required". I think a default makes more sense (not currently implemented).
___
*[`pkg/snet/reader.go` line 102 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-Nwsu60A8thotTMWEstt:-Nwsu60B-dGq9UEbkcE7:b99rk6t) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/pkg/snet/reader.go#L102)):*
> ```Go
> 		return 0, nil, serrors.New("packet is destined to a different host",
> 			"local address", localAddr,
> 			"pkt.Destination.Host", pkt.Source.Host.IP())
> ```

Accidentally put Source address in the error instead of Destination.
___
*[`pkg/snet/reader.go` line 103 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-Nwsy_oZ1F6GQJUgaxVc:-Nwsy_oZ1F6GQJUgaxVd:b-65rp3e) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/pkg/snet/reader.go#L103)):*
> ```Go
> 			"local address", localAddr,
> 			"pkt.Destination.Host", pkt.Source.Host.IP())
> 	}
> ```

Missing a check for the destination _port_. 
The error message it might be easier to understand if it only speaks about the destination address as a whole, instead of separate cases for each of  ISD-AS,  IP and port.
For this, I would combine the checks into a single if clause.
___
*[`pkg/snet/snet.go` line 52 at r9](https://reviewable.io/reviews/scionproto/scion/4344#-NqhGGXn3Ct6t1RhF9Jc:-Nwt3MMR5FEzTZT8Hh6f:b-fjoi19) ([raw file](https://github.com/scionproto/scion/blob/16fa70e6a803f593b97d1abc4e394b33385ab977/pkg/snet/snet.go#L52)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I would not make this PR bigger than it needs to be. You can still add it later, no? up to @matzf
</blockquote></details>

Agreed, do it later.
___
*[`pkg/snet/snet.go` line 57 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtWd6nKBqCoklsbnGj4:-Nwt5-HH6WAOLKf4J_6r:bj6sx1a) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/pkg/snet/snet.go#L57)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done. I opted for the second alternative, i.e., `NewCookedConn()` (not sure about the naming though, perhaps NewConn is enough since we already explain on the interface itself that it represents a "cooked" connection). I also removed the scionConnBase, which just seem unnecessary to me, and maintain scionWritter and scionReader, to have the former logic split . Let me know what you think and I will adapt
</blockquote></details>

100 for removing scionConnBase.

Ok for me if you think `NewConn` makes more sense, but just make sure that the documentation very explicitly says that this is an advanced API, that it's not the default way to obtain a Conn, that you normally want Listen/Dial instead.
___
*[`pkg/snet/snet.go` line 208 at r27](https://reviewable.io/reviews/scionproto/scion/4344#-NvHb0Dc3FpR7U1trYiU:-Nwt874Z2LKZEazNw8ni:bt26hwk) ([raw file](https://github.com/scionproto/scion/blob/a791e56b800fd463c27dfdb19878c3a0954958dc/pkg/snet/snet.go#L208)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Hm so I wonder if we should actually do that here. Given it's standard UDP we could also leverage sysctl: ```
net.ipv4.ip_local_port_range
```

then we could simply open with `:0`. However it's a bit awkward because the users will have configure it from outside.

But other than that I don't think there is anything much better that just trying the ports...
```

</blockquote></details>

I think relying on the system port range would not be a good fit for what we intend here, namely making it easier to build scion applications on any platform.

Possibly checking the ports in pseudorandom order could be a way to reduce the typical number of checks needed (versus this sort of "distributed Shlemiel the painter" approach :wink:). We need to find a pseudorandom number generator that doesn't repeat any numbers in a cycle. Then we can still visit all ports in a single pass.
But this is an optimization that we can also defer for later.
___
*[`pkg/snet/snet.go` line 180 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-Nwt6ML9B0X2zsoWuuaG:-Nwt6ML9B0X2zsoWuuaH:b-lgy30z) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/pkg/snet/snet.go#L180)):*
> ```Go
> // Nil or unspecified addresses for the PacketConn object are not supported.
> // If replyPather is nil it will use a default ReplyPather.
> func NewCookedConn(
> ```

Nit: move to snet/conn.go (and combine with `newConn` for simplicity?).
___
*[`private/app/appnet/infraenv.go` line 349 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-NwtJzf9DqMgNW-RRTgW:-NwtJzf9DqMgNW-RRTgX:b-k5wozm) ([raw file](https://github.com/scionproto/scion/blob/4a8bc98ec7d969dd622c5a90fe677e3c980aaa88/private/app/appnet/infraenv.go#L349)):*
> ```Go
> 				Log:     log.Debug,
> 			},
> 			SCIONPacketConnMetrics: nc.SCIONPacketConnMetrics,
> ```

Not sure, but shouldn't we keep the SCMPHandler (and the Metrics) here? Just move one level up to the Network.
___
*[`private/svc/svc.go` line 118 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtVfWMuDBo5vcMMT_Jx:-NwtLsSE2UYGiV1ioLT2:bfa06q5) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/svc/svc.go#L118)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done. Then I guess we can still handle it as SVC unicast and ignore the multicast label.
</blockquote></details>

I think I didn't mean to suggest to move the first check, `if pkt.Destination.Host.Type() != addr.HostTypeSVC`, into the handler. According to the docs on RequestHandler.Handle this violates the expectations there.


<!-- Sent from Reviewable.io -->

2024-05-03 05:19 UTC, lukedirtwalker reviewed
> Reviewed 1 of 6 files at r28.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 249 of 252 files reviewed, 26 unresolved discussions (waiting on @JordiSubira, @marcfrei, @matzf, @oncilla, and @tzaeschke)



<!-- Sent from Reviewable.io -->

2024-05-03 08:23 UTC, matzf reviewed
> Reviewed 2 of 17 files at r18, 4 of 19 files at r19, 7 of 27 files at r20, 8 of 17 files at r21, 1 of 4 files at r22, 3 of 4 files at r23, 17 of 22 files at r24, 1 of 3 files at r25, 16 of 25 files at r27, 5 of 6 files at r28.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 21 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, @marcfrei, @oncilla, and @tzaeschke)

___
*[`dispatcher/config/config.go` line 83 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-NwxKZQL3v_iqsCCAO71:-NwxKZQL3v_iqsCCAO72:br8l0me) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/dispatcher/config/config.go#L83)):*
> ```Go
> 	// IsDispatcher is the flag indicating whether the shim acts as dispatcher for packets arriving
> 	// to the fix endhost port. Otherwise, it will only reply to SCMPInfo packets.
> 	IsDispatcher bool `toml:"is_dispatcher,omitempty"`
> ```

I don't have a good suggestion right now, but "is_dispatcher" in the config section "dispatcher" of the component "dispatcher" is just a bit strange; just thinking about how this will be documented makes it seem rather clumsy. We'll have to revisit the terminology. We can leave it for now and revisit it after merging, together with updating the documentation.
___
*[`router/config/config.go` line 48 at r18](https://reviewable.io/reviews/scionproto/scion/4344#-Ntr-Mrb9Fx0C4lGon5k:-NwxQPd70chnr8zckRzy:b-ccvhf0) ([raw file](https://github.com/scionproto/scion/blob/75def9d56ec819affcd40dea1af63a01a3687320/router/config/config.go#L48)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

At the beginning I thought to override a different port range for specific routers, right now I use it for the acceptance tests and I thought it could be useful in general. However, you are probably right and this it's more confusing than helpful. For the tests I can figure out sth else.
</blockquote></details>

Still planning to remove this? Can also defer this as a todo for after the merge.


<!-- Sent from Reviewable.io -->

2024-05-03 08:45 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 251 of 252 files reviewed, 21 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`dispatcher/config/config.go` line 83 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-NwxKZQL3v_iqsCCAO71:-NwxbkCu3WcHUWKByo_R:b-tp4vxa) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/dispatcher/config/config.go#L83)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I don't have a good suggestion right now, but "is_dispatcher" in the config section "dispatcher" of the component "dispatcher" is just a bit strange; just thinking about how this will be documented makes it seem rather clumsy. We'll have to revisit the terminology. We can leave it for now and revisit it after merging, together with updating the documentation.
</blockquote></details>

I decided to put this name for the flag, with the idea of changing the name for the component: "dispatcher" -> "shim". I know "shim" is quite general, but I wanted to change the name so that people do not confuse it with the "old" dispatcher. What do you think?
___
*[`private/app/appnet/infraenv.go` line 349 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-NwtJzf9DqMgNW-RRTgW:-NwxbbhF2PxRFdzzHEcx:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4a8bc98ec7d969dd622c5a90fe677e3c980aaa88/private/app/appnet/infraenv.go#L349)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Not sure, but shouldn't we keep the SCMPHandler (and the Metrics) here? Just move one level up to the Network.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-03 15:08 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 251 of 252 files reviewed, 21 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`dispatcher/config/config.go` line 89 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-NwtNzK85cyD4TabRAKc:-NwyKVH4-K7dDqP586eO:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/dispatcher/config/config.go#L89)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This says "default", the sample says "required". I think a default makes more sense (not currently implemented).
</blockquote></details>

Done.
___
*[`pkg/snet/packet_conn.go` line 246 at r26](https://reviewable.io/reviews/scionproto/scion/4344#-NvCnXFP07lnzIJt-QmX:-NwygNca2hndHIq7DlWD:baq0y4e) ([raw file](https://github.com/scionproto/scion/blob/ebc3c2c91d0b90cccb58c5a27cc48ac009ffd955/pkg/snet/packet_conn.go#L246)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I don't really understand the first part. Could you maybe rephrase it, or explain it a bit more?
For the latter part: I think the 30041 assumption is hardcoded, so I'd rather remove the option to change it for now.
</blockquote></details>

Done. Nevermind the first part, I was just overthinking  whether the check was sufficient.
___
*[`pkg/snet/packet_conn.go` line 242 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-NwsVgf5De3pD2g6d3Lq:-NwyKkARE7bASeKhcQqJ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/pkg/snet/packet_conn.go#L242)):*
> ```Go
> // the shim dispatcher forwards the packets.
> //
> // A special case is the developer setup we use a unique shim dispatcher instance
> ```

Done.
___
*[`pkg/snet/packet_conn.go` line 250 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-NwsVY0X7wR5r6yJPrYS:-Nwyh4R3418-viHUhgwx:bs7wumx) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/pkg/snet/packet_conn.go#L250)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

would https://pkg.go.dev/net/netip#Addr.IsLoopback not be better as check here?
</blockquote></details>

Done. 
___
*[`pkg/snet/reader.go` line 102 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-Nwsu60A8thotTMWEstt:-NwyoHTRBvHmo6ocIH2t:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/pkg/snet/reader.go#L102)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Accidentally put Source address in the error instead of Destination.
</blockquote></details>

Done.
___
*[`pkg/snet/reader.go` line 103 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-Nwsy_oZ1F6GQJUgaxVc:-NwyoHnK3kk3GznBWYhu:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/pkg/snet/reader.go#L103)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Missing a check for the destination _port_. 
The error message it might be easier to understand if it only speaks about the destination address as a whole, instead of separate cases for each of  ISD-AS,  IP and port.
For this, I would combine the checks into a single if clause.
</blockquote></details>

Done.
___
*[`private/svc/svc.go` line 118 at r17](https://reviewable.io/reviews/scionproto/scion/4344#-NtVfWMuDBo5vcMMT_Jx:-Nwz--Ih6nYhl1fRMkeW:b-7rl0jd) ([raw file](https://github.com/scionproto/scion/blob/44b7b5046a99baa425d1b4bea1bed8c41063b9eb/private/svc/svc.go#L118)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I think I didn't mean to suggest to move the first check, `if pkt.Destination.Host.Type() != addr.HostTypeSVC`, into the handler. According to the docs on RequestHandler.Handle this violates the expectations there.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2024-05-06 09:04 UTC, matzf requested changes
> Reviewed 1 of 1 files at r29, 14 of 14 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 19 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, @marcfrei, @oncilla, and @tzaeschke)

___
*[`dispatcher/config/config.go` line 83 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-NwxKZQL3v_iqsCCAO71:-NxC5_3g0m96Udxj8Mai:b-kf9xs3) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/dispatcher/config/config.go#L83)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I decided to put this name for the flag, with the idea of changing the name for the component: "dispatcher" -> "shim". I know "shim" is quite general, but I wanted to change the name so that people do not confuse it with the "old" dispatcher. What do you think?
</blockquote></details>

Not strongly opposed to renaming, but I'm not sure if this is worth the hassle. The new component has _mostly_ the same role as the dispatcher. Renaming it will lead to additional trouble for the packaging.
___
*[`dispatcher/config/config.go` line 97 at r30](https://reviewable.io/reviews/scionproto/scion/4344#-NxC4vka6VxT_ZXAbCH9:-NxC4vka6VxT_ZXAbCHA:bmeocu5) ([raw file](https://github.com/scionproto/scion/blob/64063ef417fda77d9e1afc89636a48a3ebcf36bd/dispatcher/config/config.go#L97)):*
> ```Go
> 		if err != nil {
> 			panic(err)
> 		}
> ```

Just use `netip.IPv6Unspecified()`

Btw. I don't think `UnderlayAddr` needs to be a pointer. The zero value `netip.Addr{}` is distinct from any valid address and so can be used just like a nil value.
___
*[`dispatcher/config/sample.go` line 24 at r30](https://reviewable.io/reviews/scionproto/scion/4344#-NxC6jh-3FScNTTipTWo:-NxC6jh-3FScNTTipTWp:bmbhdl7) ([raw file](https://github.com/scionproto/scion/blob/64063ef417fda77d9e1afc89636a48a3ebcf36bd/dispatcher/config/sample.go#L24)):*
> ```Go
> id = "%s"
> 
> # The underlay UDP address opened by the dispatcher. (default ::)
> ```

Nit: IP address, not UDP
___
*[`pkg/daemon/daemon.go` line 65 at r30](https://reviewable.io/reviews/scionproto/scion/4344#-NxC5PCt4B-5tpMOpuhu:-NxC5PCt4B-5tpMOpuhv:b-t71o5d) ([raw file](https://github.com/scionproto/scion/blob/64063ef417fda77d9e1afc89636a48a3ebcf36bd/pkg/daemon/daemon.go#L65)):*
> ```Go
> type Connector interface {
> 	// LocalIA requests from the daemon the local ISD-AS number.
> 	// TODO: Caching this value to avoid contacting the CS, since this never changes.
> ```

Nit: we only contact the daemon, not the CS.
___
*[`private/topology/topology.go` line 226 at r19](https://reviewable.io/reviews/scionproto/scion/4344#-NtyrMQx1064idrAu9Xc:-NxC7w_B8x-ZvvsZh3zI:bx02pdg) ([raw file](https://github.com/scionproto/scion/blob/e71f6c288e80086318fdaa61f3d032d864a1b1db/private/topology/topology.go#L226)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

What does it exactly mean "disabling the feature" from the point of view of the snet library? I kind of anticipated this need for the BRs, but not for the snet library, which consumes the port range info from the topology (in the future via daemon). Right now, we open underlay UDP/IP sockets on the ports defined on the the given range. Should we return an error on snet if the topology has configured empty range at the moment, or how would this be handled?
</blockquote></details>

Right, I only had the router in mind. In snet we cannot disable this.


<!-- Sent from Reviewable.io -->

2024-05-06 11:22 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 19 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`dispatcher/config/config.go` line 83 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-NwxKZQL3v_iqsCCAO71:-NxCceDz5ir9LWxeL_lW:b4ykkwp) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/dispatcher/config/config.go#L83)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Not strongly opposed to renaming, but I'm not sure if this is worth the hassle. The new component has _mostly_ the same role as the dispatcher. Renaming it will lead to additional trouble for the packaging.
</blockquote></details>

Yes, indeed it is some hassle renaming. What about chaging the flag meaning and have an "onlySCMPInfoResponder"?


<!-- Sent from Reviewable.io -->

2024-05-06 13:34 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 15 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`dispatcher/config/config.go` line 97 at r30](https://reviewable.io/reviews/scionproto/scion/4344#-NxC4vka6VxT_ZXAbCH9:-NxCgqx85Ii32P8kXb4b:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/64063ef417fda77d9e1afc89636a48a3ebcf36bd/dispatcher/config/config.go#L97)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Just use `netip.IPv6Unspecified()`

Btw. I don't think `UnderlayAddr` needs to be a pointer. The zero value `netip.Addr{}` is distinct from any valid address and so can be used just like a nil value.
</blockquote></details>

Done.
___
*[`router/config/config.go` line 48 at r18](https://reviewable.io/reviews/scionproto/scion/4344#-Ntr-Mrb9Fx0C4lGon5k:-NxCkSYe7IUU8Ag5yXfS:bh0ayql) ([raw file](https://github.com/scionproto/scion/blob/75def9d56ec819affcd40dea1af63a01a3687320/router/config/config.go#L48)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Still planning to remove this? Can also defer this as a todo for after the merge.
</blockquote></details>

TODO added. 


<!-- Sent from Reviewable.io -->

2024-05-07 15:01 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 245 of 252 files reviewed, 15 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`pkg/snet/snet.go` line 174 at r24](https://reviewable.io/reviews/scionproto/scion/4344#-Nv0qRuy384sr8wOLl6D:-NxIZhHX395joCB-CO3h:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bbaa4bd6587660f1e15a40a8eb07f647c2137c6b/pkg/snet/snet.go#L174)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I think here it would be nice to use the options pattern, then you could simply have a list of options as last argument and `WithReplyPather` would be used to set the reply pather.

From infraenv.go it seems that the remote is also optional, so I would also turn that into an option.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-08 04:51 UTC, lukedirtwalker requested changes
> Reviewed 2 of 25 files at r27, 10 of 14 files at r30, 5 of 7 files at r31, 3 of 3 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 12 unresolved discussions (waiting on @JordiSubira, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`pkg/snet/reader.go` line 102 at r32](https://reviewable.io/reviews/scionproto/scion/4344#-NxLXNAA8keZ07QiWsxr:-NxLXNAA8keZ07QiWsxs:undefined) ([raw file](https://github.com/scionproto/scion/blob/c8e7b03406374ece9e1e3c0c2f941d0bc65391f2/pkg/snet/reader.go#L102)):*
> ```Go
> 			"local host", c.local.Host,
> 			"pkt destination IA", pkt.Destination.IA,
> 			"pkt destination host", pktAddrPort,
> ```





_Suggestion:_
```Go
			"local_isd_as", c.local.IA,
			"local_host", c.local.Host,
			"pkt_destination_isd_as", pkt.Destination.IA,
			"pkt_destination_host", pktAddrPort,
```


<!-- Sent from Reviewable.io -->

2024-05-08 07:20 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 12 unresolved discussions (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`pkg/snet/reader.go` line 102 at r32](https://reviewable.io/reviews/scionproto/scion/4344#-NxLXNAA8keZ07QiWsxr:-NxM3jB34FeA1Tfy0o5i:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c8e7b03406374ece9e1e3c0c2f941d0bc65391f2/pkg/snet/reader.go#L102)):*
> ```Go
> 			"local host", c.local.Host,
> 			"pkt destination IA", pkt.Destination.IA,
> 			"pkt destination host", pktAddrPort,
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-08 07:27 UTC, lukedirtwalker approved these changes
> Reviewed 1 of 1 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 11 unresolved discussions (waiting on @marcfrei, @matzf, @oncilla, and @tzaeschke)



<!-- Sent from Reviewable.io -->

2024-05-08 11:25 UTC, marcfrei reviewed
> Reviewed 3 of 183 files at r1, 4 of 34 files at r10, 5 of 20 files at r11, 1 of 20 files at r12, 11 of 38 files at r13, 8 of 19 files at r14, 7 of 7 files at r15, 5 of 10 files at r16, 11 of 17 files at r18, 4 of 19 files at r19, 8 of 27 files at r20, 10 of 17 files at r21, 2 of 4 files at r22, 3 of 4 files at r23, 16 of 22 files at r24, 1 of 3 files at r25, 20 of 25 files at r27, 2 of 6 files at r28, 1 of 1 files at r29, 10 of 14 files at r30, 7 of 7 files at r31, 3 of 3 files at r32, 1 of 1 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 22 unresolved discussions (waiting on @JordiSubira, @matzf, @oncilla, and @tzaeschke)

___
*[`daemon/internal/servers/grpc.go` line 356 at r31](https://reviewable.io/reviews/scionproto/scion/4344#-NxHCARy5UjYdSCiQT_G:-NxHCARy5UjYdSCiQT_H:b-o3761d) ([raw file](https://github.com/scionproto/scion/blob/8bb2dcce6b2ce807a51cfe29a6c26350fdc469de/daemon/internal/servers/grpc.go#L356)):*
> ```Go
> }
> 
> // AS serves the AS request.
> ```

Don't really understand this comment.
___
*[`dispatcher/dispatcher.go` line 95 at r33](https://reviewable.io/reviews/scionproto/scion/4344#-NxMilzIDS1wOGJ9UfZ_:-NxMilzIDS1wOGJ9UfZa:bnik8c9) ([raw file](https://github.com/scionproto/scion/blob/9df56579ea9229dae0139bb13a55fe096f13e46c/dispatcher/dispatcher.go#L95)):*
> ```Go
> 	server.parser = parser
> 	// if the dispatcher feature is enabled, we enable IP_PKTINFO; see
> 	// description of setIPPktInfo for more information.
> ```

Pretty redundant with the actual code. Could be removed, imo.



_Code quote:_
```Go
	// if the dispatcher feature is enabled, we enable IP_PKTINFO; see
	// description of setIPPktInfo for more information.
```
___
*[`dispatcher/dispatcher.go` line 151 at r33](https://reviewable.io/reviews/scionproto/scion/4344#-NxMlz0CCB3twl5Fu0qp:-NxMlz0CCB3twl5Fu0qq:b-9a4obn) ([raw file](https://github.com/scionproto/scion/blob/9df56579ea9229dae0139bb13a55fe096f13e46c/dispatcher/dispatcher.go#L151)):*
> ```Go
> // a byte array corresponding to the packet that has to be forwarded.
> // The input byte array *buf* is the raw incoming packet; the *underlay* address MUST NOT
> // be nil and corresponds to the IP address in the encapsulation UDP/IP header; *prevHop*
> ```

`underlay` is a struct and can't be nil



_Suggestion:_
```Go
the *underlay* address MUST NOT be nil
```
___
*[`dispatcher/dispatcher.go` line 151 at r33](https://reviewable.io/reviews/scionproto/scion/4344#-NxMo1Ra-yHFaRE2DSQk:-NxMo1Ra-yHFaRE2DSQl:b6gr9qa) ([raw file](https://github.com/scionproto/scion/blob/9df56579ea9229dae0139bb13a55fe096f13e46c/dispatcher/dispatcher.go#L151)):*
> ```Go
> // a byte array corresponding to the packet that has to be forwarded.
> // The input byte array *buf* is the raw incoming packet; the *underlay* address MUST NOT
> // be nil and corresponds to the IP address in the encapsulation UDP/IP header; *prevHop*
> ```

It's not really "encapsulated", right? Remove the word?



_Code quote:_
```Go
encapsulation
```
___
*[`dispatcher/dispatcher.go` line 157 at r33](https://reviewable.io/reviews/scionproto/scion/4344#-NxMno_3CaO1PHyb4CJ_:-NxMno_3CaO1PHyb4CJa:b2rfc1n) ([raw file](https://github.com/scionproto/scion/blob/9df56579ea9229dae0139bb13a55fe096f13e46c/dispatcher/dispatcher.go#L157)):*
> ```Go
> // It returns a non-nil error for non-recoverable errors, only.
> // If the incoming packet couldn't be processed due to a recoverable error or due to
> // incorrect address validation the returned buffer and address will be nil.
> ```

"buffer will be nil and the address empty"? 



_Code quote:_
```Go
buffer and address will be nil
```
___
*[`dispatcher/dispatcher.go` line 171 at r33](https://reviewable.io/reviews/scionproto/scion/4344#-NxMojZ5Cfk15R5FOsSs:-NxMojZ5Cfk15R5FOsSt:b-hfpv1m) ([raw file](https://github.com/scionproto/scion/blob/9df56579ea9229dae0139bb13a55fe096f13e46c/dispatcher/dispatcher.go#L171)):*
> ```Go
> 	}
> 	if len(s.decoded) < 2 {
> 		log.Error("Unexpected decode packet", "layers decoded", len(s.decoded))
> ```

remove?



_Code quote:_
```Go
decode
```
___
*[`dispatcher/dispatcher.go` line 455 at r33](https://reviewable.io/reviews/scionproto/scion/4344#-NxMrQfEA8RiUnBoK8en:-NxMrQfEA8RiUnBoK8eo:bka5gc8) ([raw file](https://github.com/scionproto/scion/blob/9df56579ea9229dae0139bb13a55fe096f13e46c/dispatcher/dispatcher.go#L455)):*
> ```Go
> 
> // parseUnderlayAddr returns the underlay destination address on the UDP/IP wrapper.
> // It returns nil, if the control message information is not present or cannot be parsed.
> ```

"an empty address" or "an invalid address"? Or should we just stick with "nil" even if it's not strictly true?



_Code quote:_
```Go
nil
```
___
*[`dispatcher/cmd/dispatcher/main.go` line 137 at r33](https://reviewable.io/reviews/scionproto/scion/4344#-NxMvHwi55YuycYzfYXo:-NxMvHwi55YuycYzfYXp:b7qhiy3) ([raw file](https://github.com/scionproto/scion/blob/9df56579ea9229dae0139bb13a55fe096f13e46c/dispatcher/cmd/dispatcher/main.go#L137)):*
> ```Go
> 
> func RunDispatcher(
> 	isDispatcher bool,
> ```

Looks a little funny, don't have a good suggestion though. Could we maybe at least just not export the function?



_Code quote:_
```Go
func RunDispatcher(
	isDispatcher bool,
```
___
*[`pkg/snet/conn.go` line 78 at r31](https://reviewable.io/reviews/scionproto/scion/4344#-NxHG1b-72DGrzDNRB2p:-NxHG1b-72DGrzDNRB2q:bvsps1c) ([raw file](https://github.com/scionproto/scion/blob/8bb2dcce6b2ce807a51cfe29a6c26350fdc469de/pkg/snet/conn.go#L78)):*
> ```Go
> 	}
> 	if local.Host == nil || local.Host.IP.IsUnspecified() {
> 		return nil, serrors.New("nil or unspecified address is not for the raw connection")
> ```

is not supported



_Code quote:_
```Go
is not
```
___
*[`pkg/snet/snet.go` line 91 at r31](https://reviewable.io/reviews/scionproto/scion/4344#-NxI--3578EGfYeWoI2z:-NxI--366N_n7zZvs0kZ:b-eu27xz) ([raw file](https://github.com/scionproto/scion/blob/8bb2dcce6b2ce807a51cfe29a6c26350fdc469de/pkg/snet/snet.go#L91)):*
> ```Go
> 	var err error
> 	if addr == nil || addr.IP.IsUnspecified() {
> 		return nil, serrors.New("nil or unspecified address is not permitted")
> ```

supported



_Code quote:_
```Go
permitted
```
___
*[`private/topology/topology.go` line 71 at r31](https://reviewable.io/reviews/scionproto/scion/4344#-NxHRLJ3Cdw_KTSbNIAh:-NxHRLJ3Cdw_KTSbNIAi:b-3nz0pc) ([raw file](https://github.com/scionproto/scion/blob/8bb2dcce6b2ce807a51cfe29a6c26350fdc469de/private/topology/topology.go#L71)):*
> ```Go
> 		MTU              int
> 		EndhostStartPort uint16
> 		EndhostEndPort   uint16
> ```

A detail and probably also a bit late, but since we already have `underlay.EndhostPort` and `topology.EndhostPort` plus `json.Topology.EndhostPortRange`, shouldn't it then be `EndhostPortStart` and `EndhostPortEnd`, here and everywhere else (daemon.proto, router.Connector, router.DataPlane, snet.scionConnWriter)?



_Code quote:_
```Go
		EndhostStartPort uint16
		EndhostEndPort   uint16
```
___
*[`router/dataplane.go` line 2060 at r33](https://reviewable.io/reviews/scionproto/scion/4344#-NxMgnWUEz1qbMLgMiRu:-NxMgnWUEz1qbMLgMiRv:bb7ondm) ([raw file](https://github.com/scionproto/scion/blob/9df56579ea9229dae0139bb13a55fe096f13e46c/router/dataplane.go#L2060)):*
> ```Go
> 	// XXX(JordiSubira): This implementation is far too slow for the dataplane.
> 	// We should reimplement this with fewer helpers and memory allocations, since
> 	// our solely goal is to parse the L4 port or identifier in the offending packets.
> ```

sole



_Code quote:_
```Go
solely
```
___
*[`tools/topology/net.py` line 179 at r31](https://reviewable.io/reviews/scionproto/scion/4344#-NxIA07c5EdsF5WvC_7l:-NxIA07dE4kRjr6fX-bq:b-7k4tyg) ([raw file](https://github.com/scionproto/scion/blob/8bb2dcce6b2ce807a51cfe29a6c26350fdc469de/tools/topology/net.py#L179)):*
> ```Python
> 
> class PortGenerator(object):
>     # XXX(JordiSubira): We keep this in the default range. If the c [...]

2024-05-08 14:22 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 9 unresolved discussions (waiting on @matzf, @oncilla, and @tzaeschke)

___
*[`daemon/internal/servers/grpc.go` line 356 at r31](https://reviewable.io/reviews/scionproto/scion/4344#-NxHCARy5UjYdSCiQT_G:-NxN0Uov-dINrqRzXVLJ:b-13rfja) ([raw file](https://github.com/scionproto/scion/blob/8bb2dcce6b2ce807a51cfe29a6c26350fdc469de/daemon/internal/servers/grpc.go#L356)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Don't really understand this comment.
</blockquote></details>

Done. It was a leftover vv'.
___
*[`dispatcher/dispatcher.go` line 151 at r33](https://reviewable.io/reviews/scionproto/scion/4344#-NxMlz0CCB3twl5Fu0qp:-NxN2ilM4b5dTilTWojr:b-3c6hv9) ([raw file](https://github.com/scionproto/scion/blob/9df56579ea9229dae0139bb13a55fe096f13e46c/dispatcher/dispatcher.go#L151)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

`underlay` is a struct and can't be nil
</blockquote></details>

Done. I changed the code but not the doc, thank you for pointing this out.
___
*[`dispatcher/dispatcher.go` line 157 at r33](https://reviewable.io/reviews/scionproto/scion/4344#-NxMno_3CaO1PHyb4CJ_:-NxN2qIJCQ5xKHCMZ4lD:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9df56579ea9229dae0139bb13a55fe096f13e46c/dispatcher/dispatcher.go#L157)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

"buffer will be nil and the address empty"?
</blockquote></details>

Done.
___
*[`private/topology/topology.go` line 71 at r31](https://reviewable.io/reviews/scionproto/scion/4344#-NxHRLJ3Cdw_KTSbNIAh:-NxNWhqj6OjGRC0zcN5A:b-9sge5l) ([raw file](https://github.com/scionproto/scion/blob/8bb2dcce6b2ce807a51cfe29a6c26350fdc469de/private/topology/topology.go#L71)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

A detail and probably also a bit late, but since we already have `underlay.EndhostPort` and `topology.EndhostPort` plus `json.Topology.EndhostPortRange`, shouldn't it then be `EndhostPortStart` and `EndhostPortEnd`, here and everywhere else (daemon.proto, router.Connector, router.DataPlane, snet.scionConnWriter)?
</blockquote></details>

Done. I actually changed everything for "dispatchedPort" which is more consistent with the the terms used somewhere else.


<!-- Sent from Reviewable.io -->

2024-05-08 14:30 UTC, marcfrei reviewed
> Reviewed 1 of 18 files at r34.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 235 of 252 files reviewed, 9 unresolved discussions (waiting on @lukedirtwalker, @matzf, @oncilla, and @tzaeschke)

___
*[`private/topology/topology.go` line 71 at r31](https://reviewable.io/reviews/scionproto/scion/4344#-NxHRLJ3Cdw_KTSbNIAh:-NxNao_-3xpAbJKn9uaI:b-xnndms) ([raw file](https://github.com/scionproto/scion/blob/8bb2dcce6b2ce807a51cfe29a6c26350fdc469de/private/topology/topology.go#L71)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Done. I actually changed everything for "dispatchedPort" which is more consistent with the the terms used somewhere else.
</blockquote></details>

Perfect, thanks!


<!-- Sent from Reviewable.io -->

2024-05-10 08:13 UTC, tzaeschke reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 17 of 18 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344#-:-NxWZ2rz0hXh1ivbEpVx:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker, @matzf, and @oncilla)



<!-- Sent from Reviewable.io -->

2024-05-10 08:13 UTC, tzaeschke reviewed
> Reviewed 9 of 17 files at r18, 4 of 19 files at r19, 7 of 27 files at r20, 10 of 17 files at r21, 2 of 4 files at r22, 1 of 4 files at r23, 15 of 22 files at r24, 18 of 25 files at r27, 1 of 6 files at r28, 9 of 14 files at r30, 3 of 7 files at r31, 1 of 3 files at r32, 1 of 1 files at r33, 1 of 18 files at r34.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker, @matzf, and @oncilla)



<!-- Sent from Reviewable.io -->

2024-05-13 09:55 UTC, matzf requested changes
> Reviewed 2 of 7 files at r31, 1 of 3 files at r32, 1 of 1 files at r33, 10 of 18 files at r34, 64 of 64 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira, @lukedirtwalker, and @oncilla)

___
*[`dispatcher/config/config.go` line 83 at r28](https://reviewable.io/reviews/scionproto/scion/4344#-NwxKZQL3v_iqsCCAO71:-NxlH7pY5ChQlxy_Npx_:b-fk7nma) ([raw file](https://github.com/scionproto/scion/blob/afc8c22bde993e3e1831ae1efc632447d3e3c401/dispatcher/config/config.go#L83)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Yes, indeed it is some hassle renaming. What about chaging the flag meaning and have an "onlySCMPInfoResponder"?
</blockquote></details>

I'd flip the sign on this, to say what it does; something like "local_udp_forwarding" or "local_udp_dispatch", "enable_local_packet_dispatch", ....
___
*[`pkg/snet/packet_conn.go` line 353 at r35](https://reviewable.io/reviews/scionproto/scion/4344#-NxlJG7o8-z8v2HiIo4-:-NxlJG7o8-z8v2HiIo40:b-ptls6p) ([raw file](https://github.com/scionproto/scion/blob/568dfc0d0a50d7681981cb37e531bd49d9238679/pkg/snet/packet_conn.go#L353)):*
> ```Go
> 		return nil, serrors.New("interface number not found", "interface", id)
> 	}
> 	return &net.UDPAddr{
> ```

Use `net.UDPAddrFromAddrPort(addrPort)`; mostly the same thing but more concise and also copies the zone, if any.


<!-- Sent from Reviewable.io -->

2024-05-13 11:46 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: 253 of 256 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker, @marcfrei, @matzf, @oncilla, and @tzaeschke)

___
*[`pkg/snet/packet_conn.go` line 353 at r35](https://reviewable.io/reviews/scionproto/scion/4344#-NxlJG7o8-z8v2HiIo4-:-NxlleXd0_6Ubr_31bYL:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/568dfc0d0a50d7681981cb37e531bd49d9238679/pkg/snet/packet_conn.go#L353)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Use `net.UDPAddrFromAddrPort(addrPort)`; mostly the same thing but more concise and also copies the zone, if any.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-14 07:31 UTC, lukedirtwalker approved these changes
> Reviewed 8 of 18 files at r34, 61 of 64 files at r35, 3 of 3 files at r36, 2 of 2 files at r37, 3 of 3 files at r38, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf and @oncilla)



<!-- Sent from Reviewable.io -->

2024-05-15 07:58 UTC, lukedirtwalker approved these changes
> Reviewed 4 of 4 files at r39, 2 of 2 files at r40, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf and @oncilla)



<!-- Sent from Reviewable.io -->

2024-05-16 08:30 UTC, matzf approved these changes
> Reviewed 3 of 3 files at r36, 2 of 2 files at r37, 4 of 4 files at r39, 2 of 2 files at r40, 3 of 3 files at r41, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)



<!-- Sent from Reviewable.io -->

2024-05-16 16:04 UTC, marcfrei approved these changes
> Reviewed 7 of 18 files at r34, 57 of 64 files at r35, 3 of 3 files at r36, 2 of 2 files at r37, 4 of 4 files at r39, 2 of 2 files at r40, 3 of 3 files at r41, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: all files reviewed, 1 unresolved discussion (waiting on @JordiSubira and @oncilla)

___
*[`pkg/snet/snet.go` line 153 at r41](https://reviewable.io/reviews/scionproto/scion/4344#-Ny14f5wErb3ghiBisWW:-Ny14f5x6o_2IfuusROb:b-mfv6mq) ([raw file](https://github.com/scionproto/scion/blob/8189bb5b5bbe54961fe6282fe93cc95b22d8d351/pkg/snet/snet.go#L153)):*
> ```Go
> 		return nil, err
> 	}
> 	log.FromCtx(ctx).Debug("UDP socket openned on", "addr", packetConn.LocalAddr(), "to", remote)
> ```

opened



_Code quote:_
```Go
openned
```


<!-- Sent from Reviewable.io -->

2024-05-17 07:29 UTC, lukedirtwalker approved these changes
> Reviewed 3 of 3 files at r41, 1 of 1 files at r42, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4344)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)



<!-- Sent from Reviewable.io -->

2024-05-17 08:56 UTC, merged