Border router restructure
scionproto/scion pull request #4351
Opened 2023-06-06 16:03 UTC by rohrerj

This pullrequest is the first out of 3 with the goal to restructure the border router as described in the design document. See [https://github.com/scionproto/scion/blob/master/doc/dev/design/BorderRouter.rst](url).

This pullrequest contains the restructuring of the router/dataplane.go to use receiver, processing routines and forwarders instead of doing this all in a per interface goroutine and the buffer reuse support.

2023-06-07 08:24 UTC, matzf commented
Great stuff, thanks @rohrerj. I'll take a closer look at this tomorrow.

2023-06-08 20:07 UTC, matzf requested changes
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351)* status: 1 of 5 files reviewed, 25 unresolved discussions (waiting on @rohrerj)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4351#-NXQK404AiX1NOVbk1Z_:-NXQK404AiX1NOVbk1Za:brzxq5u) (no related file):*
Structure: the main run loop is spread across too many places, too many methods access fields of the `Dataplane` struct. This "global" state makes it harder than necessary to see that the main loops are actually quite simple. The configuration options (`numProcRoutines` etc.) are also fields in the `Dataplane`, which is a too wide scope for these.
Here's what I would prefer:
- the `Run` function takes configuration values as parameters (e.g. in a `struct RunConfig{BatchSize int, NumProcessorRoutines int}` or something like that). This will make it easier to make these configurable later.
-  the main setup is contained in `Run`. All variables are defined here and passed / returned from free-standing helper functions; use methods only where it's too awkward to pass the data explicitly
- use helpers to simplify the main loops, so that the important bits stand out, namely the way the I/O and processing calls and the moving of the buffers through the queues. The rest should 

___
*[a discussion](https://reviewable.io/reviews/scionproto/scion/4351#-NXRRqEr2qLzIAzs7fLk:-NXRRqEr2qLzIAzs7fLl:b-8rhawg) (no related file):*
Currently packets are passed through the channels as pointer, `*packet`. Why not pass them by value, `packet` instead? It's only a little bit wider than a pointer to it and I would expect that this does not affect the performance of the channel.

This would allow to have the pool only take care of the `[]byte` buffers, not the `packet`s. The rest of the information is all passed by value and does not have to be recycled.
The advantage is that it's impossible to forget resetting a field. And it would seem to simplify the handling in a bunch of places.
Maybe it could then even make sense to use `chan processResult` for the forwarder queue.

___
___
*[`router/dataplane.go` line 598 at r1](https://reviewable.io/reviews/scionproto/scion/4351#-NXGulII-rAsojbdlYnN:-NXGulII-rAsojbdlYnO:b-bf1t4k) ([raw file](https://github.com/scionproto/scion/blob/8032c1d6d008900d9e309a7cc09be2dac4011560/router/dataplane.go#L598)):*
> ```Go
> 	// The address to where we are forwarding the packet.
> 	// Will be set by the processing routine
> 	dstAddr *net.UDPAddr
> ```

Use `netip.AddrPort` for new code wherever possible.
Once https://github.com/golang/go/issues/45886 or the corresponding functionality for the `x/net` package comes available, we'll use that to avoid the memory allocations for the addresses.
___
*[`router/dataplane.go` line 126 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXRW3gE9HS8v5VZ52KD:-NXRW3gE9HS8v5VZ52KE:b-hb5ofr) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L126)):*
> ```Go
> 	// the random value is hashed together with the flowID and the address header
> 	// to identify the processing routine that is responsible to process a packet
> 	randomValue []byte
> ```

See comment on structure; none of these fields need to be here. These can all be local variables in the `Run` function instead.
___
*[`router/dataplane.go` line 484 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXQP5O92B2uWOqpvxZ1:-NXQP5O92B2uWOqpvxZ2:ba3vjaf) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L484)):*
> ```Go
> 	d.processorQueueSize = int(math.Max(
> 		float64(len(d.interfaces)*d.interfaceBatchSize/int(d.numProcRoutines)),
> 		float64(d.interfaceBatchSize)))
> ```

Don't use floats for this stuff, please. Define a `max(a, b int) int` somewhere or just use an if.
___
*[`router/dataplane.go` line 510 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXPlRTk-Ojev03M1dxc:-NXPlRTk-Ojev03M1dxd:bwaz8tw) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L510)):*
> ```Go
> // initComponents initializes the channels, buffers, the receivers, the forwarders,
> // processing routines and the bfd sessions
> func (d *DataPlane) initComponents(ctx context.Context) {
> ```

This does _all_ the work of the actual running, so the name `initComponents` seems deceptive; I think just having this all in `Run` is just fine.
___
*[`router/dataplane.go` line 584 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXPmPBYAK18FCfUD45f:-NXPmPBYAK18FCfUD45g:bk9u3cn) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L584)):*
> ```Go
> 		log.Debug("Forwarder error", "err", err)
> 	}
> 	log.Debug("all components terminated")
> ```

The shutdown logic of waiting for the goroutines to stop and closing the channels does not seem to add anything. It also seems to be in a race against the process termination. 
Just fire-and-forget the go routines. Consequently, remove the error groups.
___
*[`router/dataplane.go` line 591 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXRUiFZ9JNS292c7x0g:-NXRUiFZ9JNS292c7x0h:b-qgywi) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L591)):*
> ```Go
> 	Addr        net.Addr
> 	Conn        BatchConn
> }
> ```

I don't think we need this struct. `Addr` is unused, so this is the same information as eg. a `map[uint16]BatchConn` which is already present in `Dataplane`.
___
*[`router/dataplane.go` line 614 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXPrrm90gyAPABC_1JI:-NXPrrm90gyAPABC_1JJ:bspakla) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L614)):*
> ```Go
> 	for d.running {
> 		// collect packets
> 		for newBufferCount+unusedBufferCount < d.interfaceBatchSize {
> ```

No need to maintain the `newBufferCount` variable:



_Suggestion:_
```Go
for i :=0; i < d.interfaceBatchSize - unusedBufferCount; i++ {
```
___
*[`router/dataplane.go` line 616 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXPpZMr3HGdt9kuEyR9:-NXPpZMr3HGdt9kuEyRA:undefined) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L616)):*
> ```Go
> 		for newBufferCount+unusedBufferCount < d.interfaceBatchSize {
> 			p := <-d.packetPool
> 			msgs[newBufferCount].Buffers[0] = p.rawPacket[:bufSize]
> ```





_Suggestion:_
```Go
p.rawPacket[:cap(p.rawPacket)]
```
___
*[`router/dataplane.go` line 622 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXPskyfC7RbRWKauVl2:-NXPskyfC7RbRWKauVl3:b-3t7c04) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L622)):*
> ```Go
> 
> 		// read batch
> 		numPkts, err := ni.Conn.ReadBatch(msgs[:newBufferCount+unusedBufferCount])
> ```

It's always the full batch size



_Suggestion:_
```Go
ni.Conn.ReadBatch(msgs)
```
___
*[`router/dataplane.go` line 625 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXPsza99_YvUcpkvrM_:-NXPsza99_YvUcpkvrMa:beskfs0) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L625)):*
> ```Go
> 		if err != nil {
> 			log.Debug("Error while reading batch", "interfaceId", ni.InterfaceId, "err", err)
> 			unusedBufferCount += newBufferCount
> ```

Just set the `unusedBufferCount` directly after the read (before error handling), so it only needs to be updated once:
`unusedBufferCount = len(msgs) - numPkts`.

Also, variable naming: I'd suggest
`numPkts` -> `numRead`.
`unusedBufferCount` -> `numUnused` or `numReusable`
___
*[`router/dataplane.go` line 646 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXPuhE_9qa5cX-QhPb1:-NXPuhEaD-gLlNKU [...]

2023-06-11 19:47 UTC, rohrerj reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351)* status: 0 of 6 files reviewed, 25 unresolved discussions (waiting on @matzf)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4351#-NXQK404AiX1NOVbk1Z_:-NXfmZGk5Q91Wsnl4Fn_:b-dxjbtb) (no related file):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Structure: the main run loop is spread across too many places, too many methods access fields of the `Dataplane` struct. This "global" state makes it harder than necessary to see that the main loops are actually quite simple. The configuration options (`numProcRoutines` etc.) are also fields in the `Dataplane`, which is a too wide scope for these.
Here's what I would prefer:
- the `Run` function takes configuration values as parameters (e.g. in a `struct RunConfig{BatchSize int, NumProcessorRoutines int}` or something like that). This will make it easier to make these configurable later.
-  the main setup is contained in `Run`. All variables are defined here and passed / returned from free-standing helper functions; use methods only where it's too awkward to pass the data explicitly
- use helpers to simplify the main loops, so that the important bits stand out, namely the way the I/O and processing calls and the moving of the buffers through the queues. The rest should 
</blockquote></details>

I restructured the run functions. Is it better now?

___
*[a discussion](https://reviewable.io/reviews/scionproto/scion/4351#-NXRRqEr2qLzIAzs7fLk:-NXfmlIY3xpcAog2zHmk:b-dazj3p) (no related file):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Currently packets are passed through the channels as pointer, `*packet`. Why not pass them by value, `packet` instead? It's only a little bit wider than a pointer to it and I would expect that this does not affect the performance of the channel.

This would allow to have the pool only take care of the `[]byte` buffers, not the `packet`s. The rest of the information is all passed by value and does not have to be recycled.
The advantage is that it's impossible to forget resetting a field. And it would seem to simplify the handling in a bunch of places.
Maybe it could then even make sense to use `chan processResult` for the forwarder queue.

</blockquote></details>

I changed the implementation to pass packets instead of *packets and the buffer pool to store only byte slices.

___
___
*[`router/dataplane.go` line 598 at r1](https://reviewable.io/reviews/scionproto/scion/4351#-NXGulII-rAsojbdlYnN:-NXfyk3CEveS41MQhCWp:bk0bozc) ([raw file](https://github.com/scionproto/scion/blob/8032c1d6d008900d9e309a7cc09be2dac4011560/router/dataplane.go#L598)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Use `netip.AddrPort` for new code wherever possible.
Once https://github.com/golang/go/issues/45886 or the corresponding functionality for the `x/net` package comes available, we'll use that to avoid the memory allocations for the addresses.
</blockquote></details>

I think it makes more sense to change this as soon as that functionality is available because the ipv4.Message struct still requires a net.Addr address and I was not able to find an efficient way to convert from netip.AddrPort back to net.Addr.
___
*[`router/dataplane.go` line 126 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXRW3gE9HS8v5VZ52KD:-NXfn1CJ6rNnuufyMkNf:bye0osy) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L126)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

See comment on structure; none of these fields need to be here. These can all be local variables in the `Run` function instead.
</blockquote></details>

I moved all fields except those for the packet pool and the channels to a new struct called RunConfig.
___
*[`router/dataplane.go` line 484 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXQP5O92B2uWOqpvxZ1:-NXfnDclDKTg6ZwhYib0:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L484)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Don't use floats for this stuff, please. Define a `max(a, b int) int` somewhere or just use an if.
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 510 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXPlRTk-Ojev03M1dxc:-NXfnEst5ezzCbUOrKRX:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L510)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This does _all_ the work of the actual running, so the name `initComponents` seems deceptive; I think just having this all in `Run` is just fine.
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 584 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXPmPBYAK18FCfUD45f:-NXfnK00-MkVHH1kVMV7:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L584)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The shutdown logic of waiting for the goroutines to stop and closing the channels does not seem to add anything. It also seems to be in a race against the process termination. 
Just fire-and-forget the go routines. Consequently, remove the error groups.
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 591 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXRUiFZ9JNS292c7x0g:-NXfnL_x76xODCnvnR-9:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L591)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I don't think we need this struct. `Addr` is unused, so this is the same information as eg. a `map[uint16]BatchConn` which is already present in `Dataplane`.
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 614 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXPrrm90gyAPABC_1JI:-NXfng2mA-b24X9I8BFz:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L614)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

No need to maintain the `newBufferCount` variable:
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 616 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXPpZMr3HGdt9kuEyR9:-NXfnyO2BWccp0K3O5qt:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L616)):*
> ```Go
> 		for newBufferCount+unusedBufferCount < d.interfaceBatchSize {
> 			p := <-d.packetPool
> 			msgs[newBufferCount].Buffers[0] = p.rawPacket[:bufSize]
> ```

Done.
___
*[`router/dataplane.go` line 622 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXPskyfC7RbRWKauVl2:-NXfntDg780AMRfDSJtw:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L622)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

It's always the full batch size
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 625 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXPsza99_YvUcpkvrM_:-NXfvmuH-IhKqEDThY6P:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L625)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Just set the `unusedBufferCount` directly after the read (before error handling), so it only needs to be updated once:
`unusedBufferCount = len(msgs) - numPkts`.
 [...]

2023-06-12 11:51 UTC, matzf requested changes
> Reviewed 3 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351)* status: 3 of 6 files reviewed, 19 unresolved discussions (waiting on @rohrerj)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4351#-NXQK404AiX1NOVbk1Z_:-NXj2FLw7c09EYpxc3OU:b-8fx2u7) (no related file):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

I restructured the run functions. Is it better now?
</blockquote></details>

:+1: 

___
___
*[`router/dataplane.go` line 598 at r1](https://reviewable.io/reviews/scionproto/scion/4351#-NXGulII-rAsojbdlYnN:-NXiqqz67QbbcFmaoA7a:b-gxztsp) ([raw file](https://github.com/scionproto/scion/blob/8032c1d6d008900d9e309a7cc09be2dac4011560/router/dataplane.go#L598)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

I think it makes more sense to change this as soon as that functionality is available because the ipv4.Message struct still requires a net.Addr address and I was not able to find an efficient way to convert from netip.AddrPort back to net.Addr.
</blockquote></details>

Fair enough.
___
*[`router/dataplane.go` line 126 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXRW3gE9HS8v5VZ52KD:-NXiVGLb9F-8QsHlKaII:b3w5wvh) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L126)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

I moved all fields except those for the packet pool and the channels to a new struct called RunConfig.
</blockquote></details>

Better. IMO it would be better still to move all of these into `Run` and pass them around explicitly, but ok to leave it.

At least the `interfaces` one needs to be fixed though; either remove it entirely, keep it as a local variable, or move it up to the existing fields `external`/`internal` and initialize it together with these.
___
*[`router/dataplane.go` line 792 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXR9NRs3WyjOl5PCuMy:-NXin4ZCCo_lFSUSB0XB:b2d7nyn) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L792)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

I created such a function.
</blockquote></details>

What I had in mind when I suggested this function was that this would block for the first packet (only) and then use non-blocking read using `select` to read the available entries. 
Now we're using the channel `len` to determine the number of available packets and use `max(1, len(c))` to wait block for at least one. This is not ideal; if the channel is initially empty, this will always read only a single message. However, it is possible (even likely) that multiple packets are added to the channel "simultaneously" (while this goroutine is sleeping) and so we needlessly use a low batch size.
As we now don't want to block when we have re-try packets, perhaps extend the interface with a number of packets for blocking read, `func readUpTo(c chan<- packet, nBlocking, nNonblocking, int, msg[]ipv4.Message) int`.
___
*[`router/dataplane.go` line 793 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXQVAE-9p1yv_mamMGo:-NXiaC774Zbjt56AX-Y6:b3kfvki) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L793)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

I changed the implementation. Additionally to what you suggested I rearranged the packets to prevent packet reordering.
E.g. we have the packets 1, 2, 3, ... 8 in the queue and the batch [1,2,3,4]. If we have an error on packet 3, packet 1 and 2 were sent successfully, packet 3 is dropped and the next batch would look like [4,5,6,7].
</blockquote></details>

Great! The logic looks good now! 
I think it could be clarified a bit though; instead of re-arranging right after reading, first return the processed buffers back to the pool, then we can simply move up the packets from the back (simply overwriting the packets previously there):
```
	numWritten, _ := conn.WriteBatch(msg, 0)
        // accounting for metrics
        bytesWritten := sumBytes(msg[:numWritten])
        // return consumed packets
        for i := 0; i < numWritten + 1 && i < len(msg); i++ {
          returnPacketToPool(msg[i].Buffer[0])
        }
        // move up the re-try packets
        for i := numWritten + 1, j :=0 ; i < len(msg); i++, j++ {
          msg[j].Buffer[0] = msg[i].Buffer[0]
        }
```
___
*[`router/dataplane.go` line 832 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXPjXTyEZc1BPg5GCy5:-NXipEe81UbWmD4EKeRx:b-u6ozqd) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L832)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

We still have to identify the BFD case. Should I just add a new field "isBFD" or do you have any other suggestion?
</blockquote></details>

Make `OutPkt` nil.
___
*[`router/dataplane.go` line 473 at r4](https://reviewable.io/reviews/scionproto/scion/4351#-NXj2UgXE2i6IxLEcwN9:-NXj2UgXE2i6IxLEcwNA:bm3xmh4) ([raw file](https://github.com/scionproto/scion/blob/1bc5b6b8acc6fdef454f0cf98d6f213d70904b47/router/dataplane.go#L473)):*
> ```Go
> 	d.populateInterfaces()
> 
> 	cfg.ProcessorQueueSize = max(
> ```

Make this a local variable instead.
Same for `ForwarderQueueSize`, initialized from `InterfaceBatchSize`.
___
*[`router/dataplane.go` line 484 at r4](https://reviewable.io/reviews/scionproto/scion/4351#-NXj33Y93obHyBqDGWwh:-NXj33Y93obHyBqDGWwi:bwp04e5) ([raw file](https://github.com/scionproto/scion/blob/1bc5b6b8acc6fdef454f0cf98d6f213d70904b47/router/dataplane.go#L484)):*
> ```Go
> 			defer log.HandlePanic()
> 			d.runReceiver(interfaceId, conn, cfg)
> 		}(interfaceId, conn)
> ```

Perhaps the `runXXX` functions could be documented to be run as a goroutine and do the `log.HandlePanic` internally. Then this can be shortened for better readability:
```
for interfaceId, conn := range interfaces {
   interfaceId, conn := interfaceId, conn // sic
   go d.runReceiver(interfaceId, conn, cfg)
   go d.runForwarder(interfaceId, conn, cfg)
}
```
And the same for the other goroutine invocations here.

And btw, as pointed out in the comment on the fields of Dataplane, I think the overall structure would be even clearer if the queues are local variables here and the `runXXX` would take their queues explicitly here, e.g.

```
   go runReceiver(cfg, interfaceId, conn, processorQueues)
   go runForwarder(cfg, interfaceId, forwarderQueues[interfaceId], conn)
// ...

   go runProcessor(cfg, processorQueues[i], forwarderQueues)

```
___
*[`router/dataplane.go` line 520 at r4](https://reviewable.io/reviews/scionproto/scion/4351#-NXiUkR51LmEbXuStvPD:-NXiUkR51LmEbXuStvPE:bcgp2tv) ([raw file](https://github.com/scionproto/scion/blob/1bc5b6b8acc6fdef454f0cf98d6f213d70904b47/router/dataplane.go#L520)):*
> ```Go
> 	r.RandomValue = make([]byte, 16)
> 	if _, err := rand.Read(r.RandomValue); err != nil {
> 		log.Error("Error while generating random value", "err", err)
> ```

This should likely be fatal. It's not really a configuration property anyway, there is no point Perhaps it's easier to move the random value as a local into the `Run` func, then you don't need to add an error return value to this function.

Btw, the receivers could also have different random values each, so you could move this even further down.
___
*[`router/dataplane.go` line 576 at r4](https://reviewable.io/reviews/scionproto/scion/4351#-NXiuebw5xR8LsiY9QVi:-NXiuebw5xR8LsiY9QVj:b-4ud17b) ([raw file](https://github.com/scionproto/scion/blob/1bc5b6b8acc6fdef454f0cf98d6f213d70904b47/router/dataplane.go#L576)):*
> ```Go
> 	numReusable := 0 // unused buffers from previous loop
> 	metrics := d.forwardingMetrics[interfaceId]
> 	currentPacketsFromPool := make([][]byte, cfg.Inte [...]

2023-06-15 10:14 UTC, matzf requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351)* status: 2 of 6 files reviewed, 7 unresolved discussions (waiting on @rohrerj)

___
*[`router/dataplane.go` line 792 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXR9NRs3WyjOl5PCuMy:-NXoG8_u153FUgZ1q186:b-ibdcar) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L792)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nit: Looking at this and how its used now, it seems that it would be somewhat more natural to pass the total number of packets to read instead of the number of non-blocking. Or alternatively, create a separate function for the blocking vs the non-blocking read.
___
*[`router/dataplane.go` line 484 at r4](https://reviewable.io/reviews/scionproto/scion/4351#-NXj33Y93obHyBqDGWwh:-NXo9EKK-R_Y4wTzDchr:bgzdxyk) ([raw file](https://github.com/scionproto/scion/blob/1bc5b6b8acc6fdef454f0cf98d6f213d70904b47/router/dataplane.go#L484)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

The top part will not compile: "go statement should always call a func lit. (gocall)".
Regarding the lower part, I changed the code to pass de processor and forwarder queues instead of storing them in the dataplane.
</blockquote></details>

Meh, linter getting in the way, ok.
___
*[`router/dataplane.go` line 585 at r4](https://reviewable.io/reviews/scionproto/scion/4351#-NXjI946AXb6aeOK6Iaf:-NXoA3Cd4D62x27GgMSb:b-f6t2hq) ([raw file](https://github.com/scionproto/scion/blob/1bc5b6b8acc6fdef454f0cf98d6f213d70904b47/router/dataplane.go#L585)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

I changed the function to pass already the currPkt instead of the index.
</blockquote></details>

Better, it's still redundant though. `currPkt == pkt.Buffers[0]`.

Btw, rename `pkt` -> `msg` (consistency)
___
*[`router/dataplane.go` line 675 at r4](https://reviewable.io/reviews/scionproto/scion/4351#-NXjPwnHBDx6MuzhbMkS:-NXoC6WKDDI-M3lOxLvs:bfw9u2o) ([raw file](https://github.com/scionproto/scion/blob/1bc5b6b8acc6fdef454f0cf98d6f213d70904b47/router/dataplane.go#L675)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

I removed the ingress parameter from the newPacketProcessor function and added it to the processPkt function. But I don't think it is necessary to add it to the reset() function since we always overwrite it at the beginning of the processPkt function. (same as for srcAddr).
</blockquote></details>

Ok. Also remove the `processor.ingressID = p.ingress` above.
The `reset()` is a bit defensive as the recycling of the state is just inherently somewhat dangerous and its easy to mess up. I'd prefer to keep resetting everything, even if it's pointless.
___
*[`router/dataplane.go` line 731 at r4](https://reviewable.io/reviews/scionproto/scion/4351#-NXiibkWANS2LNrhcFBR:-NXoFYdECS4A1BPxIv3L:biyq8fo) ([raw file](https://github.com/scionproto/scion/blob/1bc5b6b8acc6fdef454f0cf98d6f213d70904b47/router/dataplane.go#L731)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

Right. I renamed it to "batchFillStartIndex".
</blockquote></details>

Hmm, that doesn't sound very good to me either, maybe just `remaining`?

Generally the identifiers used here look a bit jarring. Suggestion:
`batchFillStartIndex` -> `remaining`
`availablePackets` -> `available`
`k` -> `written`
`byteLen` -> `writtenBytes` or `bytesWritten`
___
*[`router/dataplane.go` line 645 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NXyVGI1EqeJacOswVAg:-NXyVGI1EqeJacOswVAh:b-agdqq7) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane.go#L645)):*
> ```Go
> }
> 
> func (d *DataPlane) runProcessingRoutine(id int, c chan packet,
> ```

`c <-chan packet` (read-only)

Ideally, we'd also make the forwarder queues write-only, `fwChans map[uint16]chan<- packet`, and the same for the processing queues in the receiver routines. I don't see a very elegant way to do this without making the initialization overly clumsy.
___
*[`router/dataplane.go` line 698 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NXyQvuB4q0sbXCqTx8n:-NXyQvuB4q0sbXCqTx8o:bm03ded) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane.go#L698)):*
> ```Go
> 
> func (d *DataPlane) runForwarder(interfaceId uint16, conn BatchConn,
> 	cfg *RunConfig, c chan packet) {
> ```

`<-chan  packet` (read only)
___
*[`router/dataplane.go` line 748 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NXoGglH4h-84yfKzuec:-NXoGglI6DkubYk0kp4K:bh0liyj) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane.go#L748)):*
> ```Go
> 
> func readUpTo(c chan packet, nBlocking int, nNonBlocking int, msg []ipv4.Message) int {
> 	assign := func(p *packet, m *ipv4.Message) {
> ```

Sure this `p` does not escape to the heap here? Pass `p packet` to make sure.
___
*[`router/dataplane.go` line 1613 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NXyPTDs1onhkmznTsCv:-NXyPTDt0i9KZtV5pLQr:b7u42t8) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane.go#L1613)):*
> ```Go
> 		}
> 		// OHP should always be directed to the correct BR.
> 		if _, ok := p.d.external[ohp.FirstHop.ConsEgress]; ok {
> ```

This check safely be removed now. There is an explicit check for the validity of the ConsEgress above and this is sufficient as long as the router's internal state is consistent. Also, the same check is now done when looking up the forwarder-queue.


<!-- Sent from Reviewable.io -->

2023-06-15 11:14 UTC, rohrerj reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351)* status: 2 of 6 files reviewed, 7 unresolved discussions (waiting on @matzf)

___
*[`router/dataplane.go` line 585 at r4](https://reviewable.io/reviews/scionproto/scion/4351#-NXjI946AXb6aeOK6Iaf:-NXyib5i79v1qwG_AkwU:b-lfdb7l) ([raw file](https://github.com/scionproto/scion/blob/1bc5b6b8acc6fdef454f0cf98d6f213d70904b47/router/dataplane.go#L585)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Better, it's still redundant though. `currPkt == pkt.Buffers[0]`.

Btw, rename `pkt` -> `msg` (consistency)
</blockquote></details>

You are totally right. I removed it.
___
*[`router/dataplane.go` line 675 at r4](https://reviewable.io/reviews/scionproto/scion/4351#-NXjPwnHBDx6MuzhbMkS:-NXyjAneBvlhMuLZ_e-j:b7y358l) ([raw file](https://github.com/scionproto/scion/blob/1bc5b6b8acc6fdef454f0cf98d6f213d70904b47/router/dataplane.go#L675)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Ok. Also remove the `processor.ingressID = p.ingress` above.
The `reset()` is a bit defensive as the recycling of the state is just inherently somewhat dangerous and its easy to mess up. I'd prefer to keep resetting everything, even if it's pointless.
</blockquote></details>

Then my question is to what should we reset it? Unlike the other fields we cannot set it to nil, and if we set it to 0, we cannot distinguish between a reseted 0 and a normal 0. So I don't really see the point of reseting it. As I wrote above, you also don't reset srcAddr.
___
*[`router/dataplane.go` line 731 at r4](https://reviewable.io/reviews/scionproto/scion/4351#-NXiibkWANS2LNrhcFBR:-NXygMmG2CC7DB9LJPEe:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1bc5b6b8acc6fdef454f0cf98d6f213d70904b47/router/dataplane.go#L731)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Hmm, that doesn't sound very good to me either, maybe just `remaining`?

Generally the identifiers used here look a bit jarring. Suggestion:
`batchFillStartIndex` -> `remaining`
`availablePackets` -> `available`
`k` -> `written`
`byteLen` -> `writtenBytes` or `bytesWritten`

</blockquote></details>

Done.
___
*[`router/dataplane.go` line 645 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NXyVGI1EqeJacOswVAg:-NXyj8-16nV_z9UrlqC3:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane.go#L645)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`c <-chan packet` (read-only)

Ideally, we'd also make the forwarder queues write-only, `fwChans map[uint16]chan<- packet`, and the same for the processing queues in the receiver routines. I don't see a very elegant way to do this without making the initialization overly clumsy.
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 698 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NXyQvuB4q0sbXCqTx8n:-NXygNOrDJqFqLrUAZQE:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane.go#L698)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`<-chan  packet` (read only)
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 748 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NXoGglH4h-84yfKzuec:-NXyggVl08VAhEF1hUrb:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane.go#L748)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Sure this `p` does not escape to the heap here? Pass `p packet` to make sure.
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 1613 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NXyPTDs1onhkmznTsCv:-NXyi1UQ2xSwrJ2qvPnL:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane.go#L1613)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This check safely be removed now. There is an explicit check for the validity of the ConsEgress above and this is sufficient as long as the router's internal state is consistent. Also, the same check is now done when looking up the forwarder-queue.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-16 10:04 UTC, matzf requested changes
> Reviewed 3 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351)* status: all files reviewed, 15 unresolved discussions (waiting on @rohrerj)

___
*[`router/dataplane.go` line 675 at r4](https://reviewable.io/reviews/scionproto/scion/4351#-NXjPwnHBDx6MuzhbMkS:-NY24CXg4SfUeO0abwFp:b-bxgad4) ([raw file](https://github.com/scionproto/scion/blob/1bc5b6b8acc6fdef454f0cf98d6f213d70904b47/router/dataplane.go#L675)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

Then my question is to what should we reset it? Unlike the other fields we cannot set it to nil, and if we set it to 0, we cannot distinguish between a reseted 0 and a normal 0. So I don't really see the point of reseting it. As I wrote above, you also don't reset srcAddr.
</blockquote></details>

Ah, sorry, I misunderstood and didn't see that `srcAddr` is also not reset. My preference would be to reset it anyway (`srcAddr` to `nil`, `interfaceID` to `-1`), but not worth a long discussion.
___
*[`router/dataplane.go` line 453 at r6](https://reviewable.io/reviews/scionproto/scion/4351#-NY2A3Ng35Mr-OUvuW9O:-NY2A3Ng35Mr-OUvuW9P:bcyvk2m) ([raw file](https://github.com/scionproto/scion/blob/10e44800484f36ebbc898d0337e30df9d0dad4e8/router/dataplane.go#L453)):*
> ```Go
> 	NumProcessorRoutines int
> 	InterfaceBatchSize   int
> }
> ```

Collecting a bunch of comments on identifier names here:
-`NumProcessorRoutines`: everywhere else it's process_ing_. Keep it consistent, `NumProcessingRoutines`. To me, also just shorter `NumProcessors` and `runProcessor` etc. would seem good.
- `InterfaceBatchSize` -> `BatchSize`
-  `interfaceId` -> `ifID` (I know it's not entirely consistent in the existing code, but `ifID` is the preferred form
- `...Id` -> `...ID`
- `initializePacketPool`, `initializeChannels` -> shorten to `init....`.
- `forwardingChannels`, `fwChannels`, `procChannels` -> better queue, `initQueues`, `fwQs`, `procQs`, etc.
___
*[`router/dataplane.go` line 620 at r6](https://reviewable.io/reviews/scionproto/scion/4351#-NY2E6Te14-IkZuz_irB:-NY2E6Te14-IkZuz_irC:b-udkuyt) ([raw file](https://github.com/scionproto/scion/blob/10e44800484f36ebbc898d0337e30df9d0dad4e8/router/dataplane.go#L620)):*
> ```Go
> 
> func computeProcId(data []byte, numProcRoutines int, randomValue []byte,
> 	flowIDBuffer [3]byte, hasher hash.Hash32) (uint32, error) {
> ```

`flowIDBuffer` should be passed as a slice here; not entirely sure, but I believe this will now allocate on the heap on each call because of the `hasher.Write`.
___
*[`router/dataplane.go` line 642 at r6](https://reviewable.io/reviews/scionproto/scion/4351#-NY2CudW80TVoo8umWgG:-NY2CudW80TVoo8umWgH:bfxrlnd) ([raw file](https://github.com/scionproto/scion/blob/10e44800484f36ebbc898d0337e30df9d0dad4e8/router/dataplane.go#L642)):*
> ```Go
> 
> func (d *DataPlane) returnPacketToPool(pkt []byte) {
> 	d.packetPool <- pkt[:bufSize]
> ```

Nit: `pkt[:cap(pkt)]` might be clearer. 

More important: decide on whether to reset the length here or when popping from the pool in the receiver. We currently do it twice.
___
*[`router/dataplane.go` line 727 at r6](https://reviewable.io/reviews/scionproto/scion/4351#-NY274xo-ddV6URPgPo2:-NY274xo-ddV6URPgPo3:blap58) ([raw file](https://github.com/scionproto/scion/blob/10e44800484f36ebbc898d0337e30df9d0dad4e8/router/dataplane.go#L727)):*
> ```Go
> 		for i, pkt := range writeMsgs[:written] {
> 			writtenBytes += len(pkt.Buffers[0])
> 			d.returnPacketToPool(writeMsgs[i].Buffers[0])
> ```

Nit: use either `pkt` or `writeMsgs[i]`, not both. My preference is`writeMsgs[i]` (as it seems more consistent with the expressions int the `written!=available` case) and drop the `pkt` identifier.
___
*[`router/dataplane_internal_test.go` line 75 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2FVla4F3mp9hZ4gMB:-NY2FVla4F3mp9hZ4gMC:b-f7gr2r) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L75)):*
> ```Go
> 						spkt, gopacket.Payload(payload))
> 					require.NoError(t, err)
> 					raw := buffer.Bytes()
> ```

Replace `prepBaseMsg` with a helper that returns a fully serialized SCION message. Here we don't care at all what is in this message, so hide everything away.
In fact, I think this doesn't even have to be a proper SCION packet, as long as it's sufficiently long for the computeProcID to succeed.
___
*[`router/dataplane_internal_test.go` line 94 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2Fy7_1YKWi6Xn-l-_:-NY2Fy7_1YKWi6Xn-l-a:b39w6wu) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L94)):*
> ```Go
> 		return ret
> 	}
> 	dp := prepareDP(ctrl)
> ```

If we don't have multiple subtests, then there is no reason to keep the `prepDP` in a `func`. Just inline it here, and leave out everything that is not relevant for this testcase.
___
*[`router/dataplane_internal_test.go` line 111 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2dJD75ScUpSDLoLcZ:-NY2dJD75ScUpSDLoLc_:b-th4eyd) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L111)):*
> ```Go
> 		case <-procCh[0]:
> 			// make sure that the pool size has decreased
> 			assert.Greater(t, initialPoolSize, len(dp.packetPool))
> ```

Also check that the buffer and address are returned correctly
___
*[`router/dataplane_internal_test.go` line 146 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2OiYF8Aj718HqKVRP:-NY2OiYF8Aj718HqKVRQ:b-ud0ipb) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L146)):*
> ```Go
> 					totalCount--
> 					// 1/5 of the packets (randomly chosen) are errors
> 					if scrypto.RandInt64()%5 == 0 {
> ```

The `scrypto` stuff is a bit odd. Just `math/rand` suffices.
___
*[`router/dataplane_internal_test.go` line 159 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2d66P7yCcsTHQy4Xr:-NY2d66P7yCcsTHQy4Xs:b-wxd2tv) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L159)):*
> ```Go
> 							done <- struct{}{}
> 						}
> 						expectedPktId++
> ```

Perhaps also add a check for the `dstAddr` (both for `nil` and non-`nil` case).
___
*[`router/dataplane_internal_test.go` line 223 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2JFQS7ztgBpgUTGTJ:-NY2JFQS7ztgBpgUTGTK:b-d5a7xv) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L223)):*
> ```Go
> 		hasher.Write(randomValue)
> 		hasher.Write(flowBuf[1:4])
> 		if err := s.SerializeAddrHdr(tmpBuffer); err != nil {
> ```

No need to be efficient here, allocate the `tmpBuffer := make([]byte, s.AddrHdrLen()]` here for max simplicity.
Also move the extraction of the flow ID into this function. Then the signature is just `func(s *slayers.SCION) uint32`.
___
*[`router/dataplane_internal_test.go` line 263 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2Hup29ZnGFr_OYpfx:-NY2Hup29ZnGFr_OYpfy:bsxfn7v) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L263)):*
> ```Go
> 	dpath.HopFields[2].Mac = computeMAC(t, key,
> 		dpath.InfoFields[0], dpath.HopFields[2])
> 	spkt.Path = dpath
> ```

Again, use a helper function to create some opaque SCION packet here, the path etc is not relevant here.
___
*[`router/dataplane_internal_test.go` line 283 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2Jvv77dPf1zSFVWMk:-NY2Jvv77dPf1zSFVWMl:be7qcsr) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L283)):*
> ```Go
> 		compareHash(payload, spkt)
 [...]

2023-06-16 15:29 UTC, rohrerj reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351)* status: 2 of 6 files reviewed, 14 unresolved discussions (waiting on @matzf)

___
*[`router/dataplane.go` line 675 at r4](https://reviewable.io/reviews/scionproto/scion/4351#-NXjPwnHBDx6MuzhbMkS:-NY2hKWo2XWd29zrolc8:b28zee0) ([raw file](https://github.com/scionproto/scion/blob/1bc5b6b8acc6fdef454f0cf98d6f213d70904b47/router/dataplane.go#L675)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Ah, sorry, I misunderstood and didn't see that `srcAddr` is also not reset. My preference would be to reset it anyway (`srcAddr` to `nil`, `interfaceID` to `-1`), but not worth a long discussion.
</blockquote></details>

We use as a datatype to store the interface ids uint16. Because of that we cannot set it to -1. But to not overcomplicate that change I reset it now to 0.
___
*[`router/dataplane.go` line 453 at r6](https://reviewable.io/reviews/scionproto/scion/4351#-NY2A3Ng35Mr-OUvuW9O:-NY3m-Eu2m3Pm_A2UXk2:b-wvmewa) ([raw file](https://github.com/scionproto/scion/blob/10e44800484f36ebbc898d0337e30df9d0dad4e8/router/dataplane.go#L453)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Collecting a bunch of comments on identifier names here:
-`NumProcessorRoutines`: everywhere else it's process_ing_. Keep it consistent, `NumProcessingRoutines`. To me, also just shorter `NumProcessors` and `runProcessor` etc. would seem good.
- `InterfaceBatchSize` -> `BatchSize`
-  `interfaceId` -> `ifID` (I know it's not entirely consistent in the existing code, but `ifID` is the preferred form
- `...Id` -> `...ID`
- `initializePacketPool`, `initializeChannels` -> shorten to `init....`.
- `forwardingChannels`, `fwChannels`, `procChannels` -> better queue, `initQueues`, `fwQs`, `procQs`, etc.
</blockquote></details>

I renamed everything I found within my code.
___
*[`router/dataplane.go` line 620 at r6](https://reviewable.io/reviews/scionproto/scion/4351#-NY2E6Te14-IkZuz_irB:-NY2gd-fCNMA1QzqPTSo:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/10e44800484f36ebbc898d0337e30df9d0dad4e8/router/dataplane.go#L620)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`flowIDBuffer` should be passed as a slice here; not entirely sure, but I believe this will now allocate on the heap on each call because of the `hasher.Write`.
</blockquote></details>

Done.
___
*[`router/dataplane.go` line 642 at r6](https://reviewable.io/reviews/scionproto/scion/4351#-NY2CudW80TVoo8umWgG:-NY2gt_g3_WjfqYczem4:b-y6mia2) ([raw file](https://github.com/scionproto/scion/blob/10e44800484f36ebbc898d0337e30df9d0dad4e8/router/dataplane.go#L642)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: `pkt[:cap(pkt)]` might be clearer. 

More important: decide on whether to reset the length here or when popping from the pool in the receiver. We currently do it twice.
</blockquote></details>

Right. I decided to reset the length in the returnPacketToPool function.
___
*[`router/dataplane_internal_test.go` line 75 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2FVla4F3mp9hZ4gMB:-NY2lxn71Y5e9EDCVbDl:bqnh0ca) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L75)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Replace `prepBaseMsg` with a helper that returns a fully serialized SCION message. Here we don't care at all what is in this message, so hide everything away.
In fact, I think this doesn't even have to be a proper SCION packet, as long as it's sufficiently long for the computeProcID to succeed.
</blockquote></details>

I changed the preBaseMsg function to include a lot of stuff that we don't really care about. But I think it still makes sense to return a *slayers.SCION because the TestComputeProcId function still requires it for easier comparison.
___
*[`router/dataplane_internal_test.go` line 94 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2Fy7_1YKWi6Xn-l-_:-NY2oSLY6GtKQfhZEXCK:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L94)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

If we don't have multiple subtests, then there is no reason to keep the `prepDP` in a `func`. Just inline it here, and leave out everything that is not relevant for this testcase.
</blockquote></details>

Done.
___
*[`router/dataplane_internal_test.go` line 111 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2dJD75ScUpSDLoLcZ:-NY2qx5w60711z1c61Hy:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L111)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Also check that the buffer and address are returned correctly
</blockquote></details>

Done.
___
*[`router/dataplane_internal_test.go` line 146 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2OiYF8Aj718HqKVRP:-NY2rgQ6Czh9OdncrfcH:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L146)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The `scrypto` stuff is a bit odd. Just `math/rand` suffices.
</blockquote></details>

Done.
___
*[`router/dataplane_internal_test.go` line 159 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2d66P7yCcsTHQy4Xr:-NY3BbFW34l5S4Q8RHGE:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L159)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Perhaps also add a check for the `dstAddr` (both for `nil` and non-`nil` case).
</blockquote></details>

Done.
___
*[`router/dataplane_internal_test.go` line 223 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2JFQS7ztgBpgUTGTJ:-NY3ByTi7wzxvMzl2YBl:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L223)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

No need to be efficient here, allocate the `tmpBuffer := make([]byte, s.AddrHdrLen()]` here for max simplicity.
Also move the extraction of the flow ID into this function. Then the signature is just `func(s *slayers.SCION) uint32`.
</blockquote></details>

Done.
___
*[`router/dataplane_internal_test.go` line 263 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2Hup29ZnGFr_OYpfx:-NY3C4ZL3cTrZdoYof8b:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L263)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Again, use a helper function to create some opaque SCION packet here, the path etc is not relevant here.
</blockquote></details>

Done.
___
*[`router/dataplane_internal_test.go` line 283 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2Jvv77dPf1zSFVWMk:-NY3CA8I9IezuOFnVLKd:b-phwan1) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L283)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Great that this is testing on multiple inputs.
Subtests are typically organized the other way around; instead of defining a helper function that does the actual check, we typically create tables/maps/... (whatever works) with test cases and then have a loop that contains the test logic with each defined test case. This helps to make it very [...]

2023-06-19 09:00 UTC, matzf requested changes
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351)* status: all files reviewed, 8 unresolved discussions (waiting on @rohrerj)

___
*[`router/dataplane_internal_test.go` line 75 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2FVla4F3mp9hZ4gMB:-NYHVd6xAMD-FWKJf5uz:bsps4ss) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L75)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

I changed the preBaseMsg function to include a lot of stuff that we don't really care about. But I think it still makes sense to return a *slayers.SCION because the TestComputeProcId function still requires it for easier comparison.
</blockquote></details>

Just create a separate helper function for that too that includes the serialization part, `prepRawMsg` or something like that.
___
*[`router/dataplane_internal_test.go` line 94 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2Fy7_1YKWi6Xn-l-_:-NYHWkD97G2s9G3tjv9t:b1buwfy) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L94)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Are `SetIA` and `SetKey` really needed?
___
*[`router/dataplane_internal_test.go` line 113 at r7](https://reviewable.io/reviews/scionproto/scion/4351#-NYHkflAA9aLQoRsVUZL:-NYHkflAA9aLQoRsVUZM:bvrn34e) ([raw file](https://github.com/scionproto/scion/blob/940e6c1651d2edd5aadf243f42c8a99818c2c724/router/dataplane_internal_test.go#L113)):*
> ```Go
> 			}
> 		}
> 	}
> ```

At the end, we can check that the pool size has decreased by exactly the number of packets read. And perhaps it could also make sense to verify that each packet buffer is returned exactly once (e.g by stuffing `reflect.ValueOf(pkt.rawPacket).Pointer()` into a set `map[uinptr]struct{}`).
___
*[`router/dataplane_internal_test.go` line 151 at r7](https://reviewable.io/reviews/scionproto/scion/4351#-NYHgWuX3OKHweJ2VhY9:-NYHgWuX3OKHweJ2VhYA:bpvtgjb) ([raw file](https://github.com/scionproto/scion/blob/940e6c1651d2edd5aadf243f42c8a99818c2c724/router/dataplane_internal_test.go#L151)):*
> ```Go
> 						}
> 						if totalCount <= 100 {
> 							if m.Addr == nil {
> ```

`assert.True(t, m.Addr == nil)` for `nil` case, and add a comment like `// stronger check than assert.Nil`
`assert.NotNil(t, m.Addr)` for not-`nil` (which is stronger than `m.Addr != nil`).
___
*[`router/dataplane_internal_test.go` line 233 at r7](https://reviewable.io/reviews/scionproto/scion/4351#-NYH_iK3C1-n-ShRiu2i:-NYH_iK3C1-n-ShRiu2j:bpiw00r) ([raw file](https://github.com/scionproto/scion/blob/940e6c1651d2edd5aadf243f42c8a99818c2c724/router/dataplane_internal_test.go#L233)):*
> ```Go
> 		hasher.Write(flowBuf[1:4])
> 		if err := s.SerializeAddrHdr(tmpBuffer); err != nil {
> 			return 0
> ```

panic / fail test here
___
*[`router/dataplane_internal_test.go` line 254 at r7](https://reviewable.io/reviews/scionproto/scion/4351#-NYHZTKO4vaXc8lczSpp:-NYHZTKO4vaXc8lczSpq:bhxbnp9) ([raw file](https://github.com/scionproto/scion/blob/940e6c1651d2edd5aadf243f42c8a99818c2c724/router/dataplane_internal_test.go#L254)):*
> ```Go
> 		val2, err := computeProcID(raw, numProcs, randomValue, flowIdBuffer, hasher)
> 		assert.NoError(t, err)
> 		assert.Equal(t, val1, val2)
> ```

This is now not using the right `t` to show failing subtests (`t` here is the main test case, not a subtest). 

Generally, just pass the test case `t *testing.T` as first argument to such helper functions. Here, there seems to be a better approach though: instead of doing the comparison in `compareHash`,  change this into a helper function to call `computeProcID` (i.e. remove the call to `hashForScionPacket` here). 
Then the invocation in the test loop becomes:
```
rs := tc(t);
expected := referenceHash(rs[0].s) // renamed from "hashForSionPacket"
for i, r := range rs {
	actual, err := computeProcIDHelper(r.payload, r.s)
        assert.NoError(t, err)
        assert.Equal(t, expected, actual)
}
```
___
*[`router/dataplane_internal_test.go` line 477 at r7](https://reviewable.io/reviews/scionproto/scion/4351#-NYHY2278UyMaHlk3wfz:-NYHY2278UyMaHlk3wg-:b-mj7fb5) ([raw file](https://github.com/scionproto/scion/blob/940e6c1651d2edd5aadf243f42c8a99818c2c724/router/dataplane_internal_test.go#L477)):*
> ```Go
> 	dpath.HopFields[2].Mac = computeMAC(t, []byte("testkey_xxxxxxxx"),
> 		dpath.InfoFields[0], dpath.HopFields[2])
> 	spkt.Path = dpath
> ```

Just drop mac computation, it's not necessary here.


<!-- Sent from Reviewable.io -->

2023-06-19 10:51 UTC, rohrerj reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @matzf)

___
*[`router/dataplane_internal_test.go` line 75 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2FVla4F3mp9hZ4gMB:-NYIGWkRDYbdZC683Z5y:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L75)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Just create a separate helper function for that too that includes the serialization part, `prepRawMsg` or something like that.
</blockquote></details>

Done.
___
*[`router/dataplane_internal_test.go` line 94 at r5](https://reviewable.io/reviews/scionproto/scion/4351#-NY2Fy7_1YKWi6Xn-l-_:-NYI6KHK5ZuTpsAUP0ET:b827p0j) ([raw file](https://github.com/scionproto/scion/blob/9fa916159949aff46a87284f4d4f2351a514aecb/router/dataplane_internal_test.go#L94)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Are `SetIA` and `SetKey` really needed?
</blockquote></details>

No. You are right. This was stilll a leftover when I copied that part from another test. Since we don't call the packet processing function we don't need that. Removed.
___
*[`router/dataplane_internal_test.go` line 113 at r7](https://reviewable.io/reviews/scionproto/scion/4351#-NYHkflAA9aLQoRsVUZL:-NYI85zr6DNrVM87huXV:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/940e6c1651d2edd5aadf243f42c8a99818c2c724/router/dataplane_internal_test.go#L113)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

At the end, we can check that the pool size has decreased by exactly the number of packets read. And perhaps it could also make sense to verify that each packet buffer is returned exactly once (e.g by stuffing `reflect.ValueOf(pkt.rawPacket).Pointer()` into a set `map[uinptr]struct{}`).
</blockquote></details>

Done.
___
*[`router/dataplane_internal_test.go` line 151 at r7](https://reviewable.io/reviews/scionproto/scion/4351#-NYHgWuX3OKHweJ2VhY9:-NYIAWGc9Rxc9S4od1JI:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/940e6c1651d2edd5aadf243f42c8a99818c2c724/router/dataplane_internal_test.go#L151)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`assert.True(t, m.Addr == nil)` for `nil` case, and add a comment like `// stronger check than assert.Nil`
`assert.NotNil(t, m.Addr)` for not-`nil` (which is stronger than `m.Addr != nil`).
</blockquote></details>

Done.
___
*[`router/dataplane_internal_test.go` line 233 at r7](https://reviewable.io/reviews/scionproto/scion/4351#-NYH_iK3C1-n-ShRiu2i:-NYIAeRm5c0Otwl_p6cU:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/940e6c1651d2edd5aadf243f42c8a99818c2c724/router/dataplane_internal_test.go#L233)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

panic / fail test here
</blockquote></details>

Done.
___
*[`router/dataplane_internal_test.go` line 254 at r7](https://reviewable.io/reviews/scionproto/scion/4351#-NYHZTKO4vaXc8lczSpp:-NYID3qq42KkwebywzI4:b-svlmji) ([raw file](https://github.com/scionproto/scion/blob/940e6c1651d2edd5aadf243f42c8a99818c2c724/router/dataplane_internal_test.go#L254)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This is now not using the right `t` to show failing subtests (`t` here is the main test case, not a subtest). 

Generally, just pass the test case `t *testing.T` as first argument to such helper functions. Here, there seems to be a better approach though: instead of doing the comparison in `compareHash`,  change this into a helper function to call `computeProcID` (i.e. remove the call to `hashForScionPacket` here). 
Then the invocation in the test loop becomes:
```
rs := tc(t);
expected := referenceHash(rs[0].s) // renamed from "hashForSionPacket"
for i, r := range rs {
	actual, err := computeProcIDHelper(r.payload, r.s)
        assert.NoError(t, err)
        assert.Equal(t, expected, actual)
}
```
</blockquote></details>

Right, this look cleaner.
___
*[`router/dataplane_internal_test.go` line 477 at r7](https://reviewable.io/reviews/scionproto/scion/4351#-NYHY2278UyMaHlk3wfz:-NYIAm4h23xs35qSHiUL:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/940e6c1651d2edd5aadf243f42c8a99818c2c724/router/dataplane_internal_test.go#L477)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Just drop mac computation, it's not necessary here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-19 13:05 UTC, matzf requested changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @rohrerj)

___
*[`router/dataplane_internal_test.go` line 151 at r7](https://reviewable.io/reviews/scionproto/scion/4351#-NYHgWuX3OKHweJ2VhY9:-NYIi7zz90OwdmquKfex:bb15wkm) ([raw file](https://github.com/scionproto/scion/blob/940e6c1651d2edd5aadf243f42c8a99818c2c724/router/dataplane_internal_test.go#L151)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

Done.
</blockquote></details>

For the second check `assert.NotNil` would be better as it also checks that the value contained in the interface is non-nil.
___
*[`router/dataplane_internal_test.go` line 105 at r8](https://reviewable.io/reviews/scionproto/scion/4351#-NYIjVEA74g7LE6QOk_B:-NYIjVEA74g7LE6QOk_C:bsyn5ed) ([raw file](https://github.com/scionproto/scion/blob/8bb23d02ed03919bd4f7ab69d9b77fca0f357339/router/dataplane_internal_test.go#L105)):*
> ```Go
> 		}
> 	}
> 	time.Sleep(time.Millisecond)
> ```

Is this sleep to wait for the receiver to acquire new packets from the pool?
Sleeps like this are always finicky as it's just so easy to fail on slow or over-utilized machines. Would it make sense to wait for a signal from the third `ReadBatch` call instead?
___
*[`router/dataplane_internal_test.go` line 240 at r8](https://reviewable.io/reviews/scionproto/scion/4351#-NYIio2CDLQtn2UmgbmK:-NYIio2DCiUOfFvFWk6X:b-lazff1) ([raw file](https://github.com/scionproto/scion/blob/8bb23d02ed03919bd4f7ab69d9b77fca0f357339/router/dataplane_internal_test.go#L240)):*
> ```Go
> 
> 		val2, err := computeProcID(raw, numProcs, randomValue, flowIdBuffer, hasher)
> 		return val2, err
> ```

Nit: just `return computeProcID(...)`.


<!-- Sent from Reviewable.io -->

2023-06-19 13:26 UTC, rohrerj reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @matzf)

___
*[`router/dataplane_internal_test.go` line 151 at r7](https://reviewable.io/reviews/scionproto/scion/4351#-NYHgWuX3OKHweJ2VhY9:-NYIoWvD381uDYz_En0i:b-j4s14n) ([raw file](https://github.com/scionproto/scion/blob/940e6c1651d2edd5aadf243f42c8a99818c2c724/router/dataplane_internal_test.go#L151)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

For the second check `assert.NotNil` would be better as it also checks that the value contained in the interface is non-nil.
</blockquote></details>

Sorry I had accidentially changed both to assert.True(). Should be fixed now.
___
*[`router/dataplane_internal_test.go` line 105 at r8](https://reviewable.io/reviews/scionproto/scion/4351#-NYIjVEA74g7LE6QOk_B:-NYIoQCmDQUuMKfryKyb:b-lwoy3u) ([raw file](https://github.com/scionproto/scion/blob/8bb23d02ed03919bd4f7ab69d9b77fca0f357339/router/dataplane_internal_test.go#L105)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Is this sleep to wait for the receiver to acquire new packets from the pool?
Sleeps like this are always finicky as it's just so easy to fail on slow or over-utilized machines. Would it make sense to wait for a signal from the third `ReadBatch` call instead?
</blockquote></details>

I added a done channel to signal when its ready.


<!-- Sent from Reviewable.io -->

2023-06-19 13:42 UTC, rohrerj reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @matzf)

___
*[`router/dataplane.go` line 792 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXR9NRs3WyjOl5PCuMy:-NYIskR81-yxrRPVtPtW:b-m513jt) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L792)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: Looking at this and how its used now, it seems that it would be somewhat more natural to pass the total number of packets to read instead of the number of non-blocking. Or alternatively, create a separate function for the blocking vs the non-blocking read.
</blockquote></details>

Sorry, I was not sure whether this was just a comment or whether you asked me to fix this. I changed now the readUpTo function to accept "n" and a boolean to indicate whether we have to block or not. In case of blocking, we block only on the first element.


<!-- Sent from Reviewable.io -->

2023-06-23 07:34 UTC, matzf approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351)* status: all files reviewed, 1 unresolved discussion (waiting on @rohrerj)

___
*[`router/dataplane.go` line 792 at r3](https://reviewable.io/reviews/scionproto/scion/4351#-NXR9NRs3WyjOl5PCuMy:-NYb6WXyD4a3ErJH4pa5:btojbfd) ([raw file](https://github.com/scionproto/scion/blob/a451e9bec28eb3e790044ae3e1984fe9c3915959/router/dataplane.go#L792)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

Sorry, I was not sure whether this was just a comment or whether you asked me to fix this. I changed now the readUpTo function to accept "n" and a boolean to indicate whether we have to block or not. In case of blocking, we block only on the first element.
</blockquote></details>

Great!
___
*[`router/dataplane.go` line 645 at r9](https://reviewable.io/reviews/scionproto/scion/4351#-NYb8lyxD7iKbPu9zPr4:-NYb8lyxD7iKbPu9zPr5:bf8v2a8) ([raw file](https://github.com/scionproto/scion/blob/b3e22f895408e6b05f7bda1208ed27c86c5cf337/router/dataplane.go#L645)):*
> ```Go
> 
> func (d *DataPlane) runProcessor(id int, c <-chan packet,
> 	fwChans map[uint16]chan packet) {
> ```

Nit: `fwQs`. Also, maybe `c` -> `q`?


<!-- Sent from Reviewable.io -->

2023-06-23 07:53 UTC, matzf commented
Do you have some evaluation on the performance difference that you could attach? My own first test showed slightly _lower_ throughput  -- the test was likely overly simplistic and unreliable, but still it would be great to see some evidence that this is actually a performance _improvement_.

Also good to see would be some profiling info captured when processing some test traffic. The go pprof tool can visualize the allocations made; previously this has been showing that only the strictly necessary allocations were made during packet processing. It would be great to confirm that this is still the case.
It's ok to focus on the happy path for this (no errors, no SCMPs), as we know that this area will need more work anyway.

2023-06-23 10:26 UTC, rohrerj reviewed
I will do a proper performance evaluation in the next few days. I can attach the data once I am done with it.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351#-:-NYblpcLB8k3i0BGPhSo:boczt18)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-07-01 13:23 UTC, rohrerj commented
I ran the evaluation on my test systems. The results can be found in the short report. I also attached a pprof file for the CPU and memory allocations.
[Report.pdf](https://github.com/scionproto/scion/files/11926026/Report.pdf)
[cpu.pb.gz](https://github.com/scionproto/scion/files/11926028/cpu.pb.gz)
[allocs.pb.gz](https://github.com/scionproto/scion/files/11926029/allocs.pb.gz)

2023-07-01 13:30 UTC, rohrerj reviewed
During the evaluation I identified some additional metrics that I found useful. I added them here too. What do you think?
I also found an missing error case for WriteBatch().

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351#-:-NZ7WmYn4zN4vUMBSxX1:bmp2tft)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[`router/dataplane.go` line 710 at r10](https://reviewable.io/reviews/scionproto/scion/4351#-NZAcrNa7FknpVjRdGHB:-NZAcrNa7FknpVjRdGHC:b-q25csp) ([raw file](https://github.com/scionproto/scion/blob/f76dbcf1c9a30f590dc4163207453c55c6aa9c16/router/dataplane.go#L710)):*
> ```Go
> 			writeMsgs[remaining:])
> 		available += remaining
> 		written, _ := conn.WriteBatch(writeMsgs[:available], 0)
> ```

I think we should add some error handling here because conn.WriteBatch() could return "-1" for "written" and then we would panic when accessing writeMsgs[:-1].
How should we handle that case? Should we drop all packets or just the first one and try the other packets again?


<!-- Sent from Reviewable.io -->

2023-07-03 11:08 UTC, matzf requested changes
Great, thanks for the performance report. Good to see that you're seeing a decent throughput improvement.

The pprof reports appears to show that during the test SCMPs were triggered for the egress interface not being up. Is this expected from your setup and the packets that you generate?
Otherwise, the allocations look good, looks like nothing escapes.

One thing that stands out for me on the profile is the huge overhead for "mmsghdr pack" in the `ReadBatch`. This is the temporary structure used to translate the convenient `Message` struct into the syscall arguments and back -- ideally, we'd "fix" this by creating a better ReadBatch API that avoids the translation overhead for the syscall, but that goes beyond the point here.
Note that (almost) the same conversion also happens for `WriteBatch`, but this barely shows up in the profile. The difference between the Read and Write calls is that the Read call _always_ uses the full batch size while the Write calls only use the available packets.
So my interpretation of this is that we're transferring significantly fewer than batch size packets in the write calls. The only two explanations that I can come up with are: we are reading significantly fewer than BatchSize packets per ReadBatch, or we're dropping many packets due to lack of "processors".  Can you tell which one it is?

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351#-:-NZPzZrS4MfJDGnmBBj8:b-h94hxn)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @rohrerj)

___
*[`router/dataplane.go` line 710 at r10](https://reviewable.io/reviews/scionproto/scion/4351#-NZAcrNa7FknpVjRdGHB:-NZPhTHqBnOTxOWEnbZ4:b-kjcdp5) ([raw file](https://github.com/scionproto/scion/blob/f76dbcf1c9a30f590dc4163207453c55c6aa9c16/router/dataplane.go#L710)):*
<details><summary><i>Previously, rohrerj wrote…</i></summary><blockquote>

I think we should add some error handling here because conn.WriteBatch() could return "-1" for "written" and then we would panic when accessing writeMsgs[:-1].
How should we handle that case? Should we drop all packets or just the first one and try the other packets again?
</blockquote></details>

Indeed! I'd stick with just dropping the erroring packet. Handling this more specifically would require the inspect the error and figure out if it's a temporary, recoverable condition or permanent. Unfortunately this is much harder than it sounds.

I'd just add something like `if written < 0 { written = 0 } // WriteBatch returns -1 on error, we just consider this as 0 packets written`.
___
*[`router/metrics.go` line 61 at r11](https://reviewable.io/reviews/scionproto/scion/4351#-NZPpm_q-fTWExBN8qz0:-NZPpm_r5Yhitb8zduc1:b-m3mg9f) ([raw file](https://github.com/scionproto/scion/blob/cdd7865b23ac7aa3d7f9ab16693d0d791e5ac44b/router/metrics.go#L61)):*
> ```Go
> 			},
> 			[]string{"interface", "isd_as", "neighbor_isd_as"},
> 		),
> ```

Packets dropped due to processing errors (previously only these were counted) will nee to be looked at quite differently from packets dropped due to overload. With the current setup of the metrics, this is not very nicely separable.

Perhaps it would be nicer to keep only  `router_dropped_pkts_total` counter but use a `reason` label to split it up. This would be somewhat consistent with the way this is presented in the gateway (`gateway_frames_discarded_total`).  A consumer of the metrics has a clear way to filter which "reasons" it wants to consider for an analysis. 
For the implementation, this would mean: add a `"reason"` label to the creation of `DroppedPacketsTotal` below. In the `forwardingMetrics` you'd keep separate counters, just initialize them from the same `CounterVec` by using different values for the `reason` label.


<!-- Sent from Reviewable.io -->

2023-07-03 12:12 UTC, rohrerj reviewed
The SCMPs were not intended. Does this make a huge difference for the performance evaluation?

When I look at the raw evaluation data for e.g. WSL (100bytes payload) I see an average packet drop due to busy processors of 500pps and due to busy forwarders of 36'000pps. Unfortunately I don't have the data to reason about the actual transferred batch size.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351#-:-NZQUrqh-yeoBh_9ti9G:b-v6w0o1)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[`router/metrics.go` line 61 at r11](https://reviewable.io/reviews/scionproto/scion/4351#-NZPpm_q-fTWExBN8qz0:-NZQelKECpInIL15egZc:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/cdd7865b23ac7aa3d7f9ab16693d0d791e5ac44b/router/metrics.go#L61)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Packets dropped due to processing errors (previously only these were counted) will nee to be looked at quite differently from packets dropped due to overload. With the current setup of the metrics, this is not very nicely separable.

Perhaps it would be nicer to keep only  `router_dropped_pkts_total` counter but use a `reason` label to split it up. This would be somewhat consistent with the way this is presented in the gateway (`gateway_frames_discarded_total`).  A consumer of the metrics has a clear way to filter which "reasons" it wants to consider for an analysis. 
For the implementation, this would mean: add a `"reason"` label to the creation of `DroppedPacketsTotal` below. In the `forwardingMetrics` you'd keep separate counters, just initialize them from the same `CounterVec` by using different values for the `reason` label.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-07 11:38 UTC, matzf requested changes
> The SCMPs were not intended. Does this make a huge difference for the performance evaluation?

I haven't the foggiest. Benchmarking things correctly is very hard. An evaluation that did unexpected things might or might not be reliable. :wink: 

> I see an average packet drop [...] due to busy forwarders of 36'000pps

Together with my suspicion that the write batch size is unexpectedly low, this seems a bit worrying. It just seems like something might not quite be working as we intend it to. It would be great if you could investigate this a bit.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351#-:-NZk6ZGTA_RA-8ysESEJ:b-8x72jq)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @rohrerj)

___
*[`router/dataplane.go` line 2096 at r12](https://reviewable.io/reviews/scionproto/scion/4351#-NZk4AX9AhZYmmrxXrls:-NZk4AXA38UUC8qZJWkf:b-9kerm3) ([raw file](https://github.com/scionproto/scion/blob/e7ddb415e68da94adc57cb8f52174c8c6b1678c5/router/dataplane.go#L2096)):*
> ```Go
> 	}
> 	labels["reason"] = "any"
> 	c.DroppedPacketsTotal = metrics.DroppedPacketsTotal.With(labels)
> ```

The "reasons" should be non-overlapping, so that a consumer can take the sum to get the total number of drops.
Instead of "any", use e.g. "invalid". Perhaps rename the `DroppedPacketsTotal` to something more specific, and adapt the use of the counter accordingly.
___
*[`router/dataplane.go` line 2097 at r12](https://reviewable.io/reviews/scionproto/scion/4351#-NZk54r6EhgriNsHgmnJ:-NZk54r6EhgriNsHgmnK:b-1rzy6m) ([raw file](https://github.com/scionproto/scion/blob/e7ddb415e68da94adc57cb8f52174c8c6b1678c5/router/dataplane.go#L2097)):*
> ```Go
> 	labels["reason"] = "any"
> 	c.DroppedPacketsTotal = metrics.DroppedPacketsTotal.With(labels)
> 	labels["reason"] = "busy processor"
> ```

Conventionally the label values are `snake_case` (see e.g. the result values defined in `pkg/private/prom/prom.go`)


<!-- Sent from Reviewable.io -->

2023-07-07 18:43 UTC, rohrerj reviewed
I investigated it on my local WSL. The code seems to be correct. Based on my investigation I think the packet drop is because of bursty traffic and the go scheduler. It seems like the forwarder goroutine was not selected enough often by the go scheduler. I was able to mitigate the problem by decreasing the batch size and increasing the forwarder queue size.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351#-:-NZla3Oe-gDO8Cmm7A-1:b-l5gjtc)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`router/dataplane.go` line 2096 at r12](https://reviewable.io/reviews/scionproto/scion/4351#-NZk4AX9AhZYmmrxXrls:-NZlc5pa-L52rsg8SFCj:brctcgm) ([raw file](https://github.com/scionproto/scion/blob/e7ddb415e68da94adc57cb8f52174c8c6b1678c5/router/dataplane.go#L2096)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The "reasons" should be non-overlapping, so that a consumer can take the sum to get the total number of drops.
Instead of "any", use e.g. "invalid". Perhaps rename the `DroppedPacketsTotal` to something more specific, and adapt the use of the counter accordingly.
</blockquote></details>

I changed the implementation to use "invalid", "busy_processor" and "busy_forwarder" as reasons. All of them do not overlapp with each other.
___
*[`router/dataplane.go` line 2097 at r12](https://reviewable.io/reviews/scionproto/scion/4351#-NZk54r6EhgriNsHgmnJ:-NZlcT9IDolsnG1_gqq8:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e7ddb415e68da94adc57cb8f52174c8c6b1678c5/router/dataplane.go#L2097)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Conventionally the label values are `snake_case` (see e.g. the result values defined in `pkg/private/prom/prom.go`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-12 13:45 UTC, rohrerj reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351#-:-N_9LI6r2fZrOUDRRRXV:bnfp4nl)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-07-13 09:41 UTC, matzf approved these changes
Ok, sure, with the different goroutines the scheduler becomes more important, that's the deal that we're making with this setup.
Perhaps this is good enough for now, it seems to be a bit better than before and it's not very complicated, so let's just take this.

It would be nice to have somewhat more reliable benchmark setup and results though, so we can also use the information to attempt tracking and tuning this a bit. Perhaps we can look into this as a follow up.

> Reviewed 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351#-:-N_DVAinDEpyumHmuP43:bbakqup)* status: all files reviewed, 1 unresolved discussion (waiting on @rohrerj)

___
*[`router/dataplane.go` line 682 at r13](https://reviewable.io/reviews/scionproto/scion/4351#-N_DU0Wu1mwSxuChrHZJ:-N_DU0Wu1mwSxuChrHZK:b1d6szx) ([raw file](https://github.com/scionproto/scion/blob/baae33cc83f421a6facfcbabd57f37bed71c0b68/router/dataplane.go#L682)):*
> ```Go
> 		}
> 		if result.OutPkt == nil { // e.g. BFD case no message is forwarded
> 			metrics.ProcessedPackets.Inc()
> ```

Shouldn't we count a packet as processed even if there was an error?


<!-- Sent from Reviewable.io -->

2023-07-13 10:28 UTC, rohrerj reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[`router/dataplane.go` line 682 at r13](https://reviewable.io/reviews/scionproto/scion/4351#-N_DU0Wu1mwSxuChrHZJ:-N_DmUQO0Oga3n8hVwOn:b-uyepgm) ([raw file](https://github.com/scionproto/scion/blob/baae33cc83f421a6facfcbabd57f37bed71c0b68/router/dataplane.go#L682)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Shouldn't we count a packet as processed even if there was an error?
</blockquote></details>

Right. When I implemented that I thought about successfully processed packets but since we already have the invalid metrics it makes more sense to just count all.


<!-- Sent from Reviewable.io -->

2023-07-17 09:21 UTC, matzf approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

If there are no further comments here or in the chat, I'll merge this tomorrow.

> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4351#-:-N_Y8UNG3RtbNV6BDwe0:brgll0z)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rohrerj)



<!-- Sent from Reviewable.io -->

2023-07-18 12:52 UTC, merged