Make hiddenpaths registration work both locally and remotely
scionproto/scion pull request #4376
Opened 2023-08-10 13:09 UTC by jiceathome

hidden_paths: Enable registration of hiddenpaths both locally and remotely.

Fixes #4364

There were a number of issues:

* Because the normal case is that the registry is remote, the registerer makes no attempt at using the intraAS network to reach the registry (and the registry isn't listening on TCP). However, quic/scion path resolution to an AS-local host was broken: the resulting paths are expected to be complete paths with Metadata, but intraAS paths were meta-data-less paths, resulting in nill-ptr dereference.
* By default the control service port (shared with the hidden_segment registry) was a dynamic port. The discovery service cannot only knows of statically configured port (configured in the topo file). So the only way to make the hidden_segments service discoverable is to give the control service a static port. While possible, this would result in a confusing and conter-intuitive configuration:
  * the control_service quic address would be configured by the cs yaml file and be different from what appears in the topo file for the CS but identical to the hidden_segment service address.
  * the CS address in the topo file was acually the TCP address and could never be mirrored by the quic address (because that quic address was occupied by the service resolver).
  * the address of the hidden_segments registry in the topo file would be different from that of the CS, eventhough they share the same port.
* This was all invisible to the integration test which was skillfully predicting the dynamic port and configuring the discovery service for it.

To correct these infelicities:
* Give the Svc resolver a dynamic port
* By default, give to the CS and the hidden_segment registry the quic address that has the same IP and port as the control service's TCP address.
* Produce complete Path objects to represent intraAS paths.

In passing:
* A handful of AssertEqual() had arguments in the wrong order.
* In one case we were constructing a full SVC address with a nil path instead of an empty path.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4376)

2023-08-11 14:49 UTC, jiceatscion reviewed
I realize that what I'm doing creates a protocol incompatibility. External code trying to discover the hiddenpaths service in the old way will fail, but then... it was broken already. So I do not know how much we're committed to supporting the old way.

I think there might be a ~simple way of supporting dynamic ports in the Discovery service: could we, in the topo file, permit to refer to services addresses instead of only full addresses? Then the discovery service would know to resolve (and cache) the service address into a direct one in order to answer lookups. Am I even making sense? I'm also trying to validate the fragments of understanding that I think I'm gaining :-)

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376#-:-Nb_1Iil51ajqbbA0ZoT:b-s7znqp)* status: 0 of 53 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-14 07:30 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 0 of 53 files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4376#-NbYZKRxEamsoKP-Ls9A:-NbYZKRxEamsoKP-Ls9B:bfye3g9) (no related file):*
I skimmed the linked issue, and it sounds like the main problem is that we try to send SCION packets for intra AS communication.
There is no need to do this exchange with SCION, and you should be able to just use regular TCP/IP.

Currently, the registry is only served on the InterASQUICServer:
https://github.com/scionproto/scion/blob/4096d879b05a0a7e287bfb79590941facdf40bf4/control/hiddenpaths.go#L81-L103

I think the easiest solution would be to also serve it on `c.IntraASTCPServer`, and this address should be used for intra AS registrations. That also means that there is no need for discovering the dynamic ports, because the intra AS port is static and should be available in the topology file.

cc  @lukedirtwalker 

___


<!-- Sent from Reviewable.io -->

2023-08-14 08:17 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 0 of 53 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4376#-NbYZKRxEamsoKP-Ls9A:-Nbn4B802jXAy2SbdcYD:b-ov6tju) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I skimmed the linked issue, and it sounds like the main problem is that we try to send SCION packets for intra AS communication.
There is no need to do this exchange with SCION, and you should be able to just use regular TCP/IP.

Currently, the registry is only served on the InterASQUICServer:
https://github.com/scionproto/scion/blob/4096d879b05a0a7e287bfb79590941facdf40bf4/control/hiddenpaths.go#L81-L103

I think the easiest solution would be to also serve it on `c.IntraASTCPServer`, and this address should be used for intra AS registrations. That also means that there is no need for discovering the dynamic ports, because the intra AS port is static and should be available in the topology file.

cc  @lukedirtwalker
</blockquote></details>

Thanks. I understand it doesn't make sense to use the SCION network to communicate within the local AS. However, in this case, the registry is expected to be in a different AS. The fact that it happens to be local is circumstantial (just because it is a minimal setup for testing). So, connecting to it by its scion address is normal.

What is the designed approach for such cases? Is the client expected to have access to both addresses and make its own choice or is there a switch somewhere that bypasses the scion network automatically? In the former case, isn't the sub-optimal choice supposed to work anyway? And if so, how much more expensive is it, really?

___


<!-- Sent from Reviewable.io -->

2023-08-14 08:47 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 0 of 53 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4376#-NbYZKRxEamsoKP-Ls9A:-NbnBwbFB3cpAe-jUvMP:b-j0v72c) (no related file):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Thanks. I understand it doesn't make sense to use the SCION network to communicate within the local AS. However, in this case, the registry is expected to be in a different AS. The fact that it happens to be local is circumstantial (just because it is a minimal setup for testing). So, connecting to it by its scion address is normal.

What is the designed approach for such cases? Is the client expected to have access to both addresses and make its own choice or is there a switch somewhere that bypasses the scion network automatically? In the former case, isn't the sub-optimal choice supposed to work anyway? And if so, how much more expensive is it, really?
</blockquote></details>

One more question. You say that the main problem here is the use of SCION for intraAS communications. However, I am under the impression that this is just one way to observe the breakage. If the registry was actually remote, the scion address would be needed and the dynamic port would still prevent the discovery service from having an answer to provide. Am I missing something?

___


<!-- Sent from Reviewable.io -->

2023-08-14 09:25 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 0 of 53 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4376#-NbYZKRxEamsoKP-Ls9A:-NbnI-WhAsL7Ig4n2rh2:b-6nti4n) (no related file):*
> Thanks. I understand it doesn't make sense to use the SCION network to communicate within the local AS. However, in this case, the registry is expected to be in a different AS. The fact that it happens to be local is circumstantial (just because it is a minimal setup for testing). So, connecting to it by its scion address is normal.

I don't quite follow. If the registry is a different AS, it is never local and you always need a SCION path.

But maybe I also didn't quite grasp the initial problem. 

> What is the designed approach for such cases? Is the client expected to have access to both addresses and make its own choice or is there a switch somewhere that bypasses the scion network automatically? In the former case, isn't the sub-optimal choice supposed to work anyway? And if so, how much more expensive is it, really?

What is the "sub-optimal choice supposed to work anyway" in your scenario?

IMO, if the service is local, you always bypass the SCION network and never use SCION with empty path.
There is no need and/or advantage in using SCION here.

> You say that the main problem here is the use of SCION for intraAS communications. However, I am under the impression that this is just one way to observe the breakage. If the registry was actually remote, the scion address would be needed and the dynamic port would still prevent the discovery service from having an answer to provide. Am I missing something?

I have not worked with hidden segments for quite some time now, so my memory is foggy.
But I expect the system to do SVC resolution for remote registries.

We have an acceptance test that tests the functionality https://github.com/scionproto/scion/blob/master/acceptance/hidden_paths/test.py which contains remote registries and has been passing in CI. Do you have a configuration other than local registry where the system does not work?

___


<!-- Sent from Reviewable.io -->

2023-08-14 09:46 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 0 of 53 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4376#-NbYZKRxEamsoKP-Ls9A:-NbnNFwO-89KzLd0zGvW:b-a88zfb) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

> Thanks. I understand it doesn't make sense to use the SCION network to communicate within the local AS. However, in this case, the registry is expected to be in a different AS. The fact that it happens to be local is circumstantial (just because it is a minimal setup for testing). So, connecting to it by its scion address is normal.

I don't quite follow. If the registry is a different AS, it is never local and you always need a SCION path.

But maybe I also didn't quite grasp the initial problem. 

> What is the designed approach for such cases? Is the client expected to have access to both addresses and make its own choice or is there a switch somewhere that bypasses the scion network automatically? In the former case, isn't the sub-optimal choice supposed to work anyway? And if so, how much more expensive is it, really?

What is the "sub-optimal choice supposed to work anyway" in your scenario?

IMO, if the service is local, you always bypass the SCION network and never use SCION with empty path.
There is no need and/or advantage in using SCION here.

> You say that the main problem here is the use of SCION for intraAS communications. However, I am under the impression that this is just one way to observe the breakage. If the registry was actually remote, the scion address would be needed and the dynamic port would still prevent the discovery service from having an answer to provide. Am I missing something?

I have not worked with hidden segments for quite some time now, so my memory is foggy.
But I expect the system to do SVC resolution for remote registries.

We have an acceptance test that tests the functionality https://github.com/scionproto/scion/blob/master/acceptance/hidden_paths/test.py which contains remote registries and has been passing in CI. Do you have a configuration other than local registry where the system does not work?
</blockquote></details>

The registry would typically be in a different AS, but not necessarily. The filer of the issue was deliberately trying to use a local registry for his own purpose. So the registry may be either. In fact, I remember reading somewhere that it was even advisable to register hidden segments as up segments locally in addition to remotely, so that local entities can be aware that they're using a hidden segment (which would therefore not necessarily usable by the other party (that's as much as I understood anyway). So, both would need to work and the local case is not the majority case, even though it's the issue we just ran into.

What I mean by "sub-optimal" is using the SCION network instead of straight TCP to communicate with a host in the same AS. Yes it is unnecessary, but should it not be possible? When you say "You always bypass..." what is "you" in that phrase? Is the using code expected to make the right choice and use the TCP address when the destination is AS-local, or is there a switch layer that does the bypass for you if given both addresses (I don't remember an API resolving a set of addresses but it could very well be there).

The acceptance test passes because it hard codes the predictable (during tests) dynamic address of the registry :-)

___


<!-- Sent from Reviewable.io -->

2023-08-14 11:51 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 0 of 53 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4376#-NbYZKRxEamsoKP-Ls9A:-Nbnq37K5GP5wx0k52Z0:beanqg0) (no related file):*
> The registry would typically be in a different AS, but not necessarily. The filer of the issue was deliberately trying to use a local registry for his own purpose. So the registry may be either. In fact, I remember reading somewhere that it was even advisable to register hidden segments as up segments locally in addition to remotely, so that local entities can be aware that they're using a hidden segment (which would therefore not necessarily usable by the other party (that's as much as I understood anyway). So, both would need to work and the local case is not the majority case, even though it's the issue we just ran into.

I agree that the registry should also work locally. I'm just trying to point out that for AS internal communication, you should use TCP/IP and not QUIC/SCION. To facilitate that, the grpc server needs to be exposed on the AS internal gRPC server too (as alluded to above.)

> When you say "You always bypass..." what is "you" in that phrase?

By "you" I mean the reference implementation. The reference implementation (i.e., this repository) should use TCP/IP for AS internal communication.

> The acceptance test passes because it hard codes the predictable (during tests) dynamic address of the registry :-)

Ack. I was not aware of this hack. That indeed sounds like a problem.

___


<!-- Sent from Reviewable.io -->

2023-08-14 11:54 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 0 of 53 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4376#-NbYZKRxEamsoKP-Ls9A:-NbnsuSG8zFOHYYVXJCw:b-bozm4s) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

> The registry would typically be in a different AS, but not necessarily. The filer of the issue was deliberately trying to use a local registry for his own purpose. So the registry may be either. In fact, I remember reading somewhere that it was even advisable to register hidden segments as up segments locally in addition to remotely, so that local entities can be aware that they're using a hidden segment (which would therefore not necessarily usable by the other party (that's as much as I understood anyway). So, both would need to work and the local case is not the majority case, even though it's the issue we just ran into.

I agree that the registry should also work locally. I'm just trying to point out that for AS internal communication, you should use TCP/IP and not QUIC/SCION. To facilitate that, the grpc server needs to be exposed on the AS internal gRPC server too (as alluded to above.)

> When you say "You always bypass..." what is "you" in that phrase?

By "you" I mean the reference implementation. The reference implementation (i.e., this repository) should use TCP/IP for AS internal communication.

> The acceptance test passes because it hard codes the predictable (during tests) dynamic address of the registry :-)

Ack. I was not aware of this hack. That indeed sounds like a problem.
</blockquote></details>

To solve the dynamic port issue, you could require that an explicit port is required in the QUIC configuration of the control service. In that case, the port is statically allocated and can be configured in the discovery service.

https://github.com/scionproto/scion/blob/4096d879b05a0a7e287bfb79590941facdf40bf4/private/app/appnet/infraenv.go#L105-L107

___


<!-- Sent from Reviewable.io -->

2023-08-14 11:55 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 0 of 53 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4376#-NbYZKRxEamsoKP-Ls9A:-NbntU1P3MrYeyU-Fh1j:b-4jj8ll) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

To solve the dynamic port issue, you could require that an explicit port is required in the QUIC configuration of the control service. In that case, the port is statically allocated and can be configured in the discovery service.

https://github.com/scionproto/scion/blob/4096d879b05a0a7e287bfb79590941facdf40bf4/private/app/appnet/infraenv.go#L105-L107
</blockquote></details>

you could require that an explicit port is required in the QUIC configuration of the control service *if a hidden segment registry is served by the control service*.

___


<!-- Sent from Reviewable.io -->

2023-08-22 11:19 UTC, jiceatscion commented
Thanks!

You're addressing the questions I left in the issue.

> My suggestion would be: get rid of the separate "QUIC" address in the toml configuration and use the "public" address for QUIC instead.

Yup. I want to do that too.

> To avoid clashing this binding with the service redirector, there are a number of solutions:
> ...
>      * use some dummy IP:port address in the `Listen` for the service redirector -- this could be a dynamic port
That is the most straightforward to me. And I already have the code: Dummy Addr -> Quic/public addr. Dummy port -> dynamic.

>     * use the same socket for the service redirector and QUIC. This is easy, as the service redirection is already implemented as a sort of middleware.
Not as simple and not sure of the immediate benefits. I'd rather keep that as part of a dedicated effort to cleanup the service resolution. For example in view of killing the dispatcher?

You didn't mention another possibility:
* Configure the resolver address explicitly.
I Have the code for that too, but I'd like to delete it, unless oncilla@ has a reason to object.

2023-08-22 14:05 UTC, oncilla reviewed
> My suggestion would be: get rid of the separate "QUIC" address in the toml configuration and use the "public" address for QUIC instead. To avoid clashing this binding with the service redirector, there are a number of solutions:

FWIW, I think we are pretty much aligned on this. See: https://github.com/scionproto/scion/issues/4364#issuecomment-1680930657

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376#-:-NcSZ2nl4a1y2qn2TwZW:bo1b386)* status: 0 of 63 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-22 14:06 UTC, jiceatscion reviewed
Done.
Ready for your review.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376#-:-NcSZKCO6YrlYQQRgc5p:b-2kicuu)* status: 0 of 63 files reviewed, all discussions resolved (waiting on @oncilla)



<!-- Sent from Reviewable.io -->

2023-08-22 14:32 UTC, oncilla requested changes
> Reviewed 6 of 17 files at r2, 2 of 11 files at r4, 45 of 50 files at r5, 1 of 1 files at r6, 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: all files reviewed, 2 unresolved discussions (waiting on @jiceatscion)

___
*[`acceptance/hidden_paths/test.py` line 96 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcScrUe2THtef6_8Ske:-NcScrUe2THtef6_8Skf:b-v1gg) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/acceptance/hidden_paths/test.py#L96)):*
> ```Python
>                 / ("%s.toml" % control_id)
>             scion.update_toml({"path.hidden_paths_cfg": hp_config_url}, [control_path])
>             scion.update_toml({"quic.address": control_addresses[as_number]}, [control_path])
> ```

I think this change can be reverted now.
___
*[`control/cmd/control/main.go` line 209 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdCNw4jScU6NlxI3A:-NcSdCNw4jScU6NlxI3B:bj2tt65) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/control/cmd/control/main.go#L209)):*
> ```Go
> 		// Public: (Historical name) The TCP/IP:port address for the control service.
> 		Public: topo.ControlServiceAddress(globalCfg.General.ID),
> 		// ServiceResolution: The UDP/SCION address of the service "redirector".
> ```

Comment does not apply anymore.
___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-NcSdQmoAMJ9eJB_fNjK:bvwtu8r) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
> ```Go
> 	// Else returns nil. The difference between calling this and accessing Metadata().Interfaces is
> 	// that there is no need to check if Metadata() is nil. An alternative could be to have an
> 	// Interfaces() method to PathMetadata that accepts nil, and to call that instead.
> ```

Personally, I prefer a nil-check over extending the API surface of this interface.
Going forward, if we need to access something else from PathMetadata, are we extending the interface for that too?

(non-blocking, given it is a matter of taste) 



_Code quote:_
```Go
Interfaces() method to PathMetadata that accepts nil, and to call that instead.
```


<!-- Sent from Reviewable.io -->

2023-08-22 14:53 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: all files reviewed, 2 unresolved discussions (waiting on @oncilla)

___
*[`acceptance/hidden_paths/test.py` line 96 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcScrUe2THtef6_8Ske:-NcSfR0037PvNHOGGuR_:b-fwyd1l) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/acceptance/hidden_paths/test.py#L96)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I think this change can be reverted now.
</blockquote></details>

Not so sure. Since the quic address mirrors the public address, it is much easier to predict, but that would still be a prediction, unless the test exerts explicit control on the public address too. I will check. Stay tuned.
___
*[`control/cmd/control/main.go` line 209 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdCNw4jScU6NlxI3A:-NcSgBeq9DT2osXUYCZA:b-u3ev7s) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/control/cmd/control/main.go#L209)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Comment does not apply anymore.
</blockquote></details>

Oops. Done.
___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-NcSiFdC-BEtcJWeR9SC:b-adrxnk) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Personally, I prefer a nil-check over extending the API surface of this interface.
Going forward, if we need to access something else from PathMetadata, are we extending the interface for that too?

(non-blocking, given it is a matter of taste)
</blockquote></details>

Forcing a nillcheck on the users defeats a bit the purpose of Path being an interface. If the interface has a Metadata() method one shouldn't rely need to check that it returns something usable. But for that reason I like you alternate proposal. Accepting nil in PathMetadata methods is the logical thing to do in this context. Working on it. Stay tuned.


<!-- Sent from Reviewable.io -->

2023-08-22 15:37 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 62 of 63 files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

___
*[`acceptance/hidden_paths/test.py` line 96 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcScrUe2THtef6_8Ske:-NcSs9Ic9AFvsPm1KyjG:b6tad95) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/acceptance/hidden_paths/test.py#L96)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

It's a bit less than limpid where the test gets its topology from. I can see that it updates it with the hidden_paths services, but I am not entirely sure where the control_service comes from. I can see addresses constructed from sciond_addresses.json by sciond_addr(), but then I do not know if that function is actually used to produce the cs public address. In which case the port would be 30255.
</blockquote></details>

The test is currently doing hack-y hard coding of the QUIC port via the control_addresses dict.

What you want to do instead, is to put the same public address for the hidden_segment_*_service as for the control_service.
The test writes the hidden_segment_*_service public addresses here:

https://github.com/scionproto/scion/blob/d9acea4b6c3bb6463af4a22a48e7c44237a26685/acceptance/hidden_paths/test.py#L101-L108

So, instead of hard coding the address, simply read the control_service address from the topology file in the loop and use the public address for the hidden segment services too.

Thus, we don't even need to care where the values come from. The important bit is just that we get the public address for the control_service and re-use it for the hidden segment services.
___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-NcSrFqL07r_pqFuJx6G:b-bk5ip0) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Oh. I realize the nil receiver wasn't your proposal, it was a comment from myself. So, how about that?
</blockquote></details>

Works for me.


<!-- Sent from Reviewable.io -->

2023-08-22 15:42 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 62 of 63 files reviewed, 1 unresolved discussion (waiting on @oncilla)

___
*[`acceptance/hidden_paths/test.py` line 96 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcScrUe2THtef6_8Ske:-NcStfro8C1NCqWspSXu:b72e754) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/acceptance/hidden_paths/test.py#L96)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

(:shake-fist-at-reviewable: it interpreted my `*` as italic. Above, read `hidden_segment_service` as `hidden_segment_*_service`)
</blockquote></details>

Thanks, yes, I was trying to find where the public address came from in the test context. I don't particularly care where they come from either, but I was trying to avoid writing a bit of silly code that reads from a file if what it reads can be obtained from the code that put it there in the first place... if I can't figure it then yes, I'll just go read the file (or rather add a function in /acceptance/common/scion.py that does just that.


<!-- Sent from Reviewable.io -->

2023-08-22 16:16 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 62 of 63 files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

___
*[`acceptance/hidden_paths/test.py` line 96 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcScrUe2THtef6_8Ske:-NcT01w8AG_mtiCS_P9L:b3n257w) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/acceptance/hidden_paths/test.py#L96)):*
> but I was trying to avoid writing a bit of silly code that reads from a file if what it reads can be obtained from the code that put it there in the first place...

We have abstracted away these details. If you write a test, you don't want to care about port allocations etc.
The test defines a topology in https://github.com/scionproto/scion/blob/master/acceptance/hidden_paths/testdata/topology.topo
Based on this topology description, a complete topology is generated with [topogen](https://github.com/scionproto/scion/blob/master/tools/topogen.py)

So there are two paths to get to the result. Read the file (with helpers or not), or adapt topogen to also generate the hidden segment servers in the topology file.

Given this is a one-off test, I would go for 1. If we add a lot more topologies with hidden segments, it might be worth doing 2.


<!-- Sent from Reviewable.io -->

2023-08-22 16:36 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 61 of 64 files reviewed, 1 unresolved discussion (waiting on @oncilla)

___
*[`acceptance/hidden_paths/test.py` line 96 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcScrUe2THtef6_8Ske:-NcT5gmg74w2cYhxCVVO:b-rnraql) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/acceptance/hidden_paths/test.py#L96)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

> but I was trying to avoid writing a bit of silly code that reads from a file if what it reads can be obtained from the code that put it there in the first place...

We have abstracted away these details. If you write a test, you don't want to care about port allocations etc.
The test defines a topology in https://github.com/scionproto/scion/blob/master/acceptance/hidden_paths/testdata/topology.topo
Based on this topology description, a complete topology is generated with [topogen](https://github.com/scionproto/scion/blob/master/tools/topogen.py)

So there are two paths to get to the result. Read the file (with helpers or not), or adapt topogen to also generate the hidden segment servers in the topology file.

Given this is a one-off test, I would go for 1. If we add a lot more topologies with hidden segments, it might be worth doing 2.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2023-08-23 07:20 UTC, matzf requested changes
All clear, sounds good to me. Sorry, I had missed a part of the discussion in #4364, looks like I mostly restated what you had already discussed.

Shouldn't we also remove the `quic.address` setting entirely now, though? 
While it may appear like this could still be used to specify a SCION address different from the TCP address, this would end up with a really confusing configuration. The other entities (sciond on end hosts, routers) interpret the entry in the `topology.json` as _both_ the TCP and the SCION address -- sciond takes it as the TCP address, the router interprets it as the underlay IP address for SvcCS/DS. Technically, none of these needs to be aware of both addresses, so we _could_ just provide different `topology.json` files to each one, but this seems quite convoluted.

To avoid a configuration-breaking change, we can just ignore it and document it as deprecated.

> Reviewed 5 of 17 files at r2, 1 of 11 files at r4, 45 of 50 files at r5, 8 of 9 files at r7, 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376#-:-NcSS9sbClPSB12EOKdf:b-oin1ig)* status: all files reviewed, 5 unresolved discussions (waiting on @jiceatscion and @oncilla)

___
*[`acceptance/common/scion.py` line 88 at r9](https://reviewable.io/reviews/scionproto/scion/4376#-NcWAuyy905IrCiNQ2ii:-NcWAuyy905IrCiNQ2ij:b-gt5lru) ([raw file](https://github.com/scionproto/scion/blob/cdd27dcc91645c6bd39a2f4ad52c484c9af4cb75/acceptance/common/scion.py#L88)):*
> ```Python
>             t = json.load(f)
>         for path, val in t.items():
>             return val
> ```

As far as I understand, this doesn't do what is advertised.
Note that `path` is not the path, it's only the key of the top level entry. If we want to match an entry by the full path, we'll have to traverse or flatten the dicts explicitly.
___
*[`control/hiddenpaths.go` line 107 at r9](https://reviewable.io/reviews/scionproto/scion/4376#-NcW8siL1GsA-x50fIAz:-NcW8siL1GsA-x50fIB-:b-t1oiiy) ([raw file](https://github.com/scionproto/scion/blob/cdd27dcc91645c6bd39a2f4ad52c484c9af4cb75/control/hiddenpaths.go#L107)):*
> ```Go
> 			c.InterASQUICServer, hsRegistrationService)
> 		hspb.RegisterHiddenSegmentRegistrationServiceServer(
> 			c.IntraASTCPServer, hsRegistrationService)
> ```

I'm not sure, is TCP now really used for the local call? Otherwise, is there any benefit from exposing this?
___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-NcW6Iu1EJstdT6REgy3:b-nmd30h) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Works for me.
</blockquote></details>

I'd prefer to keep the nil-check in the caller. The metadata is simply not available in all cases, so at some point there will have to be a check to figure out if it is there or not.
___
*[`private/app/appnet/addr.go` line 158 at r9](https://reviewable.io/reviews/scionproto/scion/4376#-NcWDJBK7Y6DkBhSEOgO:-NcWDJBK7Y6DkBhSEOgP:b-ht51qf) ([raw file](https://github.com/scionproto/scion/blob/cdd27dcc91645c6bd39a2f4ad52c484c9af4cb75/private/app/appnet/addr.go#L158)):*
> ```Go
> 
> 	// SVC addresses in the local AS get resolved via topology lookup
> 	if len(p.Interfaces()) == 0 { //when local AS
> ```

Directly comparing source and destination ISD-AS would be more robust. This could perhaps be moved before the `Router.Route` call, to make it a bit clearer what's going on here.

With the changes to return a nil Interface list when the metadata is not available, this would now malfunction for "partialPath", i.e for path objects reconstructed from a dataplane path -- the interfaces list is nil/empty even for non-local paths. Not sure if this is ever a use case here, but it might still not be ideal.
___
*[`private/app/appnet/infraenv.go` line 273 at r9](https://reviewable.io/reviews/scionproto/scion/4376#-NcW9JHvAI4nu_--YDQG:-NcW9JHvAI4nu_--YDQH:b-439t1l) ([raw file](https://github.com/scionproto/scion/blob/cdd27dcc91645c6bd39a2f4ad52c484c9af4cb75/private/app/appnet/infraenv.go#L273)):*
> ```Go
> 	// The service resolution address has a dynamic port. The port isn't used but for
> 	// some reason the dispatcher wants one (and it must be unique too).
> 	srAddr, err := net.ResolveUDPAddr("udp", net.JoinHostPort(nc.Public.IP.String(), "0"))
> ```

Unnecessary round-trip via string. Just `srAddr := &net.UDPAddr{IP: nc.Public.IP, Port: 0}`
In the comment, maybe point out that both the port and the IP are dummy values.


<!-- Sent from Reviewable.io -->

2023-08-23 08:51 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: all files reviewed, 5 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`acceptance/common/scion.py` line 88 at r9](https://reviewable.io/reviews/scionproto/scion/4376#-NcWAuyy905IrCiNQ2ii:-NcW_REJ4oxx1Sk6HQy1:b-slxq49) ([raw file](https://github.com/scionproto/scion/blob/cdd27dcc91645c6bd39a2f4ad52c484c9af4cb75/acceptance/common/scion.py#L88)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

As far as I understand, this doesn't do what is advertised.
Note that `path` is not the path, it's only the key of the top level entry. If we want to match an entry by the full path, we'll have to traverse or flatten the dicts explicitly.
</blockquote></details>

Oh oops indeed. I wrote that with 1/2 my mind melting yesterday. No wonder the test fails.
___
*[`control/hiddenpaths.go` line 107 at r9](https://reviewable.io/reviews/scionproto/scion/4376#-NcW8siL1GsA-x50fIAz:-NcWToh64ky8n2yob7Bc:b460e0g) ([raw file](https://github.com/scionproto/scion/blob/cdd27dcc91645c6bd39a2f4ad52c484c9af4cb75/control/hiddenpaths.go#L107)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I'm not sure, is TCP now really used for the local call? Otherwise, is there any benefit from exposing this?
</blockquote></details>

Fair. I wasn't sure if I wanted to keep this. In principle it /should/ be there so any client has the option to use TCP when possible. But then, is it a truly useful thing to do for anything other than CS? If not, then I agree it's a rightful case of YAGNI.
___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-NcWSCXn9MASx974c4Ui:bcz6l4i) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I'd prefer to keep the nil-check in the caller. The metadata is simply not available in all cases, so at some point there will have to be a check to figure out if it is there or not.
</blockquote></details>

If all the methods support a nil receiver you might never need to check. You just get the default value that you'd have made-up after a nil check. That assumes that such a sensible default exists. If the code structure makes sense, there usually is. If not, it probably means that a metadata-less object shouldn't be an acceptable implementation of the interface. I'm talking in the abstract here. I haven't yet checked whether the code structure fits my definition of making sense :-)
___
*[`private/app/appnet/addr.go` line 158 at r9](https://reviewable.io/reviews/scionproto/scion/4376#-NcWDJBK7Y6DkBhSEOgO:-NcWVJQ_81851UUtCKW6:bbnlk7q) ([raw file](https://github.com/scionproto/scion/blob/cdd27dcc91645c6bd39a2f4ad52c484c9af4cb75/private/app/appnet/addr.go#L158)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Directly comparing source and destination ISD-AS would be more robust. This could perhaps be moved before the `Router.Route` call, to make it a bit clearer what's going on here.

With the changes to return a nil Interface list when the metadata is not available, this would now malfunction for "partialPath", i.e for path objects reconstructed from a dataplane path -- the interfaces list is nil/empty even for non-local paths. Not sure if this is ever a use case here, but it might still not be ideal.
</blockquote></details>

It was grossly malfunctioning before: the orginal code was "if len(p.Metadata().interfaces) == 0", so in essence the same test, except crashing for nil metadata. I can't figure how my change introduces a new malfunction. Do you mean this was the wrong check to begin with nil ptr notwithstanding?
___
*[`private/app/appnet/infraenv.go` line 273 at r9](https://reviewable.io/reviews/scionproto/scion/4376#-NcW9JHvAI4nu_--YDQG:-NcWX0wc4Sz1dg0xTX1p:b-7h885n) ([raw file](https://github.com/scionproto/scion/blob/cdd27dcc91645c6bd39a2f4ad52c484c9af4cb75/private/app/appnet/infraenv.go#L273)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Unnecessary round-trip via string. Just `srAddr := &net.UDPAddr{IP: nc.Public.IP, Port: 0}`
In the comment, maybe point out that both the port and the IP are dummy values.
</blockquote></details>

Ok, will fix the double conversion. I cargo-culted this from somewhere else, assuming there was a subtle reason. Ack for the comment.


<!-- Sent from Reviewable.io -->

2023-08-23 10:14 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 63 of 64 files reviewed, 5 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`acceptance/common/scion.py` line 88 at r9](https://reviewable.io/reviews/scionproto/scion/4376#-NcWAuyy905IrCiNQ2ii:-NcWsrLi9jNT4_UpUTGm:b-rnraql) ([raw file](https://github.com/scionproto/scion/blob/cdd27dcc91645c6bd39a2f4ad52c484c9af4cb75/acceptance/common/scion.py#L88)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Oh oops indeed. I wrote that with 1/2 my mind melting yesterday. No wonder the test fails.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2023-08-23 11:23 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 60 of 64 files reviewed, 5 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`private/app/appnet/infraenv.go` line 273 at r9](https://reviewable.io/reviews/scionproto/scion/4376#-NcW9JHvAI4nu_--YDQG:-NcX7dcI9slvzJiFiCC1:b-7rl0jd) ([raw file](https://github.com/scionproto/scion/blob/cdd27dcc91645c6bd39a2f4ad52c484c9af4cb75/private/app/appnet/infraenv.go#L273)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Ok, will fix the double conversion. I cargo-culted this from somewhere else, assuming there was a subtle reason. Ack for the comment.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2023-08-23 11:32 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 60 of 64 files reviewed, 5 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-NcX8_5V8dA0PpG1D0LY:b-j6vrmm) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

If all the methods support a nil receiver you might never need to check. You just get the default value that you'd have made-up after a nil check. That assumes that such a sensible default exists. If the code structure makes sense, there usually is. If not, it probably means that a metadata-less object shouldn't be an acceptable implementation of the interface. I'm talking in the abstract here. I haven't yet checked whether the code structure fits my definition of making sense :-)
</blockquote></details>

One quick check later. The number of cases of the expression path.Metadata().somefield without a nil check is positively frightening. I presume that most (hopefully all) of these cases are in a context where the path is guaranteed to have metadata. If that is the case, may be Paths with metadata and Paths without should be handled as different types.... continuing to read code.


<!-- Sent from Reviewable.io -->

2023-08-23 12:31 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 60 of 64 files reviewed, 5 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-NcXL0qp5rxoczcV_lBA:bu2ewr3) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

One quick check later. The number of cases of the expression path.Metadata().somefield without a nil check is positively frightening. I presume that most (hopefully all) of these cases are in a context where the path is guaranteed to have metadata. If that is the case, may be Paths with metadata and Paths without should be handled as different types.... continuing to read code.
</blockquote></details>

May be I'm missing something, but I don't see that there's much effort put into ensuring that Metadata() is always valid in cases where it's expected (i.e. used without a nil-check). It may be that it happens to be so, but there's nothing to enforce it. I've seen a few reflection-based type checks, but not everywhere. If all the relevant code is in fact protected by the type checks, it's not obvious because the code still manipulates the interface type. That being the case, it may be prudent to make it so that there's always metadata. How about Metadata() returning an empty PathMetadata in lieu of nil?


<!-- Sent from Reviewable.io -->

2023-08-23 12:50 UTC, oncilla reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 60 of 64 files reviewed, 5 unresolved discussions (waiting on @jiceatscion and @matzf)

___
*[`control/hiddenpaths.go` line 107 at r9](https://reviewable.io/reviews/scionproto/scion/4376#-NcW8siL1GsA-x50fIAz:-NcXRS2s60cL7bXHQdK9:bu2p3re) ([raw file](https://github.com/scionproto/scion/blob/cdd27dcc91645c6bd39a2f4ad52c484c9af4cb75/control/hiddenpaths.go#L107)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Oncilla@: Going once...
</blockquote></details>

Personally, I don't see the reason to use SCION for AS internal communication, but I don't have strong opinions. Feel free to nuke it again.


<!-- Sent from Reviewable.io -->

2023-08-23 12:53 UTC, oncilla reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 60 of 64 files reviewed, 5 unresolved discussions (waiting on @jiceatscion and @matzf)

___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-NcXRp2z7d2yc8mUK96V:bwayigo) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

May be I'm missing something, but I don't see that there's much effort put into ensuring that Metadata() is always valid in cases where it's expected (i.e. used without a nil-check). It may be that it happens to be so, but there's nothing to enforce it. I've seen a few reflection-based type checks, but not everywhere. If all the relevant code is in fact protected by the type checks, it's not obvious because the code still manipulates the interface type. That being the case, it may be prudent to make it so that there's always metadata. How about Metadata() returning an empty PathMetadata in lieu of nil?
</blockquote></details>

Everything outside of empty paths (and is created inside of scionproto/scion) will have a non-nil metadata. That's why we don't have nil checks everywhere.

But of course this could be written more defensively.


<!-- Sent from Reviewable.io -->

2023-08-23 12:56 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 60 of 64 files reviewed, 5 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`control/hiddenpaths.go` line 107 at r9](https://reviewable.io/reviews/scionproto/scion/4376#-NcW8siL1GsA-x50fIAz:-NcXRno0CbaPRDdMd9mH:b-7arn4w) ([raw file](https://github.com/scionproto/scion/blob/cdd27dcc91645c6bd39a2f4ad52c484c9af4cb75/control/hiddenpaths.go#L107)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Personally, I don't see the reason to use SCION for AS internal communication, but I don't have strong opinions. Feel free to nuke it again.
</blockquote></details>

I feel free. Thanks! Gone. (in a minute).


<!-- Sent from Reviewable.io -->

2023-08-23 13:20 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 60 of 64 files reviewed, 5 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-NcXX8tV3_LuAqZlraXx:b5sjz2p) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Everything outside of empty paths (and is created inside of scionproto/scion) will have a non-nil metadata. That's why we don't have nil checks everywhere.

But of course this could be written more defensively.
</blockquote></details>

Actually, I'd like to understand this better... I've counted 3 non-test implementations of Path: path.Path, snet.partialPath, and svc.path. Only the first one has non-nil metadata. Isn't partial path used quite a bit? Also I am puzzled by the definition of EmptyPath...it doesn't seem to even implement Path at all. WTF?


<!-- Sent from Reviewable.io -->

2023-08-24 08:04 UTC, matzf reviewed
Ok, fair enough.

> Reviewed 4 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376#-:-NcaZ3t_2R0JrhY6aIYU:b-qezkjt)* status: all files reviewed, 2 unresolved discussions (waiting on @jiceatscion and @oncilla)

___
*[`acceptance/common/scion.py` line 91 at r11](https://reviewable.io/reviews/scionproto/scion/4376#-NcaPVUmAJItzMj06q11:-NcaPVUmAJItzMj06q12:b-4a3l89) ([raw file](https://github.com/scionproto/scion/blob/8fbea8955009a2f64c3e04e11cd7982cb9b316af/acceptance/common/scion.py#L91)):*
> ```Python
>             t = json.load(f)
>             v = val_at_path(t, key)
>             if v is not None:
> ```

Nit, the "if v is not None: return v" is redundant (there is an implicit "else: return None"). Just `return val_at_path(t, key)`.
___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-NcaQ-2Y2osoNYU82v5W:b-w40t1g) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Actually, I'd like to understand this better... I've counted 3 non-test implementations of Path: path.Path, snet.partialPath, and svc.path. Only the first one has non-nil metadata. Isn't partial path used quite a bit? Also I am puzzled by the definition of EmptyPath...it doesn't seem to even implement Path at all. WTF?
</blockquote></details>

These path APIs are quite central and have gone through numerous partial refactors, and it's definitely not a very clean and simple design at this point.

Regarding the Metadata returning nil: this was explicitly designed to return `nil` in the case where no metadata is available, in order to avoid having to come up with defaults for all the individual metadata items. In a language more expressive than go, it wouldn't return a pointer but `optional<Metadata>` or something like that. 
Alternatively, the `Metadata()` could have been moved to a separate `PathWithMetadata` interface. I'm not sure I had considered this at the time. Perhaps this would have avoided the ambiguity -- or, perhaps it would just have turned the nil checks into type assertions instead, not sure.


- `snet/path.Path` is the representation of paths returned from explicit path lookups. As these are constructed from the path segments the full information, they have metadata.
- `snet.partialPath` is the representation of paths reconstructed from dataplane paths. These consist only of the "raw" hop information and source/destination ISD-AS. They don't contain any metadata, in particular no information about which ASes traversed. (They _could_ still expose information about the number of hops in the path, but there is no corresponding function in the Path interface)
- `private/svc.path` seems to be identical to `partialPath` -- I don't recall why this was not replaced with `partialPath`.


@oncilla, note that "empty" paths, i.e. paths with src == dst ISD-AS, returned from path lookups in the daemon _do_ generally contain metadata. See https://github.com/scionproto/scion/blob/d9acea4b6c3bb6463af4a22a48e7c44237a26685/pkg/daemon/grpc.go#L236-L245. It seems that only the paths built by the special-purpose `IntraASPathQuerier` deviates from this and return a `partialPath` with neither metadata nor a valid dataplane path.
Looking at this now, I agree with @jiceatscion , perhaps changing this could indeed be a more appropriate fix than fixing the call site. Then we can postulate that paths returned from `PathQuerier.Query`/`Router.Route` will always carry metadata (here the `PathWithMetadata` type _would_ have been nice).
___
*[`private/app/appnet/addr.go` line 158 at r9](https://reviewable.io/reviews/scionproto/scion/4376#-NcWDJBK7Y6DkBhSEOgO:-NcaYB1G1nAzuhaKVLyz:bdhp580) ([raw file](https://github.com/scionproto/scion/blob/cdd27dcc91645c6bd39a2f4ad52c484c9af4cb75/private/app/appnet/addr.go#L158)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

It was grossly malfunctioning before: the orginal code was "if len(p.Metadata().interfaces) == 0", so in essence the same test, except crashing for nil metadata. I can't figure how my change introduces a new malfunction. Do you mean this was the wrong check to begin with nil ptr notwithstanding?
</blockquote></details>

Rectracted, never mind, sorry.  In the bigger context, see discussion on the different path implementations and whether or not they have metadata, this seems fine.


<!-- Sent from Reviewable.io -->

2023-08-24 08:14 UTC, oncilla approved these changes
> Reviewed 4 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion)



<!-- Sent from Reviewable.io -->

2023-08-24 08:25 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

___
*[`acceptance/common/scion.py` line 91 at r11](https://reviewable.io/reviews/scionproto/scion/4376#-NcaPVUmAJItzMj06q11:-NcacoxKCXa9fGnAsS-_:b-15j3om) ([raw file](https://github.com/scionproto/scion/blob/8fbea8955009a2f64c3e04e11cd7982cb9b316af/acceptance/common/scion.py#L91)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit, the "if v is not None: return v" is redundant (there is an implicit "else: return None"). Just `return val_at_path(t, key)`.
</blockquote></details>

That would be true only if the function accepted a single file. Since it can lookup the key in several files it has to keep going when hitting None. The reason it accepts several files is because the ~reciprocal function "update_json" accepts several files.


<!-- Sent from Reviewable.io -->

2023-08-24 12:09 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

___
*[`acceptance/common/scion.py` line 91 at r11](https://reviewable.io/reviews/scionproto/scion/4376#-NcaPVUmAJItzMj06q11:-Ncb-TnGDH5x3c3D2OSW:b-oacpcg) ([raw file](https://github.com/scionproto/scion/blob/8fbea8955009a2f64c3e04e11cd7982cb9b316af/acceptance/common/scion.py#L91)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

That would be true only if the function accepted a single file. Since it can lookup the key in several files it has to keep going when hitting None. The reason it accepts several files is because the ~reciprocal function "update_json" accepts several files.
</blockquote></details>

Oh, of course, sorry! I missed the loop, the reviewable tool folded exactly above the `with open`...
___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-NcbLK1E36YqwTN0DoRv:b6nkrk3) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
> Coming up with a nil value for PathMetadata seems easy enough: All the fields are arrays, except MTU and Expiry. Couldn't empty and zero values lead to the same end behavior as checking for nil, without even having to change the using code

This would be a sensible choice for the "empty" path. However, for a `partialPath`, built as a reversed dataplane path, an empty `Interfaces` list is just incorrect. But I have to admit, looking over this now, the abstraction with the `PathMetadata` does not look very well chosen. If we want to clean this all up, we should perhaps sit down and really work out all the details.

> What you're saying is that the only cases of expecting metadata when there's none is due to paths returned by IntraASPathQuerier? If so, what should they be returning? Would that be path.Path with no hops, like the example above?

Yes, that's exactly what I meant; make it return `path.Path` with no hops. The MTU and Expiry in the Metadata are probably never accessed, but for consistency it may be good to fill them like is done here:
https://github.com/scionproto/scion/blob/d9acea4b6c3bb6463af4a22a48e7c44237a26685/private/segment/segfetcher/pather.go#L71-L74
(`p.MTU` is initialized from `topo.MTU` and would need to be added to the initialization of the `IntraASPathQuerier`).


<!-- Sent from Reviewable.io -->

2023-08-24 13:06 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-Ncbd0dF5xig_FHgNbsV:bn4bqt9) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

> Coming up with a nil value for PathMetadata seems easy enough: All the fields are arrays, except MTU and Expiry. Couldn't empty and zero values lead to the same end behavior as checking for nil, without even having to change the using code

This would be a sensible choice for the "empty" path. However, for a `partialPath`, built as a reversed dataplane path, an empty `Interfaces` list is just incorrect. But I have to admit, looking over this now, the abstraction with the `PathMetadata` does not look very well chosen. If we want to clean this all up, we should perhaps sit down and really work out all the details.

> What you're saying is that the only cases of expecting metadata when there's none is due to paths returned by IntraASPathQuerier? If so, what should they be returning? Would that be path.Path with no hops, like the example above?

Yes, that's exactly what I meant; make it return `path.Path` with no hops. The MTU and Expiry in the Metadata are probably never accessed, but for consistency it may be good to fill them like is done here:
https://github.com/scionproto/scion/blob/d9acea4b6c3bb6463af4a22a48e7c44237a26685/private/segment/segfetcher/pather.go#L71-L74
(`p.MTU` is initialized from `topo.MTU` and would need to be added to the initialization of the `IntraASPathQuerier`).
</blockquote></details>

You got it... as soon as I figure how to fix the packages dependency tree. snet.Path depends on snet and new that Router uses snet.Path, snet depends on snet.Path. So we need either fewer, or more packages :-) It doesn't look like the code itself becomes circular, just the packages in their current aggregation. That's going to be fun... not.
 


<!-- Sent from Reviewable.io -->

2023-08-24 13:15 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-NcbfbO1CPvCBW2o31YQ:b-39ieq3) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Argh. Right, cyclic dependencies were the reason that `snet/path.Path` is in a separate package. 
Perhaps the simplest solution could be to move `snet.IntraASPathQuerier` into `private/app/appnet`. I doubt that this is used anywhere else.
</blockquote></details>

:-) I was looking into exactly that. However, moving it into snet/path itself could make a bit more intuitive sense?


<!-- Sent from Reviewable.io -->

2023-08-24 13:43 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-NcbkaZzEcO0lywbRPfo:bclcpb6) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

:-) I was looking into exactly that. However, moving it into snet/path itself could make a bit more intuitive sense?
</blockquote></details>

`snet/path` was intended to contain the `snet/path.Path` struct, i.e. the implementation of the `snet.Path` interface. IMO the `IntraASPathQuerier` itself does not really fit in there. Maybe it could make sense to add a constructor function for an `snet/path.Path` representing an empty path, something like `func NewEmptyPath(ia addr.IA, mtu int) Path`.


<!-- Sent from Reviewable.io -->

2023-08-24 14:01 UTC, jiceatscion commented
> `snet/path` was intended to contain the `snet/path.Path` struct, i.e. the implementation of the `snet.Path` interface. IMO the `IntraASPathQuerier` itself does not really fit in there. Maybe it could make sense to add a constructor function for an `snet/path.Path` representing an empty path, something like `func NewEmptyPath(ia addr.IA, mtu int) Path`

There's precedent with Onehop. So, why not. However that still leaves us with the question of where to put the querier itself... there doesn't even seem to be any other implementation... what the heck is that for that can't be accomplished by straight construction?

2023-08-24 14:03 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-NcbqmYa74YWC41OUzXb:bnoecep) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
> `snet/path` was intended to contain the `snet/path.Path` struct, i.e. the implementation of the `snet.Path` interface. IMO the `IntraASPathQuerier` itself does not really fit in there. Maybe it could make sense to add a constructor function for an `snet/path.Path` representing an empty path, something like `func NewEmptyPath(ia addr.IA, mtu int) Path`

There's precedent with Onehop. So, why not. However that still leaves us with the question of where to put the querier itself... there doesn't even seem to be any other implementation... what the heck is that for that can't be accomplished by straight construction?


<!-- Sent from Reviewable.io -->

2023-08-24 14:16 UTC, oncilla approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-Ncbsl1O54C5u8PjYhzc:b-1k0faa) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

> `snet/path` was intended to contain the `snet/path.Path` struct, i.e. the implementation of the `snet.Path` interface. IMO the `IntraASPathQuerier` itself does not really fit in there. Maybe it could make sense to add a constructor function for an `snet/path.Path` representing an empty path, something like `func NewEmptyPath(ia addr.IA, mtu int) Path`

There's precedent with Onehop. So, why not. However that still leaves us with the question of where to put the querier itself... there doesn't even seem to be any other implementation... what the heck is that for that can't be accomplished by straight construction?
</blockquote></details>

I think these are remains from a time where snet was trying to do everything. Nowadays, the concerns of this package are a lot more focused.


IMO, the whole router interface does not really belong in snet in the first place. This is supported by the fact that the interface is not even used in the snet package itself.

So moving router and querier somewhere else SGTM


<!-- Sent from Reviewable.io -->

2023-08-24 14:29 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-Ncbucw24vbLw8oQKk_w:bwto6h0) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I think these are remains from a time where snet was trying to do everything. Nowadays, the concerns of this package are a lot more focused.


IMO, the whole router interface does not really belong in snet in the first place. This is supported by the fact that the interface is not even used in the snet package itself.

So moving router and querier somewhere else SGTM
</blockquote></details>

May be we should be a bit concerned by scope-creep. I'm trying to fix a bug here, not re-architect the while thing. How about filing another bug/work-item for finding a new home for the Router interface and the BaseRouter?


<!-- Sent from Reviewable.io -->

2023-08-24 15:26 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 57 of 67 files reviewed, all discussions resolved (waiting on @matzf and @oncilla)

___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-Ncc8KjZ4sm_z88yQOJ9:bw0n5rt) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

May be we should be a bit concerned by scope-creep. I'm trying to fix a bug here, not re-architect the while thing. How about filing another bug/work-item for finding a new home for the Router interface and the BaseRouter?
</blockquote></details>

Anyway. Here's my latest proposal. I'm ok with moving the intraASquerier stuff somewhere else you tell me, but I'd prefer not having to move/refactor more things within this PR.


<!-- Sent from Reviewable.io -->

2023-08-24 19:13 UTC, oncilla reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 56 of 67 files reviewed, all discussions resolved (waiting on @matzf)

___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-NccxR_00DDldvOeUB54:b-obny69) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Anyway. Here's my latest proposal. I'm ok with moving the intraASquerier stuff somewhere else you tell me, but I'd prefer not having to move/refactor more things within this PR.
</blockquote></details>

Move it to `private/app/appnet` as @matzf suggested and we should be good to merge.

(my comment was trying to add context, I should have made it clearer that it is not meant as request for more changes)


<!-- Sent from Reviewable.io -->

2023-08-24 19:15 UTC, oncilla reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 56 of 67 files reviewed, 1 unresolved discussion (waiting on @jiceatscion and @matzf)

___
*[`pkg/snet/path/intraAS.go` line 15 at r13](https://reviewable.io/reviews/scionproto/scion/4376#-NccyA_z7ip4vBtWDyLr:-NccyA_z7ip4vBtWDyLs:bel65nz) ([raw file](https://github.com/scionproto/scion/blob/d1e9dbd5bbb1a65c1f635af686442297edab3120/pkg/snet/path/intraAS.go#L15)):*
> ```Go
> // limitations under the License.
> 
> // Package path implements snet.Path with full metadata
> ```

nit: there should only be one package doc string.

(probably copy pasta)


<!-- Sent from Reviewable.io -->

2023-08-24 19:16 UTC, oncilla approved these changes
> Reviewed 9 of 11 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion)



<!-- Sent from Reviewable.io -->

2023-08-25 08:46 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 64 of 68 files reviewed, all discussions resolved (waiting on @matzf and @oncilla)

___
*[`pkg/snet/path.go` line 71 at r7](https://reviewable.io/reviews/scionproto/scion/4376#-NcSdQmn2tYybVIIxv5Q:-Ncfry96E2nNReZWmIz1:b-7rl0kd) ([raw file](https://github.com/scionproto/scion/blob/da7ab4fb8f7cfdc664edf02a8fe5996c8e6df3d0/pkg/snet/path.go#L71)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Move it to `private/app/appnet` as @matzf suggested and we should be good to merge.

(my comment was trying to add context, I should have made it clearer that it is not meant as request for more changes)
</blockquote></details>

done
___
*[`pkg/snet/path/intraAS.go` line 15 at r13](https://reviewable.io/reviews/scionproto/scion/4376#-NccyA_z7ip4vBtWDyLr:-Ncfrsof23bmWK5PwHTf:b-7rl0kd) ([raw file](https://github.com/scionproto/scion/blob/d1e9dbd5bbb1a65c1f635af686442297edab3120/pkg/snet/path/intraAS.go#L15)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

nit: there should only be one package doc string.

(probably copy pasta)
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-08-25 08:48 UTC, jiceatscion reviewed
moved the querier to appnet as you and oncilla suggested.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376#-:-Ncfs4sK2a2PFaJty9Mi:b-qjt0g2)* status: 64 of 68 files reviewed, all discussions resolved (waiting on @matzf and @oncilla)



<!-- Sent from Reviewable.io -->

2023-08-25 09:25 UTC, oncilla approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376#-:-Ncg-jVt2qLID-eSdHim:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-08-25 09:37 UTC, lukedirtwalker requested changes
> Reviewed 2 of 17 files at r2, 44 of 44 files at r3, 1 of 11 files at r4, 44 of 50 files at r5, 7 of 9 files at r7, 1 of 4 files at r10, 1 of 1 files at r11, 6 of 11 files at r12, 2 of 2 files at r13, 3 of 4 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: all files reviewed, 4 unresolved discussions (waiting on @jiceatscion and @matzf)

___
*[`acceptance/common/scion.py` line 70 at r15](https://reviewable.io/reviews/scionproto/scion/4376#-Ncg1g9y5HJpUV7T1WAZ:-Ncg1g9y5HJpUV7T1WA_:bfb96rh) ([raw file](https://github.com/scionproto/scion/blob/deed43559a25e3285ff5be41c0bd9157c6256526/acceptance/common/scion.py#L70)):*
> ```Python
>         with open(file, "w") as f:
>             json.dump(t, f, indent=2)
> ```

The changes in this file don't seem to be used anywhere, or am I missing something?
___
*[`acceptance/common/scion.py` line 72 at r15](https://reviewable.io/reviews/scionproto/scion/4376#-Ncg0yfx7jFecbPAy5fC:-Ncg0yfx7jFecbPAy5fD:b6yeagr) ([raw file](https://github.com/scionproto/scion/blob/deed43559a25e3285ff5be41c0bd9157c6256526/acceptance/common/scion.py#L72)):*
> ```Python
> 
> 
> def load_from_json(key: str, files: LocalPath) -> Any:
> ```

should that be a list of `LocalPath` ? or does it need to be directory.



_Code quote:_
```Python
files: LocalPath
```
___
*[`private/app/appnet/intraAS.go` line 1 at r15](https://reviewable.io/reviews/scionproto/scion/4376#-Ncg-it952m9GK-V_gIP:-Ncg-itA5gc_6fk1jEUi:b3b6rhz) ([raw file](https://github.com/scionproto/scion/blob/deed43559a25e3285ff5be41c0bd9157c6256526/private/app/appnet/intraAS.go#L1)):*
> ```Go
> // Copyright 2020 ETH Zurich
> ```

nit: camel case is not very usual for Go file names. I would name it `intra_as.go` instead.


<!-- Sent from Reviewable.io -->

2023-08-25 09:38 UTC, lukedirtwalker requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: all files reviewed, 5 unresolved discussions (waiting on @jiceatscion and @matzf)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4376#-Ncg2g5g0PQyH-bdpo9I:-Ncg2g5g0PQyH-bdpo9J:b-2xlv59) (no related file):*
please clean up the title and the description to contain only what it does now.

___


<!-- Sent from Reviewable.io -->

2023-08-25 10:18 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 66 of 68 files reviewed, 4 unresolved discussions (waiting on @lukedirtwalker, @matzf, and @oncilla)

___
*[`acceptance/common/scion.py` line 70 at r15](https://reviewable.io/reviews/scionproto/scion/4376#-Ncg1g9y5HJpUV7T1WAZ:-NcgArxF-cr3VMzgYjHV:bscwilr) ([raw file](https://github.com/scionproto/scion/blob/deed43559a25e3285ff5be41c0bd9157c6256526/acceptance/common/scion.py#L70)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

The changes in this file don't seem to be used anywhere, or am I missing something?
</blockquote></details>

update_json() and now load_from_json() are used by acceptance/hidden_paths/test.py.
___
*[`acceptance/common/scion.py` line 72 at r15](https://reviewable.io/reviews/scionproto/scion/4376#-Ncg0yfx7jFecbPAy5fC:-Ncg9sZb93uFZgbN7X0K:bngdj4p) ([raw file](https://github.com/scionproto/scion/blob/deed43559a25e3285ff5be41c0bd9157c6256526/acceptance/common/scion.py#L72)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

should that be a list of `LocalPath` ? or does it need to be directory.
</blockquote></details>

LocalPath is a weird overengineered beast. It is constructed from a list of paths fragments and, if that ends-up being a directory, is iterable to produce all the files in the directory. Neither features are used but because we use LocalPath we are bound to assume there could be multiple files (at least that is no harder than checking there's only one anyway). I didn't start this. That's how update_json was to begin with. I just added the reciprocal method.
___
*[`private/app/appnet/intraAS.go` line 1 at r15](https://reviewable.io/reviews/scionproto/scion/4376#-Ncg-it952m9GK-V_gIP:-NcgBe4O15A_sZTq4Z7-:b-7rl0kd) ([raw file](https://github.com/scionproto/scion/blob/deed43559a25e3285ff5be41c0bd9157c6256526/private/app/appnet/intraAS.go#L1)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

nit: camel case is not very usual for Go file names. I would name it `intra_as.go` instead.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-08-25 10:53 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: 66 of 68 files reviewed, 4 unresolved discussions (waiting on @lukedirtwalker, @matzf, and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4376#-Ncg2g5g0PQyH-bdpo9I:-NcgJsVO8EeXE9AmMLAo:b-896fix) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

please clean up the title and the description to contain only what it does now.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-08-25 15:08 UTC, lukedirtwalker approved these changes
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-08-28 09:14 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[`private/app/appnet/intraAS.go` line 45 at r14](https://reviewable.io/reviews/scionproto/scion/4376#-Ncfveuh-icwpT49ccMT:-NcvPdLr6KRTtkyMlH5s:b-b0p7g4) ([raw file](https://github.com/scionproto/scion/blob/d7c8d15addd2cbe830b33c876a3a699bbd577c61/private/app/appnet/intraAS.go#L45)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

done
</blockquote></details>

This should be resolved now. Could one of the esteemed reviewers merge the PR?


<!-- Sent from Reviewable.io -->

2023-08-28 12:11 UTC, oncilla reviewed
> Reviewed 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-08-29 06:47 UTC, matzf approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4376#-:-Nd-1unq602BUOdC4emf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)



<!-- Sent from Reviewable.io -->

2023-08-29 07:45 UTC, merged