dist: build debian packages for multiple platforms
scionproto/scion pull request #4448
Opened 2023-11-24 11:15 UTC by matzf

WIP

2023-12-15 13:59 UTC, jiceatscion requested changes
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: all files reviewed, 5 unresolved discussions (waiting on @marcfrei, @matzf, and @oncilla)

___
*[`Makefile` line 22 at r1](https://reviewable.io/reviews/scionproto/scion/4448#-NlhWPI-Dg1wkGhb2fsd:-NlhWPI-Dg1wkGhb2fse:b-nyujjg) ([raw file](https://github.com/scionproto/scion/blob/bdbf24c675423c4375423b2cb1f643a2d209c46c/Makefile#L22)):*
> ```Makefile
> 		if [ -f "$$f" ]; then \
> 			bf=`basename $$f`; \
> 			v="$$(ar p $$f control.tar.gz | tar -xz --to-stdout ./control | sed -n 's/Version: //p')"; \
> ```

What's control.tar.gz? Is that the control service? Why just this one? I don't think I understand what this is about.
___
*[`dist/BUILD.bazel` line 64 at r1](https://reviewable.io/reviews/scionproto/scion/4448#-NlhZKCf2wKVKUWBORX6:-NlhZKCf2wKVKUWBORX7:b7mkprs) ([raw file](https://github.com/scionproto/scion/blob/bdbf24c675423c4375423b2cb1f643a2d209c46c/dist/BUILD.bazel#L64)):*
> ```Starlark
>         "adduser",
>     ],
>     description = "SCION dispatcher",
> ```

Was that meant to read "SCION daemon"?



_Code quote:_
```Starlark
 description = "SCION dispatcher",
```
___
*[`dist/debian/scion.postinst` line 19 at r1](https://reviewable.io/reviews/scionproto/scion/4448#-NlhcXqa4hewCXBai5DD:-NlhcXqa4hewCXBai5DE:bm8p8nb) ([raw file](https://github.com/scionproto/scion/blob/bdbf24c675423c4375423b2cb1f643a2d209c46c/dist/debian/scion.postinst#L19)):*
> ```
>     configure)
>         # Create system user
>         adduser --system --home /var/lib/scion --group scion
> ```

If this is ever executed redundantly, it will give you an error.
Add || true?
Did you mean "--user-group" rather than "--group" ? "--group" would be the abbreviation of "--groups", which would consume the user name argument that follows and also expect the group by that name to exists.



_Code quote:_
```
adduser --system --home /var/lib/scion --group scion
```
___
*[`dist/systemd/scion-router@.service` line 16 at r1](https://reviewable.io/reviews/scionproto/scion/4448#-NlhgKsj2eLzvS_FQaht:-NlhgKsj2eLzvS_FQahu:ba4xykj) ([raw file](https://github.com/scionproto/scion/blob/bdbf24c675423c4375423b2cb1f643a2d209c46c/dist/systemd/scion-router%40.service#L16)):*
> ```desktop
> 
> [Install]
> WantedBy=multi-user.target
> ```

What happens to the OS if this fails? Does it not fail until someone creates the config, btw? Should we arrange for some kind of dormant state for the router, by way of some default/empty config file?



_Code quote:_
```desktop
multi-user.target
```
___
*[`doc/dev/setup.rst` line 120 at r1](https://reviewable.io/reviews/scionproto/scion/4448#-NlhkhM09ceEbswtntmQ:-NlhkhM09ceEbswtntmR:bcxnvps) ([raw file](https://github.com/scionproto/scion/blob/bdbf24c675423c4375423b2cb1f643a2d209c46c/doc/dev/setup.rst#L120)):*
> ```reStructuredText
>    .. code-block:: bash
> 
>       go build -o bin ./<service>/cmd/<service>...
> ```

Did you delete one of the two sqlite implementation? I didn't see that.



_Code quote:_
```reStructuredText
go build -o bin ./<service>/cmd/<service>...
```


<!-- Sent from Reviewable.io -->

2023-12-15 14:01 UTC, jiceatscion reviewed
Nice!

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448#-:-NlhlqB-5n52BClpZyst:b-83sjoh)* status: all files reviewed, 5 unresolved discussions (waiting on @marcfrei, @matzf, and @oncilla)



<!-- Sent from Reviewable.io -->

2023-12-15 14:36 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: 25 of 26 files reviewed, 5 unresolved discussions (waiting on @jiceatscion, @marcfrei, @matzf, and @oncilla)

___
*[`Makefile` line 22 at r1](https://reviewable.io/reviews/scionproto/scion/4448#-NlhWPI-Dg1wkGhb2fsd:-NlhmrtREjdV9tKQd4vT:b-wc24qa) ([raw file](https://github.com/scionproto/scion/blob/bdbf24c675423c4375423b2cb1f643a2d209c46c/Makefile#L22)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

What's control.tar.gz? Is that the control service? Why just this one? I don't think I understand what this is about.
</blockquote></details>

Ah, no unrelated to our control service. This is the manifest of the .deb package, see https://en.wikipedia.org/wiki/Deb_(file_format)#Control_archive.
Added bit better explanation and a reference to the wikipedia page (which gives a much more concise overview than the official spec).
___
*[`dist/BUILD.bazel` line 64 at r1](https://reviewable.io/reviews/scionproto/scion/4448#-NlhZKCf2wKVKUWBORX6:-NlhqM4s2VI6jxDff7OU:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bdbf24c675423c4375423b2cb1f643a2d209c46c/dist/BUILD.bazel#L64)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Was that meant to read "SCION daemon"?
</blockquote></details>

Done.
___
*[`dist/debian/scion.postinst` line 19 at r1](https://reviewable.io/reviews/scionproto/scion/4448#-NlhcXqa4hewCXBai5DD:-NlhrffqBEDgNtT9937g:bxfas7u) ([raw file](https://github.com/scionproto/scion/blob/bdbf24c675423c4375423b2cb1f643a2d209c46c/dist/debian/scion.postinst#L19)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

If this is ever executed redundantly, it will give you an error.
Add || true?
Did you mean "--user-group" rather than "--group" ? "--group" would be the abbreviation of "--groups", which would consume the user name argument that follows and also expect the group by that name to exists.
</blockquote></details>

It prints an error message if the user already exists (which I do find a bit annoying) , but it still succeeds. As I understand, this is by design; this is following the advice here: https://wiki.debian.org/AccountHandlingInMaintainerScripts

Regarding --groups vs --user-group; is it possible that your looking `useradd` instead of `adduser`? There doesn't seem to be such a flag, at least not in debian, see https://manpages.debian.org/jessie/adduser/adduser.8.en.html
___
*[`dist/systemd/scion-router@.service` line 16 at r1](https://reviewable.io/reviews/scionproto/scion/4448#-NlhgKsj2eLzvS_FQaht:-NlhqU-jEQGvX71h-AvY:b-f924ma) ([raw file](https://github.com/scionproto/scion/blob/bdbf24c675423c4375423b2cb1f643a2d209c46c/dist/systemd/scion-router%40.service#L16)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

What happens to the OS if this fails? Does it not fail until someone creates the config, btw? Should we arrange for some kind of dormant state for the router, by way of some default/empty config file?
</blockquote></details>

This [Install] section only applies when a user _enables_ the service. For example `systemctl enable scion-router@br-1.service`. This does not happen during package installation. Nothing bad happens if this fails. It just means that the systemd (attempts to) start the service whenever this multi-user target is activated. If it fails, it's marked as failing, but nothing else happens. This multi-user target is pretty much the same as runlevel 5.

Btw. it seems I need to write some documentation on how to use this stuff.
___
*[`doc/dev/setup.rst` line 120 at r1](https://reviewable.io/reviews/scionproto/scion/4448#-NlhkhM09ceEbswtntmQ:-NlhnYVZAkSj_IKJ5sEl:b-hkl1o9) ([raw file](https://github.com/scionproto/scion/blob/bdbf24c675423c4375423b2cb1f643a2d209c46c/doc/dev/setup.rst#L120)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Did you delete one of the two sqlite implementation? I didn't see that.
</blockquote></details>

Ah no sorry, this is an incomplete edit. I wanted to remove the explicit tag here to simplify the instructions, because there is a default option. (It' I wanted to move the documentation of the two options to somewhere else under "advanced build instructions", but I didn't find the right place for it yet. I'll add it somewhere.


<!-- Sent from Reviewable.io -->

2023-12-15 15:17 UTC, jiceatscion reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: all files reviewed, 1 unresolved discussion (waiting on @marcfrei, @matzf, and @oncilla)

___
*[`dist/debian/scion.postinst` line 19 at r1](https://reviewable.io/reviews/scionproto/scion/4448#-NlhcXqa4hewCXBai5DD:-Nli1oRC-Bg3Phpqim4-:b-7kst88) ([raw file](https://github.com/scionproto/scion/blob/bdbf24c675423c4375423b2cb1f643a2d209c46c/dist/debian/scion.postinst#L19)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

It prints an error message if the user already exists (which I do find a bit annoying) , but it still succeeds. As I understand, this is by design; this is following the advice here: https://wiki.debian.org/AccountHandlingInMaintainerScripts

Regarding --groups vs --user-group; is it possible that your looking `useradd` instead of `adduser`? There doesn't seem to be such a flag, at least not in debian, see https://manpages.debian.org/jessie/adduser/adduser.8.en.html
</blockquote></details>

Indeed. On my system adduser is a symlink to useradd! Ditto for the manpage. Ok, mine is redhat/fedora. Your stuff is for debian/ubuntu. So... objection withdrawn.
___
*[`dist/systemd/scion-router@.service` line 16 at r1](https://reviewable.io/reviews/scionproto/scion/4448#-NlhgKsj2eLzvS_FQaht:-Nli0hYA9p5yzdUmfIWe:b-ygsy9y) ([raw file](https://github.com/scionproto/scion/blob/bdbf24c675423c4375423b2cb1f643a2d209c46c/dist/systemd/scion-router%40.service#L16)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This [Install] section only applies when a user _enables_ the service. For example `systemctl enable scion-router@br-1.service`. This does not happen during package installation. Nothing bad happens if this fails. It just means that the systemd (attempts to) start the service whenever this multi-user target is activated. If it fails, it's marked as failing, but nothing else happens. This multi-user target is pretty much the same as runlevel 5.

Btw. it seems I need to write some documentation on how to use this stuff.
</blockquote></details>

Actually, according to debian's doc it is more like runlevel 3. They have another name for runlevel 5 ("graphics", I think). Anyway. As long as it doesn't constantly retry, I have no objection. Esp. If it begins life disabled (I hadn't considered that).


<!-- Sent from Reviewable.io -->

2023-12-15 15:19 UTC, jiceatscion approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448#-:-Nli2nDC8g7_vSTA-hHo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @marcfrei, @matzf, and @oncilla)



<!-- Sent from Reviewable.io -->

2023-12-18 09:30 UTC, marcfrei approved these changes
Fantastic, thanks so much!
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 23 of 26 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448#-:-NlwFh1zBWRyGUQjMKAQ:b-fcaxc3)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`dist/conffiles/sciond.toml` line 13 at r2](https://reviewable.io/reviews/scionproto/scion/4448#-NlwDxp_DkML3hP8BlF4:-NlwDxpa8jJk7wVr2iiG:bc5f44n) ([raw file](https://github.com/scionproto/scion/blob/f6998e7b9479e753fef72e8638cacd96ca964adc/dist/conffiles/sciond.toml#L13)):*
> ```TOML
> 
> # Optionally enable DRKey
> # [drkey_db]
> ```

This is the old DRKey config, right? Not yet using `drkey_level2_db`.


<!-- Sent from Reviewable.io -->

2023-12-18 10:46 UTC, marcfrei approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: 25 of 26 files reviewed, 2 unresolved discussions (waiting on @jiceatscion, @matzf, and @oncilla)

___
*[`dist/conffiles/sciond.toml` line 13 at r2](https://reviewable.io/reviews/scionproto/scion/4448#-NlwDxp_DkML3hP8BlF4:-NlwX8g12c_IWNdmmPM2:b4xo209) ([raw file](https://github.com/scionproto/scion/blob/f6998e7b9479e753fef72e8638cacd96ca964adc/dist/conffiles/sciond.toml#L13)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

This is the old DRKey config, right? Not yet using `drkey_level2_db`.
</blockquote></details>

Thanks for the fix, Matthias!


<!-- Sent from Reviewable.io -->

2023-12-19 13:36 UTC, lukedirtwalker requested changes
> Reviewed 23 of 26 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: all files reviewed, 5 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`Makefile` line 17 at r3](https://reviewable.io/reviews/scionproto/scion/4448#-Nm16K1U86W-BKt6_xIK:-Nm16K1U86W-BKt6_xIL:b-plr5a5) ([raw file](https://github.com/scionproto/scion/blob/222b287acc7f29ca982822a2779113956c6c0b9f/Makefile#L17)):*
> ```Makefile
> 	bazel build //dist:deb_all
> 	mkdir -p deb; rm -f deb/*;
> 	@ # Bazel cannot include the version in the filename.
> ```

huh? I thought usually it includes the version in the filename? Maybe the comment is just a bit misleading?
___
*[`README.md` line 49 at r3](https://reviewable.io/reviews/scionproto/scion/4448#-Nm165saAZDhErhzSqxv:-Nm165saAZDhErhzSqxw:undefined) ([raw file](https://github.com/scionproto/scion/blob/222b287acc7f29ca982822a2779113956c6c0b9f/README.md#L49)):*
> ```Markdown
> operational global test deployment of SCION.
> 
> The [awesome-scion](https://github.com/scionproto/awesome-scion#deployments) list containes
> ```





_Suggestion:_
```Markdown
contains
```
___
*[`dist/systemd/scion-control@.service` line 13 at r3](https://reviewable.io/reviews/scionproto/scion/4448#-Nm1CoUu3SLpm4eahWmA:-Nm1CoUu3SLpm4eahWmB:b512cp1) ([raw file](https://github.com/scionproto/scion/blob/222b287acc7f29ca982822a2779113956c6c0b9f/dist/systemd/scion-control%40.service#L13)):*
> ```desktop
> User=scion
> Group=scion
> ExecStart=/usr/bin/scion-control --config /etc/scion/%i.toml
> ```

what is the argument? The ISD-AS? Shouldn't the daemon also have that?
___
*[`dist/test/BUILD.bazel` line 10 at r3](https://reviewable.io/reviews/scionproto/scion/4448#-Nm1FxE89MoffsXYb41m:-Nm1FxE89MoffsXYb41n:b-fscbuh) ([raw file](https://github.com/scionproto/scion/blob/222b287acc7f29ca982822a2779113956c6c0b9f/dist/test/BUILD.bazel#L10)):*
> ```Starlark
>     env = {
>         "SCION_DEB_PACKAGES": "$(locations //dist:deb)",
>         "DEBUG": "1",
> ```

do we want to keep the debug env here? doesn't that leak containers?


<!-- Sent from Reviewable.io -->

2023-12-19 14:15 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: 23 of 29 files reviewed, 5 unresolved discussions (waiting on @jiceatscion, @lukedirtwalker, @marcfrei, and @oncilla)

___
*[`Makefile` line 17 at r3](https://reviewable.io/reviews/scionproto/scion/4448#-Nm16K1U86W-BKt6_xIK:-Nm1NLCh3nXMt8ShOCzW:b-o7sheg) ([raw file](https://github.com/scionproto/scion/blob/222b287acc7f29ca982822a2779113956c6c0b9f/Makefile#L17)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

huh? I thought usually it includes the version in the filename? Maybe the comment is just a bit misleading?
</blockquote></details>

It doesn't work if we want to use the git tag as the version. We have two options: either write a the version to a build file before building, or rename the files after building. I chose the latter option, because we can get the version into the .deb package just fine, just not into the filename.
Made the comment more specific. Better? 
___
*[`README.md` line 49 at r3](https://reviewable.io/reviews/scionproto/scion/4448#-Nm165saAZDhErhzSqxv:-Nm1OM3fEc69lhxeZzC_:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/222b287acc7f29ca982822a2779113956c6c0b9f/README.md#L49)):*
> ```Markdown
> operational global test deployment of SCION.
> 
> The [awesome-scion](https://github.com/scionproto/awesome-scion#deployments) list containes
> ```

Done.
___
*[`dist/conffiles/sciond.toml` line 13 at r2](https://reviewable.io/reviews/scionproto/scion/4448#-NlwDxp_DkML3hP8BlF4:-NlwRT9o6DyggEcmFHUX:b8gj3mz) ([raw file](https://github.com/scionproto/scion/blob/f6998e7b9479e753fef72e8638cacd96ca964adc/dist/conffiles/sciond.toml#L13)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

This is the old DRKey config, right? Not yet using `drkey_level2_db`.
</blockquote></details>

Good catch, fixed.
___
*[`dist/systemd/scion-control@.service` line 13 at r3](https://reviewable.io/reviews/scionproto/scion/4448#-Nm1CoUu3SLpm4eahWmA:-Nm1OPfT4oQD6X0-rZEy:b-vpf38w) ([raw file](https://github.com/scionproto/scion/blob/222b287acc7f29ca982822a2779113956c6c0b9f/dist/systemd/scion-control%40.service#L13)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

what is the argument? The ISD-AS? Shouldn't the daemon also have that?
</blockquote></details>

I've added documentation for this now (see doc/manuals/install.rst). The parameter is the basename of the config file.

For the control service and the router we support service instances per host, e.g. for operating multiple ASes (or same AS in different ISDs) from the same host. 
For the daemon running multiple instances is less useful; you'd need to specify the daemon address for every application invocation, and that just seems too cumbersome.
___
*[`dist/test/BUILD.bazel` line 10 at r3](https://reviewable.io/reviews/scionproto/scion/4448#-Nm1FxE89MoffsXYb41m:-Nm1Ooxy9prAQL0nwwCl:b-hi9yf9) ([raw file](https://github.com/scionproto/scion/blob/222b287acc7f29ca982822a2779113956c6c0b9f/dist/test/BUILD.bazel#L10)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

do we want to keep the debug env here? doesn't that leak containers?
</blockquote></details>

Ooops, fixed.
___
*[`doc/dev/setup.rst` line 120 at r1](https://reviewable.io/reviews/scionproto/scion/4448#-NlhkhM09ceEbswtntmQ:-NlwRgak1vivcB5KNHIR:b2prmso) ([raw file](https://github.com/scionproto/scion/blob/bdbf24c675423c4375423b2cb1f643a2d209c46c/doc/dev/setup.rst#L120)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Ah no sorry, this is an incomplete edit. I wanted to remove the explicit tag here to simplify the instructions, because there is a default option. (It' I wanted to move the documentation of the two options to somewhere else under "advanced build instructions", but I didn't find the right place for it yet. I'll add it somewhere.
</blockquote></details>

Done. I've added documentation on installation and related to this reorganized the build instructions a bit.


<!-- Sent from Reviewable.io -->

2023-12-19 15:51 UTC, lukedirtwalker requested changes
> Reviewed 5 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: 28 of 29 files reviewed, 3 unresolved discussions (waiting on @jiceatscion, @matzf, and @oncilla)

___
*[`Makefile` line 17 at r3](https://reviewable.io/reviews/scionproto/scion/4448#-Nm16K1U86W-BKt6_xIK:-Nm1ZSOk3IrVTolNgiDI:b-z71uo7) ([raw file](https://github.com/scionproto/scion/blob/222b287acc7f29ca982822a2779113956c6c0b9f/Makefile#L17)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

It doesn't work if we want to use the git tag as the version. We have two options: either write a the version to a build file before building, or rename the files after building. I chose the latter option, because we can get the version into the .deb package just fine, just not into the filename.
Made the comment more specific. Better?
</blockquote></details>

Aha, I see :+1: 
___
*[`README.md` line 49 at r3](https://reviewable.io/reviews/scionproto/scion/4448#-Nm165saAZDhErhzSqxv:-Nm1ZhO04RZRrxb3mdvy:b-4ywuge) ([raw file](https://github.com/scionproto/scion/blob/222b287acc7f29ca982822a2779113956c6c0b9f/README.md#L49)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

don't see it?


<!-- Sent from Reviewable.io -->

2023-12-20 05:56 UTC, lukedirtwalker approved these changes
> Reviewed 1 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion and @oncilla)

___
*[`dist/systemd/scion-control@.service` line 13 at r3](https://reviewable.io/reviews/scionproto/scion/4448#-Nm1CoUu3SLpm4eahWmA:-Nm4mNg3ATWzlgOBpkAw:brkpoa3) ([raw file](https://github.com/scionproto/scion/blob/222b287acc7f29ca982822a2779113956c6c0b9f/dist/systemd/scion-control%40.service#L13)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I've added documentation for this now (see doc/manuals/install.rst). The parameter is the basename of the config file.

For the control service and the router we support service instances per host, e.g. for operating multiple ASes (or same AS in different ISDs) from the same host. 
For the daemon running multiple instances is less useful; you'd need to specify the daemon address for every application invocation, and that just seems too cumbersome.
</blockquote></details>

Well if you really operate multiple ISD-AS and want to use the scion tooling (like showpaths) you need to have multiple daemon instances. Using the env file you can specify the daemon address in the env config file, and you would only need the ISD-AS paramater on scion tooling. Anyway just putting this out here. Not really needed to change.


<!-- Sent from Reviewable.io -->

2023-12-20 10:01 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion and @oncilla)

___
*[`README.md` line 49 at r3](https://reviewable.io/reviews/scionproto/scion/4448#-Nm165saAZDhErhzSqxv:-Nm5eWtn4Tw25a_ZtOKg:bcjwvy4) ([raw file](https://github.com/scionproto/scion/blob/222b287acc7f29ca982822a2779113956c6c0b9f/README.md#L49)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

don't see it?
</blockquote></details>

Sorry, didn't push, now done.


<!-- Sent from Reviewable.io -->

2023-12-20 12:22 UTC, lukedirtwalker approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion and @oncilla)



<!-- Sent from Reviewable.io -->

2023-12-20 12:29 UTC, jiceatscion reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)



<!-- Sent from Reviewable.io -->

2023-12-20 12:35 UTC, jiceatscion requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf and @oncilla)

___
*[`doc/dev/setup.rst` line 120 at r1](https://reviewable.io/reviews/scionproto/scion/4448#-NlhkhM09ceEbswtntmQ:-Nm6D3ZVBoKg5NeJdld1:b-3ags7k) ([raw file](https://github.com/scionproto/scion/blob/bdbf24c675423c4375423b2cb1f643a2d209c46c/doc/dev/setup.rst#L120)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Done. I've added documentation on installation and related to this reorganized the build instructions a bit.
</blockquote></details>

Sounds good, I don't see where the documentation regarding the two sql options has moved, though.


<!-- Sent from Reviewable.io -->

2023-12-20 12:36 UTC, jiceatscion approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)



<!-- Sent from Reviewable.io -->

2023-12-20 12:43 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

___
*[`doc/dev/setup.rst` line 120 at r1](https://reviewable.io/reviews/scionproto/scion/4448#-NlhkhM09ceEbswtntmQ:-Nm6EOro3myr1k3gc0VZ:b2bv6ou) ([raw file](https://github.com/scionproto/scion/blob/bdbf24c675423c4375423b2cb1f643a2d209c46c/doc/dev/setup.rst#L120)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Sounds good, I don't see where the documentation regarding the two sql options has moved, though.
</blockquote></details>

doc/dev/build.rst (sub-section "Options").


<!-- Sent from Reviewable.io -->

2023-12-20 12:44 UTC, jiceatscion commented
> > _[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oncilla)

Never mind. I found it.

2023-12-20 15:12 UTC, oncilla approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 20 of 26 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448#-:-Nm6mIJu0U9Moyn-NfGM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-12-20 16:21 UTC, marcfrei requested changes
> Reviewed 1 of 26 files at r1, 1 of 1 files at r3, 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: all files reviewed, 6 unresolved discussions (waiting on @matzf)

___
*[`doc/dev/build.rst` line 26 at r5](https://reviewable.io/reviews/scionproto/scion/4448#-Nm6xfx_AIcPY3swGU2E:-Nm6xfx_AIcPY3swGU2F:b-8aipkz) ([raw file](https://github.com/scionproto/scion/blob/5bdde50a72cc608bd24ecfc6df660240ca5513be/doc/dev/build.rst#L26)):*
> ```reStructuredText
>       cd scion
> 
> #. Determine the go version used in the bazel setup; the ``WORKSPACE`` file
> ```

Bazel



_Code quote:_
```reStructuredText
bazel
```
___
*[`doc/dev/build.rst` line 73 at r5](https://reviewable.io/reviews/scionproto/scion/4448#-Nm6vnFXBFlAo07QUvaL:-Nm6vnFY8vFcSw8d1hnt:bogq8vs) ([raw file](https://github.com/scionproto/scion/blob/5bdde50a72cc608bd24ecfc6df660240ca5513be/doc/dev/build.rst#L73)):*
> ```reStructuredText
> See :doc:`setup` for instructions on how to set up Bazel and the full development environment.
> 
> Prerequites
> ```

Prerequisites
___
*[`doc/dev/build.rst` line 83 at r5](https://reviewable.io/reviews/scionproto/scion/4448#-Nm6xpI1EKB6KN3kUu7P:-Nm6xpI2Dm32aPwswwTF:b-8aipkz) ([raw file](https://github.com/scionproto/scion/blob/5bdde50a72cc608bd24ecfc6df660240ca5513be/doc/dev/build.rst#L83)):*
> ```reStructuredText
>       cd scion
> 
> #. Install bazel: either follow the official instructions at `<https://bazel.build/install>`_, or
> ```

Bazel



_Code quote:_
```reStructuredText
bazel
```
___
*[`doc/dev/build.rst` line 90 at r5](https://reviewable.io/reviews/scionproto/scion/4448#-Nm6xyKW10mKMA9Ts6t1:-Nm6xyKW10mKMA9Ts6t2:b-8aipkz) ([raw file](https://github.com/scionproto/scion/blob/5bdde50a72cc608bd24ecfc6df660240ca5513be/doc/dev/build.rst#L90)):*
> ```reStructuredText
>       tools/install_bazel
> 
> #. Remove remote cache options from ``.bazelrc``; the default setup is useful to limit bazel's
> ```

Bazel



_Code quote:_
```reStructuredText
bazel
```
___
*[`doc/dev/build.rst` line 91 at r5](https://reviewable.io/reviews/scionproto/scion/4448#-Nm6yJvc9oAv9H7O6XPy:-Nm6yJvc9oAv9H7O6XPz:btovycz) ([raw file](https://github.com/scionproto/scion/blob/5bdde50a72cc608bd24ecfc6df660240ca5513be/doc/dev/build.rst#L91)):*
> ```reStructuredText
> 
> #. Remove remote cache options from ``.bazelrc``; the default setup is useful to limit bazel's
>    cache size when contributing to SCION, but require a running docker container acting with the
> ```

requires



_Code quote:_
```reStructuredText
require
```
___
*[`doc/dev/build.rst` line 91 at r5](https://reviewable.io/reviews/scionproto/scion/4448#-Nm6yOTU1uk7rsDN6v4p:-Nm6yOTV7BSxbwfRvTj3:b32whj) ([raw file](https://github.com/scionproto/scion/blob/5bdde50a72cc608bd24ecfc6df660240ca5513be/doc/dev/build.rst#L91)):*
> ```reStructuredText
> 
> #. Remove remote cache options from ``.bazelrc``; the default setup is useful to limit bazel's
>    cache size when contributing to SCION, but require a running docker container acting with the
> ```

as



_Code quote:_
```reStructuredText
with
```


<!-- Sent from Reviewable.io -->

2023-12-21 06:39 UTC, lukedirtwalker approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: all files reviewed, 6 unresolved discussions (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-12-21 08:41 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @marcfrei)

___
*[`doc/dev/build.rst` line 73 at r5](https://reviewable.io/reviews/scionproto/scion/4448#-Nm6vnFXBFlAo07QUvaL:-NmAX-6t9cYKePX9R66Q:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5bdde50a72cc608bd24ecfc6df660240ca5513be/doc/dev/build.rst#L73)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Prerequisites
</blockquote></details>

Done.
___
*[`doc/dev/build.rst` line 83 at r5](https://reviewable.io/reviews/scionproto/scion/4448#-Nm6xpI1EKB6KN3kUu7P:-NmAXDVN-ogouzvu4vXu:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5bdde50a72cc608bd24ecfc6df660240ca5513be/doc/dev/build.rst#L83)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Bazel
</blockquote></details>

Done.
___
*[`doc/dev/build.rst` line 90 at r5](https://reviewable.io/reviews/scionproto/scion/4448#-Nm6xyKW10mKMA9Ts6t1:-NmAXCQWDFksM_5_aHOc:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5bdde50a72cc608bd24ecfc6df660240ca5513be/doc/dev/build.rst#L90)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Bazel
</blockquote></details>

Done.
___
*[`doc/dev/build.rst` line 91 at r5](https://reviewable.io/reviews/scionproto/scion/4448#-Nm6yJvc9oAv9H7O6XPy:-NmAX7H-3_E73QiqQ5xc:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5bdde50a72cc608bd24ecfc6df660240ca5513be/doc/dev/build.rst#L91)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

requires
</blockquote></details>

Done.
___
*[`doc/dev/build.rst` line 91 at r5](https://reviewable.io/reviews/scionproto/scion/4448#-Nm6yOTU1uk7rsDN6v4p:-NmAX7k6C0tmprQ8Nfsl:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5bdde50a72cc608bd24ecfc6df660240ca5513be/doc/dev/build.rst#L91)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

as
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-21 08:43 UTC, marcfrei approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4448)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matzf)



<!-- Sent from Reviewable.io -->

2023-12-21 09:08 UTC, merged