testing: improved stream synthesis in router benchmark
scionproto/scion pull request #4457
Opened 2023-12-13 18:02 UTC by jiceatscion

Changes:
* Update the flowID of packets (and a couple of checksums) on the fly (just before sending) as opposed to pre-constructing a different packet for each stream.
* As a result, the test cases are simplified, they no-longer need to provide one packet per flowID.
* In passing, deleted the dumping of /proc/cpuinfo in the log. That has served its purpose.
* In the test harness, left in the form of comments, a suggestion of core partitioning. Not sure yet how to apply that in general. This is what provides the best results on my machine.

2023-12-19 15:09 UTC, matzf requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4457)* status: all files reviewed, 7 unresolved discussions (waiting on @jiceatscion)

___
*[`acceptance/router_benchmark/test.py` line 95 at r1](https://reviewable.io/reviews/scionproto/scion/4457#-Nm1ZTS204z9DYSAJWvY:-Nm1ZTS204z9DYSAJWvZ:b-l21tf9) ([raw file](https://github.com/scionproto/scion/blob/5444370bf9929dd90bd2ff1491b0c2c71b3f4976/acceptance/router_benchmark/test.py#L95)):*
> ```Python
> 
>     best = {cpus[0] for cpus in cores.values() if len(cpus) == 1}
>     chosen = {}
> ```

Python gotcha: `best` is a set as intended, but `chosen` is a dict. Same bug a few lines further down.

`chosen = set()`.
___
*[`acceptance/router_benchmark/test.py` line 144 at r1](https://reviewable.io/reviews/scionproto/scion/4457#-Nm1b-0R1xjgtt9nzWsj:-Nm1b-0R1xjgtt9nzWsk:b-78rzfp) ([raw file](https://github.com/scionproto/scion/blob/5444370bf9929dd90bd2ff1491b0c2c71b3f4976/acceptance/router_benchmark/test.py#L144)):*
> ```Python
>         # In the first iteration, A picks only first choice cpus and B supplements the harvest
>         # with second choice. If we still need more all first and second choice have been
>         # exhausted and subsequent iterations pick whatever's left.
> ```

Nit: coding out the third category explicitly would seem to make this much more straight forward (no while loop and no quality counter needed).  
___
*[`acceptance/router_benchmark/test.py` line 151 at r1](https://reviewable.io/reviews/scionproto/scion/4457#-Nm1a4FtBiaheAiIxmFU:-Nm1a4FtBiaheAiIxmFV:b3m542i) ([raw file](https://github.com/scionproto/scion/blob/5444370bf9929dd90bd2ff1491b0c2c71b3f4976/acceptance/router_benchmark/test.py#L151)):*
> ```Python
>                 break
>             if len(cpus) == 1:
>                 report[quality] += 1
> ```

`KeyError: 0`
___
*[`acceptance/router_benchmark/test.py` line 228 at r1](https://reviewable.io/reviews/scionproto/scion/4457#-Nm1T55rBB4vGb4O4YYA:-Nm1T55rBB4vGb4O4YYB:b-rt6rxc) ([raw file](https://github.com/scionproto/scion/blob/5444370bf9929dd90bd2ff1491b0c2c71b3f4976/acceptance/router_benchmark/test.py#L228)):*
> ```Python
>             cpu = c["cpu"]
>             core = c["core"]
>             if all_cpus is None or len(all_cpus) == 0:
> ```

Already checked above. Perhaps you wanted to check that `cpu` and `core` are usable? Also use `.get` for these?
___
*[`acceptance/router_benchmark/test.py` line 243 at r1](https://reviewable.io/reviews/scionproto/scion/4457#-Nm1TvDGArFImNioOhRh:-Nm1TvDGArFImNioOhRi:b-pzs1li) ([raw file](https://github.com/scionproto/scion/blob/5444370bf9929dd90bd2ff1491b0c2c71b3f4976/acceptance/router_benchmark/test.py#L243)):*
> ```Python
>                 caches[l2] = [cpu]
>             else:
>                 caches[l2].append(cpu)
> ```

Shortcut with `setdefault`. Same below for `cores`.



_Suggestion:_
```Python
            caches.setdefault(l2, []).append(cpu)
```
___
*[`acceptance/router_benchmark/test.py` line 390 at r1](https://reviewable.io/reviews/scionproto/scion/4457#-Nm1Uj5XC2FhJmk7KX9a:-Nm1Uj5XC2FhJmk7KX9b:b-hyd19r) ([raw file](https://github.com/scionproto/scion/blob/5444370bf9929dd90bd2ff1491b0c2c71b3f4976/acceptance/router_benchmark/test.py#L390)):*
> ```Python
>                "--network", "container:prometheus",
>                "--name", "router",
>                "--cpuset-cpus", f"{','.join(map(str, self.router_cpus))}",
> ```

Drop the `f"{}"`, this is already a string. Some more of these below.
___
*[`acceptance/router_benchmark/test.py` line 548 at r1](https://reviewable.io/reviews/scionproto/scion/4457#-Nm1VFOqApoJOxPLYJNd:-Nm1VFOr-dQuSBcDddDM:b-1bt5k5) ([raw file](https://github.com/scionproto/scion/blob/5444370bf9929dd90bd2ff1491b0c2c71b3f4976/acceptance/router_benchmark/test.py#L548)):*
> ```Python
>         # Log and check the saturation...
>         # If this is used as a CI test. Make sure that the saturation is within the expected
>         # ballpark (we expect at least 4% packet dropped due to queue overflow).
> ```

Nit: "4%" but the code has 1%. Maybe say "we expect a certain loss rate ..."?


<!-- Sent from Reviewable.io -->

2023-12-19 17:50 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4457)* status: all files reviewed, 5 unresolved discussions (waiting on @matzf)

___
*[`acceptance/router_benchmark/test.py` line 95 at r1](https://reviewable.io/reviews/scionproto/scion/4457#-Nm1ZTS204z9DYSAJWvY:-Nm1olOd49mW3y2ZusWQ:b35emgq) ([raw file](https://github.com/scionproto/scion/blob/5444370bf9929dd90bd2ff1491b0c2c71b3f4976/acceptance/router_benchmark/test.py#L95)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Python gotcha: `best` is a set as intended, but `chosen` is a dict. Same bug a few lines further down.

`chosen = set()`.
</blockquote></details>

F*g python. This one gets me at least once a year. And every time I notice the ambiguity I think python cleverly makes them indistinguishable. Then learn otherwise, then forget. Anyway... fixed.
___
*[`acceptance/router_benchmark/test.py` line 144 at r1](https://reviewable.io/reviews/scionproto/scion/4457#-Nm1b-0R1xjgtt9nzWsj:-Nm1s9wWAT68WbDYJiyd:b-85l0el) ([raw file](https://github.com/scionproto/scion/blob/5444370bf9929dd90bd2ff1491b0c2c71b3f4976/acceptance/router_benchmark/test.py#L144)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: coding out the third category explicitly would seem to make this much more straight forward (no while loop and no quality counter needed).
</blockquote></details>

Huh, actually that function was refactored one too many times and it's broken. It happens to no-longer be exercised on the CI or on my machine because the other two return better solutions. Fixing and re-testing. Regarding the style, I couldn't do it quite like you suggested, but you might like the rewrite.
Done
___
*[`acceptance/router_benchmark/test.py` line 151 at r1](https://reviewable.io/reviews/scionproto/scion/4457#-Nm1a4FtBiaheAiIxmFU:-Nm23feb0YaXtjq6etCc:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5444370bf9929dd90bd2ff1491b0c2c71b3f4976/acceptance/router_benchmark/test.py#L151)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`KeyError: 0`
</blockquote></details>

Done.
___
*[`acceptance/router_benchmark/test.py` line 228 at r1](https://reviewable.io/reviews/scionproto/scion/4457#-Nm1T55rBB4vGb4O4YYA:-Nm25DNYB3EKYnLD8rhB:b-e67ooy) ([raw file](https://github.com/scionproto/scion/blob/5444370bf9929dd90bd2ff1491b0c2c71b3f4976/acceptance/router_benchmark/test.py#L228)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Already checked above. Perhaps you wanted to check that `cpu` and `core` are usable? Also use `.get` for these?
</blockquote></details>

Right. Started it and... cookies?
___
*[`acceptance/router_benchmark/test.py` line 243 at r1](https://reviewable.io/reviews/scionproto/scion/4457#-Nm1TvDGArFImNioOhRh:-Nm25O6A3NTB8w9mnF_u:byazj3i) ([raw file](https://github.com/scionproto/scion/blob/5444370bf9929dd90bd2ff1491b0c2c71b3f4976/acceptance/router_benchmark/test.py#L243)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Shortcut with `setdefault`. Same below for `cores`.
</blockquote></details>

Better, I created a defaultdict.
___
*[`acceptance/router_benchmark/test.py` line 390 at r1](https://reviewable.io/reviews/scionproto/scion/4457#-Nm1Uj5XC2FhJmk7KX9a:-Nm27O4501EVK7hPO9sV:b-kjw1ks) ([raw file](https://github.com/scionproto/scion/blob/5444370bf9929dd90bd2ff1491b0c2c71b3f4976/acceptance/router_benchmark/test.py#L390)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Drop the `f"{}"`, this is already a string. Some more of these below.
</blockquote></details>

Oops.
Done
___
*[`acceptance/router_benchmark/test.py` line 548 at r1](https://reviewable.io/reviews/scionproto/scion/4457#-Nm1VFOqApoJOxPLYJNd:-Nm27oQGBxdG2qFBrO5j:b-r8hn55) ([raw file](https://github.com/scionproto/scion/blob/5444370bf9929dd90bd2ff1491b0c2c71b3f4976/acceptance/router_benchmark/test.py#L548)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: "4%" but the code has 1%. Maybe say "we expect a certain loss rate ..."?
</blockquote></details>

Yeah. It started as 4% but proved a bit too ambitious after the arithmetic error got fixed. Updated the comment to remove the duplicate number.


<!-- Sent from Reviewable.io -->

2023-12-20 13:22 UTC, matzf approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4457)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)



<!-- Sent from Reviewable.io -->

2023-12-20 13:39 UTC, matzf approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4457)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)



<!-- Sent from Reviewable.io -->

2023-12-20 13:53 UTC, merged