ci: fix build for openwrt package, enable setting version from env var
scionproto/scion pull request #4523
Opened 2024-05-14 20:50 UTC by matzf

Fix handling of release version (e.g. "0.11.0") in openwrt package build. Was only working for intermediate versions, like "0.10.0-32-asdlkjslka".

Allow overwriting the version used for the builds consistently. Previously there was an envar GIT_VERSION that could do this partially. Renamed to SCION_VERSION and supported now also fully for the package builds. Setting this variable in buildkite pipelines should now allow, for example, building release builds before explicitly tagging the release.

2024-05-14 20:50 UTC, matzf commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4523)
<!-- Reviewable:end -->

2024-05-15 08:34 UTC, jiceatscion requested changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4523)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`.buildkite/hooks/pre-command` line 38 at r2](https://reviewable.io/reviews/scionproto/scion/4523#-NxvMoop5K4pwXGy313s:-NxvMoop5K4pwXGy313t:blyt67) ([raw file](https://github.com/scionproto/scion/blob/9361a24b63f3b7ad043177707d1bf79b74506b03/.buildkite/hooks/pre-command#L38)):*
> ```
>         # This will be shortened to "<tag>-modified-ci"
>         export SCION_VERSION=$(tools/git-version | sed 's/-.*/-modified-ci/')
>     fi
> ```

Why not changing the variable name, but...why?
___
*[`dist/openwrt/ipk.bzl` line 100 at r2](https://reviewable.io/reviews/scionproto/scion/4523#-NxvMOBV-p5OR3vGosqw:-NxvMOBV-p5OR3vGosqx:b-vu6mo8) ([raw file](https://github.com/scionproto/scion/blob/9361a24b63f3b7ad043177707d1bf79b74506b03/dist/openwrt/ipk.bzl#L100)):*
> ```Starlark
>             ' PKG_VERSION="${pkgver}" PKG_RELEASE="${pkgrel}"',
>             r"cp bin/packages/${6}/scion/${2}_${pkgver}${pkgrel:+-}${pkgrel}_${6}.ipk ${execroot_abspath}/${4}",
>         ]),
> ```

Are there cases where pkgrel is empty?


<!-- Sent from Reviewable.io -->

2024-05-15 08:56 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4523)* status: all files reviewed, 2 unresolved discussions (waiting on @jiceatscion)

___
*[`.buildkite/hooks/pre-command` line 38 at r2](https://reviewable.io/reviews/scionproto/scion/4523#-NxvMoop5K4pwXGy313s:-NxvRjX_A4q-ZC2UYW8I:b-rqlqhf) ([raw file](https://github.com/scionproto/scion/blob/9361a24b63f3b7ad043177707d1bf79b74506b03/.buildkite/hooks/pre-command#L38)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Why not changing the variable name, but...why?
</blockquote></details>

Because calling it GIT_VERSION seemed like a lie; it's explicitly allows to build with a version name that is _not_ the git version.
___
*[`dist/openwrt/ipk.bzl` line 100 at r2](https://reviewable.io/reviews/scionproto/scion/4523#-NxvMOBV-p5OR3vGosqw:-NxvRWJx5ZfMrGBHVDJf:babz2qa) ([raw file](https://github.com/scionproto/scion/blob/9361a24b63f3b7ad043177707d1bf79b74506b03/dist/openwrt/ipk.bzl#L100)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Are there cases where pkgrel is empty?
</blockquote></details>

Yes, that's exactly the case that we're fixing here; when the git version is a release version like "0.11.0" , parsing it into `tag count commit dirty` result in an empty `pkgrel`. To match the returned file name, we omit the dash between pkgver and the empty pkgrel in this case.


<!-- Sent from Reviewable.io -->

2024-05-15 11:27 UTC, jiceatscion approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4523)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matzf)

___
*[`.buildkite/hooks/pre-command` line 38 at r2](https://reviewable.io/reviews/scionproto/scion/4523#-NxvMoop5K4pwXGy313s:-Nxw-Q7c0LSu9IKU3uLi:b-dxcbts) ([raw file](https://github.com/scionproto/scion/blob/9361a24b63f3b7ad043177707d1bf79b74506b03/.buildkite/hooks/pre-command#L38)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Because calling it GIT_VERSION seemed like a lie; it's explicitly allows to build with a version name that is _not_ the git version.
</blockquote></details>

Makes sense.
___
*[`dist/openwrt/ipk.bzl` line 100 at r2](https://reviewable.io/reviews/scionproto/scion/4523#-NxvMOBV-p5OR3vGosqw:-Nxw-LNcEfdodIg8Erb3:b-uv4ta) ([raw file](https://github.com/scionproto/scion/blob/9361a24b63f3b7ad043177707d1bf79b74506b03/dist/openwrt/ipk.bzl#L100)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Yes, that's exactly the case that we're fixing here; when the git version is a release version like "0.11.0" , parsing it into `tag count commit dirty` result in an empty `pkgrel`. To match the returned file name, we omit the dash between pkgver and the empty pkgrel in this case.
</blockquote></details>

Thanks for the clarification.


<!-- Sent from Reviewable.io -->

2024-05-16 06:57 UTC, merged