crypto: do not load already loaded TRC files
scionproto/scion pull request #4588
Opened 2024-07-31 06:52 UTC by lukedirtwalker

This commit introduces a TRC loader that keeps track of what TRC files have already been read. By doing so we can omit duplicate work of parsing TRC files and storing them in the DB.

This applies to the control service and the daemon.

2024-07-31 06:52 UTC, jiceatscion commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4588)
<!-- Reviewable:end -->

2024-07-31 08:13 UTC, oncilla requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4588)* status: all files reviewed, 3 unresolved discussions (waiting on @jiceatscion and @lukedirtwalker)

___
*[`private/trust/store.go` line 117 at r1](https://reviewable.io/reviews/scionproto/scion/4588#-O36qFOA9IJsn6nnBUnt:-O36qFOA9IJsn6nnBUnu:b-pkxa2x) ([raw file](https://github.com/scionproto/scion/blob/ae329d4ec290b973ce80d64ccc05a8c112daeaa1/private/trust/store.go#L117)):*
> ```Go
> // function exits on the first encountered error. TRCs with a not before time
> // in the future are ignored.
> // To load TRCs repeatedly, please use the dedicated TRCLoader.
> ```

You mean to *not* load TRCs repeatedly, correct?
___
*[`private/trust/store.go` line 168 at r1](https://reviewable.io/reviews/scionproto/scion/4588#-O36qLY4EytrJOdgiEg6:-O36qLY4EytrJOdgiEg7:b-9qgfbf) ([raw file](https://github.com/scionproto/scion/blob/ae329d4ec290b973ce80d64ccc05a8c112daeaa1/private/trust/store.go#L168)):*
> ```Go
> }
> 
> type TRCLoader struct {
> ```

nit: add some docs here. Especially that TRCs are not reloaded
___
*[`private/trust/store.go` line 185 at r1](https://reviewable.io/reviews/scionproto/scion/4588#-O36qSrh4_YR7D17TGjh:-O36qSrh4_YR7D17TGji:b-130svk) ([raw file](https://github.com/scionproto/scion/blob/ae329d4ec290b973ce80d64ccc05a8c112daeaa1/private/trust/store.go#L185)):*
> ```Go
> 	result, err := loadTRCs(ctx, l.Dir, l.DB, l.seen)
> 	for _, f := range result.Loaded {
> 		l.seen[f] = struct{}{}
> ```

Should we add it to seen even in case of an error?


<!-- Sent from Reviewable.io -->

2024-07-31 12:02 UTC, lukedirtwalker reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4588)* status: all files reviewed, 3 unresolved discussions (waiting on @jiceatscion and @oncilla)

___
*[`private/trust/store.go` line 185 at r1](https://reviewable.io/reviews/scionproto/scion/4588#-O36qSrh4_YR7D17TGjh:-O37ehFm7XzKuLPyzHaj:bo9fyyq) ([raw file](https://github.com/scionproto/scion/blob/ae329d4ec290b973ce80d64ccc05a8c112daeaa1/private/trust/store.go#L185)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Should we add it to seen even in case of an error?
</blockquote></details>

Yes, given we don't use a transaction in the loadTRCs function everything that is in the Loaded slice has been loaded into the DB AFAIU


<!-- Sent from Reviewable.io -->

2024-07-31 13:34 UTC, lukedirtwalker reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4588)* status: all files reviewed, 2 unresolved discussions (waiting on @jiceatscion and @oncilla)

___
*[`private/trust/store.go` line 117 at r1](https://reviewable.io/reviews/scionproto/scion/4588#-O36qFOA9IJsn6nnBUnt:-O37ze3s42_MD_HzV02A:beesd1w) ([raw file](https://github.com/scionproto/scion/blob/ae329d4ec290b973ce80d64ccc05a8c112daeaa1/private/trust/store.go#L117)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

You mean to *not* load TRCs repeatedly, correct?
</blockquote></details>

Hm I see how this comment could be misunderstood. I mean if you repeatedly call LoadTRCs you should use the TRCLoader.

I hope the new comment makes this clearer.
___
*[`private/trust/store.go` line 168 at r1](https://reviewable.io/reviews/scionproto/scion/4588#-O36qLY4EytrJOdgiEg6:-O37zs3-23als8_6upQf:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ae329d4ec290b973ce80d64ccc05a8c112daeaa1/private/trust/store.go#L168)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

nit: add some docs here. Especially that TRCs are not reloaded
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-31 13:51 UTC, oncilla approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4588)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion and @lukedirtwalker)

___
*[`private/trust/store.go` line 185 at r1](https://reviewable.io/reviews/scionproto/scion/4588#-O36qSrh4_YR7D17TGjh:-O382jR_EZeI6HmMu1J6:bbom0w4) ([raw file](https://github.com/scionproto/scion/blob/ae329d4ec290b973ce80d64ccc05a8c112daeaa1/private/trust/store.go#L185)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Yes, given we don't use a transaction in the loadTRCs function everything that is in the Loaded slice has been loaded into the DB AFAIU
</blockquote></details>

:bulb: 
___
*[`private/trust/store.go` line 172 at r2](https://reviewable.io/reviews/scionproto/scion/4588#-O382N2l8d8_JdoHQlaK:-O382N2mAeSmhCP1EQMr:b-bezdjq) ([raw file](https://github.com/scionproto/scion/blob/d1bcf7f1f30153e36492145ee9de614ebccd0acf/private/trust/store.go#L172)):*
> ```Go
> 
> // TRCLoader loads TRCs from a directory and stores them in the database. It
> // reminds files that it has already loaded and does not load them again.
> ```

nit: "remind" is the wrong verb here.



_Suggestion:_
```Go
// TRCLoader loads TRCs from a directory and stores them in the database. It
// tracks files that it has already loaded and does not load them again.
```


<!-- Sent from Reviewable.io -->

2024-07-31 14:52 UTC, oncilla approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4588)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)



<!-- Sent from Reviewable.io -->

2024-07-31 14:52 UTC, oncilla approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4588#-:-O38Gnr6DCVzvHAy4-D5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)



<!-- Sent from Reviewable.io -->

2024-08-02 05:44 UTC, lukedirtwalker reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4588)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

___
*[`private/trust/store.go` line 172 at r2](https://reviewable.io/reviews/scionproto/scion/4588#-O382N2l8d8_JdoHQlaK:-O3GbZvd2tuJca1sHI40:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d1bcf7f1f30153e36492145ee9de614ebccd0acf/private/trust/store.go#L172)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

nit: "remind" is the wrong verb here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-02 07:06 UTC, oncilla approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4588)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)



<!-- Sent from Reviewable.io -->

2024-08-28 08:56 UTC, jiceatscion approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4588)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[`control/trust.go` line 110 at r5](https://reviewable.io/reviews/scionproto/scion/4588#-O5N9JM50pSVtxHERWWg:-O5N9JM6-mqN2tQPxQBi:b-bruhyz) ([raw file](https://github.com/scionproto/scion/blob/7b04ceb837a5afaa98f865c91bcf6e3d8dc0356f/control/trust.go#L110)):*
> ```Go
> 			TRCDirs: []string{filepath.Join(cfgDir, "certs")},
> 			DB:      db,
> 		},
> ```

Any particular reason for switching to a reference?
___
*[`private/trust/store.go` line 121 at r5](https://reviewable.io/reviews/scionproto/scion/4588#-O5NBjhz7GzqmebDfaz-:-O5NBjhz7GzqmebDfaz0:b-ty83y5) ([raw file](https://github.com/scionproto/scion/blob/7b04ceb837a5afaa98f865c91bcf6e3d8dc0356f/private/trust/store.go#L121)):*
> ```Go
> // This function is not recommended for repeated use as it will read all TRC
> // files in a directory on every invocation. Consider using a TRCLoader if you
> // want to monitor a directory for new TRCs.
> ```

May be outright deprecate?


<!-- Sent from Reviewable.io -->

2024-08-28 11:15 UTC, lukedirtwalker reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4588)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

___
*[`control/trust.go` line 110 at r5](https://reviewable.io/reviews/scionproto/scion/4588#-O5N9JM50pSVtxHERWWg:-O5NgX292a6rESqn0Bsu:bf638ba) ([raw file](https://github.com/scionproto/scion/blob/7b04ceb837a5afaa98f865c91bcf6e3d8dc0356f/control/trust.go#L110)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Any particular reason for switching to a reference?
</blockquote></details>

because it now contains fields that need to be modified.
___
*[`private/trust/store.go` line 121 at r5](https://reviewable.io/reviews/scionproto/scion/4588#-O5NBjhz7GzqmebDfaz-:-O5NgHyLEr5ECaW9b6af:b-keovl9) ([raw file](https://github.com/scionproto/scion/blob/7b04ceb837a5afaa98f865c91bcf6e3d8dc0356f/private/trust/store.go#L121)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

May be outright deprecate?
</blockquote></details>

As a one off function it still makes sense.


<!-- Sent from Reviewable.io -->

2024-08-28 11:19 UTC, merged