Serrors renames
scionproto/scion pull request #4595
Opened 2024-08-12 16:19 UTC by jiceatscion

Implement the deprecation of the serrors constructors.

Wrap() -> JoinNoStack()
WithCtx() -> WrapNoStack()/JoinNoStack()
WrapStr() -> Wrap()

2024-08-12 16:19 UTC, jiceatscion commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4595)
<!-- Reviewable:end -->

2024-08-12 16:22 UTC, jiceatscion reviewed
Most of it is mechanical, with the exception of chosing between WrapNoStack and JoinNoStack as the replacement for WithCtx. In most cases, JoinNoStack was the better choice as the wrapped error was a sentinel error. I also tried to improve the doc string to help user chose the most appropriate constructor.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595#-:-O46NvE482RnuT7HFdpG:bd81z6v)* status: 0 of 214 files reviewed, all discussions resolved (waiting on @lukedirtwalker and @oncilla)



<!-- Sent from Reviewable.io -->

2024-08-12 16:31 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: 0 of 214 files reviewed, 2 unresolved discussions (waiting on @jiceatscion and @lukedirtwalker)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4595#-O46QBp63yPFDmU8FlNK:-O46QBp7-pN3g6N8iR3Y:b45dc55) (no related file):*
In https://github.com/scionproto/scion/releases/tag/v0.9.0 we attached a gopatch file to simplify transition for our downstreams.
I think it would be cool to do it here too.

___
*[a discussion](https://reviewable.io/reviews/scionproto/scion/4595#-O46QS1062cy9TD6o_zf:-O46QS1062cy9TD6o_zg:b-ej15c5) (no related file):*
Please update the title format to fit the usual pattern

___


<!-- Sent from Reviewable.io -->

2024-08-12 16:37 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: 0 of 214 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4595#-O46QBp63yPFDmU8FlNK:-O46R5SI8DJ5j2yuVDX4:b-k5hu7f) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

In https://github.com/scionproto/scion/releases/tag/v0.9.0 we attached a gopatch file to simplify transition for our downstreams.
I think it would be cool to do it here too.
</blockquote></details>

The conversion with goPatch isn't 100%; there's the choice between Wrap and Join (although wrap is always OK as a starting point), and there are some test function names (like ExampleXyz() that I fixed by hand. But I can include the patch files.Where would I place them? In the PR description text?

___
*[a discussion](https://reviewable.io/reviews/scionproto/scion/4595#-O46QS1062cy9TD6o_zf:-O46Ri0F7x1kC1e9ApWu:bjuzysv) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Please update the title format to fit the usual pattern
</blockquote></details>

Done Don't bother reminding. There's a automated check nowadays.

___


<!-- Sent from Reviewable.io -->

2024-08-12 16:39 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: 0 of 214 files reviewed, 5 unresolved discussions (waiting on @jiceatscion and @lukedirtwalker)

___
*[`pkg/private/serrors/errors.go` line 180 at r1](https://reviewable.io/reviews/scionproto/scion/4595#-O46RMYw6YjqxbjwijsJ:-O46RMYw6YjqxbjwijsK:b-45apot) ([raw file](https://github.com/scionproto/scion/blob/0128a97fb0269f64f12cdb915f9cefd3a0da1cf0/pkg/private/serrors/errors.go#L180)):*
> It can be used without an underlying
// cause by passing nil as the cause. In that case this behaves like New(), except that the
// underlying type of the returned interface is basicError, rather than a *basicError.

Do we really want to mention this. For one, basicError is package internal, and it is also not the intended use. The package client does not need to use this.

In fact, I think we should extend our linter to catch obviously wrong things like `serrors.Wrap("msg", nil, ...)`
___
*[`pkg/private/serrors/errors.go` line 188 at r1](https://reviewable.io/reviews/scionproto/scion/4595#-O46REwnBA7gZvS8MDGz:-O46REwnBA7gZvS8MDH-:bsp3b4o) ([raw file](https://github.com/scionproto/scion/blob/0128a97fb0269f64f12cdb915f9cefd3a0da1cf0/pkg/private/serrors/errors.go#L188)):*
> ```Go
> // instead use
> //
> //	Join(sentinel, nil, ...)
> ```

You can use https://tip.golang.org/doc/comment#doclinks `[Join]` to link to Join from the prose text above
___
*[`pkg/private/serrors/errors.go` line 254 at r1](https://reviewable.io/reviews/scionproto/scion/4595#-O46RgJV3Gaj9edM_138:-O46RgJV3Gaj9edM_139:b293b99) ([raw file](https://github.com/scionproto/scion/blob/0128a97fb0269f64f12cdb915f9cefd3a0da1cf0/pkg/private/serrors/errors.go#L254)):*
> ```Go
> // true.
> //
> // This is best used as an alternative to Wrap when deriving an error from a sentinel error. If
> ```

here and below



_Suggestion:_
```Go
 [Wrap]
```


<!-- Sent from Reviewable.io -->

2024-08-12 16:40 UTC, oncilla reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: 0 of 214 files reviewed, 4 unresolved discussions (waiting on @jiceatscion and @lukedirtwalker)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4595#-O46QBp63yPFDmU8FlNK:-O46SO-B2aQmZ_LtK2-g:b49w2zw) (no related file):*
What we have done in the past for ambiguous choices is to force a compiler error and let the user resolve it:

```
##@@
##var x expression
##@@
##-x.Source.Host.IP()
##+x.Source.Host.XXX_MANUAL_INTERVENTION_REQUIRED_IP_NOW_PANICS()
```

Yes, just list it in the PR description and we will include it in the release notes.


> (like ExampleXyz() that I fixed by hand.

API users don't really care about that. I think you only need to create the patch for the public API of the package.

___


<!-- Sent from Reviewable.io -->

2024-08-12 16:54 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: 0 of 214 files reviewed, 4 unresolved discussions (waiting on @lukedirtwalker and @oncilla)

___
*[`pkg/private/serrors/errors.go` line 180 at r1](https://reviewable.io/reviews/scionproto/scion/4595#-O46RMYw6YjqxbjwijsJ:-O46V6HVCO80XzbKEGTP:b-a7xv14) ([raw file](https://github.com/scionproto/scion/blob/0128a97fb0269f64f12cdb915f9cefd3a0da1cf0/pkg/private/serrors/errors.go#L180)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

> It can be used without an underlying
// cause by passing nil as the cause. In that case this behaves like New(), except that the
// underlying type of the returned interface is basicError, rather than a *basicError.

Do we really want to mention this. For one, basicError is package internal, and it is also not the intended use. The package client does not need to use this.

In fact, I think we should extend our linter to catch obviously wrong things like `serrors.Wrap("msg", nil, ...)`
</blockquote></details>

I wouldn't go that far. I updated the comment to indicate that there's rarely a reason to do it, but it is still the only way to get the same as from New() but as a value rather than pointer.
___
*[`pkg/private/serrors/errors.go` line 188 at r1](https://reviewable.io/reviews/scionproto/scion/4595#-O46REwnBA7gZvS8MDGz:-O46VeNi87aC7SSYcF9s:bb7f2mf) ([raw file](https://github.com/scionproto/scion/blob/0128a97fb0269f64f12cdb915f9cefd3a0da1cf0/pkg/private/serrors/errors.go#L188)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

You can use https://tip.golang.org/doc/comment#doclinks `[Join]` to link to Join from the prose text above
</blockquote></details>

done
___
*[`pkg/private/serrors/errors.go` line 254 at r1](https://reviewable.io/reviews/scionproto/scion/4595#-O46RgJV3Gaj9edM_138:-O46Vg-BDd7NX9iQfuCY:bb7f2mf) ([raw file](https://github.com/scionproto/scion/blob/0128a97fb0269f64f12cdb915f9cefd3a0da1cf0/pkg/private/serrors/errors.go#L254)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

here and below
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-08-12 17:08 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: 0 of 214 files reviewed, 3 unresolved discussions (waiting on @lukedirtwalker and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4595#-O46QBp63yPFDmU8FlNK:-O46YV1r5lA5ewAhPBKu:b-adokj9) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

What we have done in the past for ambiguous choices is to force a compiler error and let the user resolve it:

```
##@@
##var x expression
##@@
##-x.Source.Host.IP()
##+x.Source.Host.XXX_MANUAL_INTERVENTION_REQUIRED_IP_NOW_PANICS()
```

Yes, just list it in the PR description and we will include it in the release notes.


> (like ExampleXyz() that I fixed by hand.

API users don't really care about that. I think you only need to create the patch for the public API of the package.
</blockquote></details>

Nah, not for this. Migrating to Wrap is close enough to good. The other choice really is an embellishment. The shim was getting away with wrapStr well enough after all.

___


<!-- Sent from Reviewable.io -->

2024-08-13 13:59 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: 0 of 214 files reviewed, 3 unresolved discussions (waiting on @lukedirtwalker and @oncilla)

___
*[`pkg/private/serrors/errors.go` line 180 at r1](https://reviewable.io/reviews/scionproto/scion/4595#-O46RMYw6YjqxbjwijsJ:-O4B17IzBk6xEH1eX7sO:b-52l435) ([raw file](https://github.com/scionproto/scion/blob/0128a97fb0269f64f12cdb915f9cefd3a0da1cf0/pkg/private/serrors/errors.go#L180)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

I wouldn't go that far. I updated the comment to indicate that there's rarely a reason to do it, but it is still the only way to get the same as from New() but as a value rather than pointer.
</blockquote></details>

Tentatively resolving.


<!-- Sent from Reviewable.io -->

2024-08-14 08:23 UTC, oncilla requested changes
> Reviewed 213 of 214 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: all files reviewed, 34 unresolved discussions (waiting on @jiceatscion and @lukedirtwalker)

___
*[`gateway/control/sessionpolicy.go` line 115 at r2](https://reviewable.io/reviews/scionproto/scion/4595#-O4EtEAi5d8jnwLpF1Ey:-O4EtEAjCytaRispbrnC:b-xc5cyy) ([raw file](https://github.com/scionproto/scion/blob/0d290378935cacbafd62d05e0632bc44e8e515bb/gateway/control/sessionpolicy.go#L115)):*
> ```Go
> 	p, err := parser.Parse(ctx, raw)
> 	if err != nil {
> 		return nil, serrors.WrapNoStack("error", err, "file", file)
> ```

This should have been a wrap in the first place.



_Suggestion:_
```Go
serrors.Wrap("parsing", err, "file", file)
```
___
*[`pkg/experimental/hiddenpath/discovery.go` line 106 at r2](https://reviewable.io/reviews/scionproto/scion/4595#-O4EtxkX-KvvsCFsaU3D:-O4EtxkX-KvvsCFsaU3E:b-xc5cyy) ([raw file](https://github.com/scionproto/scion/blob/0d290378935cacbafd62d05e0632bc44e8e515bb/pkg/experimental/hiddenpath/discovery.go#L106)):*
> ```Go
> 	a, err := extractAddr(hps)
> 	if err != nil {
> 		return nil, serrors.WrapNoStack("error", err, "isd_as", ia)
> ```

This should have been a wrap in the first place.



_Suggestion:_
```Go
return nil, serrors.Wrap("extracting address", err, "isd_as", ia)
```
___
*[`pkg/experimental/hiddenpath/group.go` line 188 at r2](https://reviewable.io/reviews/scionproto/scion/4595#-O4EuMRe82sqCnc2D7df:-O4EuMRe82sqCnc2D7dg:b-ko5diq) ([raw file](https://github.com/scionproto/scion/blob/0d290378935cacbafd62d05e0632bc44e8e515bb/pkg/experimental/hiddenpath/group.go#L188)):*
> ```Go
> 	c, err := config.LoadResource(location)
> 	if err != nil {
> 		return nil, serrors.WrapNoStack("error", err, "location", location)
> ```

Should have been a Wrap in the first place.



_Suggestion:_
```Go
return nil, serrors.Wrap("reading", err, "location", location)
```
___
*[`pkg/experimental/hiddenpath/registrationpolicy.go` line 99 at r2](https://reviewable.io/reviews/scionproto/scion/4595#-O4EuSXf0GdbixLkMdqZ:-O4EuSXf0GdbixLkMdq_:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/0d290378935cacbafd62d05e0632bc44e8e515bb/pkg/experimental/hiddenpath/registrationpolicy.go#L99)):*
> ```Go
> 	c, err := config.LoadResource(location)
> 	if err != nil {
> 		return nil, nil, serrors.WrapNoStack("error", err, "location", location)
> ```

ditto



_Suggestion:_
```Go
return nil, nil, serrors.Wrap("reading", err, "location", location)
```
___
*[`pkg/private/serrors/errors.go` line 188 at r1](https://reviewable.io/reviews/scionproto/scion/4595#-O46REwnBA7gZvS8MDGz:-O4En23DCOFgBtkyQbSk:b-tn8pnb) ([raw file](https://github.com/scionproto/scion/blob/0128a97fb0269f64f12cdb915f9cefd3a0da1cf0/pkg/private/serrors/errors.go#L188)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

done
</blockquote></details>

I don't think it works in code blocks (but I might be wrong). I was thinking more along the lines:

```go
// To enrich a sentinel error with context only, do not use [Wrap]
//
//	Wrap("dummy message", sentinel, ...)
//
// instead use [Join]
//
//	Join(sentinel, nil, ...)

```
___
*[`pkg/private/serrors/errors.go` line 184 at r2](https://reviewable.io/reviews/scionproto/scion/4595#-O4EnWOJ2_eIxEiPVPkp:-O4EnWOJ2_eIxEiPVPkq:b2f5pd9) ([raw file](https://github.com/scionproto/scion/blob/0d290378935cacbafd62d05e0632bc44e8e515bb/pkg/private/serrors/errors.go#L184)):*
> ```Go
> // difference is the underlying type of the returned interface.
> //
> // To enrich a sentinel error, do not use
> ```

nit: This makes it sound like we should never use Wrap for sentinel errors, but there are cases where it is actually preferred IMO.



_Suggestion:_
```Go
To enrich a sentinel error with context only, do not use
```
___
*[`pkg/private/serrors/errors_test.go` line 349 at r2](https://reviewable.io/reviews/scionproto/scion/4595#-O4EpqgYBjqyw09lRDDQ:-O4EpqgYBjqyw09lRDDR:b-2gf051) ([raw file](https://github.com/scionproto/scion/blob/0d290378935cacbafd62d05e0632bc44e8e515bb/pkg/private/serrors/errors_test.go#L349)):*
> ```Go
> 	// ErrNoSpace is an error defined at package scope. It should be an error from a lower layer,
> 	// with some context information attached.
> 	var ErrNoSpace = serrors.New("no space", "dev", "sd0")
> ```

nit: ErrorNoSpace makes it seem like this is a sentinel error, but given it has context it is unlikely to be sentinel. 

I would change this example to be closer to the intended use of Join:
Adding sentinel error based on an error cause that we got. 

Maybe something like this:


```go
var cause = fmt.Errorf("sd0 unresponsive: %w", io.ErrNoProgress)
var ErrDB = errors.New("db")

wrapped := serros.Join(ErrDB, cause, "ctx", 1)

fmt.Println(errors.Is(wrapped, ErrDB))
fmt.Println(errors.Is(wrapped, io.ErrNoProgress))
```

This focuses on our intended use of Join. The second check against io.ErrNoProgress is just to showcase that we can get the underlying cause to. But we should focus more on our sentinel error here, which is ErrDB.
___
*[`pkg/private/serrors/errors_test.go` line 351 at r2](https://reviewable.io/reviews/scionproto/scion/4595#-O4Ep9V_77_eYsd4b6SU:-O4Ep9V_77_eYsd4b6SV:b-yl7pfn) ([raw file](https://github.com/scionproto/scion/blob/0d290378935cacbafd62d05e0632bc44e8e515bb/pkg/private/serrors/errors_test.go#L351)):*
> ```Go
> 	var ErrNoSpace = serrors.New("no space", "dev", "sd0")
> 	// ErrDB is an error defined at package scope. Here it figures a sentinel error.
> 	var ErrDB = serrors.New("db")
> ```

nit: serrors.New should not be used to construct sentinel errors.
It adds a stacktrace which is simply noise.

It will also surpress stack trace during joining/wrapping, which is not the intended behavior. 

I think we should use our preferred way of creating sentinel errors, which is errors.New or fmt.Errorf.



_Suggestion:_
```Go
var ErrDB = errors.New("db")
```
___
*[`pkg/private/serrors/errors_test.go` line 369 at r2](https://reviewable.io/reviews/scionproto/scion/4595#-O4EplWRBLqv5qwGd71a:-O4EplWRBLqv5qwGd71b:undefined) ([raw file](https://github.com/scionproto/scion/blob/0d290378935cacbafd62d05e0632bc44e8e515bb/pkg/private/serrors/errors_test.go#L369)):*
> ```Go
> func ExampleWrapNoStack() {
> 	// ErrBadL4 is an error defined at package scope.
> 	var ErrBadL4 = serrors.New("Unsupported L4 protocol")
> ```





_Suggestion:_
```Go
var ErrBadL4 = errors.New("unsupported L4 protocol")
```
___
*[`pkg/private/serrors/errors_test.go` line 370 at r2](https://reviewable.io/reviews/scionproto/scion/4595#-O4Es6B1EaqGXvT9E7zg:-O4Es6B1EaqGXvT9E7zh:b-a8jvfq) ([raw file](https://github.com/scionproto/scion/blob/0d290378935cacbafd62d05e0632bc44e8e515bb/pkg/private/serrors/errors_test.go#L370)):*
> ```Go
> 	// ErrBadL4 is an error defined at package scope.
> 	var ErrBadL4 = serrors.New("Unsupported L4 protocol")
> 	addedCtx := serrors.WrapNoStack("error", ErrBadL4, "type", "SCTP")
> ```

nit: let's use some values that are closer to the real usage.



_Suggestion:_
```Go
addedCtx := serrors.WrapNoStack("parsing packet", ErrBadL4, "type", "SCTP")
```
___
*[`pkg/private/serrors/errors_test.go` line 379 at r2](https://reviewable.io/reviews/scionproto/scion/4595#-O4EsKQf28T7Vv0oek4x:-O4EsKQf28T7Vv0oek4y:braxliq) ([raw file](https://github.com/scionproto/scion/blob/0d290378935cacbafd62d05e0632bc44e8e515bb/pkg/private/serrors/errors_test.go#L379)):*
> ```Go
> func ExampleJoinNoStack() {
> 	// errMsg is a sentinel error.
> 	var brokenPacket = serrors.New("broken")
> ```

nit: Let's use some values closer to real usage.



_Suggestion:_
```Go
var brokenPacket = errors.New("invalid packet")
```
___
*[`pkg/private/serrors/errors_test.go` line 381 at r2](https://reviewable.io/reviews/scionproto/scion/4595#-O4EpoFjAi0DtkESh9wu:-O4EpoFjAi0DtkESh9wv:undefined) ([raw file](https://github.com/scionproto/scion/blob/0d290378935cacbafd62d05e0632bc44e8e515bb/pkg/private/serro [...]

2024-08-14 08:25 UTC, oncilla requested changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: all files reviewed, 36 unresolved discussions (waiting on @jiceatscion and @lukedirtwalker)

___
*[`control/beaconing/extender.go` line 136 at r2](https://reviewable.io/reviews/scionproto/scion/4595#-O4EzId1ApOrQR6fpzfT:-O4EzId2E1B2XmX7ji88:bspmecl) ([raw file](https://github.com/scionproto/scion/blob/0d290378935cacbafd62d05e0632bc44e8e515bb/control/beaconing/extender.go#L136)):*
> ```Go
> 			return serrors.Wrap(
> 				"calculating expiry time from signer expiration time", err,
> 				"signer_expiration", signerExp)
> ```

nit: undo formatting change.
___
*[`control/beaconing/extender.go` line 239 at r2](https://reviewable.io/reviews/scionproto/scion/4595#-O4EzKH7DICwcMlRihyN:-O4EzKH7DICwcMlRihyO:b-sbnz91) ([raw file](https://github.com/scionproto/scion/blob/0d290378935cacbafd62d05e0632bc44e8e515bb/control/beaconing/extender.go#L239)):*
> ```Go
> 		return seg.HopEntry{}, nil, serrors.Wrap("checking remote ingress interface (mtu)", err,
> 			"interfaces", ingress)
> ```

There are a lot of places where you introduced an empty new line.
Was this intentional or rather a search/replace gone wrong?


<!-- Sent from Reviewable.io -->

2024-08-15 09:20 UTC, oncilla requested changes
> Reviewed 29 of 29 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: all files reviewed, 4 unresolved discussions (waiting on @jiceatscion and @lukedirtwalker)

___
*[`control/beaconing/extender.go` line 136 at r2](https://reviewable.io/reviews/scionproto/scion/4595#-O4EzId1ApOrQR6fpzfT:-O4KJ78y0GGa_ESFFyaw:b-ayv7df) ([raw file](https://github.com/scionproto/scion/blob/0d290378935cacbafd62d05e0632bc44e8e515bb/control/beaconing/extender.go#L136)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Yeah, I'm afraid that's gopatch handy work. I will assume that you have pointed out every change you wanted undone, so I won't recheck 215 files redundantly. Let me know if that is not the case.
</blockquote></details>

If we miss some we miss some :laughing: 
I also don't want to recheck... :running_man: 
___
*[`private/segment/segverifier/segverifier.go` line 162 at r3](https://reviewable.io/reviews/scionproto/scion/4595#-O4KJdcF8HaUvYeWeUgb:-O4KJdcF8HaUvYeWeUgc:b-ozkzo1) ([raw file](https://github.com/scionproto/scion/blob/97782242f4fe68af462bdb44afeee572c1424779/private/segment/segverifier/segverifier.go#L162)):*
> ```Go
> 		if err := segment.VerifyASEntry(ctx, verifier, i); err != nil {
> 			return serrors.JoinNoStack(ErrSegment, err,
> 				"seg", segment.String(), "as", asEntry.Local)
> ```

Q: With [#4597](https://github.com/scionproto/scion/pull/4597) this should not be necessary anymore because the segment implements the stringer interface. Did something not look as expected?



_Code quote:_
```Go
segment.String()
```
___
*[`private/trust/store.go` line 132 at r3](https://reviewable.io/reviews/scionproto/scion/4595#-O4KJzOf5HkL-2AZyHIh:-O4KJzOf5HkL-2AZyHIi:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/97782242f4fe68af462bdb44afeee572c1424779/private/trust/store.go#L132)):*
> ```Go
> 		raw, err := os.ReadFile(f)
> 		if err != nil {
> 			return res, serrors.WrapNoStack("error", err, "file", f)
> ```

ditto
___
*[`private/trust/store.go` line 140 at r3](https://reviewable.io/reviews/scionproto/scion/4595#-O4KK-N13XytE7P7Wf7k:-O4KK-N13XytE7P7Wf7l:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/97782242f4fe68af462bdb44afeee572c1424779/private/trust/store.go#L140)):*
> ```Go
> 		trc, err := cppki.DecodeSignedTRC(raw)
> 		if err != nil {
> 			return res, serrors.WrapNoStack("error", err, "file", f)
> ```

ditto
___
*[`private/trust/store.go` line 148 at r3](https://reviewable.io/reviews/scionproto/scion/4595#-O4KK0846xknjxtWDHGZ:-O4KK0846xknjxtWDHG_:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/97782242f4fe68af462bdb44afeee572c1424779/private/trust/store.go#L148)):*
> ```Go
> 		inserted, err := db.InsertTRC(ctx, trc)
> 		if err != nil {
> 			return res, serrors.WrapNoStack("error", err, "file", f)
> ```

ditto
___
*[`tools/braccept/runner/run.go` line 127 at r2](https://reviewable.io/reviews/scionproto/scion/4595#-O4EyUME2e2FA6B1jmSs:-O4KKFF383ZeAu6IY4K7:b-4t1lyp) ([raw file](https://github.com/scionproto/scion/blob/0d290378935cacbafd62d05e0632bc44e8e515bb/tools/braccept/runner/run.go#L127)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

The other errors aren't necessarily the cause, so I assume you mean Join(timeout, nil,...), If so, done.
</blockquote></details>

Ah. Yeah, I missed that bit. But Join is more appropriate anyway :thumbsup: 


<!-- Sent from Reviewable.io -->

2024-08-15 09:39 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: all files reviewed, 4 unresolved discussions (waiting on @lukedirtwalker and @oncilla)

___
*[`private/segment/segverifier/segverifier.go` line 162 at r3](https://reviewable.io/reviews/scionproto/scion/4595#-O4KJdcF8HaUvYeWeUgb:-O4KMTVuDSe-r_qGam62:b-45pe6m) ([raw file](https://github.com/scionproto/scion/blob/97782242f4fe68af462bdb44afeee572c1424779/private/segment/segverifier/segverifier.go#L162)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Q: With [#4597](https://github.com/scionproto/scion/pull/4597) this should not be necessary anymore because the segment implements the stringer interface. Did something not look as expected?
</blockquote></details>

That's the result of merging from master. It came from you: https://github.com/scionproto/scion/pull/4587
___
*[`private/trust/store.go` line 132 at r3](https://reviewable.io/reviews/scionproto/scion/4595#-O4KJzOf5HkL-2AZyHIh:-O4KOj497bjt_sMAzn57:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/97782242f4fe68af462bdb44afeee572c1424779/private/trust/store.go#L132)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`private/trust/store.go` line 140 at r3](https://reviewable.io/reviews/scionproto/scion/4595#-O4KK-N13XytE7P7Wf7k:-O4KOiQYBvBgnn6AS5nK:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/97782242f4fe68af462bdb44afeee572c1424779/private/trust/store.go#L140)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`private/trust/store.go` line 148 at r3](https://reviewable.io/reviews/scionproto/scion/4595#-O4KK0846xknjxtWDHGZ:-O4KOi-WApCTGJmMlPz9:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/97782242f4fe68af462bdb44afeee572c1424779/private/trust/store.go#L148)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-15 09:40 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: all files reviewed, 4 unresolved discussions (waiting on @lukedirtwalker and @oncilla)

___
*[`private/segment/segverifier/segverifier.go` line 162 at r3](https://reviewable.io/reviews/scionproto/scion/4595#-O4KJdcF8HaUvYeWeUgb:-O4KP6ykBXK8_bXiq4Ln:b8bv0jy) ([raw file](https://github.com/scionproto/scion/blob/97782242f4fe68af462bdb44afeee572c1424779/private/segment/segverifier/segverifier.go#L162)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

That's the result of merging from master. It came from you: https://github.com/scionproto/scion/pull/4587
</blockquote></details>

Want me to undo it here?


<!-- Sent from Reviewable.io -->

2024-08-15 11:38 UTC, oncilla reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @lukedirtwalker)

___
*[`private/segment/segverifier/segverifier.go` line 162 at r3](https://reviewable.io/reviews/scionproto/scion/4595#-O4KJdcF8HaUvYeWeUgb:-O4KopJS8xl1eE_Xg8WT:b-fydzjs) ([raw file](https://github.com/scionproto/scion/blob/97782242f4fe68af462bdb44afeee572c1424779/private/segment/segverifier/segverifier.go#L162)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Want me to undo it here?
</blockquote></details>

Ha, look at my memory :laughing: :facepalm: 

I think it would be good to revert since we are already here.

(making this comment non-blocking as it is unrelated to the PR.)


<!-- Sent from Reviewable.io -->

2024-08-15 11:38 UTC, oncilla approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)



<!-- Sent from Reviewable.io -->

2024-08-15 17:00 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: 215 of 216 files reviewed, all discussions resolved (waiting on @lukedirtwalker and @oncilla)

___
*[`private/segment/segverifier/segverifier.go` line 162 at r3](https://reviewable.io/reviews/scionproto/scion/4595#-O4KJdcF8HaUvYeWeUgb:-O4LyaCz6KSU6sz41Ohf:b-qxudij) ([raw file](https://github.com/scionproto/scion/blob/97782242f4fe68af462bdb44afeee572c1424779/private/segment/segverifier/segverifier.go#L162)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Ha, look at my memory :laughing: :facepalm: 

I think it would be good to revert since we are already here.

(making this comment non-blocking as it is unrelated to the PR.)
</blockquote></details>

Well...don't look at mine. ... and done.


<!-- Sent from Reviewable.io -->

2024-08-15 17:01 UTC, jiceatscion reviewed
> Reviewed 187 of 214 files at r1, 27 of 29 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4595)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)



<!-- Sent from Reviewable.io -->

2024-08-15 17:13 UTC, merged