WIP: router refactoring. Make room for multiple underlay impls.
scionproto/scion pull request #4658
Opened 2024-11-29 18:58 UTC by jiceatscion

2024-11-29 18:58 UTC, jiceatscion commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4658)
<!-- Reviewable:end -->

2025-01-27 10:13 UTC, tzaeschke reviewed
Iḿ not really familiar with this module and I'm probably missing a lot of context, so my review is almost exclusively about comments and naming.

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4658#-:-OHbEuPT88Hw3Zup00sF:bdiwaku)* status: 1 of 11 files reviewed, 22 unresolved discussions (waiting on @jiceatscion)

___
*[`-- commits` line 16 at r3](https://reviewable.io/reviews/scionproto/scion/4658#-OHb4W3M-_cXSsGfafAN:-OHb4W3M-_cXSsGfafAO:b-79qu3x):*
Since it is incomplete, maybe add some points about what exactly still needs to be done?
___
*[`router/underlay.go` line 33 at r3](https://reviewable.io/reviews/scionproto/scion/4658#-OHbCFDC69cn-rspDJjY:-OHbCFDC69cn-rspDJjZ:b-xijwt9) ([raw file](https://github.com/scionproto/scion/blob/a2fb58c1186dbcbafc115163299028f4dc686833/router/underlay.go#L33)):*
> ```Go
> 
> // Link embodies the router's idea of a point to point connection. A link associates the underlay
> // connection, with a bfdSession, a destination address, etc. It also allows the concrete send
> ```

connection with



_Code quote:_
```Go
connection, with
```
___
*[`router/underlay.go` line 48 at r3](https://reviewable.io/reviews/scionproto/scion/4658#-OHbCVmgCBVITj-pAfuT:-OHbCVmgCBVITj-pAfuU:b-80z19o) ([raw file](https://github.com/scionproto/scion/blob/a2fb58c1186dbcbafc115163299028f4dc686833/router/underlay.go#L48)):*
> ```Go
> 	IsUp() bool
> 	GetIfID() uint16
> 	GetRemote() netip.AddrPort // incremental refactoring: using code will move to underlay.
> ```

TODO?
___
*[`router/underlay.go` line 59 at r3](https://reviewable.io/reviews/scionproto/scion/4658#-OHbCaMJ4Jgp22TTEjz_:-OHbCaMJ4Jgp22TTEjza:b-80z19o) ([raw file](https://github.com/scionproto/scion/blob/a2fb58c1186dbcbafc115163299028f4dc686833/router/underlay.go#L59)):*
> ```Go
> //
> // Incremental refactoring: addresses are still explicitly IP/port. In the next step, we have to
> // make them opaque; to be interpreted only by the underlay implementation.
> ```

TODO?
___
*[`router/underlayproviders/udpip.go` line 27 at r3](https://reviewable.io/reviews/scionproto/scion/4658#-OHbD4gKE0UFOdHWlci4:-OHbD4gL2NBH4yxfMMwW:b2nhp4s) ([raw file](https://github.com/scionproto/scion/blob/a2fb58c1186dbcbafc115163299028f4dc686833/router/underlayproviders/udpip.go#L27)):*
> ```Go
> // This is currently the only implementation. The goal of splitting out this code from the router
> // is to enable other implementations. However, as a first step, we continue assuming that the
> // batchConn is given to us and is a Udp socket and that, in the case of externalLink, it is bound.
> ```

UDP



_Code quote:_
```Go
Udp
```
___
*[`router/underlayproviders/udpip.go` line 49 at r3](https://reviewable.io/reviews/scionproto/scion/4658#-OHbDNWPAV1B39e5Dyt9:-OHbDNWPAV1B39e5DytA:b3krg) ([raw file](https://github.com/scionproto/scion/blob/a2fb58c1186dbcbafc115163299028f4dc686833/router/underlayproviders/udpip.go#L49)):*
> ```Go
> 
> func (u *provider) GetConnections() map[netip.AddrPort]router.UnderlayConnection {
> 	// a map of interfaces and a map of concrete implementations aren't compatible.
> ```

A



_Code quote:_
```Go
a
```
___
*[`router/underlayproviders/udpip.go` line 50 at r3](https://reviewable.io/reviews/scionproto/scion/4658#-OHbDTW1AYLtxtFxuo-d:-OHbDTW1AYLtxtFxuo-e:b-pyansp) ([raw file](https://github.com/scionproto/scion/blob/a2fb58c1186dbcbafc115163299028f4dc686833/router/underlayproviders/udpip.go#L50)):*
> ```Go
> func (u *provider) GetConnections() map[netip.AddrPort]router.UnderlayConnection {
> 	// a map of interfaces and a map of concrete implementations aren't compatible.
> 	// For the same reason, we cannot have the map of concrete as our return type; it
> ```

concrete implementations as



_Code quote:_
```Go
concrete as
```
___
*[`router/underlayproviders/udpip.go` line 55 at r3](https://reviewable.io/reviews/scionproto/scion/4658#-OHbDkZ42r6W10p1J8Oi:-OHbDkZ52QcmZS-xCfQ2:b-30d7r4) ([raw file](https://github.com/scionproto/scion/blob/a2fb58c1186dbcbafc115163299028f4dc686833/router/underlayproviders/udpip.go#L55)):*
> ```Go
> 	// Since we do not want to store our own things as interfaces, we have to translate.
> 	// Good thing it doesn't happen often.
> 	m := make(map[netip.AddrPort]router.UnderlayConnection)
> ```

How often is `map()` called? Is it worth caching it?
___
*[`router/underlayproviders/udpip.go` line 90 at r3](https://reviewable.io/reviews/scionproto/scion/4658#-OHbE54a9CrOJbErAK4I:-OHbE54a9CrOJbErAK4J:b-80z19o) ([raw file](https://github.com/scionproto/scion/blob/a2fb58c1186dbcbafc115163299028f4dc686833/router/underlayproviders/udpip.go#L90)):*
> ```Go
> }
> 
> // Incremental refactoring: The following implements UnderlayConnection so some of the code
> ```

TODO?
___
*[`router/underlayproviders/udpip.go` line 202 at r3](https://reviewable.io/reviews/scionproto/scion/4658#-OHbET4qEwTeYrUABnca:-OHbET4qEwTeYrUABncb:b-7iwoov) ([raw file](https://github.com/scionproto/scion/blob/a2fb58c1186dbcbafc115163299028f4dc686833/router/underlayproviders/udpip.go#L202)):*
> ```Go
> // to erase the separation between link and connection for this implementation. Side effect
> // of moving the address:link here: the router does not know if there is an existing link. As
> // a result it has to give us a bfdSession in all cases and if we might throuw it away (there
> ```

throw



_Code quote:_
```Go
throuw
```
___
*[`router/underlayproviders/udpip.go` line 204 at r3](https://reviewable.io/reviews/scionproto/scion/4658#-OHbEXD84eNiaveqdmD7:-OHbEXD84eNiaveqdmD8:b-1yafxs) ([raw file](https://github.com/scionproto/scion/blob/a2fb58c1186dbcbafc115163299028f4dc686833/router/underlayproviders/udpip.go#L204)):*
> ```Go
> // a result it has to give us a bfdSession in all cases and if we might throuw it away (there
> // are no permanent resources attached to it). This will be fixed by moving some bfd related code
> // in-here; but later.
> ```

TODO? Maybe a ticket?
___
*[`router/underlayproviders/udpip.go` line 219 at r3](https://reviewable.io/reviews/scionproto/scion/4658#-OHbEmB023zOlISQ6q2Y:-OHbEmB023zOlISQ6q2Z:b-80z19o) ([raw file](https://github.com/scionproto/scion/blob/a2fb58c1186dbcbafc115163299028f4dc686833/router/underlayproviders/udpip.go#L219)):*
> ```Go
> 	c, exists := u.allConnections[netip.AddrPort{}]
> 	if !exists {
> 		// That doesn't actually happen and we'll get rid of this soon.
> ```

TODO?
___
*[`router/dataplane.go` line 232 at r3](https://reviewable.io/reviews/scionproto/scion/4658#-OHb4p8sADc-onOyOand:-OHb4p8sADc-onOyOane:b5yppwi) ([raw file](https://github.com/scionproto/scion/blob/a2fb58c1186dbcbafc115163299028f4dc686833/router/dataplane.go#L232)):*
> ```Go
> 	unsupportedUnspecifiedAddress = errors.New("unsupported unspecified address")
> 	noBFDSessionFound             = errors.New("no BFD session was found")
> 	// noBFDSessionConfigured        = errors.New("no BFD sessions have been configured")
> ```

Maybe remove this?
___
*[`router/dataplane.go` line 356 at r3](https://reviewable.io/reviews/scionproto/scion/4658#-OHb4xWSBvmj9dmNdi2B:-OHb4xWT3uWpOhxjGMGZ:b-3j3e4) ([raw file](https://github.com/scionproto/scion/blob/a2fb58c1186dbcbafc115163299028f4dc686833/router/dataplane.go#L356)):*
> ```Go
> 	}
> 
> 	l := d.underlay.NewInternalLink(conn, d.RunConfig.BatchSize)
> ```

rename to "link" or something longer than "l" (which I first read as "1")?
___
*[`router/dataplane.go` line 392 at r3](https://reviewable.io/reviews/scionproto/scion/4658#-OHb5Bua1f73tKCD1Cbx:-OHb5Bua1f73tKCD1Cby:byd4kvm) ([raw file](https://github.com/scionproto/scion/blob/a2fb58c1186dbcbafc115163299028f4dc686833/router/dataplane.go#L392)):*
> ```Go
> 	}
> 	lk := d.underlay.NewExternalLink(conn, d.RunConfig.BatchSize, bfd, dst.Addr, ifID)
> 	d.interfaces[ifID] = lk
> ```

lk -> link?
___
*[`router/dataplane.go` line 648 at r3]( [...]

2025-01-29 09:06 UTC, tzaeschke reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 11 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4658#-:-OHlIrmw2YVFcR-WGl-i:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)



<!-- Sent from Reviewable.io -->

2025-01-29 20:39 UTC, marcfrei requested changes
> Reviewed 8 of 11 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4658)* status: all files reviewed, 13 unresolved discussions (waiting on @jiceatscion)

___
*[`router/dataplane.go` line 81 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHngCQD-5mEGieM73vx:-OHngCQD-5mEGieM73vy:bsqvdqf) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/dataplane.go#L81)):*
> ```Go
> )
> 
> type BfdSession interface {
> ```

`BFDSession`

https://go.dev/wiki/CodeReviewComments#initialisms



_Code quote:_
```Go
BfdSession
```
___
*[`router/dataplane.go` line 472 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHn2sRL9DzGJnbs0LnH:-OHn2sRL9DzGJnbs0LnI:b-l4qtn3) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/dataplane.go#L472)):*
> ```Go
> }
> 
> func (d *DataPlane) addBFDController(ifID uint16, s bfd.Sender, cfg control.BFD,
> ```

This doesn't really add a `BFDController` (or BFDSession) anymore. Does it make sense to rename the method and maybe even make it a free-standing function instead of a method on `DataPlane`? The same might also apply to some of the methods using this one.



_Code quote:_
```Go
addBFDController
```
___
*[`router/dataplane.go` line 2474 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHneAQnBGJFaVgP9Qqn:-OHneAQnBGJFaVgP9Qqo:b-6oxt0z) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/dataplane.go#L2474)):*
> ```Go
> 	// If the packet is sent to an external router, we need to increment the
> 	// path to prepare it for the next hop.
> 	// This is an scmp response to pkt, so egress will be pkt.ingress.
> ```

`SCMP`?



_Code quote:_
```Go
scmp
```
___
*[`router/underlayproviders/udpip.go` line 63 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHnlHjk63VBNhtsfcE6:-OHnlHjk63VBNhtsfcE7:by6gpeu) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/underlayproviders/udpip.go#L63)):*
> ```Go
> 
> func (u *provider) GetLinks() map[netip.AddrPort]router.Link {
> 	return u.allLinks
> ```

Should we copy at least the map here? I tend towards 'yes'.



_Code quote:_
```Go
	return u.allLinks
```
___
*[`router/underlay.go` line 44 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHnhTDl3-m_VWV6wzTb:-OHnhTDmD_fATugkWqNs:b-66q0m1) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/underlay.go#L44)):*
> ```Go
> // the link is a sibling link. If the interface ID is zero, then the link is the internal link.
> type Link interface {
> 	GetScope() LinkScope
> ```

`Scope`



_Code quote:_
```Go
	GetScope
```
___
*[`router/underlay.go` line 45 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHnhb131Gir9wluTH8x:-OHnhb140UuGV3QTv3yy:beaqxjj) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/underlay.go#L45)):*
> ```Go
> type Link interface {
> 	GetScope() LinkScope
> 	GetBfdSession() BfdSession
> ```

`BFDSession`



_Code quote:_
```Go
	GetBfdSession
```
___
*[`router/underlay.go` line 47 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHnhyaLDNCLZXFm0dxs:-OHnhyaLDNCLZXFm0dxt:b-u4zmxf) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/underlay.go#L47)):*
> ```Go
> 	GetBfdSession() BfdSession
> 	IsUp() bool
> 	GetIfID() uint16
> ```

`IfID`



_Code quote:_
```Go
	GetIfID
```
___
*[`router/underlay.go` line 48 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHniW2I5Yh0837kcoc9:-OHniW2I5Yh0837kcocA:bp7gjwk) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/underlay.go#L48)):*
> ```Go
> 	IsUp() bool
> 	GetIfID() uint16
> 	GetRemote() netip.AddrPort // TODO(multi_underlay): using code will move to underlay.
> ```

`Remote` or `RemoteAddrPort`



_Code quote:_
```Go
	GetRemote
```
___
*[`router/underlay.go` line 50 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHnj1d10J3sg_fw8jb0:-OHnj1d10J3sg_fw8jb1:b-c45by3) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/underlay.go#L50)):*
> ```Go
> 	GetRemote() netip.AddrPort // TODO(multi_underlay): using code will move to underlay.
> 	Send(p *Packet) bool
> 	BlockSend(p *Packet)
> ```

Should this really be part of the interface? It's only used for testing, right?



_Code quote:_
```Go
	BlockSend(p *Packet)
```
___
*[`router/underlay.go` line 86 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHnj_sV1rY94orpOcBz:-OHnj_sV1rY94orpOcC-:b-x6e3ei) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/underlay.go#L86)):*
> ```Go
> 	// dataplane code for now. There may be fewer connections than links. For example, right now
> 	// all sibling links and the internal link use a shared un-bound connection.
> 	GetConnections() map[netip.AddrPort]UnderlayConnection
> ```

`Connections`



_Code quote:_
```Go
	GetConnections
```
___
*[`router/underlay.go` line 93 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHnjjMHA0eKIhl8OQj2:-OHnjjMHA0eKIhl8OQj3:b-9erc66) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/underlay.go#L93)):*
> ```Go
> 	// There may be fewer links than ifIDs. For example, all interfaces owned by one given sibling
> 	// router are connected via the same link because the remote address is the same.
> 	GetLinks() map[netip.AddrPort]Link
> ```

`Links`



_Code quote:_
```Go
	GetLinks
```
___
*[`router/underlay.go` line 101 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHnjwLk2ENtFuTbmzBB:-OHnjwLk2ENtFuTbmzBC:bulhskp) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/underlay.go#L101)):*
> ```Go
> 	// matched with a link), on ingest by the underlay. That would imply moving a part of the
> 	// runReceiver routine to the underlay. We will do that in the next step.
> 	GetLink(netip.AddrPort) Link
> ```

`Link` or `LinkFor`



_Code quote:_
```Go
	GetLink
```
___
*[`router/underlay.go` line 109 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHnkPlh9KH-1PxHPLZO:-OHnkPlh9KH-1PxHPLZP:b-j1vn6j) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/underlay.go#L109)):*
> ```Go
> // TODO(multi_underlay): this will eventually be reduced to nothing at all because the sender
> // receiver tasks will be part of the underlay.
> type UnderlayConnection interface {
> ```

`UnderlayConn` and the first method then `BatchConn()`?



_Code quote:_
```Go
UnderlayConnection
```


<!-- Sent from Reviewable.io -->

2025-01-31 09:23 UTC, marcfrei requested changes
> Reviewed 2 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4658)* status: all files reviewed, 7 unresolved discussions (waiting on @jiceatscion)

___
*[`router/dataplane.go` line 472 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHn2sRL9DzGJnbs0LnH:-OHvJCSm5i9XxOP_0pLQ:b60oy57) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/dataplane.go#L472)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Done. I agree that this in not a method and not an Add anymore. Renamed "NewBFDController" for the same reason. renamed AddNextHopBFD and AddExternalInterfaceBFD (although they are still methods od DataPlane. One thing I noticed is that newBFDController doesn't seem like it even belong in DataPlane anymore. Should we move it to bfd/session.go ?
</blockquote></details>

Yes, moving to bfd/session.go sounds good. And should we rename it to `newBFDSession`?

The other question would be whether we could also directly use *bfd.Session instead of having the interface `BFDSession`. bfd.Session has already abstracted away the sending and receiving part. But maybe that's for another refactoring.
___
*[`router/underlay.go` line 50 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHnj1d10J3sg_fw8jb0:-OHv_Q1l-4vdWWaX0cNj:b-tzsx6b) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/underlay.go#L50)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Yes, it is only used by tests. Unfortunately, there's no reasonably simple way of implementing that only in test code. It would take a ridiculous amount of plumbing. Anything wrong about actually having a BlockSend method, even if only for testability? Otherwise, any suggestion?
</blockquote></details>

Ok. But I would at least rename it to `SendBlocking`. I think that's more clear and it also shows that it's a variant of `Send
___
*[`router/underlayproviders/udpip.go` line 95 at r6](https://reviewable.io/reviews/scionproto/scion/4658#-OHvcIb528nWJIGEOa4n:-OHvcIb528nWJIGEOa4o:bcbsqkz) ([raw file](https://github.com/scionproto/scion/blob/48fcef7b1f75b7967719a777bb120b49202569d9/router/underlayproviders/udpip.go#L95)):*
> ```Go
> // next step
> 
> // Name returns the name (for logging) associated with a connection.
> ```

Remove comment or fix it.
___
*[`router/underlayproviders/udpip.go` line 100 at r6](https://reviewable.io/reviews/scionproto/scion/4658#-OHvcT1mATLOQ59UZ3UU:-OHvcT1mATLOQ59UZ3UV:bcbsqkz) ([raw file](https://github.com/scionproto/scion/blob/48fcef7b1f75b7967719a777bb120b49202569d9/router/underlayproviders/udpip.go#L100)):*
> ```Go
> }
> 
> // Name returns the name (for logging) associated with a connection.
> ```

Remove comment or fix it.
___
*[`router/underlayproviders/udpip.go` line 105 at r6](https://reviewable.io/reviews/scionproto/scion/4658#-OHvcTj4EGjsC3FIrf7L:-OHvcTj4EGjsC3FIrf7M:b-vfv9pl) ([raw file](https://github.com/scionproto/scion/blob/48fcef7b1f75b7967719a777bb120b49202569d9/router/underlayproviders/udpip.go#L105)):*
> ```Go
> }
> 
> // Name returns the name (for logging) associated with a connection.
> ```

Remove comment?
___
*[`router/underlayproviders/udpip.go` line 110 at r6](https://reviewable.io/reviews/scionproto/scion/4658#-OHvcUrw-jGQuzOGHzB9:-OHvcUrw-jGQuzOGHzBA:bcbsqkz) ([raw file](https://github.com/scionproto/scion/blob/48fcef7b1f75b7967719a777bb120b49202569d9/router/underlayproviders/udpip.go#L110)):*
> ```Go
> }
> 
> // Name returns the name (for logging) associated with a connection.
> ```

Remove comment or fix it.
___
*[`router/underlayproviders/udpip.go` line 255 at r6](https://reviewable.io/reviews/scionproto/scion/4658#-OHvdAtw9MmL5qWytCzO:-OHvdAtw9MmL5qWytCzP:b-sm9pop) ([raw file](https://github.com/scionproto/scion/blob/48fcef7b1f75b7967719a777bb120b49202569d9/router/underlayproviders/udpip.go#L255)):*
> ```Go
> 
> func (l *siblingLink) Send(p *router.Packet) bool {
> 	// We use an unbound connection but we offer a connected-oriented service. So, we need to
> ```

`connection-oriented`?



_Code quote:_
```Go
connected-oriented
```
___
*[`router/underlayproviders/udpip.go` line 267 at r6](https://reviewable.io/reviews/scionproto/scion/4658#-OHvdKYQ5F7_t1pbLfOY:-OHvdKYQ5F7_t1pbLfOZ:b-sm9pop) ([raw file](https://github.com/scionproto/scion/blob/48fcef7b1f75b7967719a777bb120b49202569d9/router/underlayproviders/udpip.go#L267)):*
> ```Go
> 
> func (l *siblingLink) BlockSend(p *router.Packet) {
> 	// We use an unbound connection but we offer a connected-oriented service. So, we need to
> ```

`connection-oriented`?



_Code quote:_
```Go
connected-oriented
```


<!-- Sent from Reviewable.io -->

2025-01-31 12:26 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4658)* status: 7 of 13 files reviewed, 6 unresolved discussions (waiting on @marcfrei and @tzaeschke)

___
*[`router/dataplane.go` line 472 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHn2sRL9DzGJnbs0LnH:-OHwCNO7El0H9OU72NEq:bc8mlpm) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/dataplane.go#L472)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Yes, moving to bfd/session.go sounds good. And should we rename it to `newBFDSession`?

The other question would be whether we could also directly use *bfd.Session instead of having the interface `BFDSession`. bfd.Session has already abstracted away the sending and receiving part. But maybe that's for another refactoring.
</blockquote></details>

With you on both accounts. Moved/renamed, but keeping interface for now.
___
*[`router/underlay.go` line 50 at r4](https://reviewable.io/reviews/scionproto/scion/4658#-OHnj1d10J3sg_fw8jb0:-OHwDPU2--rt3le5cozd:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/2df9f4dc82d5ea16849a63c4ea5d48bc519a3d6e/router/underlay.go#L50)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Ok. But I would at least rename it to `SendBlocking`. I think that's more clear and it also shows that it's a variant of `Send
</blockquote></details>

Done.
___
*[`router/underlayproviders/udpip.go` line 95 at r6](https://reviewable.io/reviews/scionproto/scion/4658#-OHvcIb528nWJIGEOa4n:-OHwIHcr-VJdR-mM095G:b-di29ub) ([raw file](https://github.com/scionproto/scion/blob/48fcef7b1f75b7967719a777bb120b49202569d9/router/underlayproviders/udpip.go#L95)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Remove comment or fix it.
</blockquote></details>

Done moved doc strings to the interface and fixed them all.
___
*[`router/underlayproviders/udpip.go` line 100 at r6](https://reviewable.io/reviews/scionproto/scion/4658#-OHvcT1mATLOQ59UZ3UU:-OHwIN_OEsmwrh7Y-qxT:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/48fcef7b1f75b7967719a777bb120b49202569d9/router/underlayproviders/udpip.go#L100)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Remove comment or fix it.
</blockquote></details>

Done.
___
*[`router/underlayproviders/udpip.go` line 105 at r6](https://reviewable.io/reviews/scionproto/scion/4658#-OHvcTj4EGjsC3FIrf7L:-OHwIOrE0RtTtjnlEnL_:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/48fcef7b1f75b7967719a777bb120b49202569d9/router/underlayproviders/udpip.go#L105)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Remove comment?
</blockquote></details>

Done.
___
*[`router/underlayproviders/udpip.go` line 110 at r6](https://reviewable.io/reviews/scionproto/scion/4658#-OHvcUrw-jGQuzOGHzB9:-OHwIPfl8Ll5bRNWQNrh:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/48fcef7b1f75b7967719a777bb120b49202569d9/router/underlayproviders/udpip.go#L110)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Remove comment or fix it.
</blockquote></details>

Done.
___
*[`router/underlayproviders/udpip.go` line 267 at r6](https://reviewable.io/reviews/scionproto/scion/4658#-OHvdKYQ5F7_t1pbLfOY:-OHwIbuY0cf_oDlX1-j8:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/48fcef7b1f75b7967719a777bb120b49202569d9/router/underlayproviders/udpip.go#L267)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

`connection-oriented`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-03 14:28 UTC, marcfrei requested changes
> Reviewed 3 of 6 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4658)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

___
*[`router/bfd/session.go` line 167 at r8](https://reviewable.io/reviews/scionproto/scion/4658#-OIB8UFJ7dk1LOq1drAt:-OIB8UFJ7dk1LOq1drAu:bgqwi7y) ([raw file](https://github.com/scionproto/scion/blob/4f70f2e4f024552ceff555994b36303530bdc81e/router/bfd/session.go#L167)):*
> ```Go
> }
> 
> func NewBFDSession(ifID uint16, s Sender, cfg control.BFD,
> ```

Looking at the function now that it is in package `bfd` I'm not sure anymore whether this was a good idea in the first place. Multiple concerns:
- It should be called `NewSession` now
- Argument `ifID` is not used
- It pulls in the dependency on `github.com/scionproto/scion/router/control`
- How general is this random discriminator functionality?
- Hardcoded `ReceiveQueueSize`

Not sure how unacceptable these points really are, but in doubt I'd probably keep the function (as `newBFDSession`)  in dataplane.go for now. Sorry.


<!-- Sent from Reviewable.io -->

2025-02-03 16:33 UTC, jiceatscion reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4658)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @marcfrei)

___
*[`router/bfd/session.go` line 167 at r8](https://reviewable.io/reviews/scionproto/scion/4658#-OIB8UFJ7dk1LOq1drAt:-OIBVREdDgLXz6pWMF58:bqv5a01) ([raw file](https://github.com/scionproto/scion/blob/4f70f2e4f024552ceff555994b36303530bdc81e/router/bfd/session.go#L167)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Looking at the function now that it is in package `bfd` I'm not sure anymore whether this was a good idea in the first place. Multiple concerns:
- It should be called `NewSession` now
- Argument `ifID` is not used
- It pulls in the dependency on `github.com/scionproto/scion/router/control`
- How general is this random discriminator functionality?
- Hardcoded `ReceiveQueueSize`

Not sure how unacceptable these points really are, but in doubt I'd probably keep the function (as `newBFDSession`)  in dataplane.go for now. Sorry.
</blockquote></details>

I think that it is better to fix these things and leave the code here.
- NewSession: Done. Indeed.
- ifID not used: Gone. It was no-longer used before; I should have removed it anyway.
- dependency on controller (sure, that's normal, it provides the BFD configuration). Controller.go will need a bit of refactor in the next phase anyway, I might want to move the creation of bfd sessions down to underlay.go anyway, so we'll see to the config then, if we need to.
- the discriminator is no worse or better than before. It actually doesn't mater; we don't really use it. This is one thing that could stay in the router, given that it's the router that doesn't need it... but then, having a reasonable built-in is more convenient (and ensures protocol compliance).
- queue size: it is better hard-coded here than in the caller. It is a matter of implementation. The caller should certainly not know what to use.

I think that your concerns stem from the fact that bfd now looks more like a general purpose library than before, but thanks to Go's 1-level package hierarchy, it already was exported; just without a constructor. Doesn't mean that we need to support non-router usage. Given that it was already exposed to such non-router use, this is actually an improvement.


<!-- Sent from Reviewable.io -->

2025-02-03 18:05 UTC, marcfrei approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4658#-:-OIBzMp90dJJmyBE1R5O:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

___
*[`router/bfd/session.go` line 167 at r8](https://reviewable.io/reviews/scionproto/scion/4658#-OIB8UFJ7dk1LOq1drAt:-OIBz05NDYBS03w5t-W1:b-m1nt0i) ([raw file](https://github.com/scionproto/scion/blob/4f70f2e4f024552ceff555994b36303530bdc81e/router/bfd/session.go#L167)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

I think that it is better to fix these things and leave the code here.
- NewSession: Done. Indeed.
- ifID not used: Gone. It was no-longer used before; I should have removed it anyway.
- dependency on controller (sure, that's normal, it provides the BFD configuration). Controller.go will need a bit of refactor in the next phase anyway, I might want to move the creation of bfd sessions down to underlay.go anyway, so we'll see to the config then, if we need to.
- the discriminator is no worse or better than before. It actually doesn't mater; we don't really use it. This is one thing that could stay in the router, given that it's the router that doesn't need it... but then, having a reasonable built-in is more convenient (and ensures protocol compliance).
- queue size: it is better hard-coded here than in the caller. It is a matter of implementation. The caller should certainly not know what to use.

I think that your concerns stem from the fact that bfd now looks more like a general purpose library than before, but thanks to Go's 1-level package hierarchy, it already was exported; just without a constructor. Doesn't mean that we need to support non-router usage. Given that it was already exposed to such non-router use, this is actually an improvement.
</blockquote></details>

All clear, let's try it like this then.


<!-- Sent from Reviewable.io -->

2025-02-04 09:04 UTC, merged