pkg/snet: always use topology to resolve interfaces
scionproto/scion pull request #4673
Opened 2024-12-23 06:07 UTC by lukedirtwalker

This way we can resolve interfaces even if they are dynamically changing.

2024-12-23 06:07 UTC, jiceatscion commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scionproto/scion/4673)
<!-- Reviewable:end -->

2024-12-23 06:09 UTC, lukedirtwalker reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4673)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @JordiSubira)

___
*[a discussion](https://reviewable.io/reviews/scionproto/scion/4673#-OEm7G4v2c45iO87I7n_:-OEm7G4v2c45iO87I7na:b5130uq) (no related file):*
This is more of a proposal of how we could deal with changing topologies for processes that have long standing connections. We could probably introduce some caching layer on top of snet.Topology. What do you think @JordiSubira ?


<!-- Sent from Reviewable.io -->

2024-12-23 09:14 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4673)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[a discussion](https://reviewable.io/reviews/scionproto/scion/4673#-OEm7G4v2c45iO87I7n_:-OEmaH3TAfymU1D4NTNV:b-t3k0i0) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

This is more of a proposal of how we could deal with changing topologies for processes that have long standing connections. We could probably introduce some caching layer on top of snet.Topology. What do you think @JordiSubira ?
</blockquote></details>

Indeed, back on the [dispatcherless PR](https://github.com/scionproto/scion/pull/4344) we discussed about adding some wrapper around the` snet.Daemon` API for the caching topology related requests.

We decided to put on `snet.SCIONPacketConn` the `interfaceMap` as a "once"-cache when opening a connection, which is not ideal because as you said the interface<->ID mapping can dynamically change. We sacrificed this to avoid having to call the daemon API on each packet (because more of the applications use the daemon to implement `n.Topology` right now). 

Do you think we can add the caching layer into this PR? We can have for the moment a simple one, even one shot and allow the application either to instantiate the wrapper or directly the `snet.Daemon` one.


<!-- Sent from Reviewable.io -->

2024-12-23 11:23 UTC, lukedirtwalker reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4673)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @JordiSubira)

___
*[a discussion](https://reviewable.io/reviews/scionproto/scion/4673#-OEm7G4v2c45iO87I7n_:-OEnFL646Hb7n19MuSSL:b-bd2olh) (no related file):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

Indeed, back on the [dispatcherless PR](https://github.com/scionproto/scion/pull/4344) we discussed about adding some wrapper around the` snet.Daemon` API for the caching topology related requests.

We decided to put on `snet.SCIONPacketConn` the `interfaceMap` as a "once"-cache when opening a connection, which is not ideal because as you said the interface<->ID mapping can dynamically change. We sacrificed this to avoid having to call the daemon API on each packet (because more of the applications use the daemon to implement `n.Topology` right now). 

Do you think we can add the caching layer into this PR? We can have for the moment a simple one, even one shot and allow the application either to instantiate the wrapper or directly the `snet.Daemon` one.
</blockquote></details>

Sure, I can add a caching layer here.


<!-- Sent from Reviewable.io -->

2024-12-23 16:02 UTC, oncilla requested changes
> Reviewed 10 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4673)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @JordiSubira and @lukedirtwalker)

___
*[`pkg/daemon/topology.go` line 94 at r3](https://reviewable.io/reviews/scionproto/scion/4673#-OEoElEf8Xn574DdmofO:-OEoElEf8Xn574DdmofP:b-fk52f9) ([raw file](https://github.com/scionproto/scion/blob/cd48ed84dcdf3a5501c22882a419d0676af5d56d/pkg/daemon/topology.go#L94)):*
> ```Go
> }
> 
> func (t *ReloadingTopology) Run(ctx context.Context, period time.Duration) {
> ```

We never clean up the entries that are no longer present.

Is that an issue, or do we assume interfaces are not removed?
If we assume that, I think we should add a corresponding comment
___
*[`control/cmd/control/main.go` line 957 at r3](https://reviewable.io/reviews/scionproto/scion/4673#-OEoF7138xnMskm7khmJ:-OEoF7138xnMskm7khmK:bcbij8n) ([raw file](https://github.com/scionproto/scion/blob/cd48ed84dcdf3a5501c22882a419d0676af5d56d/control/cmd/control/main.go#L957)):*
> ```Go
> 		},
> 		Interface: func(ifID uint16) (netip.AddrPort, bool) {
> 			// XXX(lukedirtwalker): The amount of conversiones between
> ```

nit: Given we know when the data changes, I think it would be easy to convert it only once and store it.


<!-- Sent from Reviewable.io -->

2024-12-23 16:16 UTC, lukedirtwalker reviewed
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4673)* status: 9 of 14 files reviewed, 3 unresolved discussions (waiting on @JordiSubira and @oncilla)

___
*[`control/cmd/control/main.go` line 957 at r3](https://reviewable.io/reviews/scionproto/scion/4673#-OEoF7138xnMskm7khmJ:-OEoIDW-50QDXNSudHkx:b-tu2342) ([raw file](https://github.com/scionproto/scion/blob/cd48ed84dcdf3a5501c22882a419d0676af5d56d/control/cmd/control/main.go#L957)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

nit: Given we know when the data changes, I think it would be easy to convert it only once and store it.
</blockquote></details>

yeah my issue is more that the topology loads as netip.AddrPort but then the API `UnderlayNextHop` exposes it as *net.UDPAddr, the snet API actually converts the netip.AddrPort back to *net.UDPAddr internally :trollface: 
___
*[`pkg/daemon/topology.go` line 94 at r3](https://reviewable.io/reviews/scionproto/scion/4673#-OEoElEf8Xn574DdmofO:-OEoHuNqEyAjraF1tHRi:b-dlbpt4) ([raw file](https://github.com/scionproto/scion/blob/cd48ed84dcdf3a5501c22882a419d0676af5d56d/pkg/daemon/topology.go#L94)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

We never clean up the entries that are no longer present.

Is that an issue, or do we assume interfaces are not removed?
If we assume that, I think we should add a corresponding comment
</blockquote></details>

Good catch

The only issue I could think of is memory leak. For now I added a comment, but for good measure I'll fix the actual implementation tomorrow.


<!-- Sent from Reviewable.io -->

2024-12-23 16:52 UTC, oncilla approved these changes
> Reviewed 3 of 13 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4673)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2024-12-23 16:52 UTC, oncilla approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4673)* status: all files reviewed, 1 unresolved discussion (waiting on @JordiSubira)



<!-- Sent from Reviewable.io -->

2024-12-24 08:27 UTC, JordiSubira approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 12 of 13 files at r3, 3 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4673#-:-OErlmky71v1TbdLfGtj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)



<!-- Sent from Reviewable.io -->

2024-12-24 08:27 UTC, JordiSubira approved these changes
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4673)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)



<!-- Sent from Reviewable.io -->

2024-12-24 13:37 UTC, lukedirtwalker reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4673)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)



<!-- Sent from Reviewable.io -->

2024-12-24 13:47 UTC, merged